In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_rows', None)

In [120]:
X_train = pd.read_csv('../../../data/processed/for_linear_model/MF,DF/predictors_train_filtered.csv')
X_test = pd.read_csv('../../../data/processed/for_linear_model/MF,DF/predictors_test_filtered.csv')
y_train = pd.read_csv('../../../data/processed/for_linear_model/MF,DF/target_train_filtered_logariphmed.csv')
y_test = pd.read_csv('../../../data/processed/for_linear_model/MF,DF/target_test_filtered_logariphmed.csv')

In [4]:
train_players = pd.read_csv('../../../data/processed/for_linear_model/MF,DF/train_players_names.csv')
test_players = pd.read_csv('../../../data/processed/for_linear_model/MF,DF/test_players_names.csv')

In [5]:
all_cols = X_train.columns
all_cols

Index(['Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
       '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh', 'SoT',
       'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'],
      dtype='object')

## Регрессор

In [122]:
LR_regressor = LinearRegression()
LR_regressor.fit(X_train, y_train)

LinearRegression()

## Предсказанные значения

In [123]:
y_pred_log = LR_regressor.predict(X_test)
y_pred = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

y_train_pred = np.exp(LR_regressor.predict(X_train))
y_train_original = np.exp(y_train)

## Метрики

In [124]:
mae_test = mean_absolute_error(y_test_original, y_pred)
rmse_test = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2_test = r2_score(y_test_original, y_pred)
mape_test = mean_absolute_percentage_error(y_test_original, y_pred)

mae_train = mean_absolute_error(y_train_original, y_train_pred)
rmse_train = np.sqrt(mean_squared_error(y_train_original, y_train_pred))
r2_train = r2_score(y_train_original, y_train_pred)
mape_train = mean_absolute_percentage_error(y_train_original, y_train_pred)

metrics = pd.DataFrame({
    'MAE':[mae_test, mae_train],
    'RMSE':[rmse_test, rmse_train],
    'MAPE':[mape_test, mape_train],
    'R2':[r2_test, r2_train]
}, index = ['test', 'train'])

## Остатки

In [125]:
y_pred = pd.Series(np.reshape(y_pred, len(y_pred)), name='Value_pred')
y_train_pred = pd.Series(np.reshape(y_train_pred, len(y_train_pred)), name='Value_pred')

comp_leftovers_test = pd.concat([test_players, y_pred, y_test_original], axis=1)
comp_leftovers_train = pd.concat([train_players, y_train_pred, y_train_original], axis=1)

## Коэффициенты

In [126]:
coeffs = LR_regressor.coef_[0]
coeffs_df = pd.DataFrame({
    'coeff':coeffs.astype('float')
}, index=X_train.columns)
coeffs_df = coeffs_df.sort_values(by='coeff', key=abs, ascending=False)

# Все переменные

In [15]:
coeffs_df

                   coeff
Min         1.543007e+01
90s        -1.434574e+01
Gls.1       2.157124e+00
G-PK.1     -2.124555e+00
Starts     -1.178213e+00
SoT         7.537068e-01
league_GB1  6.954386e-01
SoT/90     -5.794386e-01
Sh/90       5.585164e-01
league_IT1  4.317019e-01
league_ES1  4.152074e-01
Ast         4.066886e-01
league_L1   4.011630e-01
CrdY       -3.526981e-01
Int         3.071797e-01
Ast.1      -3.064784e-01
Fls         2.708756e-01
G/Sh       -2.666431e-01
Sh         -2.636972e-01
league_PO1  2.566060e-01
SoT%        2.515382e-01
league_FR1  2.108248e-01
MP          2.101519e-01
G+A         2.016560e-01
Crs        -1.900033e-01
G+A.1       1.869195e-01
G+A-PK      1.869195e-01
Age        -1.803847e-01
G/SoT       1.656180e-01
league_RU1  1.583155e-01
Off        -1.389365e-01
G-PK       -1.359524e-01
Gls        -1.359524e-01
CrdR       -9.484281e-02
2CrdY       7.721920e-02
TklW       -2.907803e-02
Fld         2.732485e-02
league_NL1  1.138940e-02
PK         -3.654299e-13
PKatt      -1.611072e-13
OG         -1.831868e-14

In [17]:
metrics

            MAE       RMSE      MAPE        R2
test   4.971850  10.594509  0.780653  0.343797
train  4.600893  11.034440  0.741912  0.637514

# Потенциальные переменные для добавления и удаления

In [106]:
base_cols = ['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Crs',
        'Int', 'Sh', 'CrdY',
        'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']

## Для добавления:

In [108]:
cols_to_add = [col for col in all_cols if not(col in base_cols)]
new_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_add:
    X_train_new = X_train[base_cols + [col]]
    X_test_new = X_test[base_cols + [col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new<mae_test or mape_new<mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=new_cols.columns, index=[col])
        new_cols = pd.concat([new_cols, row])
new_cols

             mae      mape        r2
base    4.606361  0.604399  0.374934
G-PK    4.606262  1.917277 -0.064744
PK      4.606361  1.916851 -0.064762
PKatt   4.606361  1.916851 -0.064762
Gls.1   4.453901  1.956116 -0.033639
Ast.1   4.595683  1.911439 -0.059972
G-PK.1  4.493615  1.954362 -0.050180
Off     4.469131  1.918340 -0.099597
TklW    4.559147  1.839871  0.032167
OG      4.606361  1.916851 -0.064762
Sh/90   4.587693  1.864537 -0.195395
G/Sh    4.524948  1.932450 -0.044627
G/SoT   4.603129  1.857105 -0.035963

## Для удаления:

In [58]:
cols_to_delete = [col for col in base_cols if not(col.startswith('league'))]
del_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_delete:
    X_train_new = X_train[[c for c in base_cols if c != col]]
    X_test_new = X_test[[c for c in base_cols if c != col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new < mae_test or mape_new < mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=del_cols.columns, index=[col])
        del_cols = pd.concat([del_cols, row])
del_cols

             mae      mape        r2
base    4.283921  0.648172  0.418635
CrdY    4.225603  1.914135 -0.526563
Fls     4.256138  1.850532 -0.433993
SoT/90  4.231559  1.755173 -0.145306

# Модель 1

In [18]:
X_train = X_train[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
        'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh',
       'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
        'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh',
       'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [28]:
coeffs_df

                   coeff
Gls.1       2.008133e+00
G-PK.1     -1.695967e+00
league_GB1  6.768671e-01
league_IT1  4.333538e-01
Ast         4.308539e-01
league_ES1  4.115579e-01
SoT/90     -3.680531e-01
Sh/90       3.551342e-01
league_L1   3.543621e-01
Sh          3.074069e-01
SoT%        2.656238e-01
G+A         2.621197e-01
Int         2.423032e-01
league_PO1  2.148002e-01
Crs        -2.098120e-01
league_FR1  2.012641e-01
Age        -1.750765e-01
G/SoT      -1.487741e-01
league_RU1  1.297460e-01
Off        -1.168134e-01
CrdR       -1.134981e-01
90s         8.627778e-02
TklW        7.944587e-02
Gls        -5.072047e-02
G-PK       -5.072047e-02
Ast.1      -4.499636e-02
G+A-PK     -3.340057e-02
G+A.1      -3.340057e-02
league_NL1 -2.291757e-02
Fls        -1.896028e-02
G/Sh       -1.133858e-02
Fld        -9.176650e-03
PK         -6.238066e-15
PKatt      -2.803313e-15
OG          1.110223e-16

In [24]:
metrics

            MAE       RMSE      MAPE        R2
test   5.122085  10.822406  0.744841  0.315262
train  4.665983  10.971170  0.778829  0.641659

In [25]:
comp_leftovers_train

                     Player  Value_pred   Value
0          Ilya Samoshnikov    3.365296    3.50
1         Federico Valverde   88.266096  130.00
2             Janik Haberer    1.768065    2.50
3            Andre Geraldes    0.805551    0.20
4              Mamadou Loum    0.835107    1.20
5           Sergio Carreira    5.786928    4.00
6              Ilnur Alshin    1.152953    0.50
7                 Joe Aribo   10.573374    6.00
8       Edimilson Fernandes    1.484375    3.00
9           Nayel Mehssatou    2.196630    2.20
10             Carlos Gomez    3.349149    4.00
11     Fahem Benaissa Yahia    1.093364    0.40
12            Leonardo Lelo    4.105262    4.00
13           Nair Tiknizyan    1.153824    4.00
14      Roberto Gagliardini    0.756895    1.40
15           Simone Pafundi    2.253091    5.00
16            Mandela Keita    8.669499   12.00
17              Geny Catamo   11.905774   15.00
18           Moises Caicedo   37.919596   90.00
19               Joel silva    2.279470    0.80
20          Malcolm Viltard    1.236772    0.75
21             Diogo Calila    1.469991    1.00
22             Birama Toure    0.681191    0.80
23           Danil Krugovoy    2.127014    2.80
24         Ismael Bekhoucha    0.904206    0.30
25               Lewis Cook   11.480781   15.00
26              Erick Nunes    1.903767    1.20
27          Liberato Cacace   12.194746    3.00
28     Jasper Van Oudenhove    0.429147    0.20
29            Marco Ribeiro    0.600543    0.20
30          Rayan Raveloson    1.530210    2.00
31              Luca Kerber    3.251576    1.50
32            Gabriel Bares    0.435127    0.30
33            Yuri Gorshkov    0.712262    2.00
34        Yannik Engelhardt    3.158277    6.00
35          Jeffrey Schlupp    2.655541    3.00
36             Sergio Gomez    5.094010   20.00
37            Alvaro Tejero    3.957422    1.80
38        Eduardo Camavinga    3.932956   60.00
39              Juan Bernat    1.567391    2.00
40           Robert Andrich    5.525885    9.00
41            Anton Kavaloŭ    0.450059    0.30
42             Javier Munoz    7.585326    2.00
43              Wataru Endo    1.866936    8.00
44            Thomas Partey   31.120694   14.00
45            Boris lambert    0.752933    0.75
46           Michal Sadilek    1.342886    8.00
47                 Khellven    3.943311    5.00
48             Anton Shvets    1.062506    0.80
49            Jonas Hofmann    2.857057    2.00
50          Mohamed Brahimi    0.815776    0.90
51             Roman Zobnin    0.586036    3.00
52               Pathe Ciss    5.848250    2.00
53         Jack Hinshelwood   28.960516   24.00
54        Anouar El Azzouzi    2.540584    1.80
55        Soslan Kagermazov    1.261187    0.70
56            Miodrag Pivas    0.238541    0.25
57             Matheus Dias    2.351332    1.50
58           Joey Pelupessy    0.198450    0.25
59          Marius Courcoul    1.235950    0.30
60              Naci Unuvar    1.806043    2.00
61               David Preu    1.666918    0.40
62          Antonio Sanchez    1.946162    2.50
63              Andu Kelati    2.064148    0.80
64               Joao Neves   37.540201   80.00
65         Guilherme Serrao    0.429977    0.40
66          Patrick Ciurria    1.878327    1.50
67              Nuno Santos    0.731115    9.00
68            Leon Goretzka    7.887151   22.00
69              Samuel Lino   17.923163   22.00
70           Jordan Lotomba    6.500000    6.50
71         Yannick Gerhardt    1.540846    2.50
72             Renato Tapia    3.804009    2.00
73            Adrien Tameze    1.891236    2.00
74        Robbin Weijenberg    0.423029    0.25
75             Louis Leroux    2.956241    4.00
76          Jefferson Lerma   21.411403   10.00
77          Stefan Bajcetic    2.489156    9.00
78           Geovany Quenda    8.020500   45.00
79         Ange Martial Tia    1.120754    0.30
80         Valentin Rongier    3.375463    9.00
81          Loreintz Rosier    1.758575    0.90
82            Julian Chicco    1.586750    0.50
83   Robert-Jan Vanwesemael    0.817363    1.00
84         Peer Koopmeiners    9.017187   10.00
85          Matheus Pereira    1.805347    2.50
86            Mohammed Azzi    1.332633    0.80
87             Dilane Bakwa   31.900839   25.00
88       Leander Dendoncker    2.258130    4.50
89         Iliya Berkovskiy    1.022498    0.40
90               Theo Leoni    0.898408    3.00
91              Anton Stach   17.470147   14.00
92         Manolis Saliakas    3.656839    3.00
93            Salvador Agra    0.712238    0.20
94             Matias Soule   37.719159   30.00
95                    Larra    3.594655    2.00
96             Mario Lemina   18.744767    7.50
97           Marten de Roon   11.819411    5.00
98            Kevin Martins    1.056297    1.40
99        Stephen Eustaquio    1.465036   10.00
100            Lucas Soares    1.156673    1.50
101        Brecht Dejaegere    0.726265    0.50
102            James Garner   10.682118   18.00
103              Adam Kayed    0.618538    0.30
104      Temirkhan Sundukov    2.166083    0.80
105            Pascal Gross   10.916797    5.00
106         Nicolas Seiwald    1.696536   18.00

In [27]:
comp_leftovers_test

                  Player  Value_pred  Value
0            Tomas Perez    0.525894   3.00
1     Warren Zaire-Emery    5.083613  55.00
2           Philipp Treu    4.940622   5.00
3         Desmond Acquah    0.463817   0.30
4         Oscar Mingueza   13.780557  20.00
5       Gabriel Moscardo    1.663593   8.00
6   Aleksandr Sandrachuk    0.780325   0.50
7           Jorthy Mokio    0.569431   8.00
8            James Sands    0.810549   3.00
9          Marvin Schulz    1.045815   0.70
10      Tamas Nikitscher    2.236918   1.00
11        Nemanja Gudelj    9.387414   3.00
12     Abdoulaye Sissako    1.604620   0.70
13        Juanlu Sanchez    8.069267  12.00
14          Curtis Jones   28.719388  45.00
15          Hugo Alvarez    9.281278   7.50
16       Weston McKennie   14.295020  22.00
17           Milan Gajic    0.437917   4.00
18         Pablo Rosario    6.818939   8.00
19         Ansgar Knauff   11.380686  15.00
20            Cher Ndour    1.977719   5.00
21            Denis Odoi    0.941588   0.25
22     Luka Vesner Ticic    1.284659   0.70
23             Jan Djapo    0.781398   0.50
24          Diego Laxalt    0.374153   2.00
25      Reuven Niemeijer    0.412932   0.30
26      Rodrigo Riquelme    2.027125  12.00

# Модель 2

In [35]:
X_train = X_train[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK',
        'CrdR', 'CrdY', 'G+A.1','Fls', 'Fld', 'Off', 'Crs',
        'Int', 'TklW', 'Sh','SoT%', 'Sh/90', 'SoT/90', 'G/Sh',
        'G/SoT', 'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK',
        'CrdR', 'CrdY', 'G+A.1','Fls', 'Fld', 'Off', 'Crs',
        'Int', 'TklW', 'Sh','SoT%', 'Sh/90', 'SoT/90', 'G/Sh',
        'G/SoT', 'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [46]:
coeffs_df

               coeff
league_GB1  0.720543
CrdY       -0.465623
league_ES1  0.441614
league_L1   0.428320
league_IT1  0.423664
Sh          0.412106
Fls         0.372594
SoT%        0.352575
Ast         0.304013
Sh/90       0.299887
SoT/90     -0.295645
league_PO1  0.295140
Int         0.274456
Crs        -0.244607
league_FR1  0.234280
G+A         0.196206
Age        -0.184483
TklW       -0.159921
league_RU1  0.156240
90s         0.136053
G/Sh       -0.112203
league_NL1  0.069942
G/SoT       0.066454
Off        -0.062563
G+A.1       0.052297
Fld         0.030213
CrdR       -0.017598
G-PK       -0.014131
Gls        -0.014131

In [26]:
metrics

            MAE       RMSE      MAPE        R2
test   5.122085  10.822406  0.744841  0.315262
train  4.665983  10.971170  0.778829  0.641659

In [13]:
comp_leftovers_train

                     Player  Value_pred   Value
0          Ilya Samoshnikov    2.618553    3.50
1         Federico Valverde   70.503948  130.00
2             Janik Haberer    2.737228    2.50
3            Andre Geraldes    0.644619    0.20
4              Mamadou Loum    0.896633    1.20
5           Sergio Carreira    7.849105    4.00
6              Ilnur Alshin    1.600620    0.50
7                 Joe Aribo   16.245647    6.00
8       Edimilson Fernandes    1.593523    3.00
9           Nayel Mehssatou    2.174515    2.20
10             Carlos Gomez    1.662629    4.00
11     Fahem Benaissa Yahia    1.491750    0.40
12            Leonardo Lelo    3.615169    4.00
13           Nair Tiknizyan    1.190491    4.00
14      Roberto Gagliardini    0.582902    1.40
15           Simone Pafundi    2.465544    5.00
16            Mandela Keita   10.801072   12.00
17              Geny Catamo   15.254608   15.00
18           Moises Caicedo   27.861790   90.00
19               Joel silva    2.941154    0.80
20          Malcolm Viltard    1.093658    0.75
21             Diogo Calila    1.053058    1.00
22             Birama Toure    0.532709    0.80
23           Danil Krugovoy    2.011162    2.80
24         Ismael Bekhoucha    0.619076    0.30
25               Lewis Cook   12.849806   15.00
26              Erick Nunes    1.483140    1.20
27          Liberato Cacace    8.371155    3.00
28     Jasper Van Oudenhove    0.371150    0.20
29            Marco Ribeiro    0.646333    0.20
30          Rayan Raveloson    1.318564    2.00
31              Luca Kerber    3.071934    1.50
32            Gabriel Bares    0.374422    0.30
33            Yuri Gorshkov    0.958107    2.00
34        Yannik Engelhardt    3.268501    6.00
35          Jeffrey Schlupp    3.888554    3.00
36             Sergio Gomez    4.712187   20.00
37            Alvaro Tejero    4.956980    1.80
38        Eduardo Camavinga    5.487705   60.00
39              Juan Bernat    1.809116    2.00
40           Robert Andrich    5.471796    9.00
41            Anton Kavaloŭ    0.389626    0.30
42             Javier Munoz    6.833824    2.00
43              Wataru Endo    2.377726    8.00
44            Thomas Partey   45.910203   14.00
45            Boris lambert    0.802701    0.75
46           Michal Sadilek    1.717749    8.00
47                 Khellven    3.803412    5.00
48             Anton Shvets    1.042189    0.80
49            Jonas Hofmann    2.148099    2.00
50          Mohamed Brahimi    0.685308    0.90
51             Roman Zobnin    0.596200    3.00
52               Pathe Ciss    3.489611    2.00
53         Jack Hinshelwood   21.122347   24.00
54        Anouar El Azzouzi    2.928556    1.80
55        Soslan Kagermazov    1.089739    0.70
56            Miodrag Pivas    0.266011    0.25
57             Matheus Dias    1.926534    1.50
58           Joey Pelupessy    0.273910    0.25
59          Marius Courcoul    1.520474    0.30
60              Naci Unuvar    1.686995    2.00
61               David Preu    1.369867    0.40
62          Antonio Sanchez    2.205860    2.50
63              Andu Kelati    2.634139    0.80
64               Joao Neves   43.768468   80.00
65         Guilherme Serrao    0.445857    0.40
66          Patrick Ciurria    2.507513    1.50
67              Nuno Santos    0.874515    9.00
68            Leon Goretzka    9.554260   22.00
69              Samuel Lino   19.945030   22.00
70           Jordan Lotomba    1.028738    6.50
71         Yannick Gerhardt    2.105952    2.50
72             Renato Tapia    2.890050    2.00
73            Adrien Tameze    1.504277    2.00
74        Robbin Weijenberg    0.463183    0.25
75             Louis Leroux    2.958259    4.00
76          Jefferson Lerma   17.199300   10.00
77          Stefan Bajcetic    2.665555    9.00
78           Geovany Quenda   10.492051   45.00
79         Ange Martial Tia    1.560354    0.30
80         Valentin Rongier    3.853670    9.00
81          Loreintz Rosier    2.214799    0.90
82            Julian Chicco    2.078033    0.50
83   Robert-Jan Vanwesemael    0.909574    1.00
84         Peer Koopmeiners   14.075423   10.00
85          Matheus Pereira    1.575623    2.50
86            Mohammed Azzi    1.795387    0.80
87             Dilane Bakwa   45.249780   25.00
88       Leander Dendoncker    2.928292    4.50
89         Iliya Berkovskiy    1.436639    0.40
90               Theo Leoni    1.059017    3.00
91              Anton Stach   13.695321   14.00
92         Manolis Saliakas    3.562496    3.00
93            Salvador Agra    0.719197    0.20
94             Matias Soule   28.556678   30.00
95                    Larra    2.685894    2.00
96             Mario Lemina   14.249665    7.50
97           Marten de Roon   17.721398    5.00
98            Kevin Martins    1.174916    1.40
99        Stephen Eustaquio    1.412514   10.00
100            Lucas Soares    1.041569    1.50
101        Brecht Dejaegere    0.723882    0.50
102            James Garner    6.899380   18.00
103              Adam Kayed    0.803358    0.30
104      Temirkhan Sundukov    1.334624    0.80
105            Pascal Gross    6.683384    5.00
106         Nicolas Seiwald    1.919179   18.00

In [14]:
comp_leftovers_test

                  Player  Value_pred  Value
0            Tomas Perez    0.500229   3.00
1     Warren Zaire-Emery    6.643224  55.00
2           Philipp Treu    5.128795   5.00
3         Desmond Acquah    0.387419   0.30
4         Oscar Mingueza   12.219897  20.00
5       Gabriel Moscardo    1.096048   8.00
6   Aleksandr Sandrachuk    0.779859   0.50
7           Jorthy Mokio    0.982916   8.00
8            James Sands    0.901500   3.00
9          Marvin Schulz    0.871458   0.70
10      Tamas Nikitscher    2.965894   1.00
11        Nemanja Gudelj    3.298104   3.00
12     Abdoulaye Sissako    0.956295   0.70
13        Juanlu Sanchez    5.172300  12.00
14          Curtis Jones   42.382760  45.00
15          Hugo Alvarez    7.991253   7.50
16       Weston McKennie   20.596179  22.00
17           Milan Gajic    0.417474   4.00
18         Pablo Rosario    3.172594   8.00
19         Ansgar Knauff   20.201750  15.00
20            Cher Ndour    1.506261   5.00
21            Denis Odoi    0.911050   0.25
22     Luka Vesner Ticic    1.301825   0.70
23             Jan Djapo    1.184609   0.50
24          Diego Laxalt    0.316383   2.00
25      Reuven Niemeijer    0.473691   0.30
26      Rodrigo Riquelme    3.328393  12.00

# Модель 3

In [45]:
X_train = X_train[['Age', '90s', 'Ast', 'G+A',
        'CrdY', 'G+A.1','Fls', 'Fld', 'Off', 'Crs',
        'Int', 'TklW', 'Sh', 'Sh/90', 'SoT/90',
        'G/SoT', 'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Ast', 'G+A',
        'CrdY', 'G+A.1','Fls', 'Fld', 'Off', 'Crs',
        'Int', 'TklW', 'Sh', 'Sh/90', 'SoT/90',
        'G/SoT', 'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [51]:
coeffs_df

               coeff
league_GB1  0.628319
CrdY       -0.409005
90s         0.400346
Ast         0.391792
league_ES1  0.381605
league_IT1  0.377260
league_L1   0.349202
Fls         0.313095
Crs        -0.300863
Sh          0.262610
league_PO1  0.209486
Int         0.207569
Age        -0.202945
Sh/90       0.194489
league_FR1  0.187077
TklW       -0.165203
G+A         0.140249
league_RU1  0.113005
SoT/90      0.053201
Off        -0.049795
G/SoT       0.045371
Fld         0.031535
league_NL1 -0.005379
G+A.1      -0.002973

In [52]:
metrics

            MAE       RMSE      MAPE        R2
test   4.283921   9.972083  0.648172  0.418635
train  4.977076  11.770965  0.848875  0.587509

In [53]:
comp_leftovers_train

                     Player  Value_pred   Value
0          Ilya Samoshnikov    2.965257    3.50
1         Federico Valverde   70.924103  130.00
2             Janik Haberer    2.634147    2.50
3            Andre Geraldes    0.535035    0.20
4              Mamadou Loum    0.918454    1.20
5           Sergio Carreira    8.204141    4.00
6              Ilnur Alshin    1.507998    0.50
7                 Joe Aribo   13.647999    6.00
8       Edimilson Fernandes    1.587880    3.00
9           Nayel Mehssatou    2.580102    2.20
10             Carlos Gomez    2.090387    4.00
11     Fahem Benaissa Yahia    1.171089    0.40
12            Leonardo Lelo    3.532538    4.00
13           Nair Tiknizyan    1.265816    4.00
14      Roberto Gagliardini    0.776924    1.40
15           Simone Pafundi    2.236806    5.00
16            Mandela Keita    5.233299   12.00
17              Geny Catamo   13.673739   15.00
18           Moises Caicedo   37.731594   90.00
19               Joel silva    2.772579    0.80
20          Malcolm Viltard    1.057783    0.75
21             Diogo Calila    1.129050    1.00
22             Birama Toure    0.437140    0.80
23           Danil Krugovoy    2.196498    2.80
24         Ismael Bekhoucha    0.848868    0.30
25               Lewis Cook   13.170719   15.00
26              Erick Nunes    1.621588    1.20
27          Liberato Cacace    8.990658    3.00
28     Jasper Van Oudenhove    0.287906    0.20
29            Marco Ribeiro    0.776946    0.20
30          Rayan Raveloson    1.384016    2.00
31              Luca Kerber    1.957106    1.50
32            Gabriel Bares    0.501979    0.30
33            Yuri Gorshkov    0.727783    2.00
34        Yannik Engelhardt    3.575387    6.00
35          Jeffrey Schlupp    6.630209    3.00
36             Sergio Gomez    3.726851   20.00
37            Alvaro Tejero    4.409318    1.80
38        Eduardo Camavinga    5.431671   60.00
39              Juan Bernat    1.822251    2.00
40           Robert Andrich    5.247081    9.00
41            Anton Kavaloŭ    0.490919    0.30
42             Javier Munoz    8.007528    2.00
43              Wataru Endo    2.554918    8.00
44            Thomas Partey   42.301436   14.00
45            Boris lambert    0.756443    0.75
46           Michal Sadilek    1.523935    8.00
47                 Khellven    3.418529    5.00
48             Anton Shvets    0.934007    0.80
49            Jonas Hofmann    2.401794    2.00
50          Mohamed Brahimi    0.760110    0.90
51             Roman Zobnin    0.635767    3.00
52               Pathe Ciss    4.059330    2.00
53         Jack Hinshelwood   18.927334   24.00
54        Anouar El Azzouzi    3.137283    1.80
55        Soslan Kagermazov    1.181470    0.70
56            Miodrag Pivas    0.329859    0.25
57             Matheus Dias    2.171431    1.50
58           Joey Pelupessy    0.302012    0.25
59          Marius Courcoul    1.250838    0.30
60              Naci Unuvar    1.403895    2.00
61               David Preu    1.379018    0.40
62          Antonio Sanchez    2.314651    2.50
63              Andu Kelati    2.666632    0.80
64               Joao Neves   46.411449   80.00
65         Guilherme Serrao    0.645988    0.40
66          Patrick Ciurria    2.478214    1.50
67              Nuno Santos    0.749633    9.00
68            Leon Goretzka    8.924655   22.00
69              Samuel Lino   22.555321   22.00
70           Jordan Lotomba    0.972555    6.50
71         Yannick Gerhardt    2.173121    2.50
72             Renato Tapia    2.703980    2.00
73            Adrien Tameze    1.200706    2.00
74        Robbin Weijenberg    0.511993    0.25
75             Louis Leroux    2.462863    4.00
76          Jefferson Lerma   14.848120   10.00
77          Stefan Bajcetic    2.355383    9.00
78           Geovany Quenda   10.051937   45.00
79         Ange Martial Tia    1.784824    0.30
80         Valentin Rongier    3.039232    9.00
81          Loreintz Rosier    2.376278    0.90
82            Julian Chicco    1.536734    0.50
83   Robert-Jan Vanwesemael    0.920253    1.00
84         Peer Koopmeiners   13.072466   10.00
85          Matheus Pereira    1.592709    2.50
86            Mohammed Azzi    1.459082    0.80
87             Dilane Bakwa   47.739700   25.00
88       Leander Dendoncker    2.674336    4.50
89         Iliya Berkovskiy    1.413617    0.40
90               Theo Leoni    1.149910    3.00
91              Anton Stach   12.509074   14.00
92         Manolis Saliakas    3.721031    3.00
93            Salvador Agra    0.860333    0.20
94             Matias Soule   30.143844   30.00
95                    Larra    3.120949    2.00
96             Mario Lemina   11.990466    7.50
97           Marten de Roon   25.244636    5.00
98            Kevin Martins    1.438972    1.40
99        Stephen Eustaquio    1.181364   10.00
100            Lucas Soares    0.930478    1.50
101        Brecht Dejaegere    0.741288    0.50
102            James Garner    5.384304   18.00
103              Adam Kayed    0.757068    0.30
104      Temirkhan Sundukov    1.362683    0.80
105            Pascal Gross    7.076562    5.00
106         Nicolas Seiwald    2.942262   18.00

In [54]:
comp_leftovers_test

                  Player  Value_pred  Value
0            Tomas Perez    0.645499   3.00
1     Warren Zaire-Emery    6.533108  55.00
2           Philipp Treu    6.455020   5.00
3         Desmond Acquah    0.419046   0.30
4         Oscar Mingueza   15.074233  20.00
5       Gabriel Moscardo    1.089153   8.00
6   Aleksandr Sandrachuk    0.736784   0.50
7           Jorthy Mokio    0.969667   8.00
8            James Sands    1.126579   3.00
9          Marvin Schulz    0.663359   0.70
10      Tamas Nikitscher    1.625243   1.00
11        Nemanja Gudelj    3.624783   3.00
12     Abdoulaye Sissako    1.021508   0.70
13        Juanlu Sanchez    6.002721  12.00
14          Curtis Jones   42.559917  45.00
15          Hugo Alvarez    9.000679   7.50
16       Weston McKennie   22.975174  22.00
17           Milan Gajic    0.497067   4.00
18         Pablo Rosario    2.890243   8.00
19         Ansgar Knauff   20.435219  15.00
20            Cher Ndour    1.854132   5.00
21            Denis Odoi    0.952311   0.25
22     Luka Vesner Ticic    1.484170   0.70
23             Jan Djapo    1.186345   0.50
24          Diego Laxalt    0.463832   2.00
25      Reuven Niemeijer    0.484892   0.30
26      Rodrigo Riquelme    3.315804  12.00

# Модель 4

In [68]:
X_train = X_train[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Off', 'Crs',
        'Int', 'TklW', 'Sh', 'Sh/90',
        'G/SoT', 'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Off', 'Crs',
        'Int', 'TklW', 'Sh', 'Sh/90',
        'G/SoT', 'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [74]:
coeffs_df

               coeff
league_GB1  0.618371
league_IT1  0.381162
league_ES1  0.377871
Ast         0.349301
league_L1   0.328785
G+A         0.255136
Crs        -0.246523
Sh/90       0.237200
Sh          0.235199
league_FR1  0.207111
Age        -0.199017
90s         0.195211
Int         0.188369
league_PO1  0.155252
league_RU1  0.096398
TklW        0.095668
Off        -0.068227
G/SoT       0.044714
Fls        -0.035960
Fld        -0.022547
G+A.1      -0.017006
league_NL1 -0.012249

In [75]:
metrics

            MAE       RMSE      MAPE        R2
test   4.228028  10.285888  0.686389  0.381471
train  4.676480  10.837535  0.845049  0.650336

In [76]:
comp_leftovers_train

                     Player  Value_pred   Value
0          Ilya Samoshnikov    3.835788    3.50
1         Federico Valverde   85.528953  130.00
2             Janik Haberer    1.710462    2.50
3            Andre Geraldes    0.554349    0.20
4              Mamadou Loum    0.973474    1.20
5           Sergio Carreira    5.479852    4.00
6              Ilnur Alshin    1.177053    0.50
7                 Joe Aribo    9.983952    6.00
8       Edimilson Fernandes    1.451505    3.00
9           Nayel Mehssatou    2.513479    2.20
10             Carlos Gomez    1.956630    4.00
11     Fahem Benaissa Yahia    0.932610    0.40
12            Leonardo Lelo    3.139535    4.00
13           Nair Tiknizyan    1.235558    4.00
14      Roberto Gagliardini    0.777040    1.40
15           Simone Pafundi    2.214798    5.00
16            Mandela Keita    4.651845   12.00
17              Geny Catamo   11.094388   15.00
18           Moises Caicedo   41.079205   90.00
19               Joel silva    2.310375    0.80
20          Malcolm Viltard    1.055883    0.75
21             Diogo Calila    1.480804    1.00
22             Birama Toure    0.610440    0.80
23           Danil Krugovoy    2.031093    2.80
24         Ismael Bekhoucha    1.062268    0.30
25               Lewis Cook   13.836793   15.00
26              Erick Nunes    1.969740    1.20
27          Liberato Cacace   11.279933    3.00
28     Jasper Van Oudenhove    0.355533    0.20
29            Marco Ribeiro    0.630803    0.20
30          Rayan Raveloson    1.636714    2.00
31              Luca Kerber    2.039023    1.50
32            Gabriel Bares    0.567901    0.30
33            Yuri Gorshkov    0.595524    2.00
34        Yannik Engelhardt    3.488677    6.00
35          Jeffrey Schlupp    5.762357    3.00
36             Sergio Gomez    4.061611   20.00
37            Alvaro Tejero    3.736674    1.80
38        Eduardo Camavinga    4.745144   60.00
39              Juan Bernat    1.585466    2.00
40           Robert Andrich    5.625060    9.00
41            Anton Kavaloŭ    0.469329    0.30
42             Javier Munoz    7.334170    2.00
43              Wataru Endo    1.848514    8.00
44            Thomas Partey   30.810863   14.00
45            Boris lambert    1.028830    0.75
46           Michal Sadilek    1.644358    8.00
47                 Khellven    3.435366    5.00
48             Anton Shvets    0.887870    0.80
49            Jonas Hofmann    2.204847    2.00
50          Mohamed Brahimi    0.931170    0.90
51             Roman Zobnin    0.769991    3.00
52               Pathe Ciss    6.911118    2.00
53         Jack Hinshelwood   24.922766   24.00
54        Anouar El Azzouzi    3.004964    1.80
55        Soslan Kagermazov    1.409399    0.70
56            Miodrag Pivas    0.323584    0.25
57             Matheus Dias    1.988720    1.50
58           Joey Pelupessy    0.292601    0.25
59          Marius Courcoul    1.184816    0.30
60              Naci Unuvar    1.900251    2.00
61               David Preu    1.590405    0.40
62          Antonio Sanchez    1.872204    2.50
63              Andu Kelati    2.888250    0.80
64               Joao Neves   41.092316   80.00
65         Guilherme Serrao    0.667799    0.40
66          Patrick Ciurria    2.085543    1.50
67              Nuno Santos    0.616685    9.00
68            Leon Goretzka    7.521296   22.00
69              Samuel Lino   21.533642   22.00
70           Jordan Lotomba    0.839386    6.50
71         Yannick Gerhardt    2.261378    2.50
72             Renato Tapia    3.014679    2.00
73            Adrien Tameze    1.388315    2.00
74        Robbin Weijenberg    0.512618    0.25
75             Louis Leroux    2.679876    4.00
76          Jefferson Lerma   14.581630   10.00
77          Stefan Bajcetic    2.417182    9.00
78           Geovany Quenda    7.291159   45.00
79         Ange Martial Tia    1.721809    0.30
80         Valentin Rongier    3.037339    9.00
81          Loreintz Rosier    2.463549    0.90
82            Julian Chicco    1.576331    0.50
83   Robert-Jan Vanwesemael    0.854559    1.00
84         Peer Koopmeiners    8.398333   10.00
85          Matheus Pereira    2.151987    2.50
86            Mohammed Azzi    1.233705    0.80
87             Dilane Bakwa   33.945089   25.00
88       Leander Dendoncker    2.266220    4.50
89         Iliya Berkovskiy    0.975492    0.40
90               Theo Leoni    0.992474    3.00
91              Anton Stach   14.751786   14.00
92         Manolis Saliakas    3.991601    3.00
93            Salvador Agra    0.999818    0.20
94             Matias Soule   34.610560   30.00
95                    Larra    5.121597    2.00
96             Mario Lemina   16.968930    7.50
97           Marten de Roon   18.789912    5.00
98            Kevin Martins    1.605766    1.40
99        Stephen Eustaquio    1.104439   10.00
100            Lucas Soares    1.221805    1.50
101        Brecht Dejaegere    0.748266    0.50
102            James Garner    7.677603   18.00
103              Adam Kayed    0.727424    0.30
104      Temirkhan Sundukov    1.937504    0.80
105            Pascal Gross   10.989907    5.00
106         Nicolas Seiwald    2.053398   18.00

In [77]:
comp_leftovers_test

                  Player  Value_pred  Value
0            Tomas Perez    0.585302   3.00
1     Warren Zaire-Emery    5.137166  55.00
2           Philipp Treu    4.770309   5.00
3         Desmond Acquah    0.485517   0.30
4         Oscar Mingueza   19.901207  20.00
5       Gabriel Moscardo    1.540249   8.00
6   Aleksandr Sandrachuk    0.720507   0.50
7           Jorthy Mokio    1.019275   8.00
8            James Sands    0.952952   3.00
9          Marvin Schulz    0.862646   0.70
10      Tamas Nikitscher    1.277293   1.00
11        Nemanja Gudelj    3.841898   3.00
12     Abdoulaye Sissako    1.628536   0.70
13        Juanlu Sanchez   12.461288  12.00
14          Curtis Jones   38.994788  45.00
15          Hugo Alvarez   10.118363   7.50
16       Weston McKennie   12.469426  22.00
17           Milan Gajic    0.418903   4.00
18         Pablo Rosario    3.666374   8.00
19         Ansgar Knauff   14.596602  15.00
20            Cher Ndour    1.846012   5.00
21            Denis Odoi    1.134301   0.25
22     Luka Vesner Ticic    1.157616   0.70
23             Jan Djapo    1.297063   0.50
24          Diego Laxalt    0.412224   2.00
25      Reuven Niemeijer    0.546469   0.30
26      Rodrigo Riquelme    2.613956  12.00

# Модель 5

In [86]:
X_train = X_train[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Off', 'Crs',
        'Int', 'TklW', 'Sh', 'Sh/90', 'CrdY',
        'G/SoT', 'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Off', 'Crs',
        'Int', 'TklW', 'Sh', 'Sh/90', 'CrdY',
        'G/SoT', 'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [92]:
coeffs_df

               coeff
league_GB1  0.627912
90s         0.409147
CrdY       -0.405187
league_ES1  0.376781
Ast         0.375582
league_IT1  0.373878
league_L1   0.342837
Fls         0.307631
Crs        -0.297349
Sh          0.245874
Sh/90       0.238024
Int         0.204814
Age        -0.204444
league_PO1  0.202626
league_FR1  0.188033
TklW       -0.161459
G+A         0.155389
league_RU1  0.105287
Off        -0.055181
G/SoT       0.042724
Fld         0.032478
league_NL1 -0.017437
G+A.1       0.013547

In [93]:
metrics

            MAE       RMSE      MAPE        R2
test   4.231559   9.943165  0.648996  0.422002
train  4.982563  11.810597  0.847874  0.584727

In [94]:
comp_leftovers_train

                     Player  Value_pred   Value
0          Ilya Samoshnikov    3.040318    3.50
1         Federico Valverde   69.178032  130.00
2             Janik Haberer    2.602067    2.50
3            Andre Geraldes    0.531200    0.20
4              Mamadou Loum    0.954562    1.20
5           Sergio Carreira    8.200330    4.00
6              Ilnur Alshin    1.521022    0.50
7                 Joe Aribo   13.784577    6.00
8       Edimilson Fernandes    1.629517    3.00
9           Nayel Mehssatou    2.525121    2.20
10             Carlos Gomez    2.076597    4.00
11     Fahem Benaissa Yahia    1.154789    0.40
12            Leonardo Lelo    3.535418    4.00
13           Nair Tiknizyan    1.259168    4.00
14      Roberto Gagliardini    0.768255    1.40
15           Simone Pafundi    2.123300    5.00
16            Mandela Keita    5.118108   12.00
17              Geny Catamo   13.757153   15.00
18           Moises Caicedo   38.934588   90.00
19               Joel silva    2.742589    0.80
20          Malcolm Viltard    1.072339    0.75
21             Diogo Calila    1.124587    1.00
22             Birama Toure    0.439480    0.80
23           Danil Krugovoy    2.182286    2.80
24         Ismael Bekhoucha    0.841349    0.30
25               Lewis Cook   13.378710   15.00
26              Erick Nunes    1.644125    1.20
27          Liberato Cacace    8.968113    3.00
28     Jasper Van Oudenhove    0.281050    0.20
29            Marco Ribeiro    0.789569    0.20
30          Rayan Raveloson    1.411441    2.00
31              Luca Kerber    1.875464    1.50
32            Gabriel Bares    0.504893    0.30
33            Yuri Gorshkov    0.724300    2.00
34        Yannik Engelhardt    3.614670    6.00
35          Jeffrey Schlupp    5.971755    3.00
36             Sergio Gomez    3.645497   20.00
37            Alvaro Tejero    4.546616    1.80
38        Eduardo Camavinga    5.517124   60.00
39              Juan Bernat    1.850533    2.00
40           Robert Andrich    5.311727    9.00
41            Anton Kavaloŭ    0.503203    0.30
42             Javier Munoz    8.014650    2.00
43              Wataru Endo    2.543580    8.00
44            Thomas Partey   42.948213   14.00
45            Boris lambert    0.734116    0.75
46           Michal Sadilek    1.509220    8.00
47                 Khellven    3.352977    5.00
48             Anton Shvets    0.928443    0.80
49            Jonas Hofmann    2.325770    2.00
50          Mohamed Brahimi    0.757038    0.90
51             Roman Zobnin    0.636818    3.00
52               Pathe Ciss    4.142026    2.00
53         Jack Hinshelwood   19.260492   24.00
54        Anouar El Azzouzi    3.116007    1.80
55        Soslan Kagermazov    1.182974    0.70
56            Miodrag Pivas    0.317989    0.25
57             Matheus Dias    2.177698    1.50
58           Joey Pelupessy    0.304362    0.25
59          Marius Courcoul    1.258791    0.30
60              Naci Unuvar    1.566286    2.00
61               David Preu    1.485409    0.40
62          Antonio Sanchez    2.340449    2.50
63              Andu Kelati    2.636472    0.80
64               Joao Neves   46.528161   80.00
65         Guilherme Serrao    0.645382    0.40
66          Patrick Ciurria    2.538418    1.50
67              Nuno Santos    0.787743    9.00
68            Leon Goretzka    8.908603   22.00
69              Samuel Lino   21.668999   22.00
70           Jordan Lotomba    0.949703    6.50
71         Yannick Gerhardt    2.161879    2.50
72             Renato Tapia    2.685235    2.00
73            Adrien Tameze    1.166676    2.00
74        Robbin Weijenberg    0.519676    0.25
75             Louis Leroux    2.472407    4.00
76          Jefferson Lerma   14.737056   10.00
77          Stefan Bajcetic    2.341065    9.00
78           Geovany Quenda    9.962872   45.00
79         Ange Martial Tia    1.689005    0.30
80         Valentin Rongier    3.051536    9.00
81          Loreintz Rosier    2.359280    0.90
82            Julian Chicco    1.561033    0.50
83   Robert-Jan Vanwesemael    0.928642    1.00
84         Peer Koopmeiners   12.836295   10.00
85          Matheus Pereira    1.551315    2.50
86            Mohammed Azzi    1.427112    0.80
87             Dilane Bakwa   47.189573   25.00
88       Leander Dendoncker    2.614753    4.50
89         Iliya Berkovskiy    1.431586    0.40
90               Theo Leoni    1.164414    3.00
91              Anton Stach   12.295972   14.00
92         Manolis Saliakas    3.795393    3.00
93            Salvador Agra    0.853522    0.20
94             Matias Soule   30.897624   30.00
95                    Larra    3.172831    2.00
96             Mario Lemina   12.166576    7.50
97           Marten de Roon   25.623913    5.00
98            Kevin Martins    1.501110    1.40
99        Stephen Eustaquio    1.149270   10.00
100            Lucas Soares    0.909485    1.50
101        Brecht Dejaegere    0.755579    0.50
102            James Garner    5.451138   18.00
103              Adam Kayed    0.757220    0.30
104      Temirkhan Sundukov    1.354838    0.80
105            Pascal Gross    7.141868    5.00
106         Nicolas Seiwald    2.963036   18.00

In [95]:
comp_leftovers_test

                  Player  Value_pred  Value
0            Tomas Perez    0.636176   3.00
1     Warren Zaire-Emery    6.540751  55.00
2           Philipp Treu    6.469560   5.00
3         Desmond Acquah    0.426085   0.30
4         Oscar Mingueza   15.356645  20.00
5       Gabriel Moscardo    1.254621   8.00
6   Aleksandr Sandrachuk    0.721872   0.50
7           Jorthy Mokio    0.988178   8.00
8            James Sands    1.117833   3.00
9          Marvin Schulz    0.653479   0.70
10      Tamas Nikitscher    1.599851   1.00
11        Nemanja Gudelj    3.634815   3.00
12     Abdoulaye Sissako    1.042657   0.70
13        Juanlu Sanchez    6.162768  12.00
14          Curtis Jones   42.525723  45.00
15          Hugo Alvarez    9.078149   7.50
16       Weston McKennie   22.796028  22.00
17           Milan Gajic    0.492424   4.00
18         Pablo Rosario    2.908248   8.00
19         Ansgar Knauff   19.744842  15.00
20            Cher Ndour    1.941505   5.00
21            Denis Odoi    0.964461   0.25
22     Luka Vesner Ticic    1.482985   0.70
23             Jan Djapo    1.249121   0.50
24          Diego Laxalt    0.465623   2.00
25      Reuven Niemeijer    0.466699   0.30
26      Rodrigo Riquelme    3.331063  12.00

# Модель 6

In [96]:
X_train = X_train[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Crs',
        'Int', 'Sh', 'CrdY',
        'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Crs',
        'Int', 'Sh', 'CrdY',
        'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [102]:
coeffs_df

               coeff
league_GB1  0.685622
Sh          0.485414
league_IT1  0.416379
league_ES1  0.410039
league_L1   0.405901
CrdY       -0.358037
Crs        -0.293371
Ast         0.291118
Fls         0.245688
league_PO1  0.245375
league_FR1  0.243869
G+A         0.225284
Age        -0.177662
Int         0.171185
90s         0.151764
league_RU1  0.139070
G+A.1       0.044108
league_NL1  0.038679
Fld        -0.005166

In [103]:
metrics

            MAE       RMSE      MAPE        R2
test   4.606361  10.340092  0.604399  0.374934
train  4.865338  11.395057  0.850999  0.613434

In [104]:
comp_leftovers_train

                     Player  Value_pred   Value
0          Ilya Samoshnikov    3.162465    3.50
1         Federico Valverde   83.526757  130.00
2             Janik Haberer    3.056207    2.50
3            Andre Geraldes    0.549679    0.20
4              Mamadou Loum    0.849636    1.20
5           Sergio Carreira    7.650201    4.00
6              Ilnur Alshin    1.427921    0.50
7                 Joe Aribo   15.129429    6.00
8       Edimilson Fernandes    1.602753    3.00
9           Nayel Mehssatou    2.244166    2.20
10             Carlos Gomez    1.806396    4.00
11     Fahem Benaissa Yahia    1.058289    0.40
12            Leonardo Lelo    3.010570    4.00
13           Nair Tiknizyan    1.254646    4.00
14      Roberto Gagliardini    1.046574    1.40
15           Simone Pafundi    1.719691    5.00
16            Mandela Keita    4.258170   12.00
17              Geny Catamo   14.593709   15.00
18           Moises Caicedo   35.167686   90.00
19               Joel silva    3.093278    0.80
20          Malcolm Viltard    1.036828    0.75
21             Diogo Calila    1.217811    1.00
22             Birama Toure    0.507142    0.80
23           Danil Krugovoy    1.934232    2.80
24         Ismael Bekhoucha    1.096806    0.30
25               Lewis Cook   12.204658   15.00
26              Erick Nunes    1.912346    1.20
27          Liberato Cacace    9.990971    3.00
28     Jasper Van Oudenhove    0.274901    0.20
29            Marco Ribeiro    0.866824    0.20
30          Rayan Raveloson    1.188123    2.00
31              Luca Kerber    2.140633    1.50
32            Gabriel Bares    0.737757    0.30
33            Yuri Gorshkov    0.759671    2.00
34        Yannik Engelhardt    3.370777    6.00
35          Jeffrey Schlupp    2.891144    3.00
36             Sergio Gomez    4.053990   20.00
37            Alvaro Tejero    3.630779    1.80
38        Eduardo Camavinga    5.142075   60.00
39              Juan Bernat    2.169717    2.00
40           Robert Andrich    4.917576    9.00
41            Anton Kavaloŭ    0.517861    0.30
42             Javier Munoz    7.390522    2.00
43              Wataru Endo    3.599579    8.00
44            Thomas Partey   47.867589   14.00
45            Boris lambert    0.810290    0.75
46           Michal Sadilek    1.467548    8.00
47                 Khellven    3.390350    5.00
48             Anton Shvets    0.855093    0.80
49            Jonas Hofmann    1.930728    2.00
50          Mohamed Brahimi    0.887027    0.90
51             Roman Zobnin    0.579990    3.00
52               Pathe Ciss    3.707622    2.00
53         Jack Hinshelwood   20.520620   24.00
54        Anouar El Azzouzi    3.403775    1.80
55        Soslan Kagermazov    1.192444    0.70
56            Miodrag Pivas    0.446904    0.25
57             Matheus Dias    2.013336    1.50
58           Joey Pelupessy    0.417972    0.25
59          Marius Courcoul    1.245631    0.30
60              Naci Unuvar    0.824921    2.00
61               David Preu    1.339093    0.40
62          Antonio Sanchez    2.371008    2.50
63              Andu Kelati    2.294283    0.80
64               Joao Neves   48.287049   80.00
65         Guilherme Serrao    0.741531    0.40
66          Patrick Ciurria    2.472320    1.50
67              Nuno Santos    0.614952    9.00
68            Leon Goretzka    8.655198   22.00
69              Samuel Lino   21.361668   22.00
70           Jordan Lotomba    0.855012    6.50
71         Yannick Gerhardt    2.313787    2.50
72             Renato Tapia    2.363843    2.00
73            Adrien Tameze    1.181490    2.00
74        Robbin Weijenberg    0.588207    0.25
75             Louis Leroux    2.647205    4.00
76          Jefferson Lerma   12.845694   10.00
77          Stefan Bajcetic    2.134735    9.00
78           Geovany Quenda    9.298175   45.00
79         Ange Martial Tia    1.186455    0.30
80         Valentin Rongier    3.227993    9.00
81          Loreintz Rosier    2.122479    0.90
82            Julian Chicco    1.655465    0.50
83   Robert-Jan Vanwesemael    0.858284    1.00
84         Peer Koopmeiners   12.827243   10.00
85          Matheus Pereira    1.640347    2.50
86            Mohammed Azzi    1.521127    0.80
87             Dilane Bakwa   47.557793   25.00
88       Leander Dendoncker    3.056733    4.50
89         Iliya Berkovskiy    1.328906    0.40
90               Theo Leoni    1.079937    3.00
91              Anton Stach   13.598887   14.00
92         Manolis Saliakas    3.961797    3.00
93            Salvador Agra    0.960150    0.20
94             Matias Soule   30.569990   30.00
95                    Larra    3.343643    2.00
96             Mario Lemina   16.398549    7.50
97           Marten de Roon   19.034030    5.00
98            Kevin Martins    2.171452    1.40
99        Stephen Eustaquio    1.189117   10.00
100            Lucas Soares    0.886229    1.50
101        Brecht Dejaegere    0.771270    0.50
102            James Garner    6.306101   18.00
103              Adam Kayed    0.693592    0.30
104      Temirkhan Sundukov    1.468444    0.80
105            Pascal Gross    7.653161    5.00
106         Nicolas Seiwald    2.849815   18.00

In [105]:
comp_leftovers_test

                  Player  Value_pred  Value
0            Tomas Perez    0.802514   3.00
1     Warren Zaire-Emery    5.942096  55.00
2           Philipp Treu    6.235929   5.00
3         Desmond Acquah    0.395730   0.30
4         Oscar Mingueza   14.081132  20.00
5       Gabriel Moscardo    0.878594   8.00
6   Aleksandr Sandrachuk    0.630826   0.50
7           Jorthy Mokio    0.813257   8.00
8            James Sands    1.448511   3.00
9          Marvin Schulz    0.765004   0.70
10      Tamas Nikitscher    1.612004   1.00
11        Nemanja Gudelj    3.382341   3.00
12     Abdoulaye Sissako    1.096841   0.70
13        Juanlu Sanchez    6.689614  12.00
14          Curtis Jones   46.328627  45.00
15          Hugo Alvarez    8.551490   7.50
16       Weston McKennie   17.611271  22.00
17           Milan Gajic    0.492556   4.00
18         Pablo Rosario    2.958139   8.00
19         Ansgar Knauff   26.859498  15.00
20            Cher Ndour    1.847564   5.00
21            Denis Odoi    0.938226   0.25
22     Luka Vesner Ticic    1.247945   0.70
23             Jan Djapo    0.955721   0.50
24          Diego Laxalt    0.515213   2.00
25      Reuven Niemeijer    0.341805   0.30
26      Rodrigo Riquelme    2.439782  12.00

# Модель 7

In [110]:
X_train = X_train[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Crs',
        'Int', 'Sh', 'CrdY', 'TklW', 'G/SoT',
        'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Crs',
        'Int', 'Sh', 'CrdY', 'TklW', 'G/SoT',
        'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [116]:
coeffs_df

               coeff
league_GB1  0.691533
Sh          0.521531
Ast         0.415302
CrdY       -0.405899
league_IT1  0.398249
league_ES1  0.396696
league_L1   0.394910
Fls         0.326552
Crs        -0.312627
90s         0.245604
league_FR1  0.234332
league_PO1  0.227383
Age        -0.198007
Int         0.174120
TklW       -0.160136
league_RU1  0.138194
G/SoT       0.075336
G+A         0.060638
G+A.1       0.035188
league_NL1  0.022890
Fld        -0.000844

In [117]:
metrics

            MAE       RMSE      MAPE        R2
test   4.550414  10.218123  0.633095  0.389594
train  5.011802  11.887067  0.855382  0.579332

In [118]:
comp_leftovers_train

                     Player  Value_pred   Value
0          Ilya Samoshnikov    3.139587    3.50
1         Federico Valverde   72.433412  130.00
2             Janik Haberer    2.993041    2.50
3            Andre Geraldes    0.534490    0.20
4              Mamadou Loum    0.837587    1.20
5           Sergio Carreira    8.483575    4.00
6              Ilnur Alshin    1.541724    0.50
7                 Joe Aribo   14.872709    6.00
8       Edimilson Fernandes    1.690339    3.00
9           Nayel Mehssatou    2.516180    2.20
10             Carlos Gomez    1.827138    4.00
11     Fahem Benaissa Yahia    1.385535    0.40
12            Leonardo Lelo    2.834031    4.00
13           Nair Tiknizyan    1.323975    4.00
14      Roberto Gagliardini    0.983817    1.40
15           Simone Pafundi    1.644683    5.00
16            Mandela Keita    4.368095   12.00
17              Geny Catamo   14.369159   15.00
18           Moises Caicedo   34.581320   90.00
19               Joel silva    2.716285    0.80
20          Malcolm Viltard    1.003151    0.75
21             Diogo Calila    1.205612    1.00
22             Birama Toure    0.458868    0.80
23           Danil Krugovoy    2.182371    2.80
24         Ismael Bekhoucha    1.060400    0.30
25               Lewis Cook   13.129303   15.00
26              Erick Nunes    1.669111    1.20
27          Liberato Cacace    9.793360    3.00
28     Jasper Van Oudenhove    0.265290    0.20
29            Marco Ribeiro    0.849843    0.20
30          Rayan Raveloson    1.231415    2.00
31              Luca Kerber    2.096416    1.50
32            Gabriel Bares    0.707743    0.30
33            Yuri Gorshkov    0.783081    2.00
34        Yannik Engelhardt    3.806324    6.00
35          Jeffrey Schlupp    2.928860    3.00
36             Sergio Gomez    3.640851   20.00
37            Alvaro Tejero    4.155095    1.80
38        Eduardo Camavinga    5.442660   60.00
39              Juan Bernat    1.980088    2.00
40           Robert Andrich    5.567626    9.00
41            Anton Kavaloŭ    0.529516    0.30
42             Javier Munoz    7.616883    2.00
43              Wataru Endo    3.683585    8.00
44            Thomas Partey   44.659659   14.00
45            Boris lambert    0.826585    0.75
46           Michal Sadilek    1.519750    8.00
47                 Khellven    3.204627    5.00
48             Anton Shvets    0.839529    0.80
49            Jonas Hofmann    1.858805    2.00
50          Mohamed Brahimi    0.769643    0.90
51             Roman Zobnin    0.606665    3.00
52               Pathe Ciss    3.786392    2.00
53         Jack Hinshelwood   20.119558   24.00
54        Anouar El Azzouzi    3.292410    1.80
55        Soslan Kagermazov    1.156878    0.70
56            Miodrag Pivas    0.438632    0.25
57             Matheus Dias    1.923328    1.50
58           Joey Pelupessy    0.382585    0.25
59          Marius Courcoul    1.304251    0.30
60              Naci Unuvar    0.812940    2.00
61               David Preu    1.332024    0.40
62          Antonio Sanchez    2.480129    2.50
63              Andu Kelati    2.293239    0.80
64               Joao Neves   47.204570   80.00
65         Guilherme Serrao    0.693181    0.40
66          Patrick Ciurria    2.668723    1.50
67              Nuno Santos    0.608698    9.00
68            Leon Goretzka    8.620410   22.00
69              Samuel Lino   21.072704   22.00
70           Jordan Lotomba    0.939273    6.50
71         Yannick Gerhardt    2.440706    2.50
72             Renato Tapia    2.268218    2.00
73            Adrien Tameze    1.137715    2.00
74        Robbin Weijenberg    0.551507    0.25
75             Louis Leroux    2.552435    4.00
76          Jefferson Lerma   15.566687   10.00
77          Stefan Bajcetic    2.411298    9.00
78           Geovany Quenda   10.633750   45.00
79         Ange Martial Tia    1.207247    0.30
80         Valentin Rongier    3.083282    9.00
81          Loreintz Rosier    2.265533    0.90
82            Julian Chicco    1.523609    0.50
83   Robert-Jan Vanwesemael    0.918942    1.00
84         Peer Koopmeiners   12.127512   10.00
85          Matheus Pereira    1.691995    2.50
86            Mohammed Azzi    1.466708    0.80
87             Dilane Bakwa   51.662381   25.00
88       Leander Dendoncker    3.099315    4.50
89         Iliya Berkovskiy    1.401927    0.40
90               Theo Leoni    1.145159    3.00
91              Anton Stach   12.799796   14.00
92         Manolis Saliakas    4.108005    3.00
93            Salvador Agra    1.007824    0.20
94             Matias Soule   28.451409   30.00
95                    Larra    3.279674    2.00
96             Mario Lemina   14.843835    7.50
97           Marten de Roon   20.900345    5.00
98            Kevin Martins    2.002497    1.40
99        Stephen Eustaquio    1.139722   10.00
100            Lucas Soares    0.868747    1.50
101        Brecht Dejaegere    0.733270    0.50
102            James Garner    5.829758   18.00
103              Adam Kayed    0.737573    0.30
104      Temirkhan Sundukov    1.313373    0.80
105            Pascal Gross    7.260229    5.00
106         Nicolas Seiwald    2.818546   18.00

In [119]:
comp_leftovers_test

                  Player  Value_pred  Value
0            Tomas Perez    0.796853   3.00
1     Warren Zaire-Emery    6.601790  55.00
2           Philipp Treu    6.060081   5.00
3         Desmond Acquah    0.378087   0.30
4         Oscar Mingueza   13.854026  20.00
5       Gabriel Moscardo    0.869940   8.00
6   Aleksandr Sandrachuk    0.652062   0.50
7           Jorthy Mokio    1.056697   8.00
8            James Sands    1.438282   3.00
9          Marvin Schulz    0.706866   0.70
10      Tamas Nikitscher    1.678671   1.00
11        Nemanja Gudelj    3.313357   3.00
12     Abdoulaye Sissako    0.960505   0.70
13        Juanlu Sanchez    5.693750  12.00
14          Curtis Jones   48.371016  45.00
15          Hugo Alvarez    9.097722   7.50
16       Weston McKennie   22.017022  22.00
17           Milan Gajic    0.545518   4.00
18         Pablo Rosario    2.838222   8.00
19         Ansgar Knauff   26.622625  15.00
20            Cher Ndour    1.882051   5.00
21            Denis Odoi    0.997932   0.25
22     Luka Vesner Ticic    1.461948   0.70
23             Jan Djapo    1.278582   0.50
24          Diego Laxalt    0.494591   2.00
25      Reuven Niemeijer    0.314928   0.30
26      Rodrigo Riquelme    2.528514  12.00

# Модель 8

In [121]:
X_train = X_train[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Crs', 'Off',
        'Int', 'Sh', 'CrdY', 'TklW', 'G/SoT', 'SoT/90',
        'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Ast', 'G+A',
        'G+A.1','Fls', 'Fld', 'Crs', 'Off',
        'Int', 'Sh', 'CrdY', 'TklW', 'G/SoT', 'SoT/90',
        'league_ES1', 'league_FR1','league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [127]:
coeffs_df

               coeff
league_GB1  0.652205
Ast         0.445104
CrdY       -0.418056
Sh          0.405216
league_ES1  0.401035
league_IT1  0.393974
league_L1   0.382905
Fls         0.332998
90s         0.316926
Crs        -0.311276
league_PO1  0.235793
Int         0.202776
league_FR1  0.201357
Age        -0.196689
SoT/90      0.183318
TklW       -0.173109
league_RU1  0.143862
G+A         0.069175
G/SoT       0.063626
league_NL1  0.038730
G+A.1      -0.035279
Off        -0.023151
Fld         0.018312

In [128]:
metrics

            MAE       RMSE      MAPE        R2
test   4.402375  10.113996  0.637125  0.401971
train  5.008232  11.703111  0.853053  0.592251