In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_rows', None)

In [74]:
X_train = pd.read_csv('csv/final_datasets/for_linear_model/MF,FW/predictors_train_filtered.csv')
X_test = pd.read_csv('csv/final_datasets/for_linear_model/MF,FW/predictors_test_filtered.csv')
y_train = pd.read_csv('csv/final_datasets/for_linear_model/MF,FW/target_train_filtered_logariphmed.csv')
y_test = pd.read_csv('csv/final_datasets/for_linear_model/MF,FW/target_test_filtered_logariphmed.csv')

In [16]:
train_players = pd.read_csv('csv/final_datasets/for_linear_model/MF,FW/train_players_names.csv')
test_players = pd.read_csv('csv/final_datasets/for_linear_model/MF,FW/test_players_names.csv')

In [6]:
all_cols = X_train.columns
all_cols

Index(['Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
       '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh', 'SoT',
       'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'],
      dtype='object')

<b>Регрессор</b>

In [92]:
LR_regressor = LinearRegression()
LR_regressor.fit(X_train, y_train)

LinearRegression()

<b>Предсказанные значения</b>

In [93]:
y_pred_log = LR_regressor.predict(X_test)
y_pred = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

y_train_pred = np.exp(LR_regressor.predict(X_train))
y_train_original = np.exp(y_train)

<b>Метрики</b>

In [94]:
mae_test = mean_absolute_error(y_test_original, y_pred)
rmse_test = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2_test = r2_score(y_test_original, y_pred)
mape_test = mean_absolute_percentage_error(y_test_original, y_pred)

mae_train = mean_absolute_error(y_train_original, y_train_pred)
rmse_train = np.sqrt(mean_squared_error(y_train_original, y_train_pred))
r2_train = r2_score(y_train_original, y_train_pred)
mape_train = mean_absolute_percentage_error(y_train_original, y_train_pred)

metrics = pd.DataFrame({
    'MAE':[mae_test, mae_train],
    'RMSE':[rmse_test, rmse_train],
    'MAPE':[mape_test, mape_train],
    'R2':[r2_test, r2_train]
}, index = ['test', 'train'])

<b>Сравнение остатков</b>

In [95]:
y_pred = pd.Series(np.reshape(y_pred, len(y_pred)), name='Value_pred')
y_train_pred = pd.Series(np.reshape(y_train_pred, len(y_train_pred)), name='Value_pred')

comp_leftovers_test = pd.concat([test_players, y_pred, y_test_original], axis=1)
comp_leftovers_train = pd.concat([train_players, y_train_pred, y_train_original], axis=1)

<b>Коэффициенты</b>

In [96]:
coeffs = LR_regressor.coef_[0]
coeffs_df = pd.DataFrame({
    'coeff':coeffs.astype('float')
}, index=X_train.columns)
coeffs_df = coeffs_df.sort_values(by='coeff', key=abs, ascending=False)

<b>Все переменные</b>

In [13]:
coeffs_df

               coeff
Min         4.304878
90s        -4.013622
G-PK.1     -1.929223
Gls.1       1.747549
league_GB1  0.835877
G+A-PK      0.730689
league_L1   0.596664
league_ES1  0.521720
SoT         0.473778
league_IT1  0.454867
league_FR1  0.452985
G/SoT       0.448286
G/Sh       -0.343676
Age        -0.336798
G+A.1      -0.256082
PK         -0.241729
Starts      0.238592
MP         -0.203838
TklW        0.177457
SoT/90     -0.162646
league_RU1  0.155551
Off        -0.142708
league_PO1  0.120523
Crs        -0.100053
Int        -0.086013
SoT%        0.060026
Sh          0.056901
Gls        -0.056451
CrdY       -0.050820
Ast.1       0.039363
G+A        -0.036936
CrdR       -0.035931
Fld         0.027662
2CrdY       0.020046
OG          0.015507
Fls         0.015421
Sh/90      -0.013680
PKatt       0.009394
Ast        -0.002651
league_NL1 -0.002516
G-PK        0.002373

In [14]:
metrics

            MAE       RMSE      MAPE        R2
test   6.262792  12.732324  0.979577  0.054685
train  5.132817  12.021404  0.721469  0.463513

In [19]:
comp_leftovers_test

                            Player  Value_pred  Value
0                  Pedro Goncalves    3.676679  30.00
1                   Dani Rodriguez    3.736283   0.80
2                 Gustavo Klismahn    1.371311   0.60
3                 Zico Buurmeester    1.525448   3.50
4                      Elves Balde    1.025636   0.30
5           Hakon Arnar Haraldsson   10.837656  18.00
6                   Emmanuel Ekong    1.392482   0.55
7                     Simone Verdi    0.587379   1.50
8                     Umut Tohumcu    5.928324   6.00
9                     Ethan Mbappe    1.493469   5.00
10                      Alex Baena   17.402998  55.00
11                    Mikel Merino   20.348181  35.00
12                 Takumi Minamino    6.124098  15.00
13                     Yeremi Pino   11.247124  30.00
14                   Nikola Vlasic    8.287597   8.00
15          Michel-Ange Balikwisha    0.676055   7.00
16                   Calvin Stengs    1.183365   7.00
17                      Manu Bueno   10.135227   1.50
18                   Youssef Maziz    0.820737   1.30
19                  Luis Guilherme    6.683598  15.00
20                     Tom Bischof   40.583119  30.00
21                Malamine Efekele    0.442361   0.40
22                 Luciano Valente    4.600075   7.00
23               Lars Olden Larsen    0.334933   0.50
24                   Coba da Costa    4.838797   3.00
25                  Nichita Motpan    0.627661   0.50
26                    Khalil Fayad    3.339651   3.00
27                  Nikita Ermakov    1.518221   0.60
28                   Romain Faivre    5.620609   6.00
29                    Leonel Bucca    1.463497   0.60
30                    Carles Perez    5.473086   2.00
31                    Ivan Sanchez    1.789032   0.60
32                    Jesus Medina    1.241645   3.00
33                     Enzo Millot   17.574341  35.00
34               Grigoris Kastanos    2.599866   1.50
35                  Ar'jany Martha    0.847806   0.70
36                     Marko Bulat    0.781164   2.00
37                Maksim Samorodov    6.031032   2.50
38                     Mario Gotze    4.045663   4.00
39                     Jaime Pinto    0.399907   0.20
40                       Stoichkov    1.344965   1.50
41                    Yan Diomande   13.624199   1.50
42                           Peque    5.325882   3.50
43                 Jorge Carrascal    3.240356   7.00
44              Mohammed Ihattaren    2.803372   1.00
45                   Ramon Terrats    5.597530   4.00
46                    Kerim Mrabti    0.964264   2.00
47             Gaetano Castrovilli    1.322663   1.50
48  Domingos Andre Ribeiro Almeida    7.740249  10.00
49                   William Gomes    0.738423   9.00
50                    Ole Pohlmann    2.409316   2.50
51                Khoren Bayramyan    0.265521   0.60
52            Charles De Ketelaere   19.416795  35.00
53                    Rodrigo Mora    7.394678  40.00
54                  Bryan Limbombe    0.316409   0.40
55                 Ademola Lookman    8.107243  60.00
56          Matias Fernandez-Pardo   72.113850  15.00
57             Gianluca Prestianni    0.830964   8.00
58                    Carles Alena    4.477768   2.50
59          Oscar Rodriguez Arnaiz    3.641962   2.00
60                      Ado Onaiwu    1.702965   1.50
61                     Amine Talal    0.746619   0.80
62               Christopher Scott    0.333277   0.50
63                       Alan Ruiz    0.712417   0.40
64               Ander Barrenetxea    4.801891  15.00
65                      Jon Guridi    4.484020   3.00
66            Edmond-Paris Maghoma    5.456952   0.80
67                   Dwight McNeil   34.887074  25.00
68                   Drissa Camara    1.454706   1.50
69                   Ricardo Horta    4.814549  12.00

In [20]:
comp_leftovers_train

                         Player  Value_pred    Value
0                Hwang Hee-chan    5.114546   12.000
1                   Pau Cabanes    3.108334    0.800
2                    Unai Gomez    7.460736    6.000
3                 Danila Kozlov    1.150891    2.000
4              Gerard Vandeplas    0.539660    0.400
5                 Shavy Babicka    3.218635    2.500
6                  Nikola Cumic    0.935699    1.500
7                Nicola Sansone    0.467558    0.400
8             Francisco Trincao   35.709630   35.000
9                 Mehdi Merghem    0.422012    0.450
10                 Zeki Amdouni    2.614958   12.000
11                Adnan Januzaj    2.427577    1.200
12             Omari Hutchinson   48.807388   22.000
13                 James Mcatee   17.818502   20.000
14              Paxten Aaronson   11.357774    8.000
15               Kader Ouattara    0.841832    0.800
16                    Kees Smit    1.068916    5.000
17              Connor Metcalfe    2.053637    2.500
18                  Iker Losada    3.419964    1.500
19               Ringo Meerveld    3.576694    3.000
20                 Mahdi Camara   15.045138    9.000
21              Butta Magomedov    0.650656    0.600
22               Reziuan Mirzov    0.799665    0.500
23              Fredrik Aursnes    3.711957   20.000
24             Gianluca Caprari    2.614126    1.000
25            Yaya Kader Fofana    5.329197    4.000
26     Kristian Nokkvi Hlynsson    2.585969    4.000
27                 Miguel Sousa    0.593317    0.500
28                 Edoardo Bove   10.440754    5.000
29                Mattia Felici    5.214623    2.800
30              Yorbe Vertessen    3.521560    6.000
31                Gaetan Perrin   15.440524    8.000
32               Antoine Joujou    2.778899    2.000
33          Juan Manuel Boselli    3.657917    1.200
34            Aleksandr Golovin    3.313055   20.000
35                 Peio Canales    2.468016    1.000
36                Pablo Roberto    0.679306    0.800
37              Braian Mansilla    3.585816    1.800
38               Patrick Wimmer   10.812802   15.000
39                    Raul Moro    8.913860    7.500
40                 Sami Ouaissa    1.911077    1.500
41            Vladislav Sarveli    1.074282    0.900
42                  Merlin Rohl    5.081201   12.000
43             Sebastian Nanasi   12.330934   18.000
44              Jeong Woo-yeong    8.647666    4.000
45                     Can Uzun    9.695714   18.000
46                Dennis Geiger    2.172688    2.000
47                  Moussa Kone    0.375955    0.400
48               Danilo Al Saed    0.444795    0.800
49               Kazeem Olaigbe    4.307252    5.000
50              Samuel Grandsir    1.087383    0.800
51               Alen Halilovic    1.270794    1.000
52                   Luis Rioja    2.923331    2.000
53               Kamory Doumbia    5.891217    4.000
54           Svetoslav Kovachev    0.475604    0.800
55           Junior Dina Ebimbe    4.395825    6.000
56                   Thabo Cele    0.517979    0.350
57                Fabian Rieder    8.795566    6.000
58                  Adrian Beck    6.737077    2.000
59          Nikolai Giorgobiani    0.781628    0.500
60                 Kevin Felida    0.407844    0.200
61                Karim Onisiwo    0.961305    0.800
62                    Chiquinho    1.214462    2.000
63            Nicolas Dominguez   19.662322   18.000
64             Tommaso Baldanzi    3.693537   12.000
65                Chiheb Labidi    0.587614    0.500
66           Alejandro Garnacho   51.979795   45.000
67                 Laszlo Benes    2.685003    3.000
68                Lucas Paqueta   23.610939   28.000
69                   Arda Guler   12.313081   45.000
70             Yari Verschaeren    2.704123    5.000
71               Jamie Leweling    8.133165   20.000
72                        Jofre    9.092654    3.000
73                 Thomas Bruns    0.645100    0.250
74                Takefusa Kubo    7.336359   30.000
75             Teun Koopmeiners    6.836417   35.000
76            Thibaud Verlinden    3.133308    1.700
77                Dylan Mertens    0.711237    0.500
78                Kiryl Zinovic    0.671833    0.400
79                 Amine Gouiri   19.857249   30.000
80            Zakaria Aboukhlal    8.816303   12.000
81           Keano Vanrafelghem    0.589797    0.900
82           Jochem van de Kamp    1.532690    0.800
83              Andrej Kramaric    9.318526    4.000
84           Dehmaine Assoumani    1.264990    0.200
85              Albert Gronbaek   15.801104   11.000
86              Jorg Schreuders    2.333134    1.200
87             Valery Fernandez    0.886278    2.000
88           Yair Mena Palacios    0.344793    0.100
89                  Amad Diallo   65.309037   45.000
90               Casper Staring    0.383498    0.350
91             Mikkel Damsgaard   55.557914   28.000
92             Brandon Aguilera    2.348071    1.500
93              Kevin De Bruyne   15.342239   20.000
94           Babatunde Akinsola    1.627978    0.500
95                 Carlos Forbs    6.886811    8.000
96                 Tidiam Gomis   10.548408    3.000
97                 Jeremie Boga    3.033450   10.000
98                Bilal Bafdili    1.017704    0.900
99           Yaroslav Gladyshev    7.573390    4.000
100                Tomas Suslov    8.491527    6.000
101                 John McGinn   18.444124   16.000
102               Alberto Risco    1.898210    0.200
103               Ola Solbakken    1.847952    2.300
104                  Rui Mendes    0.774760    0.350
105                   Alex Sola    2.115846    2.500
106            Marco van Ginkel    1.031153    0.400
107                Lucas Piazon    1.830173    0.800
108               Alassane Plea    9.172280    5.000
109               Diego Collado    0.474053    0.400
110                      Danilo    6.347300   28.000
111                  Amine Adli    2.784220   18.000
112                Fares Chaibi    7.024118    9.000
113              Florent Mollet    0.579979    1.200
114              Lukas Daschner    3.501561    0.900
115            Aleksei Batrakov    8.412202   12.000
116             James Rodriguez    0.496471    2.500
117                  Rony Lopes    0.810627    2.000
118       Alexis Claude-Maurice   21.681429   12.000
119                 Pablo Torre    5.911047    6.000
120               Pelle Clement    1.084579    0.650
121                     Brenner    6.532861    4.000
122            Arno Verschueren    1.159748    1.500
123          Eliesse Ben Seghir   18.551386   28.000
124                       Anuar    2.293193    0.900
125              Edouard Michut    1.149000    1.800
126              Lechi Sadulaev    2.350083    3.500
127                Sergi Darder    6.686339    4.000
128                  Kodai Sano    2.361774    4.000
129       Isaac Palazon Camacho    7.594564    3.500
130              Thomas Robinet    1.898035    0.400
131                   Lior Kasa    2.401638    1.500
132                 David Costa    1.238554    6.000
133                 Cole Palmer  184.755453  120.000
134                  Joao Graca    1.382804    0.300
135              Olivier Dumont    0.809774    0.400
136                Andre Franco    1.207599    2.500
137               Franck Surdez    2.505321    2.000
138                  Levi Smans    2.464537    2.000
139                         Duk    1.657748    1.000
140            Georginio Rutter   38.332793   32.000
141               Hugo Vetlesen    1.024216    4.000
142      Jean-Ricner Bellegarde   39.352066   18.000
143         Javad Hosseinnezhad    3.068263    0.900
144                  Lucas Vera    2.108470    3.500
145           Aleksandr Rudenko    1.623570    1.000
146                Eberechi Eze   79.057023   55.000
147                  Yann Gboho   22.112948    8.000
148              Martin Terrier    3.714518   17.000
149              Mathieu Cafaro    1.322481    2.500
150              Morten Thorsby    3.619993    3.000
151            Abdelkahar Kadri    2.296541    2.200
152                    John Joe    2.448746    1.200
153           Ezequiel Bullaude    2.616538    2.500
154            Dejan Kulusevski   50.941016   50.000
155                Omari Forson    2.013714    2.000
156               Thiago Almada    6.272260   25.000
157                    Bruninho    1.882528    1.500
158                   Moi Gomez    1.071902    2.000
159       Richard van der Venne    0.451345    0.225
160               Abdou Harroui    5.564196    1.800
161                Sofiane Diop    5.697790   10.000
162               Ivan Oblyakov    4.322386    9.000
163               Ivo Rodrigues    1.158252    1.000
164              Angelo Fulgini    2.118387    5.000
165                   Leo Sauer    6.697471    5.000
166               Theo Bongonda    2.519800    6.000
167                      Arthur    2.024073    3.500
168               Daniel Borges    0.511747    0.400
169             Soren Tengstedt    0.374676    0.800
170  Bruno Xavier Almeida Costa    1.613945    0.500
171                Fermin Lopez   11.437325   50.000
172          Aliou Badara Balde    1.814947    0.800
173                 Arthur Atta    3.657753    8.000
174               Malik Tillman    5.184933   32.000
175                 Nicolas Paz   94.012465   35.000
176              Junior Messias    1.652566    1.500
177                  Pere Milla    1.181632    1.200
178                  Phil Foden   30.393359  100.000
179            Giovani Lo Celso   10.223448   15.000
180            Anton Zinkovskiy    0.903288    2.500
181                 Yunus Musah    5.639102   20.000
182                 Tom Reyners    0.688028    0.800
183              Yassine Kechta    7.469911    5.000
184               Thomas Muller    2.634392    6.000
185              Omri Gandelman    1.866907    4.000
186                Pablo Solari    2.600696    7.000
187         Fisayo Dele-Bashiru    7.346471    7.500
188                Alex Bermejo    0.519571    0.400
189              Sergey Pinyaev    9.300998    8.000
190              Sergio Bermejo    0.554655    0.900
191          Jacob Bruun Larsen    3.089638    5.000
192                 Dani de Wit    3.485558    2.500
193               Matheus Cunha  130.886860   60.000
194              Kenneth Taylor    3.865196   28.000
195                Noah Edjouma    2.844168    0.800
196                Isa Sakamoto    3.247614    2.500
197                Habib Diarra   11.671862   20.000
198                Ludovic Blas   18.739519   18.000
199          Moses David Cobnan    1.830063    0.900
200                Nikola Storm    2.077566    2.000
201           Vladimir Khubulov    1.518901    0.600
202             Hamzat Ojediran    2.660231    1.800
203               Bilal Brahimi    1.084465    1.800
204        Joao Ferreira Barros    0.754854    0.200
205                   Adi Nalic    0.429843    0.350
206                Jens Odgaard   10.306599   12.000
207                 Michel Vlap    2.689008    5.000
208               Chris Fuhrich    8.062616   15.000
209                Yann Karamoh    1.637729    1.800
210          Ruslan Malinovskyi    2.979552    2.500
211              Marcus Edwards    2.388268   12.000
212            Steven Skrzybski    6.978689    1.000
213             Miguel Reisinho    1.005546    0.700
214             Lucas Fernandes    0.519772    1.500
215             Vito van Crooij    2.195316    1.500
216                 Boulaye Dia    9.858835   15.000
217               Conor Chaplin    9.760448    6.000
218               Tjaronn Chery    2.475868    0.500
219                  Remi Oudin    1.194112    1.500
220                 Joe Willock    8.754718   22.000
221               Florian Wirtz   63.977714  140.000
222             Roberto Navarro    4.474089    6.000
223               Dermane Karim    2.209399    3.000
224           Zelimkhan Bakayev    1.342529    2.000
225              Ewan Henderson    1.240403    0.600
226                 Sergi Canos    1.668108    1.000
227            Gianluca Gaetano    6.166798    4.000
228              Valenti­n Vada    1.420335    1.800
229              Samuel Bastien    0.668143    0.650
230              Peter Gonzalez    1.769630    1.200
231               Takuro Kaneko    0.706152    1.500
232                 Jakob Breum    4.651751    5.000
233       Moritz-Broni Kwarteng    1.567274    1.000
234             Mikhail Ignatov    0.383240    1.000
235                        Gavi   29.413918   60.000
236            Roberto Gonzalez    1.132918    1.500
237       Kiernan Dewsbury-Hall   10.581919   20.000
238         Benjamin Rollheiser    3.948157    8.000
239         Pape Daouda Diongue    2.819699    0.800
240                Miguel Baeza    0.943483    0.400
241               Manuel Namora    0.443375    0.100
242          Jean Matteo Bahoya   18.635404   17.000
243          Rajiv van La Parra    0.221364    0.200
244                Cesar Huerta    3.962838    6.000
245                Brajan Gruda   36.912397   25.000
246                Carlos Soler    9.131078   18.000
247                Fabio Vieira    3.324092   22.000
248               Pablo Sarabia    5.936010    5.000
249                Julio Enciso   37.904183   22.000
250            Petter Nosa Dahl    0.853013    0.600
251           Geoffry Hairemans    0.540489    0.500
252                 Eren Dinkci    6.999157    8.000
253                Nathan Tella    6.594289   15.000
254                  Marquinhos    2.535058    6.000
255               Joao Carvalho    3.083870    3.000
256            Nathan Broadhead    6.421733    4.500
257             Patrick Joosten    0.452139    0.275
258              Vasilije Adzic    1.675313    4.000
259                 Kamal Sowah    0.465750    0.800
260                 Paul Wanner   22.561725   18.000
261              Rafael Barbosa    0.338217    0.350
262               Tino Kadewere    2.730086    2.500
263          Badredine Bouanani    9.506871    7.000
264            Felix Lemarechal   11.745528   10.000
265                 Diego Lopez   15.686702   15.000
266               Pablo Fornals    4.260845    6.000
267                 Joao Mendes    1.244536    2.000
268               Fabio Miretti   14.924180   14.000
269               Himad Abdelli    8.547167    7.000
270             Rodrigo Zalazar    5.463533   18.000
271                Jimmy Mari­n    1.694174    0.600
272              Bernardo Silva   29.100200   38.000
273              Ilias Akhomach    4.131318   15.000
274                   Dani Olmo   17.192575   60.000
275            Argyrios Darelas    0.446104    0.250
276               Darwin Machis    1.102148    0.600

<b>Модель 1</b>

In [22]:
X_train = X_train[['G+A', 'G+A.1', 'Sh', 'Ast.1', 'Sh/90', 'SoT/90', '90s', 'Fld', 'G/SoT', 'TklW', 'Crs', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'G+A.1', 'Sh', 'Ast.1', 'Sh/90', 'SoT/90', '90s', 'Fld', 'G/SoT', 'TklW', 'Crs', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [28]:
coeffs_df

               coeff
league_GB1  0.751768
league_L1   0.510106
league_ES1  0.421669
league_FR1  0.411759
league_IT1  0.408176
Age        -0.327147
Sh          0.323125
Ast.1       0.304993
90s         0.266206
G/SoT       0.228467
Crs        -0.120091
TklW        0.108364
league_RU1  0.094803
league_PO1  0.091968
G+A         0.087211
G+A.1      -0.053388
Fld         0.041621
league_NL1 -0.038148
SoT/90     -0.017965
Sh/90       0.004542

In [29]:
metrics

            MAE       RMSE      MAPE        R2
test   4.828872   9.216708  0.867970  0.504649
train  5.497479  12.940978  0.763351  0.378297

In [30]:
comp_leftovers_test

                            Player  Value_pred  Value
0                  Pedro Goncalves    3.521731  30.00
1                   Dani Rodriguez    4.685114   0.80
2                 Gustavo Klismahn    1.341554   0.60
3                 Zico Buurmeester    1.553045   3.50
4                      Elves Balde    1.364235   0.30
5           Hakon Arnar Haraldsson   10.111187  18.00
6                   Emmanuel Ekong    1.736135   0.55
7                     Simone Verdi    0.625940   1.50
8                     Umut Tohumcu    4.919224   6.00
9                     Ethan Mbappe    2.392701   5.00
10                      Alex Baena   22.605465  55.00
11                    Mikel Merino   23.722931  35.00
12                 Takumi Minamino    8.026343  15.00
13                     Yeremi Pino   21.668522  30.00
14                   Nikola Vlasic    8.505964   8.00
15          Michel-Ange Balikwisha    0.999275   7.00
16                   Calvin Stengs    1.197371   7.00
17                      Manu Bueno    4.615398   1.50
18                   Youssef Maziz    1.013611   1.30
19                  Luis Guilherme    6.813080  15.00
20                     Tom Bischof   24.416054  30.00
21                Malamine Efekele    0.491997   0.40
22                 Luciano Valente    4.432240   7.00
23               Lars Olden Larsen    0.319856   0.50
24                   Coba da Costa    3.858561   3.00
25                  Nichita Motpan    0.762091   0.50
26                    Khalil Fayad    3.338295   3.00
27                  Nikita Ermakov    1.282185   0.60
28                   Romain Faivre    3.470176   6.00
29                    Leonel Bucca    1.827496   0.60
30                    Carles Perez    4.192705   2.00
31                    Ivan Sanchez    2.132507   0.60
32                    Jesus Medina    1.194116   3.00
33                     Enzo Millot   18.451859  35.00
34               Grigoris Kastanos    3.440535   1.50
35                  Ar'jany Martha    0.927913   0.70
36                     Marko Bulat    0.914411   2.00
37                Maksim Samorodov    6.426392   2.50
38                     Mario Gotze    4.491304   4.00
39                     Jaime Pinto    0.413703   0.20
40                       Stoichkov    1.634457   1.50
41                    Yan Diomande    9.219772   1.50
42                           Peque    4.905765   3.50
43                 Jorge Carrascal    3.009358   7.00
44              Mohammed Ihattaren    2.056269   1.00
45                   Ramon Terrats    5.421915   4.00
46                    Kerim Mrabti    0.974636   2.00
47             Gaetano Castrovilli    1.508381   1.50
48  Domingos Andre Ribeiro Almeida    5.799587  10.00
49                   William Gomes    0.758782   9.00
50                    Ole Pohlmann    2.067533   2.50
51                Khoren Bayramyan    0.311119   0.60
52            Charles De Ketelaere   18.329245  35.00
53                    Rodrigo Mora    9.416055  40.00
54                  Bryan Limbombe    0.389186   0.40
55                 Ademola Lookman   18.688075  60.00
56          Matias Fernandez-Pardo    9.069460  15.00
57             Gianluca Prestianni    0.944727   8.00
58                    Carles Alena    3.308427   2.50
59          Oscar Rodriguez Arnaiz    6.107549   2.00
60                      Ado Onaiwu    2.603938   1.50
61                     Amine Talal    0.754198   0.80
62               Christopher Scott    0.432249   0.50
63                       Alan Ruiz    0.794037   0.40
64               Ander Barrenetxea    6.109453  15.00
65                      Jon Guridi    3.553123   3.00
66            Edmond-Paris Maghoma    4.368132   0.80
67                   Dwight McNeil   28.244503  25.00
68                   Drissa Camara    2.318987   1.50
69                   Ricardo Horta    3.985476  12.00

In [31]:
comp_leftovers_train

                         Player  Value_pred    Value
0                Hwang Hee-chan    7.237241   12.000
1                   Pau Cabanes    2.968813    0.800
2                    Unai Gomez    6.909523    6.000
3                 Danila Kozlov    1.577470    2.000
4              Gerard Vandeplas    0.526407    0.400
5                 Shavy Babicka    5.364708    2.500
6                  Nikola Cumic    0.959405    1.500
7                Nicola Sansone    0.639685    0.400
8             Francisco Trincao   29.407427   35.000
9                 Mehdi Merghem    0.447434    0.450
10                 Zeki Amdouni    3.027866   12.000
11                Adnan Januzaj    2.192161    1.200
12             Omari Hutchinson   35.936090   22.000
13                 James Mcatee   12.350576   20.000
14              Paxten Aaronson   12.999723    8.000
15               Kader Ouattara    0.831289    0.800
16                    Kees Smit    1.051572    5.000
17              Connor Metcalfe    1.774786    2.500
18                  Iker Losada    2.912007    1.500
19               Ringo Meerveld    2.607933    3.000
20                 Mahdi Camara   12.632551    9.000
21              Butta Magomedov    0.851656    0.600
22               Reziuan Mirzov    0.767892    0.500
23              Fredrik Aursnes    2.596431   20.000
24             Gianluca Caprari    2.630512    1.000
25            Yaya Kader Fofana    4.517107    4.000
26     Kristian Nokkvi Hlynsson    2.102059    4.000
27                 Miguel Sousa    0.742694    0.500
28                 Edoardo Bove    7.465552    5.000
29                Mattia Felici    4.671803    2.800
30              Yorbe Vertessen    3.790343    6.000
31                Gaetan Perrin   17.981843    8.000
32               Antoine Joujou    3.759012    2.000
33          Juan Manuel Boselli    3.653643    1.200
34            Aleksandr Golovin    2.842783   20.000
35                 Peio Canales    1.963205    1.000
36                Pablo Roberto    0.870516    0.800
37              Braian Mansilla    4.309853    1.800
38               Patrick Wimmer   17.337799   15.000
39                    Raul Moro   10.843248    7.500
40                 Sami Ouaissa    2.684875    1.500
41            Vladislav Sarveli    1.296994    0.900
42                  Merlin Rohl    4.004478   12.000
43             Sebastian Nanasi   10.813677   18.000
44              Jeong Woo-yeong    7.844741    4.000
45                     Can Uzun    8.619244   18.000
46                Dennis Geiger    2.022385    2.000
47                  Moussa Kone    0.411185    0.400
48               Danilo Al Saed    0.283306    0.800
49               Kazeem Olaigbe    1.788042    5.000
50              Samuel Grandsir    0.907768    0.800
51               Alen Halilovic    1.118564    1.000
52                   Luis Rioja    4.115592    2.000
53               Kamory Doumbia    7.413403    4.000
54           Svetoslav Kovachev    0.503965    0.800
55           Junior Dina Ebimbe    4.136964    6.000
56                   Thabo Cele    0.418643    0.350
57                Fabian Rieder    8.012258    6.000
58                  Adrian Beck    6.402414    2.000
59          Nikolai Giorgobiani    0.920522    0.500
60                 Kevin Felida    0.350404    0.200
61                Karim Onisiwo    0.820446    0.800
62                    Chiquinho    1.205342    2.000
63            Nicolas Dominguez   15.737553   18.000
64             Tommaso Baldanzi    5.194759   12.000
65                Chiheb Labidi    0.989210    0.500
66           Alejandro Garnacho   66.374399   45.000
67                 Laszlo Benes    3.302779    3.000
68                Lucas Paqueta   29.378686   28.000
69                   Arda Guler   12.188721   45.000
70             Yari Verschaeren    3.159843    5.000
71               Jamie Leweling    6.364340   20.000
72                        Jofre    9.986549    3.000
73                 Thomas Bruns    0.649409    0.250
74                Takefusa Kubo    8.946250   30.000
75             Teun Koopmeiners    6.553457   35.000
76            Thibaud Verlinden    2.647374    1.700
77                Dylan Mertens    0.708894    0.500
78                Kiryl Zinovic    0.984250    0.400
79                 Amine Gouiri   18.514686   30.000
80            Zakaria Aboukhlal    9.364976   12.000
81           Keano Vanrafelghem    0.723180    0.900
82           Jochem van de Kamp    1.522990    0.800
83              Andrej Kramaric   12.489063    4.000
84           Dehmaine Assoumani    1.793630    0.200
85              Albert Gronbaek    4.088385   11.000
86              Jorg Schreuders    2.564548    1.200
87             Valery Fernandez    2.509277    2.000
88           Yair Mena Palacios    0.442105    0.100
89                  Amad Diallo   77.208652   45.000
90               Casper Staring    0.402011    0.350
91             Mikkel Damsgaard   60.717770   28.000
92             Brandon Aguilera    2.547571    1.500
93              Kevin De Bruyne   17.338463   20.000
94           Babatunde Akinsola    2.113033    0.500
95                 Carlos Forbs    6.131396    8.000
96                 Tidiam Gomis   11.245026    3.000
97                 Jeremie Boga    2.921544   10.000
98                Bilal Bafdili    1.365451    0.900
99           Yaroslav Gladyshev    7.527099    4.000
100                Tomas Suslov    8.034912    6.000
101                 John McGinn   19.526900   16.000
102               Alberto Risco    2.079250    0.200
103               Ola Solbakken    1.574946    2.300
104                  Rui Mendes    0.754855    0.350
105                   Alex Sola    2.578533    2.500
106            Marco van Ginkel    0.495704    0.400
107                Lucas Piazon    1.317189    0.800
108               Alassane Plea   10.493115    5.000
109               Diego Collado    0.469323    0.400
110                      Danilo    4.578970   28.000
111                  Amine Adli    3.460258   18.000
112                Fares Chaibi    8.136623    9.000
113              Florent Mollet    0.636148    1.200
114              Lukas Daschner    3.188423    0.900
115            Aleksei Batrakov    8.070729   12.000
116             James Rodriguez    0.556196    2.500
117                  Rony Lopes    0.653402    2.000
118       Alexis Claude-Maurice   17.024717   12.000
119                 Pablo Torre    6.473125    6.000
120               Pelle Clement    1.445023    0.650
121                     Brenner    5.725655    4.000
122            Arno Verschueren    1.510712    1.500
123          Eliesse Ben Seghir   16.730882   28.000
124                       Anuar    3.081568    0.900
125              Edouard Michut    1.059065    1.800
126              Lechi Sadulaev    3.187783    3.500
127                Sergi Darder    5.866925    4.000
128                  Kodai Sano    2.686953    4.000
129       Isaac Palazon Camacho    7.558576    3.500
130              Thomas Robinet    1.897157    0.400
131                   Lior Kasa    2.440092    1.500
132                 David Costa    1.459005    6.000
133                 Cole Palmer  211.951445  120.000
134                  Joao Graca    1.028321    0.300
135              Olivier Dumont    0.765163    0.400
136                Andre Franco    1.157132    2.500
137               Franck Surdez    2.783647    2.000
138                  Levi Smans    2.267031    2.000
139                         Duk    1.285819    1.000
140            Georginio Rutter   48.253791   32.000
141               Hugo Vetlesen    1.268192    4.000
142      Jean-Ricner Bellegarde   38.668965   18.000
143         Javad Hosseinnezhad    3.567925    0.900
144                  Lucas Vera    1.789114    3.500
145           Aleksandr Rudenko    1.897591    1.000
146                Eberechi Eze  101.306719   55.000
147                  Yann Gboho   13.319488    8.000
148              Martin Terrier    3.443716   17.000
149              Mathieu Cafaro    1.666305    2.500
150              Morten Thorsby    3.193340    3.000
151            Abdelkahar Kadri    3.245109    2.200
152                    John Joe    2.634028    1.200
153           Ezequiel Bullaude    2.409203    2.500
154            Dejan Kulusevski   42.384026   50.000
155                Omari Forson    2.057955    2.000
156               Thiago Almada    6.875066   25.000
157                    Bruninho    1.479868    1.500
158                   Moi Gomez    0.998576    2.000
159       Richard van der Venne    0.488490    0.225
160               Abdou Harroui    4.815032    1.800
161                Sofiane Diop    9.810194   10.000
162               Ivan Oblyakov    3.397452    9.000
163               Ivo Rodrigues    1.254235    1.000
164              Angelo Fulgini    2.512437    5.000
165                   Leo Sauer    5.625345    5.000
166               Theo Bongonda    1.936746    6.000
167                      Arthur    1.281544    3.500
168               Daniel Borges    0.650577    0.400
169             Soren Tengstedt    0.403087    0.800
170  Bruno Xavier Almeida Costa    0.867955    0.500
171                Fermin Lopez   15.359945   50.000
172          Aliou Badara Balde    2.060845    0.800
173                 Arthur Atta    4.551943    8.000
174               Malik Tillman    4.870860   32.000
175                 Nicolas Paz   81.897056   35.000
176              Junior Messias    1.610916    1.500
177                  Pere Milla    1.456324    1.200
178                  Phil Foden   28.826337  100.000
179            Giovani Lo Celso    5.421901   15.000
180            Anton Zinkovskiy    0.738510    2.500
181                 Yunus Musah    5.864299   20.000
182                 Tom Reyners    0.756614    0.800
183              Yassine Kechta    7.423105    5.000
184               Thomas Muller    3.098910    6.000
185              Omri Gandelman    2.591475    4.000
186                Pablo Solari    1.191329    7.000
187         Fisayo Dele-Bashiru    5.891669    7.500
188                Alex Bermejo    0.734874    0.400
189              Sergey Pinyaev    8.701855    8.000
190              Sergio Bermejo    0.621658    0.900
191          Jacob Bruun Larsen    4.985203    5.000
192                 Dani de Wit    4.901813    2.500
193               Matheus Cunha  118.156530   60.000
194              Kenneth Taylor    4.638061   28.000
195                Noah Edjouma    3.370133    0.800
196                Isa Sakamoto    2.742426    2.500
197                Habib Diarra   11.348404   20.000
198                Ludovic Blas   14.422278   18.000
199          Moses David Cobnan    2.125498    0.900
200                Nikola Storm    1.655047    2.000
201           Vladimir Khubulov    1.640115    0.600
202             Hamzat Ojediran    3.273805    1.800
203               Bilal Brahimi    1.366492    1.800
204        Joao Ferreira Barros    0.872427    0.200
205                   Adi Nalic    0.494492    0.350
206                Jens Odgaard    8.351745   12.000
207                 Michel Vlap    3.232106    5.000
208               Chris Fuhrich    6.404354   15.000
209                Yann Karamoh    2.613629    1.800
210          Ruslan Malinovskyi    2.825115    2.500
211              Marcus Edwards    1.006613   12.000
212            Steven Skrzybski    5.276521    1.000
213             Miguel Reisinho    1.973944    0.700
214             Lucas Fernandes    0.434012    1.500
215             Vito van Crooij    2.218134    1.500
216                 Boulaye Dia    9.679268   15.000
217               Conor Chaplin    8.453661    6.000
218               Tjaronn Chery    2.104868    0.500
219                  Remi Oudin    1.056578    1.500
220                 Joe Willock   12.518910   22.000
221               Florian Wirtz   61.871409  140.000
222             Roberto Navarro    3.898563    6.000
223               Dermane Karim    1.533454    3.000
224           Zelimkhan Bakayev    1.158551    2.000
225              Ewan Henderson    1.518974    0.600
226                 Sergi Canos    2.047917    1.000
227            Gianluca Gaetano    9.474049    4.000
228              Valenti­n Vada    1.023460    1.800
229              Samuel Bastien    0.566054    0.650
230              Peter Gonzalez    1.939415    1.200
231               Takuro Kaneko    0.601612    1.500
232                 Jakob Breum    5.272558    5.000
233       Moritz-Broni Kwarteng    1.487590    1.000
234             Mikhail Ignatov    0.498892    1.000
235                        Gavi   13.624522   60.000
236            Roberto Gonzalez    0.926969    1.500
237       Kiernan Dewsbury-Hall    8.678448   20.000
238         Benjamin Rollheiser    4.722826    8.000
239         Pape Daouda Diongue    2.342154    0.800
240                Miguel Baeza    1.167441    0.400
241               Manuel Namora    0.403866    0.100
242          Jean Matteo Bahoya   16.318594   17.000
243          Rajiv van La Parra    0.251206    0.200
244                Cesar Huerta    2.559136    6.000
245                Brajan Gruda   32.255273   25.000
246                Carlos Soler    9.178880   18.000
247                Fabio Vieira    3.446210   22.000
248               Pablo Sarabia    7.595788    5.000
249                Julio Enciso   32.260544   22.000
250            Petter Nosa Dahl    1.240939    0.600
251           Geoffry Hairemans    0.678651    0.500
252                 Eren Dinkci    6.353871    8.000
253                Nathan Tella    8.321103   15.000
254                  Marquinhos    4.497001    6.000
255               Joao Carvalho    3.251647    3.000
256            Nathan Broadhead    6.224433    4.500
257             Patrick Joosten    0.494088    0.275
258              Vasilije Adzic    2.040773    4.000
259                 Kamal Sowah    0.510655    0.800
260                 Paul Wanner   14.613355   18.000
261              Rafael Barbosa    0.336206    0.350
262               Tino Kadewere    2.916740    2.500
263          Badredine Bouanani    7.723076    7.000
264            Felix Lemarechal   11.693183   10.000
265                 Diego Lopez   21.254042   15.000
266               Pablo Fornals    3.604531    6.000
267                 Joao Mendes    1.660804    2.000
268               Fabio Miretti   12.752179   14.000
269               Himad Abdelli    9.977957    7.000
270             Rodrigo Zalazar    4.019089   18.000
271                Jimmy Mari­n    1.247930    0.600
272              Bernardo Silva   26.158823   38.000
273              Ilias Akhomach    3.117926   15.000
274                   Dani Olmo    8.243521   60.000
275            Argyrios Darelas    0.393736    0.250
276               Darwin Machis    1.162884    0.600

<b>Модель 2</b>

In [38]:
X_train = X_train[['G+A', 'Sh', 'Ast.1', 'Sh/90', '90s', 'Fld', 'G/SoT', 'TklW', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Sh', 'Ast.1', 'Sh/90', '90s', 'Fld', 'G/SoT', 'TklW', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [44]:
coeffs_df

               coeff
league_GB1  0.775596
league_L1   0.539960
league_IT1  0.438593
league_FR1  0.432594
league_ES1  0.432063
Age        -0.341519
Sh          0.317403
Ast.1       0.270200
G/SoT       0.214043
90s         0.203485
TklW        0.128945
league_PO1  0.114515
league_RU1  0.103651
G+A         0.044823
Fld         0.041921
Sh/90      -0.023026
league_NL1 -0.008729

In [45]:
metrics

            MAE       RMSE      MAPE        R2
test   4.838630   9.025999  0.877333  0.524937
train  5.466847  13.088024  0.768487  0.364089

In [46]:
comp_leftovers_test

                            Player  Value_pred  Value
0                  Pedro Goncalves    3.331164  30.00
1                   Dani Rodriguez    4.789001   0.80
2                 Gustavo Klismahn    1.443584   0.60
3                 Zico Buurmeester    1.535796   3.50
4                      Elves Balde    1.416420   0.30
5           Hakon Arnar Haraldsson   10.142502  18.00
6                   Emmanuel Ekong    1.770281   0.55
7                     Simone Verdi    0.678181   1.50
8                     Umut Tohumcu    5.097386   6.00
9                     Ethan Mbappe    2.402541   5.00
10                      Alex Baena   27.804863  55.00
11                    Mikel Merino   21.781381  35.00
12                 Takumi Minamino    6.730328  15.00
13                     Yeremi Pino   19.868850  30.00
14                   Nikola Vlasic    7.708799   8.00
15          Michel-Ange Balikwisha    1.025017   7.00
16                   Calvin Stengs    1.199724   7.00
17                      Manu Bueno    4.663734   1.50
18                   Youssef Maziz    1.113232   1.30
19                  Luis Guilherme    6.950777  15.00
20                     Tom Bischof   32.825627  30.00
21                Malamine Efekele    0.476806   0.40
22                 Luciano Valente    3.981130   7.00
23               Lars Olden Larsen    0.316164   0.50
24                   Coba da Costa    3.887573   3.00
25                  Nichita Motpan    0.776902   0.50
26                    Khalil Fayad    3.366158   3.00
27                  Nikita Ermakov    1.196872   0.60
28                   Romain Faivre    3.512250   6.00
29                    Leonel Bucca    1.687895   0.60
30                    Carles Perez    4.077521   2.00
31                    Ivan Sanchez    2.551894   0.60
32                    Jesus Medina    1.165911   3.00
33                     Enzo Millot   17.500029  35.00
34               Grigoris Kastanos    3.495752   1.50
35                  Ar'jany Martha    0.874443   0.70
36                     Marko Bulat    1.098279   2.00
37                Maksim Samorodov    5.726586   2.50
38                     Mario Gotze    4.507033   4.00
39                     Jaime Pinto    0.401578   0.20
40                       Stoichkov    1.464961   1.50
41                    Yan Diomande    8.998566   1.50
42                           Peque    4.412587   3.50
43                 Jorge Carrascal    2.888475   7.00
44              Mohammed Ihattaren    2.503542   1.00
45                   Ramon Terrats    5.299780   4.00
46                    Kerim Mrabti    0.865034   2.00
47             Gaetano Castrovilli    1.532707   1.50
48  Domingos Andre Ribeiro Almeida    5.911095  10.00
49                   William Gomes    0.808493   9.00
50                    Ole Pohlmann    2.020372   2.50
51                Khoren Bayramyan    0.301156   0.60
52            Charles De Ketelaere   17.222989  35.00
53                    Rodrigo Mora    8.768803  40.00
54                  Bryan Limbombe    0.394462   0.40
55                 Ademola Lookman   20.807228  60.00
56          Matias Fernandez-Pardo    8.340243  15.00
57             Gianluca Prestianni    0.879268   8.00
58                    Carles Alena    3.116802   2.50
59          Oscar Rodriguez Arnaiz    5.806085   2.00
60                      Ado Onaiwu    2.504615   1.50
61                     Amine Talal    0.681662   0.80
62               Christopher Scott    0.399952   0.50
63                       Alan Ruiz    0.851957   0.40
64               Ander Barrenetxea    6.141232  15.00
65                      Jon Guridi    3.095707   3.00
66            Edmond-Paris Maghoma    4.439839   0.80
67                   Dwight McNeil   32.160937  25.00
68                   Drissa Camara    2.338809   1.50
69                   Ricardo Horta    4.003753  12.00

In [47]:
comp_leftovers_train

                         Player  Value_pred    Value
0                Hwang Hee-chan    7.141220   12.000
1                   Pau Cabanes    3.125264    0.800
2                    Unai Gomez    6.225660    6.000
3                 Danila Kozlov    1.625387    2.000
4              Gerard Vandeplas    0.513498    0.400
5                 Shavy Babicka    5.433185    2.500
6                  Nikola Cumic    0.897488    1.500
7                Nicola Sansone    0.620219    0.400
8             Francisco Trincao   24.345933   35.000
9                 Mehdi Merghem    0.461010    0.450
10                 Zeki Amdouni    2.886580   12.000
11                Adnan Januzaj    2.355151    1.200
12             Omari Hutchinson   37.122886   22.000
13                 James Mcatee   13.361455   20.000
14              Paxten Aaronson   12.796584    8.000
15               Kader Ouattara    0.863410    0.800
16                    Kees Smit    1.043647    5.000
17              Connor Metcalfe    1.817720    2.500
18                  Iker Losada    2.820443    1.500
19               Ringo Meerveld    2.290871    3.000
20                 Mahdi Camara   11.799097    9.000
21              Butta Magomedov    0.828845    0.600
22               Reziuan Mirzov    0.698752    0.500
23              Fredrik Aursnes    2.395601   20.000
24             Gianluca Caprari    2.905573    1.000
25            Yaya Kader Fofana    4.403926    4.000
26     Kristian Nokkvi Hlynsson    2.174379    4.000
27                 Miguel Sousa    0.753054    0.500
28                 Edoardo Bove    7.272887    5.000
29                Mattia Felici    4.863829    2.800
30              Yorbe Vertessen    3.758083    6.000
31                Gaetan Perrin   19.903315    8.000
32               Antoine Joujou    3.859869    2.000
33          Juan Manuel Boselli    3.451054    1.200
34            Aleksandr Golovin    2.831200   20.000
35                 Peio Canales    1.968567    1.000
36                Pablo Roberto    0.846431    0.800
37              Braian Mansilla    4.675702    1.800
38               Patrick Wimmer   17.153648   15.000
39                    Raul Moro   12.491993    7.500
40                 Sami Ouaissa    2.666206    1.500
41            Vladislav Sarveli    1.180234    0.900
42                  Merlin Rohl    3.972713   12.000
43             Sebastian Nanasi   10.586982   18.000
44              Jeong Woo-yeong    7.737874    4.000
45                     Can Uzun    9.135046   18.000
46                Dennis Geiger    2.041451    2.000
47                  Moussa Kone    0.391388    0.400
48               Danilo Al Saed    0.295998    0.800
49               Kazeem Olaigbe    1.797619    5.000
50              Samuel Grandsir    0.931642    0.800
51               Alen Halilovic    1.160950    1.000
52                   Luis Rioja    5.456838    2.000
53               Kamory Doumbia    7.958251    4.000
54           Svetoslav Kovachev    0.462812    0.800
55           Junior Dina Ebimbe    3.937653    6.000
56                   Thabo Cele    0.411148    0.350
57                Fabian Rieder    8.451930    6.000
58                  Adrian Beck    6.182662    2.000
59          Nikolai Giorgobiani    0.953301    0.500
60                 Kevin Felida    0.363658    0.200
61                Karim Onisiwo    0.772562    0.800
62                    Chiquinho    1.183971    2.000
63            Nicolas Dominguez   15.154490   18.000
64             Tommaso Baldanzi    5.019277   12.000
65                Chiheb Labidi    1.020266    0.500
66           Alejandro Garnacho   63.535274   45.000
67                 Laszlo Benes    3.660516    3.000
68                Lucas Paqueta   27.166531   28.000
69                   Arda Guler   12.337068   45.000
70             Yari Verschaeren    3.251829    5.000
71               Jamie Leweling    6.693290   20.000
72                        Jofre    9.193328    3.000
73                 Thomas Bruns    0.787584    0.250
74                Takefusa Kubo    9.131524   30.000
75             Teun Koopmeiners    7.605603   35.000
76            Thibaud Verlinden    3.302310    1.700
77                Dylan Mertens    0.640743    0.500
78                Kiryl Zinovic    0.947713    0.400
79                 Amine Gouiri   17.524987   30.000
80            Zakaria Aboukhlal    8.627616   12.000
81           Keano Vanrafelghem    0.687623    0.900
82           Jochem van de Kamp    1.466902    0.800
83              Andrej Kramaric   12.043556    4.000
84           Dehmaine Assoumani    1.890561    0.200
85              Albert Gronbaek    3.911620   11.000
86              Jorg Schreuders    2.495512    1.200
87             Valery Fernandez    2.665679    2.000
88           Yair Mena Palacios    0.444638    0.100
89                  Amad Diallo   72.779862   45.000
90               Casper Staring    0.413183    0.350
91             Mikkel Damsgaard   70.196773   28.000
92             Brandon Aguilera    2.773202    1.500
93              Kevin De Bruyne   19.877139   20.000
94           Babatunde Akinsola    2.150571    0.500
95                 Carlos Forbs    6.436286    8.000
96                 Tidiam Gomis   10.839174    3.000
97                 Jeremie Boga    2.787481   10.000
98                Bilal Bafdili    1.341937    0.900
99           Yaroslav Gladyshev    6.474831    4.000
100                Tomas Suslov    8.642653    6.000
101                 John McGinn   18.771455   16.000
102               Alberto Risco    1.921916    0.200
103               Ola Solbakken    1.610071    2.300
104                  Rui Mendes    0.746201    0.350
105                   Alex Sola    2.397067    2.500
106            Marco van Ginkel    0.454857    0.400
107                Lucas Piazon    1.452780    0.800
108               Alassane Plea    9.324963    5.000
109               Diego Collado    0.432144    0.400
110                      Danilo    4.720932   28.000
111                  Amine Adli    3.709993   18.000
112                Fares Chaibi    9.058335    9.000
113              Florent Mollet    0.619737    1.200
114              Lukas Daschner    3.411546    0.900
115            Aleksei Batrakov    9.906045   12.000
116             James Rodriguez    0.535172    2.500
117                  Rony Lopes    0.748966    2.000
118       Alexis Claude-Maurice   15.201788   12.000
119                 Pablo Torre    7.139495    6.000
120               Pelle Clement    1.385314    0.650
121                     Brenner    5.926716    4.000
122            Arno Verschueren    1.362347    1.500
123          Eliesse Ben Seghir   16.578559   28.000
124                       Anuar    2.857542    0.900
125              Edouard Michut    1.100608    1.800
126              Lechi Sadulaev    3.787144    3.500
127                Sergi Darder    6.698608    4.000
128                  Kodai Sano    2.467603    4.000
129       Isaac Palazon Camacho    7.718528    3.500
130              Thomas Robinet    1.628362    0.400
131                   Lior Kasa    2.556539    1.500
132                 David Costa    1.458153    6.000
133                 Cole Palmer  215.587474  120.000
134                  Joao Graca    0.972653    0.300
135              Olivier Dumont    0.715299    0.400
136                Andre Franco    1.133664    2.500
137               Franck Surdez    2.535466    2.000
138                  Levi Smans    2.589425    2.000
139                         Duk    1.278680    1.000
140            Georginio Rutter   41.461094   32.000
141               Hugo Vetlesen    1.149091    4.000
142      Jean-Ricner Bellegarde   35.804015   18.000
143         Javad Hosseinnezhad    3.383512    0.900
144                  Lucas Vera    2.133722    3.500
145           Aleksandr Rudenko    1.719183    1.000
146                Eberechi Eze   98.469922   55.000
147                  Yann Gboho   11.643822    8.000
148              Martin Terrier    3.368182   17.000
149              Mathieu Cafaro    1.687656    2.500
150              Morten Thorsby    3.047412    3.000
151            Abdelkahar Kadri    3.709811    2.200
152                    John Joe    2.609238    1.200
153           Ezequiel Bullaude    2.155660    2.500
154            Dejan Kulusevski   42.947295   50.000
155                Omari Forson    2.149265    2.000
156               Thiago Almada    6.761510   25.000
157                    Bruninho    1.388094    1.500
158                   Moi Gomez    0.975077    2.000
159       Richard van der Venne    0.481929    0.225
160               Abdou Harroui    4.657261    1.800
161                Sofiane Diop    9.853532   10.000
162               Ivan Oblyakov    3.744466    9.000
163               Ivo Rodrigues    1.185972    1.000
164              Angelo Fulgini    2.560805    5.000
165                   Leo Sauer    5.925869    5.000
166               Theo Bongonda    1.924374    6.000
167                      Arthur    1.211682    3.500
168               Daniel Borges    0.638015    0.400
169             Soren Tengstedt    0.387993    0.800
170  Bruno Xavier Almeida Costa    0.917319    0.500
171                Fermin Lopez   14.740240   50.000
172          Aliou Badara Balde    2.034615    0.800
173                 Arthur Atta    4.576455    8.000
174               Malik Tillman    4.843964   32.000
175                 Nicolas Paz   70.995074   35.000
176              Junior Messias    1.588800    1.500
177                  Pere Milla    1.459568    1.200
178                  Phil Foden   29.834317  100.000
179            Giovani Lo Celso    6.087193   15.000
180            Anton Zinkovskiy    0.772530    2.500
181                 Yunus Musah    5.835490   20.000
182                 Tom Reyners    0.709209    0.800
183              Yassine Kechta    7.395988    5.000
184               Thomas Muller    2.992546    6.000
185              Omri Gandelman    2.169290    4.000
186                Pablo Solari    1.269983    7.000
187         Fisayo Dele-Bashiru    5.729128    7.500
188                Alex Bermejo    0.747025    0.400
189              Sergey Pinyaev    8.251558    8.000
190              Sergio Bermejo    0.631863    0.900
191          Jacob Bruun Larsen    5.293931    5.000
192                 Dani de Wit    4.713110    2.500
193               Matheus Cunha  129.154961   60.000
194              Kenneth Taylor    4.245917   28.000
195                Noah Edjouma    4.111005    0.800
196                Isa Sakamoto    2.493137    2.500
197                Habib Diarra   10.618409   20.000
198                Ludovic Blas   15.691395   18.000
199          Moses David Cobnan    2.059128    0.900
200                Nikola Storm    1.591173    2.000
201           Vladimir Khubulov    1.710217    0.600
202             Hamzat Ojediran    3.320964    1.800
203               Bilal Brahimi    1.880863    1.800
204        Joao Ferreira Barros    0.895844    0.200
205                   Adi Nalic    0.498595    0.350
206                Jens Odgaard    7.795068   12.000
207                 Michel Vlap    3.639446    5.000
208               Chris Fuhrich    6.799861   15.000
209                Yann Karamoh    2.557383    1.800
210          Ruslan Malinovskyi    2.684766    2.500
211              Marcus Edwards    1.036550   12.000
212            Steven Skrzybski    5.020925    1.000
213             Miguel Reisinho    1.841924    0.700
214             Lucas Fernandes    0.434227    1.500
215             Vito van Crooij    2.214318    1.500
216                 Boulaye Dia    8.069608   15.000
217               Conor Chaplin    7.919714    6.000
218               Tjaronn Chery    2.413388    0.500
219                  Remi Oudin    1.134256    1.500
220                 Joe Willock   12.098369   22.000
221               Florian Wirtz   62.214345  140.000
222             Roberto Navarro    3.871230    6.000
223               Dermane Karim    1.488335    3.000
224           Zelimkhan Bakayev    1.154156    2.000
225              Ewan Henderson    1.695834    0.600
226                 Sergi Canos    1.921108    1.000
227            Gianluca Gaetano    8.902261    4.000
228              Valenti­n Vada    1.051992    1.800
229              Samuel Bastien    0.563791    0.650
230              Peter Gonzalez    1.881907    1.200
231               Takuro Kaneko    0.649188    1.500
232                 Jakob Breum    5.491757    5.000
233       Moritz-Broni Kwarteng    1.431379    1.000
234             Mikhail Ignatov    0.449687    1.000
235                        Gavi   12.244060   60.000
236            Roberto Gonzalez    0.986254    1.500
237       Kiernan Dewsbury-Hall    8.554960   20.000
238         Benjamin Rollheiser    4.876292    8.000
239         Pape Daouda Diongue    2.754024    0.800
240                Miguel Baeza    1.227452    0.400
241               Manuel Namora    0.405026    0.100
242          Jean Matteo Bahoya   16.925563   17.000
243          Rajiv van La Parra    0.229789    0.200
244                Cesar Huerta    2.340825    6.000
245                Brajan Gruda   32.792371   25.000
246                Carlos Soler    9.074612   18.000
247                Fabio Vieira    3.904710   22.000
248               Pablo Sarabia    7.983753    5.000
249                Julio Enciso   32.098565   22.000
250            Petter Nosa Dahl    1.156108    0.600
251           Geoffry Hairemans    0.680573    0.500
252                 Eren Dinkci    6.153853    8.000
253                Nathan Tella    7.893203   15.000
254                  Marquinhos    4.378432    6.000
255               Joao Carvalho    2.960744    3.000
256            Nathan Broadhead    6.329275    4.500
257             Patrick Joosten    0.501540    0.275
258              Vasilije Adzic    2.277362    4.000
259                 Kamal Sowah    0.503214    0.800
260                 Paul Wanner   15.627055   18.000
261              Rafael Barbosa    0.346841    0.350
262               Tino Kadewere    2.829285    2.500
263          Badredine Bouanani    7.670598    7.000
264            Felix Lemarechal   11.095465   10.000
265                 Diego Lopez   18.573447   15.000
266               Pablo Fornals    3.433091    6.000
267                 Joao Mendes    1.720058    2.000
268               Fabio Miretti   13.443063   14.000
269               Himad Abdelli    9.188487    7.000
270             Rodrigo Zalazar    4.182956   18.000
271                Jimmy Mari­n    1.509860    0.600
272              Bernardo Silva   24.892715   38.000
273              Ilias Akhomach    3.100268   15.000
274                   Dani Olmo    7.580662   60.000
275            Argyrios Darelas    0.416626    0.250
276               Darwin Machis    1.212814    0.600

<b>Модель 3</b>

In [52]:
X_train = X_train[['G+A', 'G+A.1', 'Sh', 'Ast.1', 'Sh/90', '90s', 'Fld', 'G/SoT', 'Crs', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'G+A.1', 'Sh', 'Ast.1', 'Sh/90', '90s', 'Fld', 'G/SoT', 'Crs', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [58]:
coeffs_df

               coeff
league_GB1  0.739391
league_L1   0.491097
league_ES1  0.406008
league_FR1  0.401513
league_IT1  0.388880
90s         0.372766
Age        -0.333867
Ast.1       0.325004
Sh          0.311321
G/SoT       0.239976
Crs        -0.138103
league_PO1  0.082617
league_RU1  0.078050
G+A.1      -0.077188
G+A         0.068873
Fld         0.048854
league_NL1 -0.048543
Sh/90      -0.004455

In [59]:
metrics

            MAE       RMSE      MAPE        R2
test   4.914413   9.336048  0.841872  0.491738
train  5.481849  13.122266  0.762994  0.360757

In [60]:
comp_leftovers_test

                            Player  Value_pred  Value
0                  Pedro Goncalves    3.617585  30.00
1                   Dani Rodriguez    4.265362   0.80
2                 Gustavo Klismahn    1.312897   0.60
3                 Zico Buurmeester    1.518145   3.50
4                      Elves Balde    1.424956   0.30
5           Hakon Arnar Haraldsson   10.606293  18.00
6                   Emmanuel Ekong    1.694140   0.55
7                     Simone Verdi    0.627720   1.50
8                     Umut Tohumcu    4.882786   6.00
9                     Ethan Mbappe    2.507677   5.00
10                      Alex Baena   23.284054  55.00
11                    Mikel Merino   20.854829  35.00
12                 Takumi Minamino    8.531590  15.00
13                     Yeremi Pino   19.177102  30.00
14                   Nikola Vlasic    8.848689   8.00
15          Michel-Ange Balikwisha    0.914379   7.00
16                   Calvin Stengs    1.268501   7.00
17                      Manu Bueno    4.517165   1.50
18                   Youssef Maziz    1.110873   1.30
19                  Luis Guilherme    7.030009  15.00
20                     Tom Bischof   17.670612  30.00
21                Malamine Efekele    0.518624   0.40
22                 Luciano Valente    5.356949   7.00
23               Lars Olden Larsen    0.319531   0.50
24                   Coba da Costa    3.773951   3.00
25                  Nichita Motpan    0.698901   0.50
26                    Khalil Fayad    3.277297   3.00
27                  Nikita Ermakov    1.289231   0.60
28                   Romain Faivre    3.473671   6.00
29                    Leonel Bucca    1.839776   0.60
30                    Carles Perez    3.797260   2.00
31                    Ivan Sanchez    1.902773   0.60
32                    Jesus Medina    1.176533   3.00
33                     Enzo Millot   19.470868  35.00
34               Grigoris Kastanos    3.166757   1.50
35                  Ar'jany Martha    0.911755   0.70
36                     Marko Bulat    0.847405   2.00
37                Maksim Samorodov    5.384035   2.50
38                     Mario Gotze    3.978385   4.00
39                     Jaime Pinto    0.411616   0.20
40                       Stoichkov    1.607463   1.50
41                    Yan Diomande    9.113980   1.50
42                           Peque    5.351907   3.50
43                 Jorge Carrascal    2.671461   7.00
44              Mohammed Ihattaren    2.032718   1.00
45                   Ramon Terrats    5.525210   4.00
46                    Kerim Mrabti    0.981412   2.00
47             Gaetano Castrovilli    1.447989   1.50
48  Domingos Andre Ribeiro Almeida    5.241646  10.00
49                   William Gomes    0.745603   9.00
50                    Ole Pohlmann    2.217377   2.50
51                Khoren Bayramyan    0.294307   0.60
52            Charles De Ketelaere   20.295384  35.00
53                    Rodrigo Mora    9.364164  40.00
54                  Bryan Limbombe    0.404004   0.40
55                 Ademola Lookman   17.737775  60.00
56          Matias Fernandez-Pardo   10.066257  15.00
57             Gianluca Prestianni    0.948558   8.00
58                    Carles Alena    3.405221   2.50
59          Oscar Rodriguez Arnaiz    5.845802   2.00
60                      Ado Onaiwu    2.736123   1.50
61                     Amine Talal    0.773616   0.80
62               Christopher Scott    0.447363   0.50
63                       Alan Ruiz    0.775870   0.40
64               Ander Barrenetxea    5.760137  15.00
65                      Jon Guridi    3.567529   3.00
66            Edmond-Paris Maghoma    4.373624   0.80
67                   Dwight McNeil   29.599482  25.00
68                   Drissa Camara    2.267451   1.50
69                   Ricardo Horta    4.164130  12.00

In [61]:
comp_leftovers_train

                         Player  Value_pred    Value
0                Hwang Hee-chan    7.623980   12.000
1                   Pau Cabanes    2.934369    0.800
2                    Unai Gomez    7.481754    6.000
3                 Danila Kozlov    1.579379    2.000
4              Gerard Vandeplas    0.558538    0.400
5                 Shavy Babicka    5.421215    2.500
6                  Nikola Cumic    1.020080    1.500
7                Nicola Sansone    0.631126    0.400
8             Francisco Trincao   29.339394   35.000
9                 Mehdi Merghem    0.413555    0.450
10                 Zeki Amdouni    2.974303   12.000
11                Adnan Januzaj    2.138257    1.200
12             Omari Hutchinson   42.899078   22.000
13                 James Mcatee   12.401808   20.000
14              Paxten Aaronson    8.268260    8.000
15               Kader Ouattara    0.854229    0.800
16                    Kees Smit    1.004884    5.000
17              Connor Metcalfe    1.857216    2.500
18                  Iker Losada    2.841774    1.500
19               Ringo Meerveld    3.314889    3.000
20                 Mahdi Camara   11.089200    9.000
21              Butta Magomedov    0.856291    0.600
22               Reziuan Mirzov    0.791178    0.500
23              Fredrik Aursnes    2.567942   20.000
24             Gianluca Caprari    2.699107    1.000
25            Yaya Kader Fofana    4.509186    4.000
26     Kristian Nokkvi Hlynsson    2.152967    4.000
27                 Miguel Sousa    0.727972    0.500
28                 Edoardo Bove    7.102132    5.000
29                Mattia Felici    4.595484    2.800
30              Yorbe Vertessen    3.835223    6.000
31                Gaetan Perrin   16.931148    8.000
32               Antoine Joujou    3.762264    2.000
33          Juan Manuel Boselli    4.173653    1.200
34            Aleksandr Golovin    2.565759   20.000
35                 Peio Canales    1.962517    1.000
36                Pablo Roberto    0.906475    0.800
37              Braian Mansilla    3.459717    1.800
38               Patrick Wimmer   14.762905   15.000
39                    Raul Moro   11.785038    7.500
40                 Sami Ouaissa    3.101919    1.500
41            Vladislav Sarveli    1.366353    0.900
42                  Merlin Rohl    4.091728   12.000
43             Sebastian Nanasi   12.058021   18.000
44              Jeong Woo-yeong    8.273636    4.000
45                     Can Uzun    8.824871   18.000
46                Dennis Geiger    1.886854    2.000
47                  Moussa Kone    0.425440    0.400
48               Danilo Al Saed    0.282625    0.800
49               Kazeem Olaigbe    1.824142    5.000
50              Samuel Grandsir    0.873902    0.800
51               Alen Halilovic    1.183201    1.000
52                   Luis Rioja    4.320029    2.000
53               Kamory Doumbia    6.418869    4.000
54           Svetoslav Kovachev    0.491546    0.800
55           Junior Dina Ebimbe    4.097266    6.000
56                   Thabo Cele    0.397084    0.350
57                Fabian Rieder    7.505054    6.000
58                  Adrian Beck    6.253827    2.000
59          Nikolai Giorgobiani    0.928717    0.500
60                 Kevin Felida    0.354726    0.200
61                Karim Onisiwo    0.787467    0.800
62                    Chiquinho    1.253286    2.000
63            Nicolas Dominguez   12.324272   18.000
64             Tommaso Baldanzi    5.314537   12.000
65                Chiheb Labidi    0.949770    0.500
66           Alejandro Garnacho   70.894487   45.000
67                 Laszlo Benes    3.301719    3.000
68                Lucas Paqueta   26.911115   28.000
69                   Arda Guler   11.907551   45.000
70             Yari Verschaeren    2.730501    5.000
71               Jamie Leweling    7.164724   20.000
72                        Jofre   10.920216    3.000
73                 Thomas Bruns    0.575897    0.250
74                Takefusa Kubo    9.646716   30.000
75             Teun Koopmeiners    6.464558   35.000
76            Thibaud Verlinden    2.671017    1.700
77                Dylan Mertens    0.693063    0.500
78                Kiryl Zinovic    1.001776    0.400
79                 Amine Gouiri   19.861645   30.000
80            Zakaria Aboukhlal    9.956308   12.000
81           Keano Vanrafelghem    0.767426    0.900
82           Jochem van de Kamp    1.441934    0.800
83              Andrej Kramaric   14.107543    4.000
84           Dehmaine Assoumani    1.847989    0.200
85              Albert Gronbaek    4.172925   11.000
86              Jorg Schreuders    2.543129    1.200
87             Valery Fernandez    2.411729    2.000
88           Yair Mena Palacios    0.440827    0.100
89                  Amad Diallo   67.622042   45.000
90               Casper Staring    0.405527    0.350
91             Mikkel Damsgaard   51.782135   28.000
92             Brandon Aguilera    2.410694    1.500
93              Kevin De Bruyne   17.688934   20.000
94           Babatunde Akinsola    2.163220    0.500
95                 Carlos Forbs    6.022051    8.000
96                 Tidiam Gomis   11.740193    3.000
97                 Jeremie Boga    3.258267   10.000
98                Bilal Bafdili    1.444857    0.900
99           Yaroslav Gladyshev    7.748156    4.000
100                Tomas Suslov    6.886834    6.000
101                 John McGinn   20.128288   16.000
102               Alberto Risco    2.026001    0.200
103               Ola Solbakken    1.657979    2.300
104                  Rui Mendes    0.800968    0.350
105                   Alex Sola    2.562210    2.500
106            Marco van Ginkel    0.497454    0.400
107                Lucas Piazon    1.197720    0.800
108               Alassane Plea   11.709378    5.000
109               Diego Collado    0.456344    0.400
110                      Danilo    4.616536   28.000
111                  Amine Adli    3.354871   18.000
112                Fares Chaibi    7.998107    9.000
113              Florent Mollet    0.643196    1.200
114              Lukas Daschner    3.305304    0.900
115            Aleksei Batrakov    7.879377   12.000
116             James Rodriguez    0.550162    2.500
117                  Rony Lopes    0.657592    2.000
118       Alexis Claude-Maurice   15.898552   12.000
119                 Pablo Torre    6.383845    6.000
120               Pelle Clement    1.483898    0.650
121                     Brenner    5.803736    4.000
122            Arno Verschueren    1.532045    1.500
123          Eliesse Ben Seghir   16.162404   28.000
124                       Anuar    2.916047    0.900
125              Edouard Michut    0.942681    1.800
126              Lechi Sadulaev    3.516584    3.500
127                Sergi Darder    5.848447    4.000
128                  Kodai Sano    2.837658    4.000
129       Isaac Palazon Camacho    7.662403    3.500
130              Thomas Robinet    2.103625    0.400
131                   Lior Kasa    2.463598    1.500
132                 David Costa    1.550966    6.000
133                 Cole Palmer  226.677325  120.000
134                  Joao Graca    1.045905    0.300
135              Olivier Dumont    0.757842    0.400
136                Andre Franco    1.258637    2.500
137               Franck Surdez    2.822741    2.000
138                  Levi Smans    2.504642    2.000
139                         Duk    1.271915    1.000
140            Georginio Rutter   50.528189   32.000
141               Hugo Vetlesen    1.288819    4.000
142      Jean-Ricner Bellegarde   37.595080   18.000
143         Javad Hosseinnezhad    3.495807    0.900
144                  Lucas Vera    1.872945    3.500
145           Aleksandr Rudenko    1.980220    1.000
146                Eberechi Eze  100.985327   55.000
147                  Yann Gboho   14.779845    8.000
148              Martin Terrier    3.551176   17.000
149              Mathieu Cafaro    1.712220    2.500
150              Morten Thorsby    2.977810    3.000
151            Abdelkahar Kadri    3.055580    2.200
152                    John Joe    2.456767    1.200
153           Ezequiel Bullaude    2.417982    2.500
154            Dejan Kulusevski   43.736223   50.000
155                Omari Forson    2.005243    2.000
156               Thiago Almada    7.038259   25.000
157                    Bruninho    1.528488    1.500
158                   Moi Gomez    0.980462    2.000
159       Richard van der Venne    0.494049    0.225
160               Abdou Harroui    4.741053    1.800
161                Sofiane Diop    9.168544   10.000
162               Ivan Oblyakov    3.088322    9.000
163               Ivo Rodrigues    1.237834    1.000
164              Angelo Fulgini    2.579790    5.000
165                   Leo Sauer    5.628620    5.000
166               Theo Bongonda    1.883037    6.000
167                      Arthur    1.317524    3.500
168               Daniel Borges    0.627773    0.400
169             Soren Tengstedt    0.400848    0.800
170  Bruno Xavier Almeida Costa    0.924457    0.500
171                Fermin Lopez   14.871557   50.000
172          Aliou Badara Balde    2.041872    0.800
173                 Arthur Atta    4.690682    8.000
174               Malik Tillman    3.892607   32.000
175                 Nicolas Paz   75.459709   35.000
176              Junior Messias    1.607767    1.500
177                  Pere Milla    1.458429    1.200
178                  Phil Foden   32.117383  100.000
179            Giovani Lo Celso    4.911694   15.000
180            Anton Zinkovskiy    0.704184    2.500
181                 Yunus Musah    5.795631   20.000
182                 Tom Reyners    0.777314    0.800
183              Yassine Kechta    6.643530    5.000
184               Thomas Muller    3.246988    6.000
185              Omri Gandelman    2.515042    4.000
186                Pablo Solari    1.127170    7.000
187         Fisayo Dele-Bashiru    6.032162    7.500
188                Alex Bermejo    0.745128    0.400
189              Sergey Pinyaev    9.435494    8.000
190              Sergio Bermejo    0.644456    0.900
191          Jacob Bruun Larsen    5.131626    5.000
192                 Dani de Wit    4.613362    2.500
193               Matheus Cunha  112.112066   60.000
194              Kenneth Taylor    4.918890   28.000
195                Noah Edjouma    3.335827    0.800
196                Isa Sakamoto    2.838878    2.500
197                Habib Diarra   13.657674   20.000
198                Ludovic Blas   13.996988   18.000
199          Moses David Cobnan    2.126905    0.900
200                Nikola Storm    1.753632    2.000
201           Vladimir Khubulov    1.482258    0.600
202             Hamzat Ojediran    2.992186    1.800
203               Bilal Brahimi    1.478313    1.800
204        Joao Ferreira Barros    0.846406    0.200
205                   Adi Nalic    0.491646    0.350
206                Jens Odgaard    8.949648   12.000
207                 Michel Vlap    2.996076    5.000
208               Chris Fuhrich    6.912485   15.000
209                Yann Karamoh    2.824949    1.800
210          Ruslan Malinovskyi    2.655238    2.500
211              Marcus Edwards    0.998156   12.000
212            Steven Skrzybski    5.379996    1.000
213             Miguel Reisinho    1.957575    0.700
214             Lucas Fernandes    0.455031    1.500
215             Vito van Crooij    2.228739    1.500
216                 Boulaye Dia   10.873981   15.000
217               Conor Chaplin    8.920232    6.000
218               Tjaronn Chery    2.028600    0.500
219                  Remi Oudin    1.051034    1.500
220                 Joe Willock   11.860289   22.000
221               Florian Wirtz   59.417731  140.000
222             Roberto Navarro    3.628329    6.000
223               Dermane Karim    1.306552    3.000
224           Zelimkhan Bakayev    1.183716    2.000
225              Ewan Henderson    1.483579    0.600
226                 Sergi Canos    1.987780    1.000
227            Gianluca Gaetano    9.516294    4.000
228              Valenti­n Vada    1.026630    1.800
229              Samuel Bastien    0.592561    0.650
230              Peter Gonzalez    1.940711    1.200
231               Takuro Kaneko    0.592546    1.500
232                 Jakob Breum    5.587455    5.000
233       Moritz-Broni Kwarteng    1.429589    1.000
234             Mikhail Ignatov    0.498167    1.000
235                        Gavi   12.899522   60.000
236            Roberto Gonzalez    0.961921    1.500
237       Kiernan Dewsbury-Hall    8.659096   20.000
238         Benjamin Rollheiser    4.910559    8.000
239         Pape Daouda Diongue    2.304024    0.800
240                Miguel Baeza    1.206821    0.400
241               Manuel Namora    0.423919    0.100
242          Jean Matteo Bahoya   15.045356   17.000
243          Rajiv van La Parra    0.250587    0.200
244                Cesar Huerta    2.600175    6.000
245                Brajan Gruda   33.184671   25.000
246                Carlos Soler    9.689492   18.000
247                Fabio Vieira    3.286727   22.000
248               Pablo Sarabia    7.464690    5.000
249                Julio Enciso   34.163193   22.000
250            Petter Nosa Dahl    1.256093    0.600
251           Geoffry Hairemans    0.654818    0.500
252                 Eren Dinkci    6.300823    8.000
253                Nathan Tella    8.659446   15.000
254                  Marquinhos    4.549406    6.000
255               Joao Carvalho    3.428864    3.000
256            Nathan Broadhead    6.568431    4.500
257             Patrick Joosten    0.521935    0.275
258              Vasilije Adzic    2.129925    4.000
259                 Kamal Sowah    0.495308    0.800
260                 Paul Wanner   13.218800   18.000
261              Rafael Barbosa    0.348205    0.350
262               Tino Kadewere    2.908776    2.500
263          Badredine Bouanani    8.597400    7.000
264            Felix Lemarechal   11.094337   10.000
265                 Diego Lopez   23.688814   15.000
266               Pablo Fornals    3.875070    6.000
267                 Joao Mendes    1.596328    2.000
268               Fabio Miretti   13.203099   14.000
269               Himad Abdelli   10.024586    7.000
270             Rodrigo Zalazar    3.849088   18.000
271                Jimmy Mari­n    1.277187    0.600
272              Bernardo Silva   24.677525   38.000
273              Ilias Akhomach    3.093719   15.000
274                   Dani Olmo    7.915129   60.000
275            Argyrios Darelas    0.403454    0.250
276               Darwin Machis    1.154976    0.600

<b>Модель 4</b>

In [62]:
X_train = X_train[['G+A', 'G+A.1', 'Ast.1', 'Sh/90', '90s', 'Fld', 'G/SoT', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'G+A.1', 'Ast.1', 'Sh/90', '90s', 'Fld', 'G/SoT', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [68]:
coeffs_df

               coeff
league_GB1  0.745626
league_L1   0.480961
90s         0.443726
league_IT1  0.392746
league_FR1  0.386713
league_ES1  0.372358
Age        -0.351727
Ast.1       0.290474
G/SoT       0.219604
G+A         0.173204
Sh/90       0.084388
league_PO1  0.072795
G+A.1      -0.068697
Fld         0.068522
league_RU1  0.052310
league_NL1 -0.049094

In [69]:
metrics

            MAE       RMSE      MAPE        R2
test   4.868575   9.109763  0.848586  0.516078
train  5.125910  11.648225  0.788811  0.496305

In [70]:
comp_leftovers_test

                            Player  Value_pred  Value
0                  Pedro Goncalves    3.543022  30.00
1                   Dani Rodriguez    5.100796   0.80
2                 Gustavo Klismahn    1.433737   0.60
3                 Zico Buurmeester    1.495277   3.50
4                      Elves Balde    1.461662   0.30
5           Hakon Arnar Haraldsson   10.972044  18.00
6                   Emmanuel Ekong    1.831694   0.55
7                     Simone Verdi    0.662893   1.50
8                     Umut Tohumcu    4.653413   6.00
9                     Ethan Mbappe    3.161541   5.00
10                      Alex Baena   29.886491  55.00
11                    Mikel Merino   19.235150  35.00
12                 Takumi Minamino    6.284323  15.00
13                     Yeremi Pino   19.598288  30.00
14                   Nikola Vlasic    9.040261   8.00
15          Michel-Ange Balikwisha    0.844635   7.00
16                   Calvin Stengs    1.284906   7.00
17                      Manu Bueno    4.418754   1.50
18                   Youssef Maziz    1.130661   1.30
19                  Luis Guilherme    8.336119  15.00
20                     Tom Bischof   21.496847  30.00
21                Malamine Efekele    0.500337   0.40
22                 Luciano Valente    4.886748   7.00
23               Lars Olden Larsen    0.331323   0.50
24                   Coba da Costa    3.512214   3.00
25                  Nichita Motpan    0.697191   0.50
26                    Khalil Fayad    3.168600   3.00
27                  Nikita Ermakov    1.178229   0.60
28                   Romain Faivre    3.488932   6.00
29                    Leonel Bucca    1.674947   0.60
30                    Carles Perez    3.197431   2.00
31                    Ivan Sanchez    2.370789   0.60
32                    Jesus Medina    1.132278   3.00
33                     Enzo Millot   18.816738  35.00
34               Grigoris Kastanos    3.154232   1.50
35                  Ar'jany Martha    0.902094   0.70
36                     Marko Bulat    0.999579   2.00
37                Maksim Samorodov    4.139268   2.50
38                     Mario Gotze    4.287437   4.00
39                     Jaime Pinto    0.413322   0.20
40                       Stoichkov    1.392817   1.50
41                    Yan Diomande    8.499883   1.50
42                           Peque    4.651121   3.50
43                 Jorge Carrascal    2.579299   7.00
44              Mohammed Ihattaren    2.246068   1.00
45                   Ramon Terrats    5.384696   4.00
46                    Kerim Mrabti    0.936855   2.00
47             Gaetano Castrovilli    1.452172   1.50
48  Domingos Andre Ribeiro Almeida    5.814687  10.00
49                   William Gomes    0.818740   9.00
50                    Ole Pohlmann    2.285833   2.50
51                Khoren Bayramyan    0.272026   0.60
52            Charles De Ketelaere   21.495943  35.00
53                    Rodrigo Mora    9.100888  40.00
54                  Bryan Limbombe    0.443686   0.40
55                 Ademola Lookman   18.671871  60.00
56          Matias Fernandez-Pardo   10.019314  15.00
57             Gianluca Prestianni    1.140616   8.00
58                    Carles Alena    3.178575   2.50
59          Oscar Rodriguez Arnaiz    5.254493   2.00
60                      Ado Onaiwu    2.511989   1.50
61                     Amine Talal    0.663522   0.80
62               Christopher Scott    0.472198   0.50
63                       Alan Ruiz    0.869991   0.40
64               Ander Barrenetxea    5.470776  15.00
65                      Jon Guridi    3.093485   3.00
66            Edmond-Paris Maghoma    4.422062   0.80
67                   Dwight McNeil   40.345274  25.00
68                   Drissa Camara    2.457804   1.50
69                   Ricardo Horta    4.963139  12.00

In [71]:
comp_leftovers_train

                         Player  Value_pred    Value
0                Hwang Hee-chan    7.471218   12.000
1                   Pau Cabanes    2.900548    0.800
2                    Unai Gomez    6.750610    6.000
3                 Danila Kozlov    1.525404    2.000
4              Gerard Vandeplas    0.523412    0.400
5                 Shavy Babicka    5.622375    2.500
6                  Nikola Cumic    0.886108    1.500
7                Nicola Sansone    0.815571    0.400
8             Francisco Trincao   20.784443   35.000
9                 Mehdi Merghem    0.428204    0.450
10                 Zeki Amdouni    2.827121   12.000
11                Adnan Januzaj    2.290411    1.200
12             Omari Hutchinson   46.590205   22.000
13                 James Mcatee   14.365921   20.000
14              Paxten Aaronson    7.386316    8.000
15               Kader Ouattara    1.042362    0.800
16                    Kees Smit    0.942127    5.000
17              Connor Metcalfe    1.840504    2.500
18                  Iker Losada    2.527803    1.500
19               Ringo Meerveld    3.580838    3.000
20                 Mahdi Camara    9.911383    9.000
21              Butta Magomedov    0.799216    0.600
22               Reziuan Mirzov    0.701045    0.500
23              Fredrik Aursnes    2.686819   20.000
24             Gianluca Caprari    3.161709    1.000
25            Yaya Kader Fofana    4.266693    4.000
26     Kristian Nokkvi Hlynsson    2.224278    4.000
27                 Miguel Sousa    0.722077    0.500
28                 Edoardo Bove    6.930278    5.000
29                Mattia Felici    4.835467    2.800
30              Yorbe Vertessen    3.782489    6.000
31                Gaetan Perrin   23.263243    8.000
32               Antoine Joujou    3.849322    2.000
33          Juan Manuel Boselli    4.015928    1.200
34            Aleksandr Golovin    2.377955   20.000
35                 Peio Canales    1.879460    1.000
36                Pablo Roberto    0.843172    0.800
37              Braian Mansilla    2.696414    1.800
38               Patrick Wimmer   13.571469   15.000
39                    Raul Moro   14.021608    7.500
40                 Sami Ouaissa    3.414263    1.500
41            Vladislav Sarveli    1.215050    0.900
42                  Merlin Rohl    3.952370   12.000
43             Sebastian Nanasi   13.967269   18.000
44              Jeong Woo-yeong    8.058952    4.000
45                     Can Uzun    9.373845   18.000
46                Dennis Geiger    1.781958    2.000
47                  Moussa Kone    0.434976    0.400
48               Danilo Al Saed    0.267895    0.800
49               Kazeem Olaigbe    2.049011    5.000
50              Samuel Grandsir    0.763500    0.800
51               Alen Halilovic    1.154369    1.000
52                   Luis Rioja    7.341250    2.000
53               Kamory Doumbia    6.789762    4.000
54           Svetoslav Kovachev    0.455740    0.800
55           Junior Dina Ebimbe    4.116585    6.000
56                   Thabo Cele    0.363202    0.350
57                Fabian Rieder    7.660524    6.000
58                  Adrian Beck    5.377482    2.000
59          Nikolai Giorgobiani    0.941573    0.500
60                 Kevin Felida    0.352880    0.200
61                Karim Onisiwo    0.824388    0.800
62                    Chiquinho    1.282520    2.000
63            Nicolas Dominguez   11.611239   18.000
64             Tommaso Baldanzi    5.128081   12.000
65                Chiheb Labidi    0.889712    0.500
66           Alejandro Garnacho   50.174391   45.000
67                 Laszlo Benes    3.651569    3.000
68                Lucas Paqueta   24.882130   28.000
69                   Arda Guler   11.280173   45.000
70             Yari Verschaeren    2.917202    5.000
71               Jamie Leweling    7.422083   20.000
72                        Jofre   10.056094    3.000
73                 Thomas Bruns    0.714091    0.250
74                Takefusa Kubo    9.725769   30.000
75             Teun Koopmeiners    7.326458   35.000
76            Thibaud Verlinden    2.900629    1.700
77                Dylan Mertens    0.569347    0.500
78                Kiryl Zinovic    0.964704    0.400
79                 Amine Gouiri   16.178319   30.000
80            Zakaria Aboukhlal    7.546888   12.000
81           Keano Vanrafelghem    0.803067    0.900
82           Jochem van de Kamp    1.471099    0.800
83              Andrej Kramaric   14.890328    4.000
84           Dehmaine Assoumani    2.119457    0.200
85              Albert Gronbaek    3.974861   11.000
86              Jorg Schreuders    2.736955    1.200
87             Valery Fernandez    2.140692    2.000
88           Yair Mena Palacios    0.434670    0.100
89                  Amad Diallo   69.515663   45.000
90               Casper Staring    0.397296    0.350
91             Mikkel Damsgaard   81.885943   28.000
92             Brandon Aguilera    2.647653    1.500
93              Kevin De Bruyne   20.337864   20.000
94           Babatunde Akinsola    2.153404    0.500
95                 Carlos Forbs    6.247473    8.000
96                 Tidiam Gomis   12.085041    3.000
97                 Jeremie Boga    2.875417   10.000
98                Bilal Bafdili    1.498991    0.900
99           Yaroslav Gladyshev    6.087667    4.000
100                Tomas Suslov    7.171733    6.000
101                 John McGinn   22.415426   16.000
102               Alberto Risco    2.725456    0.200
103               Ola Solbakken    1.643775    2.300
104                  Rui Mendes    0.764634    0.350
105                   Alex Sola    2.302859    2.500
106            Marco van Ginkel    0.457272    0.400
107                Lucas Piazon    1.411158    0.800
108               Alassane Plea   11.887895    5.000
109               Diego Collado    0.575563    0.400
110                      Danilo    4.441469   28.000
111                  Amine Adli    3.437262   18.000
112                Fares Chaibi    8.723142    9.000
113              Florent Mollet    0.653921    1.200
114              Lukas Daschner    3.345024    0.900
115            Aleksei Batrakov   14.256686   12.000
116             James Rodriguez    0.552204    2.500
117                  Rony Lopes    0.702451    2.000
118       Alexis Claude-Maurice   12.569545   12.000
119                 Pablo Torre    6.074650    6.000
120               Pelle Clement    1.595698    0.650
121                     Brenner    5.726073    4.000
122            Arno Verschueren    1.113608    1.500
123          Eliesse Ben Seghir   13.984359   28.000
124                       Anuar    2.832512    0.900
125              Edouard Michut    0.953261    1.800
126              Lechi Sadulaev    4.339589    3.500
127                Sergi Darder    7.767822    4.000
128                  Kodai Sano    2.717169    4.000
129       Isaac Palazon Camacho    6.806089    3.500
130              Thomas Robinet    1.601802    0.400
131                   Lior Kasa    2.703255    1.500
132                 David Costa    1.615052    6.000
133                 Cole Palmer  176.839883  120.000
134                  Joao Graca    0.925784    0.300
135              Olivier Dumont    0.780571    0.400
136                Andre Franco    1.161642    2.500
137               Franck Surdez    2.863461    2.000
138                  Levi Smans    2.734211    2.000
139                         Duk    1.179006    1.000
140            Georginio Rutter   42.249511   32.000
141               Hugo Vetlesen    1.103757    4.000
142      Jean-Ricner Bellegarde   42.561336   18.000
143         Javad Hosseinnezhad    3.290023    0.900
144                  Lucas Vera    2.891969    3.500
145           Aleksandr Rudenko    1.693559    1.000
146                Eberechi Eze   76.749935   55.000
147                  Yann Gboho   12.727852    8.000
148              Martin Terrier    3.399393   17.000
149              Mathieu Cafaro    1.670826    2.500
150              Morten Thorsby    2.914010    3.000
151            Abdelkahar Kadri    3.359592    2.200
152                    John Joe    2.375916    1.200
153           Ezequiel Bullaude    2.134959    2.500
154            Dejan Kulusevski   49.879438   50.000
155                Omari Forson    2.238309    2.000
156               Thiago Almada    6.976563   25.000
157                    Bruninho    1.524740    1.500
158                   Moi Gomez    0.898095    2.000
159       Richard van der Venne    0.483544    0.225
160               Abdou Harroui    4.761353    1.800
161                Sofiane Diop    9.593640   10.000
162               Ivan Oblyakov    3.639351    9.000
163               Ivo Rodrigues    1.251645    1.000
164              Angelo Fulgini    2.513985    5.000
165                   Leo Sauer    5.225202    5.000
166               Theo Bongonda    1.707828    6.000
167                      Arthur    1.250715    3.500
168               Daniel Borges    0.653573    0.400
169             Soren Tengstedt    0.416374    0.800
170  Bruno Xavier Almeida Costa    1.023374    0.500
171                Fermin Lopez   13.946915   50.000
172          Aliou Badara Balde    2.575667    0.800
173                 Arthur Atta    4.474289    8.000
174               Malik Tillman    3.617897   32.000
175                 Nicolas Paz   40.681322   35.000
176              Junior Messias    1.573342    1.500
177                  Pere Milla    1.384464    1.200
178                  Phil Foden   32.933691  100.000
179            Giovani Lo Celso    5.904979   15.000
180            Anton Zinkovskiy    0.698922    2.500
181                 Yunus Musah    5.764960   20.000
182                 Tom Reyners    0.770573    0.800
183              Yassine Kechta    6.281240    5.000
184               Thomas Muller    2.988263    6.000
185              Omri Gandelman    2.092012    4.000
186                Pablo Solari    1.380621    7.000
187         Fisayo Dele-Bashiru    5.839929    7.500
188                Alex Bermejo    0.762904    0.400
189              Sergey Pinyaev    8.045465    8.000
190              Sergio Bermejo    0.615791    0.900
191          Jacob Bruun Larsen    5.286843    5.000
192                 Dani de Wit    4.154150    2.500
193               Matheus Cunha  101.069820   60.000
194              Kenneth Taylor    5.315994   28.000
195                Noah Edjouma    3.768995    0.800
196                Isa Sakamoto    2.282172    2.500
197                Habib Diarra   16.221909   20.000
198                Ludovic Blas   16.058245   18.000
199          Moses David Cobnan    2.056528    0.900
200                Nikola Storm    1.239606    2.000
201           Vladimir Khubulov    1.511641    0.600
202             Hamzat Ojediran    2.954538    1.800
203               Bilal Brahimi    1.910275    1.800
204        Joao Ferreira Barros    0.900993    0.200
205                   Adi Nalic    0.486985    0.350
206                Jens Odgaard    7.769258   12.000
207                 Michel Vlap    3.579005    5.000
208               Chris Fuhrich    7.083834   15.000
209                Yann Karamoh    2.679857    1.800
210          Ruslan Malinovskyi    2.500584    2.500
211              Marcus Edwards    1.179211   12.000
212            Steven Skrzybski    5.131450    1.000
213             Miguel Reisinho    1.755437    0.700
214             Lucas Fernandes    0.435109    1.500
215             Vito van Crooij    2.698106    1.500
216                 Boulaye Dia   10.181400   15.000
217               Conor Chaplin    8.526825    6.000
218               Tjaronn Chery    1.851069    0.500
219                  Remi Oudin    1.094985    1.500
220                 Joe Willock   11.646578   22.000
221               Florian Wirtz   60.202742  140.000
222             Roberto Navarro    3.346482    6.000
223               Dermane Karim    1.229983    3.000
224           Zelimkhan Bakayev    1.166190    2.000
225              Ewan Henderson    1.642926    0.600
226                 Sergi Canos    1.890886    1.000
227            Gianluca Gaetano    9.035492    4.000
228              Valenti­n Vada    1.055558    1.800
229              Samuel Bastien    0.622610    0.650
230              Peter Gonzalez    1.856608    1.200
231               Takuro Kaneko    0.697713    1.500
232                 Jakob Breum    6.129253    5.000
233       Moritz-Broni Kwarteng    1.579421    1.000
234             Mikhail Ignatov    0.532678    1.000
235                        Gavi   11.011485   60.000
236            Roberto Gonzalez    1.009443    1.500
237       Kiernan Dewsbury-Hall    7.940841   20.000
238         Benjamin Rollheiser    4.063500    8.000
239         Pape Daouda Diongue    3.408713    0.800
240                Miguel Baeza    1.117538    0.400
241               Manuel Namora    0.404192    0.100
242          Jean Matteo Bahoya   15.353514   17.000
243          Rajiv van La Parra    0.226727    0.200
244                Cesar Huerta    2.326154    6.000
245                Brajan Gruda   35.361087   25.000
246                Carlos Soler    9.611359   18.000
247                Fabio Vieira    3.666324   22.000
248               Pablo Sarabia    8.188286    5.000
249                Julio Enciso   31.190570   22.000
250            Petter Nosa Dahl    1.306989    0.600
251           Geoffry Hairemans    0.721948    0.500
252                 Eren Dinkci    6.045754    8.000
253                Nathan Tella    8.181795   15.000
254                  Marquinhos    5.219134    6.000
255               Joao Carvalho    3.605004    3.000
256            Nathan Broadhead    6.741443    4.500
257             Patrick Joosten    0.536339    0.275
258              Vasilije Adzic    2.452835    4.000
259                 Kamal Sowah    0.473709    0.800
260                 Paul Wanner   14.319513   18.000
261              Rafael Barbosa    0.367488    0.350
262               Tino Kadewere    2.599170    2.500
263          Badredine Bouanani    8.375076    7.000
264            Felix Lemarechal   10.959917   10.000
265                 Diego Lopez   24.223757   15.000
266               Pablo Fornals    3.589568    6.000
267                 Joao Mendes    1.640371    2.000
268               Fabio Miretti   15.804065   14.000
269               Himad Abdelli   10.005630    7.000
270             Rodrigo Zalazar    4.067128   18.000
271                Jimmy Mari­n    1.444368    0.600
272              Bernardo Silva   28.241314   38.000
273              Ilias Akhomach    3.028261   15.000
274                   Dani Olmo    7.246782   60.000
275            Argyrios Darelas    0.373345    0.250
276               Darwin Machis    1.201217    0.600

In [77]:
X_train = X_train[['G+A', 'G+A.1', 'Sh/90', '90s', 'Fld', 'G/SoT', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'G+A.1', 'Sh/90', '90s', 'Fld', 'G/SoT', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [83]:
coeffs_df

               coeff
league_GB1  0.723024
league_L1   0.469459
90s         0.459986
league_IT1  0.386027
Age        -0.352579
league_FR1  0.339752
league_ES1  0.335996
G+A         0.213450
G+A.1       0.207368
league_NL1 -0.096316
G/SoT       0.083182
Fld         0.058255
league_PO1  0.041426
Sh/90       0.017533
league_RU1  0.000955

In [84]:
metrics

            MAE       RMSE      MAPE       R2
test   4.716678   8.632656  0.828857  0.56544
train  5.252818  12.757309  0.827967  0.39582

In [87]:
comp_leftovers_test

                            Player  Value_pred  Value
0                  Pedro Goncalves    2.679313  30.00
1                   Dani Rodriguez    4.077808   0.80
2                 Gustavo Klismahn    1.123630   0.60
3                 Zico Buurmeester    1.513418   3.50
4                      Elves Balde    1.301026   0.30
5           Hakon Arnar Haraldsson   10.572635  18.00
6                   Emmanuel Ekong    2.061732   0.55
7                     Simone Verdi    0.765563   1.50
8                     Umut Tohumcu    4.304514   6.00
9                     Ethan Mbappe    2.632617   5.00
10                      Alex Baena   24.508606  55.00
11                    Mikel Merino   22.502460  35.00
12                 Takumi Minamino    6.379179  15.00
13                     Yeremi Pino   14.739740  30.00
14                   Nikola Vlasic   10.335875   8.00
15          Michel-Ange Balikwisha    0.671273   7.00
16                   Calvin Stengs    0.829176   7.00
17                      Manu Bueno    4.743491   1.50
18                   Youssef Maziz    1.351328   1.30
19                  Luis Guilherme    8.620873  15.00
20                     Tom Bischof   24.895824  30.00
21                Malamine Efekele    0.663691   0.40
22                 Luciano Valente    4.230439   7.00
23               Lars Olden Larsen    0.334324   0.50
24                   Coba da Costa    3.379679   3.00
25                  Nichita Motpan    0.740684   0.50
26                    Khalil Fayad    3.276235   3.00
27                  Nikita Ermakov    1.188693   0.60
28                   Romain Faivre    3.528047   6.00
29                    Leonel Bucca    1.606995   0.60
30                    Carles Perez    3.405125   2.00
31                    Ivan Sanchez    2.341318   0.60
32                    Jesus Medina    0.809385   3.00
33                     Enzo Millot   19.610024  35.00
34               Grigoris Kastanos    3.131048   1.50
35                  Ar'jany Martha    0.966825   0.70
36                     Marko Bulat    1.227468   2.00
37                Maksim Samorodov    3.792893   2.50
38                     Mario Gotze    4.049727   4.00
39                     Jaime Pinto    0.443757   0.20
40                       Stoichkov    1.207652   1.50
41                    Yan Diomande    7.005522   1.50
42                           Peque    4.295503   3.50
43                 Jorge Carrascal    2.874753   7.00
44              Mohammed Ihattaren    2.074912   1.00
45                   Ramon Terrats    5.659054   4.00
46                    Kerim Mrabti    1.130666   2.00
47             Gaetano Castrovilli    1.767677   1.50
48  Domingos Andre Ribeiro Almeida    5.511195  10.00
49                   William Gomes    0.871387   9.00
50                    Ole Pohlmann    2.023548   2.50
51                Khoren Bayramyan    0.292343   0.60
52            Charles De Ketelaere   21.923658  35.00
53                    Rodrigo Mora   10.620461  40.00
54                  Bryan Limbombe    0.421759   0.40
55                 Ademola Lookman   27.619625  60.00
56          Matias Fernandez-Pardo    6.658500  15.00
57             Gianluca Prestianni    1.001599   8.00
58                    Carles Alena    3.078051   2.50
59          Oscar Rodriguez Arnaiz    3.931189   2.00
60                      Ado Onaiwu    2.953445   1.50
61                     Amine Talal    0.713730   0.80
62               Christopher Scott    0.530594   0.50
63                       Alan Ruiz    0.910882   0.40
64               Ander Barrenetxea    4.701152  15.00
65                      Jon Guridi    3.589850   3.00
66            Edmond-Paris Maghoma    5.144454   0.80
67                   Dwight McNeil   32.222921  25.00
68                   Drissa Camara    2.551983   1.50
69                   Ricardo Horta    5.596760  12.00

In [88]:
comp_leftovers_train

                         Player  Value_pred    Value
0                Hwang Hee-chan    7.921569   12.000
1                   Pau Cabanes    3.356514    0.800
2                    Unai Gomez    5.487338    6.000
3                 Danila Kozlov    1.671769    2.000
4              Gerard Vandeplas    0.694201    0.400
5                 Shavy Babicka    5.482835    2.500
6                  Nikola Cumic    0.957301    1.500
7                Nicola Sansone    0.779500    0.400
8             Francisco Trincao   17.020089   35.000
9                 Mehdi Merghem    0.456179    0.450
10                 Zeki Amdouni    3.567328   12.000
11                Adnan Januzaj    2.109942    1.200
12             Omari Hutchinson   50.785307   22.000
13                 James Mcatee   21.228832   20.000
14              Paxten Aaronson    6.772964    8.000
15               Kader Ouattara    1.717143    0.800
16                    Kees Smit    0.961012    5.000
17              Connor Metcalfe    2.118898    2.500
18                  Iker Losada    2.662033    1.500
19               Ringo Meerveld    3.612736    3.000
20                 Mahdi Camara   10.109633    9.000
21              Butta Magomedov    0.823577    0.600
22               Reziuan Mirzov    0.733103    0.500
23              Fredrik Aursnes    2.560197   20.000
24             Gianluca Caprari    3.787545    1.000
25            Yaya Kader Fofana    3.706417    4.000
26     Kristian Nokkvi Hlynsson    2.035545    4.000
27                 Miguel Sousa    0.804607    0.500
28                 Edoardo Bove    5.636686    5.000
29                Mattia Felici    4.276611    2.800
30              Yorbe Vertessen    3.899383    6.000
31                Gaetan Perrin   20.952116    8.000
32               Antoine Joujou    3.369147    2.000
33          Juan Manuel Boselli    4.943043    1.200
34            Aleksandr Golovin    2.581956   20.000
35                 Peio Canales    2.074417    1.000
36                Pablo Roberto    0.918484    0.800
37              Braian Mansilla    2.560924    1.800
38               Patrick Wimmer   12.418008   15.000
39                    Raul Moro   13.347887    7.500
40                 Sami Ouaissa    3.732440    1.500
41            Vladislav Sarveli    1.038820    0.900
42                  Merlin Rohl    4.257669   12.000
43             Sebastian Nanasi   13.110791   18.000
44              Jeong Woo-yeong    7.570081    4.000
45                     Can Uzun   11.979957   18.000
46                Dennis Geiger    2.198643    2.000
47                  Moussa Kone    0.440584    0.400
48               Danilo Al Saed    0.298457    0.800
49               Kazeem Olaigbe    1.592165    5.000
50              Samuel Grandsir    0.876079    0.800
51               Alen Halilovic    1.022143    1.000
52                   Luis Rioja    7.676329    2.000
53               Kamory Doumbia    6.453794    4.000
54           Svetoslav Kovachev    0.452365    0.800
55           Junior Dina Ebimbe    3.082542    6.000
56                   Thabo Cele    0.400920    0.350
57                Fabian Rieder    6.299525    6.000
58                  Adrian Beck    6.109705    2.000
59          Nikolai Giorgobiani    0.881008    0.500
60                 Kevin Felida    0.383104    0.200
61                Karim Onisiwo    0.881137    0.800
62                    Chiquinho    1.278145    2.000
63            Nicolas Dominguez   13.016788   18.000
64             Tommaso Baldanzi    4.924528   12.000
65                Chiheb Labidi    0.963624    0.500
66           Alejandro Garnacho   55.245747   45.000
67                 Laszlo Benes    3.839733    3.000
68                Lucas Paqueta   27.384160   28.000
69                   Arda Guler    9.277665   45.000
70             Yari Verschaeren    2.706002    5.000
71               Jamie Leweling    8.125540   20.000
72                        Jofre    9.455629    3.000
73                 Thomas Bruns    0.610982    0.250
74                Takefusa Kubo   10.538531   30.000
75             Teun Koopmeiners    7.419559   35.000
76            Thibaud Verlinden    2.680757    1.700
77                Dylan Mertens    0.588090    0.500
78                Kiryl Zinovic    0.984653    0.400
79                 Amine Gouiri   20.021622   30.000
80            Zakaria Aboukhlal    8.800534   12.000
81           Keano Vanrafelghem    0.746543    0.900
82           Jochem van de Kamp    1.587563    0.800
83              Andrej Kramaric   17.675943    4.000
84           Dehmaine Assoumani    1.988108    0.200
85              Albert Gronbaek    2.911609   11.000
86              Jorg Schreuders    2.964758    1.200
87             Valery Fernandez    3.029634    2.000
88           Yair Mena Palacios    0.485975    0.100
89                  Amad Diallo   67.741666   45.000
90               Casper Staring    0.457247    0.350
91             Mikkel Damsgaard   66.172212   28.000
92             Brandon Aguilera    2.573485    1.500
93              Kevin De Bruyne   15.908792   20.000
94           Babatunde Akinsola    2.014676    0.500
95                 Carlos Forbs    7.371939    8.000
96                 Tidiam Gomis    6.255053    3.000
97                 Jeremie Boga    2.477014   10.000
98                Bilal Bafdili    1.688501    0.900
99           Yaroslav Gladyshev    6.653180    4.000
100                Tomas Suslov    8.103639    6.000
101                 John McGinn   20.029791   16.000
102               Alberto Risco    2.209772    0.200
103               Ola Solbakken    2.086017    2.300
104                  Rui Mendes    0.666805    0.350
105                   Alex Sola    2.272505    2.500
106            Marco van Ginkel    0.491829    0.400
107                Lucas Piazon    1.453324    0.800
108               Alassane Plea   13.744851    5.000
109               Diego Collado    0.527426    0.400
110                      Danilo    5.492959   28.000
111                  Amine Adli    4.087139   18.000
112                Fares Chaibi    7.189716    9.000
113              Florent Mollet    0.637974    1.200
114              Lukas Daschner    3.347046    0.900
115            Aleksei Batrakov   17.847181   12.000
116             James Rodriguez    0.542462    2.500
117                  Rony Lopes    0.748058    2.000
118       Alexis Claude-Maurice   15.750203   12.000
119                 Pablo Torre    7.582938    6.000
120               Pelle Clement    1.159426    0.650
121                     Brenner    4.276461    4.000
122            Arno Verschueren    1.010923    1.500
123          Eliesse Ben Seghir   14.491862   28.000
124                       Anuar    2.983745    0.900
125              Edouard Michut    0.962897    1.800
126              Lechi Sadulaev    3.786330    3.500
127                Sergi Darder    6.840490    4.000
128                  Kodai Sano    2.411583    4.000
129       Isaac Palazon Camacho    6.145714    3.500
130              Thomas Robinet    1.594828    0.400
131                   Lior Kasa    3.047555    1.500
132                 David Costa    1.573334    6.000
133                 Cole Palmer  220.258500  120.000
134                  Joao Graca    0.687925    0.300
135              Olivier Dumont    0.900064    0.400
136                Andre Franco    0.896839    2.500
137               Franck Surdez    2.368147    2.000
138                  Levi Smans    2.796671    2.000
139                         Duk    1.291859    1.000
140            Georginio Rutter   39.235433   32.000
141               Hugo Vetlesen    1.121486    4.000
142      Jean-Ricner Bellegarde   28.803687   18.000
143         Javad Hosseinnezhad    2.467020    0.900
144                  Lucas Vera    3.286748    3.500
145           Aleksandr Rudenko    1.990953    1.000
146                Eberechi Eze   71.394409   55.000
147                  Yann Gboho   12.785859    8.000
148              Martin Terrier    3.585484   17.000
149              Mathieu Cafaro    1.694001    2.500
150              Morten Thorsby    3.504522    3.000
151            Abdelkahar Kadri    2.457306    2.200
152                    John Joe    2.448322    1.200
153           Ezequiel Bullaude    2.407789    2.500
154            Dejan Kulusevski   52.886235   50.000
155                Omari Forson    2.512312    2.000
156               Thiago Almada    4.478295   25.000
157                    Bruninho    1.318148    1.500
158                   Moi Gomez    1.023720    2.000
159       Richard van der Venne    0.553716    0.225
160               Abdou Harroui    3.413555    1.800
161                Sofiane Diop    8.747381   10.000
162               Ivan Oblyakov    4.011698    9.000
163               Ivo Rodrigues    1.143394    1.000
164              Angelo Fulgini    2.290915    5.000
165                   Leo Sauer    5.682539    5.000
166               Theo Bongonda    2.003149    6.000
167                      Arthur    1.235729    3.500
168               Daniel Borges    0.688035    0.400
169             Soren Tengstedt    0.397954    0.800
170  Bruno Xavier Almeida Costa    1.047974    0.500
171                Fermin Lopez   12.211259   50.000
172          Aliou Badara Balde    2.474140    0.800
173                 Arthur Atta    4.775241    8.000
174               Malik Tillman    4.834558   32.000
175                 Nicolas Paz   38.387040   35.000
176              Junior Messias    1.591423    1.500
177                  Pere Milla    1.888589    1.200
178                  Phil Foden   36.375658  100.000
179            Giovani Lo Celso    7.297076   15.000
180            Anton Zinkovskiy    0.625318    2.500
181                 Yunus Musah    6.215147   20.000
182                 Tom Reyners    0.906720    0.800
183              Yassine Kechta    6.581696    5.000
184               Thomas Muller    2.521162    6.000
185              Omri Gandelman    2.218556    4.000
186                Pablo Solari    1.221059    7.000
187         Fisayo Dele-Bashiru    5.910262    7.500
188                Alex Bermejo    0.796709    0.400
189              Sergey Pinyaev    6.032367    8.000
190              Sergio Bermejo    0.709925    0.900
191          Jacob Bruun Larsen    5.641413    5.000
192                 Dani de Wit    4.418320    2.500
193               Matheus Cunha  126.345722   60.000
194              Kenneth Taylor    5.765044   28.000
195                Noah Edjouma    7.598339    0.800
196                Isa Sakamoto    2.344235    2.500
197                Habib Diarra   16.006951   20.000
198                Ludovic Blas   13.894877   18.000
199          Moses David Cobnan    2.282096    0.900
200                Nikola Storm    1.306484    2.000
201           Vladimir Khubulov    1.864275    0.600
202             Hamzat Ojediran    3.046262    1.800
203               Bilal Brahimi    1.343583    1.800
204        Joao Ferreira Barros    0.936950    0.200
205                   Adi Nalic    0.487275    0.350
206                Jens Odgaard    9.814636   12.000
207                 Michel Vlap    2.924343    5.000
208               Chris Fuhrich    7.305655   15.000
209                Yann Karamoh    2.721909    1.800
210          Ruslan Malinovskyi    1.620928    2.500
211              Marcus Edwards    1.390715   12.000
212            Steven Skrzybski    5.935727    1.000
213             Miguel Reisinho    2.497904    0.700
214             Lucas Fernandes    0.516851    1.500
215             Vito van Crooij    2.719863    1.500
216                 Boulaye Dia   13.260573   15.000
217               Conor Chaplin    7.999996    6.000
218               Tjaronn Chery    2.342985    0.500
219                  Remi Oudin    1.334294    1.500
220                 Joe Willock   10.827080   22.000
221               Florian Wirtz   58.796214  140.000
222             Roberto Navarro    3.587287    6.000
223               Dermane Karim    1.310018    3.000
224           Zelimkhan Bakayev    1.275269    2.000
225              Ewan Henderson    1.761784    0.600
226                 Sergi Canos    1.401395    1.000
227            Gianluca Gaetano    6.625465    4.000
228              Valenti­n Vada    0.964994    1.800
229              Samuel Bastien    0.598569    0.650
230              Peter Gonzalez    1.872685    1.200
231               Takuro Kaneko    0.710467    1.500
232                 Jakob Breum    6.396560    5.000
233       Moritz-Broni Kwarteng    1.610530    1.000
234             Mikhail Ignatov    0.471981    1.000
235                        Gavi    6.710064   60.000
236            Roberto Gonzalez    0.981100    1.500
237       Kiernan Dewsbury-Hall    6.422662   20.000
238         Benjamin Rollheiser    2.269566    8.000
239         Pape Daouda Diongue    6.729324    0.800
240                Miguel Baeza    1.108718    0.400
241               Manuel Namora    0.456688    0.100
242          Jean Matteo Bahoya   11.240688   17.000
243          Rajiv van La Parra    0.254308    0.200
244                Cesar Huerta    1.751688    6.000
245                Brajan Gruda   22.823058   25.000
246                Carlos Soler   10.207337   18.000
247                Fabio Vieira    3.329504   22.000
248               Pablo Sarabia    8.033200    5.000
249                Julio Enciso   25.534627   22.000
250            Petter Nosa Dahl    1.193365    0.600
251           Geoffry Hairemans    0.716717    0.500
252                 Eren Dinkci    5.708344    8.000
253                Nathan Tella    7.416642   15.000
254                  Marquinhos    3.220044    6.000
255               Joao Carvalho    3.567104    3.000
256            Nathan Broadhead    8.545869    4.500
257             Patrick Joosten    0.466784    0.275
258              Vasilije Adzic    2.721945    4.000
259                 Kamal Sowah    0.495467    0.800
260                 Paul Wanner   15.227404   18.000
261              Rafael Barbosa    0.391138    0.350
262               Tino Kadewere    2.009349    2.500
263          Badredine Bouanani    7.581422    7.000
264            Felix Lemarechal   10.163784   10.000
265                 Diego Lopez   23.235341   15.000
266               Pablo Fornals    3.342256    6.000
267                 Joao Mendes    1.604229    2.000
268               Fabio Miretti   14.145805   14.000
269               Himad Abdelli   11.777267    7.000
270             Rodrigo Zalazar    3.208679   18.000
271                Jimmy Mari­n    1.545832    0.600
272              Bernardo Silva   28.874426   38.000
273              Ilias Akhomach    3.168865   15.000
274                   Dani Olmo   10.066251   60.000
275            Argyrios Darelas    0.429208    0.250
276               Darwin Machis    1.055521    0.600

In [90]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                         Player  Value_pred    Value
133                 Cole Palmer  220.258500  120.000
193               Matheus Cunha  126.345722   60.000
146                Eberechi Eze   71.394409   55.000
89                  Amad Diallo   67.741666   45.000
91             Mikkel Damsgaard   66.172212   28.000
221               Florian Wirtz   58.796214  140.000
66           Alejandro Garnacho   55.245747   45.000
154            Dejan Kulusevski   52.886235   50.000
12             Omari Hutchinson   50.785307   22.000
140            Georginio Rutter   39.235433   32.000
175                 Nicolas Paz   38.387040   35.000
178                  Phil Foden   36.375658  100.000
272              Bernardo Silva   28.874426   38.000
142      Jean-Ricner Bellegarde   28.803687   18.000
68                Lucas Paqueta   27.384160   28.000
249                Julio Enciso   25.534627   22.000
265                 Diego Lopez   23.235341   15.000
245                Brajan Gruda   22.823058   25.000
13                 James Mcatee   21.228832   20.000
31                Gaetan Perrin   20.952116    8.000
101                 John McGinn   20.029791   16.000
79                 Amine Gouiri   20.021622   30.000
115            Aleksei Batrakov   17.847181   12.000
83              Andrej Kramaric   17.675943    4.000
8             Francisco Trincao   17.020089   35.000
197                Habib Diarra   16.006951   20.000
93              Kevin De Bruyne   15.908792   20.000
118       Alexis Claude-Maurice   15.750203   12.000
260                 Paul Wanner   15.227404   18.000
123          Eliesse Ben Seghir   14.491862   28.000
268               Fabio Miretti   14.145805   14.000
198                Ludovic Blas   13.894877   18.000
108               Alassane Plea   13.744851    5.000
39                    Raul Moro   13.347887    7.500
216                 Boulaye Dia   13.260573   15.000
43             Sebastian Nanasi   13.110791   18.000
63            Nicolas Dominguez   13.016788   18.000
147                  Yann Gboho   12.785859    8.000
38               Patrick Wimmer   12.418008   15.000
171                Fermin Lopez   12.211259   50.000
45                     Can Uzun   11.979957   18.000
269               Himad Abdelli   11.777267    7.000
242          Jean Matteo Bahoya   11.240688   17.000
220                 Joe Willock   10.827080   22.000
74                Takefusa Kubo   10.538531   30.000
246                Carlos Soler   10.207337   18.000
264            Felix Lemarechal   10.163784   10.000
20                 Mahdi Camara   10.109633    9.000
274                   Dani Olmo   10.066251   60.000
206                Jens Odgaard    9.814636   12.000
72                        Jofre    9.455629    3.000
69                   Arda Guler    9.277665   45.000
80            Zakaria Aboukhlal    8.800534   12.000
161                Sofiane Diop    8.747381   10.000
256            Nathan Broadhead    8.545869    4.500
71               Jamie Leweling    8.125540   20.000
100                Tomas Suslov    8.103639    6.000
248               Pablo Sarabia    8.033200    5.000
217               Conor Chaplin    7.999996    6.000
0                Hwang Hee-chan    7.921569   12.000
52                   Luis Rioja    7.676329    2.000
195                Noah Edjouma    7.598339    0.800
119                 Pablo Torre    7.582938    6.000
263          Badredine Bouanani    7.581422    7.000
44              Jeong Woo-yeong    7.570081    4.000
75             Teun Koopmeiners    7.419559   35.000
253                Nathan Tella    7.416642   15.000
95                 Carlos Forbs    7.371939    8.000
208               Chris Fuhrich    7.305655   15.000
179            Giovani Lo Celso    7.297076   15.000
112                Fares Chaibi    7.189716    9.000
127                Sergi Darder    6.840490    4.000
14              Paxten Aaronson    6.772964    8.000
239         Pape Daouda Diongue    6.729324    0.800
235                        Gavi    6.710064   60.000
99           Yaroslav Gladyshev    6.653180    4.000
227            Gianluca Gaetano    6.625465    4.000
183              Yassine Kechta    6.581696    5.000
53               Kamory Doumbia    6.453794    4.000
237       Kiernan Dewsbury-Hall    6.422662   20.000
232                 Jakob Breum    6.396560    5.000
57                Fabian Rieder    6.299525    6.000
96                 Tidiam Gomis    6.255053    3.000
181                 Yunus Musah    6.215147   20.000
129       Isaac Palazon Camacho    6.145714    3.500
58                  Adrian Beck    6.109705    2.000
189              Sergey Pinyaev    6.032367    8.000
212            Steven Skrzybski    5.935727    1.000
187         Fisayo Dele-Bashiru    5.910262    7.500
194              Kenneth Taylor    5.765044   28.000
252                 Eren Dinkci    5.708344    8.000
165                   Leo Sauer    5.682539    5.000
191          Jacob Bruun Larsen    5.641413    5.000
28                 Edoardo Bove    5.636686    5.000
110                      Danilo    5.492959   28.000
2                    Unai Gomez    5.487338    6.000
5                 Shavy Babicka    5.482835    2.500
33          Juan Manuel Boselli    4.943043    1.200
64             Tommaso Baldanzi    4.924528   12.000
174               Malik Tillman    4.834558   32.000
173                 Arthur Atta    4.775241    8.000
156               Thiago Almada    4.478295   25.000
192                 Dani de Wit    4.418320    2.500
29                Mattia Felici    4.276611    2.800
121                     Brenner    4.276461    4.000
42                  Merlin Rohl    4.257669   12.000
111                  Amine Adli    4.087139   18.000
162               Ivan Oblyakov    4.011698    9.000
30              Yorbe Vertessen    3.899383    6.000
67                 Laszlo Benes    3.839733    3.000
24             Gianluca Caprari    3.787545    1.000
126              Lechi Sadulaev    3.786330    3.500
40                 Sami Ouaissa    3.732440    1.500
25            Yaya Kader Fofana    3.706417    4.000
19               Ringo Meerveld    3.612736    3.000
222             Roberto Navarro    3.587287    6.000
148              Martin Terrier    3.585484   17.000
10                 Zeki Amdouni    3.567328   12.000
255               Joao Carvalho    3.567104    3.000
150              Morten Thorsby    3.504522    3.000
160               Abdou Harroui    3.413555    1.800
32               Antoine Joujou    3.369147    2.000
1                   Pau Cabanes    3.356514    0.800
114              Lukas Daschner    3.347046    0.900
266               Pablo Fornals    3.342256    6.000
247                Fabio Vieira    3.329504   22.000
144                  Lucas Vera    3.286748    3.500
254                  Marquinhos    3.220044    6.000
270             Rodrigo Zalazar    3.208679   18.000
273              Ilias Akhomach    3.168865   15.000
55           Junior Dina Ebimbe    3.082542    6.000
131                   Lior Kasa    3.047555    1.500
202             Hamzat Ojediran    3.046262    1.800
87             Valery Fernandez    3.029634    2.000
124                       Anuar    2.983745    0.900
86              Jorg Schreuders    2.964758    1.200
207                 Michel Vlap    2.924343    5.000
85              Albert Gronbaek    2.911609   11.000
138                  Levi Smans    2.796671    2.000
258              Vasilije Adzic    2.721945    4.000
209                Yann Karamoh    2.721909    1.800
215             Vito van Crooij    2.719863    1.500
70             Yari Verschaeren    2.706002    5.000
76            Thibaud Verlinden    2.680757    1.700
18                  Iker Losada    2.662033    1.500
34            Aleksandr Golovin    2.581956   20.000
92             Brandon Aguilera    2.573485    1.500
37              Braian Mansilla    2.560924    1.800
23              Fredrik Aursnes    2.560197   20.000
184               Thomas Muller    2.521162    6.000
155                Omari Forson    2.512312    2.000
213             Miguel Reisinho    2.497904    0.700
97                 Jeremie Boga    2.477014   10.000
172          Aliou Badara Balde    2.474140    0.800
143         Javad Hosseinnezhad    2.467020    0.900
151            Abdelkahar Kadri    2.457306    2.200
152                    John Joe    2.448322    1.200
128                  Kodai Sano    2.411583    4.000
153           Ezequiel Bullaude    2.407789    2.500
137               Franck Surdez    2.368147    2.000
196                Isa Sakamoto    2.344235    2.500
218               Tjaronn Chery    2.342985    0.500
164              Angelo Fulgini    2.290915    5.000
199          Moses David Cobnan    2.282096    0.900
105                   Alex Sola    2.272505    2.500
238         Benjamin Rollheiser    2.269566    8.000
185              Omri Gandelman    2.218556    4.000
102               Alberto Risco    2.209772    0.200
46                Dennis Geiger    2.198643    2.000
17              Connor Metcalfe    2.118898    2.500
11                Adnan Januzaj    2.109942    1.200
103               Ola Solbakken    2.086017    2.300
35                 Peio Canales    2.074417    1.000
26     Kristian Nokkvi Hlynsson    2.035545    4.000
94           Babatunde Akinsola    2.014676    0.500
262               Tino Kadewere    2.009349    2.500
166               Theo Bongonda    2.003149    6.000
145           Aleksandr Rudenko    1.990953    1.000
84           Dehmaine Assoumani    1.988108    0.200
177                  Pere Milla    1.888589    1.200
230              Peter Gonzalez    1.872685    1.200
201           Vladimir Khubulov    1.864275    0.600
225              Ewan Henderson    1.761784    0.600
244                Cesar Huerta    1.751688    6.000
15               Kader Ouattara    1.717143    0.800
149              Mathieu Cafaro    1.694001    2.500
98                Bilal Bafdili    1.688501    0.900
3                 Danila Kozlov    1.671769    2.000
210          Ruslan Malinovskyi    1.620928    2.500
233       Moritz-Broni Kwarteng    1.610530    1.000
267                 Joao Mendes    1.604229    2.000
130              Thomas Robinet    1.594828    0.400
49               Kazeem Olaigbe    1.592165    5.000
176              Junior Messias    1.591423    1.500
82           Jochem van de Kamp    1.587563    0.800
132                 David Costa    1.573334    6.000
271                Jimmy Mari­n    1.545832    0.600
107                Lucas Piazon    1.453324    0.800
226                 Sergi Canos    1.401395    1.000
211              Marcus Edwards    1.390715   12.000
203               Bilal Brahimi    1.343583    1.800
219                  Remi Oudin    1.334294    1.500
157                    Bruninho    1.318148    1.500
223               Dermane Karim    1.310018    3.000
200                Nikola Storm    1.306484    2.000
139                         Duk    1.291859    1.000
62                    Chiquinho    1.278145    2.000
224           Zelimkhan Bakayev    1.275269    2.000
167                      Arthur    1.235729    3.500
186                Pablo Solari    1.221059    7.000
250            Petter Nosa Dahl    1.193365    0.600
120               Pelle Clement    1.159426    0.650
163               Ivo Rodrigues    1.143394    1.000
141               Hugo Vetlesen    1.121486    4.000
240                Miguel Baeza    1.108718    0.400
276               Darwin Machis    1.055521    0.600
170  Bruno Xavier Almeida Costa    1.047974    0.500
41            Vladislav Sarveli    1.038820    0.900
158                   Moi Gomez    1.023720    2.000
51               Alen Halilovic    1.022143    1.000
122            Arno Verschueren    1.010923    1.500
78                Kiryl Zinovic    0.984653    0.400
236            Roberto Gonzalez    0.981100    1.500
228              Valenti­n Vada    0.964994    1.800
65                Chiheb Labidi    0.963624    0.500
125              Edouard Michut    0.962897    1.800
16                    Kees Smit    0.961012    5.000
6                  Nikola Cumic    0.957301    1.500
204        Joao Ferreira Barros    0.936950    0.200
36                Pablo Roberto    0.918484    0.800
182                 Tom Reyners    0.906720    0.800
135              Olivier Dumont    0.900064    0.400
136                Andre Franco    0.896839    2.500
61                Karim Onisiwo    0.881137    0.800
59          Nikolai Giorgobiani    0.881008    0.500
50              Samuel Grandsir    0.876079    0.800
21              Butta Magomedov    0.823577    0.600
27                 Miguel Sousa    0.804607    0.500
188                Alex Bermejo    0.796709    0.400
7                Nicola Sansone    0.779500    0.400
117                  Rony Lopes    0.748058    2.000
81           Keano Vanrafelghem    0.746543    0.900
22               Reziuan Mirzov    0.733103    0.500
251           Geoffry Hairemans    0.716717    0.500
231               Takuro Kaneko    0.710467    1.500
190              Sergio Bermejo    0.709925    0.900
4              Gerard Vandeplas    0.694201    0.400
168               Daniel Borges    0.688035    0.400
134                  Joao Graca    0.687925    0.300
104                  Rui Mendes    0.666805    0.350
113              Florent Mollet    0.637974    1.200
180            Anton Zinkovskiy    0.625318    2.500
73                 Thomas Bruns    0.610982    0.250
229              Samuel Bastien    0.598569    0.650
77                Dylan Mertens    0.588090    0.500
159       Richard van der Venne    0.553716    0.225
116             James Rodriguez    0.542462    2.500
109               Diego Collado    0.527426    0.400
214             Lucas Fernandes    0.516851    1.500
259                 Kamal Sowah    0.495467    0.800
106            Marco van Ginkel    0.491829    0.400
205                   Adi Nalic    0.487275    0.350
88           Yair Mena Palacios    0.485975    0.100
234             Mikhail Ignatov    0.471981    1.000
257             Patrick Joosten    0.466784    0.275
90               Casper Staring    0.457247    0.350
241               Manuel Namora    0.456688    0.100
9                 Mehdi Merghem    0.456179    0.450
54           Svetoslav Kovachev    0.452365    0.800
47                  Moussa Kone    0.440584    0.400
275            Argyrios Darelas    0.429208    0.250
56                   Thabo Cele    0.400920    0.350
169             Soren Tengstedt    0.397954    0.800
261              Rafael Barbosa    0.391138    0.350
60                 Kevin Felida    0.383104    0.200
48               Danilo Al Saed    0.298457    0.800
243          Rajiv van La Parra    0.254308    0.200

In [91]:
X_train = X_train[['G+A', 'Sh/90', '90s', 'Fld', 'G/SoT', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Sh/90', '90s', 'Fld', 'G/SoT', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [97]:
coeffs_df

               coeff
league_GB1  0.735365
league_L1   0.483841
league_IT1  0.399948
90s         0.376520
G+A         0.367518
league_FR1  0.357504
Age        -0.353592
league_ES1  0.343101
G/SoT       0.174225
league_NL1 -0.088982
Fld         0.060297
Sh/90       0.052555
league_PO1  0.041380
league_RU1  0.016203

In [98]:
metrics

            MAE       RMSE      MAPE        R2
test   4.565101   8.330637  0.831055  0.595315
train  5.536570  14.358948  0.837187  0.234591

In [99]:
comp_leftovers_test

                            Player  Value_pred  Value
0                  Pedro Goncalves    2.267385  30.00
1                   Dani Rodriguez    4.099590   0.80
2                 Gustavo Klismahn    0.918985   0.60
3                 Zico Buurmeester    1.563450   3.50
4                      Elves Balde    1.216618   0.30
5           Hakon Arnar Haraldsson   11.004373  18.00
6                   Emmanuel Ekong    2.340219   0.55
7                     Simone Verdi    0.860571   1.50
8                     Umut Tohumcu    3.860250   6.00
9                     Ethan Mbappe    3.303771   5.00
10                      Alex Baena   26.761870  55.00
11                    Mikel Merino   23.481312  35.00
12                 Takumi Minamino    6.653630  15.00
13                     Yeremi Pino   14.879357  30.00
14                   Nikola Vlasic   10.126024   8.00
15          Michel-Ange Balikwisha    0.933288   7.00
16                   Calvin Stengs    0.672446   7.00
17                      Manu Bueno    4.987546   1.50
18                   Youssef Maziz    1.302392   1.30
19                  Luis Guilherme    9.938263  15.00
20                     Tom Bischof   25.031573  30.00
21                Malamine Efekele    0.663741   0.40
22                 Luciano Valente    3.879671   7.00
23               Lars Olden Larsen    0.362255   0.50
24                   Coba da Costa    3.342434   3.00
25                  Nichita Motpan    0.757078   0.50
26                    Khalil Fayad    3.381928   3.00
27                  Nikita Ermakov    1.131273   0.60
28                   Romain Faivre    3.152349   6.00
29                    Leonel Bucca    1.533856   0.60
30                    Carles Perez    3.592572   2.00
31                    Ivan Sanchez    2.375501   0.60
32                    Jesus Medina    0.728249   3.00
33                     Enzo Millot   19.562018  35.00
34               Grigoris Kastanos    3.263362   1.50
35                  Ar'jany Martha    0.873448   0.70
36                     Marko Bulat    1.189877   2.00
37                Maksim Samorodov    3.883455   2.50
38                     Mario Gotze    4.446161   4.00
39                     Jaime Pinto    0.470722   0.20
40                       Stoichkov    1.189560   1.50
41                    Yan Diomande    7.166811   1.50
42                           Peque    4.397787   3.50
43                 Jorge Carrascal    2.765834   7.00
44              Mohammed Ihattaren    1.908379   1.00
45                   Ramon Terrats    5.830799   4.00
46                    Kerim Mrabti    1.000383   2.00
47             Gaetano Castrovilli    1.823926   1.50
48  Domingos Andre Ribeiro Almeida    4.750216  10.00
49                   William Gomes    0.939886   9.00
50                    Ole Pohlmann    2.009193   2.50
51                Khoren Bayramyan    0.299363   0.60
52            Charles De Ketelaere   22.287971  35.00
53                    Rodrigo Mora    9.854190  40.00
54                  Bryan Limbombe    0.469995   0.40
55                 Ademola Lookman   30.603255  60.00
56          Matias Fernandez-Pardo    9.284845  15.00
57             Gianluca Prestianni    1.178992   8.00
58                    Carles Alena    2.775008   2.50
59          Oscar Rodriguez Arnaiz    3.708750   2.00
60                      Ado Onaiwu    2.815595   1.50
61                     Amine Talal    0.747514   0.80
62               Christopher Scott    0.585268   0.50
63                       Alan Ruiz    0.798140   0.40
64               Ander Barrenetxea    4.359860  15.00
65                      Jon Guridi    3.328637   3.00
66            Edmond-Paris Maghoma    5.584154   0.80
67                   Dwight McNeil   29.806887  25.00
68                   Drissa Camara    2.941229   1.50
69                   Ricardo Horta    5.884179  12.00

In [100]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                         Player  Value_pred    Value
133                 Cole Palmer  257.644664  120.000
193               Matheus Cunha  146.814299   60.000
146                Eberechi Eze   77.224173   55.000
89                  Amad Diallo   71.149596   45.000
91             Mikkel Damsgaard   66.147869   28.000
221               Florian Wirtz   60.735551  140.000
66           Alejandro Garnacho   57.277039   45.000
154            Dejan Kulusevski   56.108400   50.000
12             Omari Hutchinson   48.046348   22.000
140            Georginio Rutter   42.256466   32.000
175                 Nicolas Paz   40.639676   35.000
178                  Phil Foden   39.240800  100.000
272              Bernardo Silva   28.752222   38.000
142      Jean-Ricner Bellegarde   28.647630   18.000
68                Lucas Paqueta   27.984741   28.000
265                 Diego Lopez   26.017815   15.000
249                Julio Enciso   25.050698   22.000
31                Gaetan Perrin   23.595379    8.000
79                 Amine Gouiri   21.216182   30.000
13                 James Mcatee   19.568752   20.000
101                 John McGinn   19.299427   16.000
83              Andrej Kramaric   19.228330    4.000
115            Aleksei Batrakov   19.181139   12.000
8             Francisco Trincao   18.770167   35.000
245                Brajan Gruda   17.714729   25.000
118       Alexis Claude-Maurice   17.049463   12.000
108               Alassane Plea   15.688156    5.000
260                 Paul Wanner   15.593081   18.000
268               Fabio Miretti   15.432732   14.000
93              Kevin De Bruyne   15.315580   20.000
197                Habib Diarra   15.283477   20.000
123          Eliesse Ben Seghir   14.541767   28.000
43             Sebastian Nanasi   14.149047   18.000
216                 Boulaye Dia   14.101565   15.000
198                Ludovic Blas   14.097523   18.000
39                    Raul Moro   12.941677    7.500
147                  Yann Gboho   12.663613    8.000
38               Patrick Wimmer   12.647405   15.000
242          Jean Matteo Bahoya   11.752253   17.000
63            Nicolas Dominguez   11.625211   18.000
269               Himad Abdelli   11.473249    7.000
171                Fermin Lopez   10.881881   50.000
45                     Can Uzun   10.765578   18.000
74                Takefusa Kubo   10.741604   30.000
264            Felix Lemarechal   10.595609   10.000
20                 Mahdi Camara   10.138604    9.000
220                 Joe Willock   10.109524   22.000
206                Jens Odgaard   10.091321   12.000
246                Carlos Soler   10.010404   18.000
72                        Jofre    9.313431    3.000
235                        Gavi    9.158189   60.000
0                Hwang Hee-chan    9.126098   12.000
80            Zakaria Aboukhlal    8.920126   12.000
274                   Dani Olmo    8.634179   60.000
256            Nathan Broadhead    8.618534    4.500
69                   Arda Guler    8.482445   45.000
217               Conor Chaplin    8.269397    6.000
44              Jeong Woo-yeong    8.161585    4.000
95                 Carlos Forbs    7.835850    8.000
161                Sofiane Diop    7.792725   10.000
71               Jamie Leweling    7.776117   20.000
14              Paxten Aaronson    7.737245    8.000
52                   Luis Rioja    7.534147    2.000
75             Teun Koopmeiners    7.527239   35.000
100                Tomas Suslov    7.424657    6.000
248               Pablo Sarabia    7.367653    5.000
208               Chris Fuhrich    7.034743   15.000
253                Nathan Tella    6.944944   15.000
263          Badredine Bouanani    6.880288    7.000
112                Fares Chaibi    6.824105    9.000
232                 Jakob Breum    6.721827    5.000
179            Giovani Lo Celso    6.600229   15.000
183              Yassine Kechta    6.523655    5.000
187         Fisayo Dele-Bashiru    6.493925    7.500
53               Kamory Doumbia    6.472924    4.000
99           Yaroslav Gladyshev    6.453554    4.000
127                Sergi Darder    6.414990    4.000
58                  Adrian Beck    6.366591    2.000
227            Gianluca Gaetano    6.309177    4.000
129       Isaac Palazon Camacho    6.106219    3.500
189              Sergey Pinyaev    5.939210    8.000
28                 Edoardo Bove    5.939078    5.000
181                 Yunus Musah    5.790547   20.000
194              Kenneth Taylor    5.787814   28.000
165                   Leo Sauer    5.781453    5.000
110                      Danilo    5.691256   28.000
57                Fabian Rieder    5.680767    6.000
212            Steven Skrzybski    5.676308    1.000
5                 Shavy Babicka    5.526859    2.500
2                    Unai Gomez    5.292650    6.000
195                Noah Edjouma    5.289699    0.800
237       Kiernan Dewsbury-Hall    5.264194   20.000
64             Tommaso Baldanzi    5.205607   12.000
252                 Eren Dinkci    5.106277    8.000
174               Malik Tillman    5.104690   32.000
191          Jacob Bruun Larsen    5.047726    5.000
33          Juan Manuel Boselli    4.969633    1.200
119                 Pablo Torre    4.896122    6.000
173                 Arthur Atta    4.716241    8.000
96                 Tidiam Gomis    4.684491    3.000
192                 Dani de Wit    4.569116    2.500
30              Yorbe Vertessen    4.447393    6.000
239         Pape Daouda Diongue    4.426445    0.800
111                  Amine Adli    4.395965   18.000
42                  Merlin Rohl    4.130435   12.000
156               Thiago Almada    4.118381   25.000
40                 Sami Ouaissa    4.011778    1.500
162               Ivan Oblyakov    3.950663    9.000
25            Yaya Kader Fofana    3.785482    4.000
29                Mattia Felici    3.750243    2.800
255               Joao Carvalho    3.706040    3.000
126              Lechi Sadulaev    3.700034    3.500
67                 Laszlo Benes    3.664091    3.000
85              Albert Gronbaek    3.659160   11.000
266               Pablo Fornals    3.645635    6.000
222             Roberto Navarro    3.614673    6.000
24             Gianluca Caprari    3.548470    1.000
19               Ringo Meerveld    3.457453    3.000
131                   Lior Kasa    3.448346    1.500
1                   Pau Cabanes    3.440829    0.800
148              Martin Terrier    3.423604   17.000
202             Hamzat Ojediran    3.388464    1.800
273              Ilias Akhomach    3.386474   15.000
247                Fabio Vieira    3.216971   22.000
121                     Brenner    3.213636    4.000
144                  Lucas Vera    3.177951    3.500
258              Vasilije Adzic    3.162651    4.000
150              Morten Thorsby    3.139189    3.000
32               Antoine Joujou    3.132454    2.000
172          Aliou Badara Balde    3.054092    0.800
207                 Michel Vlap    3.049850    5.000
124                       Anuar    3.013919    0.900
86              Jorg Schreuders    3.009914    1.200
270             Rodrigo Zalazar    2.999255   18.000
160               Abdou Harroui    2.951189    1.800
114              Lukas Daschner    2.939938    0.900
10                 Zeki Amdouni    2.890227   12.000
18                  Iker Losada    2.870095    1.500
155                Omari Forson    2.850066    2.000
55           Junior Dina Ebimbe    2.808360    6.000
102               Alberto Risco    2.806905    0.200
254                  Marquinhos    2.782692    6.000
34            Aleksandr Golovin    2.777356   20.000
87             Valery Fernandez    2.770038    2.000
209                Yann Karamoh    2.727784    1.800
215             Vito van Crooij    2.680644    1.500
92             Brandon Aguilera    2.664651    1.500
152                    John Joe    2.643469    1.200
37              Braian Mansilla    2.621233    1.800
138                  Levi Smans    2.617397    2.000
70             Yari Verschaeren    2.577706    5.000
76            Thibaud Verlinden    2.457244    1.700
143         Javad Hosseinnezhad    2.451145    0.900
153           Ezequiel Bullaude    2.443285    2.500
128                  Kodai Sano    2.434321    4.000
97                 Jeremie Boga    2.401318   10.000
218               Tjaronn Chery    2.389338    0.500
23              Fredrik Aursnes    2.382789   20.000
84           Dehmaine Assoumani    2.368870    0.200
151            Abdelkahar Kadri    2.360761    2.200
164              Angelo Fulgini    2.349833    5.000
17              Connor Metcalfe    2.314495    2.500
184               Thomas Muller    2.309905    6.000
46                Dennis Geiger    2.230443    2.000
35                 Peio Canales    2.201336    1.000
213             Miguel Reisinho    2.150740    0.700
105                   Alex Sola    2.149692    2.500
185              Omri Gandelman    2.128810    4.000
103               Ola Solbakken    2.106474    2.300
94           Babatunde Akinsola    2.068507    0.500
166               Theo Bongonda    2.056517    6.000
11                Adnan Januzaj    2.040744    1.200
230              Peter Gonzalez    2.035644    1.200
137               Franck Surdez    2.032237    2.000
199          Moses David Cobnan    2.030784    0.900
145           Aleksandr Rudenko    2.016759    1.000
196                Isa Sakamoto    1.959834    2.500
201           Vladimir Khubulov    1.937357    0.600
49               Kazeem Olaigbe    1.932328    5.000
26     Kristian Nokkvi Hlynsson    1.920714    4.000
233       Moritz-Broni Kwarteng    1.908085    1.000
98                Bilal Bafdili    1.852775    0.900
149              Mathieu Cafaro    1.844320    2.500
3                 Danila Kozlov    1.797917    2.000
132                 David Costa    1.791922    6.000
177                  Pere Milla    1.774520    1.200
225              Ewan Henderson    1.772346    0.600
244                Cesar Huerta    1.706735    6.000
262               Tino Kadewere    1.654291    2.500
176              Junior Messias    1.617610    1.500
267                 Joao Mendes    1.596086    2.000
203               Bilal Brahimi    1.547999    1.800
271                Jimmy Mari­n    1.540745    0.600
15               Kader Ouattara    1.450939    0.800
130              Thomas Robinet    1.443802    0.400
62                    Chiquinho    1.441342    2.000
219                  Remi Oudin    1.436487    1.500
82           Jochem van de Kamp    1.385967    0.800
139                         Duk    1.381039    1.000
238         Benjamin Rollheiser    1.339902    8.000
224           Zelimkhan Bakayev    1.333955    2.000
226                 Sergi Canos    1.322807    1.000
211              Marcus Edwards    1.318240   12.000
210          Ruslan Malinovskyi    1.307048    2.500
157                    Bruninho    1.271978    1.500
240                Miguel Baeza    1.251680    0.400
223               Dermane Karim    1.232010    3.000
200                Nikola Storm    1.229486    2.000
107                Lucas Piazon    1.213898    0.800
120               Pelle Clement    1.207128    0.650
136                Andre Franco    1.194051    2.500
141               Hugo Vetlesen    1.130799    4.000
167                      Arthur    1.118932    3.500
250            Petter Nosa Dahl    1.115638    0.600
186                Pablo Solari    1.087306    7.000
163               Ivo Rodrigues    1.081603    1.000
78                Kiryl Zinovic    1.063757    0.400
65                Chiheb Labidi    1.028261    0.500
276               Darwin Machis    1.023692    0.600
61                Karim Onisiwo    1.022023    0.800
204        Joao Ferreira Barros    1.012373    0.200
158                   Moi Gomez    1.010845    2.000
125              Edouard Michut    1.009785    1.800
170  Bruno Xavier Almeida Costa    1.007237    0.500
6                  Nikola Cumic    0.991076    1.500
51               Alen Halilovic    0.981760    1.000
16                    Kees Smit    0.974841    5.000
7                Nicola Sansone    0.972498    0.400
41            Vladislav Sarveli    0.965976    0.900
236            Roberto Gonzalez    0.965911    1.500
135              Olivier Dumont    0.965226    0.400
122            Arno Verschueren    0.962204    1.500
50              Samuel Grandsir    0.938737    0.800
134                  Joao Graca    0.934820    0.300
228              Valenti­n Vada    0.933780    1.800
81           Keano Vanrafelghem    0.933615    0.900
182                 Tom Reyners    0.927780    0.800
21              Butta Magomedov    0.912831    0.600
36                Pablo Roberto    0.888756    0.800
188                Alex Bermejo    0.846414    0.400
59          Nikolai Giorgobiani    0.820585    0.500
231               Takuro Kaneko    0.809517    1.500
27                 Miguel Sousa    0.773515    0.500
117                  Rony Lopes    0.748617    2.000
168               Daniel Borges    0.741775    0.400
113              Florent Mollet    0.731100    1.200
22               Reziuan Mirzov    0.723247    0.500
190              Sergio Bermejo    0.721346    0.900
4              Gerard Vandeplas    0.709396    0.400
251           Geoffry Hairemans    0.703048    0.500
104                  Rui Mendes    0.634913    0.350
180            Anton Zinkovskiy    0.628396    2.500
109               Diego Collado    0.621573    0.400
73                 Thomas Bruns    0.618905    0.250
116             James Rodriguez    0.615475    2.500
77                Dylan Mertens    0.576712    0.500
234             Mikhail Ignatov    0.563194    1.000
229              Samuel Bastien    0.532003    0.650
205                   Adi Nalic    0.525838    0.350
88           Yair Mena Palacios    0.511981    0.100
214             Lucas Fernandes    0.506515    1.500
259                 Kamal Sowah    0.501844    0.800
159       Richard van der Venne    0.497063    0.225
54           Svetoslav Kovachev    0.494718    0.800
47                  Moussa Kone    0.477319    0.400
9                 Mehdi Merghem    0.475851    0.450
241               Manuel Namora    0.468457    0.100
257             Patrick Joosten    0.457281    0.275
90               Casper Staring    0.450578    0.350
275            Argyrios Darelas    0.447743    0.250
169             Soren Tengstedt    0.439902    0.800
106            Marco van Ginkel    0.429691    0.400
56                   Thabo Cele    0.414563    0.350
261              Rafael Barbosa    0.411958    0.350
60                 Kevin Felida    0.396039    0.200
48               Danilo Al Saed    0.311310    0.800
243          Rajiv van La Parra    0.269320    0.200

In [72]:
base_cols = ['G+A', 'G+A.1', 'Ast.1', 'Sh/90', '90s', 'Fld', 'G/SoT', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']

In [75]:
cols_to_add = [col for col in all_cols if not(col in base_cols)]
new_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_add:
    X_train_new = X_train[base_cols + [col]]
    X_test_new = X_test[base_cols + [col]]
    LR_regressor.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new<mae_test or mape_new<mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=new_cols.columns, index=[col])
        new_cols = pd.concat([new_cols, row])
new_cols

             mae      mape        r2
base    4.868575  0.848586  0.516078
Starts  4.652191  1.065595 -0.266716
Gls     4.834931  1.101207 -0.548908
Ast     4.834931  1.101207 -0.548908
G-PK    4.738015  1.096229 -0.401524
PK      4.828316  1.116326 -0.459347
PKatt   4.854903  1.117976 -0.501586
Fls     4.734653  1.109610 -0.337099
TklW    4.752886  1.110109 -0.440269
OG      4.868440  1.117182 -0.520659
SoT%    4.861029  1.128782 -0.480368
SoT/90  4.867424  1.117605 -0.508637

In [76]:
cols_to_delete = [col for col in base_cols if not(col.startswith('league'))]
del_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_delete:
    X_train_new = X_train[[c for c in base_cols if c != col]]
    X_test_new = X_test[[c for c in base_cols if c != col]]
    LR_regressor.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new < mae_test or mape_new < mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=del_cols.columns, index=[col])
        del_cols = pd.concat([del_cols, row])
del_cols

            mae      mape        r2
base   4.868575  0.848586  0.516078
Ast.1  4.716678  1.236882 -0.469451
Fld    4.854948  1.108384 -0.440092