In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pd.set_option('display.max_rows', None)

In [54]:
X_train = pd.read_csv('csv/final_datasets/for_linear_model/DF/predictors_train_filtered.csv')
X_test = pd.read_csv('csv/final_datasets/for_linear_model/DF/predictors_test_filtered.csv')
y_train = pd.read_csv('csv/final_datasets/for_linear_model/DF/target_train_filtered_logariphmed.csv')
y_test = pd.read_csv('csv/final_datasets/for_linear_model/DF/target_test_filtered_logariphmed.csv')

In [5]:
train_players = pd.read_csv('csv/final_datasets/for_linear_model/DF/train_players_names.csv')
test_players = pd.read_csv('csv/final_datasets/for_linear_model/DF/test_players_names.csv')

In [6]:
all_cols = X_train.columns
all_cols

Index(['Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
       '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh', 'SoT',
       'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'],
      dtype='object')

## Регрессор

In [56]:
LR_regressor = LinearRegression()
LR_regressor.fit(X_train, y_train)

LinearRegression()

## Предсказанные значения

In [57]:
y_pred_log = LR_regressor.predict(X_test)
y_pred = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

y_train_pred = np.exp(LR_regressor.predict(X_train))
y_train_original = np.exp(y_train)

## Метрики

In [58]:
mae_test = mean_absolute_error(y_test_original, y_pred)
rmse_test = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2_test = r2_score(y_test_original, y_pred)
mape_test = mean_absolute_percentage_error(y_test_original, y_pred)

mae_train = mean_absolute_error(y_train_original, y_train_pred)
rmse_train = np.sqrt(mean_squared_error(y_train_original, y_train_pred))
r2_train = r2_score(y_train_original, y_train_pred)
mape_train = mean_absolute_percentage_error(y_train_original, y_train_pred)

metrics = pd.DataFrame({
    'MAE':[mae_test, mae_train],
    'RMSE':[rmse_test, rmse_train],
    'MAPE':[mape_test, mape_train],
    'R2':[r2_test, r2_train]
}, index = ['test', 'train'])

## Остатки

In [59]:
y_pred = pd.Series(np.reshape(y_pred, len(y_pred)), name='Value_pred')
y_train_pred = pd.Series(np.reshape(y_train_pred, len(y_train_pred)), name='Value_pred')

comp_leftovers_test = pd.concat([test_players, y_pred, y_test_original], axis=1)
comp_leftovers_train = pd.concat([train_players, y_train_pred, y_train_original], axis=1)

## Коэффициенты

In [60]:
coeffs = LR_regressor.coef_[0]
coeffs_df = pd.DataFrame({
    'coeff':coeffs.astype('float')
}, index=X_train.columns)
coeffs_df = coeffs_df.sort_values(by='coeff', key=abs, ascending=False)

# Все переменные

In [99]:
coeffs_df

                coeff
90s         23.536915
Min        -23.505636
G+A.1       -1.039924
G+A-PK       1.027266
league_GB1   0.644170
Age         -0.574810
G-PK.1      -0.368688
league_IT1   0.364808
league_L1    0.324781
Starts       0.314362
Gls.1        0.311172
league_ES1   0.306656
league_FR1   0.268930
Crs         -0.185063
Ast          0.175336
Sh/90        0.157308
league_NL1  -0.132026
G+A          0.124696
Fls          0.103969
Sh           0.096531
league_PO1  -0.091982
TklW        -0.085759
SoT/90      -0.069824
OG          -0.063155
SoT          0.062155
CrdY        -0.057126
2CrdY        0.048279
G/Sh         0.048112
SoT%         0.042698
Int         -0.029464
CrdR        -0.023761
league_RU1  -0.019439
PK           0.015913
G-PK        -0.011296
MP           0.010251
Fld          0.009477
G/SoT        0.007883
Gls         -0.007571
PKatt       -0.007407
Off          0.001521
Ast.1        0.000341

In [13]:
metrics

            MAE       RMSE      MAPE        R2
test   5.741616  12.221873  0.904190  0.184838
train  4.626652   9.346249  0.872897  0.382257

In [17]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                               Player  Value_pred   Value
664                      Milos Kerkez   95.261310  45.000
730                    Nathan Collins   74.871969  28.000
412                      Dean Huijsen   66.580929  60.000
784                      Daniel Munoz   62.514942  25.000
890                      Levi Colwill   58.217044  55.000
56             Trent Alexander-Arnold   54.636312  75.000
342                 Nikola Milenkovic   54.625294  35.000
25                      Neco Williams   45.419707  20.000
10                        Pedro Porro   44.669265  38.000
472                    Jurrien Timber   41.614041  55.000
777                   Maxence Lacroix   41.599193  25.000
1                     Tyrick Mitchell   41.485364  25.000
795             Taylor Harwood-Bellis   40.915777  22.000
503                           Murillo   40.302756  55.000
320                       Diogo Dalot   38.301037  30.000
213                Jan Paul van Hecke   37.328043  32.000
9                         Dara O'Shea   35.714693  14.000
303                    William Saliba   34.706759  80.000
572                      James Justin   32.589757  13.000
178                        Lewis Hall   32.455802  32.000
206                    Illia Zabarnyi   32.106663  42.000
836                 Sepp van den Berg   31.911261  22.000
702                       Pau Cubarsi   31.265308  80.000
772                   Raoul Bellanova   30.457317  24.000
138                      Robin Gosens   29.605084   8.000
147                      Nuno Tavares   29.482645  25.000
228                 Aaron Wan-Bissaka   29.324154  24.000
522                        Malo Gusto   28.695096  35.000
734                Jarrad Branthwaite   28.258627  50.000
315                     Conor Bradley   27.465432  30.000
771                   Trevoh Chalobah   24.884148  25.000
205                  Matthijs de Ligt   24.827422  38.000
183                     Nelson Semedo   23.483660   9.000
533                Alessandro Bastoni   23.222187  80.000
362                     Achraf Hakimi   23.050598  80.000
451                     Nico O’Reilly   22.713822  18.000
390                Kyle Walker-Peters   22.286023  15.000
621                   Alejandro Balde   21.941432  60.000
104                 Charlie Cresswell   21.935977  10.000
236                  Emmanuel Agbadou   21.704628  20.000
607                      Anthony Caci   21.425891  12.000
655                    Destiny Udogie   21.330253  40.000
805                     Luka Vuskovic   21.229730  12.000
264                     Jacob Greaves   20.987099  18.000
208                       Djed Spence   20.490155  20.000
785                     Tariq Lamptey   20.476063  11.000
456                       Harry Amass   20.221671   5.000
69                         Ezri Konsa   20.032648  35.000
628                    Chris Richards   19.919148  14.000
724                         Leny Yoro   19.217626  55.000
177                        James Hill   19.020076   3.000
101                    Theo Hernandez   18.924578  35.000
743                     Alex Grimaldo   18.894545  30.000
418                        Kike Salas   18.799912   8.000
541                     Obite N'Dicka   18.751471  30.000
871                 Lisandro Martinez   18.553526  40.000
326                        Leif Davis   17.711408  22.000
834                      Fabian Schar   17.439957   7.000
28                      Sergi Cardona   17.362088  10.000
899                       Jorrel Hato   17.140914  35.000
81                    Florian Lejeune   17.105039   2.500
877                    Bafode Diakite   17.058749  28.000
377                    Michael Kayode   16.955218  18.000
787                      Jake O'Brien   16.913226  18.000
393                        Kenny Tete   16.490759  13.000
761                Yann Aurel Bisseck   16.056430  35.000
53                           Ola Aina   16.032578  22.000
204                        Guela Doue   15.961938  18.000
142                  Pervis Estupinan   15.753340  30.000
242                      Mamadou Sarr   15.629337  20.000
299                Sebastiano Luperto   15.590216   4.000
866                     Johan Vasquez   15.580825  14.000
411                    Quentin Merlin   15.532447  15.000
591                      Luca Ranieri   15.419069  12.000
558                       Tim Oermann   15.367397   5.000
576                  Tosin Adarabioyo   15.362773  20.000
118                    Danilho Doekhi   15.103185  13.000
747                       Enzo Boyomo   14.908101  20.000
603                        Matty Cash   14.799888  25.000
741                              Dodo   14.785064  24.000
432                   Virgil van Dijk   14.630503  23.000
42                      Radu Dragusin   14.362280  25.000
861           Konstantinos Mavropanos   14.357113  17.000
496                Cristhian Mosquera   14.193273  30.000
304                Nico Schlotterbeck   14.167740  40.000
310                      Andrei Ratiu   13.952640  12.000
94                     Piero Hincapie   13.834185  50.000
98                    James Tarkowski   13.573292   9.000
840         Victor Bernth Kristiansen   13.382579  15.000
329                      Jan Bednarek   13.167584   9.000
608                       Caleb Okoli   13.013543  10.000
108                     Cesar Tarrega   12.994366  10.000
661                       Sam Beukema   12.930086  28.000
443                   Ramy Bensebaini   12.873701   7.000
352                   Lasse Rosenboom   12.847899   1.500
89                     Koni De Winter   12.781675  22.000
427                        Ruben Dias   12.706604  65.000
870                     Arthur Theate   12.597299  24.000
474                    Pietro Comuzzo   12.459105  25.000
122                         Ben White   12.296260  45.000
394                 Jean-Clair Todibo   12.294482  25.000
255                   Cristian Romero   12.199002  50.000
494                     Amir Rrahmani   12.196022  12.000
596                  Saba Goglichidze   12.192564   8.000
791                         Jay Idzes   12.154094   7.500
710              Federico Baschirotto   11.996109   3.600
131                       Nuno Mendes   11.956767  70.000
397                    Santiago Bueno   11.833231  10.000
908                     Carlos Romero   11.774753   5.000
121                    Giovanni Leoni   11.702555  18.000
398                       Mattia Viti   11.701997   5.500
312                   Cameron Burgess   11.407458   2.000
375                      Juan Miranda   11.270709  15.000
466                     Nicolo Savona   11.229435  12.000
97                   Nathan Patterson   11.199102  15.000
241                    Carlos Augusto   11.126812  26.000
617                     Joakim Maehle   11.094026  14.000
35                      Omar Alderete   11.090406   8.000
119                       Sven Botman   10.827179  42.000
293                         Vanderson   10.803752  20.000
715                       Diogo Leite   10.696464  17.000
798                     Manuel Akanji   10.587947  28.000
129                 Rasmus Kristensen   10.559188  14.000
388                          Dan Burn   10.413417   6.000
850                        Jon Martin   10.387839   8.000
802                Strahinja Pavlovic   10.295622  18.000
481                         Saul Coco   10.267762  10.000
507                      Aaron Martin   10.263652   6.500
778                         Welington   10.224358   3.000
714                        Adam Obert   10.184280   3.000
885                        Mario Gila   10.170606  30.000
718                        Jaka Bijol   10.064269  18.000
786                    Federico Gatti   10.002833  24.000
60                   Enrico Del Prato    9.976692   6.500
346                   Kristoffer Ajer    9.933320  18.000
379                     Julian Chabot    9.910002  12.000
625                    Facundo Medina    9.834036  25.000
649                            Morato    9.833653  14.000
703            Ainsley Maitland-Niles    9.698577  12.000
690                     Axel Tuanzebe    9.679856   5.000
184                           Carmona    9.575257  12.000
287                        Pau Torres    9.466717  32.000
854                    Omar El Hilali    9.353170  15.000
898                   Marash Kumbulla    9.326349   7.500
630                   Alberto Dossena    9.316493   8.000
369                  Abdulai Juma Bah    9.275441   6.000
323                 Zakaria El Ouahdi    9.172546  12.000
859                    Jeremy Jacquet    9.094478  10.000
276                       Luke Thomas    9.018406   6.000
243                    Edmond Tapsoba    8.995763  35.000
513                    Ki-Jana Hoever    8.938527   5.000
742                   Lilian Brassier    8.875003  10.000
493                 Chrislain Matsima    8.805271  22.000
225                   Yerson Mosquera    8.729232   8.000
141                     Matteo Gabbia    8.714040  14.000
128                       Hector Fort    8.674756  10.000
399                    Gabriele Zappa    8.661802   4.000
729                    Nnamdi Collins    8.620641  10.000
169                             Natan    8.507611   9.000
71                      Frans Kratzig    8.489349   3.500
163                    Matteo Ruggeri    8.446456  16.000
410                  Gianluca Mancini    8.415731  15.000
347                        Saidou Sow    8.410226   6.000
136                  Santiago Mourino    8.406600   3.000
132                      Raul Asencio    8.392572  40.000
766                         Loic Bade    8.377104  25.000
479                     Lucas Beraldo    8.365271  25.000
590               Giovanni Di Lorenzo    8.328389  12.000
762                      Givairo Read    8.327922  16.000
73             El Chadaille Bitshiabu    8.318359  18.000
171                   Luca Marianucci    8.317186   7.500
666                     Julian Araujo    8.228031  10.000
817                  Daniele Ghilardi    8.225400   5.000
598                      Jonathan Tah    8.180677  30.000
76                         Ko Itakura    8.091276  12.000
819                     Arthur Chaves    7.917799   5.000
356                       Kevin Danso    7.895595  25.000
430                     Konrad Laimer    7.883505  25.000
476              Lutsharel Geertruida    7.860015  20.000
221                      Nasser Djiga    7.855207  10.000
447                 Thomas Kristensen    7.840362   6.000
219                  Ousmane Diomande    7.781654  45.000
237                       Lucas Digne    7.751337  10.000
758                   Luca Pellegrini    7.705168   3.000
152                   Mathias Olivera    7.673712  20.000
58                   Valentin Gendrey    7.672910   7.000
21                  Christian Mawissa    7.623047  15.000
615                 Leonidas Stergiou    7.563988   5.000
807                       Timo Becker    7.558597   1.500
839                  Martim Fernandes    7.536527  12.000
574                    Phillipp Mwene    7.534806   1.800
67                     Patrick Mainka    7.489323   3.000
614                     Pierre Kalulu    7.476088  28.000
247                        James Bree    7.460783   2.500
594                     Gabriel Suazo    7.451224   4.000
650                   Luke Woolfenden    7.447379   2.000
538             Ignace Van Der Brempt    7.427002   4.000
731                    Jorge Herrando    7.382517   4.000
420                       Anrie Chase    7.359417   3.000
134                       Nathan Zeze    7.349711  15.000
5                       Aitor Paredes    7.316191  22.000
282                      Sael Kumbedi    7.295850   7.000
34                    Emmanuel Biumla    7.276082   4.000
188             Etienne Youte Kinkoue    7.269038   7.000
512                        Zeki Celik    7.261262   6.000
480                       Juan Herzog    7.236997   2.500
361                     Willian Pacho    7.234534  65.000
573                      Jorge Cuenca    7.217422   5.000
694                       Mika Marmol    7.197895  10.000
416                 Davide Zappacosta    7.102812   5.000
875               Lucas Oliveira Rosa    7.098159   3.000
286                  Timothy Castagne    7.054730  13.000
674                     Ryan Flamingo    7.015539  20.000
441             Giorgos Kyriakopoulos    6.994893   2.500
84                    Benedikt Gimber    6.969032   3.000
232                        Luck Zogbe    6.950853   2.500
424                        Adam Aznou    6.904051   4.000
727                        Amar Dedic    6.864947  12.000
415                         Luca Netz    6.855807   6.000
531                 Benoît Badiashile    6.852409  22.000
114                        Robin Koch    6.831477  18.000
585         Abdoulaye Niakhate Ndiaye    6.805986   4.000
680                    Antonio Raillo    6.755969   1.800
847                   Alexander Prass    6.688099   5.000
408                 Kosta Nedeljkovic    6.684010  10.000
258                    Becir Omeragic    6.680359   4.500
691                   Max Rosenfelder    6.680268   8.000
905                      David Nemeth    6.676001   4.000
901                   Fabio Chiarodia    6.669756   2.000
294                         Isak Hien    6.630620  30.000
90                           Kialonda    6.615510   3.500
105                 Marc-Oliver Kempf    6.486455   3.000
145                Leo Skiri Østigard    6.450452  10.000
556                         David Zec    6.445435   2.500
116                     Ethan Pinnock    6.402914   7.000
185                   Matthias Ginter    6.373512   7.000
701                      Marko Ivezic    6.355135   2.000
291                      Clement Akpa    6.256035   5.000
551                    Waldemar Anton    6.241701  18.000
686                 Alessio Romagnoli    6.229578   7.000
881             Alessandro Buongiorno    6.182367  50.000
853                    Kilian Fischer    6.143069   6.000
883                     Harry Maguire    6.119844  13.000
378             Sebastian Walukiewicz    6.119640   4.500
555              Souffian El Karouani    6.043137   9.000
852                   Arouna Sangante    6.037184   8.000
251                         Joe Gomez    6.010434  20.000
396                          Ze Vitor    6.009555   2.000
620                      Archie Brown    5.997721   7.000
562                     Moise Bombito    5.992577  10.000
677                   Lautaro Valenti    5.985970   1.500
199                      Adam Webster    5.942507  11.000
794                       Axel Disasi    5.941810  22.000
284                       Conor Coady    5.912241   2.200
845                            Arthur    5.888815   7.000
191                       Jhon Lucumi    5.872224  22.000
515                     Adrià Pedrosa    5.808146   7.000
40                 Abdukodir Khusanov    5.743246  35.000
120                        Leo Petrot    5.712533   0.900
848                      Manu Sanchez    5.701911   6.000
564                  Christopher Wooh    5.695527   6.000
842                 Joel Schingtienne    5.685074   3.500
668                  Odilon Kossounou    5.648486  25.000
613                     Max Geschwill    5.630642   1.500
487                    Bart van Rooij    5.621051   6.000
340                    Rafik Belghali    5.573198   2.500
47                         Juan Foyth    5.568473  15.000
274                      Matt Doherty    5.534348   2.000
270                     Nahuel Molina    5.529506  20.000
249                     Noahkai Banks    5.521307   6.000
281                       Pau Navarro    5.512009   3.000
15                         Sacha Boey    5.497159  18.000
803                       Jakov Medic    5.489440   2.000
902                   Nahuel Tenaglia    5.483026   3.000
389                    Stefan Lekovic    5.480032   1.700
196                     Aurele Amenda    5.475341   7.500
735              Andreas Hanche-Olsen    5.469132   6.000
435                      Mickael Nade    5.467854   2.000
336                Alessandro Circati    5.438938   8.000
39                    Valentin Rosier    5.409343   3.000
353                  Leonardo Balerdi    5.399314  20.000
792                       Moritz Jenz    5.398760   5.000
49                     Martin Valjent    5.391815   6.000
160                     Michael Keane    5.390833   5.000
260                       Denis Vavro    5.387769   7.000
455                   Antonio Candela    5.375861   1.800
452                  Timothee Pembele    5.359543   2.500
235                Jeffrey Gouweleeuw    5.348391   1.500
117                  Olivier Boscagli    5.342472  20.000
548                   Jan-Carlo Simic    5.339339   8.000
514                Sebastiaan Bornauw    5.308787   6.000
211                     Modibo Sagnan    5.308579   3.000
41                  Nicolas Valentini    5.253822   6.000
618                 Kiliann Sildillia    5.229534  10.000
893                  Philipp Lienhart    5.209991  12.000
810                      Malick Thiaw    5.166475  18.000
95                  Yarek Gasiorowski    5.143301   7.500
33                        Omar Traore    5.126333   4.000
365                David Moller Wolfe    5.115997   9.000
860                         Gaby Jean    5.110742   2.000
892                       Jordan Teze    5.084401   9.000
511                      Abakar Sylla    5.083518  10.000
271                       Angel Ortiz    5.082513   2.500
195                        Javi Lopez    5.054499   7.500
693                  Robin Le Normand    5.045656  40.000
174                    Gautier Lloris    5.043688   3.000
464                      Fellipe Jack    5.030618   1.400
167                      Yael Mouanga    5.020858   0.600
133                   Leandro Cabrera    4.994400   1.000
756                        Umit Akdag    4.994373   0.600
295                 Kingsley Ehizibue    4.984244   2.400
745                  Juan David Cabal    4.980848   9.000
61                       Ivan Smolcic    4.972940   1.800
804                      Niklas Stark    4.969897   4.000
127                  Lucas Mincarelli    4.963896   0.900
334                    Almugera Kabar    4.956884   1.000
181           Anselmo Garcia MacNulty    4.937325   1.500
37                     Hassane Kamara    4.931647   3.500
278                      David Hancko    4.931386  30.000
508                     Igor Zubeldia    4.899234  12.000
44                  Mikayil Ngor Faye    4.866911   6.000
74                      Hiroki Sekine    4.841556   1.200
688                 Maximilian Wittek    4.830611   1.500
381               Gabriel Gudmundsson    4.802946   7.000
70                     Marco Palestra    4.799863   3.500
72                          Emil Holm    4.799440   8.000
380                      Tiago Santos    4.782535  15.000
417                 Alejandro Frances    4.772709   2.000
439                     Antonio Silva    4.766552  32.000
470                        David Raum    4.761160  20.000
889                    Ardian Ismajli    4.753269   6.000
903                  Souleymane Toure    4.751794   7.000
175                       Nico Elvedi    4.739033   8.000
770                     Jesus Vazquez    4.721869   3.000
80                     Ramon Hendriks    4.692912   5.000
428                       Igor Diveev    4.687271   8.000
684                   Kostas Tsimikas    4.675626  18.000
68                Dimitris Giannoulis    4.674612   3.000
816                 Guillermo Maripan    4.657480   4.000
790                            Copete    4.633392   3.000
0              Alessandro Marcandalli    4.630789   2.000
473                     Erhan Masovic    4.615588   2.000
469                       Enzo Tchato    4.588542   2.500

In [16]:
comp_leftovers_test.sort_values('Value_pred', ascending=False)

                       Player  Value_pred   Value
23            Rayan Ait-Nouri  139.935654  35.000
77             Josko Gvardiol   65.011485  75.000
168          Antonee Robinson   46.375016  35.000
179            Marc Cucurella   34.725967  35.000
136         Gabriel Magalhaes   31.674999  75.000
86            Ibrahima Konate   31.669813  60.000
82              Calvin Bassey   28.116200  25.000
201                Marc Guehi   27.954755  45.000
60                Ian Maatsen   27.933642  28.000
227        Myles Lewis-Skelly   27.568274  45.000
31   Konstantinos Koulierakis   22.688031  25.000
133                Max Kilman   21.860609  25.000
94            Emanuele Valeri   20.926972   3.000
30           Micky van de Ven   19.549796  50.000
2          Riccardo Calafiori   18.026020  35.000
63                  Wout Faes   17.607367  15.000
110         Vitaliy Mykolenko   17.160934  28.000
54          Noussair Mazraoui   16.579146  25.000
66             Javi Rodriguez   16.302200  15.000
214          Leopold Querfeld   16.251845  13.000
211             Diego Coppola   15.732839  10.000
143               Logan Costa   15.313902  18.000
59                 Toti Gomes   14.941285  28.000
114            Wilfried Singo   12.986136  25.000
192             Lukas Ullrich   12.729574   8.000
25            Anthony Rouault   12.633721  10.000
164               Oumar Solet   11.783522  18.000
21              Pedro Pereira   11.477033   1.500
141        Nathan Wood-Gordon   11.277329   3.500
171                    Catena   11.140938   3.000
98              Wesley Fofana   10.997606  25.000
123             Mads Roerslev   10.293846   6.000
1             Alphonso Davies   10.228542  50.000
11              Daniel Vivian    9.355340  40.000
5                Harry Clarke    9.300691   4.500
184              Jules Kounde    9.192284  65.000
228        Alexsandro Ribeiro    9.009567  20.000
200             Sergio Akieme    8.927513   7.000
212            Julian Ryerson    8.798686  20.000
220           Sinaly Diomande    8.772341   5.000
172            Jarell Quansah    8.640240  20.000
34                Abdel Abqar    8.444753   7.500
12     Maximilian Mittelstadt    8.362140  20.000
147                  Angelino    8.301834  20.000
0                Jon Aramburu    7.977286  15.000
36              Gerard Martin    7.854182  12.000
87              Botond Balogh    7.697177   2.400
93                 Alex Valle    7.692190   6.000
204             Alan Matturro    7.676112   7.000
149            Javi Hernandez    7.628361   2.500
104            Cedric Zesiger    7.587020   7.000
8                  Yerry Mina    7.553148   3.000
124             Jordan Zemura    7.544325   4.500
51           Giorgio Scalvini    7.532757  35.000
125            Andrea Carboni    7.406185   2.800
132              Finn Jeltsch    7.226040  20.000
101                 Issa Diop    7.117670  14.000
67                Lloyd Kelly    7.080113  16.000
83       Michael Amir Murillo    7.039406  10.000
173                Joe Scally    7.039067  10.000
154             Antoine Mendy    6.997270   2.500
189               Kim Min-jae    6.846957  40.000
65                Tim Drexler    6.749824   3.000
15                Ali Dembele    6.603014   0.900
134              Thilo Kehrer    6.588336  20.000
37                   Iglesias    6.506009   3.500
100        Soumaila Coulibaly    6.446946   8.000
215            Willy Kambwala    6.424261   4.000
182                      Igor    6.372201  20.000
150               Fran Garcia    6.359941  18.000
92                Ilay Camara    6.219677   4.000
155           Castello Lukeba    6.103436  40.000
58      Youssouf Ndayishimiye    6.062960  12.000
165             Marcos Senesi    5.966206  22.000
221           Ladislav Krejci    5.963893  12.000
148             Rafik Messali    5.947855   0.800
157                 Yoel Lago    5.782095   1.000
56                  Felix Agu    5.702543   8.000
137        Anass Salah-Eddine    5.633552   8.000
27                Abdul Mumin    5.590673   5.000
97              Egor Teslenko    5.575651   2.000
4              Romain Perraud    5.557195   5.000
226               Chico Lamba    5.336038   3.000
73             Goncalo Inacio    5.154693  45.000
3                  Fali Cande    5.108790   2.500
170            Inigo Martinez    5.106614   5.000
19           Mahamadou Nagida    5.102275   0.800
103           Dayot Upamecano    4.994647  50.000
195             Jack Stephens    4.947467   1.500
160       Keven Schlotterbeck    4.922001   6.000
229          Domagoj Bradaric    4.893131   4.000
126          Andrew Robertson    4.806203  18.000
74               Javi Sanchez    4.766780   1.500
107              David Torres    4.624332   1.500
44           Andrey Langovich    4.612935   3.000
57           Flavius Daniliuc    4.576522   2.700
102               Jesus Areso    4.568344  12.000
95               Armando Izzo    4.566214   1.500
198            Berat Djimsiti    4.499141   6.000
78            Tommaso Augello    4.452266   1.800
183            Tomas Palacios    4.328244   4.000
202         Tsuyoshi Watanabe    4.274918   9.000
14         Jannik Vestergaard    4.220167   2.000
121           Moussa Niakhate    3.944018  15.000
219              Adam Marusic    3.904396   3.500
177              Kelvin Amian    3.879190   2.500
111                Hauke Wahl    3.782437   1.500
52                 Rico Henry    3.701515  15.000
42                Jonas Rouhi    3.697953   2.000
159               Malang Sarr    3.667628   5.000
163           Mohammed Salisu    3.614272  12.000
129              Joseph Okumu    3.612837   7.000
117             Scott McKenna    3.489702   4.000
158            Emmanuel Kakou    3.437587   1.000
222               Emil Krafth    3.422742   2.000
91           Mouctar Diakhaby    3.336467   2.000
167              Semm Renders    3.272143   1.500
50              Jordy Makengo    3.254619   6.000
69            Cristian Castro    3.217304   0.800
185               Matte Smets    3.149631  13.000
35                 Bamo Meite    3.145809   4.000
209             Juan Berrocal    3.118918   1.500
48            Thierry Correia    3.076603   3.000
205         Francesco Zampano    3.054992   1.000
116                      Nino    3.031068  11.000
88                Amos Pieper    3.022910   3.500
32                Anton Gaaei    2.947445   7.000
118                 Mats Rots    2.906303   1.000
203               Dinis Pinto    2.904220   1.500
109       Giangiacomo Magnani    2.785824   1.800
169        Brendan Chardonnet    2.761444   6.000
108                Karol Fila    2.615186   0.600
206              Robert Gumny    2.563427   1.500
188         Roberto Fernandez    2.544712   3.500
22          Milan Majstorovic    2.526402   1.800
49              Marco Komenda    2.507438   0.800
55                 Hugo Bueno    2.495888   8.000
187            German Ignatov    2.492161   0.500
176           Matija Nastasic    2.413581   0.800
13                 Alex Munoz    2.382557   1.000
131                Diego Rico    2.382166   1.200
166              Andy Pelmard    2.308619   2.000
29           Eduardo Quaresma    2.284553  18.000
190             Ibe Hautekiet    2.267540   3.500
80              Ryan Alebiosu    2.261963   0.500
225        Jose Maria Gimenez    2.223799  20.000
152        Christian Kabasele    2.221612   0.700
9                 Aiham Ousou    2.213279   2.500
79                Ivan Ordets    2.190099   1.000
38             Egor Pogostnov    2.182738   1.800
39             Ricardo Mangas    2.158513   2.500
208             Thomas Beelen    2.149532   8.000
191                    Moises    2.124292   5.000
119         Godfried Frimpong    2.104377   2.000
161            Jose Luis Gayà    2.099820   9.000
10            Youssouf Sabaly    2.046579   1.800
210           Maksim Nenakhov    2.045866   3.000
105              Craig Dawson    1.986459   1.500
218              Manuel Osifo    1.970421   0.700
186             Ricardo Visus    1.908362   0.750
130                Marco Sala    1.899207   0.900
28      Przemyslaw Frankowski    1.862832   7.000
40         Mike van der Hoorn    1.804901   1.000
62            Duplexe Tchamba    1.796758   1.000
75              Ferland Mendy    1.783422  14.000
135           Brandon Mechele    1.774934   3.500
53               Victor Gomez    1.689306   6.000
194        Jordan Torunarigha    1.686082   4.000
224              Jordan Amavi    1.659021   1.500
43              Alexis Duarte    1.638024   3.000
41              Shawn Adewoye    1.622573   1.300
46           Mike Eerdhuijzen    1.610669   2.300
180          Maksim Shnaptsev    1.603846   0.300
96         Vasilios Zagaritis    1.591875   0.700
115            Manuel Lazzari    1.588432   3.500
20                Jonny Evans    1.566442   1.000
223          Massadio Haidara    1.549675   1.500
153              David Hrncar    1.492754   1.200
61             Evgeni Morozov    1.467612   3.000
193            Lucas Calegari    1.449111   3.500
89            Oleksandr Filin    1.440258   1.000
99                    Ben Mee    1.409427   0.700
196                Jose Gomes    1.365561   1.000
24                Tiago Djalo    1.319653   8.000
18              Stephen Welsh    1.294895   1.000
217         Toby Alderweireld    1.289037   2.000
127                Juan Jesus    1.283310   1.500
181               Ahmed Touba    1.266925   2.500
33               Sergino Dest    1.266070  16.000
216           Lucas Hernandez    1.262413  25.000
140                Kenny Lala    1.262291   2.000
113              Tiago Esgaio    1.254566   0.900
7            Zineddine Belaid    1.236366   0.800
213                    Orinho    1.198655   0.600
76              Boris Popovic    1.197903   1.500
128          Jonathan Mutombo    1.184146   0.500
26       Lorenzo De Silvestri    1.165303   0.800
175        Jose Luis Palomino    1.092114   0.700
138          Javier Manquillo    1.072649   1.000
16            Aleksei Tatayev    1.059874   0.800
45               Hamza Mendyl    1.055935   1.000
71               Eduard Sobol    1.044671   0.900
199          Mutalip Alibekov    1.008889   0.700
178             Marvin Elimbi    1.004418   0.750
174                    Michel    0.990369   1.000
106             Alexander Bah    0.983310  10.000
142     Aleksandr Soldatenkov    0.950372   4.000
81               Rafael Toloi    0.947735   1.400
145             Hjalmar Ekdal    0.916725   4.500
68               Ivan Marquez    0.865465   0.600
70              Igor Yurganov    0.859238   0.500
144           Abdoulaye Bamba    0.843280   0.300
197               Axel Witsel    0.808616   2.000
146           Thierry Lutonda    0.767534   0.300
112                Glenn Bijl    0.753863   1.500
120           Renato Pantalon    0.733170   0.600
122   Francisco Reis Ferreira    0.731872   0.700
156            Paulo Oliveira    0.720380   1.000
85          Mathias Jorgensen    0.585239   0.500
90      Boli Bolingoli-Mbombo    0.574549   0.500
151       Konstantin Savichev    0.554799   0.900
6                  Boyd Reith    0.532763   0.400
162            Wolke Janssens    0.498055   0.400
72        Patrick van Aanholt    0.479347   0.500
139       Redouan El Yaakoubi    0.469249   0.550
64               Carlos Ponck    0.443774   0.600
17            Marvin da Graca    0.424011   0.400
47            Ruben Fernandes    0.414048   0.050
207                Raul Silva    0.236426   0.100
84              Aaron Meijers    0.134707   0.075

In [27]:
comp_leftovers_train[comp_leftovers_train['Player'].str.contains('Petrov')]

               Player  Value_pred  Value
288  Hristiyan Petrov    0.911652    0.6
306     Sergei Petrov    0.493325    0.4

# Потенциальные переменные для добавления и удаления

In [158]:
base_cols = ['G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'G/Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']

In [160]:
cols_to_add = [col for col in all_cols if not(col in base_cols)]
new_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_add:
    X_train_new = X_train[base_cols + [col]]
    X_test_new = X_test[base_cols + [col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new<mae_test or mape_new<mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=new_cols.columns, index=[col])
        new_cols = pd.concat([new_cols, row])
new_cols

             mae      mape        r2
base    5.372967  0.917254  0.405040
MP      5.372435  1.135546 -0.254711
Starts  5.372608  1.131070 -0.254962
Min     5.346980  1.134117 -0.369775
Gls     5.370874  1.137968 -0.250175
PK      5.370874  1.137968 -0.250175
PKatt   5.372805  1.137722 -0.246176
CrdR    5.371681  1.141755 -0.248972
Fls     5.367723  1.150526 -0.362269
Off     5.371714  1.139739 -0.252983
SoT/90  5.371127  1.135702 -0.256291

In [161]:
cols_to_delete = [col for col in base_cols if not(col.startswith('league'))]
del_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_delete:
    X_train_new = X_train[[c for c in base_cols if c != col]]
    X_test_new = X_test[[c for c in base_cols if c != col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new < mae_test or mape_new < mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=del_cols.columns, index=[col])
        del_cols = pd.concat([del_cols, row])
del_cols

           mae      mape        r2
base  5.372967  0.917254  0.405040
Int   5.371651  1.140412 -0.272437
G/Sh  5.369203  1.139141 -0.269325

# Модель 1

In [31]:
X_train = X_train[['G+A', 'Ast', 'G-PK', 'Ast.1', 'Sh', 'SoT/90', '90s', 'Fld', 'Fls', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Ast', 'G-PK', 'Ast.1', 'Sh', 'SoT/90', '90s', 'Fld', 'Fls', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [37]:
coeffs_df

               coeff
league_GB1  0.644750
Age        -0.586466
90s         0.363879
league_IT1  0.363689
league_L1   0.323772
league_ES1  0.299015
Ast         0.288419
league_FR1  0.271033
G+A        -0.160010
G-PK        0.159311
TklW       -0.134078
league_NL1 -0.130379
Sh          0.110288
league_PO1 -0.093377
Sh/90       0.089491
Fls         0.084432
Fld        -0.020009
league_RU1 -0.018658
Int        -0.005621
Ast.1       0.003493
SoT/90     -0.000114

In [38]:
metrics

            MAE       RMSE      MAPE        R2
test   5.669392  11.283822  0.930519  0.305166
train  4.679034   9.559381  0.886455  0.353762

In [45]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                               Player  Value_pred   Value
664                      Milos Kerkez  110.517417  45.000
412                      Dean Huijsen   69.441752  60.000
10                        Pedro Porro   68.833300  38.000
56             Trent Alexander-Arnold   62.048535  75.000
730                    Nathan Collins   59.365208  28.000
890                      Levi Colwill   56.788238  55.000
342                 Nikola Milenkovic   49.625804  35.000
503                           Murillo   44.277455  55.000
784                      Daniel Munoz   44.093253  25.000
178                        Lewis Hall   41.802382  32.000
25                      Neco Williams   41.489142  20.000
795             Taylor Harwood-Bellis   40.777778  22.000
777                   Maxence Lacroix   37.887350  25.000
206                    Illia Zabarnyi   37.088276  42.000
320                       Diogo Dalot   35.249268  30.000
228                 Aaron Wan-Bissaka   33.607767  24.000
1                     Tyrick Mitchell   33.572114  25.000
472                    Jurrien Timber   31.953740  55.000
836                 Sepp van den Berg   31.770991  22.000
9                         Dara O'Shea   30.649127  14.000
326                        Leif Davis   30.412059  22.000
522                        Malo Gusto   30.044642  35.000
213                Jan Paul van Hecke   29.655559  32.000
772                   Raoul Bellanova   28.747218  24.000
572                      James Justin   28.224176  13.000
734                Jarrad Branthwaite   26.302577  50.000
303                    William Saliba   26.302342  80.000
805                     Luka Vuskovic   26.219356  12.000
702                       Pau Cubarsi   25.258023  80.000
451                     Nico O’Reilly   25.189867  18.000
743                     Alex Grimaldo   24.997265  30.000
724                         Leny Yoro   23.725043  55.000
147                      Nuno Tavares   22.846798  25.000
315                     Conor Bradley   22.562238  30.000
104                 Charlie Cresswell   22.502431  10.000
771                   Trevoh Chalobah   21.858564  25.000
142                  Pervis Estupinan   21.625056  30.000
205                  Matthijs de Ligt   21.550430  38.000
456                       Harry Amass   21.427248   5.000
101                    Theo Hernandez   20.611221  35.000
390                Kyle Walker-Peters   20.501457  15.000
834                      Fabian Schar   20.231063   7.000
607                      Anthony Caci   20.202383  12.000
208                       Djed Spence   19.895479  20.000
840         Victor Bernth Kristiansen   19.777970  15.000
375                      Juan Miranda   19.751030  15.000
264                     Jacob Greaves   19.559265  18.000
621                   Alejandro Balde   18.870413  60.000
741                              Dodo   18.862916  24.000
183                     Nelson Semedo   18.807822   9.000
362                     Achraf Hakimi   18.247872  80.000
655                    Destiny Udogie   18.127193  40.000
28                      Sergi Cardona   17.845493  10.000
69                         Ezri Konsa   17.521096  35.000
785                     Tariq Lamptey   17.449758  11.000
871                 Lisandro Martinez   16.652327  40.000
108                     Cesar Tarrega   16.489633  10.000
507                      Aaron Martin   16.430296   6.500
877                    Bafode Diakite   16.369034  28.000
53                           Ola Aina   16.183585  22.000
377                    Michael Kayode   16.030734  18.000
787                      Jake O'Brien   16.004776  18.000
236                  Emmanuel Agbadou   15.961158  20.000
866                     Johan Vasquez   15.682875  14.000
94                     Piero Hincapie   15.637253  50.000
418                        Kike Salas   15.590854   8.000
204                        Guela Doue   15.553250  18.000
427                        Ruben Dias   15.373031  65.000
533                Alessandro Bastoni   15.189715  80.000
541                     Obite N'Dicka   15.037581  30.000
603                        Matty Cash   14.859046  25.000
628                    Chris Richards   14.740041  14.000
242                      Mamadou Sarr   14.553800  20.000
177                        James Hill   14.523013   3.000
42                      Radu Dragusin   14.409453  25.000
908                     Carlos Romero   14.393491   5.000
388                          Dan Burn   14.355598   6.000
432                   Virgil van Dijk   14.275428  23.000
761                Yann Aurel Bisseck   14.144010  35.000
118                    Danilho Doekhi   14.064677  13.000
393                        Kenny Tete   14.052002  13.000
89                     Koni De Winter   13.743566  22.000
747                       Enzo Boyomo   13.681651  20.000
861           Konstantinos Mavropanos   13.679955  17.000
411                    Quentin Merlin   13.633323  15.000
474                    Pietro Comuzzo   13.161398  25.000
791                         Jay Idzes   13.046389   7.500
60                   Enrico Del Prato   12.908124   6.500
591                      Luca Ranieri   12.866046  12.000
81                    Florian Lejeune   12.836355   2.500
576                  Tosin Adarabioyo   12.810997  20.000
310                      Andrei Ratiu   12.608975  12.000
481                         Saul Coco   12.563806  10.000
558                       Tim Oermann   12.515523   5.000
329                      Jan Bednarek   12.461896   9.000
608                       Caleb Okoli   12.402488  10.000
441             Giorgos Kyriakopoulos   12.363118   2.500
496                Cristhian Mosquera   12.328871  30.000
299                Sebastiano Luperto   12.221262   4.000
870                     Arthur Theate   12.119982  24.000
394                 Jean-Clair Todibo   12.032556  25.000
718                        Jaka Bijol   12.022016  18.000
131                       Nuno Mendes   11.970052  70.000
493                 Chrislain Matsima   11.877036  22.000
129                 Rasmus Kristensen   11.867496  14.000
397                    Santiago Bueno   11.788303  10.000
898                   Marash Kumbulla   11.607617   7.500
138                      Robin Gosens   11.447056   8.000
596                  Saba Goglichidze   11.330437   8.000
122                         Ben White   11.323976  45.000
494                     Amir Rrahmani   11.226547  12.000
850                        Jon Martin   11.188432   8.000
241                    Carlos Augusto   11.113160  26.000
121                    Giovanni Leoni   11.052457  18.000
854                    Omar El Hilali   10.985819  15.000
710              Federico Baschirotto   10.962276   3.600
399                    Gabriele Zappa   10.950990   4.000
255                   Cristian Romero   10.810089  50.000
649                            Morato   10.669110  14.000
304                Nico Schlotterbeck   10.571837  40.000
276                       Luke Thomas   10.569392   6.000
97                   Nathan Patterson   10.541967  15.000
466                     Nicolo Savona   10.451432  12.000
237                       Lucas Digne   10.352315  10.000
690                     Axel Tuanzebe   10.344956   5.000
555              Souffian El Karouani   10.238626   9.000
98                    James Tarkowski   10.230824   9.000
617                     Joakim Maehle   10.203457  14.000
899                       Jorrel Hato   10.194826  35.000
35                      Omar Alderete   10.181823   8.000
885                        Mario Gila   10.066453  30.000
817                  Daniele Ghilardi    9.833482   5.000
312                   Cameron Burgess    9.806055   2.000
287                        Pau Torres    9.792020  32.000
293                         Vanderson    9.737064  20.000
798                     Manuel Akanji    9.736786  28.000
184                           Carmona    9.600654  12.000
661                       Sam Beukema    9.575531  28.000
352                   Lasse Rosenboom    9.535868   1.500
802                Strahinja Pavlovic    9.426698  18.000
479                     Lucas Beraldo    9.295970  25.000
346                   Kristoffer Ajer    9.288725  18.000
410                  Gianluca Mancini    9.287872  15.000
398                       Mattia Viti    9.277157   5.500
666                     Julian Araujo    9.275671  10.000
369                  Abdulai Juma Bah    9.219118   6.000
188             Etienne Youte Kinkoue    9.072020   7.000
729                    Nnamdi Collins    9.056831  10.000
766                         Loic Bade    9.026273  25.000
119                       Sven Botman    9.024948  42.000
715                       Diogo Leite    8.994360  17.000
141                     Matteo Gabbia    8.992193  14.000
778                         Welington    8.956983   3.000
243                    Edmond Tapsoba    8.956960  35.000
323                 Zakaria El Ouahdi    8.906123  12.000
71                      Frans Kratzig    8.905778   3.500
379                     Julian Chabot    8.890478  12.000
221                      Nasser Djiga    8.854476  10.000
128                       Hector Fort    8.794154  10.000
714                        Adam Obert    8.751480   3.000
225                   Yerson Mosquera    8.709380   8.000
625                    Facundo Medina    8.671107  25.000
598                      Jonathan Tah    8.669071  30.000
443                   Ramy Bensebaini    8.548061   7.000
163                    Matteo Ruggeri    8.485757  16.000
650                   Luke Woolfenden    8.299718   2.000
513                    Ki-Jana Hoever    8.224045   5.000
758                   Luca Pellegrini    8.200675   3.000
590               Giovanni Di Lorenzo    8.185076  12.000
136                  Santiago Mourino    8.154788   3.000
76                         Ko Itakura    8.123775  12.000
247                        James Bree    7.989207   2.500
694                       Mika Marmol    7.957660  10.000
470                        David Raum    7.889830  20.000
819                     Arthur Chaves    7.799493   5.000
810                      Malick Thiaw    7.798975  18.000
742                   Lilian Brassier    7.786248  10.000
171                   Luca Marianucci    7.733910   7.500
515                     Adrià Pedrosa    7.718666   7.000
447                 Thomas Kristensen    7.715110   6.000
347                        Saidou Sow    7.625719   6.000
859                    Jeremy Jacquet    7.599305  10.000
848                      Manu Sanchez    7.566071   6.000
688                 Maximilian Wittek    7.555178   1.500
416                 Davide Zappacosta    7.525032   5.000
169                             Natan    7.508433   9.000
286                  Timothy Castagne    7.507188  13.000
786                    Federico Gatti    7.481614  24.000
594                     Gabriel Suazo    7.439294   4.000
531                 Benoît Badiashile    7.412608  22.000
794                       Axel Disasi    7.404542  22.000
610                    Antonino Gallo    7.377360   4.300
34                    Emmanuel Biumla    7.342164   4.000
901                   Fabio Chiarodia    7.336142   2.000
680                    Antonio Raillo    7.295276   1.800
408                 Kosta Nedeljkovic    7.289036  10.000
134                       Nathan Zeze    7.271887  15.000
703            Ainsley Maitland-Niles    7.204842  12.000
73             El Chadaille Bitshiabu    7.197821  18.000
152                   Mathias Olivera    7.155297  20.000
573                      Jorge Cuenca    7.126615   5.000
40                 Abdukodir Khusanov    7.115027  35.000
614                     Pierre Kalulu    7.088879  28.000
219                  Ousmane Diomande    7.078935  45.000
875               Lucas Oliveira Rosa    7.056221   3.000
68                Dimitris Giannoulis    7.055708   3.000
430                     Konrad Laimer    7.026394  25.000
630                   Alberto Dossena    7.025845   8.000
701                      Marko Ivezic    7.015185   2.000
274                      Matt Doherty    7.000058   2.000
114                        Robin Koch    6.984939  18.000
291                      Clement Akpa    6.932311   5.000
883                     Harry Maguire    6.862576  13.000
574                    Phillipp Mwene    6.813964   1.800
556                         David Zec    6.798079   2.500
249                     Noahkai Banks    6.779020   6.000
191                       Jhon Lucumi    6.740243  22.000
33                        Omar Traore    6.739136   4.000
731                    Jorge Herrando    6.732806   4.000
613                     Max Geschwill    6.729947   1.500
905                      David Nemeth    6.725165   4.000
480                       Juan Herzog    6.693454   2.500
132                      Raul Asencio    6.686446  40.000
420                       Anrie Chase    6.638920   3.000
424                        Adam Aznou    6.612022   4.000
361                     Willian Pacho    6.608890  65.000
116                     Ethan Pinnock    6.588215   7.000
332                     Abel Bretones    6.548465   4.000
620                      Archie Brown    6.542883   7.000
415                         Luca Netz    6.541592   6.000
853                    Kilian Fischer    6.515680   6.000
145                Leo Skiri Østigard    6.515416  10.000
847                   Alexander Prass    6.508325   5.000
260                       Denis Vavro    6.486866   7.000
58                   Valentin Gendrey    6.476290   7.000
90                           Kialonda    6.468487   3.500
195                        Javi Lopez    6.365074   7.500
5                       Aitor Paredes    6.351296  22.000
67                     Patrick Mainka    6.318390   3.000
852                   Arouna Sangante    6.289607   8.000
564                  Christopher Wooh    6.286542   6.000
282                      Sael Kumbedi    6.262380   7.000
356                       Kevin Danso    6.259878  25.000
903                  Souleymane Toure    6.247021   7.000
727                        Amar Dedic    6.245989  12.000
232                        Luck Zogbe    6.225310   2.500
762                      Givairo Read    6.176744  16.000
21                  Christian Mawissa    6.130851  15.000
691                   Max Rosenfelder    6.125524   8.000
551                    Waldemar Anton    6.113435  18.000
469                       Enzo Tchato    6.057713   2.500
538             Ignace Van Der Brempt    6.049097   4.000
615                 Leonidas Stergiou    6.035326   5.000
585         Abdoulaye Niakhate Ndiaye    6.027211   4.000
612                    Flavio Nazinho    6.025090   3.000
378             Sebastian Walukiewicz    5.999904   4.500
902                   Nahuel Tenaglia    5.979969   3.000
618                 Kiliann Sildillia    5.978117  10.000
294                         Isak Hien    5.971385  30.000
127                  Lucas Mincarelli    5.957500   0.900
85                       Tuur Rommens    5.953779   4.000
548                   Jan-Carlo Simic    5.916345   8.000
258                    Becir Omeragic    5.906448   4.500
455                   Antonio Candela    5.883051   1.800
459                   Maxim De Cuyper    5.875675  16.000
512                        Zeki Celik    5.837469   6.000
381               Gabriel Gudmundsson    5.806175   7.000
476              Lutsharel Geertruida    5.785162  20.000
167                      Yael Mouanga    5.769060   0.600
95                  Yarek Gasiorowski    5.759957   7.500
686                 Alessio Romagnoli    5.753760   7.000
160                     Michael Keane    5.753337   5.000
389                    Stefan Lekovic    5.726262   1.700
92                         Lewis Dunk    5.699643   6.000
39                    Valentin Rosier    5.664779   3.000
807                       Timo Becker    5.662864   1.500
803                       Jakov Medic    5.633794   2.000
37                     Hassane Kamara    5.608923   3.500
660              Alessandro Vogliacco    5.600125   2.800
842                 Joel Schingtienne    5.589448   3.500
464                      Fellipe Jack    5.580772   1.400
839                  Martim Fernandes    5.559100  12.000
185                   Matthias Ginter    5.541039   7.000
845                            Arthur    5.490689   7.000
684                   Kostas Tsimikas    5.482553  18.000
165                       Marius Wolf    5.457604   3.000
72                          Emil Holm    5.441719   8.000
679      Caio Henrique Oliveira Silva    5.441402  15.000
281                       Pau Navarro    5.433196   3.000
44                  Mikayil Ngor Faye    5.415621   6.000
336                Alessandro Circati    5.397914   8.000
452                  Timothee Pembele    5.384718   2.500
511                      Abakar Sylla    5.369048  10.000
84                    Benedikt Gimber    5.355143   3.000
79                    Marcus Pedersen    5.337919   3.000
211                     Modibo Sagnan    5.333200   3.000
417                 Alejandro Frances    5.280021   2.000
425                    Bryan Reynolds    5.267665   3.500
562                     Moise Bombito    5.264525  10.000
677                   Lautaro Valenti    5.254206   1.500
49                     Martin Valjent    5.250605   6.000
80                     Ramon Hendriks    5.202155   5.000
893                  Philipp Lienhart    5.201765  12.000
656                    Ramon Martinez    5.199554   1.000
334                    Almugera Kabar    5.179551   1.000
668                  Odilon Kossounou    5.149230  25.000
41                  Nicolas Valentini    5.119947   6.000
190                      Dion De Neve    5.111194   0.900
251                         Joe Gomez    5.106537  20.000
271                       Angel Ortiz    5.084050   2.500
881             Alessandro Buongiorno    5.077495  50.000
365                David Moller Wolfe    5.069676   9.000
265                   Alvaro Carreras    5.018275  35.000
120                        Leo Petrot    4.995459   0.900
284                       Conor Coady    4.978213   2.200
270                     Nahuel Molina    4.976784  20.000
199                      Adam Webster    4.966882  11.000
514                Sebastiaan Bornauw    4.966283   6.000
770                     Jesus Vazquez    4.945343   3.000
181           Anselmo Garcia MacNulty    4.916666   1.500
674                     Ryan Flamingo    4.912166  20.000
105                 Marc-Oliver Kempf    4.897854   3.000
353                  Leonardo Balerdi    4.895028  20.000
380                      Tiago Santos    4.877614  15.000
110                     Moussa Diarra    4.839470   1.800
435                      Mickael Nade    4.819032   2.000
74                      Hiroki Sekine    4.811703   1.200
15                         Sacha Boey    4.794363  18.000
340                    Rafik Belghali    4.793547   2.500
693                  Robin Le Normand    4.789181  40.000
47                         Juan Foyth    4.779013  15.000
70                     Marco Palestra    4.765554   3.500
235                Jeffrey Gouweleeuw    4.764153   1.500
487                    Bart van Rooij    4.762446   6.000
0              Alessandro Marcandalli    4.727057   2.000
396                          Ze Vitor    4.712981   2.000
61                       Ivan Smolcic    4.710484   1.800
175                       Nico Elvedi    4.705570   8.000
508                     Igor Zubeldia    4.704806  12.000
133                   Leandro Cabrera    4.678699   1.000
792                       Moritz Jenz    4.676750   5.000
726                      Denso Kasius    4.675503   4.000
756                        Umit Akdag    4.642610   0.600

In [46]:
comp_leftovers_test.sort_values('Value_pred', ascending=False)

                       Player  Value_pred   Value
23            Rayan Ait-Nouri  104.374223  35.000
77             Josko Gvardiol   67.675446  75.000
168          Antonee Robinson   53.727674  35.000
201                Marc Guehi   36.639039  45.000
179            Marc Cucurella   31.037772  35.000
60                Ian Maatsen   27.540945  28.000
227        Myles Lewis-Skelly   27.308639  45.000
86            Ibrahima Konate   27.150344  60.000
136         Gabriel Magalhaes   25.938437  75.000
110         Vitaliy Mykolenko   25.143597  28.000
82              Calvin Bassey   24.685298  25.000
94            Emanuele Valeri   20.807788   3.000
31   Konstantinos Koulierakis   20.732447  25.000
133                Max Kilman   20.399734  25.000
2          Riccardo Calafiori   19.554488  35.000
211             Diego Coppola   17.950667  10.000
63                  Wout Faes   17.336356  15.000
214          Leopold Querfeld   17.155328  13.000
30           Micky van de Ven   15.855290  50.000
66             Javi Rodriguez   15.367384  15.000
59                 Toti Gomes   14.923275  28.000
192             Lukas Ullrich   13.944783   8.000
54          Noussair Mazraoui   13.126828  25.000
98              Wesley Fofana   12.309004  25.000
123             Mads Roerslev   11.861117   6.000
21              Pedro Pereira   11.525534   1.500
147                  Angelino   11.504964  20.000
200             Sergio Akieme   11.401522   7.000
141        Nathan Wood-Gordon   11.244467   3.500
172            Jarell Quansah   11.085214  20.000
143               Logan Costa   10.971554  18.000
228        Alexsandro Ribeiro   10.750169  20.000
12     Maximilian Mittelstadt   10.646139  20.000
114            Wilfried Singo   10.484449  25.000
212            Julian Ryerson    9.937298  20.000
126          Andrew Robertson    9.823770  18.000
184              Jules Kounde    9.594919  65.000
149            Javi Hernandez    9.512240   2.500
220           Sinaly Diomande    9.337841   5.000
11              Daniel Vivian    9.171928  40.000
1             Alphonso Davies    9.143776  50.000
102               Jesus Areso    8.874664  12.000
173                Joe Scally    8.838951  10.000
25            Anthony Rouault    8.818615  10.000
78            Tommaso Augello    8.751912   1.800
124             Jordan Zemura    8.506993   4.500
5                Harry Clarke    8.332352   4.500
171                    Catena    8.309365   3.000
87              Botond Balogh    8.271034   2.400
221           Ladislav Krejci    8.190953  12.000
164               Oumar Solet    8.048156  18.000
93                 Alex Valle    8.030142   6.000
36              Gerard Martin    8.019901  12.000
125            Andrea Carboni    7.860042   2.800
34                Abdel Abqar    7.767129   7.500
204             Alan Matturro    7.760855   7.000
0                Jon Aramburu    7.692804  15.000
4              Romain Perraud    7.629863   5.000
101                 Issa Diop    7.386168  14.000
19           Mahamadou Nagida    7.317862   0.800
15                Ali Dembele    7.140656   0.900
37                   Iglesias    7.012587   3.500
182                      Igor    6.842073  20.000
132              Finn Jeltsch    6.811076  20.000
215            Willy Kambwala    6.725274   4.000
51           Giorgio Scalvini    6.532646  35.000
150               Fran Garcia    6.499316  18.000
155           Castello Lukeba    6.360204  40.000
92                Ilay Camara    6.320786   4.000
104            Cedric Zesiger    6.279827   7.000
56                  Felix Agu    6.262822   8.000
165             Marcos Senesi    6.200015  22.000
107              David Torres    5.917444   1.500
154             Antoine Mendy    5.900201   2.500
229          Domagoj Bradaric    5.858048   4.000
65                Tim Drexler    5.729316   3.000
103           Dayot Upamecano    5.651769  50.000
58      Youssouf Ndayishimiye    5.647141  12.000
83       Michael Amir Murillo    5.583870  10.000
8                  Yerry Mina    5.475327   3.000
100        Soumaila Coulibaly    5.465507   8.000
134              Thilo Kehrer    5.307696  20.000
27                Abdul Mumin    5.289858   5.000
67                Lloyd Kelly    5.230187  16.000
189               Kim Min-jae    5.190934  40.000
157                 Yoel Lago    5.156789   1.000
44           Andrey Langovich    5.052450   3.000
32                Anton Gaaei    5.047288   7.000
97              Egor Teslenko    5.015742   2.000
148             Rafik Messali    4.943360   0.800
219              Adam Marusic    4.921646   3.500
195             Jack Stephens    4.887035   1.500
198            Berat Djimsiti    4.560200   6.000
74               Javi Sanchez    4.550699   1.500
117             Scott McKenna    4.499267   4.000
160       Keven Schlotterbeck    4.479152   6.000
3                  Fali Cande    4.423805   2.500
42                Jonas Rouhi    4.410886   2.000
14         Jannik Vestergaard    4.252116   2.000
183            Tomas Palacios    4.236961   4.000
73             Goncalo Inacio    4.236405  45.000
226               Chico Lamba    4.090155   3.000
57           Flavius Daniliuc    3.996602   2.700
52                 Rico Henry    3.935337  15.000
95               Armando Izzo    3.807191   1.500
177              Kelvin Amian    3.745934   2.500
158            Emmanuel Kakou    3.730515   1.000
50              Jordy Makengo    3.717240   6.000
222               Emil Krafth    3.702962   2.000
131                Diego Rico    3.686874   1.200
202         Tsuyoshi Watanabe    3.512726   9.000
129              Joseph Okumu    3.498063   7.000
121           Moussa Niakhate    3.493311  15.000
203               Dinis Pinto    3.486556   1.500
170            Inigo Martinez    3.483371   5.000
169        Brendan Chardonnet    3.472516   6.000
185               Matte Smets    3.435452  13.000
88                Amos Pieper    3.403588   3.500
111                Hauke Wahl    3.399415   1.500
159               Malang Sarr    3.365045   5.000
209             Juan Berrocal    3.332970   1.500
35                 Bamo Meite    3.321589   4.000
167              Semm Renders    3.285738   1.500
91           Mouctar Diakhaby    3.257493   2.000
163           Mohammed Salisu    3.234950  12.000
205         Francesco Zampano    3.151839   1.000
28      Przemyslaw Frankowski    3.148524   7.000
96         Vasilios Zagaritis    3.055672   0.700
118                 Mats Rots    2.969794   1.000
48            Thierry Correia    2.960262   3.000
109       Giangiacomo Magnani    2.884179   1.800
69            Cristian Castro    2.758417   0.800
225        Jose Maria Gimenez    2.758368  20.000
206              Robert Gumny    2.710505   1.500
161            Jose Luis Gayà    2.694782   9.000
187            German Ignatov    2.647906   0.500
105              Craig Dawson    2.624120   1.500
116                      Nino    2.615655  11.000
137        Anass Salah-Eddine    2.588730   8.000
49              Marco Komenda    2.573435   0.800
119         Godfried Frimpong    2.565500   2.000
153              David Hrncar    2.516384   1.200
166              Andy Pelmard    2.406933   2.000
55                 Hugo Bueno    2.343064   8.000
13                 Alex Munoz    2.336875   1.000
9                 Aiham Ousou    2.322894   2.500
22          Milan Majstorovic    2.295971   1.800
130                Marco Sala    2.246322   0.900
190             Ibe Hautekiet    2.231139   3.500
46           Mike Eerdhuijzen    2.214081   2.300
115            Manuel Lazzari    2.207333   3.500
79                Ivan Ordets    2.206613   1.000
188         Roberto Fernandez    2.139815   3.500
38             Egor Pogostnov    2.109032   1.800
80              Ryan Alebiosu    2.102760   0.500
152        Christian Kabasele    2.091490   0.700
176           Matija Nastasic    2.067127   0.800
196                Jose Gomes    1.974670   1.000
218              Manuel Osifo    1.956390   0.700
53               Victor Gomez    1.952009   6.000
186             Ricardo Visus    1.936131   0.750
140                Kenny Lala    1.875398   2.000
191                    Moises    1.810116   5.000
208             Thomas Beelen    1.797592   8.000
210           Maksim Nenakhov    1.760960   3.000
223          Massadio Haidara    1.734064   1.500
181               Ahmed Touba    1.733865   2.500
10            Youssouf Sabaly    1.677123   1.800
180          Maksim Shnaptsev    1.650108   0.300
99                    Ben Mee    1.605577   0.700
41              Shawn Adewoye    1.601493   1.300
216           Lucas Hernandez    1.573893  25.000
75              Ferland Mendy    1.568812  14.000
61             Evgeni Morozov    1.545059   3.000
224              Jordan Amavi    1.514471   1.500
193            Lucas Calegari    1.505433   3.500
62            Duplexe Tchamba    1.500854   1.000
113              Tiago Esgaio    1.488931   0.900
194        Jordan Torunarigha    1.465204   4.000
135           Brandon Mechele    1.456142   3.500
20                Jonny Evans    1.448785   1.000
40         Mike van der Hoorn    1.423797   1.000
217         Toby Alderweireld    1.406472   2.000
29           Eduardo Quaresma    1.383427  18.000
128          Jonathan Mutombo    1.321834   0.500
89            Oleksandr Filin    1.300776   1.000
43              Alexis Duarte    1.279552   3.000
7            Zineddine Belaid    1.258204   0.800
127                Juan Jesus    1.257250   1.500
142     Aleksandr Soldatenkov    1.140734   4.000
178             Marvin Elimbi    1.113380   0.750
16            Aleksei Tatayev    1.109732   0.800
213                    Orinho    1.102269   0.600
138          Javier Manquillo    1.101724   1.000
18              Stephen Welsh    1.091817   1.000
26       Lorenzo De Silvestri    1.069432   0.800
151       Konstantin Savichev    1.052607   0.900
71               Eduard Sobol    1.035223   0.900
24                Tiago Djalo    1.035054   8.000
33               Sergino Dest    1.030398  16.000
76              Boris Popovic    1.028629   1.500
112                Glenn Bijl    0.996528   1.500
39             Ricardo Mangas    0.986697   2.500
174                    Michel    0.983350   1.000
108                Karol Fila    0.975658   0.600
81               Rafael Toloi    0.973113   1.400
175        Jose Luis Palomino    0.965449   0.700
68               Ivan Marquez    0.930124   0.600
106             Alexander Bah    0.928607  10.000
45               Hamza Mendyl    0.915297   1.000
199          Mutalip Alibekov    0.879002   0.700
144           Abdoulaye Bamba    0.868392   0.300
120           Renato Pantalon    0.842890   0.600
145             Hjalmar Ekdal    0.814556   4.500
146           Thierry Lutonda    0.813580   0.300
70              Igor Yurganov    0.794604   0.500
122   Francisco Reis Ferreira    0.689449   0.700
197               Axel Witsel    0.684945   2.000
156            Paulo Oliveira    0.650981   1.000
6                  Boyd Reith    0.646218   0.400
85          Mathias Jorgensen    0.576801   0.500
90      Boli Bolingoli-Mbombo    0.560907   0.500
162            Wolke Janssens    0.483476   0.400
72        Patrick van Aanholt    0.465615   0.500
17            Marvin da Graca    0.460731   0.400
47            Ruben Fernandes    0.410430   0.050
139       Redouan El Yaakoubi    0.396976   0.550
64               Carlos Ponck    0.368523   0.600
207                Raul Silva    0.269534   0.100
84              Aaron Meijers    0.145746   0.075

# Модель 2

In [51]:
X_train = X_train[['G+A', 'G+A.1', 'Ast', 'G-PK', 'Ast.1', 'Sh', 'SoT/90', '90s', 'Fls', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'G+A.1', 'Ast', 'G-PK', 'Ast.1', 'Sh', 'SoT/90', '90s', 'Fls', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [57]:
coeffs_df

               coeff
league_GB1  0.640705
Age        -0.585580
90s         0.364311
league_IT1  0.357902
league_L1   0.323469
league_ES1  0.296088
league_FR1  0.265908
Ast         0.245730
G-PK        0.189217
TklW       -0.138398
league_NL1 -0.132993
G+A.1      -0.124025
Sh/90       0.113915
G+A        -0.104896
league_PO1 -0.097645
Ast.1       0.093012
Fls         0.080768
Sh          0.065344
SoT/90      0.020065
league_RU1 -0.019826
Int        -0.007341

In [58]:
metrics

            MAE       RMSE      MAPE        R2
test   5.613919  11.363877  0.920371  0.295272
train  4.663112   9.586427  0.882595  0.350100

In [59]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                               Player  Value_pred   Value
664                      Milos Kerkez  115.716721  45.000
412                      Dean Huijsen   68.397480  60.000
10                        Pedro Porro   66.809384  38.000
730                    Nathan Collins   61.832988  28.000
56             Trent Alexander-Arnold   58.321354  75.000
890                      Levi Colwill   56.880083  55.000
342                 Nikola Milenkovic   51.616052  35.000
784                      Daniel Munoz   44.903736  25.000
503                           Murillo   42.753415  55.000
178                        Lewis Hall   40.762975  32.000
795             Taylor Harwood-Bellis   40.352567  22.000
25                      Neco Williams   40.242150  20.000
777                   Maxence Lacroix   35.696317  25.000
206                    Illia Zabarnyi   34.957998  42.000
228                 Aaron Wan-Bissaka   33.995565  24.000
1                     Tyrick Mitchell   32.520144  25.000
320                       Diogo Dalot   32.461563  30.000
472                    Jurrien Timber   32.078089  55.000
326                        Leif Davis   30.559345  22.000
836                 Sepp van den Berg   30.271171  22.000
522                        Malo Gusto   29.793473  35.000
213                Jan Paul van Hecke   29.678969  32.000
572                      James Justin   29.321506  13.000
9                         Dara O'Shea   29.033086  14.000
772                   Raoul Bellanova   28.272762  24.000
805                     Luka Vuskovic   28.204241  12.000
303                    William Saliba   27.302992  80.000
734                Jarrad Branthwaite   26.080862  50.000
743                     Alex Grimaldo   24.819223  30.000
315                     Conor Bradley   24.239897  30.000
702                       Pau Cubarsi   24.226363  80.000
724                         Leny Yoro   23.541134  55.000
104                 Charlie Cresswell   22.816446  10.000
771                   Trevoh Chalobah   22.742137  25.000
147                      Nuno Tavares   22.611654  25.000
205                  Matthijs de Ligt   22.293908  38.000
101                    Theo Hernandez   22.161974  35.000
456                       Harry Amass   22.029357   5.000
142                  Pervis Estupinan   21.373136  30.000
451                     Nico O’Reilly   21.294232  18.000
390                Kyle Walker-Peters   20.952761  15.000
834                      Fabian Schar   20.543186   7.000
208                       Djed Spence   20.020062  20.000
264                     Jacob Greaves   19.976790  18.000
840         Victor Bernth Kristiansen   19.415732  15.000
375                      Juan Miranda   19.355271  15.000
621                   Alejandro Balde   19.324849  60.000
69                         Ezri Konsa   19.294819  35.000
607                      Anthony Caci   19.209834  12.000
741                              Dodo   18.874670  24.000
362                     Achraf Hakimi   18.687370  80.000
655                    Destiny Udogie   18.553821  40.000
183                     Nelson Semedo   18.412833   9.000
377                    Michael Kayode   18.174786  18.000
138                      Robin Gosens   17.745812   8.000
28                      Sergi Cardona   17.472263  10.000
877                    Bafode Diakite   17.326862  28.000
53                           Ola Aina   16.961924  22.000
871                 Lisandro Martinez   16.546768  40.000
108                     Cesar Tarrega   16.481685  10.000
94                     Piero Hincapie   16.355368  50.000
236                  Emmanuel Agbadou   15.971740  20.000
787                      Jake O'Brien   15.833047  18.000
866                     Johan Vasquez   15.795303  14.000
785                     Tariq Lamptey   15.790132  11.000
418                        Kike Salas   15.779898   8.000
507                      Aaron Martin   15.649576   6.500
533                Alessandro Bastoni   15.437369  80.000
204                        Guela Doue   15.255108  18.000
427                        Ruben Dias   15.059095  65.000
177                        James Hill   14.998114   3.000
603                        Matty Cash   14.977616  25.000
628                    Chris Richards   14.681160  14.000
432                   Virgil van Dijk   14.557253  23.000
42                      Radu Dragusin   14.516980  25.000
541                     Obite N'Dicka   14.377099  30.000
908                     Carlos Romero   14.124002   5.000
242                      Mamadou Sarr   14.079948  20.000
89                     Koni De Winter   14.015379  22.000
411                    Quentin Merlin   13.986183  15.000
60                   Enrico Del Prato   13.980960   6.500
388                          Dan Burn   13.944964   6.000
761                Yann Aurel Bisseck   13.833162  35.000
861           Konstantinos Mavropanos   13.543185  17.000
747                       Enzo Boyomo   13.457268  20.000
393                        Kenny Tete   13.448681  13.000
118                    Danilho Doekhi   13.214105  13.000
474                    Pietro Comuzzo   13.157302  25.000
591                      Luca Ranieri   12.970185  12.000
329                      Jan Bednarek   12.800195   9.000
496                Cristhian Mosquera   12.709049  30.000
441             Giorgos Kyriakopoulos   12.670488   2.500
791                         Jay Idzes   12.587347   7.500
481                         Saul Coco   12.582071  10.000
131                       Nuno Mendes   12.525838  70.000
576                  Tosin Adarabioyo   12.516910  20.000
129                 Rasmus Kristensen   12.478033  14.000
898                   Marash Kumbulla   12.357394   7.500
310                      Andrei Ratiu   12.332124  12.000
608                       Caleb Okoli   12.160928  10.000
558                       Tim Oermann   12.119266   5.000
299                Sebastiano Luperto   11.831569   4.000
493                 Chrislain Matsima   11.782225  22.000
81                    Florian Lejeune   11.724688   2.500
394                 Jean-Clair Todibo   11.709522  25.000
397                    Santiago Bueno   11.699062  10.000
870                     Arthur Theate   11.660657  24.000
718                        Jaka Bijol   11.545158  18.000
850                        Jon Martin   11.366239   8.000
596                  Saba Goglichidze   11.314664   8.000
122                         Ben White   11.309758  45.000
399                    Gabriele Zappa   11.293416   4.000
255                   Cristian Romero   11.239603  50.000
241                    Carlos Augusto   11.038467  26.000
710              Federico Baschirotto   10.855313   3.600
854                    Omar El Hilali   10.833736  15.000
121                    Giovanni Leoni   10.678721  18.000
649                            Morato   10.623667  14.000
304                Nico Schlotterbeck   10.546778  40.000
617                     Joakim Maehle   10.507925  14.000
276                       Luke Thomas   10.473977   6.000
494                     Amir Rrahmani   10.419470  12.000
97                   Nathan Patterson   10.406115  15.000
466                     Nicolo Savona   10.392259  12.000
98                    James Tarkowski   10.282898   9.000
690                     Axel Tuanzebe   10.196944   5.000
555              Souffian El Karouani   10.177532   9.000
885                        Mario Gila   10.157445  30.000
899                       Jorrel Hato   10.034673  35.000
237                       Lucas Digne   10.027494  10.000
119                       Sven Botman    9.942520  42.000
817                  Daniele Ghilardi    9.935888   5.000
293                         Vanderson    9.754725  20.000
312                   Cameron Burgess    9.741955   2.000
287                        Pau Torres    9.725447  32.000
802                Strahinja Pavlovic    9.695980  18.000
35                      Omar Alderete    9.561146   8.000
352                   Lasse Rosenboom    9.531969   1.500
661                       Sam Beukema    9.524450  28.000
410                  Gianluca Mancini    9.501426  15.000
798                     Manuel Akanji    9.497162  28.000
184                           Carmona    9.460692  12.000
398                       Mattia Viti    9.365319   5.500
715                       Diogo Leite    9.334187  17.000
346                   Kristoffer Ajer    9.327630  18.000
379                     Julian Chabot    9.212987  12.000
369                  Abdulai Juma Bah    9.210133   6.000
479                     Lucas Beraldo    9.208094  25.000
729                    Nnamdi Collins    9.203767  10.000
666                     Julian Araujo    9.141178  10.000
778                         Welington    9.113384   3.000
128                       Hector Fort    9.112265  10.000
141                     Matteo Gabbia    8.959080  14.000
598                      Jonathan Tah    8.856467  30.000
766                         Loic Bade    8.841329  25.000
71                      Frans Kratzig    8.815121   3.500
323                 Zakaria El Ouahdi    8.810118  12.000
225                   Yerson Mosquera    8.807676   8.000
590               Giovanni Di Lorenzo    8.748965  12.000
221                      Nasser Djiga    8.743720  10.000
188             Etienne Youte Kinkoue    8.697889   7.000
243                    Edmond Tapsoba    8.449664  35.000
758                   Luca Pellegrini    8.438598   3.000
443                   Ramy Bensebaini    8.435424   7.000
714                        Adam Obert    8.383046   3.000
76                         Ko Itakura    8.366205  12.000
163                    Matteo Ruggeri    8.283670  16.000
136                  Santiago Mourino    8.235176   3.000
650                   Luke Woolfenden    8.174832   2.000
625                    Facundo Medina    8.158592  25.000
513                    Ki-Jana Hoever    8.084967   5.000
247                        James Bree    7.980583   2.500
470                        David Raum    7.861903  20.000
819                     Arthur Chaves    7.814796   5.000
171                   Luca Marianucci    7.794373   7.500
859                    Jeremy Jacquet    7.793345  10.000
58                   Valentin Gendrey    7.719635   7.000
515                     Adrià Pedrosa    7.660236   7.000
416                 Davide Zappacosta    7.637149   5.000
810                      Malick Thiaw    7.589765  18.000
875               Lucas Oliveira Rosa    7.579653   3.000
694                       Mika Marmol    7.573109  10.000
169                             Natan    7.569249   9.000
742                   Lilian Brassier    7.566389  10.000
347                        Saidou Sow    7.548172   6.000
786                    Federico Gatti    7.527590  24.000
447                 Thomas Kristensen    7.485549   6.000
848                      Manu Sanchez    7.467700   6.000
594                     Gabriel Suazo    7.437842   4.000
286                  Timothy Castagne    7.421057  13.000
408                 Kosta Nedeljkovic    7.387845  10.000
73             El Chadaille Bitshiabu    7.377885  18.000
114                        Robin Koch    7.350126  18.000
134                       Nathan Zeze    7.321588  15.000
531                 Benoît Badiashile    7.305012  22.000
34                    Emmanuel Biumla    7.232315   4.000
40                 Abdukodir Khusanov    7.214819  35.000
610                    Antonino Gallo    7.179040   4.300
688                 Maximilian Wittek    7.167960   1.500
614                     Pierre Kalulu    7.160555  28.000
727                        Amar Dedic    7.140165  12.000
573                      Jorge Cuenca    7.133564   5.000
68                Dimitris Giannoulis    7.124917   3.000
430                     Konrad Laimer    7.110047  25.000
291                      Clement Akpa    7.022187   5.000
274                      Matt Doherty    6.995730   2.000
630                   Alberto Dossena    6.991987   8.000
883                     Harry Maguire    6.986585  13.000
794                       Axel Disasi    6.973353  22.000
703            Ainsley Maitland-Niles    6.968640  12.000
680                    Antonio Raillo    6.936093   1.800
219                  Ousmane Diomande    6.927675  45.000
152                   Mathias Olivera    6.902286  20.000
701                      Marko Ivezic    6.870057   2.000
249                     Noahkai Banks    6.859121   6.000
556                         David Zec    6.838627   2.500
33                        Omar Traore    6.834311   4.000
574                    Phillipp Mwene    6.821272   1.800
424                        Adam Aznou    6.795999   4.000
332                     Abel Bretones    6.789254   4.000
132                      Raul Asencio    6.769536  40.000
480                       Juan Herzog    6.743437   2.500
905                      David Nemeth    6.704369   4.000
116                     Ethan Pinnock    6.703801   7.000
420                       Anrie Chase    6.703165   3.000
145                Leo Skiri Østigard    6.645805  10.000
847                   Alexander Prass    6.632673   5.000
613                     Max Geschwill    6.628153   1.500
731                    Jorge Herrando    6.582665   4.000
620                      Archie Brown    6.525160   7.000
232                        Luck Zogbe    6.508751   2.500
415                         Luca Netz    6.507350   6.000
260                       Denis Vavro    6.504521   7.000
191                       Jhon Lucumi    6.501090  22.000
195                        Javi Lopez    6.479708   7.500
853                    Kilian Fischer    6.426872   6.000
282                      Sael Kumbedi    6.387112   7.000
361                     Willian Pacho    6.383539  65.000
5                       Aitor Paredes    6.346368  22.000
90                           Kialonda    6.306969   3.500
901                   Fabio Chiarodia    6.304289   2.000
356                       Kevin Danso    6.299893  25.000
564                  Christopher Wooh    6.295608   6.000
67                     Patrick Mainka    6.274965   3.000
762                      Givairo Read    6.232889  16.000
902                   Nahuel Tenaglia    6.209003   3.000
551                    Waldemar Anton    6.154796  18.000
476              Lutsharel Geertruida    6.132505  20.000
538             Ignace Van Der Brempt    6.132216   4.000
691                   Max Rosenfelder    6.124430   8.000
381               Gabriel Gudmundsson    6.072075   7.000
548                   Jan-Carlo Simic    6.067349   8.000
469                       Enzo Tchato    6.044873   2.500
21                  Christian Mawissa    6.024990  15.000
455                   Antonio Candela    6.016658   1.800
852                   Arouna Sangante    6.015506   8.000
585         Abdoulaye Niakhate Ndiaye    5.997369   4.000
903                  Souleymane Toure    5.946742   7.000
380                      Tiago Santos    5.934929  15.000
258                    Becir Omeragic    5.893606   4.500
612                    Flavio Nazinho    5.884990   3.000
294                         Isak Hien    5.873641  30.000
378             Sebastian Walukiewicz    5.832613   4.500
389                    Stefan Lekovic    5.824035   1.700
686                 Alessio Romagnoli    5.778354   7.000
44                  Mikayil Ngor Faye    5.745111   6.000
167                      Yael Mouanga    5.684701   0.600
95                  Yarek Gasiorowski    5.683822   7.500
127                  Lucas Mincarelli    5.664448   0.900
185                   Matthias Ginter    5.663873   7.000
92                         Lewis Dunk    5.659963   6.000
85                       Tuur Rommens    5.655814   4.000
839                  Martim Fernandes    5.648181  12.000
615                 Leonidas Stergiou    5.645680   5.000
512                        Zeki Celik    5.625282   6.000
803                       Jakov Medic    5.610967   2.000
684                   Kostas Tsimikas    5.603583  18.000
39                    Valentin Rosier    5.582134   3.000
37                     Hassane Kamara    5.535313   3.500
459                   Maxim De Cuyper    5.525309  16.000
49                     Martin Valjent    5.511434   6.000
618                 Kiliann Sildillia    5.497086  10.000
660              Alessandro Vogliacco    5.495947   2.800
807                       Timo Becker    5.495788   1.500
72                          Emil Holm    5.494214   8.000
464                      Fellipe Jack    5.465638   1.400
845                            Arthur    5.462262   7.000
165                       Marius Wolf    5.446123   3.000
84                    Benedikt Gimber    5.444504   3.000
842                 Joel Schingtienne    5.442281   3.500
281                       Pau Navarro    5.411954   3.000
251                         Joe Gomez    5.397793  20.000
336                Alessandro Circati    5.391847   8.000
679      Caio Henrique Oliveira Silva    5.354510  15.000
79                    Marcus Pedersen    5.347788   3.000
211                     Modibo Sagnan    5.342724   3.000
452                  Timothee Pembele    5.341527   2.500
893                  Philipp Lienhart    5.327848  12.000
80                     Ramon Hendriks    5.317437   5.000
668                  Odilon Kossounou    5.299800  25.000
417                 Alejandro Frances    5.273388   2.000
365                David Moller Wolfe    5.252723   9.000
160                     Michael Keane    5.247359   5.000
265                   Alvaro Carreras    5.174620  35.000
334                    Almugera Kabar    5.172306   1.000
425                    Bryan Reynolds    5.164748   3.500
881             Alessandro Buongiorno    5.152922  50.000
677                   Lautaro Valenti    5.144364   1.500
511                      Abakar Sylla    5.137270  10.000
271                       Angel Ortiz    5.133274   2.500
562                     Moise Bombito    5.124028  10.000
61                       Ivan Smolcic    5.069800   1.800
770                     Jesus Vazquez    5.035044   3.000
190                      Dion De Neve    5.026763   0.900
41                  Nicolas Valentini    5.003699   6.000
199                      Adam Webster    5.000236  11.000
284                       Conor Coady    4.978606   2.200
15                         Sacha Boey    4.940883  18.000
120                        Leo Petrot    4.922444   0.900
110                     Moussa Diarra    4.906952   1.800
161                     David Jurasek    4.901694   5.000
693                  Robin Le Normand    4.894374  40.000
435                      Mickael Nade    4.886769   2.000
270                     Nahuel Molina    4.877589  20.000
0              Alessandro Marcandalli    4.860537   2.000
133                   Leandro Cabrera    4.855747   1.000
575                       Willi Orban    4.849455   8.000
74                      Hiroki Sekine    4.806928   1.200
181           Anselmo Garcia MacNulty    4.801551   1.500
175                       Nico Elvedi    4.792292   8.000
47                         Juan Foyth    4.772988  15.000
70                     Marco Palestra    4.753562   3.500
196                     Aurele Amenda    4.747531   7.500
353                  Leonardo Balerdi    4.738013  20.000
105                 Marc-Oliver Kempf    4.736009   3.000
792                       Moritz Jenz    4.713188   5.000
487                    Bart van Rooij    4.699846   6.000
235                Jeffrey Gouweleeuw    4.679170   1.500
254                    Daniel Oyegoke    4.659684   0.500
340                    Rafik Belghali    4.653736   2.500
623                      Lukas Kubler    4.647506   1.500
508                     Igor Zubeldia    4.614022  12.000
674                     Ryan Flamingo    4.608997  20.000

In [60]:
comp_leftovers_test.sort_values('Value_pred', ascending=False)

                       Player  Value_pred   Value
23            Rayan Ait-Nouri  110.516296  35.000
77             Josko Gvardiol   71.804358  75.000
168          Antonee Robinson   49.664445  35.000
201                Marc Guehi   39.058889  45.000
179            Marc Cucurella   34.969210  35.000
227        Myles Lewis-Skelly   28.647967  45.000
60                Ian Maatsen   27.739204  28.000
136         Gabriel Magalhaes   26.596850  75.000
86            Ibrahima Konate   26.559494  60.000
110         Vitaliy Mykolenko   25.248342  28.000
82              Calvin Bassey   25.161395  25.000
94            Emanuele Valeri   19.827918   3.000
31   Konstantinos Koulierakis   19.795380  25.000
133                Max Kilman   19.547162  25.000
2          Riccardo Calafiori   19.087627  35.000
211             Diego Coppola   17.618645  10.000
214          Leopold Querfeld   17.045283  13.000
63                  Wout Faes   17.009381  15.000
30           Micky van de Ven   16.133866  50.000
66             Javi Rodriguez   15.954467  15.000
59                 Toti Gomes   14.651936  28.000
192             Lukas Ullrich   14.031296   8.000
123             Mads Roerslev   13.734317   6.000
54          Noussair Mazraoui   12.688173  25.000
143               Logan Costa   12.354480  18.000
98              Wesley Fofana   12.348609  25.000
147                  Angelino   11.803140  20.000
200             Sergio Akieme   11.358141   7.000
141        Nathan Wood-Gordon   11.167827   3.500
21              Pedro Pereira   11.150309   1.500
172            Jarell Quansah   10.957311  20.000
12     Maximilian Mittelstadt   10.721267  20.000
114            Wilfried Singo   10.669842  25.000
228        Alexsandro Ribeiro   10.651698  20.000
212            Julian Ryerson   10.129176  20.000
184              Jules Kounde    9.685391  65.000
149            Javi Hernandez    9.685201   2.500
11              Daniel Vivian    9.625484  40.000
220           Sinaly Diomande    9.486186   5.000
126          Andrew Robertson    9.458069  18.000
1             Alphonso Davies    9.443310  50.000
173                Joe Scally    9.306941  10.000
25            Anthony Rouault    9.244487  10.000
102               Jesus Areso    8.618190  12.000
5                Harry Clarke    8.579102   4.500
221           Ladislav Krejci    8.338687  12.000
124             Jordan Zemura    8.318188   4.500
78            Tommaso Augello    8.310011   1.800
164               Oumar Solet    8.236004  18.000
93                 Alex Valle    8.231089   6.000
171                    Catena    8.043085   3.000
87              Botond Balogh    8.039714   2.400
4              Romain Perraud    8.010334   5.000
204             Alan Matturro    8.005075   7.000
0                Jon Aramburu    7.942958  15.000
36              Gerard Martin    7.756921  12.000
34                Abdel Abqar    7.716631   7.500
125            Andrea Carboni    7.661389   2.800
101                 Issa Diop    7.398957  14.000
37                   Iglesias    6.845693   3.500
51           Giorgio Scalvini    6.844595  35.000
56                  Felix Agu    6.830262   8.000
132              Finn Jeltsch    6.830010  20.000
182                      Igor    6.814590  20.000
215            Willy Kambwala    6.689901   4.000
155           Castello Lukeba    6.466002  40.000
92                Ilay Camara    6.440232   4.000
15                Ali Dembele    6.437115   0.900
150               Fran Garcia    6.430567  18.000
104            Cedric Zesiger    6.266206   7.000
65                Tim Drexler    6.252571   3.000
165             Marcos Senesi    6.123513  22.000
154             Antoine Mendy    6.026622   2.500
107              David Torres    5.872680   1.500
229          Domagoj Bradaric    5.849871   4.000
19           Mahamadou Nagida    5.804937   0.800
103           Dayot Upamecano    5.781280  50.000
58      Youssouf Ndayishimiye    5.702987  12.000
134              Thilo Kehrer    5.700066  20.000
8                  Yerry Mina    5.686259   3.000
83       Michael Amir Murillo    5.586381  10.000
100        Soumaila Coulibaly    5.534613   8.000
67                Lloyd Kelly    5.460813  16.000
27                Abdul Mumin    5.337103   5.000
189               Kim Min-jae    5.317504  40.000
219              Adam Marusic    5.182121   3.500
97              Egor Teslenko    5.169159   2.000
157                 Yoel Lago    5.111619   1.000
32                Anton Gaaei    5.101467   7.000
44           Andrey Langovich    5.077497   3.000
148             Rafik Messali    5.016369   0.800
195             Jack Stephens    4.825066   1.500
74               Javi Sanchez    4.560511   1.500
198            Berat Djimsiti    4.470784   6.000
3                  Fali Cande    4.430184   2.500
160       Keven Schlotterbeck    4.386113   6.000
117             Scott McKenna    4.364880   4.000
42                Jonas Rouhi    4.336433   2.000
14         Jannik Vestergaard    4.260784   2.000
183            Tomas Palacios    4.255883   4.000
73             Goncalo Inacio    4.240693  45.000
226               Chico Lamba    4.192863   3.000
95               Armando Izzo    4.018881   1.500
57           Flavius Daniliuc    3.955789   2.700
52                 Rico Henry    3.893555  15.000
158            Emmanuel Kakou    3.880187   1.000
131                Diego Rico    3.762836   1.200
177              Kelvin Amian    3.762190   2.500
50              Jordy Makengo    3.730116   6.000
222               Emil Krafth    3.707572   2.000
137        Anass Salah-Eddine    3.571787   8.000
203               Dinis Pinto    3.558303   1.500
129              Joseph Okumu    3.480115   7.000
170            Inigo Martinez    3.466464   5.000
121           Moussa Niakhate    3.455951  15.000
88                Amos Pieper    3.429334   3.500
185               Matte Smets    3.402325  13.000
169        Brendan Chardonnet    3.388792   6.000
202         Tsuyoshi Watanabe    3.379775   9.000
111                Hauke Wahl    3.375005   1.500
159               Malang Sarr    3.344053   5.000
35                 Bamo Meite    3.304813   4.000
209             Juan Berrocal    3.284258   1.500
167              Semm Renders    3.269779   1.500
163           Mohammed Salisu    3.229171  12.000
205         Francesco Zampano    3.207072   1.000
206              Robert Gumny    3.188760   1.500
48            Thierry Correia    3.182079   3.000
96         Vasilios Zagaritis    3.003177   0.700
91           Mouctar Diakhaby    2.971402   2.000
118                 Mats Rots    2.921283   1.000
109       Giangiacomo Magnani    2.851928   1.800
28      Przemyslaw Frankowski    2.845467   7.000
69            Cristian Castro    2.753805   0.800
116                      Nino    2.747880  11.000
225        Jose Maria Gimenez    2.742662  20.000
187            German Ignatov    2.706616   0.500
161            Jose Luis Gayà    2.683578   9.000
105              Craig Dawson    2.653474   1.500
49              Marco Komenda    2.599190   0.800
119         Godfried Frimpong    2.598238   2.000
153              David Hrncar    2.452740   1.200
166              Andy Pelmard    2.418697   2.000
9                 Aiham Ousou    2.350708   2.500
55                 Hugo Bueno    2.335354   8.000
22          Milan Majstorovic    2.332010   1.800
13                 Alex Munoz    2.309159   1.000
115            Manuel Lazzari    2.288365   3.500
130                Marco Sala    2.205336   0.900
79                Ivan Ordets    2.204554   1.000
46           Mike Eerdhuijzen    2.183350   2.300
190             Ibe Hautekiet    2.173248   3.500
38             Egor Pogostnov    2.167659   1.800
188         Roberto Fernandez    2.158126   3.500
80              Ryan Alebiosu    2.104263   0.500
176           Matija Nastasic    2.085881   0.800
152        Christian Kabasele    2.044946   0.700
196                Jose Gomes    2.026008   1.000
218              Manuel Osifo    1.951678   0.700
53               Victor Gomez    1.942992   6.000
186             Ricardo Visus    1.942871   0.750
191                    Moises    1.870338   5.000
223          Massadio Haidara    1.810711   1.500
210           Maksim Nenakhov    1.792463   3.000
140                Kenny Lala    1.788046   2.000
208             Thomas Beelen    1.772156   8.000
181               Ahmed Touba    1.749710   2.500
10            Youssouf Sabaly    1.656631   1.800
180          Maksim Shnaptsev    1.638534   0.300
41              Shawn Adewoye    1.601281   1.300
224              Jordan Amavi    1.592382   1.500
99                    Ben Mee    1.582963   0.700
216           Lucas Hernandez    1.566992  25.000
75              Ferland Mendy    1.557028  14.000
20                Jonny Evans    1.543818   1.000
193            Lucas Calegari    1.529625   3.500
62            Duplexe Tchamba    1.493193   1.000
61             Evgeni Morozov    1.489496   3.000
113              Tiago Esgaio    1.486691   0.900
135           Brandon Mechele    1.476547   3.500
40         Mike van der Hoorn    1.468870   1.000
194        Jordan Torunarigha    1.459665   4.000
217         Toby Alderweireld    1.415936   2.000
29           Eduardo Quaresma    1.372730  18.000
128          Jonathan Mutombo    1.360885   0.500
89            Oleksandr Filin    1.328394   1.000
43              Alexis Duarte    1.300083   3.000
7            Zineddine Belaid    1.296567   0.800
127                Juan Jesus    1.232662   1.500
213                    Orinho    1.169099   0.600
142     Aleksandr Soldatenkov    1.126636   4.000
18              Stephen Welsh    1.114363   1.000
108                Karol Fila    1.111257   0.600
39             Ricardo Mangas    1.098354   2.500
178             Marvin Elimbi    1.095476   0.750
138          Javier Manquillo    1.088164   1.000
26       Lorenzo De Silvestri    1.078333   0.800
24                Tiago Djalo    1.067133   8.000
33               Sergino Dest    1.061156  16.000
16            Aleksei Tatayev    1.060133   0.800
76              Boris Popovic    1.033839   1.500
112                Glenn Bijl    1.025284   1.500
71               Eduard Sobol    1.018402   0.900
151       Konstantin Savichev    1.001345   0.900
81               Rafael Toloi    0.979574   1.400
174                    Michel    0.966128   1.000
68               Ivan Marquez    0.942497   0.600
106             Alexander Bah    0.934224  10.000
175        Jose Luis Palomino    0.922344   0.700
45               Hamza Mendyl    0.920065   1.000
199          Mutalip Alibekov    0.918530   0.700
144           Abdoulaye Bamba    0.856344   0.300
120           Renato Pantalon    0.837239   0.600
146           Thierry Lutonda    0.823069   0.300
145             Hjalmar Ekdal    0.817792   4.500
70              Igor Yurganov    0.809114   0.500
197               Axel Witsel    0.679705   2.000
122   Francisco Reis Ferreira    0.678320   0.700
6                  Boyd Reith    0.664078   0.400
156            Paulo Oliveira    0.655990   1.000
90      Boli Bolingoli-Mbombo    0.585208   0.500
85          Mathias Jorgensen    0.574587   0.500
162            Wolke Janssens    0.489399   0.400
72        Patrick van Aanholt    0.450012   0.500
17            Marvin da Graca    0.443099   0.400
139       Redouan El Yaakoubi    0.408432   0.550
47            Ruben Fernandes    0.407641   0.050
64               Carlos Ponck    0.375627   0.600
207                Raul Silva    0.249594   0.100
84              Aaron Meijers    0.147297   0.075

# Модель 3

In [66]:
X_train = X_train[['G+A', 'G+A.1', 'Ast', 'G-PK', 'Ast.1', 'Sh', 'SoT/90', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'G+A.1', 'Ast', 'G-PK', 'Ast.1', 'Sh', 'SoT/90', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [72]:
coeffs_df

               coeff
league_GB1  0.633083
Age        -0.588033
90s         0.398699
league_IT1  0.361135
league_L1   0.319165
league_ES1  0.298034
league_FR1  0.265436
Ast         0.241660
G-PK        0.193043
league_NL1 -0.141574
G+A.1      -0.124892
Sh/90       0.115678
TklW       -0.111724
G+A        -0.110545
Ast.1       0.095742
league_PO1 -0.091425
Sh          0.070633
league_RU1 -0.022201
SoT/90      0.017195
Int        -0.002877
CrdY        0.002203

In [73]:
metrics

            MAE       RMSE      MAPE        R2
test   5.600638  11.405773  0.911615  0.290066
train  4.641290   9.544416  0.886544  0.355784

In [74]:
comp_leftovers_train

                               Player  Value_pred   Value
0              Alessandro Marcandalli    4.824710   2.000
1                     Tyrick Mitchell   34.312494  25.000
2                    Valentin Paltsev    3.272173   2.500
3                        Teo Quintero    0.703826   0.600
4                      Kaio Pantaleao    0.748273   1.800
5                       Aitor Paredes    6.178441  22.000
6                    Fredrik Oppegard    1.463485   0.600
7                       Sergei Bozhin    1.042034   0.700
8                  Francisco Petrasso    1.270452   1.500
9                         Dara O'Shea   30.593307  14.000
10                        Pedro Porro   68.380271  38.000
11                      Fikayo Tomori    3.572426  20.000
12                             Marcao    1.446427   2.000
13                       Martin Erlic    3.614108   4.000
14                  Alexandre Penetra    2.869624   9.000
15                         Sacha Boey    4.881722  18.000
16                      Kyriani Sabbe    3.133170   4.500
17                     Djibril Sidibe    1.998463   1.000
18                      Seiya Maikuma    1.117011   4.000
19                      Rick Karsdorp    0.432992   3.000
20                Mohamed Abdelmoneim    2.201137   4.000
21                  Christian Mawissa    6.121832  15.000
22                     Thomas Meunier    2.651451   2.000
23                         Mats Deijl    2.392484   2.000
24        Marcelo dos Santos Ferreira    0.524998   0.100
25                      Neco Williams   43.147920  20.000
26                  Edoardo Goldaniga    3.944176   3.000
27                     Danny da Costa    2.216919   1.500
28                      Sergi Cardona   16.976488  10.000
29                        Jon Pacheco    3.360753   6.000
30                 Viktor Aleksandrov    1.820814   1.200
31                  Rustam Ashurmatov    0.668416   0.600
32                     Aske Adelgaard    1.946204   0.850
33                        Omar Traore    6.973856   4.000
34                    Emmanuel Biumla    7.582021   4.000
35                      Omar Alderete    9.610281   8.000
36                    Oscar de Marcos    1.629681   1.500
37                     Hassane Kamara    5.458994   3.500
38                   Mimeirhel Benita    2.499446   1.000
39                    Valentin Rosier    5.294161   3.000
40                 Abdukodir Khusanov    7.261633  35.000
41                  Nicolas Valentini    4.895125   6.000
42                      Radu Dragusin   14.846284  25.000
43                       Martin Frese    2.341413   2.000
44                  Mikayil Ngor Faye    5.759272   6.000
45                         Leo Greiml    2.446489   2.000
46                     Mitchell Dijks    0.532150   0.600
47                         Juan Foyth    4.854978  15.000
48                         Maks Dziov    2.274743   0.700
49                     Martin Valjent    6.001420   6.000
50                       Matvei Lukin    2.432769   1.200
51                        Emin Bayram    2.735313   3.500
52                       Cesar Montes    1.099743   4.500
53                           Ola Aina   17.848716  22.000
54                        David Alaba    0.785357   6.000
55                 Bas van den Eynden    1.949655   0.700
56             Trent Alexander-Arnold   66.113736  75.000
57                Christopher Mamengi    0.652989   0.250
58                   Valentin Gendrey    7.825856   7.000
59                      Oleg Reabciuk    2.022224   4.000
60                   Enrico Del Prato   14.824270   6.500
61                       Ivan Smolcic    5.056835   1.800
62                        Joao Mendes    2.247358   2.000
63                         Hiroki Ito    1.900436  25.000
64                        Mike Kleijn    1.272858   0.250
65                         Nathan Ake    4.296142  25.000
66                    Antonio Rudiger    3.414248  20.000
67                     Patrick Mainka    6.947971   3.000
68                Dimitris Giannoulis    7.599365   3.000
69                         Ezri Konsa   21.378073  35.000
70                     Marco Palestra    4.938323   3.500
71                      Frans Kratzig    9.180048   3.500
72                          Emil Holm    5.537269   8.000
73             El Chadaille Bitshiabu    7.673845  18.000
74                      Hiroki Sekine    5.033510   1.200
75            Konstantin Nizhegorodov    1.125357   0.300
76                         Ko Itakura    8.380917  12.000
77                       Igor Vujacic    1.369904   3.000
78                         Borna Sosa    3.064994   4.500
79                    Marcus Pedersen    5.317619   3.000
80                     Ramon Hendriks    5.285980   5.000
81                    Florian Lejeune   10.562806   2.500
82                     Gleison Bremer    2.223733  50.000
83                      Marvin Senaya    2.710290   1.800
84                    Benedikt Gimber    4.406923   3.000
85                       Tuur Rommens    5.905143   4.000
86                     Alberto Moreno    2.292347   1.500
87                   Yunis Abdelhamid    0.591004   0.400
88                     Rosen Bozhinov    2.146335   0.400
89                     Koni De Winter   12.287120  22.000
90                           Kialonda    6.913118   3.500
91                   Jonas Fohrenbach    3.358115   1.500
92                         Lewis Dunk    6.012043   6.000
93                      Pierre Cornud    1.520602   0.800
94                     Piero Hincapie   16.905925  50.000
95                  Yarek Gasiorowski    6.112137   7.500
96                          Rob Nizet    1.100911   0.350
97                   Nathan Patterson   10.287759  15.000
98                    James Tarkowski    9.914262   9.000
99                        Maxime Busi    0.851386   1.000
100                         Lucas Hey    1.693236   5.000
101                    Theo Hernandez   24.308201  35.000
102              Alec Van Hoorenbeeck    1.055369   0.800
103                     Erik Schouten    0.350723   0.200
104                 Charlie Cresswell   22.716244  10.000
105                 Marc-Oliver Kempf    4.981920   3.000
106                   Alexandre Pinto    0.775391   0.500
107                    Dani Fernandez    1.384172   0.800
108                     Cesar Tarrega   14.192607  10.000
109                   Mardochee Nzita    1.205219   1.000
110                     Moussa Diarra    4.709194   1.800
111                       Aihen Munoz    2.862705   4.000
112                       Jorge Saenz    3.271481   1.500
113                     Gideon Mensah    3.481676   4.000
114                        Robin Koch    7.249312  18.000
115                        Karol Mets    1.352799   1.300
116                     Ethan Pinnock    7.068350   7.000
117                  Olivier Boscagli    2.991277  20.000
118                    Danilho Doekhi   12.610839  13.000
119                       Sven Botman    9.863219  42.000
120                        Leo Petrot    5.131380   0.900
121                    Giovanni Leoni   10.966186  18.000
122                         Ben White   11.359139  45.000
123                   Maksim Osipenko    2.475086   5.000
124                     Jordan Lefort    3.563239   1.500
125                        Willy Boly    2.282173   1.500
126                      Lucas Africo    0.977139   0.300
127                  Lucas Mincarelli    5.887939   0.900
128                       Hector Fort    9.285422  10.000
129                 Rasmus Kristensen   12.623266  14.000
130                    Tanguy Nianzou    3.709060   1.500
131                       Nuno Mendes   12.943262  70.000
132                      Raul Asencio    7.087976  40.000
133                   Leandro Cabrera    4.972920   1.000
134                       Nathan Zeze    7.486747  15.000
135                  Christian Gunter    4.791435   3.500
136                  Santiago Mourino    7.806795   3.000
137                   Michael Svoboda    3.975187   2.500
138                      Robin Gosens   17.710568   8.000
139                    Vitali Lystsov    0.373532   0.300
140                  Carlos Dominguez    4.056752   3.000
141                     Matteo Gabbia    9.134262  14.000
142                  Pervis Estupinan   20.385993  30.000
143                   Kiryl Pyachenin    1.190501   0.750
144                           Willyan    2.182633   6.000
145                Leo Skiri Østigard    6.126500  10.000
146                      Ilya Gaponov    0.769108   0.600
147                      Nuno Tavares   22.707479  25.000
148                   Aaron Cresswell    2.443080   0.500
149                    Facundo Garces    3.566385   2.000
150                   Rein Van Helden    3.536407   2.500
151                      Felix Bacher    1.789518   2.000
152                   Mathias Olivera    6.963766  20.000
153                    Siebe Horemans    1.644431   3.500
154                     Carlens Arcus    2.518726   1.800
155                    Rayan Senhadji    0.930039   0.700
156               Sven Sostaric Karic    1.626327   1.000
157                   Nicolas Pallois    1.028990   0.400
158                 Dmitri Skopintsev    1.310233   2.500
159                      Miguel Lopes    0.178814   0.050
160                     Michael Keane    5.246577   5.000
161                     David Jurasek    5.039889   5.000
162                 Lukas Klostermann    3.198345   8.000
163                    Matteo Ruggeri    8.777251  16.000
164                           Ulisses    2.856638   1.500
165                       Marius Wolf    5.376377   3.000
166                              Viti    3.591043   2.000
167                      Yael Mouanga    5.729421   0.600
168               Nemanja Andjelkovic    0.722531   0.750
169                             Natan    7.881693   9.000
170                   Sherel Floranus    1.106966   0.850
171                   Luca Marianucci    8.025970   7.500
172                    Jelle Bataille    1.154098   2.500
173                      Georgi Zotov    0.380595   0.050
174                    Gautier Lloris    4.028603   3.000
175                       Nico Elvedi    5.211970   8.000
176                      Brian Olivan    1.867212   1.800
177                        James Hill   14.852916   3.000
178                        Lewis Hall   44.970682  32.000
179                       Lucas Olaza    1.428880   4.000
180                       Inigo Lekue    1.093099   2.000
181           Anselmo Garcia MacNulty    4.602371   1.500
182                 Aridane Hernandez    0.901261   0.300
183                     Nelson Semedo   15.821408   9.000
184                           Carmona    9.100266  12.000
185                   Matthias Ginter    6.058121   7.000
186                     Hasan Kurucay    1.457618   1.300
187                     Joao Ferreira    1.428882   3.000
188             Etienne Youte Kinkoue    9.176849   7.000
189                            Danilo    1.028333   3.500
190                      Dion De Neve    5.512682   0.900
191                       Jhon Lucumi    6.848245  22.000
192                      Robson Bambu    0.832828   3.000
193                   Domingos Duarte    2.508510   0.800
194                    Jonathan Panzo    1.488453   1.200
195                        Javi Lopez    6.142512   7.500
196                     Aurele Amenda    4.714449   7.500
197            Vyacheslav Bardybakhin    1.302823   0.500
198                     Mario Hermoso    1.918221   7.000
199                      Adam Webster    5.006670  11.000
200                       Dembo Sylla    1.810768   0.500
201                     Patrick Erras    2.215248   0.800
202                   Maxime Bernauer    2.131373   2.000
203                Aleksandr Silyanov    3.087656   6.000
204                        Guela Doue   14.366170  18.000
205                  Matthijs de Ligt   22.989597  38.000
206                    Illia Zabarnyi   37.486735  42.000
207                  Maximilian Bauer    2.969618   2.000
208                       Djed Spence   19.850989  20.000
209                       Kyle Walker    3.171383   4.000
210                     Dani Carvajal    0.965473   8.000
211                     Modibo Sagnan    5.155345   3.000
212                      Nayef Aguerd    3.203207  18.000
213                Jan Paul van Hecke   30.142854  32.000
214                  Olivier Aertssen    1.896902   0.750
215             Tolis Konstantopoulos    2.976315   0.800
216                Bruno Martins Indi    0.263187   0.650
217                  Raffael Behounek    1.674611   0.800
218                       Ivan Balliu    1.079676   1.400
219                  Ousmane Diomande    6.406301  45.000
220                       Theo Barbet    0.993902   0.375
221                      Nasser Djiga    8.716046  10.000
222                     Ruben Roosken    1.321621   0.600
223                 Christiaan Ravych    3.162960   4.500
224               Ze Pedro Figueiredo    0.846804   4.000
225                   Yerson Mosquera    8.707661   8.000
226                   Bryan Goncalves    0.805585   0.600
227                     Oliver Braude    3.100577   4.000
228                 Aaron Wan-Bissaka   35.657426  24.000
229                         Finn Stam    1.352246   0.450
230                Frederico Venancio    0.533869   0.600
231                      Srdjan Babic    1.969013   6.000
232                        Luck Zogbe    6.718931   2.500
233                      Loic Mbe Soh    2.459684   2.000
234                        Youri Baas    2.145142  12.000
235                Jeffrey Gouweleeuw    4.847766   1.500
236                  Emmanuel Agbadou   16.851520  20.000
237                       Lucas Digne   10.105004  10.000
238                 Ignacio Rodriguez    1.712396   0.600
239                 Cesar Azpilicueta    0.875893   1.500
240                 Ricardo Rodriguez    1.646133   2.000
241                    Carlos Augusto   11.729967  26.000
242                      Mamadou Sarr   13.592386  20.000
243                    Edmond Tapsoba    7.901811  35.000
244                   Benjamin Pavard    3.441052  25.000
245                    Tommy St. Jago    1.663918   1.000
246                      Rick Meissen    1.046215   0.500
247                        James Bree    8.246862   2.500
248                        Pablo Mari    3.401152   3.500
249                     Noahkai Banks    6.988416   6.000
250                   Filipe Ferreira    0.539159   0.100
251                         Joe Gomez    5.497622  20.000
252                            Patric    1.210611   2.500
253                           Patrick    0.727057   0.900
254                    Daniel Oyegoke    4.784350   0.500
255                   Cristian Romero   11.478596  50.000
256                    Matisse Didden    1.051960   1.000
257                  Eliaquim Mangala    0.202495   0.200
258                    Becir Omeragic    6.121394   4.500
259                      Nehuen Perez    3.160197  13.000
260                       Denis Vavro    7.240415   7.000
261                     Stefan Lainer    1.298311   1.200
262                  Roman Neustadter    0.358404   0.150
263                       Marc Bartra    2.663649   1.000
264                     Jacob Greaves   20.600665  18.000
265                   Alvaro Carreras    5.069970  35.000
266                      Joseph Aidoo    1.560983   1.200
267                    Lorenzo Milani    0.944157   0.225
268                    Idar Shumakhov    2.645608   1.000
269                    Henry Lawrence    2.547032   1.500
270                     Nahuel Molina    5.030266  20.000
271                       Angel Ortiz    5.225541   2.500
272                     Tomas Ribeiro    0.945891   1.000
273                    Daniele Rugani    0.416014   3.000
274                      Matt Doherty    7.014892   2.000
275                   Danila Khotulev    1.657145   0.400
276                       Luke Thomas   10.369090   6.000
277                         Oscar Gil    0.920082   0.700
278                      David Hancko    4.825802  30.000
279                     Nicolo Casale    3.697546   6.000
280                 Frederic Guilbert    3.738838   2.500
281                       Pau Navarro    5.570640   3.000
282                      Sael Kumbedi    6.203190   7.000
283                           Maracas    1.064393   1.000
284                       Conor Coady    5.108942   2.200
285                    Josip Stanisic    4.168321  32.000
286                  Timothy Castagne    7.584355  13.000
287                        Pau Torres   10.275709  32.000
288                  Hristiyan Petrov    1.017152   0.600
289                      Adamo Nagalo    1.009210   6.000
290                      Myenty Abena    0.428381   0.700
291                      Clement Akpa    7.727149   5.000
292                    Jens Mathijsen    1.371921   0.200
293                         Vanderson    9.851799  20.000
294                         Isak Hien    5.585801  30.000
295                 Kingsley Ehizibue    4.226666   2.400
296                        Brian Plat    1.818844   0.700
297                      Falaye Sacko    1.803018   1.500
298                 Souleyman Doumbia    0.657134   1.000
299                Sebastiano Luperto   12.570225   4.000
300                    Ilya Vakhaniya    2.545712   3.000
301                  Rodrigo Pinheiro    2.925398   2.500
302                       Zaid Romero    1.335350   3.000
303                    William Saliba   27.329219  80.000
304                Nico Schlotterbeck   10.629267  40.000
305                   Aritz Elustondo    1.800129   3.000
306                     Sergei Petrov    0.532378   0.400
307                      Haruya Fujii    1.803530   2.000
308                      Eder Militao    3.636173  30.000
309                       Bas Kuipers    1.325842   1.200
310                      Andrei Ratiu   13.351274  12.000
311                   Milos Veljkovic    2.413236   3.000
312                   Cameron Burgess   10.101514   2.000
313                        Adam Smith    3.336210   0.750
314                      Marco Friedl    3.604242  12.000
315                     Conor Bradley   23.375583  30.000
316                 Aleksandar Sedlar    0.868542   0.300
317                     Maxim Leitsch    2.980104   1.500
318                       Nathan Ngoy    1.786904   3.500
319                    Edgardo Farina    2.364954   1.000
320                       Diogo Dalot   29.885153  30.000
321                    Jorne Spileers    2.120492   2.000
322                      Mats Hummels    0.978482   2.000
323                 Zakaria El Ouahdi    8.893596  12.000
324                    Federico Barba    1.460366   0.500
325                   Ewoud Pletinckx    1.823089   1.800
326                        Leif Davis   30.290916  22.000
327                Leftheris Lyratzis    1.199507   0.850
328                    Giorgio Altare    3.027643   1.000
329                      Jan Bednarek   12.052459   9.000
330                        Oumar Sako    1.357816   3.000
331                    Pascal Stenzel    3.597166   2.000
332                     Abel Bretones    6.935631   4.000
333                       Raul Albiol    0.520601   1.000
334                    Almugera Kabar    5.196634   1.000
335                       Hugo Gambor    1.943296   1.000
336                Alessandro Circati    5.589079   8.000
337                  Thijmen Blokzijl    2.952065   2.000
338                     Mujaid Sadick    2.246772   8.000
339              Vyacheslav Karavayev    0.568892   3.500
340                    Rafik Belghali    4.608144   2.500
341                   Stefano Sabelli    2.609226   1.400
342                 Nikola Milenkovic   54.963660  35.000

In [75]:
comp_leftovers_test

                       Player  Value_pred   Value
0                Jon Aramburu    7.382454  15.000
1             Alphonso Davies    9.921329  50.000
2          Riccardo Calafiori   18.451519  35.000
3                  Fali Cande    4.265522   2.500
4              Romain Perraud    7.839115   5.000
5                Harry Clarke    8.403590   4.500
6                  Boyd Reith    0.663792   0.400
7            Zineddine Belaid    1.304509   0.800
8                  Yerry Mina    5.391975   3.000
9                 Aiham Ousou    2.256036   2.500
10            Youssouf Sabaly    1.678353   1.800
11              Daniel Vivian    9.873173  40.000
12     Maximilian Mittelstadt   11.182996  20.000
13                 Alex Munoz    2.156359   1.000
14         Jannik Vestergaard    4.217916   2.000
15                Ali Dembele    6.384009   0.900
16            Aleksei Tatayev    0.989558   0.800
17            Marvin da Graca    0.446246   0.400
18              Stephen Welsh    1.134380   1.000
19           Mahamadou Nagida    5.867799   0.800
20                Jonny Evans    1.506694   1.000
21              Pedro Pereira    9.716074   1.500
22          Milan Majstorovic    2.399094   1.800
23            Rayan Ait-Nouri  112.525886  35.000
24                Tiago Djalo    1.107173   8.000
25            Anthony Rouault    8.929831  10.000
26       Lorenzo De Silvestri    1.035993   0.800
27                Abdul Mumin    5.396029   5.000
28      Przemyslaw Frankowski    2.792127   7.000
29           Eduardo Quaresma    1.386342  18.000
30           Micky van de Ven   15.806155  50.000
31   Konstantinos Koulierakis   19.776502  25.000
32                Anton Gaaei    5.143324   7.000
33               Sergino Dest    1.067406  16.000
34                Abdel Abqar    6.718775   7.500
35                 Bamo Meite    3.242078   4.000
36              Gerard Martin    7.647155  12.000
37                   Iglesias    6.499871   3.500
38             Egor Pogostnov    2.070964   1.800
39             Ricardo Mangas    1.085748   2.500
40         Mike van der Hoorn    1.455850   1.000
41              Shawn Adewoye    1.462297   1.300
42                Jonas Rouhi    4.379772   2.000
43              Alexis Duarte    1.350133   3.000
44           Andrey Langovich    5.124423   3.000
45               Hamza Mendyl    0.916830   1.000
46           Mike Eerdhuijzen    2.295007   2.300
47            Ruben Fernandes    0.446220   0.050
48            Thierry Correia    3.131505   3.000
49              Marco Komenda    2.554694   0.800
50              Jordy Makengo    3.802472   6.000
51           Giorgio Scalvini    6.906229  35.000
52                 Rico Henry    3.833766  15.000
53               Victor Gomez    2.081214   6.000
54          Noussair Mazraoui   12.687411  25.000
55                 Hugo Bueno    2.389225   8.000
56                  Felix Agu    7.107442   8.000
57           Flavius Daniliuc    4.059341   2.700
58      Youssouf Ndayishimiye    5.783708  12.000
59                 Toti Gomes   15.080328  28.000
60                Ian Maatsen   28.007443  28.000
61             Evgeni Morozov    1.451493   3.000
62            Duplexe Tchamba    1.510231   1.000
63                  Wout Faes   17.353546  15.000
64               Carlos Ponck    0.390352   0.600
65                Tim Drexler    6.096504   3.000
66             Javi Rodriguez   15.260388  15.000
67                Lloyd Kelly    5.365554  16.000
68               Ivan Marquez    0.885165   0.600
69            Cristian Castro    2.953298   0.800
70              Igor Yurganov    0.803092   0.500
71               Eduard Sobol    1.007344   0.900
72        Patrick van Aanholt    0.457518   0.500
73             Goncalo Inacio    4.260795  45.000
74               Javi Sanchez    4.648815   1.500
75              Ferland Mendy    1.641643  14.000
76              Boris Popovic    1.113808   1.500
77             Josko Gvardiol   81.945783  75.000
78            Tommaso Augello    8.813950   1.800
79                Ivan Ordets    2.124404   1.000
80              Ryan Alebiosu    2.137437   0.500
81               Rafael Toloi    0.993698   1.400
82              Calvin Bassey   25.719733  25.000
83       Michael Amir Murillo    5.424995  10.000
84              Aaron Meijers    0.147236   0.075
85          Mathias Jorgensen    0.578132   0.500
86            Ibrahima Konate   25.902640  60.000
87              Botond Balogh    8.320057   2.400
88                Amos Pieper    3.547196   3.500
89            Oleksandr Filin    1.358352   1.000
90      Boli Bolingoli-Mbombo    0.548032   0.500
91           Mouctar Diakhaby    3.111442   2.000
92                Ilay Camara    6.176645   4.000
93                 Alex Valle    8.261578   6.000
94            Emanuele Valeri   19.894904   3.000
95               Armando Izzo    3.024282   1.500
96         Vasilios Zagaritis    3.080230   0.700
97              Egor Teslenko    5.169666   2.000
98              Wesley Fofana   11.244110  25.000
99                    Ben Mee    1.529116   0.700
100        Soumaila Coulibaly    5.332280   8.000
101                 Issa Diop    7.439919  14.000
102               Jesus Areso    8.719166  12.000
103           Dayot Upamecano    5.802653  50.000
104            Cedric Zesiger    5.759082   7.000
105              Craig Dawson    2.653724   1.500
106             Alexander Bah    1.004085  10.000
107              David Torres    5.964739   1.500
108                Karol Fila    1.106240   0.600
109       Giangiacomo Magnani    3.013312   1.800
110         Vitaliy Mykolenko   26.710248  28.000
111                Hauke Wahl    3.741049   1.500
112                Glenn Bijl    0.979102   1.500
113              Tiago Esgaio    1.449052   0.900
114            Wilfried Singo    9.766611  25.000
115            Manuel Lazzari    2.354398   3.500
116                      Nino    2.842653  11.000
117             Scott McKenna    4.678380   4.000
118                 Mats Rots    3.085739   1.000
119         Godfried Frimpong    2.628273   2.000
120           Renato Pantalon    0.876745   0.600
121           Moussa Niakhate    3.283888  15.000
122   Francisco Reis Ferreira    0.717491   0.700
123             Mads Roerslev   14.059811   6.000
124             Jordan Zemura    8.096272   4.500
125            Andrea Carboni    7.578563   2.800
126          Andrew Robertson   10.132296  18.000
127                Juan Jesus    1.231331   1.500
128          Jonathan Mutombo    1.424459   0.500
129              Joseph Okumu    3.583112   7.000
130                Marco Sala    2.233142   0.900
131                Diego Rico    3.685365   1.200
132              Finn Jeltsch    6.999854  20.000
133                Max Kilman   20.270070  25.000
134              Thilo Kehrer    5.788540  20.000
135           Brandon Mechele    1.581629   3.500
136         Gabriel Magalhaes   26.661493  75.000
137        Anass Salah-Eddine    3.607879   8.000
138          Javier Manquillo    1.077401   1.000
139       Redouan El Yaakoubi    0.396959   0.550
140                Kenny Lala    1.921861   2.000
141        Nathan Wood-Gordon   10.954604   3.500
142     Aleksandr Soldatenkov    1.160517   4.000
143               Logan Costa   13.051794  18.000
144           Abdoulaye Bamba    0.890292   0.300
145             Hjalmar Ekdal    0.786337   4.500
146           Thierry Lutonda    0.818922   0.300
147                  Angelino   11.758703  20.000
148             Rafik Messali    4.992481   0.800
149            Javi Hernandez    8.089079   2.500
150               Fran Garcia    7.106466  18.000
151       Konstantin Savichev    0.968234   0.900
152        Christian Kabasele    1.960285   0.700
153              David Hrncar    2.625595   1.200
154             Antoine Mendy    6.092617   2.500
155           Castello Lukeba    6.660885  40.000
156            Paulo Oliveira    0.646216   1.000
157                 Yoel Lago    4.873616   1.000
158            Emmanuel Kakou    3.823575   1.000
159               Malang Sarr    3.398451   5.000
160       Keven Schlotterbeck    4.506353   6.000
161            Jose Luis Gayà    2.649736   9.000
162            Wolke Janssens    0.524120   0.400
163           Mohammed Salisu    3.338876  12.000
164               Oumar Solet    8.350781  18.000
165             Marcos Senesi    5.708753  22.000
166              Andy Pelmard    2.475226   2.000
167              Semm Renders    3.299754   1.500
168          Antonee Robinson   49.734515  35.000
169        Brendan Chardonnet    3.222570   6.000
170            Inigo Martinez    3.531746   5.000
171                    Catena    7.755805   3.000
172            Jarell Quansah   10.656400  20.000
173                Joe Scally    9.556125  10.000
174                    Michel    0.998785   1.000
175        Jose Luis Palomino    0.950581   0.700
176           Matija Nastasic    2.154813   0.800
177              Kelvin Amian    3.843314   2.500
178             Marvin Elimbi    1.068342   0.750
179            Marc Cucurella   33.957296  35.000
180          Maksim Shnaptsev    1.648287   0.300
181               Ahmed Touba    1.842488   2.500
182                      Igor    6.696037  20.000
183            Tomas Palacios    4.464086   4.000
184              Jules Kounde   10.305749  65.000
185               Matte Smets    3.664168  13.000
186             Ricardo Visus    1.793743   0.750
187            German Ignatov    2.786282   0.500
188         Roberto Fernandez    2.109439   3.500
189               Kim Min-jae    5.143753  40.000
190             Ibe Hautekiet    2.230596   3.500
191                    Moises    1.810556   5.000
192             Lukas Ullrich   13.516030   8.000
193            Lucas Calegari    1.583356   3.500
194        Jordan Torunarigha    1.469161   4.000
195             Jack Stephens    4.830192   1.500
196                Jose Gomes    2.073764   1.000
197               Axel Witsel    0.713535   2.000
198            Berat Djimsiti    4.732762   6.000
199          Mutalip Alibekov    0.899484   0.700
200             Sergio Akieme   11.322621   7.000
201                Marc Guehi   40.446660  45.000
202         Tsuyoshi Watanabe    3.480378   9.000
203               Dinis Pinto    3.175125   1.500
204             Alan Matturro    8.092056   7.000
205         Francesco Zampano    3.084072   1.000
206              Robert Gumny    3.149030   1.500
207                Raul Silva    0.248620   0.100
208             Thomas Beelen    1.773519   8.000
209             Juan Berrocal    3.194234   1.500
210           Maksim Nenakhov    1.759333   3.000
211             Diego Coppola   16.762552  10.000
212            Julian Ryerson    9.543170  20.000
213                    Orinho    1.227922   0.600
214          Leopold Querfeld   16.672735  13.000
215            Willy Kambwala    7.126652   4.000
216           Lucas Hernandez    1.610735  25.000
217         Toby Alderweireld    1.467780   2.000
218              Manuel Osifo    1.836879   0.700
219              Adam Marusic    5.351296   3.500
220           Sinaly Diomande    9.239795   5.000
221           Ladislav Krejci    8.454647  12.000
222               Emil Krafth    3.613562   2.000
223          Massadio Haidara    1.792952   1.500
224              Jordan Amavi    1.557886   1.500
225        Jose Maria Gimenez    2.891190  20.000
226               Chico Lamba    3.869347   3.000
227        Myles Lewis-Skelly   28.847683  45.000
228        Alexsandro Ribeiro   10.629455  20.000
229          Domagoj Bradaric    6.034364   4.000

# Модель 4

In [55]:
X_train = X_train[['G+A', 'G+A.1', 'Ast', 'G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'G+A.1', 'Ast', 'G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [62]:
coeffs_df

               coeff
league_GB1  0.626925
Age        -0.588286
90s         0.431176
league_IT1  0.352984
league_L1   0.312027
league_ES1  0.291146
league_FR1  0.257755
Ast         0.213310
G-PK        0.185899
Sh/90       0.166882
league_NL1 -0.148636
G+A.1      -0.141414
TklW       -0.111273
Ast.1       0.103537
league_PO1 -0.098109
G+A        -0.060760
league_RU1 -0.029089
CrdY        0.004951
Int        -0.002861

In [61]:
metrics

            MAE       RMSE      MAPE        R2
test   5.566665  11.325218  0.913154  0.300058
train  4.647761   9.568882  0.886695  0.352477

In [63]:
comp_leftovers_train

                               Player  Value_pred   Value
0              Alessandro Marcandalli    4.732267   2.000
1                     Tyrick Mitchell   35.508587  25.000
2                    Valentin Paltsev    3.064061   2.500
3                        Teo Quintero    0.714488   0.600
4                      Kaio Pantaleao    0.747734   1.800
5                       Aitor Paredes    6.375678  22.000
6                    Fredrik Oppegard    1.489391   0.600
7                       Sergei Bozhin    1.026532   0.700
8                  Francisco Petrasso    1.282803   1.500
9                         Dara O'Shea   30.227170  14.000
10                        Pedro Porro   64.970657  38.000
11                      Fikayo Tomori    3.611861  20.000
12                             Marcao    1.407608   2.000
13                       Martin Erlic    4.134103   4.000
14                  Alexandre Penetra    2.813113   9.000
15                         Sacha Boey    4.815819  18.000
16                      Kyriani Sabbe    3.162967   4.500
17                     Djibril Sidibe    2.037778   1.000
18                      Seiya Maikuma    1.094520   4.000
19                      Rick Karsdorp    0.424030   3.000
20                Mohamed Abdelmoneim    2.151591   4.000
21                  Christian Mawissa    6.105967  15.000
22                     Thomas Meunier    2.511856   2.000
23                         Mats Deijl    2.302524   2.000
24        Marcelo dos Santos Ferreira    0.548511   0.100
25                      Neco Williams   40.482460  20.000
26                  Edoardo Goldaniga    3.979954   3.000
27                     Danny da Costa    2.242560   1.500
28                      Sergi Cardona   17.327005  10.000
29                        Jon Pacheco    3.324555   6.000
30                 Viktor Aleksandrov    1.832222   1.200
31                  Rustam Ashurmatov    0.676572   0.600
32                     Aske Adelgaard    1.952624   0.850
33                        Omar Traore    6.932382   4.000
34                    Emmanuel Biumla    7.544890   4.000
35                      Omar Alderete    8.730042   8.000
36                    Oscar de Marcos    1.634151   1.500
37                     Hassane Kamara    5.516322   3.500
38                   Mimeirhel Benita    2.452973   1.000
39                    Valentin Rosier    5.389219   3.000
40                 Abdukodir Khusanov    7.048959  35.000
41                  Nicolas Valentini    4.981613   6.000
42                      Radu Dragusin   14.835943  25.000
43                       Martin Frese    2.328391   2.000
44                  Mikayil Ngor Faye    5.674987   6.000
45                         Leo Greiml    2.459557   2.000
46                     Mitchell Dijks    0.540774   0.600
47                         Juan Foyth    4.799154  15.000
48                         Maks Dziov    2.281352   0.700
49                     Martin Valjent    6.239942   6.000
50                       Matvei Lukin    2.457739   1.200
51                        Emin Bayram    2.735407   3.500
52                       Cesar Montes    1.074267   4.500
53                           Ola Aina   18.846800  22.000
54                        David Alaba    0.753156   6.000
55                 Bas van den Eynden    1.971218   0.700
56             Trent Alexander-Arnold   63.088882  75.000
57                Christopher Mamengi    0.624094   0.250
58                   Valentin Gendrey    7.845694   7.000
59                      Oleg Reabciuk    2.058404   4.000
60                   Enrico Del Prato   15.780553   6.500
61                       Ivan Smolcic    5.072483   1.800
62                        Joao Mendes    2.212906   2.000
63                         Hiroki Ito    1.752919  25.000
64                        Mike Kleijn    1.203745   0.250
65                         Nathan Ake    4.320378  25.000
66                    Antonio Rudiger    3.269457  20.000
67                     Patrick Mainka    6.657168   3.000
68                Dimitris Giannoulis    7.808070   3.000
69                         Ezri Konsa   22.109919  35.000
70                     Marco Palestra    4.706771   3.500
71                      Frans Kratzig    9.185673   3.500
72                          Emil Holm    5.544293   8.000
73             El Chadaille Bitshiabu    7.511758  18.000
74                      Hiroki Sekine    5.078115   1.200
75            Konstantin Nizhegorodov    1.078406   0.300
76                         Ko Itakura    8.383566  12.000
77                       Igor Vujacic    1.345955   3.000
78                         Borna Sosa    3.031798   4.500
79                    Marcus Pedersen    5.239243   3.000
80                     Ramon Hendriks    5.279321   5.000
81                    Florian Lejeune    8.865761   2.500
82                     Gleison Bremer    2.250122  50.000
83                      Marvin Senaya    2.715359   1.800
84                    Benedikt Gimber    4.457408   3.000
85                       Tuur Rommens    5.263185   4.000
86                     Alberto Moreno    2.217506   1.500
87                   Yunis Abdelhamid    0.579645   0.400
88                     Rosen Bozhinov    2.101340   0.400
89                     Koni De Winter   12.385658  22.000
90                           Kialonda    6.863990   3.500
91                   Jonas Fohrenbach    3.379009   1.500
92                         Lewis Dunk    5.975697   6.000
93                      Pierre Cornud    1.470158   0.800
94                     Piero Hincapie   17.074235  50.000
95                  Yarek Gasiorowski    6.113163   7.500
96                          Rob Nizet    1.096434   0.350
97                   Nathan Patterson   10.109497  15.000
98                    James Tarkowski   10.078888   9.000
99                        Maxime Busi    0.861016   1.000
100                         Lucas Hey    1.677351   5.000
101                    Theo Hernandez   22.166589  35.000
102              Alec Van Hoorenbeeck    1.064619   0.800
103                     Erik Schouten    0.350957   0.200
104                 Charlie Cresswell   21.276850  10.000
105                 Marc-Oliver Kempf    4.832679   3.000
106                   Alexandre Pinto    0.757796   0.500
107                    Dani Fernandez    1.383840   0.800
108                     Cesar Tarrega   14.156034  10.000
109                   Mardochee Nzita    1.189779   1.000
110                     Moussa Diarra    4.819132   1.800
111                       Aihen Munoz    2.901813   4.000
112                       Jorge Saenz    3.285558   1.500
113                     Gideon Mensah    3.559910   4.000
114                        Robin Koch    7.333192  18.000
115                        Karol Mets    1.349710   1.300
116                     Ethan Pinnock    7.079822   7.000
117                  Olivier Boscagli    3.026085  20.000
118                    Danilho Doekhi   11.950824  13.000
119                       Sven Botman   10.124515  42.000
120                        Leo Petrot    5.269398   0.900
121                    Giovanni Leoni   10.917438  18.000
122                         Ben White   11.419246  45.000
123                   Maksim Osipenko    2.615192   5.000
124                     Jordan Lefort    3.696647   1.500
125                        Willy Boly    2.192927   1.500
126                      Lucas Africo    0.970721   0.300
127                  Lucas Mincarelli    5.929819   0.900
128                       Hector Fort    9.605089  10.000
129                 Rasmus Kristensen   12.899427  14.000
130                    Tanguy Nianzou    3.716160   1.500
131                       Nuno Mendes   12.401461  70.000
132                      Raul Asencio    7.154019  40.000
133                   Leandro Cabrera    5.155848   1.000
134                       Nathan Zeze    7.453018  15.000
135                  Christian Gunter    4.740701   3.500
136                  Santiago Mourino    7.724464   3.000
137                   Michael Svoboda    3.887705   2.500
138                      Robin Gosens   19.284145   8.000
139                    Vitali Lystsov    0.362639   0.300
140                  Carlos Dominguez    4.020325   3.000
141                     Matteo Gabbia    9.200389  14.000
142                  Pervis Estupinan   19.345542  30.000
143                   Kiryl Pyachenin    1.191462   0.750
144                           Willyan    2.090893   6.000
145                Leo Skiri Østigard    6.218479  10.000
146                      Ilya Gaponov    0.753507   0.600
147                      Nuno Tavares   22.446680  25.000
148                   Aaron Cresswell    2.490836   0.500
149                    Facundo Garces    3.604447   2.000
150                   Rein Van Helden    3.614023   2.500
151                      Felix Bacher    1.859072   2.000
152                   Mathias Olivera    6.922422  20.000
153                    Siebe Horemans    1.693794   3.500
154                     Carlens Arcus    2.575679   1.800
155                    Rayan Senhadji    0.930546   0.700
156               Sven Sostaric Karic    1.627584   1.000
157                   Nicolas Pallois    1.055383   0.400
158                 Dmitri Skopintsev    1.324456   2.500
159                      Miguel Lopes    0.179897   0.050
160                     Michael Keane    5.312048   5.000
161                     David Jurasek    5.010132   5.000
162                 Lukas Klostermann    3.251017   8.000
163                    Matteo Ruggeri    8.848971  16.000
164                           Ulisses    2.821114   1.500
165                       Marius Wolf    5.469882   3.000
166                              Viti    3.664123   2.000
167                      Yael Mouanga    5.660225   0.600
168               Nemanja Andjelkovic    0.706574   0.750
169                             Natan    7.976772   9.000
170                   Sherel Floranus    1.126613   0.850
171                   Luca Marianucci    7.980682   7.500
172                    Jelle Bataille    1.157903   2.500
173                      Georgi Zotov    0.411280   0.050
174                    Gautier Lloris    4.198376   3.000
175                       Nico Elvedi    5.212801   8.000
176                      Brian Olivan    1.872898   1.800
177                        James Hill   16.133925   3.000
178                        Lewis Hall   45.953049  32.000
179                       Lucas Olaza    1.436644   4.000
180                       Inigo Lekue    1.084837   2.000
181           Anselmo Garcia MacNulty    4.497085   1.500
182                 Aridane Hernandez    0.899745   0.300
183                     Nelson Semedo   15.716531   9.000
184                           Carmona    8.978585  12.000
185                   Matthias Ginter    5.990068   7.000
186                     Hasan Kurucay    1.488676   1.300
187                     Joao Ferreira    1.422343   3.000
188             Etienne Youte Kinkoue    9.079858   7.000
189                            Danilo    1.005603   3.500
190                      Dion De Neve    5.520636   0.900
191                       Jhon Lucumi    6.896271  22.000
192                      Robson Bambu    0.835036   3.000
193                   Domingos Duarte    2.570246   0.800
194                    Jonathan Panzo    1.494472   1.200
195                        Javi Lopez    6.210400   7.500
196                     Aurele Amenda    5.071979   7.500
197            Vyacheslav Bardybakhin    1.246010   0.500
198                     Mario Hermoso    2.000377   7.000
199                      Adam Webster    5.019887  11.000
200                       Dembo Sylla    1.801263   0.500
201                     Patrick Erras    2.272357   0.800
202                   Maxime Bernauer    2.116833   2.000
203                Aleksandr Silyanov    3.068836   6.000
204                        Guela Doue   14.282224  18.000
205                  Matthijs de Ligt   22.370834  38.000
206                    Illia Zabarnyi   38.473189  42.000
207                  Maximilian Bauer    2.870617   2.000
208                       Djed Spence   20.098342  20.000
209                       Kyle Walker    3.170143   4.000
210                     Dani Carvajal    0.952256   8.000
211                     Modibo Sagnan    5.252605   3.000
212                      Nayef Aguerd    3.126885  18.000
213                Jan Paul van Hecke   30.408404  32.000
214                  Olivier Aertssen    1.889862   0.750
215             Tolis Konstantopoulos    2.860096   0.800
216                Bruno Martins Indi    0.266162   0.650
217                  Raffael Behounek    1.776464   0.800
218                       Ivan Balliu    1.075763   1.400
219                  Ousmane Diomande    6.125243  45.000
220                       Theo Barbet    0.975842   0.375
221                      Nasser Djiga    8.294762  10.000
222                     Ruben Roosken    1.345018   0.600
223                 Christiaan Ravych    3.133220   4.500
224               Ze Pedro Figueiredo    0.841052   4.000
225                   Yerson Mosquera    8.782427   8.000
226                   Bryan Goncalves    0.803571   0.600
227                     Oliver Braude    3.101139   4.000
228                 Aaron Wan-Bissaka   37.223512  24.000
229                         Finn Stam    1.353566   0.450
230                Frederico Venancio    0.535340   0.600
231                      Srdjan Babic    1.989460   6.000
232                        Luck Zogbe    7.043192   2.500
233                      Loic Mbe Soh    2.484468   2.000
234                        Youri Baas    2.213253  12.000
235                Jeffrey Gouweleeuw    4.917639   1.500
236                  Emmanuel Agbadou   16.588270  20.000
237                       Lucas Digne   10.220046  10.000
238                 Ignacio Rodriguez    1.698723   0.600
239                 Cesar Azpilicueta    0.867825   1.500
240                 Ricardo Rodriguez    1.641773   2.000
241                    Carlos Augusto   11.640171  26.000
242                      Mamadou Sarr   13.981585  20.000
243                    Edmond Tapsoba    7.695592  35.000
244                   Benjamin Pavard    3.449892  25.000
245                    Tommy St. Jago    1.681772   1.000
246                      Rick Meissen    1.010122   0.500
247                        James Bree    8.210141   2.500
248                        Pablo Mari    3.493544   3.500
249                     Noahkai Banks    6.950352   6.000
250                   Filipe Ferreira    0.536407   0.100
251                         Joe Gomez    5.372094  20.000
252                            Patric    1.178127   2.500
253                           Patrick    0.724217   0.900
254                    Daniel Oyegoke    5.090030   0.500
255                   Cristian Romero   11.150662  50.000
256                    Matisse Didden    1.046811   1.000
257                  Eliaquim Mangala    0.195515   0.200
258                    Becir Omeragic    6.047643   4.500
259                      Nehuen Perez    3.246403  13.000
260                       Denis Vavro    7.008580   7.000
261                     Stefan Lainer    1.295206   1.200
262                  Roman Neustadter    0.360416   0.150
263                       Marc Bartra    2.652535   1.000
264                     Jacob Greaves   20.813518  18.000
265                   Alvaro Carreras    5.193877  35.000
266                      Joseph Aidoo    1.531358   1.200
267                    Lorenzo Milani    1.012655   0.225
268                    Idar Shumakhov    2.684676   1.000
269                    Henry Lawrence    2.632221   1.500
270                     Nahuel Molina    5.074524  20.000
271                       Angel Ortiz    5.261336   2.500
272                     Tomas Ribeiro    0.923937   1.000
273                    Daniele Rugani    0.429242   3.000
274                      Matt Doherty    7.220875   2.000
275                   Danila Khotulev    1.622382   0.400
276                       Luke Thomas   10.490936   6.000
277                         Oscar Gil    0.920450   0.700
278                      David Hancko    4.231505  30.000
279                     Nicolo Casale    3.642261   6.000
280                 Frederic Guilbert    3.789397   2.500
281                       Pau Navarro    5.507469   3.000
282                      Sael Kumbedi    6.081901   7.000
283                           Maracas    1.072155   1.000
284                       Conor Coady    5.185524   2.200
285                    Josip Stanisic    4.134291  32.000
286                  Timothy Castagne    7.544775  13.000
287                        Pau Torres   10.260882  32.000
288                  Hristiyan Petrov    0.949380   0.600
289                      Adamo Nagalo    1.028945   6.000
290                      Myenty Abena    0.410650   0.700
291                      Clement Akpa    7.942604   5.000
292                    Jens Mathijsen    1.308244   0.200
293                         Vanderson    9.581670  20.000
294                         Isak Hien    5.662152  30.000
295                 Kingsley Ehizibue    4.184336   2.400
296                        Brian Plat    1.858511   0.700
297                      Falaye Sacko    1.789249   1.500
298                 Souleyman Doumbia    0.679344   1.000
299                Sebastiano Luperto   12.529509   4.000
300                    Ilya Vakhaniya    2.583166   3.000
301                  Rodrigo Pinheiro    2.949810   2.500
302                       Zaid Romero    1.383121   3.000
303                    William Saliba   29.145217  80.000
304                Nico Schlotterbeck   10.576435  40.000
305                   Aritz Elustondo    1.811714   3.000
306                     Sergei Petrov    0.538465   0.400
307                      Haruya Fujii    1.830764   2.000
308                      Eder Militao    3.673556  30.000
309                       Bas Kuipers    1.366494   1.200
310                      Andrei Ratiu   12.881066  12.000
311                   Milos Veljkovic    2.372216   3.000
312                   Cameron Burgess   10.023232   2.000
313                        Adam Smith    3.390011   0.750
314                      Marco Friedl    3.664691  12.000
315                     Conor Bradley   23.952119  30.000
316                 Aleksandar Sedlar    0.853197   0.300
317                     Maxim Leitsch    3.041920   1.500
318                       Nathan Ngoy    1.760760   3.500
319                    Edgardo Farina    2.396960   1.000
320                       Diogo Dalot   29.032200  30.000
321                    Jorne Spileers    2.102665   2.000
322                      Mats Hummels    0.991976   2.000
323                 Zakaria El Ouahdi    7.298645  12.000
324                    Federico Barba    1.427749   0.500
325                   Ewoud Pletinckx    1.784967   1.800
326                        Leif Davis   30.856195  22.000
327                Leftheris Lyratzis    1.170296   0.850
328                    Giorgio Altare    2.987567   1.000
329                      Jan Bednarek   12.711917   9.000
330                        Oumar Sako    1.357854   3.000
331                    Pascal Stenzel    4.246513   2.000
332                     Abel Bretones    7.013459   4.000
333                       Raul Albiol    0.520960   1.000
334                    Almugera Kabar    4.953390   1.000
335                       Hugo Gambor    1.988779   1.000
336                Alessandro Circati    5.562686   8.000
337                  Thijmen Blokzijl    3.017541   2.000
338                     Mujaid Sadick    2.320616   8.000
339              Vyacheslav Karavayev    0.551490   3.500
340                    Rafik Belghali    4.059320   2.500
341                   Stefano Sabelli    2.652104   1.400
342                 Nikola Milenkovic   55.886418  35.000

In [64]:
comp_leftovers_test

                       Player  Value_pred   Value
0                Jon Aramburu    7.562272  15.000
1             Alphonso Davies    9.947059  50.000
2          Riccardo Calafiori   18.211865  35.000
3                  Fali Cande    4.290052   2.500
4              Romain Perraud    7.862222   5.000
5                Harry Clarke    8.099773   4.500
6                  Boyd Reith    0.648006   0.400
7            Zineddine Belaid    1.324183   0.800
8                  Yerry Mina    5.116593   3.000
9                 Aiham Ousou    2.272183   2.500
10            Youssouf Sabaly    1.694319   1.800
11              Daniel Vivian   10.136262  40.000
12     Maximilian Mittelstadt   11.294220  20.000
13                 Alex Munoz    2.162747   1.000
14         Jannik Vestergaard    4.192117   2.000
15                Ali Dembele    6.480126   0.900
16            Aleksei Tatayev    0.978465   0.800
17            Marvin da Graca    0.452246   0.400
18              Stephen Welsh    1.112032   1.000
19           Mahamadou Nagida    5.803054   0.800
20                Jonny Evans    1.492257   1.000
21              Pedro Pereira    9.873803   1.500
22          Milan Majstorovic    2.282975   1.800
23            Rayan Ait-Nouri  110.164939  35.000
24                Tiago Djalo    1.179921   8.000
25            Anthony Rouault    8.981491  10.000
26       Lorenzo De Silvestri    1.021381   0.800
27                Abdul Mumin    5.507920   5.000
28      Przemyslaw Frankowski    2.848533   7.000
29           Eduardo Quaresma    1.395911  18.000
30           Micky van de Ven   15.778805  50.000
31   Konstantinos Koulierakis   19.279560  25.000
32                Anton Gaaei    5.157424   7.000
33               Sergino Dest    1.127391  16.000
34                Abdel Abqar    6.845454   7.500
35                 Bamo Meite    3.182559   4.000
36              Gerard Martin    7.694660  12.000
37                   Iglesias    6.359043   3.500
38             Egor Pogostnov    2.070903   1.800
39             Ricardo Mangas    1.092996   2.500
40         Mike van der Hoorn    1.449094   1.000
41              Shawn Adewoye    1.464376   1.300
42                Jonas Rouhi    4.170856   2.000
43              Alexis Duarte    1.326672   3.000
44           Andrey Langovich    5.089198   3.000
45               Hamza Mendyl    0.931176   1.000
46           Mike Eerdhuijzen    2.356468   2.300
47            Ruben Fernandes    0.444337   0.050
48            Thierry Correia    3.112942   3.000
49              Marco Komenda    2.563072   0.800
50              Jordy Makengo    3.706652   6.000
51           Giorgio Scalvini    7.698705  35.000
52                 Rico Henry    3.652468  15.000
53               Victor Gomez    2.061483   6.000
54          Noussair Mazraoui   12.785152  25.000
55                 Hugo Bueno    2.420736   8.000
56                  Felix Agu    7.175662   8.000
57           Flavius Daniliuc    4.001002   2.700
58      Youssouf Ndayishimiye    5.900261  12.000
59                 Toti Gomes   15.489325  28.000
60                Ian Maatsen   28.443730  28.000
61             Evgeni Morozov    1.440571   3.000
62            Duplexe Tchamba    1.539941   1.000
63                  Wout Faes   17.868101  15.000
64               Carlos Ponck    0.374956   0.600
65                Tim Drexler    5.835644   3.000
66             Javi Rodriguez   15.935418  15.000
67                Lloyd Kelly    5.440086  16.000
68               Ivan Marquez    0.902334   0.600
69            Cristian Castro    3.015972   0.800
70              Igor Yurganov    0.797266   0.500
71               Eduard Sobol    0.955812   0.900
72        Patrick van Aanholt    0.456828   0.500
73             Goncalo Inacio    4.365214  45.000
74               Javi Sanchez    4.693701   1.500
75              Ferland Mendy    1.619390  14.000
76              Boris Popovic    1.109500   1.500
77             Josko Gvardiol   77.740868  75.000
78            Tommaso Augello    9.297064   1.800
79                Ivan Ordets    2.140960   1.000
80              Ryan Alebiosu    2.218701   0.500
81               Rafael Toloi    1.012504   1.400
82              Calvin Bassey   26.245620  25.000
83       Michael Amir Murillo    5.479090  10.000
84              Aaron Meijers    0.146081   0.075
85          Mathias Jorgensen    0.595921   0.500
86            Ibrahima Konate   25.859116  60.000
87              Botond Balogh    8.534845   2.400
88                Amos Pieper    3.550160   3.500
89            Oleksandr Filin    1.380515   1.000
90      Boli Bolingoli-Mbombo    0.551682   0.500
91           Mouctar Diakhaby    3.195867   2.000
92                Ilay Camara    5.771643   4.000
93                 Alex Valle    8.368042   6.000
94            Emanuele Valeri   19.910684   3.000
95               Armando Izzo    3.154956   1.500
96         Vasilios Zagaritis    3.142798   0.700
97              Egor Teslenko    5.156287   2.000
98              Wesley Fofana   11.341871  25.000
99                    Ben Mee    1.463808   0.700
100        Soumaila Coulibaly    5.566286   8.000
101                 Issa Diop    7.394552  14.000
102               Jesus Areso    9.214485  12.000
103           Dayot Upamecano    5.777226  50.000
104            Cedric Zesiger    5.773761   7.000
105              Craig Dawson    2.655172   1.500
106             Alexander Bah    1.011672  10.000
107              David Torres    5.963916   1.500
108                Karol Fila    1.121514   0.600
109       Giangiacomo Magnani    3.059708   1.800
110         Vitaliy Mykolenko   27.701595  28.000
111                Hauke Wahl    3.755065   1.500
112                Glenn Bijl    0.959772   1.500
113              Tiago Esgaio    1.432353   0.900
114            Wilfried Singo    9.658186  25.000
115            Manuel Lazzari    2.336881   3.500
116                      Nino    2.775147  11.000
117             Scott McKenna    4.752061   4.000
118                 Mats Rots    3.126104   1.000
119         Godfried Frimpong    2.740679   2.000
120           Renato Pantalon    0.867939   0.600
121           Moussa Niakhate    3.416426  15.000
122   Francisco Reis Ferreira    0.720473   0.700
123             Mads Roerslev   14.301326   6.000
124             Jordan Zemura    8.134595   4.500
125            Andrea Carboni    7.687355   2.800
126          Andrew Robertson   10.057927  18.000
127                Juan Jesus    1.229534   1.500
128          Jonathan Mutombo    1.444636   0.500
129              Joseph Okumu    3.599779   7.000
130                Marco Sala    2.143468   0.900
131                Diego Rico    3.714352   1.200
132              Finn Jeltsch    6.954334  20.000
133                Max Kilman   20.716422  25.000
134              Thilo Kehrer    5.916526  20.000
135           Brandon Mechele    1.590130   3.500
136         Gabriel Magalhaes   26.860248  75.000
137        Anass Salah-Eddine    3.706024   8.000
138          Javier Manquillo    1.041442   1.000
139       Redouan El Yaakoubi    0.380383   0.550
140                Kenny Lala    2.032757   2.000
141        Nathan Wood-Gordon   10.912825   3.500
142     Aleksandr Soldatenkov    1.178720   4.000
143               Logan Costa   13.590734  18.000
144           Abdoulaye Bamba    0.892365   0.300
145             Hjalmar Ekdal    0.781404   4.500
146           Thierry Lutonda    0.837407   0.300
147                  Angelino   11.580394  20.000
148             Rafik Messali    5.161609   0.800
149            Javi Hernandez    8.104406   2.500
150               Fran Garcia    7.050768  18.000
151       Konstantin Savichev    0.979222   0.900
152        Christian Kabasele    1.974831   0.700
153              David Hrncar    2.474582   1.200
154             Antoine Mendy    6.270567   2.500
155           Castello Lukeba    6.665677  40.000
156            Paulo Oliveira    0.633521   1.000
157                 Yoel Lago    4.720657   1.000
158            Emmanuel Kakou    3.889163   1.000
159               Malang Sarr    3.381044   5.000
160       Keven Schlotterbeck    4.533364   6.000
161            Jose Luis Gayà    2.624079   9.000
162            Wolke Janssens    0.521596   0.400
163           Mohammed Salisu    3.246197  12.000
164               Oumar Solet    8.175524  18.000
165             Marcos Senesi    5.722575  22.000
166              Andy Pelmard    2.451554   2.000
167              Semm Renders    3.277152   1.500
168          Antonee Robinson   52.363763  35.000
169        Brendan Chardonnet    3.257075   6.000
170            Inigo Martinez    3.587471   5.000
171                    Catena    7.818282   3.000
172            Jarell Quansah   10.514603  20.000
173                Joe Scally    9.830888  10.000
174                    Michel    0.956579   1.000
175        Jose Luis Palomino    0.944084   0.700
176           Matija Nastasic    2.230957   0.800
177              Kelvin Amian    3.879327   2.500
178             Marvin Elimbi    1.030363   0.750
179            Marc Cucurella   34.623038  35.000
180          Maksim Shnaptsev    1.552335   0.300
181               Ahmed Touba    1.902435   2.500
182                      Igor    6.653599  20.000
183            Tomas Palacios    4.388723   4.000
184              Jules Kounde   10.401310  65.000
185               Matte Smets    3.827407  13.000
186             Ricardo Visus    1.777298   0.750
187            German Ignatov    2.898155   0.500
188         Roberto Fernandez    2.086423   3.500
189               Kim Min-jae    5.252803  40.000
190             Ibe Hautekiet    2.300970   3.500
191                    Moises    1.851749   5.000
192             Lukas Ullrich   13.780882   8.000
193            Lucas Calegari    1.594551   3.500
194        Jordan Torunarigha    1.516971   4.000
195             Jack Stephens    4.844135   1.500
196                Jose Gomes    2.044795   1.000
197               Axel Witsel    0.703836   2.000
198            Berat Djimsiti    4.696473   6.000
199          Mutalip Alibekov    0.886178   0.700
200             Sergio Akieme   11.062127   7.000
201                Marc Guehi   42.345163  45.000
202         Tsuyoshi Watanabe    3.305999   9.000
203               Dinis Pinto    3.112740   1.500
204             Alan Matturro    7.843695   7.000
205         Francesco Zampano    3.085064   1.000
206              Robert Gumny    3.257203   1.500
207                Raul Silva    0.249647   0.100
208             Thomas Beelen    1.774619   8.000
209             Juan Berrocal    3.227135   1.500
210           Maksim Nenakhov    1.731978   3.000
211             Diego Coppola   17.554531  10.000
212            Julian Ryerson    9.629955  20.000
213                    Orinho    1.181028   0.600
214          Leopold Querfeld   16.853192  13.000
215            Willy Kambwala    7.079290   4.000
216           Lucas Hernandez    1.606232  25.000
217         Toby Alderweireld    1.477453   2.000
218              Manuel Osifo    1.840170   0.700
219              Adam Marusic    5.262903   3.500
220           Sinaly Diomande    9.539588   5.000
221           Ladislav Krejci    8.489010  12.000
222               Emil Krafth    3.582024   2.000
223          Massadio Haidara    1.790918   1.500
224              Jordan Amavi    1.554800   1.500
225        Jose Maria Gimenez    2.940863  20.000
226               Chico Lamba    3.953406   3.000
227        Myles Lewis-Skelly   29.104683  45.000
228        Alexsandro Ribeiro   10.506611  20.000
229          Domagoj Bradaric    6.038056   4.000

# Модель 5

In [44]:
X_train = X_train[['G+A', 'G+A.1', 'G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'G+A.1', 'G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [50]:
coeffs_df

               coeff
league_GB1  0.629187
Age        -0.589858
90s         0.431591
league_IT1  0.355601
league_L1   0.314257
league_ES1  0.291664
league_FR1  0.258124
G+A         0.207486
Sh/90       0.166010
G+A.1      -0.150654
league_NL1 -0.147237
Ast.1       0.122030
TklW       -0.107120
league_PO1 -0.097210
G-PK        0.041523
league_RU1 -0.029767
Int        -0.004690
CrdY        0.004419

In [51]:
metrics

            MAE       RMSE      MAPE        R2
test   5.550672  11.212241  0.914493  0.313954
train  4.637658   9.532799  0.886727  0.357351

In [52]:
comp_leftovers_train

                               Player  Value_pred   Value
0              Alessandro Marcandalli    4.760061   2.000
1                     Tyrick Mitchell   34.880581  25.000
2                    Valentin Paltsev    3.063554   2.500
3                        Teo Quintero    0.706990   0.600
4                      Kaio Pantaleao    0.738747   1.800
5                       Aitor Paredes    6.324494  22.000
6                    Fredrik Oppegard    1.490828   0.600
7                       Sergei Bozhin    1.019418   0.700
8                  Francisco Petrasso    1.258889   1.500
9                         Dara O'Shea   30.011124  14.000
10                        Pedro Porro   63.069707  38.000
11                      Fikayo Tomori    3.632996  20.000
12                             Marcao    1.403247   2.000
13                       Martin Erlic    4.132886   4.000
14                  Alexandre Penetra    2.812109   9.000
15                         Sacha Boey    4.941499  18.000
16                      Kyriani Sabbe    3.194615   4.500
17                     Djibril Sidibe    2.014404   1.000
18                      Seiya Maikuma    1.102792   4.000
19                      Rick Karsdorp    0.432092   3.000
20                Mohamed Abdelmoneim    2.151562   4.000
21                  Christian Mawissa    6.140965  15.000
22                     Thomas Meunier    2.501331   2.000
23                         Mats Deijl    3.047200   2.000
24        Marcelo dos Santos Ferreira    0.548522   0.100
25                      Neco Williams   40.216427  20.000
26                  Edoardo Goldaniga    3.983805   3.000
27                     Danny da Costa    2.241688   1.500
28                      Sergi Cardona   16.565563  10.000
29                        Jon Pacheco    3.324222   6.000
30                 Viktor Aleksandrov    1.833525   1.200
31                  Rustam Ashurmatov    0.671299   0.600
32                     Aske Adelgaard    1.957279   0.850
33                        Omar Traore    6.935364   4.000
34                    Emmanuel Biumla    7.530692   4.000
35                      Omar Alderete    8.706238   8.000
36                    Oscar de Marcos    1.609492   1.500
37                     Hassane Kamara    5.421420   3.500
38                   Mimeirhel Benita    2.459474   1.000
39                    Valentin Rosier    5.349528   3.000
40                 Abdukodir Khusanov    7.043981  35.000
41                  Nicolas Valentini    5.020146   6.000
42                      Radu Dragusin   14.896906  25.000
43                       Martin Frese    2.341358   2.000
44                  Mikayil Ngor Faye    5.674147   6.000
45                         Leo Greiml    2.470322   2.000
46                     Mitchell Dijks    0.537674   0.600
47                         Juan Foyth    4.769620  15.000
48                         Maks Dziov    2.280820   0.700
49                     Martin Valjent    6.228345   6.000
50                       Matvei Lukin    2.389600   1.200
51                        Emin Bayram    2.719883   3.500
52                       Cesar Montes    1.069990   4.500
53                           Ola Aina   18.898313  22.000
54                        David Alaba    0.749076   6.000
55                 Bas van den Eynden    1.914430   0.700
56             Trent Alexander-Arnold   61.329441  75.000
57                Christopher Mamengi    0.624998   0.250
58                   Valentin Gendrey    7.910129   7.000
59                      Oleg Reabciuk    2.018579   4.000
60                   Enrico Del Prato   15.846102   6.500
61                       Ivan Smolcic    5.091681   1.800
62                        Joao Mendes    2.227823   2.000
63                         Hiroki Ito    1.705879  25.000
64                        Mike Kleijn    1.252775   0.250
65                         Nathan Ake    4.332217  25.000
66                    Antonio Rudiger    3.259547  20.000
67                     Patrick Mainka    6.621075   3.000
68                Dimitris Giannoulis    7.643652   3.000
69                         Ezri Konsa   22.227529  35.000
70                     Marco Palestra    4.742147   3.500
71                      Frans Kratzig    9.192609   3.500
72                          Emil Holm    5.562147   8.000
73             El Chadaille Bitshiabu    7.579896  18.000
74                      Hiroki Sekine    5.075433   1.200
75            Konstantin Nizhegorodov    1.073394   0.300
76                         Ko Itakura    8.418716  12.000
77                       Igor Vujacic    1.335764   3.000
78                         Borna Sosa    3.053003   4.500
79                    Marcus Pedersen    5.260098   3.000
80                     Ramon Hendriks    5.304686   5.000
81                    Florian Lejeune    8.607122   2.500
82                     Gleison Bremer    2.258452  50.000
83                      Marvin Senaya    2.706857   1.800
84                    Benedikt Gimber    4.509442   3.000
85                       Tuur Rommens    5.216647   4.000
86                     Alberto Moreno    2.222204   1.500
87                   Yunis Abdelhamid    0.576655   0.400
88                     Rosen Bozhinov    2.094704   0.400
89                     Koni De Winter   12.395831  22.000
90                           Kialonda    6.839297   3.500
91                   Jonas Fohrenbach    3.389180   1.500
92                         Lewis Dunk    5.983919   6.000
93                      Pierre Cornud    1.468210   0.800
94                     Piero Hincapie   17.018818  50.000
95                  Yarek Gasiorowski    6.120917   7.500
96                          Rob Nizet    1.099836   0.350
97                   Nathan Patterson   10.439245  15.000
98                    James Tarkowski   10.080310   9.000
99                        Maxime Busi    0.864249   1.000
100                         Lucas Hey    1.677293   5.000
101                    Theo Hernandez   21.834395  35.000
102              Alec Van Hoorenbeeck    1.056430   0.800
103                     Erik Schouten    0.351624   0.200
104                 Charlie Cresswell   21.052497  10.000
105                 Marc-Oliver Kempf    4.850493   3.000
106                   Alexandre Pinto    0.761989   0.500
107                    Dani Fernandez    1.368142   0.800
108                     Cesar Tarrega   14.237569  10.000
109                   Mardochee Nzita    1.191898   1.000
110                     Moussa Diarra    4.834906   1.800
111                       Aihen Munoz    2.896042   4.000
112                       Jorge Saenz    3.279314   1.500
113                     Gideon Mensah    3.558956   4.000
114                        Robin Koch    7.326182  18.000
115                        Karol Mets    1.352077   1.300
116                     Ethan Pinnock    7.068641   7.000
117                  Olivier Boscagli    2.929302  20.000
118                    Danilho Doekhi   11.891383  13.000
119                       Sven Botman   10.154404  42.000
120                        Leo Petrot    5.184040   0.900
121                    Giovanni Leoni   10.943268  18.000
122                         Ben White   11.453882  45.000
123                   Maksim Osipenko    4.438578   5.000
124                     Jordan Lefort    3.673556   1.500
125                        Willy Boly    2.190189   1.500
126                      Lucas Africo    0.967392   0.300
127                  Lucas Mincarelli    5.874165   0.900
128                       Hector Fort    9.604281  10.000
129                 Rasmus Kristensen   12.721273  14.000
130                    Tanguy Nianzou    3.710725   1.500
131                       Nuno Mendes   12.232942  70.000
132                      Raul Asencio    7.141749  40.000
133                   Leandro Cabrera    5.052774   1.000
134                       Nathan Zeze    7.476758  15.000
135                  Christian Gunter    4.704220   3.500
136                  Santiago Mourino    7.709364   3.000
137                   Michael Svoboda    3.894985   2.500
138                      Robin Gosens   19.275416   8.000
139                    Vitali Lystsov    0.356938   0.300
140                  Carlos Dominguez    4.023207   3.000
141                     Matteo Gabbia    9.227544  14.000
142                  Pervis Estupinan   19.403157  30.000
143                   Kiryl Pyachenin    1.178002   0.750
144                           Willyan    2.045896   6.000
145                Leo Skiri Østigard    6.238635  10.000
146                      Ilya Gaponov    0.749337   0.600
147                      Nuno Tavares   21.905514  25.000
148                   Aaron Cresswell    2.490740   0.500
149                    Facundo Garces    3.591956   2.000
150                   Rein Van Helden    3.601332   2.500
151                      Felix Bacher    1.860503   2.000
152                   Mathias Olivera    6.916899  20.000
153                    Siebe Horemans    1.667153   3.500
154                     Carlens Arcus    2.573261   1.800
155                    Rayan Senhadji    0.929115   0.700
156               Sven Sostaric Karic    1.613271   1.000
157                   Nicolas Pallois    1.041871   0.400
158                 Dmitri Skopintsev    1.318129   2.500
159                      Miguel Lopes    0.179226   0.050
160                     Michael Keane    5.225469   5.000
161                     David Jurasek    5.076656   5.000
162                 Lukas Klostermann    3.252381   8.000
163                    Matteo Ruggeri    8.821938  16.000
164                           Ulisses    2.821892   1.500
165                       Marius Wolf    5.391585   3.000
166                              Viti    3.659879   2.000
167                      Yael Mouanga    5.663457   0.600
168               Nemanja Andjelkovic    0.700305   0.750
169                             Natan    7.936009   9.000
170                   Sherel Floranus    1.129263   0.850
171                   Luca Marianucci    8.026508   7.500
172                    Jelle Bataille    1.164615   2.500
173                      Georgi Zotov    0.415929   0.050
174                    Gautier Lloris    4.179996   3.000
175                       Nico Elvedi    5.208040   8.000
176                      Brian Olivan    1.870045   1.800
177                        James Hill   16.476287   3.000
178                        Lewis Hall   45.612398  32.000
179                       Lucas Olaza    1.419746   4.000
180                       Inigo Lekue    1.083014   2.000
181           Anselmo Garcia MacNulty    4.504089   1.500
182                 Aridane Hernandez    0.895825   0.300
183                     Nelson Semedo   15.409288   9.000
184                           Carmona    9.035227  12.000
185                   Matthias Ginter    5.961326   7.000
186                     Hasan Kurucay    1.479734   1.300
187                     Joao Ferreira    1.425374   3.000
188             Etienne Youte Kinkoue    9.051925   7.000
189                            Danilo    1.016911   3.500
190                      Dion De Neve    5.440358   0.900
191                       Jhon Lucumi    6.903279  22.000
192                      Robson Bambu    0.829160   3.000
193                   Domingos Duarte    2.561027   0.800
194                    Jonathan Panzo    1.489249   1.200
195                        Javi Lopez    6.239076   7.500
196                     Aurele Amenda    5.083110   7.500
197            Vyacheslav Bardybakhin    1.239088   0.500
198                     Mario Hermoso    1.997128   7.000
199                      Adam Webster    5.021687  11.000
200                       Dembo Sylla    1.801031   0.500
201                     Patrick Erras    2.256594   0.800
202                   Maxime Bernauer    2.112750   2.000
203                Aleksandr Silyanov    3.046345   6.000
204                        Guela Doue   14.181622  18.000
205                  Matthijs de Ligt   22.416427  38.000
206                    Illia Zabarnyi   38.598999  42.000
207                  Maximilian Bauer    2.887079   2.000
208                       Djed Spence   20.094509  20.000
209                       Kyle Walker    3.181190   4.000
210                     Dani Carvajal    0.937799   8.000
211                     Modibo Sagnan    5.249947   3.000
212                      Nayef Aguerd    3.131612  18.000
213                Jan Paul van Hecke   30.418572  32.000
214                  Olivier Aertssen    1.893355   0.750
215             Tolis Konstantopoulos    2.883519   0.800
216                Bruno Martins Indi    0.265486   0.650
217                  Raffael Behounek    1.763763   0.800
218                       Ivan Balliu    1.073998   1.400
219                  Ousmane Diomande    6.115661  45.000
220                       Theo Barbet    0.977449   0.375
221                      Nasser Djiga    8.332633  10.000
222                     Ruben Roosken    1.342841   0.600
223                 Christiaan Ravych    3.151568   4.500
224               Ze Pedro Figueiredo    0.841198   4.000
225                   Yerson Mosquera    8.812575   8.000
226                   Bryan Goncalves    0.802593   0.600
227                     Oliver Braude    3.114339   4.000
228                 Aaron Wan-Bissaka   36.196603  24.000
229                         Finn Stam    1.364377   0.450
230                Frederico Venancio    0.534161   0.600
231                      Srdjan Babic    1.963792   6.000
232                        Luck Zogbe    7.050954   2.500
233                      Loic Mbe Soh    2.486230   2.000
234                        Youri Baas    2.213059  12.000
235                Jeffrey Gouweleeuw    4.791861   1.500
236                  Emmanuel Agbadou   16.756217  20.000
237                       Lucas Digne   10.062833  10.000
238                 Ignacio Rodriguez    1.703040   0.600
239                 Cesar Azpilicueta    0.859798   1.500
240                 Ricardo Rodriguez    1.638477   2.000
241                    Carlos Augusto   11.522691  26.000
242                      Mamadou Sarr   13.952500  20.000
243                    Edmond Tapsoba    7.737191  35.000
244                   Benjamin Pavard    3.456740  25.000
245                    Tommy St. Jago    1.700847   1.000
246                      Rick Meissen    1.011839   0.500
247                        James Bree    8.262427   2.500
248                        Pablo Mari    3.497107   3.500
249                     Noahkai Banks    6.993543   6.000
250                   Filipe Ferreira    0.535042   0.100
251                         Joe Gomez    5.391589  20.000
252                            Patric    1.168608   2.500
253                           Patrick    0.719042   0.900
254                    Daniel Oyegoke    5.109307   0.500
255                   Cristian Romero   11.201949  50.000
256                    Matisse Didden    1.047751   1.000
257                  Eliaquim Mangala    0.194855   0.200
258                    Becir Omeragic    6.057024   4.500
259                      Nehuen Perez    3.234908  13.000
260                       Denis Vavro    6.992502   7.000
261                     Stefan Lainer    1.287644   1.200
262                  Roman Neustadter    0.356713   0.150
263                       Marc Bartra    2.614796   1.000
264                     Jacob Greaves   20.934874  18.000
265                   Alvaro Carreras    5.173005  35.000
266                      Joseph Aidoo    1.527678   1.200
267                    Lorenzo Milani    1.011597   0.225
268                    Idar Shumakhov    2.655356   1.000
269                    Henry Lawrence    2.631267   1.500
270                     Nahuel Molina    5.031189  20.000
271                       Angel Ortiz    5.399136   2.500
272                     Tomas Ribeiro    0.914355   1.000
273                    Daniele Rugani    0.427695   3.000
274                      Matt Doherty    7.176193   2.000
275                   Danila Khotulev    1.631192   0.400
276                       Luke Thomas   10.577310   6.000
277                         Oscar Gil    0.915874   0.700
278                      David Hancko    4.200633  30.000
279                     Nicolo Casale    3.656771   6.000
280                 Frederic Guilbert    3.796187   2.500
281                       Pau Navarro    5.535337   3.000
282                      Sael Kumbedi    6.098591   7.000
283                           Maracas    1.063638   1.000
284                       Conor Coady    5.185600   2.200
285                    Josip Stanisic    4.193693  32.000
286                  Timothy Castagne    7.576928  13.000
287                        Pau Torres   10.321034  32.000
288                  Hristiyan Petrov    0.932482   0.600
289                      Adamo Nagalo    1.029858   6.000
290                      Myenty Abena    0.408237   0.700
291                      Clement Akpa    7.920843   5.000
292                    Jens Mathijsen    1.315078   0.200
293                         Vanderson    9.475795  20.000
294                         Isak Hien    5.706566  30.000
295                 Kingsley Ehizibue    4.200535   2.400
296                        Brian Plat    1.866057   0.700
297                      Falaye Sacko    1.782143   1.500
298                 Souleyman Doumbia    0.676397   1.000
299                Sebastiano Luperto   12.330468   4.000
300                    Ilya Vakhaniya    2.558887   3.000
301                  Rodrigo Pinheiro    2.938978   2.500
302                       Zaid Romero    1.377955   3.000
303                    William Saliba   29.477838  80.000
304                Nico Schlotterbeck   10.446894  40.000
305                   Aritz Elustondo    1.807594   3.000
306                     Sergei Petrov    0.532422   0.400
307                      Haruya Fujii    1.832232   2.000
308                      Eder Militao    3.661342  30.000
309                       Bas Kuipers    1.341281   1.200
310                      Andrei Ratiu   12.681566  12.000
311                   Milos Veljkovic    2.384225   3.000
312                   Cameron Burgess   10.012069   2.000
313                        Adam Smith    3.395911   0.750
314                      Marco Friedl    3.700452  12.000
315                     Conor Bradley   24.349644  30.000
316                 Aleksandar Sedlar    0.850496   0.300
317                     Maxim Leitsch    3.017689   1.500
318                       Nathan Ngoy    1.757715   3.500
319                    Edgardo Farina    2.347642   1.000
320                       Diogo Dalot   28.718325  30.000
321                    Jorne Spileers    2.071325   2.000
322                      Mats Hummels    0.991418   2.000
323                 Zakaria El Ouahdi    7.241905  12.000
324                    Federico Barba    1.429912   0.500
325                   Ewoud Pletinckx    1.776930   1.800
326                        Leif Davis   30.697493  22.000
327                Leftheris Lyratzis    1.188269   0.850
328                    Giorgio Altare    3.001003   1.000
329                      Jan Bednarek   12.687764   9.000
330                        Oumar Sako    1.344491   3.000
331                    Pascal Stenzel    4.233296   2.000
332                     Abel Bretones    7.036585   4.000
333                       Raul Albiol    0.518000   1.000
334                    Almugera Kabar    4.985382   1.000
335                       Hugo Gambor    1.986173   1.000
336                Alessandro Circati    5.597229   8.000
337                  Thijmen Blokzijl    3.027785   2.000
338                     Mujaid Sadick    2.329085   8.000
339              Vyacheslav Karavayev    0.548955   3.500
340                    Rafik Belghali    4.041683   2.500
341                   Stefano Sabelli    2.648646   1.400
342                 Nikola Milenkovic   55.310466  35.000

In [53]:
comp_leftovers_test

                       Player  Value_pred   Value
0                Jon Aramburu    7.632123  15.000
1             Alphonso Davies    9.927970  50.000
2          Riccardo Calafiori   18.151490  35.000
3                  Fali Cande    4.293745   2.500
4              Romain Perraud    7.744173   5.000
5                Harry Clarke    8.129064   4.500
6                  Boyd Reith    0.651621   0.400
7            Zineddine Belaid    1.318612   0.800
8                  Yerry Mina    5.139381   3.000
9                 Aiham Ousou    2.264139   2.500
10            Youssouf Sabaly    1.693360   1.800
11              Daniel Vivian   10.089617  40.000
12     Maximilian Mittelstadt   10.946843  20.000
13                 Alex Munoz    2.143853   1.000
14         Jannik Vestergaard    4.198259   2.000
15                Ali Dembele    6.390478   0.900
16            Aleksei Tatayev    0.963860   0.800
17            Marvin da Graca    0.449085   0.400
18              Stephen Welsh    1.108764   1.000
19           Mahamadou Nagida    5.603714   0.800
20                Jonny Evans    1.490935   1.000
21              Pedro Pereira    9.744908   1.500
22          Milan Majstorovic    2.265994   1.800
23            Rayan Ait-Nouri  106.063301  35.000
24                Tiago Djalo    1.178573   8.000
25            Anthony Rouault    9.051116  10.000
26       Lorenzo De Silvestri    1.015577   0.800
27                Abdul Mumin    5.463122   5.000
28      Przemyslaw Frankowski    3.700660   7.000
29           Eduardo Quaresma    1.401046  18.000
30           Micky van de Ven   15.886945  50.000
31   Konstantinos Koulierakis   19.154148  25.000
32                Anton Gaaei    5.053048   7.000
33               Sergino Dest    1.155977  16.000
34                Abdel Abqar    6.790072   7.500
35                 Bamo Meite    3.177140   4.000
36              Gerard Martin    7.669049  12.000
37                   Iglesias    6.351137   3.500
38             Egor Pogostnov    2.061418   1.800
39             Ricardo Mangas    1.080206   2.500
40         Mike van der Hoorn    1.424410   1.000
41              Shawn Adewoye    1.463038   1.300
42                Jonas Rouhi    4.196060   2.000
43              Alexis Duarte    1.321825   3.000
44           Andrey Langovich    5.010776   3.000
45               Hamza Mendyl    0.940153   1.000
46           Mike Eerdhuijzen    2.353307   2.300
47            Ruben Fernandes    0.438795   0.050
48            Thierry Correia    3.116661   3.000
49              Marco Komenda    2.580112   0.800
50              Jordy Makengo    3.731538   6.000
51           Giorgio Scalvini    7.722124  35.000
52                 Rico Henry    3.663983  15.000
53               Victor Gomez    2.049027   6.000
54          Noussair Mazraoui   12.956610  25.000
55                 Hugo Bueno    2.429545   8.000
56                  Felix Agu    7.166925   8.000
57           Flavius Daniliuc    4.041810   2.700
58      Youssouf Ndayishimiye    5.862420  12.000
59                 Toti Gomes   15.575266  28.000
60                Ian Maatsen   28.437038  28.000
61             Evgeni Morozov    1.420258   3.000
62            Duplexe Tchamba    1.525446   1.000
63                  Wout Faes   18.010177  15.000
64               Carlos Ponck    0.374606   0.600
65                Tim Drexler    5.874936   3.000
66             Javi Rodriguez   15.771344  15.000
67                Lloyd Kelly    5.491331  16.000
68               Ivan Marquez    0.897500   0.600
69            Cristian Castro    3.000786   0.800
70              Igor Yurganov    0.790723   0.500
71               Eduard Sobol    0.951520   0.900
72        Patrick van Aanholt    0.456194   0.500
73             Goncalo Inacio    4.308715  45.000
74               Javi Sanchez    4.665275   1.500
75              Ferland Mendy    1.622163  14.000
76              Boris Popovic    1.108443   1.500
77             Josko Gvardiol   78.312085  75.000
78            Tommaso Augello    8.952254   1.800
79                Ivan Ordets    2.132197   1.000
80              Ryan Alebiosu    2.259319   0.500
81               Rafael Toloi    1.012895   1.400
82              Calvin Bassey   26.511964  25.000
83       Michael Amir Murillo    5.388684  10.000
84              Aaron Meijers    0.145749   0.075
85          Mathias Jorgensen    0.590103   0.500
86            Ibrahima Konate   25.704057  60.000
87              Botond Balogh    8.544313   2.400
88                Amos Pieper    3.565765   3.500
89            Oleksandr Filin    1.378420   1.000
90      Boli Bolingoli-Mbombo    0.549846   0.500
91           Mouctar Diakhaby    3.112893   2.000
92                Ilay Camara    5.717318   4.000
93                 Alex Valle    8.424760   6.000
94            Emanuele Valeri   22.183379   3.000
95               Armando Izzo    3.130852   1.500
96         Vasilios Zagaritis    3.103767   0.700
97              Egor Teslenko    5.066401   2.000
98              Wesley Fofana   11.393141  25.000
99                    Ben Mee    1.463526   0.700
100        Soumaila Coulibaly    5.551232   8.000
101                 Issa Diop    7.428724  14.000
102               Jesus Areso    9.100865  12.000
103           Dayot Upamecano    5.780227  50.000
104            Cedric Zesiger    5.735818   7.000
105              Craig Dawson    2.652272   1.500
106             Alexander Bah    1.015391  10.000
107              David Torres    5.964042   1.500
108                Karol Fila    1.112122   0.600
109       Giangiacomo Magnani    3.054740   1.800
110         Vitaliy Mykolenko   27.548811  28.000
111                Hauke Wahl    3.782373   1.500
112                Glenn Bijl    0.953602   1.500
113              Tiago Esgaio    1.425527   0.900
114            Wilfried Singo    9.530926  25.000
115            Manuel Lazzari    2.341974   3.500
116                      Nino    2.738622  11.000
117             Scott McKenna    4.750298   4.000
118                 Mats Rots    3.132308   1.000
119         Godfried Frimpong    2.686446   2.000
120           Renato Pantalon    0.868743   0.600
121           Moussa Niakhate    3.424591  15.000
122   Francisco Reis Ferreira    0.722401   0.700
123             Mads Roerslev   14.485690   6.000
124             Jordan Zemura    8.117045   4.500
125            Andrea Carboni    7.724429   2.800
126          Andrew Robertson   10.047079  18.000
127                Juan Jesus    1.234920   1.500
128          Jonathan Mutombo    1.451569   0.500
129              Joseph Okumu    3.579518   7.000
130                Marco Sala    2.155691   0.900
131                Diego Rico    3.661345   1.200
132              Finn Jeltsch    7.010506  20.000
133                Max Kilman   20.686283  25.000
134              Thilo Kehrer    5.887914  20.000
135           Brandon Mechele    1.575846   3.500
136         Gabriel Magalhaes   26.720041  75.000
137        Anass Salah-Eddine    3.754925   8.000
138          Javier Manquillo    1.038776   1.000
139       Redouan El Yaakoubi    0.379992   0.550
140                Kenny Lala    3.071293   2.000
141        Nathan Wood-Gordon   10.973312   3.500
142     Aleksandr Soldatenkov    1.173821   4.000
143               Logan Costa   13.619115  18.000
144           Abdoulaye Bamba    0.889248   0.300
145             Hjalmar Ekdal    0.783752   4.500
146           Thierry Lutonda    0.839817   0.300
147                  Angelino   11.573427  20.000
148             Rafik Messali    5.248519   0.800
149            Javi Hernandez    8.024742   2.500
150               Fran Garcia    7.009450  18.000
151       Konstantin Savichev    1.114748   0.900
152        Christian Kabasele    1.955316   0.700
153              David Hrncar    2.439611   1.200
154             Antoine Mendy    6.286043   2.500
155           Castello Lukeba    6.718654  40.000
156            Paulo Oliveira    0.629090   1.000
157                 Yoel Lago    4.777977   1.000
158            Emmanuel Kakou    3.865964   1.000
159               Malang Sarr    3.375784   5.000
160       Keven Schlotterbeck    4.488642   6.000
161            Jose Luis Gayà    2.621749   9.000
162            Wolke Janssens    0.521461   0.400
163           Mohammed Salisu    3.224139  12.000
164               Oumar Solet    8.156469  18.000
165             Marcos Senesi    5.756143  22.000
166              Andy Pelmard    2.449369   2.000
167              Semm Renders    3.324196   1.500
168          Antonee Robinson   49.198336  35.000
169        Brendan Chardonnet    3.258235   6.000
170            Inigo Martinez    3.482154   5.000
171                    Catena    7.640646   3.000
172            Jarell Quansah   10.575561  20.000
173                Joe Scally    9.950370  10.000
174                    Michel    0.957303   1.000
175        Jose Luis Palomino    0.942087   0.700
176           Matija Nastasic    2.220950   0.800
177              Kelvin Amian    3.896686   2.500
178             Marvin Elimbi    1.031605   0.750
179            Marc Cucurella   34.682659  35.000
180          Maksim Shnaptsev    1.603235   0.300
181               Ahmed Touba    1.892845   2.500
182                      Igor    6.676596  20.000
183            Tomas Palacios    4.411021   4.000
184              Jules Kounde   10.253858  65.000
185               Matte Smets    3.825205  13.000
186             Ricardo Visus    1.774904   0.750
187            German Ignatov    2.885864   0.500
188         Roberto Fernandez    2.077760   3.500
189               Kim Min-jae    5.256534  40.000
190             Ibe Hautekiet    2.306684   3.500
191                    Moises    1.815818   5.000
192             Lukas Ullrich   13.702201   8.000
193            Lucas Calegari    1.598778   3.500
194        Jordan Torunarigha    1.506801   4.000
195             Jack Stephens    4.857173   1.500
196                Jose Gomes    2.027014   1.000
197               Axel Witsel    0.704688   2.000
198            Berat Djimsiti    4.659341   6.000
199          Mutalip Alibekov    0.882504   0.700
200             Sergio Akieme   10.839721   7.000
201                Marc Guehi   42.028489  45.000
202         Tsuyoshi Watanabe    3.246145   9.000
203               Dinis Pinto    3.103590   1.500
204             Alan Matturro    7.885428   7.000
205         Francesco Zampano    3.077973   1.000
206              Robert Gumny    3.258507   1.500
207                Raul Silva    0.244515   0.100
208             Thomas Beelen    1.766324   8.000
209             Juan Berrocal    3.214029   1.500
210           Maksim Nenakhov    1.732432   3.000
211             Diego Coppola   17.667138  10.000
212            Julian Ryerson    9.505882  20.000
213                    Orinho    1.175008   0.600
214          Leopold Querfeld   16.703187  13.000
215            Willy Kambwala    7.092705   4.000
216           Lucas Hernandez    1.607074  25.000
217         Toby Alderweireld    1.437817   2.000
218              Manuel Osifo    1.850743   0.700
219              Adam Marusic    5.261014   3.500
220           Sinaly Diomande    9.378049   5.000
221           Ladislav Krejci    8.439940  12.000
222               Emil Krafth    3.585309   2.000
223          Massadio Haidara    1.784263   1.500
224              Jordan Amavi    1.551697   1.500
225        Jose Maria Gimenez    2.920277  20.000
226               Chico Lamba    3.915419   3.000
227        Myles Lewis-Skelly   29.250034  45.000
228        Alexsandro Ribeiro   10.396449  20.000
229          Domagoj Bradaric    6.087537   4.000

# Модель 6

In [33]:
X_train = X_train[['G+A.1', 'G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A.1', 'G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [39]:
coeffs_df

               coeff
league_GB1  0.637359
Age        -0.584323
90s         0.472828
league_IT1  0.366363
league_L1   0.323853
league_ES1  0.297940
league_FR1  0.266634
Ast.1       0.236942
Sh/90       0.171286
G-PK        0.161150
G+A.1      -0.156113
league_NL1 -0.135592
league_PO1 -0.093038
TklW       -0.081167
league_RU1 -0.023454
Int        -0.017298
CrdY        0.000324

In [40]:
metrics

            MAE       RMSE      MAPE        R2
test   5.447071  10.546331  0.900855  0.393024
train  4.585201   9.367524  0.893122  0.379442

In [41]:
comp_leftovers_train

                               Player  Value_pred   Value
0              Alessandro Marcandalli    4.580892   2.000
1                     Tyrick Mitchell   29.126872  25.000
2                    Valentin Paltsev    3.353092   2.500
3                        Teo Quintero    0.699054   0.600
4                      Kaio Pantaleao    0.732866   1.800
5                       Aitor Paredes    6.471008  22.000
6                    Fredrik Oppegard    1.460603   0.600
7                       Sergei Bozhin    1.054437   0.700
8                  Francisco Petrasso    1.189564   1.500
9                         Dara O'Shea   29.122953  14.000
10                        Pedro Porro   49.727508  38.000
11                      Fikayo Tomori    3.677063  20.000
12                             Marcao    1.332882   2.000
13                       Martin Erlic    4.023394   4.000
14                  Alexandre Penetra    2.959576   9.000
15                         Sacha Boey    5.872110  18.000
16                      Kyriani Sabbe    3.354809   4.500
17                     Djibril Sidibe    1.905680   1.000
18                      Seiya Maikuma    1.196837   4.000
19                      Rick Karsdorp    0.503229   3.000
20                Mohamed Abdelmoneim    2.113724   4.000
21                  Christian Mawissa    6.306973  15.000
22                     Thomas Meunier    2.756280   2.000
23                         Mats Deijl    2.671269   2.000
24        Marcelo dos Santos Ferreira    0.607591   0.100
25                      Neco Williams   38.443358  20.000
26                  Edoardo Goldaniga    4.262783   3.000
27                     Danny da Costa    2.256668   1.500
28                      Sergi Cardona   11.529810  10.000
29                        Jon Pacheco    3.217414   6.000
30                 Viktor Aleksandrov    1.894732   1.200
31                  Rustam Ashurmatov    0.651056   0.600
32                     Aske Adelgaard    1.939139   0.850
33                        Omar Traore    7.113555   4.000
34                    Emmanuel Biumla    7.584088   4.000
35                      Omar Alderete    9.589140   8.000
36                    Oscar de Marcos    1.478078   1.500
37                     Hassane Kamara    4.769921   3.500
38                   Mimeirhel Benita    2.499544   1.000
39                    Valentin Rosier    5.275025   3.000
40                 Abdukodir Khusanov    7.039763  35.000
41                  Nicolas Valentini    5.107077   6.000
42                      Radu Dragusin   14.719409  25.000
43                       Martin Frese    2.297616   2.000
44                  Mikayil Ngor Faye    5.557290   6.000
45                         Leo Greiml    2.745669   2.000
46                     Mitchell Dijks    0.516141   0.600
47                         Juan Foyth    4.859581  15.000
48                         Maks Dziov    2.382484   0.700
49                     Martin Valjent    6.869852   6.000
50                       Matvei Lukin    2.306911   1.200
51                        Emin Bayram    2.649473   3.500
52                       Cesar Montes    1.098000   4.500
53                           Ola Aina   20.179272  22.000
54                        David Alaba    0.704874   6.000
55                 Bas van den Eynden    1.822203   0.700
56             Trent Alexander-Arnold   50.072740  75.000
57                Christopher Mamengi    0.591923   0.250
58                   Valentin Gendrey    7.972849   7.000
59                      Oleg Reabciuk    1.837508   4.000
60                   Enrico Del Prato   17.607662   6.500
61                       Ivan Smolcic    5.000467   1.800
62                        Joao Mendes    2.454269   2.000
63                         Hiroki Ito    1.594916  25.000
64                        Mike Kleijn    1.673978   0.250
65                         Nathan Ake    4.248880  25.000
66                    Antonio Rudiger    3.487983  20.000
67                     Patrick Mainka    6.827160   3.000
68                Dimitris Giannoulis    6.496261   3.000
69                         Ezri Konsa   24.603812  35.000
70                     Marco Palestra    4.485372   3.500
71                      Frans Kratzig    9.143111   3.500
72                          Emil Holm    5.738043   8.000
73             El Chadaille Bitshiabu    7.642982  18.000
74                      Hiroki Sekine    4.987121   1.200
75            Konstantin Nizhegorodov    1.010142   0.300
76                         Ko Itakura    9.471203  12.000
77                       Igor Vujacic    1.407496   3.000
78                         Borna Sosa    3.106966   4.500
79                    Marcus Pedersen    5.291486   3.000
80                     Ramon Hendriks    5.283485   5.000
81                    Florian Lejeune    7.855985   2.500
82                     Gleison Bremer    2.207714  50.000
83                      Marvin Senaya    2.546649   1.800
84                    Benedikt Gimber    5.087922   3.000
85                       Tuur Rommens    4.948674   4.000
86                     Alberto Moreno    2.324685   1.500
87                   Yunis Abdelhamid    0.578196   0.400
88                     Rosen Bozhinov    1.904816   0.400
89                     Koni De Winter   13.120877  22.000
90                           Kialonda    6.732678   3.500
91                   Jonas Fohrenbach    3.455908   1.500
92                         Lewis Dunk    6.279184   6.000
93                      Pierre Cornud    1.423395   0.800
94                     Piero Hincapie   16.880489  50.000
95                  Yarek Gasiorowski    5.940360   7.500
96                          Rob Nizet    1.094133   0.350
97                   Nathan Patterson   12.831732  15.000
98                    James Tarkowski   10.652369   9.000
99                        Maxime Busi    0.871236   1.000
100                         Lucas Hey    1.591907   5.000
101                    Theo Hernandez   20.805545  35.000
102              Alec Van Hoorenbeeck    1.082870   0.800
103                     Erik Schouten    0.368889   0.200
104                 Charlie Cresswell   21.516128  10.000
105                 Marc-Oliver Kempf    5.263027   3.000
106                   Alexandre Pinto    0.775477   0.500
107                    Dani Fernandez    1.307316   0.800
108                     Cesar Tarrega   16.178287  10.000
109                   Mardochee Nzita    1.167922   1.000
110                     Moussa Diarra    4.987429   1.800
111                       Aihen Munoz    2.860265   4.000
112                       Jorge Saenz    3.394336   1.500
113                     Gideon Mensah    3.672535   4.000
114                        Robin Koch    7.920654  18.000
115                        Karol Mets    1.342080   1.300
116                     Ethan Pinnock    7.418316   7.000
117                  Olivier Boscagli    2.278250  20.000
118                    Danilho Doekhi   12.255716  13.000
119                       Sven Botman    9.872901  42.000
120                        Leo Petrot    4.714781   0.900
121                    Giovanni Leoni   10.774177  18.000
122                         Ben White   11.417378  45.000
123                   Maksim Osipenko    2.591021   5.000
124                     Jordan Lefort    3.834005   1.500
125                        Willy Boly    2.086960   1.500
126                      Lucas Africo    0.999391   0.300
127                  Lucas Mincarelli    5.775148   0.900
128                       Hector Fort    9.206811  10.000
129                 Rasmus Kristensen   12.239692  14.000
130                    Tanguy Nianzou    3.520115   1.500
131                       Nuno Mendes   11.464148  70.000
132                      Raul Asencio    6.956437  40.000
133                   Leandro Cabrera    4.909317   1.000
134                       Nathan Zeze    7.624868  15.000
135                  Christian Gunter    4.704121   3.500
136                  Santiago Mourino    7.672760   3.000
137                   Michael Svoboda    3.949845   2.500
138                      Robin Gosens   16.463725   8.000
139                    Vitali Lystsov    0.340847   0.300
140                  Carlos Dominguez    3.987507   3.000
141                     Matteo Gabbia    9.825943  14.000
142                  Pervis Estupinan   20.468150  30.000
143                   Kiryl Pyachenin    1.209808   0.750
144                           Willyan    1.935273   6.000
145                Leo Skiri Østigard    6.658172  10.000
146                      Ilya Gaponov    0.723525   0.600
147                      Nuno Tavares   17.364253  25.000
148                   Aaron Cresswell    2.468878   0.500
149                    Facundo Garces    3.445408   2.000
150                   Rein Van Helden    3.599885   2.500
151                      Felix Bacher    1.943828   2.000
152                   Mathias Olivera    6.855799  20.000
153                    Siebe Horemans    1.482001   3.500
154                     Carlens Arcus    2.637229   1.800
155                    Rayan Senhadji    0.965581   0.700
156               Sven Sostaric Karic    1.655521   1.000
157                   Nicolas Pallois    1.001657   0.400
158                 Dmitri Skopintsev    1.350404   2.500
159                      Miguel Lopes    0.179427   0.050
160                     Michael Keane    5.247617   5.000
161                     David Jurasek    5.441977   5.000
162                 Lukas Klostermann    3.347812   8.000
163                    Matteo Ruggeri    8.118646  16.000
164                           Ulisses    3.039444   1.500
165                       Marius Wolf    4.902816   3.000
166                              Viti    3.614893   2.000
167                      Yael Mouanga    5.505138   0.600
168               Nemanja Andjelkovic    0.663247   0.750
169                             Natan    7.899621   9.000
170                   Sherel Floranus    1.160503   0.850
171                   Luca Marianucci    7.973913   7.500
172                    Jelle Bataille    1.207838   2.500
173                      Georgi Zotov    0.504896   0.050
174                    Gautier Lloris    4.446291   3.000
175                       Nico Elvedi    5.293846   8.000
176                      Brian Olivan    1.885146   1.800
177                        James Hill   18.953903   3.000
178                        Lewis Hall   40.126342  32.000
179                       Lucas Olaza    1.420581   4.000
180                       Inigo Lekue    1.068473   2.000
181           Anselmo Garcia MacNulty    4.939798   1.500
182                 Aridane Hernandez    0.904456   0.300
183                     Nelson Semedo   13.241100   9.000
184                           Carmona   10.037908  12.000
185                   Matthias Ginter    6.205079   7.000
186                     Hasan Kurucay    1.470097   1.300
187                     Joao Ferreira    1.409360   3.000
188             Etienne Youte Kinkoue    9.359145   7.000
189                            Danilo    1.091237   3.500
190                      Dion De Neve    5.053896   0.900
191                       Jhon Lucumi    7.059637  22.000
192                      Robson Bambu    0.806408   3.000
193                   Domingos Duarte    2.642137   0.800
194                    Jonathan Panzo    1.474499   1.200
195                        Javi Lopez    6.530368   7.500
196                     Aurele Amenda    4.799482   7.500
197            Vyacheslav Bardybakhin    1.167544   0.500
198                     Mario Hermoso    1.924751   7.000
199                      Adam Webster    4.907554  11.000
200                       Dembo Sylla    1.717493   0.500
201                     Patrick Erras    2.237931   0.800
202                   Maxime Bernauer    2.064905   2.000
203                Aleksandr Silyanov    3.105902   6.000
204                        Guela Doue   14.012682  18.000
205                  Matthijs de Ligt   23.750913  38.000
206                    Illia Zabarnyi   40.019269  42.000
207                  Maximilian Bauer    2.821624   2.000
208                       Djed Spence   19.710571  20.000
209                       Kyle Walker    3.325257   4.000
210                     Dani Carvajal    0.910642   8.000
211                     Modibo Sagnan    5.652662   3.000
212                      Nayef Aguerd    3.309724  18.000
213                Jan Paul van Hecke   31.510165  32.000
214                  Olivier Aertssen    1.932939   0.750
215             Tolis Konstantopoulos    3.100675   0.800
216                Bruno Martins Indi    0.260770   0.650
217                  Raffael Behounek    1.805339   0.800
218                       Ivan Balliu    1.078377   1.400
219                  Ousmane Diomande    6.473863  45.000
220                       Theo Barbet    0.965125   0.375
221                      Nasser Djiga    7.720734  10.000
222                     Ruben Roosken    1.358503   0.600
223                 Christiaan Ravych    3.432610   4.500
224               Ze Pedro Figueiredo    0.846735   4.000
225                   Yerson Mosquera    8.398158   8.000
226                   Bryan Goncalves    0.789910   0.600
227                     Oliver Braude    3.210499   4.000
228                 Aaron Wan-Bissaka   28.980328  24.000
229                         Finn Stam    1.404818   0.450
230                Frederico Venancio    0.541776   0.600
231                      Srdjan Babic    2.004113   6.000
232                        Luck Zogbe    6.988976   2.500
233                      Loic Mbe Soh    2.587585   2.000
234                        Youri Baas    2.268812  12.000
235                Jeffrey Gouweleeuw    4.058524   1.500
236                  Emmanuel Agbadou   18.720853  20.000
237                       Lucas Digne    8.815934  10.000
238                 Ignacio Rodriguez    1.659116   0.600
239                 Cesar Azpilicueta    0.864235   1.500
240                 Ricardo Rodriguez    1.648926   2.000
241                    Carlos Augusto   11.447999  26.000
242                      Mamadou Sarr   13.924675  20.000
243                    Edmond Tapsoba    8.369862  35.000
244                   Benjamin Pavard    3.474321  25.000
245                    Tommy St. Jago    1.956838   1.000
246                      Rick Meissen    0.986187   0.500
247                        James Bree    8.329462   2.500
248                        Pablo Mari    3.702852   3.500
249                     Noahkai Banks    6.604364   6.000
250                   Filipe Ferreira    0.558631   0.100
251                         Joe Gomez    5.257670  20.000
252                            Patric    1.147792   2.500
253                           Patrick    0.702305   0.900
254                    Daniel Oyegoke    4.849515   0.500
255                   Cristian Romero   11.826778  50.000
256                    Matisse Didden    1.014102   1.000
257                  Eliaquim Mangala    0.184490   0.200
258                    Becir Omeragic    6.272894   4.500
259                      Nehuen Perez    3.001950  13.000
260                       Denis Vavro    7.453147   7.000
261                     Stefan Lainer    1.282042   1.200
262                  Roman Neustadter    0.356120   0.150
263                       Marc Bartra    2.614690   1.000
264                     Jacob Greaves   22.197202  18.000
265                   Alvaro Carreras    5.297395  35.000
266                      Joseph Aidoo    1.468968   1.200
267                    Lorenzo Milani    0.973277   0.225
268                    Idar Shumakhov    2.668375   1.000
269                    Henry Lawrence    2.653792   1.500
270                     Nahuel Molina    4.721410  20.000
271                       Angel Ortiz    6.531517   2.500
272                     Tomas Ribeiro    0.906888   1.000
273                    Daniele Rugani    0.420389   3.000
274                      Matt Doherty    7.247461   2.000
275                   Danila Khotulev    1.702769   0.400
276                       Luke Thomas   10.693022   6.000
277                         Oscar Gil    0.915974   0.700
278                      David Hancko    4.487079  30.000
279                     Nicolo Casale    3.655298   6.000
280                 Frederic Guilbert    3.924434   2.500
281                       Pau Navarro    5.473758   3.000
282                      Sael Kumbedi    6.064505   7.000
283                           Maracas    1.062909   1.000
284                       Conor Coady    5.321111   2.200
285                    Josip Stanisic    4.481555  32.000
286                  Timothy Castagne    7.694016  13.000
287                        Pau Torres   10.869594  32.000
288                  Hristiyan Petrov    0.907038   0.600
289                      Adamo Nagalo    0.978406   6.000
290                      Myenty Abena    0.391392   0.700
291                      Clement Akpa    8.017962   5.000
292                    Jens Mathijsen    1.242488   0.200
293                         Vanderson    8.963465  20.000
294                         Isak Hien    6.105526  30.000
295                 Kingsley Ehizibue    4.430238   2.400
296                        Brian Plat    1.954751   0.700
297                      Falaye Sacko    1.754764   1.500
298                 Souleyman Doumbia    0.629095   1.000
299                Sebastiano Luperto   11.243349   4.000
300                    Ilya Vakhaniya    2.521083   3.000
301                  Rodrigo Pinheiro    2.802473   2.500
302                       Zaid Romero    1.304801   3.000
303                    William Saliba   33.526971  80.000
304                Nico Schlotterbeck    9.185245  40.000
305                   Aritz Elustondo    1.826585   3.000
306                     Sergei Petrov    0.527194   0.400
307                      Haruya Fujii    1.832086   2.000
308                      Eder Militao    3.786798  30.000
309                       Bas Kuipers    1.267857   1.200
310                      Andrei Ratiu   12.031005  12.000
311                   Milos Veljkovic    2.407544   3.000
312                   Cameron Burgess    9.788668   2.000
313                        Adam Smith    3.466908   0.750
314                      Marco Friedl    3.981792  12.000
315                     Conor Bradley   26.953077  30.000
316                 Aleksandar Sedlar    0.825368   0.300
317                     Maxim Leitsch    2.944143   1.500
318                       Nathan Ngoy    1.654949   3.500
319                    Edgardo Farina    2.343164   1.000
320                       Diogo Dalot   26.448736  30.000
321                    Jorne Spileers    1.921301   2.000
322                      Mats Hummels    0.995059   2.000
323                 Zakaria El Ouahdi    7.485450  12.000
324                    Federico Barba    1.384686   0.500
325                   Ewoud Pletinckx    1.782277   1.800
326                        Leif Davis   29.865683  22.000
327                Leftheris Lyratzis    1.344742   0.850
328                    Giorgio Altare    2.940872   1.000
329                      Jan Bednarek   13.217209   9.000
330                        Oumar Sako    1.390178   3.000
331                    Pascal Stenzel    4.185246   2.000
332                     Abel Bretones    7.670715   4.000
333                       Raul Albiol    0.519123   1.000
334                    Almugera Kabar    4.658670   1.000
335                       Hugo Gambor    1.961492   1.000
336                Alessandro Circati    5.395616   8.000
337                  Thijmen Blokzijl    3.181944   2.000
338                     Mujaid Sadick    2.498685   8.000
339              Vyacheslav Karavayev    0.545180   3.500
340                    Rafik Belghali    4.090305   2.500
341                   Stefano Sabelli    2.614587   1.400
342                 Nikola Milenkovic   55.320019  35.000

In [42]:
comp_leftovers_test

                       Player  Value_pred   Value
0                Jon Aramburu    8.343553  15.000
1             Alphonso Davies    9.824185  50.000
2          Riccardo Calafiori   18.613235  35.000
3                  Fali Cande    4.322374   2.500
4              Romain Perraud    7.395978   5.000
5                Harry Clarke    7.697380   4.500
6                  Boyd Reith    0.662487   0.400
7            Zineddine Belaid    1.261718   0.800
8                  Yerry Mina    5.694794   3.000
9                 Aiham Ousou    2.266363   2.500
10            Youssouf Sabaly    1.730572   1.800
11              Daniel Vivian   10.949600  40.000
12     Maximilian Mittelstadt    8.237046  20.000
13                 Alex Munoz    2.254088   1.000
14         Jannik Vestergaard    4.214897   2.000
15                Ali Dembele    6.142786   0.900
16            Aleksei Tatayev    0.929750   0.800
17            Marvin da Graca    0.452082   0.400
18              Stephen Welsh    1.040139   1.000
19           Mahamadou Nagida    5.349311   0.800
20                Jonny Evans    1.448398   1.000
21              Pedro Pereira    8.862159   1.500
22          Milan Majstorovic    2.253574   1.800
23            Rayan Ait-Nouri   77.719776  35.000
24                Tiago Djalo    1.140730   8.000
25            Anthony Rouault    9.597774  10.000
26       Lorenzo De Silvestri    1.030884   0.800
27                Abdul Mumin    5.464850   5.000
28      Przemyslaw Frankowski    2.944432   7.000
29           Eduardo Quaresma    1.431438  18.000
30           Micky van de Ven   16.073669  50.000
31   Konstantinos Koulierakis   18.061632  25.000
32                Anton Gaaei    4.545996   7.000
33               Sergino Dest    1.419725  16.000
34                Abdel Abqar    6.674580   7.500
35                 Bamo Meite    3.019869   4.000
36              Gerard Martin    7.768528  12.000
37                   Iglesias    6.688953   3.500
38             Egor Pogostnov    1.982543   1.800
39             Ricardo Mangas    1.052679   2.500
40         Mike van der Hoorn    1.388936   1.000
41              Shawn Adewoye    1.516421   1.300
42                Jonas Rouhi    3.943234   2.000
43              Alexis Duarte    1.307798   3.000
44           Andrey Langovich    4.782682   3.000
45               Hamza Mendyl    0.995737   1.000
46           Mike Eerdhuijzen    2.507123   2.300
47            Ruben Fernandes    0.441283   0.050
48            Thierry Correia    3.118027   3.000
49              Marco Komenda    2.643702   0.800
50              Jordy Makengo    3.642704   6.000
51           Giorgio Scalvini    7.419117  35.000
52                 Rico Henry    3.444144  15.000
53               Victor Gomez    1.947079   6.000
54          Noussair Mazraoui   14.418811  25.000
55                 Hugo Bueno    2.460445   8.000
56                  Felix Agu    7.515648   8.000
57           Flavius Daniliuc    4.117246   2.700
58      Youssouf Ndayishimiye    6.189154  12.000
59                 Toti Gomes   16.195497  28.000
60                Ian Maatsen   29.041953  28.000
61             Evgeni Morozov    1.377688   3.000
62            Duplexe Tchamba    1.494463   1.000
63                  Wout Faes   20.000351  15.000
64               Carlos Ponck    0.358522   0.600
65                Tim Drexler    5.658958   3.000
66             Javi Rodriguez   15.285366  15.000
67                Lloyd Kelly    5.587628  16.000
68               Ivan Marquez    0.948981   0.600
69            Cristian Castro    3.005697   0.800
70              Igor Yurganov    0.800722   0.500
71               Eduard Sobol    0.891782   0.900
72        Patrick van Aanholt    0.482932   0.500
73             Goncalo Inacio    4.083239  45.000
74               Javi Sanchez    4.845049   1.500
75              Ferland Mendy    1.636973  14.000
76              Boris Popovic    1.075773   1.500
77             Josko Gvardiol   91.502380  75.000
78            Tommaso Augello    6.348711   1.800
79                Ivan Ordets    2.145039   1.000
80              Ryan Alebiosu    2.596633   0.500
81               Rafael Toloi    0.990193   1.400
82              Calvin Bassey   29.995332  25.000
83       Michael Amir Murillo    4.999115  10.000
84              Aaron Meijers    0.145723   0.075
85          Mathias Jorgensen    0.566896   0.500
86            Ibrahima Konate   24.992975  60.000
87              Botond Balogh    8.370163   2.400
88                Amos Pieper    3.638340   3.500
89            Oleksandr Filin    1.509901   1.000
90      Boli Bolingoli-Mbombo    0.524197   0.500
91           Mouctar Diakhaby    3.036579   2.000
92                Ilay Camara    5.383426   4.000
93                 Alex Valle    8.442211   6.000
94            Emanuele Valeri   15.056471   3.000
95               Armando Izzo    3.084863   1.500
96         Vasilios Zagaritis    2.928787   0.700
97              Egor Teslenko    4.908239   2.000
98              Wesley Fofana   11.223039  25.000
99                    Ben Mee    1.385385   0.700
100        Soumaila Coulibaly    5.300634   8.000
101                 Issa Diop    7.523389  14.000
102               Jesus Areso    8.470275  12.000
103           Dayot Upamecano    6.052922  50.000
104            Cedric Zesiger    5.386430   7.000
105              Craig Dawson    2.622331   1.500
106             Alexander Bah    1.035787  10.000
107              David Torres    5.885712   1.500
108                Karol Fila    1.049746   0.600
109       Giangiacomo Magnani    3.103356   1.800
110         Vitaliy Mykolenko   26.995596  28.000
111                Hauke Wahl    4.252407   1.500
112                Glenn Bijl    1.002152   1.500
113              Tiago Esgaio    1.465896   0.900
114            Wilfried Singo    9.033079  25.000
115            Manuel Lazzari    2.351545   3.500
116                      Nino    2.803925  11.000
117             Scott McKenna    5.045850   4.000
118                 Mats Rots    3.258771   1.000
119         Godfried Frimpong    2.331213   2.000
120           Renato Pantalon    0.867797   0.600
121           Moussa Niakhate    3.764493  15.000
122   Francisco Reis Ferreira    0.733880   0.700
123             Mads Roerslev   14.274523   6.000
124             Jordan Zemura    8.023430   4.500
125            Andrea Carboni    7.864522   2.800
126          Andrew Robertson   10.302528  18.000
127                Juan Jesus    1.259127   1.500
128          Jonathan Mutombo    1.436972   0.500
129              Joseph Okumu    3.678914   7.000
130                Marco Sala    2.068234   0.900
131                Diego Rico    3.435566   1.200
132              Finn Jeltsch    6.854792  20.000
133                Max Kilman   21.512563  25.000
134              Thilo Kehrer    6.432436  20.000
135           Brandon Mechele    1.622020   3.500
136         Gabriel Magalhaes   27.339288  75.000
137        Anass Salah-Eddine    3.707001   8.000
138          Javier Manquillo    0.997126   1.000
139       Redouan El Yaakoubi    0.366095   0.550
140                Kenny Lala    2.194126   2.000
141        Nathan Wood-Gordon   10.668545   3.500
142     Aleksandr Soldatenkov    1.220149   4.000
143               Logan Costa   13.907965  18.000
144           Abdoulaye Bamba    0.910833   0.300
145             Hjalmar Ekdal    0.794680   4.500
146           Thierry Lutonda    0.824443   0.300
147                  Angelino   12.310744  20.000
148             Rafik Messali    6.014777   0.800
149            Javi Hernandez    8.042914   2.500
150               Fran Garcia    6.794477  18.000
151       Konstantin Savichev    1.004592   0.900
152        Christian Kabasele    2.008010   0.700
153              David Hrncar    2.346682   1.200
154             Antoine Mendy    6.337248   2.500
155           Castello Lukeba    6.876243  40.000
156            Paulo Oliveira    0.639934   1.000
157                 Yoel Lago    5.029262   1.000
158            Emmanuel Kakou    3.755684   1.000
159               Malang Sarr    3.403852   5.000
160       Keven Schlotterbeck    4.560673   6.000
161            Jose Luis Gayà    2.686184   9.000
162            Wolke Janssens    0.510520   0.400
163           Mohammed Salisu    3.241663  12.000
164               Oumar Solet    7.974663  18.000
165             Marcos Senesi    5.774026  22.000
166              Andy Pelmard    2.324697   2.000
167              Semm Renders    3.486181   1.500
168          Antonee Robinson   27.522689  35.000
169        Brendan Chardonnet    3.586603   6.000
170            Inigo Martinez    2.891074   5.000
171                    Catena    6.862475   3.000
172            Jarell Quansah   10.113909  20.000
173                Joe Scally   10.920757  10.000
174                    Michel    0.885006   1.000
175        Jose Luis Palomino    0.953490   0.700
176           Matija Nastasic    2.304839   0.800
177              Kelvin Amian    4.283899   2.500
178             Marvin Elimbi    0.964088   0.750
179            Marc Cucurella   37.963138  35.000
180          Maksim Shnaptsev    2.118624   0.300
181               Ahmed Touba    1.946348   2.500
182                      Igor    6.525394  20.000
183            Tomas Palacios    4.202339   4.000
184              Jules Kounde    9.587614  65.000
185               Matte Smets    3.879118  13.000
186             Ricardo Visus    1.841854   0.750
187            German Ignatov    2.771933   0.500
188         Roberto Fernandez    2.152483   3.500
189               Kim Min-jae    5.572931  40.000
190             Ibe Hautekiet    2.368989   3.500
191                    Moises    1.764589   5.000
192             Lukas Ullrich   12.862386   8.000
193            Lucas Calegari    1.577132   3.500
194        Jordan Torunarigha    1.442392   4.000
195             Jack Stephens    5.023746   1.500
196                Jose Gomes    2.070529   1.000
197               Axel Witsel    0.728412   2.000
198            Berat Djimsiti    4.567916   6.000
199          Mutalip Alibekov    0.888726   0.700
200             Sergio Akieme   10.001296   7.000
201                Marc Guehi   41.195279  45.000
202         Tsuyoshi Watanabe    3.037885   9.000
203               Dinis Pinto    3.182999   1.500
204             Alan Matturro    7.664086   7.000
205         Francesco Zampano    3.046873   1.000
206              Robert Gumny    3.156901   1.500
207                Raul Silva    0.234268   0.100
208             Thomas Beelen    1.760008   8.000
209             Juan Berrocal    3.100071   1.500
210           Maksim Nenakhov    1.864210   3.000
211             Diego Coppola   19.161515  10.000
212            Julian Ryerson    8.796924  20.000
213                    Orinho    1.238606   0.600
214          Leopold Querfeld   15.879105  13.000
215            Willy Kambwala    6.980653   4.000
216           Lucas Hernandez    1.618325  25.000
217         Toby Alderweireld    1.330587   2.000
218              Manuel Osifo    1.855176   0.700
219              Adam Marusic    5.854364   3.500
220           Sinaly Diomande    8.858555   5.000
221           Ladislav Krejci    8.826035  12.000
222               Emil Krafth    3.408073   2.000
223          Massadio Haidara    1.843406   1.500
224              Jordan Amavi    1.570892   1.500
225        Jose Maria Gimenez    2.874937  20.000
226               Chico Lamba    3.658149   3.000
227        Myles Lewis-Skelly   29.367915  45.000
228        Alexsandro Ribeiro   10.430224  20.000
229          Domagoj Bradaric    6.540353   4.000

# Модель 7

In [21]:
X_train = X_train[['G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'G/Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'G/Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [27]:
coeffs_df

               coeff
league_GB1  0.641083
Age        -0.584654
90s         0.498375
league_IT1  0.369875
league_L1   0.323487
league_ES1  0.299119
league_FR1  0.268603
Sh/90       0.153379
league_NL1 -0.135465
Ast.1       0.123801
league_PO1 -0.091362
G-PK        0.089788
TklW       -0.079379
league_RU1 -0.024233
Int        -0.018064
G/Sh       -0.003794
CrdY        0.002388

In [28]:
metrics

            MAE       RMSE      MAPE        R2
test   5.372967  10.441416  0.917254  0.405040
train  4.588574   9.361336  0.897543  0.380261

In [29]:
comp_leftovers_train

                               Player  Value_pred   Value
0              Alessandro Marcandalli    4.432573   2.000
1                     Tyrick Mitchell   31.069978  25.000
2                    Valentin Paltsev    3.358897   2.500
3                        Teo Quintero    0.774306   0.600
4                      Kaio Pantaleao    0.751695   1.800
5                       Aitor Paredes    6.496157  22.000
6                    Fredrik Oppegard    1.366992   0.600
7                       Sergei Bozhin    1.043633   0.700
8                  Francisco Petrasso    1.418022   1.500
9                         Dara O'Shea   30.554910  14.000
10                        Pedro Porro   48.008256  38.000
11                      Fikayo Tomori    3.768551  20.000
12                             Marcao    1.318909   2.000
13                       Martin Erlic    3.658910   4.000
14                  Alexandre Penetra    3.017187   9.000
15                         Sacha Boey    5.698055  18.000
16                      Kyriani Sabbe    3.162185   4.500
17                     Djibril Sidibe    1.967516   1.000
18                      Seiya Maikuma    1.179061   4.000
19                      Rick Karsdorp    0.497879   3.000
20                Mohamed Abdelmoneim    2.111921   4.000
21                  Christian Mawissa    6.425168  15.000
22                     Thomas Meunier    2.650164   2.000
23                         Mats Deijl    2.793334   2.000
24        Marcelo dos Santos Ferreira    0.622545   0.100
25                      Neco Williams   38.203126  20.000
26                  Edoardo Goldaniga    4.374276   3.000
27                     Danny da Costa    2.291762   1.500
28                      Sergi Cardona   11.750023  10.000
29                        Jon Pacheco    3.190584   6.000
30                 Viktor Aleksandrov    1.899957   1.200
31                  Rustam Ashurmatov    0.624014   0.600
32                     Aske Adelgaard    1.922086   0.850
33                        Omar Traore    7.288549   4.000
34                    Emmanuel Biumla    7.773641   4.000
35                      Omar Alderete    9.416929   8.000
36                    Oscar de Marcos    1.479208   1.500
37                     Hassane Kamara    4.758916   3.500
38                   Mimeirhel Benita    2.522232   1.000
39                    Valentin Rosier    5.310163   3.000
40                 Abdukodir Khusanov    7.021965  35.000
41                  Nicolas Valentini    5.023095   6.000
42                      Radu Dragusin   14.674717  25.000
43                       Martin Frese    2.243056   2.000
44                  Mikayil Ngor Faye    5.314022   6.000
45                         Leo Greiml    2.694461   2.000
46                     Mitchell Dijks    0.526823   0.600
47                         Juan Foyth    4.782447  15.000
48                         Maks Dziov    2.381611   0.700
49                     Martin Valjent    6.632672   6.000
50                       Matvei Lukin    2.856892   1.200
51                        Emin Bayram    2.675278   3.500
52                       Cesar Montes    1.075198   4.500
53                           Ola Aina   20.185371  22.000
54                        David Alaba    0.689119   6.000
55                 Bas van den Eynden    2.377697   0.700
56             Trent Alexander-Arnold   46.610139  75.000
57                Christopher Mamengi    0.575874   0.250
58                   Valentin Gendrey    6.774922   7.000
59                      Oleg Reabciuk    1.879087   4.000
60                   Enrico Del Prato   16.540040   6.500
61                       Ivan Smolcic    4.742237   1.800
62                        Joao Mendes    2.550337   2.000
63                         Hiroki Ito    2.321383  25.000
64                        Mike Kleijn    1.648315   0.250
65                         Nathan Ake    4.151681  25.000
66                    Antonio Rudiger    3.468262  20.000
67                     Patrick Mainka    6.796603   3.000
68                Dimitris Giannoulis    6.529324   3.000
69                         Ezri Konsa   24.393320  35.000
70                     Marco Palestra    4.406917   3.500
71                      Frans Kratzig    9.197375   3.500
72                          Emil Holm    5.860170   8.000
73             El Chadaille Bitshiabu    7.504360  18.000
74                      Hiroki Sekine    4.860642   1.200
75            Konstantin Nizhegorodov    0.984057   0.300
76                         Ko Itakura    9.026108  12.000
77                       Igor Vujacic    1.417931   3.000
78                         Borna Sosa    3.097376   4.500
79                    Marcus Pedersen    5.253960   3.000
80                     Ramon Hendriks    5.202672   5.000
81                    Florian Lejeune    7.456555   2.500
82                     Gleison Bremer    2.139387  50.000
83                      Marvin Senaya    2.447810   1.800
84                    Benedikt Gimber    5.262899   3.000
85                       Tuur Rommens    4.945317   4.000
86                     Alberto Moreno    2.312201   1.500
87                   Yunis Abdelhamid    0.575337   0.400
88                     Rosen Bozhinov    1.797388   0.400
89                     Koni De Winter   12.995724  22.000
90                           Kialonda    6.799336   3.500
91                   Jonas Fohrenbach    3.475504   1.500
92                         Lewis Dunk    6.388281   6.000
93                      Pierre Cornud    1.409752   0.800
94                     Piero Hincapie   16.296977  50.000
95                  Yarek Gasiorowski    5.847411   7.500
96                          Rob Nizet    1.070890   0.350
97                   Nathan Patterson   12.624619  15.000
98                    James Tarkowski   10.884943   9.000
99                        Maxime Busi    0.842876   1.000
100                         Lucas Hey    1.547743   5.000
101                    Theo Hernandez   18.842178  35.000
102              Alec Van Hoorenbeeck    1.136043   0.800
103                     Erik Schouten    0.370274   0.200
104                 Charlie Cresswell   20.451035  10.000
105                 Marc-Oliver Kempf    5.398694   3.000
106                   Alexandre Pinto    0.764974   0.500
107                    Dani Fernandez    1.321101   0.800
108                     Cesar Tarrega   15.929536  10.000
109                   Mardochee Nzita    1.108326   1.000
110                     Moussa Diarra    5.133197   1.800
111                       Aihen Munoz    2.808822   4.000
112                       Jorge Saenz    3.399358   1.500
113                     Gideon Mensah    3.814224   4.000
114                        Robin Koch    7.494592  18.000
115                        Karol Mets    1.310826   1.300
116                     Ethan Pinnock    7.398045   7.000
117                  Olivier Boscagli    2.299836  20.000
118                    Danilho Doekhi   12.098065  13.000
119                       Sven Botman    9.265249  42.000
120                        Leo Petrot    4.945613   0.900
121                    Giovanni Leoni   11.173459  18.000
122                         Ben White   11.258870  45.000
123                   Maksim Osipenko    2.872320   5.000
124                     Jordan Lefort    4.056392   1.500
125                        Willy Boly    1.987340   1.500
126                      Lucas Africo    0.989031   0.300
127                  Lucas Mincarelli    6.166811   0.900
128                       Hector Fort    8.699301  10.000
129                 Rasmus Kristensen   11.227426  14.000
130                    Tanguy Nianzou    3.414208   1.500
131                       Nuno Mendes   11.199325  70.000
132                      Raul Asencio    7.071165  40.000
133                   Leandro Cabrera    4.596858   1.000
134                       Nathan Zeze    7.670434  15.000
135                  Christian Gunter    4.579704   3.500
136                  Santiago Mourino    7.691295   3.000
137                   Michael Svoboda    4.055946   2.500
138                      Robin Gosens    9.370910   8.000
139                    Vitali Lystsov    0.399241   0.300
140                  Carlos Dominguez    3.964394   3.000
141                     Matteo Gabbia    9.701736  14.000
142                  Pervis Estupinan   20.028857  30.000
143                   Kiryl Pyachenin    1.249831   0.750
144                           Willyan    1.879710   6.000
145                Leo Skiri Østigard    6.330087  10.000
146                      Ilya Gaponov    0.705956   0.600
147                      Nuno Tavares   16.871569  25.000
148                   Aaron Cresswell    2.410526   0.500
149                    Facundo Garces    3.302304   2.000
150                   Rein Van Helden    3.637763   2.500
151                      Felix Bacher    1.954610   2.000
152                   Mathias Olivera    7.031366  20.000
153                    Siebe Horemans    1.502349   3.500
154                     Carlens Arcus    2.725682   1.800
155                    Rayan Senhadji    0.962735   0.700
156               Sven Sostaric Karic    1.631047   1.000
157                   Nicolas Pallois    1.038743   0.400
158                 Dmitri Skopintsev    1.270187   2.500
159                      Miguel Lopes    0.177228   0.050
160                     Michael Keane    5.972785   5.000
161                     David Jurasek    5.182557   5.000
162                 Lukas Klostermann    3.373080   8.000
163                    Matteo Ruggeri    8.355718  16.000
164                           Ulisses    2.963023   1.500
165                       Marius Wolf    4.879181   3.000
166                              Viti    3.734802   2.000
167                      Yael Mouanga    5.492375   0.600
168               Nemanja Andjelkovic    0.636051   0.750
169                             Natan    7.959427   9.000
170                   Sherel Floranus    1.179333   0.850
171                   Luca Marianucci    7.776303   7.500
172                    Jelle Bataille    1.205048   2.500
173                      Georgi Zotov    0.466941   0.050
174                    Gautier Lloris    4.453583   3.000
175                       Nico Elvedi    5.251851   8.000
176                      Brian Olivan    1.843358   1.800
177                        James Hill   17.817699   3.000
178                        Lewis Hall   41.438938  32.000
179                       Lucas Olaza    1.395703   4.000
180                       Inigo Lekue    1.049048   2.000
181           Anselmo Garcia MacNulty    4.937775   1.500
182                 Aridane Hernandez    0.874051   0.300
183                     Nelson Semedo   13.908307   9.000
184                           Carmona   10.462340  12.000
185                   Matthias Ginter    5.994044   7.000
186                     Hasan Kurucay    1.485466   1.300
187                     Joao Ferreira    1.412198   3.000
188             Etienne Youte Kinkoue    9.523508   7.000
189                            Danilo    1.081186   3.500
190                      Dion De Neve    4.966469   0.900
191                       Jhon Lucumi    7.355837  22.000
192                      Robson Bambu    0.840867   3.000
193                   Domingos Duarte    2.675464   0.800
194                    Jonathan Panzo    1.499199   1.200
195                        Javi Lopez    6.669374   7.500
196                     Aurele Amenda    4.435237   7.500
197            Vyacheslav Bardybakhin    1.100901   0.500
198                     Mario Hermoso    1.813081   7.000
199                      Adam Webster    4.800430  11.000
200                       Dembo Sylla    1.659283   0.500
201                     Patrick Erras    2.314144   0.800
202                   Maxime Bernauer    2.036024   2.000
203                Aleksandr Silyanov    3.076477   6.000
204                        Guela Doue   14.113152  18.000
205                  Matthijs de Ligt   23.270408  38.000
206                    Illia Zabarnyi   42.463639  42.000
207                  Maximilian Bauer    2.760137   2.000
208                       Djed Spence   20.005800  20.000
209                       Kyle Walker    3.359768   4.000
210                     Dani Carvajal    1.010014   8.000
211                     Modibo Sagnan    5.622264   3.000
212                      Nayef Aguerd    3.276927  18.000
213                Jan Paul van Hecke   32.191518  32.000
214                  Olivier Aertssen    1.968897   0.750
215             Tolis Konstantopoulos    3.115562   0.800
216                Bruno Martins Indi    0.249972   0.650
217                  Raffael Behounek    1.797480   0.800
218                       Ivan Balliu    1.082552   1.400
219                  Ousmane Diomande    6.212532  45.000
220                       Theo Barbet    0.938111   0.375
221                      Nasser Djiga    7.551609  10.000
222                     Ruben Roosken    1.376983   0.600
223                 Christiaan Ravych    3.437349   4.500
224               Ze Pedro Figueiredo    0.843998   4.000
225                   Yerson Mosquera    8.157594   8.000
226                   Bryan Goncalves    0.776653   0.600
227                     Oliver Braude    3.311282   4.000
228                 Aaron Wan-Bissaka   28.984114  24.000
229                         Finn Stam    1.378641   0.450
230                Frederico Venancio    0.550675   0.600
231                      Srdjan Babic    1.973261   6.000
232                        Luck Zogbe    6.571597   2.500
233                      Loic Mbe Soh    2.610060   2.000
234                        Youri Baas    2.256708  12.000
235                Jeffrey Gouweleeuw    4.096380   1.500
236                  Emmanuel Agbadou   17.975585  20.000
237                       Lucas Digne    9.114728  10.000
238                 Ignacio Rodriguez    1.665134   0.600
239                 Cesar Azpilicueta    0.899807   1.500
240                 Ricardo Rodriguez    1.637078   2.000
241                    Carlos Augusto   11.314313  26.000
242                      Mamadou Sarr   14.484231  20.000
243                    Edmond Tapsoba    8.427437  35.000
244                   Benjamin Pavard    3.496913  25.000
245                    Tommy St. Jago    2.043321   1.000
246                      Rick Meissen    0.964437   0.500
247                        James Bree    8.295395   2.500
248                        Pablo Mari    3.891752   3.500
249                     Noahkai Banks    6.335966   6.000
250                   Filipe Ferreira    0.569783   0.100
251                         Joe Gomez    5.090112  20.000
252                            Patric    1.283851   2.500
253                           Patrick    0.728878   0.900
254                    Daniel Oyegoke    4.550016   0.500
255                   Cristian Romero   11.703388  50.000
256                    Matisse Didden    0.970582   1.000
257                  Eliaquim Mangala    0.181833   0.200
258                    Becir Omeragic    6.337404   4.500
259                      Nehuen Perez    2.564712  13.000
260                       Denis Vavro    7.126197   7.000
261                     Stefan Lainer    1.363391   1.200
262                  Roman Neustadter    0.356589   0.150
263                       Marc Bartra    2.574036   1.000
264                     Jacob Greaves   22.492501  18.000
265                   Alvaro Carreras    5.113311  35.000
266                      Joseph Aidoo    1.437571   1.200
267                    Lorenzo Milani    0.903866   0.225
268                    Idar Shumakhov    2.651756   1.000
269                    Henry Lawrence    2.710915   1.500
270                     Nahuel Molina    4.716965  20.000
271                       Angel Ortiz    6.293274   2.500
272                     Tomas Ribeiro    1.005381   1.000
273                    Daniele Rugani    0.399485   3.000
274                      Matt Doherty    7.321537   2.000
275                   Danila Khotulev    1.670697   0.400
276                       Luke Thomas   10.627425   6.000
277                         Oscar Gil    0.942515   0.700
278                      David Hancko    4.067419  30.000
279                     Nicolo Casale    3.612189   6.000
280                 Frederic Guilbert    4.059451   2.500
281                       Pau Navarro    5.441738   3.000
282                      Sael Kumbedi    5.971606   7.000
283                           Maracas    1.078188   1.000
284                       Conor Coady    5.376112   2.200
285                    Josip Stanisic    4.425127  32.000
286                  Timothy Castagne    7.763421  13.000
287                        Pau Torres   11.110405  32.000
288                  Hristiyan Petrov    1.124089   0.600
289                      Adamo Nagalo    0.924838   6.000
290                      Myenty Abena    0.381500   0.700
291                      Clement Akpa    8.379872   5.000
292                    Jens Mathijsen    1.207636   0.200
293                         Vanderson    8.857351  20.000
294                         Isak Hien    6.354790  30.000
295                 Kingsley Ehizibue    4.583440   2.400
296                        Brian Plat    1.995535   0.700
297                      Falaye Sacko    1.774210   1.500
298                 Souleyman Doumbia    0.596509   1.000
299                Sebastiano Luperto   11.515163   4.000
300                    Ilya Vakhaniya    2.573045   3.000
301                  Rodrigo Pinheiro    2.841294   2.500
302                       Zaid Romero    1.239096   3.000
303                    William Saliba   33.538936  80.000
304                Nico Schlotterbeck    9.195571  40.000
305                   Aritz Elustondo    1.829764   3.000
306                     Sergei Petrov    0.528523   0.400
307                      Haruya Fujii    1.828657   2.000
308                      Eder Militao    3.839347  30.000
309                       Bas Kuipers    1.258031   1.200
310                      Andrei Ratiu   11.715337  12.000
311                   Milos Veljkovic    2.383125   3.000
312                   Cameron Burgess    9.775194   2.000
313                        Adam Smith    3.542068   0.750
314                      Marco Friedl    4.108718  12.000
315                     Conor Bradley   25.706175  30.000
316                 Aleksandar Sedlar    0.808652   0.300
317                     Maxim Leitsch    3.126709   1.500
318                       Nathan Ngoy    1.548224   3.500
319                    Edgardo Farina    2.595806   1.000
320                       Diogo Dalot   27.346472  30.000
321                    Jorne Spileers    2.206672   2.000
322                      Mats Hummels    0.959815   2.000
323                 Zakaria El Ouahdi    6.954993  12.000
324                    Federico Barba    1.339356   0.500
325                   Ewoud Pletinckx    1.878366   1.800
326                        Leif Davis   30.276694  22.000
327                Leftheris Lyratzis    1.294115   0.850
328                    Giorgio Altare    2.888284   1.000
329                      Jan Bednarek   13.173146   9.000
330                        Oumar Sako    1.389182   3.000
331                    Pascal Stenzel    3.603052   2.000
332                     Abel Bretones    7.650302   4.000
333                       Raul Albiol    0.519241   1.000
334                    Almugera Kabar    4.519787   1.000
335                       Hugo Gambor    1.988579   1.000
336                Alessandro Circati    5.269540   8.000
337                  Thijmen Blokzijl    3.200525   2.000
338                     Mujaid Sadick    2.542083   8.000
339              Vyacheslav Karavayev    0.527795   3.500
340                    Rafik Belghali    3.944385   2.500
341                   Stefano Sabelli    2.699359   1.400
342                 Nikola Milenkovic   49.777484  35.000

In [30]:
comp_leftovers_test

                       Player  Value_pred   Value
0                Jon Aramburu    8.417943  15.000
1             Alphonso Davies    9.521763  50.000
2          Riccardo Calafiori   20.263305  35.000
3                  Fali Cande    4.427993   2.500
4              Romain Perraud    7.272842   5.000
5                Harry Clarke    7.531020   4.500
6                  Boyd Reith    0.649284   0.400
7            Zineddine Belaid    1.218045   0.800
8                  Yerry Mina    5.702930   3.000
9                 Aiham Ousou    2.275199   2.500
10            Youssouf Sabaly    1.742966   1.800
11              Daniel Vivian   10.267191  40.000
12     Maximilian Mittelstadt    8.147746  20.000
13                 Alex Munoz    2.355924   1.000
14         Jannik Vestergaard    4.268019   2.000
15                Ali Dembele    7.449977   0.900
16            Aleksei Tatayev    0.991431   0.800
17            Marvin da Graca    0.471449   0.400
18              Stephen Welsh    0.986128   1.000
19           Mahamadou Nagida    7.870456   0.800
20                Jonny Evans    1.388528   1.000
21              Pedro Pereira    9.160034   1.500
22          Milan Majstorovic    2.359469   1.800
23            Rayan Ait-Nouri   72.378433  35.000
24                Tiago Djalo    1.071874   8.000
25            Anthony Rouault    9.047476  10.000
26       Lorenzo De Silvestri    1.044247   0.800
27                Abdul Mumin    5.463255   5.000
28      Przemyslaw Frankowski    3.614890   7.000
29           Eduardo Quaresma    1.446753  18.000
30           Micky van de Ven   15.914146  50.000
31   Konstantinos Koulierakis   18.158868  25.000
32                Anton Gaaei    4.490655   7.000
33               Sergino Dest    1.334144  16.000
34                Abdel Abqar    6.900618   7.500
35                 Bamo Meite    2.949492   4.000
36              Gerard Martin    8.060042  12.000
37                   Iglesias    6.902363   3.500
38             Egor Pogostnov    1.895382   1.800
39             Ricardo Mangas    1.044263   2.500
40         Mike van der Hoorn    1.329718   1.000
41              Shawn Adewoye    1.505337   1.300
42                Jonas Rouhi    3.870051   2.000
43              Alexis Duarte    1.295247   3.000
44           Andrey Langovich    4.602328   3.000
45               Hamza Mendyl    0.970145   1.000
46           Mike Eerdhuijzen    2.523679   2.300
47            Ruben Fernandes    0.437281   0.050
48            Thierry Correia    2.977268   3.000
49              Marco Komenda    2.634245   0.800
50              Jordy Makengo    3.597979   6.000
51           Giorgio Scalvini    6.850466  35.000
52                 Rico Henry    3.371915  15.000
53               Victor Gomez    1.949060   6.000
54          Noussair Mazraoui   15.190929  25.000
55                 Hugo Bueno    2.397858   8.000
56                  Felix Agu    7.458137   8.000
57           Flavius Daniliuc    4.094009   2.700
58      Youssouf Ndayishimiye    6.159014  12.000
59                 Toti Gomes   17.087750  28.000
60                Ian Maatsen   28.765173  28.000
61             Evgeni Morozov    1.462563   3.000
62            Duplexe Tchamba    1.503328   1.000
63                  Wout Faes   20.383630  15.000
64               Carlos Ponck    0.349844   0.600
65                Tim Drexler    5.397381   3.000
66             Javi Rodriguez   14.931680  15.000
67                Lloyd Kelly    5.147859  16.000
68               Ivan Marquez    0.931510   0.600
69            Cristian Castro    3.089023   0.800
70              Igor Yurganov    0.783772   0.500
71               Eduard Sobol    0.869635   0.900
72        Patrick van Aanholt    0.467814   0.500
73             Goncalo Inacio    3.982571  45.000
74               Javi Sanchez    4.825703   1.500
75              Ferland Mendy    1.642208  14.000
76              Boris Popovic    1.056605   1.500
77             Josko Gvardiol   80.831364  75.000
78            Tommaso Augello    6.711131   1.800
79                Ivan Ordets    2.137000   1.000
80              Ryan Alebiosu    2.507370   0.500
81               Rafael Toloi    0.952079   1.400
82              Calvin Bassey   30.881228  25.000
83       Michael Amir Murillo    5.077186  10.000
84              Aaron Meijers    0.142319   0.075
85          Mathias Jorgensen    0.559480   0.500
86            Ibrahima Konate   25.391988  60.000
87              Botond Balogh    8.681508   2.400
88                Amos Pieper    3.605676   3.500
89            Oleksandr Filin    1.564341   1.000
90      Boli Bolingoli-Mbombo    0.503458   0.500
91           Mouctar Diakhaby    3.622223   2.000
92                Ilay Camara    5.289353   4.000
93                 Alex Valle    8.192409   6.000
94            Emanuele Valeri   15.758947   3.000
95               Armando Izzo    3.132395   1.500
96         Vasilios Zagaritis    3.044306   0.700
97              Egor Teslenko    4.673281   2.000
98              Wesley Fofana   11.293638  25.000
99                    Ben Mee    1.360822   0.700
100        Soumaila Coulibaly    5.016579   8.000
101                 Issa Diop    7.539255  14.000
102               Jesus Areso    9.036875  12.000
103           Dayot Upamecano    5.997904  50.000
104            Cedric Zesiger    5.375971   7.000
105              Craig Dawson    2.579143   1.500
106             Alexander Bah    1.020803  10.000
107              David Torres    5.917263   1.500
108                Karol Fila    0.989868   0.600
109       Giangiacomo Magnani    3.126434   1.800
110         Vitaliy Mykolenko   27.761238  28.000
111                Hauke Wahl    4.423134   1.500
112                Glenn Bijl    0.987000   1.500
113              Tiago Esgaio    1.428595   0.900
114            Wilfried Singo    8.957029  25.000
115            Manuel Lazzari    2.360511   3.500
116                      Nino    2.716248  11.000
117             Scott McKenna    5.198844   4.000
118                 Mats Rots    3.206711   1.000
119         Godfried Frimpong    2.358847   2.000
120           Renato Pantalon    0.869283   0.600
121           Moussa Niakhate    3.970165  15.000
122   Francisco Reis Ferreira    0.734491   0.700
123             Mads Roerslev   12.114792   6.000
124             Jordan Zemura    7.990898   4.500
125            Andrea Carboni    8.125502   2.800
126          Andrew Robertson   10.607705  18.000
127                Juan Jesus    1.258818   1.500
128          Jonathan Mutombo    1.385914   0.500
129              Joseph Okumu    3.661682   7.000
130                Marco Sala    2.043402   0.900
131                Diego Rico    3.585977   1.200
132              Finn Jeltsch    6.711203  20.000
133                Max Kilman   22.977791  25.000
134              Thilo Kehrer    6.124907  20.000
135           Brandon Mechele    1.553921   3.500
136         Gabriel Magalhaes   26.209355  75.000
137        Anass Salah-Eddine    2.582131   8.000
138          Javier Manquillo    0.981694   1.000
139       Redouan El Yaakoubi    0.353791   0.550
140                Kenny Lala    2.648058   2.000
141        Nathan Wood-Gordon   10.566346   3.500
142     Aleksandr Soldatenkov    1.247119   4.000
143               Logan Costa   11.901435  18.000
144           Abdoulaye Bamba    0.924777   0.300
145             Hjalmar Ekdal    0.790056   4.500
146           Thierry Lutonda    0.788009   0.300
147                  Angelino   11.958694  20.000
148             Rafik Messali    5.739995   0.800
149            Javi Hernandez    7.834205   2.500
150               Fran Garcia    6.869151  18.000
151       Konstantin Savichev    1.079586   0.900
152        Christian Kabasele    2.094512   0.700
153              David Hrncar    2.344101   1.200
154             Antoine Mendy    6.039915   2.500
155           Castello Lukeba    6.895291  40.000
156            Paulo Oliveira    0.631776   1.000
157                 Yoel Lago    4.995451   1.000
158            Emmanuel Kakou    3.747222   1.000
159               Malang Sarr    3.383293   5.000
160       Keven Schlotterbeck    4.827159   6.000
161            Jose Luis Gayà    2.695663   9.000
162            Wolke Janssens    0.504560   0.400
163           Mohammed Salisu    3.331647  12.000
164               Oumar Solet    7.985553  18.000
165             Marcos Senesi    5.813980  22.000
166              Andy Pelmard    2.249546   2.000
167              Semm Renders    3.431312   1.500
168          Antonee Robinson   29.491518  35.000
169        Brendan Chardonnet    3.628554   6.000
170            Inigo Martinez    2.975543   5.000
171                    Catena    6.983615   3.000
172            Jarell Quansah    9.957797  20.000
173                Joe Scally   11.354658  10.000
174                    Michel    0.866986   1.000
175        Jose Luis Palomino    0.983874   0.700
176           Matija Nastasic    2.306503   0.800
177              Kelvin Amian    4.342505   2.500
178             Marvin Elimbi    0.949754   0.750
179            Marc Cucurella   34.583033  35.000
180          Maksim Shnaptsev    2.077651   0.300
181               Ahmed Touba    1.934821   2.500
182                      Igor    6.551130  20.000
183            Tomas Palacios    4.121803   4.000
184              Jules Kounde    9.452963  65.000
185               Matte Smets    4.023683  13.000
186             Ricardo Visus    1.843843   0.750
187            German Ignatov    2.609793   0.500
188         Roberto Fernandez    2.118925   3.500
189               Kim Min-jae    5.503301  40.000
190             Ibe Hautekiet    2.436673   3.500
191                    Moises    1.737394   5.000
192             Lukas Ullrich   12.964647   8.000
193            Lucas Calegari    1.599017   3.500
194        Jordan Torunarigha    1.471556   4.000
195             Jack Stephens    5.111019   1.500
196                Jose Gomes    1.967578   1.000
197               Axel Witsel    0.723313   2.000
198            Berat Djimsiti    4.576641   6.000
199          Mutalip Alibekov    0.861938   0.700
200             Sergio Akieme    9.710926   7.000
201                Marc Guehi   40.110645  45.000
202         Tsuyoshi Watanabe    2.959508   9.000
203               Dinis Pinto    3.096896   1.500
204             Alan Matturro    7.544071   7.000
205         Francesco Zampano    3.087961   1.000
206              Robert Gumny    2.879370   1.500
207                Raul Silva    0.269924   0.100
208             Thomas Beelen    1.773878   8.000
209             Juan Berrocal    3.068065   1.500
210           Maksim Nenakhov    1.843618   3.000
211             Diego Coppola   19.129937  10.000
212            Julian Ryerson    8.626675  20.000
213                    Orinho    1.167577   0.600
214          Leopold Querfeld   15.929744  13.000
215            Willy Kambwala    6.898484   4.000
216           Lucas Hernandez    1.594654  25.000
217         Toby Alderweireld    1.275602   2.000
218              Manuel Osifo    1.823129   0.700
219              Adam Marusic    5.499277   3.500
220           Sinaly Diomande    8.866876   5.000
221           Ladislav Krejci    8.610657  12.000
222               Emil Krafth    3.322466   2.000
223          Massadio Haidara    1.838898   1.500
224              Jordan Amavi    1.498933   1.500
225        Jose Maria Gimenez    2.941343  20.000
226               Chico Lamba    3.705651   3.000
227        Myles Lewis-Skelly   30.340679  45.000
228        Alexsandro Ribeiro   10.585325  20.000
229          Domagoj Bradaric    6.671060   4.000

# Модель 8

In [7]:
X_train = X_train[['G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G-PK', 'Ast.1', '90s', 'CrdY', 'Sh/90', 'TklW', 'Age', 'Int', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [179]:
coeffs_df

               coeff
league_GB1  0.641447
Age        -0.584517
90s         0.499064
league_IT1  0.370106
league_L1   0.323713
league_ES1  0.299498
league_FR1  0.268970
Sh/90       0.154092
league_NL1 -0.135165
Ast.1       0.123980
league_PO1 -0.091097
G-PK        0.086928
TklW       -0.079272
league_RU1 -0.023949
Int        -0.018021
CrdY        0.002443

In [180]:
metrics

            MAE       RMSE      MAPE        R2
test   5.369203  10.435910  0.917497  0.405668
train  4.587877   9.360052  0.897648  0.380431

In [182]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                               Player  Value_pred   Value
664                      Milos Kerkez   87.317019  45.000
412                      Dean Huijsen   61.453324  60.000
730                    Nathan Collins   56.144334  28.000
890                      Levi Colwill   55.663988  55.000
503                           Murillo   50.295091  55.000
342                 Nikola Milenkovic   49.465111  35.000
10                        Pedro Porro   47.956962  38.000
56             Trent Alexander-Arnold   46.491784  75.000
206                    Illia Zabarnyi   42.492948  42.000
178                        Lewis Hall   41.452132  32.000
795             Taylor Harwood-Bellis   40.692221  22.000
25                      Neco Williams   38.232264  20.000
777                   Maxence Lacroix   36.204772  25.000
303                    William Saliba   33.742047  80.000
836                 Sepp van den Berg   32.940649  22.000
213                Jan Paul van Hecke   32.200211  32.000
1                     Tyrick Mitchell   31.104079  25.000
9                         Dara O'Shea   30.598586  14.000
784                      Daniel Munoz   30.473307  25.000
326                        Leif Davis   30.280130  22.000
522                        Malo Gusto   29.693033  35.000
734                Jarrad Branthwaite   29.601069  50.000
472                    Jurrien Timber   29.165264  55.000
228                 Aaron Wan-Bissaka   28.995005  24.000
572                      James Justin   27.905632  13.000
320                       Diogo Dalot   27.390086  30.000
451                     Nico O’Reilly   26.684611  18.000
315                     Conor Bradley   25.720948  30.000
840         Victor Bernth Kristiansen   24.548176  15.000
69                         Ezri Konsa   24.418415  35.000
724                         Leny Yoro   23.497904  55.000
205                  Matthijs de Ligt   23.242080  38.000
702                       Pau Cubarsi   23.117762  80.000
805                     Luka Vuskovic   22.793616  12.000
264                     Jacob Greaves   22.505869  18.000
771                   Trevoh Chalobah   22.476262  25.000
456                       Harry Amass   21.002405   5.000
390                Kyle Walker-Peters   20.664196  15.000
104                 Charlie Cresswell   20.378314  10.000
53                           Ola Aina   20.214401  22.000
142                  Pervis Estupinan   20.035800  30.000
208                       Djed Spence   20.020365  20.000
655                    Destiny Udogie   20.020095  40.000
101                    Theo Hernandez   18.733677  35.000
496                Cristhian Mosquera   18.672017  30.000
785                     Tariq Lamptey   18.368152  11.000
834                      Fabian Schar   18.289036   7.000
236                  Emmanuel Agbadou   17.975951  20.000
177                        James Hill   17.821957   3.000
772                   Raoul Bellanova   17.343592  24.000
787                      Jake O'Brien   17.306551  18.000
628                    Chris Richards   16.965403  14.000
147                      Nuno Tavares   16.907993  25.000
377                    Michael Kayode   16.657895  18.000
621                   Alejandro Balde   16.588871  60.000
60                   Enrico Del Prato   16.544807   6.500
866                     Johan Vasquez   16.512464  14.000
94                     Piero Hincapie   16.271501  50.000
871                 Lisandro Martinez   16.020602  40.000
108                     Cesar Tarrega   15.913508  10.000
427                        Ruben Dias   15.910347  65.000
541                     Obite N'Dicka   15.574119  30.000
747                       Enzo Boyomo   15.363454  20.000
741                              Dodo   15.245430  24.000
432                   Virgil van Dijk   15.231643  23.000
877                    Bafode Diakite   15.035002  28.000
743                     Alex Grimaldo   15.002834  30.000
603                        Matty Cash   14.911327  25.000
418                        Kike Salas   14.875611   8.000
42                      Radu Dragusin   14.656855  25.000
474                    Pietro Comuzzo   14.491489  25.000
242                      Mamadou Sarr   14.478825  20.000
908                     Carlos Romero   14.333118   5.000
861           Konstantinos Mavropanos   14.234811  17.000
388                          Dan Burn   14.220646   6.000
362                     Achraf Hakimi   14.147591  80.000
204                        Guela Doue   14.118892  18.000
183                     Nelson Semedo   13.928788   9.000
375                      Juan Miranda   13.869054  15.000
399                    Gabriele Zappa   13.802339   4.000
761                Yann Aurel Bisseck   13.643004  35.000
596                  Saba Goglichidze   13.392924   8.000
329                      Jan Bednarek   13.282858   9.000
791                         Jay Idzes   13.274464   7.500
576                  Tosin Adarabioyo   13.170929  20.000
394                 Jean-Clair Todibo   13.109827  25.000
493                 Chrislain Matsima   12.992146  22.000
89                     Koni De Winter   12.986064  22.000
898                   Marash Kumbulla   12.919119   7.500
591                      Luca Ranieri   12.737666  12.000
558                       Tim Oermann   12.731278   5.000
411                    Quentin Merlin   12.717920  15.000
870                     Arthur Theate   12.639909  24.000
854                    Omar El Hilali   12.607370  15.000
97                   Nathan Patterson   12.604537  15.000
710              Federico Baschirotto   12.573619   3.600
608                       Caleb Okoli   12.115154  10.000
118                    Danilho Doekhi   12.094601  13.000
393                        Kenny Tete   11.975390  13.000
885                        Mario Gila   11.893817  30.000
481                         Saul Coco   11.783487  10.000
28                      Sergi Cardona   11.760090  10.000
255                   Cristian Romero   11.701566  50.000
310                      Andrei Ratiu   11.699556  12.000
299                Sebastiano Luperto   11.514679   4.000
607                      Anthony Caci   11.496446  12.000
718                        Jaka Bijol   11.453778  18.000
397                    Santiago Bueno   11.367784  10.000
121                    Giovanni Leoni   11.312169  18.000
241                    Carlos Augusto   11.280451  26.000
122                         Ben White   11.258119  45.000
131                       Nuno Mendes   11.201126  70.000
398                       Mattia Viti   11.197495   5.500
129                 Rasmus Kristensen   11.164712  14.000
466                     Nicolo Savona   11.134658  12.000
287                        Pau Torres   11.106465  32.000
533                Alessandro Bastoni   11.002013  80.000
98                    James Tarkowski   10.893420   9.000
276                       Luke Thomas   10.616945   6.000
661                       Sam Beukema   10.612408  28.000
441             Giorgos Kyriakopoulos   10.580925   2.500
850                        Jon Martin   10.559468   8.000
507                      Aaron Martin   10.488526   6.500
184                           Carmona   10.477644  12.000
649                            Morato   10.432714  14.000
690                     Axel Tuanzebe   10.372695   5.000
802                Strahinja Pavlovic   10.126676  18.000
817                  Daniele Ghilardi   10.123762   5.000
479                     Lucas Beraldo   10.072779  25.000
798                     Manuel Akanji    9.887520  28.000
312                   Cameron Burgess    9.774556   2.000
352                   Lasse Rosenboom    9.746940   1.500
141                     Matteo Gabbia    9.691880  14.000
598                      Jonathan Tah    9.632566  30.000
346                   Kristoffer Ajer    9.623411  18.000
369                  Abdulai Juma Bah    9.554277   6.000
188             Etienne Youte Kinkoue    9.525647   7.000
35                      Omar Alderete    9.422316   8.000
410                  Gianluca Mancini    9.410579  15.000
766                         Loic Bade    9.407678  25.000
138                      Robin Gosens    9.320466   8.000
727                        Amar Dedic    9.274172  12.000
119                       Sven Botman    9.261357  42.000
71                      Frans Kratzig    9.200646   3.500
304                Nico Schlotterbeck    9.199697  40.000
617                     Joakim Maehle    9.133691  14.000
237                       Lucas Digne    9.123035  10.000
76                         Ko Itakura    9.000702  12.000
494                     Amir Rrahmani    8.921855  12.000
729                    Nnamdi Collins    8.904387  10.000
715                       Diogo Leite    8.870466  17.000
293                         Vanderson    8.860703  20.000
610                    Antonino Gallo    8.847289   4.300
778                         Welington    8.746754   3.000
128                       Hector Fort    8.692818  10.000
379                     Julian Chabot    8.482755  12.000
714                        Adam Obert    8.471861   3.000
243                    Edmond Tapsoba    8.431458  35.000
513                    Ki-Jana Hoever    8.395809   5.000
291                      Clement Akpa    8.380777   5.000
163                    Matteo Ruggeri    8.346391  16.000
590               Giovanni Di Lorenzo    8.308318  12.000
247                        James Bree    8.286240   2.500
650                   Luke Woolfenden    8.260202   2.000
666                     Julian Araujo    8.206905  10.000
625                    Facundo Medina    8.205751  25.000
758                   Luca Pellegrini    8.200467   3.000
614                     Pierre Kalulu    8.157215  28.000
225                   Yerson Mosquera    8.143441   8.000
565                      Bjorn Meijer    8.013151   4.000
848                      Manu Sanchez    8.010712   6.000
786                    Federico Gatti    7.971852  24.000
169                             Natan    7.967661   9.000
819                     Arthur Chaves    7.938371   5.000
810                      Malick Thiaw    7.864392  18.000
694                       Mika Marmol    7.860949  10.000
34                    Emmanuel Biumla    7.809365   4.000
171                   Luca Marianucci    7.766888   7.500
286                  Timothy Castagne    7.761868  13.000
347                        Saidou Sow    7.729130   6.000
859                    Jeremy Jacquet    7.705900  10.000
136                  Santiago Mourino    7.693693   3.000
134                       Nathan Zeze    7.664677  15.000
332                     Abel Bretones    7.653781   4.000
899                       Jorrel Hato    7.638706  35.000
742                   Lilian Brassier    7.636079  10.000
447                 Thomas Kristensen    7.601808   6.000
221                      Nasser Djiga    7.528805  10.000
73             El Chadaille Bitshiabu    7.492280  18.000
114                        Robin Koch    7.480048  18.000
794                       Axel Disasi    7.460027  22.000
81                    Florian Lejeune    7.451133   2.500
853                    Kilian Fischer    7.426462   6.000
116                     Ethan Pinnock    7.407546   7.000
191                       Jhon Lucumi    7.357212  22.000
274                      Matt Doherty    7.333345   2.000
33                        Omar Traore    7.291354   4.000
688                 Maximilian Wittek    7.271329   1.500
901                   Fabio Chiarodia    7.239083   2.000
408                 Kosta Nedeljkovic    7.205754  10.000
905                      David Nemeth    7.205417   4.000
260                       Denis Vavro    7.111856   7.000
132                      Raul Asencio    7.064201  40.000
152                   Mathias Olivera    7.034113  20.000
40                 Abdukodir Khusanov    7.016850  35.000
515                     Adrià Pedrosa    6.969608   7.000
480                       Juan Herzog    6.965829   2.500
323                 Zakaria El Ouahdi    6.933438  12.000
883                     Harry Maguire    6.876206  13.000
415                         Luca Netz    6.871730   6.000
361                     Willian Pacho    6.867881  65.000
90                           Kialonda    6.799585   3.500
67                     Patrick Mainka    6.795817   3.000
416                 Davide Zappacosta    6.790354   5.000
613                     Max Geschwill    6.775887   1.500
58                   Valentin Gendrey    6.772479   7.000
847                   Alexander Prass    6.767647   5.000
424                        Adam Aznou    6.700656   4.000
556                         David Zec    6.683698   2.500
691                   Max Rosenfelder    6.671280   8.000
195                        Javi Lopez    6.664928   7.500
701                      Marko Ivezic    6.660936   2.000
469                       Enzo Tchato    6.654634   2.500
470                        David Raum    6.643283  20.000
49                     Martin Valjent    6.637876   6.000
630                   Alberto Dossena    6.614942   8.000
585         Abdoulaye Niakhate Ndiaye    6.586399   4.000
232                        Luck Zogbe    6.570902   2.500
5                       Aitor Paredes    6.550431  22.000
573                      Jorge Cuenca    6.539888   5.000
703            Ainsley Maitland-Niles    6.536442  12.000
68                Dimitris Giannoulis    6.533387   3.000
902                   Nahuel Tenaglia    6.500585   3.000
615                 Leonidas Stergiou    6.465780   5.000
531                 Benoît Badiashile    6.450015  22.000
21                  Christian Mawissa    6.416552  15.000
92                         Lewis Dunk    6.389609   6.000
294                         Isak Hien    6.352605  30.000
258                    Becir Omeragic    6.333413   4.500
145                Leo Skiri Østigard    6.332981  10.000
686                 Alessio Romagnoli    6.327903   7.000
249                     Noahkai Banks    6.319096   6.000
271                       Angel Ortiz    6.286169   2.500
875               Lucas Oliveira Rosa    6.285477   3.000
455                   Antonio Candela    6.269351   1.800
852                   Arouna Sangante    6.252408   8.000
476              Lutsharel Geertruida    6.237607  20.000
443                   Ramy Bensebaini    6.231311   7.000
538             Ignace Van Der Brempt    6.219864   4.000
842                 Joel Schingtienne    6.201199   3.500
219                  Ousmane Diomande    6.198532  45.000
731                    Jorge Herrando    6.189067   4.000
420                       Anrie Chase    6.184311   3.000
127                  Lucas Mincarelli    6.175634   0.900
430                     Konrad Laimer    6.173849  25.000
618                 Kiliann Sildillia    6.101743  10.000
807                       Timo Becker    6.077380   1.500
680                    Antonio Raillo    6.044979   1.800
893                  Philipp Lienhart    6.024623  12.000
160                     Michael Keane    5.984731   5.000
185                   Matthias Ginter    5.982572   7.000
282                      Sael Kumbedi    5.963443   7.000
381               Gabriel Gudmundsson    5.955137   7.000
903                  Souleymane Toure    5.904222   7.000
72                          Emil Holm    5.861030   8.000
803                       Jakov Medic    5.843176   2.000
95                  Yarek Gasiorowski    5.838528   7.500
378             Sebastian Walukiewicz    5.829351   4.500
452                  Timothee Pembele    5.811723   2.500
684                   Kostas Tsimikas    5.768423  18.000
548                   Jan-Carlo Simic    5.767000   8.000
881             Alessandro Buongiorno    5.762022  50.000
574                    Phillipp Mwene    5.754646   1.800
551                    Waldemar Anton    5.753792  18.000
656                    Ramon Martinez    5.720942   1.000
15                         Sacha Boey    5.690714  18.000
389                    Stefan Lekovic    5.648506   1.700
555              Souffian El Karouani    5.629456   9.000
211                     Modibo Sagnan    5.627847   3.000
512                        Zeki Celik    5.615318   6.000
594                     Gabriel Suazo    5.612553   4.000
564                  Christopher Wooh    5.612466   6.000
562                     Moise Bombito    5.591633  10.000
762                      Givairo Read    5.574448  16.000
356                       Kevin Danso    5.517036  25.000
660              Alessandro Vogliacco    5.500376   2.800
167                      Yael Mouanga    5.481685   0.600
380                      Tiago Santos    5.465933  15.000
284                       Conor Coady    5.449462   2.200
435                      Mickael Nade    5.442600   2.000
281                       Pau Navarro    5.431001   3.000
105                 Marc-Oliver Kempf    5.401927   3.000
612                    Flavio Nazinho    5.379167   3.000
39                    Valentin Rosier    5.314321   3.000
44                  Mikayil Ngor Faye    5.309746   6.000
353                  Leonardo Balerdi    5.277147  20.000
84                    Benedikt Gimber    5.265057   3.000
417                 Alejandro Frances    5.259798   2.000
336                Alessandro Circati    5.256922   8.000
175                       Nico Elvedi    5.250794   8.000
79                    Marcus Pedersen    5.248089   3.000
620                      Archie Brown    5.231704   7.000
80                     Ramon Hendriks    5.195677   5.000
889                    Ardian Ismajli    5.179838   6.000
161                     David Jurasek    5.176811   5.000
677                   Lautaro Valenti    5.174109   1.500
511                      Abakar Sylla    5.140776  10.000
845                            Arthur    5.131537   7.000
110                     Moussa Diarra    5.128166   1.800
514                Sebastiaan Bornauw    5.121034   6.000
634                             Jubal    5.119155   2.500
265                   Alvaro Carreras    5.102827  35.000
251                         Joe Gomez    5.083363  20.000
575                       Willi Orban    5.040779   8.000
839                  Martim Fernandes    5.039304  12.000
668                  Odilon Kossounou    5.038670  25.000
41                  Nicolas Valentini    5.018259   6.000
914                   Julian Malatini    5.014582   2.500
190                      Dion De Neve    4.955128   0.900
85                       Tuur Rommens    4.948611   4.000
120                        Leo Petrot    4.948345   0.900
181           Anselmo Garcia MacNulty    4.936543   1.500
376                       Pedro Bondo    4.933616   0.500
165                       Marius Wolf    4.879173   3.000
464                      Fellipe Jack    4.863952   1.400
74                      Hiroki Sekine    4.854855   1.200
770                     Jesus Vazquez    4.817179   3.000
199                      Adam Webster    4.795798  11.000
47                         Juan Foyth    4.781874  15.000
693                  Robin Le Normand    4.780926  40.000
37                     Hassane Kamara    4.759011   3.500
459                   Maxim De Cuyper    4.753808  16.000
428                       Igor Diveev    4.747293   8.000
61                       Ivan Smolcic    4.738215   1.800
270                     Nahuel Molina    4.717108  20.000
726                      Denso Kasius    4.708734   4.000
539                      Tyrone Mings    4.666959   5.000
133                   Leandro Cabrera    4.585071   1.000
295                 Kingsley Ehizibue    4.584802   2.400
679      Caio Henrique Oliveira Silva    4.580401  15.000
135                  Christian Gunter    4.572755   3.500
254                    Daniel Oyegoke    4.542267   0.500
334                    Almugera Kabar    4.504422   1.000

In [183]:
comp_leftovers_test.sort_values('Value_pred', ascending=False)

                       Player  Value_pred   Value
77             Josko Gvardiol   80.247596  75.000
23            Rayan Ait-Nouri   72.037168  35.000
201                Marc Guehi   40.093512  45.000
179            Marc Cucurella   34.408033  35.000
82              Calvin Bassey   30.894256  25.000
227        Myles Lewis-Skelly   30.557671  45.000
168          Antonee Robinson   29.550028  35.000
60                Ian Maatsen   28.775205  28.000
110         Vitaliy Mykolenko   27.779017  28.000
136         Gabriel Magalhaes   26.142407  75.000
86            Ibrahima Konate   25.389916  60.000
133                Max Kilman   23.001164  25.000
63                  Wout Faes   20.393146  15.000
2          Riccardo Calafiori   20.290401  35.000
211             Diego Coppola   19.158517  10.000
31   Konstantinos Koulierakis   18.169242  25.000
59                 Toti Gomes   17.092644  28.000
214          Leopold Querfeld   15.913454  13.000
30           Micky van de Ven   15.904939  50.000
94            Emanuele Valeri   15.758833   3.000
54          Noussair Mazraoui   15.206213  25.000
66             Javi Rodriguez   14.944218  15.000
192             Lukas Ullrich   12.976921   8.000
123             Mads Roerslev   12.106358   6.000
147                  Angelino   11.936302  20.000
143               Logan Costa   11.908301  18.000
173                Joe Scally   11.348527  10.000
98              Wesley Fofana   11.278492  25.000
126          Andrew Robertson   10.614831  18.000
228        Alexsandro Ribeiro   10.586370  20.000
141        Nathan Wood-Gordon   10.546718   3.500
11              Daniel Vivian   10.236795  40.000
172            Jarell Quansah    9.935932  20.000
200             Sergio Akieme    9.699124   7.000
1             Alphonso Davies    9.516784  50.000
184              Jules Kounde    9.446855  65.000
21              Pedro Pereira    9.163604   1.500
25            Anthony Rouault    9.044959  10.000
102               Jesus Areso    9.044180  12.000
114            Wilfried Singo    8.957753  25.000
220           Sinaly Diomande    8.894216   5.000
87              Botond Balogh    8.671495   2.400
212            Julian Ryerson    8.616543  20.000
221           Ladislav Krejci    8.602176  12.000
0                Jon Aramburu    8.426431  15.000
93                 Alex Valle    8.183994   6.000
12     Maximilian Mittelstadt    8.151295  20.000
125            Andrea Carboni    8.121493   2.800
36              Gerard Martin    8.074981  12.000
124             Jordan Zemura    7.987683   4.500
164               Oumar Solet    7.983106  18.000
19           Mahamadou Nagida    7.915281   0.800
149            Javi Hernandez    7.828654   2.500
101                 Issa Diop    7.531963  14.000
204             Alan Matturro    7.529462   7.000
5                Harry Clarke    7.514882   4.500
15                Ali Dembele    7.474488   0.900
56                  Felix Agu    7.467393   8.000
4              Romain Perraud    7.265531   5.000
171                    Catena    6.987666   3.000
37                   Iglesias    6.912383   3.500
34                Abdel Abqar    6.904933   7.500
215            Willy Kambwala    6.888736   4.000
155           Castello Lukeba    6.884870  40.000
150               Fran Garcia    6.872817  18.000
51           Giorgio Scalvini    6.845884  35.000
78            Tommaso Augello    6.713219   1.800
132              Finn Jeltsch    6.695778  20.000
229          Domagoj Bradaric    6.673735   4.000
182                      Igor    6.539180  20.000
58      Youssouf Ndayishimiye    6.164995  12.000
134              Thilo Kehrer    6.128412  20.000
154             Antoine Mendy    6.038544   2.500
103           Dayot Upamecano    5.994313  50.000
107              David Torres    5.909496   1.500
165             Marcos Senesi    5.806001  22.000
148             Rafik Messali    5.736838   0.800
8                  Yerry Mina    5.701264   3.000
189               Kim Min-jae    5.524512  40.000
219              Adam Marusic    5.473782   3.500
27                Abdul Mumin    5.471319   5.000
65                Tim Drexler    5.385644   3.000
104            Cedric Zesiger    5.375802   7.000
92                Ilay Camara    5.290327   4.000
117             Scott McKenna    5.199422   4.000
67                Lloyd Kelly    5.144550  16.000
195             Jack Stephens    5.136379   1.500
83       Michael Amir Murillo    5.080895  10.000
100        Soumaila Coulibaly    5.011439   8.000
157                 Yoel Lago    4.984878   1.000
74               Javi Sanchez    4.829281   1.500
160       Keven Schlotterbeck    4.827543   6.000
97              Egor Teslenko    4.662411   2.000
44           Andrey Langovich    4.601588   3.000
198            Berat Djimsiti    4.576150   6.000
32                Anton Gaaei    4.481483   7.000
3                  Fali Cande    4.441321   2.500
111                Hauke Wahl    4.424053   1.500
177              Kelvin Amian    4.351051   2.500
14         Jannik Vestergaard    4.263654   2.000
183            Tomas Palacios    4.110915   4.000
57           Flavius Daniliuc    4.086113   2.700
185               Matte Smets    4.018195  13.000
73             Goncalo Inacio    3.976926  45.000
121           Moussa Niakhate    3.969813  15.000
42                Jonas Rouhi    3.857022   2.000
158            Emmanuel Kakou    3.743116   1.000
226               Chico Lamba    3.707399   3.000
129              Joseph Okumu    3.662044   7.000
169        Brendan Chardonnet    3.629795   6.000
91           Mouctar Diakhaby    3.627186   2.000
28      Przemyslaw Frankowski    3.614502   7.000
88                Amos Pieper    3.602000   3.500
131                Diego Rico    3.591378   1.200
50              Jordy Makengo    3.588148   6.000
167              Semm Renders    3.420397   1.500
159               Malang Sarr    3.380531   5.000
52                 Rico Henry    3.362516  15.000
163           Mohammed Salisu    3.335859  12.000
222               Emil Krafth    3.315888   2.000
118                 Mats Rots    3.204659   1.000
95               Armando Izzo    3.141605   1.500
109       Giangiacomo Magnani    3.126172   1.800
205         Francesco Zampano    3.092394   1.000
203               Dinis Pinto    3.091452   1.500
69            Cristian Castro    3.090633   0.800
209             Juan Berrocal    3.064674   1.500
96         Vasilios Zagaritis    3.046333   0.700
170            Inigo Martinez    2.978228   5.000
48            Thierry Correia    2.975759   3.000
202         Tsuyoshi Watanabe    2.949997   9.000
35                 Bamo Meite    2.943192   4.000
225        Jose Maria Gimenez    2.940583  20.000
206              Robert Gumny    2.878088   1.500
116                      Nino    2.712846  11.000
161            Jose Luis Gayà    2.697040   9.000
140                Kenny Lala    2.650659   2.000
49              Marco Komenda    2.630026   0.800
187            German Ignatov    2.606871   0.500
137        Anass Salah-Eddine    2.582766   8.000
105              Craig Dawson    2.576892   1.500
46           Mike Eerdhuijzen    2.524399   2.300
80              Ryan Alebiosu    2.502999   0.500
190             Ibe Hautekiet    2.433319   3.500
55                 Hugo Bueno    2.397553   8.000
22          Milan Majstorovic    2.366266   1.800
119         Godfried Frimpong    2.363765   2.000
13                 Alex Munoz    2.362774   1.000
115            Manuel Lazzari    2.358143   3.500
153              David Hrncar    2.343563   1.200
176           Matija Nastasic    2.338889   0.800
9                 Aiham Ousou    2.272636   2.500
166              Andy Pelmard    2.244973   2.000
79                Ivan Ordets    2.136443   1.000
188         Roberto Fernandez    2.118905   3.500
152        Christian Kabasele    2.092607   0.700
180          Maksim Shnaptsev    2.073064   0.300
130                Marco Sala    2.037277   0.900
196                Jose Gomes    1.961741   1.000
53               Victor Gomez    1.949294   6.000
181               Ahmed Touba    1.934063   2.500
38             Egor Pogostnov    1.892594   1.800
210           Maksim Nenakhov    1.844605   3.000
186             Ricardo Visus    1.843562   0.750
223          Massadio Haidara    1.838910   1.500
218              Manuel Osifo    1.818225   0.700
208             Thomas Beelen    1.774321   8.000
10            Youssouf Sabaly    1.742160   1.800
191                    Moises    1.739486   5.000
75              Ferland Mendy    1.639609  14.000
193            Lucas Calegari    1.596626   3.500
216           Lucas Hernandez    1.592646  25.000
89            Oleksandr Filin    1.564464   1.000
135           Brandon Mechele    1.548365   3.500
41              Shawn Adewoye    1.505297   1.300
62            Duplexe Tchamba    1.504994   1.000
224              Jordan Amavi    1.498784   1.500
194        Jordan Torunarigha    1.469299   4.000
61             Evgeni Morozov    1.466948   3.000
29           Eduardo Quaresma    1.465546  18.000
113              Tiago Esgaio    1.426759   0.900
20                Jonny Evans    1.386931   1.000
128          Jonathan Mutombo    1.384428   0.500
99                    Ben Mee    1.357491   0.700
33               Sergino Dest    1.333587  16.000
40         Mike van der Hoorn    1.326244   1.000
43              Alexis Duarte    1.293685   3.000
217         Toby Alderweireld    1.268787   2.000
127                Juan Jesus    1.257046   1.500
142     Aleksandr Soldatenkov    1.246266   4.000
7            Zineddine Belaid    1.215575   0.800
213                    Orinho    1.169028   0.600
151       Konstantin Savichev    1.080381   0.900
24                Tiago Djalo    1.071281   8.000
76              Boris Popovic    1.055113   1.500
39             Ricardo Mangas    1.047406   2.500
26       Lorenzo De Silvestri    1.044677   0.800
106             Alexander Bah    1.020678  10.000
16            Aleksei Tatayev    0.998514   0.800
175        Jose Luis Palomino    0.996651   0.700
108                Karol Fila    0.994000   0.600
18              Stephen Welsh    0.988080   1.000
112                Glenn Bijl    0.986945   1.500
138          Javier Manquillo    0.979501   1.000
45               Hamza Mendyl    0.967740   1.000
81               Rafael Toloi    0.950609   1.400
178             Marvin Elimbi    0.947016   0.750
68               Ivan Marquez    0.931865   0.600
144           Abdoulaye Bamba    0.923834   0.300
120           Renato Pantalon    0.868149   0.600
71               Eduard Sobol    0.867355   0.900
174                    Michel    0.864340   1.000
199          Mutalip Alibekov    0.861374   0.700
145             Hjalmar Ekdal    0.788894   4.500
146           Thierry Lutonda    0.786811   0.300
70              Igor Yurganov    0.783535   0.500
122   Francisco Reis Ferreira    0.733905   0.700
197               Axel Witsel    0.722397   2.000
6                  Boyd Reith    0.648254   0.400
156            Paulo Oliveira    0.631696   1.000
85          Mathias Jorgensen    0.558937   0.500
162            Wolke Janssens    0.503157   0.400
90      Boli Bolingoli-Mbombo    0.502225   0.500
17            Marvin da Graca    0.472500   0.400
72        Patrick van Aanholt    0.468176   0.500
47            Ruben Fernandes    0.437320   0.050
139       Redouan El Yaakoubi    0.352996   0.550
64               Carlos Ponck    0.349063   0.600
207                Raul Silva    0.270887   0.100
84              Aaron Meijers    0.142091   0.075

In [19]:
comp_leftovers_train[comp_leftovers_train['Player'].str.contains('Diego')]

             Player  Value_pred  Value
577  Diego Llorente    3.908016    6.0
821    Diego Carlos    3.579433    9.5
880           Diego    2.552908    8.0