In [16]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
pd.set_option('display.max_rows', None)

In [26]:
X_train = pd.read_csv('csv/final_datasets/for_linear_model/FW/predictors_train_filtered.csv')
X_test = pd.read_csv('csv/final_datasets/for_linear_model/FW/predictors_test_filtered.csv')
y_train = pd.read_csv('csv/final_datasets/for_linear_model/FW/target_train_filtered_logariphmed.csv')
y_test = pd.read_csv('csv/final_datasets/for_linear_model/FW/target_test_filtered_logariphmed.csv')

In [19]:
train_players = pd.read_csv('csv/final_datasets/for_linear_model/FW/train_players_names.csv')
test_players = pd.read_csv('csv/final_datasets/for_linear_model/FW/test_players_names.csv')

In [27]:
all_cols = X_train.columns
all_cols

Index(['Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
       '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh', 'SoT',
       'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'],
      dtype='object')

<b>Все переменные</b>

In [119]:
LR_regressor = LinearRegression()
LR_regressor.fit(X_train, y_train)

LinearRegression()

In [120]:
y_pred_log = LR_regressor.predict(X_test)
y_pred = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

In [121]:
mae = mean_absolute_error(y_test_original, y_pred)
rmse = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2 = r2_score(y_test_original, y_pred)
mape = mean_absolute_percentage_error(y_test_original, y_pred)

In [122]:
mae

14.311149130874828

In [123]:
rmse

74.6127463691872

In [124]:
r2

-18.122821459211938

In [24]:
coeffs = LR_regressor.coef_[0]
coeffs_df = pd.DataFrame({
    'coeff':coeffs.astype('float')
}, index=X_train.columns)

In [29]:
coeffs_df.sort_values(by='coeff', key=abs, ascending=False)

               coeff
90s        -8.516524
Min         7.941238
G+A-PK     -2.942862
G-PK.1      1.648239
G+A.1       1.099232
Ast.1       0.869921
league_GB1  0.751053
league_IT1  0.465502
Age        -0.433684
SoT/90      0.416301
league_ES1  0.368914
Sh          0.347584
league_L1   0.337282
Gls.1      -0.325070
league_FR1  0.284211
G/Sh        0.255236
G-PK        0.237690
Ast         0.221099
Fld         0.219651
Starts      0.218762
G+A         0.195582
SoT%       -0.194688
PK         -0.187745
Gls         0.158736
MP          0.143963
Fls        -0.140576
Crs         0.118686
Sh/90      -0.099588
CrdY       -0.096447
Off         0.092278
league_PO1 -0.079828
Int         0.057131
TklW       -0.041867
league_NL1  0.034582
CrdR        0.033753
PKatt       0.031446
2CrdY      -0.029109
OG          0.022684
G/SoT      -0.019938
SoT         0.014849
league_RU1 -0.001920

<b>Переменные: Gls, SoT, PK, Ast, Fld, SoT/90, Age, G/Sh, Sh/90, league_ES1, league_FR1,
       league_GB1, league_IT1, league_L1, league_NL1, league_PO1,
       league_RU1</b>

In [28]:
X_train = X_train[['Gls', 'SoT', 'PK', 'Ast', 'Fld', 'SoT/90', 'Age', 'G/Sh', 'Sh/90', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Gls', 'SoT', 'PK', 'Ast', 'Fld', 'SoT/90', 'Age', 'G/Sh', 'Sh/90', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [29]:
LR_regressor = LinearRegression()
LR_regressor.fit(X_train, y_train)

LinearRegression()

In [30]:
y_pred_log = LR_regressor.predict(X_test)
y_pred = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

In [31]:
mae = mean_absolute_error(y_test_original, y_pred)
rmse = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2 = r2_score(y_test_original, y_pred)
mape = mean_absolute_percentage_error(y_test_original, y_pred)

In [32]:
mae

15.187177275966171

In [33]:
rmse

100.79277545042763

In [34]:
r2

-33.89672947679499

In [35]:
mape

0.895061112581898

In [36]:
coeffs = LR_regressor.coef_[0]
coeffs_df = pd.DataFrame({
    'coeff':coeffs.astype('float')
}, index=X_train.columns)

In [37]:
coeffs_df.sort_values(by='coeff', key=abs, ascending=False)

               coeff
league_GB1  2.000275
league_IT1  1.342325
league_ES1  1.064718
league_L1   0.966256
league_FR1  0.840845
Age        -0.443280
Gls         0.407161
league_PO1 -0.379854
Ast         0.358886
league_RU1 -0.231606
SoT         0.203343
Fld         0.153085
SoT/90      0.117109
league_NL1 -0.060025
Sh/90       0.059093
PK         -0.048393
G/Sh        0.009148

In [38]:
y_pred = pd.Series(np.reshape(y_pred, len(y_pred)), name='Value_pred')
pd.concat([test_players, y_pred, y_test_original], axis=1)

                   Player   Value_pred    Value
0         Diederrick Joel     0.327686    0.300
1     Mohamed Lamine Bayo     3.395219    2.800
2             Mirko Maric     1.416277    0.700
3            Mika Biereth    18.129106   30.000
4          Dusan Vlahovic    21.079403   35.000
5          Ibrahima Niane     3.448896    1.000
6             Fabio Silva    17.610008   20.000
7            Oday Dabbagh     0.835723    1.200
8          Andrea Petagna     1.295143    1.000
9        Arsenii Dmitriev     1.100468    0.200
10         Julian Alvarez    26.055396  100.000
11     Georges Mikautadze    21.272972   22.000
12          Donyell Malen     4.380089   25.000
13  Khvicha Kvaratskhelia    44.183184   90.000
14      Lequincio Zeefuik     1.377512    0.850
15   Valentin Castellanos    26.230846   25.000
16           Simon Elisor     0.813610    1.000
17     Rodrigo Ruiz Di­az     0.507355    0.500
18          Borja Mayoral     3.024959    7.500
19    Guilherme Schettine     1.608198    0.900
20            Kyan Vaesen     1.633676    0.700
21        Ange-Yoan Bonny    23.026738   20.000
22         Valentim Sousa     0.797128    0.150
23         Florian Kruger     0.593010    0.500
24         Andres Ferrari     2.544399    1.500
25          Lucas Stassin    50.564951   18.000
26        Nathan N'Goumou     3.887944    4.000
27          Rodrigo Pinho     0.563594    0.250
28          Mark McKenzie     1.617837    6.000
29       Andri Gudjohnsen     1.754352    2.000
30        Henrique Araujo     1.641448    2.000
31           Isaac Mbenza     0.930419    0.800
32                 Miguel     5.503062    2.000
33         Khyzyr Appayev     0.181940    0.125
34               Rochinha     0.326257    1.000
35       Billal Messaoudi     0.694244    0.600
36          Goncalo Ramos    16.878661   40.000
37            Bamba Dieng     2.663690    3.000
38                 Luismi     2.075623    2.000
39        Samuel Mbangula     9.048813   14.000
40         Esteban Lepaul     4.657496    7.000
41                 Wendel     0.778847    1.200
42        Serder Serderov     0.301703    0.350
43              Dan Ndoye    31.355047   35.000
44         Gamid Agalarov     2.831283    1.200
45        Abakar Gadzhiev     1.019747    0.600
46       Casper Tengstedt     5.758977    6.000
47        Folarin Balogun     3.945199   18.000
48         Jacob Ondrejka     9.293264    8.000
49          Maxwel Cornet     2.833901    8.000
50          Ibrahim Sadiq     3.027511    3.500
51        Joel Pohjanpalo     3.353889    4.500
52           Ivan Perisic     2.470201    1.500
53           Alvaro djalo     2.338819    5.000
54      Aleksei Kashtanov     0.649166    0.700
55            Sam Lammers     1.700271    4.000
56         Ion Nicolaescu     1.633351    1.500
57          Cedric Teguia     0.878470    0.800
58          Gabriel Jesus     6.571368   32.000
59           Ross Stewart     3.720534    4.000
60   Charles-Andreas Brym     2.219749    0.450
61      Dmitri Tsypchenko     0.635946    0.500
62             Kaio Cesar     2.191287    5.000
63          Mohamed Salah  1045.731489   50.000
64      Alejandro Marques     1.549722    2.500
65             Umar Sadiq     2.649657    5.000
66         Gabriel Vieira     4.617581    5.000
67           Oh Hyeon-gyu     3.874708    3.500
68             Mathys Tel    20.019745   35.000
69             Diogo Jota    14.730678   40.000
70            Vaclav Sejk     0.944015    0.800
71             Cyle Larin     4.370326    3.500
72     Andreas Skov Olsen     4.658571   14.000
73     Andreas Hountondji     1.264217    2.500
74            Dyego Sousa     0.159534    0.050
75           Raul Jimenez    19.536639    5.000
76              Evanilson    36.943183   35.000
77            Dire Mebude     1.779960    1.000
78         Gustaf Nilsson     5.474315    5.000
79        Niclas Fullkrug     4.940281   10.000
80        Pietro Pellegri     4.116325    2.000
81             Tiago Reis     0.569506    0.400
82                   Kike     4.437326    0.900
83         Robert Bozenik     2.513541    4.000
84           Taylor Booth     0.710270    2.000
85             Dani Gomez     2.343661    1.000
86        Michy Batshuayi     1.346212    4.000
87           Kaj Sierhuis     0.612289    1.300
88         Gorka Guruzeta     5.803942    9.000
89        Marcus Rashford    14.649520   50.000
90         Johan Bakayoko     4.229008   30.000
91         Daishawn Redan     1.267599    0.600
92        Lion Lauberbach     2.074143    1.000
93          Wout Weghorst     1.733128    4.000
94         Saul Guarirapa     1.589982    1.500
95         Hirving Lozano     1.234836   10.000
96       Ruben van Bommel     5.145960    8.000
97    Aleksandr Koksharov     1.393164    0.800
98          Arthur Cabral     0.852098   10.000

In [39]:
y_train_pred = np.exp(LR_regressor.predict(X_train))
y_train_original = np.exp(y_train)

mae = mean_absolute_error(y_train_original, y_train_pred)
rmse = np.sqrt(mean_squared_error(y_train_original, y_train_pred))
mape = mean_absolute_percentage_error(y_train_original, y_train_pred)
r2 = r2_score(y_train_original, y_train_pred)

y_train_pred = pd.Series(np.reshape(y_train_pred, len(y_train_pred)), name='Value_pred')
pd.concat([train_players, y_train_pred, y_train_original], axis=1)

                          Player  Value_pred    Value
0               Giovanni Simeone    2.422333    5.000
1                  Promise David    7.080574   11.000
2             Johannes Eggestein    4.262180    2.500
3                  Armando Broja    5.113618   12.000
4                  Telmo Arcanjo    1.565642    3.000
5                         Madson    1.241263    2.000
6              Riccardo Orsolini   27.408000   25.000
7                Dimitris Rallis    1.564694    0.650
8                  Phillip Tietz    4.844157    5.000
9                Tamerlan Musaev    2.605058    3.500
10                     Luis Diaz   48.866947   70.000
11               Ousmane Dembele   57.270059   90.000
12                Andreas Albers    0.967672    0.300
13                Maroan Sannadi    4.125840   10.000
14                Manfred Ugalde   13.241904   15.000
15                Samuel Essende    5.587543    4.500
16                  Oscar Aranda    5.028616    4.000
17              Leandro Trossard   35.618229   22.000
18             Amine El Ouazzani    1.806037    3.500
19                 Ollie Watkins  104.007942   40.000
20                          Beto   15.202790   22.000
21                  Samuel Obeng    0.366541    0.550
22            Elias Mar Omarsson    1.290857    0.700
23               Roberto Piccoli   18.835717   12.000
24             El Mehdi Maouhoub    1.939740    1.800
25              Andrea Pinamonti   14.127859   15.000
26               Thierry Ambrose    1.869840    0.900
27                  Ilya Sadygov    0.550509    0.100
28                Walid Cheddira    2.595792    2.500
29                 Marcus Thuram   25.234924   75.000
30                  Caleb Ekuban    3.174498    1.300
31              Santiago Gimenez    5.652204   30.000
32                      Max Dean    3.343325    3.500
33                Dango Ouattara   33.255223   28.000
34              Mohammad Mohebbi    1.159645    3.000
35                  Willian Jose    0.269165    1.800
36                     Theo Bair    3.199003    1.800
37                  Keisuke Goto    1.521136    1.200
38              Sayfallah Ltaief    1.356178    1.800
39                Mohamed Nassoh    2.180086    0.700
40               Jarne Steuckers    5.461676   11.000
41              Alvaro Rodriguez    5.271736    2.500
42                  Dylan Nandin    1.306865    0.800
43               Georgi Melkadze    1.122961    0.700
44                   Phil Harres    7.566001    4.000
45              Tobias Lauritsen    4.456759    3.500
46                Gaetan Laborde    6.567137    6.000
47                  Jhon Cordoba    5.798738   12.000
48                         Diego    3.432060    1.500
49               Anton Zabolotny    1.549812    0.700
50                Vladimir Ilyin    0.440217    0.500
51                 Joel Jorquera    0.564661    0.300
52                  Hugo Ekitike   73.183515   75.000
53                Imran Aznaurov    0.911476    0.250
54                  Amine Salama    1.648939    1.500
55                 Kevin Behrens    1.127840    1.000
56                 Anders Dreyer    2.468621    9.000
57                 Thierno Barry   27.347926   20.000
58         Ricky van Wolfswinkel    0.718365    0.400
59                  Ivan Prtajin    1.519791    1.200
60               Atsamaz Revazov    1.964850    0.150
61               Serhou Guirassy   30.662905   45.000
62                 Malick Fofana   12.454186   30.000
63              Shamar Nicholson    0.734449    3.800
64                   Marvin Cuni    0.550974    1.000
65                    Joao Costa    0.708029    0.500
66                Cedric Bakambu    1.895778    1.500
67               Arciom Sumanski    1.766904    0.700
68              Cristhian Stuani    2.545900    1.000
69                       Ze Luis    0.418038    0.100
70           Anastasios Douvikas    8.914158   10.000
71                         Cucho    4.249601   18.000
72                 Oumar Diakite    4.961065    6.000
73                 Sidiki Cherif    3.510517    0.800
74                   Randy Nteka    2.433715    1.500
75                Igor Matanovic    3.825725    5.000
76               Budu Zivzivadze    2.494666    2.000
77                 Camiel Neghli    2.362363    2.000
78                   Wesley Said    1.321459    3.000
79                 Ibrahim Salah    3.003228    3.000
80                   Chico Banza    0.489427    0.800
81                 Bojan Miovski    2.552325    2.500
82                   Andrej Ilic    4.025558    4.000
83               Parfait Guiagon    4.824528    3.000
84                 Junior Ndiaye    2.598413    0.150
85                   Chuba Akpom    1.936988    7.000
86                 Patrik Schick   14.798939   27.000
87                    Ole Romeny    0.900795    1.200
88              Chiedozie Ogbene    2.961127    7.000
89               Adrian Baquerin    4.252818    0.500
90                   Dylan Vente    2.288745    2.000
91               Mikel Oyarzabal    6.049686   25.000
92                      Yira Sor    2.313334    5.000
93                     Abel Ruiz    3.059062    4.000
94              Daniel Karlsbakk    0.752601    2.500
95                 Danny Welbeck   14.478867    5.000
96                  Bruny Nsimba    2.793377    2.000
97                 Jack Harrison    4.930708   14.000
98               Bertug Yildirim    3.183909    2.000
99                 Kasey McAteer    9.472005    2.000
100                  Jader Duran   27.665623   35.000
101             Didier Lamkel Ze    1.012713    0.500
102                   Moise Kean   73.302018   50.000
103                Jeremy Bokila    0.428622    0.100
104               Angel Di Maria    0.856511    2.000
105                    Hugo Duro   11.956193   14.000
106             Couhaib Driouech    1.479439    4.000
107           Benjamin Dominguez   12.602776   15.000
108             Jesper Lindstrom    7.407345   18.000
109                Bryan Linssen    0.482722    0.400
110                 Luuk de Jong    5.263868    2.500
111                Taiwo Awoniyi    5.284905   16.000
112                 Noni Madueke   41.616112   40.000
113                   Liam Delap   58.892525   40.000
114          Mitchell van Bergen    1.800774    1.500
115              Antoine Semenyo   75.633639   40.000
116             Timur Suleimanov    0.703447    1.200
117                  Neal Maupay    3.990912    8.000
118              Oliver McBurnie    5.774252    2.500
119               Franck Honorat    6.081931   12.000
120                Ali Al Hamadi    5.567220    2.500
121                  Rafael Leao   41.234787   70.000
122                 Cyril Ngonge    5.609028    8.000
123               Kasper Dolberg    5.684148   13.000
124                 Ante Budimir   13.879297    5.000
125                 Jacob Murphy   48.147270   16.000
126          Chidozie Obi-Martin   11.505906    5.000
127                 Justin Cuero    1.054004    0.250
128          Michael Gregoritsch    1.554413    3.000
129               Mergim Berisha    2.306617    3.500
130                 Duvan Zapata    2.037034    3.500
131            Alexander Sorloth   25.571811   25.000
132                 Isaac Romero    7.032534    6.000
133               Jonathan David   23.882237   45.000
134                 Troy Parrott    7.116087   14.000
135               Emanuel Emegha   26.282377   25.000
136                  Yoane Wissa   98.605137   32.000
137                 Artem Dzyuba    1.214120    1.500
138                   Makan Aiko    0.919655    0.600
139                   Akor Adams    3.252501    5.000
140                  Julien Ngoy    0.484101    0.400
141              Ivan Timoshenko    0.505000    0.650
142             Lautaro Martinez   23.737317   95.000
143              Ludovic Ajorque    5.984358    4.000
144           Uladzislaŭ Marozaŭ    0.636002    0.250
145                         Nene    0.184483    0.050
146              Santiago Castro   33.650227   35.000
147              Farid El Melali    3.996917    3.500
148               Thijs Dallinga    7.074778   12.000
149               Tomas Cvancara    2.984915    3.000
150                   Yan Lincon    0.947704    0.600
151          Alexandre Lacazette    6.254764    6.000
152           Aurelien Scheidler    3.113806    1.800
153               Alvaro Pascual    3.031189    1.000
154                Nico Williams   14.649866   70.000
155               Samu Omorodion   10.180597   50.000
156  Brynjolfur Darri Willumsson    1.585826    0.700
157                  Ayoze Perez   14.826328   10.000
158             Marko Arnautovic    1.939155    3.000
159            Roberto Fernandez    6.557113    6.000
160              Tim Kleindienst   28.610868   17.000
161                Youssuf Sylla    1.003498    0.600
162                 Vedat Muriqi    4.525027    5.000
163                Son Heung-min   31.075527   20.000
164                Shunsuke Mito    2.195582    0.850
165                Dante Vanzeir    1.191860    5.000
166                 Oliver Burke    2.848058    3.000
167                    Ansu Fati    4.327126    5.000
168                 Meschak Elia    1.426292    4.000
169            Djylian N'Guessan    3.296883    0.800
170              Brennan Johnson   34.948472   40.000
171           Christian Gytkjaer    1.395878    0.700
172               Michiel Kramer    0.345484    0.125
173              Abdoulie Ceesay    2.074825    0.500
174                 Artem Dovbyk   10.866199   30.000
175                 Umaro Embalo    0.860073    0.700
176                   Chris Wood   30.743532   10.000
177              Sergi Guardiola    0.903574    0.500
178                  Daniel Fila    5.027318    3.000
179        Dominic Calvert-Lewin   10.120785   16.000
180                    Noah Ohio    2.167089    2.000
181                Harvey Barnes   28.672574   35.000
182            Kelechi Iheanacho    1.402341    4.500
183                 Ricardo Pepi    5.577862   16.000
184               Andrea Belotti    4.754426    2.000
185                Mateo Retegui  135.703731   45.000
186                Jesus Ramirez    1.051270    1.000
187                   Leroy Sane   15.207394   32.000
188               Marvin Ducksch   11.833600    6.000
189                Alberto Cerri    2.098404    1.000
190                   Harry Kane   69.935733   75.000
191                  Eser Gurbuz    1.971487    0.600
192               Sergio Camello    4.753846    3.000
193                  Andy Delort    0.892058    1.500
194              Jesper Karlsson    2.725517    4.000
195                 Milan Djuric    2.221551    1.500
196                      Clayton    6.721524    5.000
197                Afonso Patrao    1.117924    2.000
198                  Shio Fukuda    4.045167    0.500
199                Evan Ferguson    9.896383   25.000
200              Korede Osundina    0.645493    0.450
201                 Lamine Yamal  285.339633  200.000
202                Toni Martinez    3.481272    2.500
203                Mohamed Meite    4.994180    5.000
204                   Pedro Neto   30.173480   50.000
205        Abdul Fatawu Issahaku   13.352878   11.000
206                  Assane Diao   30.333927   30.000
207                Chidera Ejuke    2.808433    4.000
208                   Ayase Ueda    2.082130    8.000
209              Federico Chiesa    5.824003   14.000
210               Luka Kulenovic    2.895271    1.200
211              Mattia Zaccagni   19.817592   20.000
212             Sebastien Haller    0.935526    3.000
213                  Keita Balde    2.376064    0.900
214           Richonell Margaret    5.559307    0.700
215               Ezequiel Avila    1.978197    2.000
216                   Mika Godts    3.303554   10.000
217            Santiago Pierotti    5.858499    4.000
218                Juanmi Latasa    4.807872    2.000
219                  Ernest Poku    2.538195    4.000
220              Dmitry Vorobyev    3.602598    3.000
221                        Isaac    1.366238    0.700
222                Matija Frigan    6.723460    7.500
223                    Che Adams   11.766986   15.000
224                 Benito Raman    3.303788    2.000
225              Nicolas Jackson   68.317216   50.000
226              Kyogo Furuhashi    0.755071    9.000
227               Yoann Cathline    4.727481    8.000
228                  Alejo Veliz    4.302386    2.500
229                Kirill Glebov    1.576649    1.500
230                Fyodor Smolov    0.345140    1.000
231                 Belajdi Pusi    0.692513    0.350
232                  Florian Aye    1.461199    1.200
233                Gerard Moreno    2.194636    4.000
234         Sydney van Hooijdonk    0.899131    1.000
235        Oskar Siira Sivertsen    0.863740    1.300
236                 Ben Brereton    4.412173    7.500
237                Nikola Stulic    3.903183    4.000
238            Soufiane Benjdida    1.040292    0.500
239               Rasmus Hojlund   13.369508   35.000
240             Benedikt Pichler    2.752302    1.500
241              Noah Weisshaupt    3.368560    5.000
242          Romain Del Castillo    3.796069    7.000
243          Konstantin Tyukavin    2.644815   16.000
244                Brian Brobbey    3.199566   22.000
245                 M'Bala Nzola    3.512803    6.000
246                Tammy Abraham    6.878729   15.000
247                Rodrigo Muniz   28.152139   20.000
248                    David Min    0.988479    0.800
249              Felippe Cardoso    0.816949    0.750
250                Iliman Ndiaye   17.531464   22.000
251                       Safira    0.564229    0.600
252          Kahveh Zahiroleslam    2.403519    0.800
253        Bobby De Cordova-Reid    3.553661    2.500
254                    Daan Rots    4.230589    4.000
255              Ibrahim Sissoko    1.876538    1.800
256                   Andre Ayew    1.241843    0.600
257                Romeo Vermant    4.792176    6.000
258          Gabriel Charpentier    4.804447    1.300
259               Miguel Almiron    3.362179   10.000
260                Dennis Eckert    2.222456    2.500
261                Francis Amuzu    1.360440    4.000
262               Maksim Savelev    0.692066    0.500
263                  Richarlison    8.602257   20.000
264               Alexis Sanchez    0.764407    1.500
265                  Terem Moffi    7.728992   15.000
266                  Raul Blanco    0.529715    0.300
267              Ognjen Ozegovic    0.471100    0.500
268                Finn Stokkers    0.949572    0.450
269              Odsonne Edouard    4.262829    8.000
270                 Darwin Nunez   13.632323   45.000
271             Nicolo Cambiaghi    6.923336    8.500
272               Inaki Williams   12.186432   15.000
273          Christian Rasmussen    1.048291    1.500
274                Kylian Mbappe  190.857621  180.000
275                Samuel Edozie    2.531478    6.000
276               Dodi Lukebakio   15.854111   20.000
277               Borja Iglesias    8.100611    3.000
278              Nelson Oliveira    0.945405    0.350
279                 Mirlind Daku    7.618161    8.000
280             Antonio Sanabria    2.446517    2.800
281              Rodrigo Ribeiro    0.992395    2.500
282                  Nacho Ferri    3.948065    2.200
283    Silvere Ganvoula M'Boussy    1.603728    1.400
284                Sergei Gribov    0.715651    0.250
285        Orri Steinn Oskarsson    4.667112   15.000
286                     Ze Turbo    0.515135    0.450
287              Thom van Bergen    2.798806    1.300
288              Viktor Gyokeres  140.934935   75.000
289                Mayckel Lahdo    1.634396    3.000
290              Michail Antonio    2.401013    0.700
291                Callum Wilson    1.955968    8.000
292              Bertrand Traore    3.136659    8.000
293                Kento Shiogai    2.414390    0.850
294                 Junior Adamu    4.559476    5.000
295               Erling Haaland  139.990162  180.000
296                 Jordan Pefok    2.151745    3.000
297             Mama Samba Balde    2.734731    4.000
298                 Keinan Davis    4.010734    3.400
299                Rafik Guitane    0.848300    4.000
300              Stephy Mavididi    7.533218   10.000
301             Gerson Rodrigues    0.370700    0.600
302                    Deniz Gul    0.754310    4.000
303               Gustav Isaksen   12.538651   20.000
304            Ermedin Demirovic   12.585783   22.000
305                 Jadon Sancho   13.027597   28.000
306              Mostafa Mohamed    3.733348    5.000
307             Asier Villalibre    2.076335    1.200
308                Thiago Vecino    0.439355    0.700
309               Cameron Archer    8.309632   12.000
310                     Noa Lang   12.969678   25.000
311            Randal Kolo Muani   12.455851   30.000
312                Romelu Lukaku   30.451992   22.000
313           Christopher Nkunku   10.344840   35.000
314                 Marcos Andre    2.442587    1.000
315                Mohamed Berte    2.484606    1.200
316      Logan Delaurier-Chaubet    0.853689    0.400
317                   Alerrandro    0.446339    3.500
318                Jorge Aguirre    1.003237    0.600
319            Vangelis Pavlidis   12.803502   35.000
320            Muhammed Badamosi    0.964675    1.000
321              Bojan Radulovic    0.800709    0.800
322                 Steve Ngoura    5.211174    0.800
323                Arnaud Nordin    3.649775    5.000
324               Anton Shamonin    1.378558    0.250
325                 Paul Onuachu    7.281613    6.000
326                Max Moerstedt    3.916171    7.000
327                Jordy Soladio    0.702984    0.350
328               Mohamed Amoura   28.676004   32.000
329                 Fran Navarro    0.640996    6.000
330              Antoine Bernier    1.515730    1.500
331            Jonathan Burkardt   19.428902   35.000
332                William Osula    8.625578    7.000
333               Alexander Isak  168.371530  120.000
334               Yegor Golenkov    1.671631    2.500
335                  David Neres    4.781477   30.000
336             Marwan Al Sahafi    2.318729    1.000
337              Alessio da Cruz    1.049913    0.600
338         Jorgen Strand Larsen   56.524216   30.000
339               Matthis Abline   14.101892   18.000
340                    Amin Sarr    5.231222    5.000
341             Gustavo da Silva    1.154180    3.000
342           Robert Lewandowski   21.695617   12.000
343              Nikola Krstovic   45.726540   15.000
344                        Pablo    1.672933    0.800
345             Mateo Pellegrino    6.221397    6.000
346              Daniel Jebbison   11.352337    4.000
347                 Karol Czubak    0.874868    0.600
348              Mikkel Kaufmann    2.146716    1.200
349              Youssouph Badji    1.825046    1.000
350               Mario Gonzalez    0.547114    1.200
351              Bradley Barcola   80.171540   70.000
352                     Cassiano    0.656943    0.200
353                         Koka    1.548308    0.800
354                       Tomane    0.461605    0.200
355                Hafiz Ibrahim    2.862307    0.500
356                Jim Allevinah    2.225750    1.500
357                 Kevin Denkey    3.674937   14.000
358               Tolu Arokodare   23.924561   18.000
359              Victor Boniface    8.077656   40.000
360               Tyrique George   11.118254   10.000
361                 Bryan Mbeumo  161.848362   55.000
362               Yevgeni Markov    0.660743    0.600
363              Daniel Mosquera    7.618163    1.500
364            Andre Lacximicant    2.149884    1.000
365                   Pau Victor    5.818670    4.000
366                  Jamie Vardy    8.529135    1.000
367                Adrian Butzke    0.622349    0.300
368            Goduine Koyalipou    3.730082    2.500

In [40]:
mape

0.8504881206636142