In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_rows', None)

In [98]:
X_train = pd.read_csv('../../../data/processed/for_linear_model/DF,MF/predictors_train_filtered.csv')
X_test = pd.read_csv('../../../data/processed/for_linear_model/DF,MF/predictors_test_filtered.csv')
y_train = pd.read_csv('../../../data/processed/for_linear_model/DF,MF/target_train_filtered_logariphmed.csv')
y_test = pd.read_csv('../../../data/processed/for_linear_model/DF,MF/target_test_filtered_logariphmed.csv')

In [4]:
train_players = pd.read_csv('../../../data/processed/for_linear_model/DF,MF/train_players_names.csv')
test_players = pd.read_csv('../../../data/processed/for_linear_model/DF,MF/test_players_names.csv')

In [6]:
all_cols = X_train.columns
all_cols

Index(['Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
       '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh', 'SoT',
       'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'],
      dtype='object')

## Регрессор

In [104]:
LR_regressor = LinearRegression()
LR_regressor.fit(X_train, y_train)

LinearRegression()

## Предсказанные значения

In [105]:
y_pred_log = LR_regressor.predict(X_test)
y_pred = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

y_train_pred = np.exp(LR_regressor.predict(X_train))
y_train_original = np.exp(y_train)

## Метрики

In [106]:
mae_test = mean_absolute_error(y_test_original, y_pred)
rmse_test = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2_test = r2_score(y_test_original, y_pred)
mape_test = mean_absolute_percentage_error(y_test_original, y_pred)

mae_train = mean_absolute_error(y_train_original, y_train_pred)
rmse_train = np.sqrt(mean_squared_error(y_train_original, y_train_pred))
r2_train = r2_score(y_train_original, y_train_pred)
mape_train = mean_absolute_percentage_error(y_train_original, y_train_pred)

metrics = pd.DataFrame({
    'MAE':[mae_test, mae_train],
    'RMSE':[rmse_test, rmse_train],
    'MAPE':[mape_test, mape_train],
    'R2':[r2_test, r2_train]
}, index = ['test', 'train'])

## Остатки

In [107]:
y_pred = pd.Series(np.reshape(y_pred, len(y_pred)), name='Value_pred')
y_train_pred = pd.Series(np.reshape(y_train_pred, len(y_train_pred)), name='Value_pred')

comp_leftovers_test = pd.concat([test_players, y_pred, y_test_original], axis=1)
comp_leftovers_train = pd.concat([train_players, y_train_pred, y_train_original], axis=1)

## Коэффициенты

In [108]:
coeffs = LR_regressor.coef_[0]
coeffs_df = pd.DataFrame({
    'coeff':coeffs.astype('float')
}, index=X_train.columns)
coeffs_df = coeffs_df.sort_values(by='coeff', key=abs, ascending=False)

# Все переменные

In [13]:
coeffs_df

               coeff
Min         8.684038
90s        -6.710016
league_GB1  0.775071
Starts     -0.763686
Ast.1       0.541095
MP         -0.534376
SoT         0.513828
Sh         -0.373773
Age        -0.350489
G+A-PK     -0.332881
league_IT1  0.326938
G-PK.1      0.316915
league_L1   0.316761
league_ES1  0.300641
league_FR1  0.287510
Sh/90       0.215894
G/Sh        0.213663
G+A.1      -0.195559
PK          0.105059
league_NL1  0.097042
CrdY       -0.090386
Fls        -0.084570
Crs        -0.076650
SoT/90     -0.075147
Int        -0.071030
OG          0.070165
SoT%       -0.053695
CrdR        0.049747
TklW        0.038182
G-PK       -0.029477
Fld        -0.027268
2CrdY      -0.016511
PKatt      -0.014430
league_PO1  0.012905
G+A        -0.011131
Ast        -0.010776
league_RU1  0.009602
Gls        -0.006897
G/SoT       0.003250
Off         0.003082
Gls.1      -0.002496

In [14]:
metrics

            MAE       RMSE      MAPE        R2
test   6.413018  13.968448  2.493828  0.172109
train  2.504211   4.562421  0.708134  0.641897

In [15]:
comp_leftovers_train

                        Player  Value_pred  Value
0               Claudio Falcao    1.466037   0.80
1               Josha Vagnoman    6.367078  10.00
2           Samuele Birindelli    7.460604   2.80
3    Fernando Ferreira Fonseca    0.818566   0.50
4              Jairo Riedewald    0.828498   1.80
5           Jackson Tchatchoua   15.504043   8.00
6                  Reece James   15.548355  30.00
7              Ismael Doukoure   14.895639  18.00
8                 Mauro Junior    4.745205  12.00
9           Miroslav Bogosavac    0.611272   1.00
10               Juan Cuadrado    0.854114   1.00
11              Jakub Kaminski    3.350566   5.00
12                Amadou Dante    1.026945   1.50
13                  Allan Nyom    0.916972   0.30
14               Diego Moreira   14.939713  18.00
15        Siebe Van Der Heyden    1.905006   2.50
16          Jean-Kevin Duverne    1.238428   2.50
17               Goncalo Costa    0.991679   0.50
18                 Lars Ritzka    1.338346   1.00
19               Darko Lazovic    1.962726   0.80
20                 Nhoa Sangui    2.636285   2.50
21                Louis Patris    1.465939   2.00
22                Renato Veiga    8.216042  25.00
23                Tiago Araujo    1.107556   1.30
24              Bart Nieuwkoop    0.808134   2.00
25               Honest Ahanor    4.226760   5.00
26               Stefan Dzodic    2.679356   0.20
27                 Wagner Pina    3.903257   5.00
28                Ihor Kalinin    0.549162   0.70
29             Aleksandr Ektov    1.452188   0.80
30                 Noah Fadiga    1.777280   3.00
31            Julian Lelieveld    1.917620   0.50
32               Juan Castillo    0.969634   0.50
33                 Gary Magnee    1.029359   1.50
34         Oleksandr Zinchenko    8.575476  20.00
35            Rafael Rodrigues    0.859380   0.80
36              Deiver Machado    2.003414   3.00
37             Nikita Kakkoyev    2.855804   1.20
38                   Gijs Smal    1.507744   7.00
39               Thomas Keller    1.179527   0.50
40                 Ilya Agapov    0.783585   1.00
41                 John Tolkin    2.518188   2.50
42              Niels Nkounkou    1.351904   3.50
43    Jean-Charles Castelletto    7.570761   3.50
44                       Djene    1.896830   1.80
45              James Abankwah    2.569325   1.00
46               Fabio Ferraro    4.384854   1.30
47               Marco Weymans    0.623385   0.30
48              Felix Passlack    3.233969   2.00
49                 Colin Dagba    1.018029   0.70
50             Alexandro Calut    0.633604   0.40
51         Nikolas Veratschnig    2.012158   1.50
52              Lamare Bogarde   11.741327   6.00
53             Adrien Truffert   16.945483  15.00
54                 Archie Gray   32.258131  38.00
55            Killian Sardella    3.516022   5.00
56                 Samuel Dahl    8.166906   7.00
57              Ferdi Kadioglu   16.471046  25.00
58            Dominik Javorcek    1.896834   0.55
59             Diogo Travassos    1.870768   1.50
60             Goncalo Almeida    0.841187   0.25
61             Marcos Llorente    8.401227  25.00
62                Mats Wieffer   13.440486  25.00
63               Dario Grujcic    0.806754   0.25
64                David Pastor    1.798954   1.00
65            Fode Ballo-Toure    0.941047   1.20
66          Geoffrey Kondogbia    2.462833   7.00
67               Simion Michez    2.309539   1.50
68                Dominik Kohr    2.486278   3.50
69                  Eric Smith    7.834507   5.00
70             Mitchell Weiser   11.926546   5.00
71                 Melvin Bard    8.311126  15.00
72                Paulo Victor    0.957146   0.80
73                  Ridle Baku    6.334045   9.00
74                Marnon Busch    1.735105   1.20
75                 Rui Modesto    1.498527   2.00
76              Mihailo Ristic    1.268830   0.90
77               Vanja Drkusic    0.709339   4.00
78               Ivan Fresneda    2.490166   8.00
79             Kirill Bozhenov    0.524893   0.35
80            Bruno Onyemaechi    2.133613   2.70
81             Gonzalo Montiel    1.251048   5.00
82                 Ryoya Ogawa    1.968216   1.50
83                 Caleb Wiley    2.760279   8.00
84                 Tom Pouilly    2.205677   0.80
85                   Ken Nkuba    0.934837   2.70
86            Miguel Gutierrez   10.652235  20.00
87                Lucas Fasson    1.108331   3.00
88                 Eray Comert    2.285064   2.00
89                 Aron Donnum    5.181154   4.00
90                        Tuta    6.289811  15.00
91             Nicola Zalewski    2.830650  12.00
92                 John Stones   28.590896  25.00
93               Andres Garcia   11.888949   7.00
94                      Derick    1.151524   0.30
95            Joao Mario Lopes    1.110269  10.00
96                 Alex Moreno    6.408116   7.00
97             Petar Golubovic    0.453071   0.35
98         Aleksandr Kutitskiy    2.477444   1.80
99           Samuel Amo-Ameyaw    6.186042   4.00
100     Christian Neiva Afonso    0.396112   0.50
101                Robert Skov    2.836543   4.00
102               Ilia Rozhkov    3.440295   2.50
103             Warren Kamanzi    1.821933   2.00
104                Zeno Debast    3.088087  30.00
105        Christopher Trimmel    0.880697   0.60
106             Syb Van Ottele    2.347738   1.00
107                         MT    2.649176   5.00
108              Jaydee Canvot    3.057240   4.00
109           Jailson Siqueira    1.997276   1.00
110        Stephan El Shaarawy    3.029645   3.50
111                 Hugo Novoa    2.671047   1.50
112                 Eric Veiga    0.357634   0.20
113              Ruben Aguilar    1.504000   3.50
114             Arnau Martinez   13.574912  10.00
115               Ryan Manning    7.143154   3.00
116            Frederic Ananou    0.525719   0.40
117                   Ali Abdi    2.455365   3.00
118                  Joao Tome    0.695157   0.60
119                  Tom Rothe    9.333844  10.00
120            Patrick Pflucke    2.648023   1.60
121               Yuri Ribeiro    0.414488   1.20
122            Ruslan Bezrukov    2.013105   1.00
123            Alfonso Pedraza    2.228627   2.50
124               Pedro Amaral    1.952521   1.00
125          Jerome Roussillon    0.883538   0.80
126             Pedro Carvalho    0.944333   0.40
127          Mikael Ellertsson    7.152877   3.40
128           Bjarki Bjarkason    1.090835   0.80
129                   Emre Can    5.097023   7.00
130                 Rico Lewis   40.967317  40.00
131                Tom Louchet    2.213251   2.50
132            Josip Juranovic    1.512598   4.00
133            Marious Vrousai    3.658214   2.00
134            Darko Todorovic    1.000000   1.00
135                 Mory Gbane    4.065974   4.00
136             Fabiano Parisi    3.062765   6.00
137            Gustavo Mantuan    2.292610   3.50
138          Yukinari Sugawara   19.400449  11.00
139           Pawel Dawidowicz    1.444799   2.50

In [16]:
comp_leftovers_test

                 Player  Value_pred  Value
0        Danil Stepanov    0.561864   0.60
1           Eric Garcia    7.871803  18.00
2        Leandro Bacuna   14.795869   0.30
3       Ridwane M'Barki    0.251768   0.25
4         Nicolas Cozza    6.160999   3.50
5     Nikolai Rasskazov    1.412038   1.50
6     Raphael Guerreiro    5.609009   8.00
7         Nilton Varela    1.718796   1.50
8   Filippo Terracciano    1.799802   3.20
9        Julius Dirksen    1.722087   0.40
10        Kobe Corbanie    1.297051   1.70
11                Moura    6.840187  15.00
12           Max Aarons    1.314296   6.00
13     Jeremie Frimpong   17.721830  50.00
14       Danila Prokhin    4.621109   1.50
15         Nadir Zortea    8.893086   5.00
16     Jeanuel Belocian    1.419592  15.00
17      Nathaniel Clyne    3.586466   1.00
18       Dmitri Kabutov    0.710480   0.80
19      Nathaniel Brown   10.347449  22.00
20       Mateo Stamatov    0.813355   0.50
21      Jonathan Clauss    2.799379   5.00
22      Lorenz Assignon    3.028765   9.00
23              Rivaldo    1.176507   0.20
24          Tomas Silva    1.215929   0.10
25   Maximiliano Araujo    2.021041  17.00
26        Adam Dzwigala    1.053799   0.60
27      Jhoanner Chavez    2.830913   3.50
28        Matheus Nunes   22.798245  35.00
29  Aurelien Tchouameni    5.926430  75.00
30          Daam Foulon    3.263131   2.50
31          Finn Porath    5.637794   1.70
32       Josip Mitrovic    1.198806   0.50
33           Ali Maamar    0.915891   2.00
34    Daniil Khlusevich    0.953171   3.50
35      Fernando Calero    2.188382   1.50

# Потенциальные переменные для добавления и удаления

## Текущие столбцы

In [97]:
base_cols = ['Age', '90s', 'Gls', 'Ast', 'G+A',
       '2CrdY', 'G+A.1', 'G-PK.1',
       'Crs', 'Int',
       'SoT%', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']

## Для добавления:

In [99]:
cols_to_add = [col for col in all_cols if not(col in base_cols)]
new_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_add:
    X_train_new = X_train[base_cols + [col]]
    X_test_new = X_test[base_cols + [col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new<mae_test or mape_new<mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=new_cols.columns, index=[col])
        new_cols = pd.concat([new_cols, row])
new_cols

             mae      mape        r2
base    5.168998  1.080572  0.228252
Starts  5.157480  1.197914 -3.239179

## Для удаления:

In [100]:
cols_to_delete = [col for col in base_cols if not(col.startswith('league'))]
del_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_delete:
    X_train_new = X_train[[c for c in base_cols if c != col]]
    X_test_new = X_test[[c for c in base_cols if c != col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new < mae_test or mape_new < mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=del_cols.columns, index=[col])
        del_cols = pd.concat([del_cols, row])
del_cols

             mae      mape        r2
base    5.168998  1.080572  0.228252
Gls     5.168998  1.196868 -3.243716
Ast     5.168998  1.196868 -3.243716
G+A     5.168998  1.196868 -3.243716
G-PK.1  5.167895  1.196433 -3.268970

# Модель 1

In [25]:
X_train = X_train[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdR', 'Gls.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
        'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW',
       'SoT%', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdR', 'Gls.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
        'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW',
       'SoT%', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [31]:
coeffs_df

               coeff
league_GB1  0.696683
90s         0.666750
G+A-PK     -0.621583
G+A.1       0.535955
Age        -0.367677
league_L1   0.263304
G/Sh        0.262555
league_ES1  0.260256
league_FR1  0.252451
league_IT1  0.229571
Fls        -0.186827
SoT/90      0.175694
Gls.1      -0.139598
Crs        -0.117438
Ast         0.117415
G/SoT      -0.104106
G+A         0.095949
G-PK.1      0.088159
PK          0.062908
Fld        -0.056401
Off         0.052489
PKatt      -0.045500
league_NL1  0.039524
league_PO1 -0.034811
TklW       -0.031394
league_RU1 -0.031155
Gls         0.024547
CrdR        0.016203
G-PK        0.012338
SoT%        0.004366
Int         0.003201

In [32]:
metrics

            MAE       RMSE      MAPE        R2
test   5.583333  13.414909  1.320670  0.236424
train  2.780889   5.064896  0.752939  0.558675

# Модель 2

In [37]:
X_train = X_train[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', '2CrdY', 'CrdR', 'Gls.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
       'Fld', 'Off', 'Crs', 'Int', 'TklW',
       'SoT%', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', '2CrdY', 'CrdR', 'Gls.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
       'Fld', 'Off', 'Crs', 'Int', 'TklW',
       'SoT%', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [43]:
coeffs_df

               coeff
league_GB1  0.676696
90s         0.539723
G+A-PK     -0.522506
G+A.1       0.428700
Age        -0.387808
league_FR1  0.253876
league_ES1  0.252338
league_L1   0.248153
league_IT1  0.230948
G/Sh        0.208503
Ast         0.151337
G/SoT      -0.126778
G+A         0.118565
PK          0.099109
SoT%        0.088666
Crs        -0.087640
PKatt      -0.080852
TklW       -0.075545
league_PO1 -0.075390
Fld        -0.066436
Off         0.062844
Gls.1       0.049087
league_RU1 -0.041699
league_NL1  0.039254
G-PK.1      0.024854
2CrdY      -0.024250
Gls         0.021448
Int        -0.010259
CrdR        0.007439
G-PK        0.001426

In [44]:
metrics

            MAE       RMSE      MAPE        R2
test   5.294987  13.486479  1.113241  0.228255
train  2.824135   5.152226  0.767549  0.543325

In [46]:
comp_leftovers_train

                        Player  Value_pred  Value
0               Claudio Falcao    1.615323   0.80
1               Josha Vagnoman    4.861826  10.00
2           Samuele Birindelli    5.296176   2.80
3    Fernando Ferreira Fonseca    0.865093   0.50
4              Jairo Riedewald    0.733491   1.80
5           Jackson Tchatchoua   16.180793   8.00
6                  Reece James   13.595550  30.00
7              Ismael Doukoure   11.039145  18.00
8                 Mauro Junior    3.795261  12.00
9           Miroslav Bogosavac    0.637725   1.00
10               Juan Cuadrado    0.599540   1.00
11              Jakub Kaminski    3.116623   5.00
12                Amadou Dante    0.982079   1.50
13                  Allan Nyom    1.118807   0.30
14               Diego Moreira   19.979847  18.00
15        Siebe Van Der Heyden    2.286872   2.50
16          Jean-Kevin Duverne    1.229459   2.50
17               Goncalo Costa    1.242546   0.50
18                 Lars Ritzka    1.237203   1.00
19               Darko Lazovic    2.712846   0.80
20                 Nhoa Sangui    4.872005   2.50
21                Louis Patris    1.824501   2.00
22                Renato Veiga    4.998487  25.00
23                Tiago Araujo    0.829909   1.30
24              Bart Nieuwkoop    0.867141   2.00
25               Honest Ahanor    3.471514   5.00
26               Stefan Dzodic    2.289072   0.20
27                 Wagner Pina    4.960037   5.00
28                Ihor Kalinin    0.662219   0.70
29             Aleksandr Ektov    1.365627   0.80
30                 Noah Fadiga    1.657418   3.00
31            Julian Lelieveld    1.752687   0.50
32               Juan Castillo    0.994547   0.50
33                 Gary Magnee    1.429342   1.50
34         Oleksandr Zinchenko    6.890544  20.00
35            Rafael Rodrigues    1.203160   0.80
36              Deiver Machado    2.840456   3.00
37             Nikita Kakkoyev    1.852854   1.20
38                   Gijs Smal    1.616418   7.00
39               Thomas Keller    1.196605   0.50
40                 Ilya Agapov    0.695105   1.00
41                 John Tolkin    2.063337   2.50
42              Niels Nkounkou    1.442450   3.50
43    Jean-Charles Castelletto    4.002628   3.50
44                       Djene    2.878170   1.80
45              James Abankwah    1.918690   1.00
46               Fabio Ferraro    3.814217   1.30
47               Marco Weymans    0.769368   0.30
48              Felix Passlack    6.599513   2.00
49                 Colin Dagba    1.222648   0.70
50             Alexandro Calut    0.816240   0.40
51         Nikolas Veratschnig    2.202745   1.50
52              Lamare Bogarde   17.992509   6.00
53             Adrien Truffert    9.843194  15.00
54                 Archie Gray   47.765883  38.00
55            Killian Sardella    2.179268   5.00
56                 Samuel Dahl    1.344575   7.00
57              Ferdi Kadioglu    9.171728  25.00
58            Dominik Javorcek    1.755400   0.55
59             Diogo Travassos    1.692075   1.50
60             Goncalo Almeida    1.226725   0.25
61             Marcos Llorente    6.899144  25.00
62                Mats Wieffer   17.388523  25.00
63               Dario Grujcic    0.785369   0.25
64                David Pastor    1.971448   1.00
65            Fode Ballo-Toure    1.132724   1.20
66          Geoffrey Kondogbia    1.848367   7.00
67               Simion Michez    1.742288   1.50
68                Dominik Kohr    2.683080   3.50
69                  Eric Smith    5.265722   5.00
70             Mitchell Weiser   10.497765   5.00
71                 Melvin Bard    4.596040  15.00
72                Paulo Victor    1.036240   0.80
73                  Ridle Baku    8.326802   9.00
74                Marnon Busch    1.683989   1.20
75                 Rui Modesto    2.245121   2.00
76              Mihailo Ristic    1.208806   0.90
77               Vanja Drkusic    0.671283   4.00
78               Ivan Fresneda    2.819607   8.00
79             Kirill Bozhenov    0.795141   0.35
80            Bruno Onyemaechi    1.514820   2.70
81             Gonzalo Montiel    1.163256   5.00
82                 Ryoya Ogawa    2.514204   1.50
83                 Caleb Wiley    2.036928   8.00
84                 Tom Pouilly    2.134570   0.80
85                   Ken Nkuba    0.945267   2.70
86            Miguel Gutierrez   11.813106  20.00
87                Lucas Fasson    1.018786   3.00
88                 Eray Comert    3.437957   2.00
89                 Aron Donnum    4.473981   4.00
90                        Tuta    6.343015  15.00
91             Nicola Zalewski    2.892678  12.00
92                 John Stones   30.386713  25.00
93               Andres Garcia   10.021614   7.00
94                      Derick    0.887559   0.30
95            Joao Mario Lopes    1.519357  10.00
96                 Alex Moreno    5.529556   7.00
97             Petar Golubovic    0.499259   0.35
98         Aleksandr Kutitskiy    2.008034   1.80
99           Samuel Amo-Ameyaw    6.069439   4.00
100     Christian Neiva Afonso    0.528816   0.50
101                Robert Skov    2.683466   4.00
102               Ilia Rozhkov    3.824534   2.50
103             Warren Kamanzi    3.526762   2.00
104                Zeno Debast    3.208958  30.00
105        Christopher Trimmel    1.084944   0.60
106             Syb Van Ottele    2.867846   1.00
107                         MT    2.573780   5.00
108              Jaydee Canvot    4.463724   4.00
109           Jailson Siqueira    1.682582   1.00
110        Stephan El Shaarawy    2.823532   3.50
111                 Hugo Novoa    2.384854   1.50
112                 Eric Veiga    0.655868   0.20
113              Ruben Aguilar    1.635418   3.50
114             Arnau Martinez   12.435569  10.00
115               Ryan Manning    8.286326   3.00
116            Frederic Ananou    0.545163   0.40
117                   Ali Abdi    3.168564   3.00
118                  Joao Tome    0.901494   0.60
119                  Tom Rothe    9.616040  10.00
120            Patrick Pflucke    2.398248   1.60
121               Yuri Ribeiro    0.459054   1.20
122            Ruslan Bezrukov    2.347479   1.00
123            Alfonso Pedraza    1.439364   2.50
124               Pedro Amaral    1.923915   1.00
125          Jerome Roussillon    0.606279   0.80
126             Pedro Carvalho    1.027335   0.40
127          Mikael Ellertsson    8.336372   3.40
128           Bjarki Bjarkason    1.294300   0.80
129                   Emre Can    4.834906   7.00
130                 Rico Lewis   33.617712  40.00
131                Tom Louchet    2.709764   2.50
132            Josip Juranovic    1.630242   4.00
133            Marious Vrousai    2.180635   2.00
134            Darko Todorovic    1.000000   1.00
135                 Mory Gbane    3.305155   4.00
136             Fabiano Parisi    3.809982   6.00
137            Gustavo Mantuan    2.151507   3.50
138          Yukinari Sugawara   22.954120  11.00
139           Pawel Dawidowicz    2.194583   2.50

In [47]:
comp_leftovers_test

                 Player  Value_pred  Value
0        Danil Stepanov    0.673700   0.60
1           Eric Garcia    8.439097  18.00
2        Leandro Bacuna    3.408636   0.30
3       Ridwane M'Barki    0.318025   0.25
4         Nicolas Cozza    4.191708   3.50
5     Nikolai Rasskazov    1.932328   1.50
6     Raphael Guerreiro    4.322365   8.00
7         Nilton Varela    1.873128   1.50
8   Filippo Terracciano    2.597621   3.20
9        Julius Dirksen    1.197083   0.40
10        Kobe Corbanie    2.176273   1.70
11                Moura   14.555662  15.00
12           Max Aarons    1.582148   6.00
13     Jeremie Frimpong   16.022203  50.00
14       Danila Prokhin    1.985850   1.50
15         Nadir Zortea   10.100398   5.00
16     Jeanuel Belocian    1.905692  15.00
17      Nathaniel Clyne    3.464539   1.00
18       Dmitri Kabutov    0.960568   0.80
19      Nathaniel Brown    9.697946  22.00
20       Mateo Stamatov    0.825020   0.50
21      Jonathan Clauss    5.089668   5.00
22      Lorenz Assignon    8.489094   9.00
23              Rivaldo    0.597574   0.20
24          Tomas Silva    0.902783   0.10
25   Maximiliano Araujo    2.557069  17.00
26        Adam Dzwigala    0.932117   0.60
27      Jhoanner Chavez    3.380264   3.50
28        Matheus Nunes   40.563215  35.00
29  Aurelien Tchouameni    6.826946  75.00
30          Daam Foulon    2.508383   2.50
31          Finn Porath    3.563262   1.70
32       Josip Mitrovic    1.438161   0.50
33           Ali Maamar    1.104041   2.00
34    Daniil Khlusevich    0.906409   3.50
35      Fernando Calero    2.753673   1.50

# Модель 3

In [52]:
X_train = X_train[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', '2CrdY', 'CrdR', 'G+A.1', 'G-PK.1', 'G+A-PK',
       'Fld', 'Off', 'Crs', 'Int', 'TklW',
       'SoT%', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', '2CrdY', 'CrdR', 'G+A.1', 'G-PK.1', 'G+A-PK',
       'Fld', 'Off', 'Crs', 'Int', 'TklW',
       'SoT%', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [58]:
coeffs_df

               coeff
league_GB1  0.674901
G+A-PK     -0.605878
90s         0.532636
G+A.1       0.511992
Age        -0.388645
league_FR1  0.255534
league_ES1  0.251850
league_L1   0.246298
league_IT1  0.229492
G/Sh        0.214313
Ast         0.149031
G/SoT      -0.127246
G+A         0.119782
PK          0.094357
SoT%        0.091199
Crs        -0.086036
PKatt      -0.078080
league_PO1 -0.076428
TklW       -0.074811
Fld        -0.067219
Off         0.061819
G-PK.1      0.055361
league_RU1 -0.043428
league_NL1  0.039110
Gls         0.027159
2CrdY      -0.023466
Int        -0.008886
G-PK        0.008405
CrdR        0.006557

In [59]:
metrics

            MAE       RMSE      MAPE        R2
test   5.276381  13.471834  1.123086  0.229930
train  2.827389   5.162423  0.768464  0.541516

In [60]:
comp_leftovers_train

                        Player  Value_pred  Value
0               Claudio Falcao    1.607933   0.80
1               Josha Vagnoman    4.868975  10.00
2           Samuele Birindelli    5.371044   2.80
3    Fernando Ferreira Fonseca    0.864382   0.50
4              Jairo Riedewald    0.738891   1.80
5           Jackson Tchatchoua   16.070223   8.00
6                  Reece James   13.594247  30.00
7              Ismael Doukoure   11.234434  18.00
8                 Mauro Junior    3.756748  12.00
9           Miroslav Bogosavac    0.639687   1.00
10               Juan Cuadrado    0.596220   1.00
11              Jakub Kaminski    3.106059   5.00
12                Amadou Dante    0.985968   1.50
13                  Allan Nyom    1.117577   0.30
14               Diego Moreira   20.092922  18.00
15        Siebe Van Der Heyden    2.249606   2.50
16          Jean-Kevin Duverne    1.168803   2.50
17               Goncalo Costa    1.239285   0.50
18                 Lars Ritzka    1.236074   1.00
19               Darko Lazovic    2.697705   0.80
20                 Nhoa Sangui    4.884266   2.50
21                Louis Patris    1.824663   2.00
22                Renato Veiga    4.995041  25.00
23                Tiago Araujo    0.835149   1.30
24              Bart Nieuwkoop    0.878492   2.00
25               Honest Ahanor    3.497464   5.00
26               Stefan Dzodic    2.315107   0.20
27                 Wagner Pina    4.949850   5.00
28                Ihor Kalinin    0.659241   0.70
29             Aleksandr Ektov    1.363141   0.80
30                 Noah Fadiga    1.645984   3.00
31            Julian Lelieveld    1.744822   0.50
32               Juan Castillo    1.002454   0.50
33                 Gary Magnee    1.428922   1.50
34         Oleksandr Zinchenko    6.852936  20.00
35            Rafael Rodrigues    1.214561   0.80
36              Deiver Machado    2.833814   3.00
37             Nikita Kakkoyev    1.832723   1.20
38                   Gijs Smal    1.614672   7.00
39               Thomas Keller    1.200523   0.50
40                 Ilya Agapov    0.693139   1.00
41                 John Tolkin    2.053809   2.50
42              Niels Nkounkou    1.447226   3.50
43    Jean-Charles Castelletto    3.982783   3.50
44                       Djene    2.830707   1.80
45              James Abankwah    1.927039   1.00
46               Fabio Ferraro    3.815282   1.30
47               Marco Weymans    0.773955   0.30
48              Felix Passlack    6.531712   2.00
49                 Colin Dagba    1.228074   0.70
50             Alexandro Calut    0.823983   0.40
51         Nikolas Veratschnig    2.205907   1.50
52              Lamare Bogarde   18.185501   6.00
53             Adrien Truffert    9.998743  15.00
54                 Archie Gray   47.897840  38.00
55            Killian Sardella    2.181930   5.00
56                 Samuel Dahl    1.347354   7.00
57              Ferdi Kadioglu    9.051923  25.00
58            Dominik Javorcek    1.743879   0.55
59             Diogo Travassos    1.700757   1.50
60             Goncalo Almeida    1.229059   0.25
61             Marcos Llorente    6.913199  25.00
62                Mats Wieffer   17.342100  25.00
63               Dario Grujcic    0.790867   0.25
64                David Pastor    1.949970   1.00
65            Fode Ballo-Toure    1.143153   1.20
66          Geoffrey Kondogbia    1.847127   7.00
67               Simion Michez    1.730069   1.50
68                Dominik Kohr    2.700878   3.50
69                  Eric Smith    5.248306   5.00
70             Mitchell Weiser   10.638420   5.00
71                 Melvin Bard    4.673036  15.00
72                Paulo Victor    1.037371   0.80
73                  Ridle Baku    8.416735   9.00
74                Marnon Busch    1.676918   1.20
75                 Rui Modesto    2.257163   2.00
76              Mihailo Ristic    1.208698   0.90
77               Vanja Drkusic    0.670953   4.00
78               Ivan Fresneda    2.854930   8.00
79             Kirill Bozhenov    0.793557   0.35
80            Bruno Onyemaechi    1.531123   2.70
81             Gonzalo Montiel    1.170362   5.00
82                 Ryoya Ogawa    2.537190   1.50
83                 Caleb Wiley    2.052711   8.00
84                 Tom Pouilly    2.173314   0.80
85                   Ken Nkuba    0.952782   2.70
86            Miguel Gutierrez   11.735278  20.00
87                Lucas Fasson    1.018018   3.00
88                 Eray Comert    3.420696   2.00
89                 Aron Donnum    4.530761   4.00
90                        Tuta    6.411568  15.00
91             Nicola Zalewski    2.892264  12.00
92                 John Stones   31.127103  25.00
93               Andres Garcia   10.040383   7.00
94                      Derick    0.887687   0.30
95            Joao Mario Lopes    1.506386  10.00
96                 Alex Moreno    5.496353   7.00
97             Petar Golubovic    0.497697   0.35
98         Aleksandr Kutitskiy    2.022368   1.80
99           Samuel Amo-Ameyaw    5.165660   4.00
100     Christian Neiva Afonso    0.527465   0.50
101                Robert Skov    2.683294   4.00
102               Ilia Rozhkov    3.862605   2.50
103             Warren Kamanzi    3.567391   2.00
104                Zeno Debast    3.190231  30.00
105        Christopher Trimmel    1.076208   0.60
106             Syb Van Ottele    2.855817   1.00
107                         MT    2.565023   5.00
108              Jaydee Canvot    4.507893   4.00
109           Jailson Siqueira    1.696426   1.00
110        Stephan El Shaarawy    2.789394   3.50
111                 Hugo Novoa    2.397225   1.50
112                 Eric Veiga    0.665153   0.20
113              Ruben Aguilar    1.642463   3.50
114             Arnau Martinez   12.515879  10.00
115               Ryan Manning    8.229704   3.00
116            Frederic Ananou    0.548912   0.40
117                   Ali Abdi    3.220744   3.00
118                  Joao Tome    0.902082   0.60
119                  Tom Rothe    9.680481  10.00
120            Patrick Pflucke    2.412548   1.60
121               Yuri Ribeiro    0.459216   1.20
122            Ruslan Bezrukov    2.344635   1.00
123            Alfonso Pedraza    1.441568   2.50
124               Pedro Amaral    1.903685   1.00
125          Jerome Roussillon    0.607413   0.80
126             Pedro Carvalho    1.027687   0.40
127          Mikael Ellertsson    8.330626   3.40
128           Bjarki Bjarkason    1.298344   0.80
129                   Emre Can    4.835034   7.00
130                 Rico Lewis   33.483187  40.00
131                Tom Louchet    2.738379   2.50
132            Josip Juranovic    1.627768   4.00
133            Marious Vrousai    2.172982   2.00
134            Darko Todorovic    1.000000   1.00
135                 Mory Gbane    3.282961   4.00
136             Fabiano Parisi    3.846670   6.00
137            Gustavo Mantuan    2.150782   3.50
138          Yukinari Sugawara   22.929046  11.00
139           Pawel Dawidowicz    2.168004   2.50

In [61]:
comp_leftovers_test

                 Player  Value_pred  Value
0        Danil Stepanov    0.673258   0.60
1           Eric Garcia    8.522207  18.00
2        Leandro Bacuna    3.467723   0.30
3       Ridwane M'Barki    0.320286   0.25
4         Nicolas Cozza    4.231772   3.50
5     Nikolai Rasskazov    1.906790   1.50
6     Raphael Guerreiro    4.358680   8.00
7         Nilton Varela    1.855384   1.50
8   Filippo Terracciano    2.608296   3.20
9        Julius Dirksen    1.214354   0.40
10        Kobe Corbanie    2.202980   1.70
11                Moura   14.808390  15.00
12           Max Aarons    1.591662   6.00
13     Jeremie Frimpong   16.273020  50.00
14       Danila Prokhin    1.972707   1.50
15         Nadir Zortea   10.434405   5.00
16     Jeanuel Belocian    1.913877  15.00
17      Nathaniel Clyne    3.455985   1.00
18       Dmitri Kabutov    0.952138   0.80
19      Nathaniel Brown    9.810162  22.00
20       Mateo Stamatov    0.818730   0.50
21      Jonathan Clauss    5.186400   5.00
22      Lorenz Assignon    8.626128   9.00
23              Rivaldo    0.598285   0.20
24          Tomas Silva    0.909245   0.10
25   Maximiliano Araujo    2.577543  17.00
26        Adam Dzwigala    0.930836   0.60
27      Jhoanner Chavez    3.423238   3.50
28        Matheus Nunes   40.200814  35.00
29  Aurelien Tchouameni    6.766047  75.00
30          Daam Foulon    2.527846   2.50
31          Finn Porath    3.573080   1.70
32       Josip Mitrovic    1.452287   0.50
33           Ali Maamar    1.113616   2.00
34    Daniil Khlusevich    0.903049   3.50
35      Fernando Calero    2.810338   1.50

# Модель 4

In [62]:
X_train = X_train[['Age', '90s', 'Gls', 'Ast', 'G+A', 'PK',
       '2CrdY', 'G+A.1', 'G-PK.1',
       'Off',
       'SoT%', 'G/Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Gls', 'Ast', 'G+A', 'PK',
       '2CrdY', 'G+A.1', 'G-PK.1',
       'Off',
       'SoT%', 'G/Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [68]:
coeffs_df

               coeff
league_GB1  0.704861
Age        -0.389401
90s         0.387681
league_FR1  0.298692
league_L1   0.296181
league_ES1  0.293833
league_IT1  0.269400
G/Sh        0.142935
Ast         0.122717
SoT%        0.108856
G+A         0.097069
G+A.1      -0.095015
PK          0.073771
league_NL1  0.067548
Off         0.049760
league_PO1 -0.047727
G-PK.1      0.033967
2CrdY      -0.029771
league_RU1 -0.022070
Gls         0.019240

In [69]:
metrics

            MAE       RMSE      MAPE        R2
test   5.374772  13.687768  1.255729  0.205046
train  2.725314   5.027361  0.766593  0.565192

# Модель 5

In [74]:
X_train = X_train[['Age', '90s', 'Gls', 'Ast', 'G+A',
       '2CrdY', 'G+A.1', 'G-PK.1',
       'Off', 'Crs', 'Int',
       'SoT%', 'G/Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Gls', 'Ast', 'G+A',
       '2CrdY', 'G+A.1', 'G-PK.1',
       'Off', 'Crs', 'Int',
       'SoT%', 'G/Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [80]:
coeffs_df

               coeff
league_GB1  0.684653
90s         0.476487
Age        -0.375656
league_L1   0.272964
league_FR1  0.266198
league_ES1  0.258095
league_IT1  0.237932
G/Sh        0.139745
G+A         0.116520
Ast         0.111290
SoT%        0.107273
Crs        -0.090637
Gls         0.074338
Int        -0.072996
league_PO1 -0.066896
G+A.1      -0.057492
Off         0.052910
2CrdY      -0.052451
league_NL1  0.045032
league_RU1 -0.038917
G-PK.1     -0.037931

In [81]:
metrics

            MAE       RMSE      MAPE        R2
test   5.299735  13.488795  1.024503  0.227990
train  2.749328   5.088813  0.768807  0.554498

In [87]:
comp_leftovers_train

                        Player  Value_pred  Value
0               Claudio Falcao    1.371245   0.80
1               Josha Vagnoman    4.985697  10.00
2           Samuele Birindelli    5.189832   2.80
3    Fernando Ferreira Fonseca    0.922994   0.50
4              Jairo Riedewald    0.718637   1.80
5           Jackson Tchatchoua   17.078961   8.00
6                  Reece James   14.026476  30.00
7              Ismael Doukoure   13.509108  18.00
8                 Mauro Junior    3.439411  12.00
9           Miroslav Bogosavac    0.667824   1.00
10               Juan Cuadrado    0.690515   1.00
11              Jakub Kaminski    2.938577   5.00
12                Amadou Dante    0.978307   1.50
13                  Allan Nyom    1.220722   0.30
14               Diego Moreira   18.642168  18.00
15        Siebe Van Der Heyden    2.173676   2.50
16          Jean-Kevin Duverne    1.475410   2.50
17               Goncalo Costa    1.187003   0.50
18                 Lars Ritzka    1.937512   1.00
19               Darko Lazovic    1.958540   0.80
20                 Nhoa Sangui    4.516563   2.50
21                Louis Patris    2.070542   2.00
22                Renato Veiga    4.354773  25.00
23                Tiago Araujo    0.878004   1.30
24              Bart Nieuwkoop    0.973736   2.00
25               Honest Ahanor    3.502287   5.00
26               Stefan Dzodic    2.150922   0.20
27                 Wagner Pina    5.528793   5.00
28                Ihor Kalinin    0.649902   0.70
29             Aleksandr Ektov    1.449944   0.80
30                 Noah Fadiga    1.521984   3.00
31            Julian Lelieveld    1.761457   0.50
32               Juan Castillo    0.952951   0.50
33                 Gary Magnee    1.294320   1.50
34         Oleksandr Zinchenko    6.601691  20.00
35            Rafael Rodrigues    1.264914   0.80
36              Deiver Machado    2.675723   3.00
37             Nikita Kakkoyev    2.048884   1.20
38                   Gijs Smal    1.486622   7.00
39               Thomas Keller    1.229941   0.50
40                 Ilya Agapov    0.670482   1.00
41                 John Tolkin    2.155249   2.50
42              Niels Nkounkou    1.424983   3.50
43    Jean-Charles Castelletto    3.407163   3.50
44                       Djene    2.512848   1.80
45              James Abankwah    1.850874   1.00
46               Fabio Ferraro    3.616213   1.30
47               Marco Weymans    0.882674   0.30
48              Felix Passlack    6.426006   2.00
49                 Colin Dagba    1.304127   0.70
50             Alexandro Calut    0.757082   0.40
51         Nikolas Veratschnig    2.225571   1.50
52              Lamare Bogarde   19.763318   6.00
53             Adrien Truffert   10.119889  15.00
54                 Archie Gray   43.770674  38.00
55            Killian Sardella    2.150505   5.00
56                 Samuel Dahl    1.269363   7.00
57              Ferdi Kadioglu   10.628895  25.00
58            Dominik Javorcek    1.912059   0.55
59             Diogo Travassos    1.829665   1.50
60             Goncalo Almeida    1.158819   0.25
61             Marcos Llorente    7.819750  25.00
62                Mats Wieffer   19.386961  25.00
63               Dario Grujcic    0.892311   0.25
64                David Pastor    1.812069   1.00
65            Fode Ballo-Toure    1.165718   1.20
66          Geoffrey Kondogbia    1.902681   7.00
67               Simion Michez    1.781971   1.50
68                Dominik Kohr    3.280138   3.50
69                  Eric Smith    4.846635   5.00
70             Mitchell Weiser   11.193427   5.00
71                 Melvin Bard    4.169801  15.00
72                Paulo Victor    1.229839   0.80
73                  Ridle Baku    9.269720   9.00
74                Marnon Busch    1.638640   1.20
75                 Rui Modesto    2.343266   2.00
76              Mihailo Ristic    1.242914   0.90
77               Vanja Drkusic    0.622100   4.00
78               Ivan Fresneda    2.677959   8.00
79             Kirill Bozhenov    0.759533   0.35
80            Bruno Onyemaechi    1.661579   2.70
81             Gonzalo Montiel    1.129054   5.00
82                 Ryoya Ogawa    2.579699   1.50
83                 Caleb Wiley    2.091079   8.00
84                 Tom Pouilly    2.142059   0.80
85                   Ken Nkuba    0.966776   2.70
86            Miguel Gutierrez   11.213131  20.00
87                Lucas Fasson    0.955460   3.00
88                 Eray Comert    3.101359   2.00
89                 Aron Donnum    5.749000   4.00
90                        Tuta    5.969648  15.00
91             Nicola Zalewski    3.280261  12.00
92                 John Stones   23.601306  25.00
93               Andres Garcia    9.555270   7.00
94                      Derick    0.881216   0.30
95            Joao Mario Lopes    1.541786  10.00
96                 Alex Moreno    5.346584   7.00
97             Petar Golubovic    0.475436   0.35
98         Aleksandr Kutitskiy    1.837018   1.80
99           Samuel Amo-Ameyaw    5.057040   4.00
100     Christian Neiva Afonso    0.684465   0.50
101                Robert Skov    1.787331   4.00
102               Ilia Rozhkov    3.665430   2.50
103             Warren Kamanzi    3.773039   2.00
104                Zeno Debast    2.839380  30.00
105        Christopher Trimmel    1.056424   0.60
106             Syb Van Ottele    2.683524   1.00
107                         MT    2.650150   5.00
108              Jaydee Canvot    4.089165   4.00
109           Jailson Siqueira    1.697679   1.00
110        Stephan El Shaarawy    2.733938   3.50
111                 Hugo Novoa    2.283297   1.50
112                 Eric Veiga    0.690177   0.20
113              Ruben Aguilar    1.823718   3.50
114             Arnau Martinez   13.142351  10.00
115               Ryan Manning    8.766774   3.00
116            Frederic Ananou    0.520728   0.40
117                   Ali Abdi    3.314258   3.00
118                  Joao Tome    0.888918   0.60
119                  Tom Rothe    9.975282  10.00
120            Patrick Pflucke    1.876714   1.60
121               Yuri Ribeiro    0.465447   1.20
122            Ruslan Bezrukov    2.430806   1.00
123            Alfonso Pedraza    1.528045   2.50
124               Pedro Amaral    1.760392   1.00
125          Jerome Roussillon    0.623387   0.80
126             Pedro Carvalho    1.011327   0.40
127          Mikael Ellertsson   10.329775   3.40
128           Bjarki Bjarkason    1.284379   0.80
129                   Emre Can    3.418052   7.00
130                 Rico Lewis   35.323355  40.00
131                Tom Louchet    2.726997   2.50
132            Josip Juranovic    1.666009   4.00
133            Marious Vrousai    2.168012   2.00
134            Darko Todorovic    1.235296   1.00
135                 Mory Gbane    2.667411   4.00
136             Fabiano Parisi    4.161750   6.00
137            Gustavo Mantuan    2.175850   3.50
138          Yukinari Sugawara   22.432321  11.00
139           Pawel Dawidowicz    1.955215   2.50

In [88]:
comp_leftovers_test

                 Player  Value_pred  Value
0        Danil Stepanov    0.656877   0.60
1           Eric Garcia    8.140353  18.00
2        Leandro Bacuna    2.233194   0.30
3       Ridwane M'Barki    0.321154   0.25
4         Nicolas Cozza    4.274569   3.50
5     Nikolai Rasskazov    1.648817   1.50
6     Raphael Guerreiro    4.416489   8.00
7         Nilton Varela    1.946334   1.50
8   Filippo Terracciano    2.549692   3.20
9        Julius Dirksen    1.209188   0.40
10        Kobe Corbanie    2.131814   1.70
11                Moura   13.162426  15.00
12           Max Aarons    1.576334   6.00
13     Jeremie Frimpong   17.963723  50.00
14       Danila Prokhin    1.737567   1.50
15         Nadir Zortea   11.152501   5.00
16     Jeanuel Belocian    1.940384  15.00
17      Nathaniel Clyne    3.457730   1.00
18       Dmitri Kabutov    0.929589   0.80
19      Nathaniel Brown   12.419201  22.00
20       Mateo Stamatov    0.771641   0.50
21      Jonathan Clauss    4.465837   5.00
22      Lorenz Assignon    9.816318   9.00
23              Rivaldo    0.608669   0.20
24          Tomas Silva    0.845871   0.10
25   Maximiliano Araujo    3.046547  17.00
26        Adam Dzwigala    0.960088   0.60
27      Jhoanner Chavez    3.239356   3.50
28        Matheus Nunes   41.032775  35.00
29  Aurelien Tchouameni    5.518907  75.00
30          Daam Foulon    2.975464   2.50
31          Finn Porath    4.191814   1.70
32       Josip Mitrovic    1.710376   0.50
33           Ali Maamar    1.121039   2.00
34    Daniil Khlusevich    0.885498   3.50
35      Fernando Calero    3.073890   1.50

# Модель 6

In [89]:
X_train = X_train[['Age', '90s', 'Gls', 'Ast', 'G+A',
       '2CrdY', 'G+A.1', 'G-PK.1',
       'Crs', 'Int',
       'SoT%', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Gls', 'Ast', 'G+A',
       '2CrdY', 'G+A.1', 'G-PK.1',
       'Crs', 'Int',
       'SoT%', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [95]:
coeffs_df

               coeff
league_GB1  0.687271
90s         0.514902
Age        -0.379389
league_L1   0.271412
league_FR1  0.267954
league_ES1  0.259541
league_IT1  0.247741
G/Sh        0.210644
G+A         0.126646
G/SoT      -0.121998
Ast         0.108318
Gls         0.098785
Int        -0.093571
SoT%        0.088110
Crs        -0.083785
G+A.1      -0.063046
league_PO1 -0.057129
league_NL1  0.044981
league_RU1 -0.040408
2CrdY      -0.039297
G-PK.1     -0.008497

In [96]:
metrics

            MAE       RMSE      MAPE        R2
test   5.168998  13.486506  1.080572  0.228252
train  2.791708   5.149400  0.768641  0.543826

In [102]:
comp_leftovers_train

                        Player  Value_pred  Value
0               Claudio Falcao    1.468495   0.80
1               Josha Vagnoman    5.300171  10.00
2           Samuele Birindelli    5.200596   2.80
3    Fernando Ferreira Fonseca    0.973234   0.50
4              Jairo Riedewald    0.707242   1.80
5           Jackson Tchatchoua   13.267947   8.00
6                  Reece James   13.788649  30.00
7              Ismael Doukoure   11.489177  18.00
8                 Mauro Junior    3.452216  12.00
9           Miroslav Bogosavac    0.640042   1.00
10               Juan Cuadrado    0.727072   1.00
11              Jakub Kaminski    3.062914   5.00
12                Amadou Dante    0.989087   1.50
13                  Allan Nyom    1.232282   0.30
14               Diego Moreira   19.090405  18.00
15        Siebe Van Der Heyden    2.144971   2.50
16          Jean-Kevin Duverne    1.464024   2.50
17               Goncalo Costa    1.180472   0.50
18                 Lars Ritzka    1.373035   1.00
19               Darko Lazovic    1.837892   0.80
20                 Nhoa Sangui    4.853452   2.50
21                Louis Patris    2.013650   2.00
22                Renato Veiga    4.280342  25.00
23                Tiago Araujo    0.850451   1.30
24              Bart Nieuwkoop    0.909786   2.00
25               Honest Ahanor    3.651427   5.00
26               Stefan Dzodic    2.223467   0.20
27                 Wagner Pina    4.583082   5.00
28                Ihor Kalinin    0.692919   0.70
29             Aleksandr Ektov    1.339067   0.80
30                 Noah Fadiga    1.724361   3.00
31            Julian Lelieveld    1.834265   0.50
32               Juan Castillo    0.940864   0.50
33                 Gary Magnee    1.310075   1.50
34         Oleksandr Zinchenko    6.651806  20.00
35            Rafael Rodrigues    1.199101   0.80
36              Deiver Machado    2.511702   3.00
37             Nikita Kakkoyev    2.034893   1.20
38                   Gijs Smal    1.504370   7.00
39               Thomas Keller    1.247766   0.50
40                 Ilya Agapov    0.683940   1.00
41                 John Tolkin    2.241928   2.50
42              Niels Nkounkou    1.456435   3.50
43    Jean-Charles Castelletto    3.662847   3.50
44                       Djene    2.706595   1.80
45              James Abankwah    1.960926   1.00
46               Fabio Ferraro    3.722811   1.30
47               Marco Weymans    0.803881   0.30
48              Felix Passlack    6.501869   2.00
49                 Colin Dagba    1.335469   0.70
50             Alexandro Calut    0.771045   0.40
51         Nikolas Veratschnig    1.988717   1.50
52              Lamare Bogarde   19.092799   6.00
53             Adrien Truffert   10.150740  15.00
54                 Archie Gray   43.832503  38.00
55            Killian Sardella    2.315487   5.00
56                 Samuel Dahl    1.195799   7.00
57              Ferdi Kadioglu    8.273571  25.00
58            Dominik Javorcek    1.882821   0.55
59             Diogo Travassos    1.860240   1.50
60             Goncalo Almeida    1.076123   0.25
61             Marcos Llorente    7.144053  25.00
62                Mats Wieffer   18.932228  25.00
63               Dario Grujcic    0.867381   0.25
64                David Pastor    1.852281   1.00
65            Fode Ballo-Toure    1.217950   1.20
66          Geoffrey Kondogbia    1.964972   7.00
67               Simion Michez    1.725509   1.50
68                Dominik Kohr    3.135275   3.50
69                  Eric Smith    4.736783   5.00
70             Mitchell Weiser   13.956096   5.00
71                 Melvin Bard    4.409348  15.00
72                Paulo Victor    1.277777   0.80
73                  Ridle Baku    9.153863   9.00
74                Marnon Busch    1.706257   1.20
75                 Rui Modesto    2.290664   2.00
76              Mihailo Ristic    1.285533   0.90
77               Vanja Drkusic    0.617293   4.00
78               Ivan Fresneda    2.989963   8.00
79             Kirill Bozhenov    0.786885   0.35
80            Bruno Onyemaechi    1.591042   2.70
81             Gonzalo Montiel    1.156392   5.00
82                 Ryoya Ogawa    2.353911   1.50
83                 Caleb Wiley    2.143236   8.00
84                 Tom Pouilly    2.141256   0.80
85                   Ken Nkuba    0.966395   2.70
86            Miguel Gutierrez   10.481930  20.00
87                Lucas Fasson    0.983172   3.00
88                 Eray Comert    3.289135   2.00
89                 Aron Donnum    6.078628   4.00
90                        Tuta    5.961640  15.00
91             Nicola Zalewski    3.251014  12.00
92                 John Stones   29.402791  25.00
93               Andres Garcia   10.001004   7.00
94                      Derick    0.953516   0.30
95            Joao Mario Lopes    1.668657  10.00
96                 Alex Moreno    5.571739   7.00
97             Petar Golubovic    0.477406   0.35
98         Aleksandr Kutitskiy    1.792057   1.80
99           Samuel Amo-Ameyaw    5.191163   4.00
100     Christian Neiva Afonso    0.520589   0.50
101                Robert Skov    1.815359   4.00
102               Ilia Rozhkov    3.614258   2.50
103             Warren Kamanzi    3.540932   2.00
104                Zeno Debast    3.077569  30.00
105        Christopher Trimmel    1.071735   0.60
106             Syb Van Ottele    2.793544   1.00
107                         MT    2.670386   5.00
108              Jaydee Canvot    4.283758   4.00
109           Jailson Siqueira    1.684206   1.00
110        Stephan El Shaarawy    2.687377   3.50
111                 Hugo Novoa    2.226754   1.50
112                 Eric Veiga    0.650489   0.20
113              Ruben Aguilar    1.520074   3.50
114             Arnau Martinez   13.121776  10.00
115               Ryan Manning    9.384349   3.00
116            Frederic Ananou    0.516849   0.40
117                   Ali Abdi    3.238133   3.00
118                  Joao Tome    0.947552   0.60
119                  Tom Rothe   10.256059  10.00
120            Patrick Pflucke    1.927517   1.60
121               Yuri Ribeiro    0.465163   1.20
122            Ruslan Bezrukov    2.415182   1.00
123            Alfonso Pedraza    1.516310   2.50
124               Pedro Amaral    1.825660   1.00
125          Jerome Roussillon    0.631304   0.80
126             Pedro Carvalho    1.067727   0.40
127          Mikael Ellertsson   10.399286   3.40
128           Bjarki Bjarkason    1.357243   0.80
129                   Emre Can    3.554686   7.00
130                 Rico Lewis   35.509707  40.00
131                Tom Louchet    2.741223   2.50
132            Josip Juranovic    1.677847   4.00
133            Marious Vrousai    2.221151   2.00
134            Darko Todorovic    1.178772   1.00
135                 Mory Gbane    2.701961   4.00
136             Fabiano Parisi    4.461109   6.00
137            Gustavo Mantuan    2.379505   3.50
138          Yukinari Sugawara   21.061050  11.00
139           Pawel Dawidowicz    2.155846   2.50

In [103]:
comp_leftovers_test

                 Player  Value_pred  Value
0        Danil Stepanov    0.676700   0.60
1           Eric Garcia    8.712923  18.00
2        Leandro Bacuna    2.613380   0.30
3       Ridwane M'Barki    0.326678   0.25
4         Nicolas Cozza    4.183914   3.50
5     Nikolai Rasskazov    1.679672   1.50
6     Raphael Guerreiro    5.077972   8.00
7         Nilton Varela    2.171921   1.50
8   Filippo Terracciano    2.567638   3.20
9        Julius Dirksen    1.186583   0.40
10        Kobe Corbanie    2.081863   1.70
11                Moura   12.941974  15.00
12           Max Aarons    1.629960   6.00
13     Jeremie Frimpong   16.781512  50.00
14       Danila Prokhin    1.769204   1.50
15         Nadir Zortea   12.963635   5.00
16     Jeanuel Belocian    1.984777  15.00
17      Nathaniel Clyne    3.594166   1.00
18       Dmitri Kabutov    1.017471   0.80
19      Nathaniel Brown   12.899116  22.00
20       Mateo Stamatov    0.775614   0.50
21      Jonathan Clauss    4.606218   5.00
22      Lorenz Assignon    8.579497   9.00
23              Rivaldo    0.642434   0.20
24          Tomas Silva    0.891736   0.10
25   Maximiliano Araujo    2.959529  17.00
26        Adam Dzwigala    0.982957   0.60
27      Jhoanner Chavez    3.127326   3.50
28        Matheus Nunes   35.209326  35.00
29  Aurelien Tchouameni    5.871070  75.00
30          Daam Foulon    2.569548   2.50
31          Finn Porath    4.595353   1.70
32       Josip Mitrovic    1.621805   0.50
33           Ali Maamar    1.115811   2.00
34    Daniil Khlusevich    0.859689   3.50
35      Fernando Calero    2.694977   1.50

# Модель 7

In [101]:
X_train = X_train[['Age', '90s', 'Gls', 'Ast',
       '2CrdY',
       'Crs', 'Int',
       'SoT%', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Age', '90s', 'Gls', 'Ast',
       '2CrdY',
       'Crs', 'Int',
       'SoT%', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [109]:
coeffs_df

               coeff
league_GB1  0.687696
90s         0.542010
Age        -0.384654
league_L1   0.275449
league_FR1  0.268338
league_ES1  0.260469
league_IT1  0.250034
G/Sh        0.197610
Ast         0.156486
Gls         0.130956
G/SoT      -0.128557
Int        -0.091817
SoT%        0.089016
Crs        -0.082800
league_PO1 -0.056390
league_NL1  0.040694
league_RU1 -0.038837
2CrdY      -0.032070

In [110]:
metrics

            MAE       RMSE      MAPE        R2
test   5.226608  13.506199  1.046830  0.225996
train  2.759821   5.120070  0.765459  0.549008

In [111]:
comp_leftovers_train

                        Player  Value_pred  Value
0               Claudio Falcao    1.522152   0.80
1               Josha Vagnoman    5.369468  10.00
2           Samuele Birindelli    5.194542   2.80
3    Fernando Ferreira Fonseca    0.988770   0.50
4              Jairo Riedewald    0.689526   1.80
5           Jackson Tchatchoua   13.000959   8.00
6                  Reece James   13.839613  30.00
7              Ismael Doukoure   11.104437  18.00
8                 Mauro Junior    3.344609  12.00
9           Miroslav Bogosavac    0.625462   1.00
10               Juan Cuadrado    0.741655   1.00
11              Jakub Kaminski    3.139622   5.00
12                Amadou Dante    0.978890   1.50
13                  Allan Nyom    1.255918   0.30
14               Diego Moreira   18.269016  18.00
15        Siebe Van Der Heyden    2.069334   2.50
16          Jean-Kevin Duverne    1.306699   2.50
17               Goncalo Costa    1.219515   0.50
18                 Lars Ritzka    1.342797   1.00
19               Darko Lazovic    1.841594   0.80
20                 Nhoa Sangui    4.945368   2.50
21                Louis Patris    2.012293   2.00
22                Renato Veiga    4.205185  25.00
23                Tiago Araujo    0.862717   1.30
24              Bart Nieuwkoop    0.912799   2.00
25               Honest Ahanor    3.562832   5.00
26               Stefan Dzodic    2.142700   0.20
27                 Wagner Pina    4.477657   5.00
28                Ihor Kalinin    0.697370   0.70
29             Aleksandr Ektov    1.314171   0.80
30                 Noah Fadiga    1.861522   3.00
31            Julian Lelieveld    1.833321   0.50
32               Juan Castillo    0.913247   0.50
33                 Gary Magnee    1.324533   1.50
34         Oleksandr Zinchenko    6.757488  20.00
35            Rafael Rodrigues    1.179209   0.80
36              Deiver Machado    2.561930   3.00
37             Nikita Kakkoyev    2.071493   1.20
38                   Gijs Smal    1.475925   7.00
39               Thomas Keller    1.202474   0.50
40                 Ilya Agapov    0.711644   1.00
41                 John Tolkin    2.349192   2.50
42              Niels Nkounkou    1.418340   3.50
43    Jean-Charles Castelletto    3.788723   3.50
44                       Djene    2.784426   1.80
45              James Abankwah    1.889017   1.00
46               Fabio Ferraro    3.697265   1.30
47               Marco Weymans    0.805520   0.30
48              Felix Passlack    6.369676   2.00
49                 Colin Dagba    1.338445   0.70
50             Alexandro Calut    0.739509   0.40
51         Nikolas Veratschnig    1.939599   1.50
52              Lamare Bogarde   18.594753   6.00
53             Adrien Truffert   10.150830  15.00
54                 Archie Gray   44.800950  38.00
55            Killian Sardella    2.357312   5.00
56                 Samuel Dahl    1.094436   7.00
57              Ferdi Kadioglu    8.381914  25.00
58            Dominik Javorcek    2.169032   0.55
59             Diogo Travassos    1.870665   1.50
60             Goncalo Almeida    1.056951   0.25
61             Marcos Llorente    6.849445  25.00
62                Mats Wieffer   19.613704  25.00
63               Dario Grujcic    0.923397   0.25
64                David Pastor    1.901754   1.00
65            Fode Ballo-Toure    1.175456   1.20
66          Geoffrey Kondogbia    1.983855   7.00
67               Simion Michez    1.917128   1.50
68                Dominik Kohr    3.132486   3.50
69                  Eric Smith    4.874922   5.00
70             Mitchell Weiser   12.871419   5.00
71                 Melvin Bard    4.553763  15.00
72                Paulo Victor    1.291708   0.80
73                  Ridle Baku    8.809090   9.00
74                Marnon Busch    1.713202   1.20
75                 Rui Modesto    2.343691   2.00
76              Mihailo Ristic    1.326081   0.90
77               Vanja Drkusic    0.597390   4.00
78               Ivan Fresneda    3.051033   8.00
79             Kirill Bozhenov    0.772132   0.35
80            Bruno Onyemaechi    1.578354   2.70
81             Gonzalo Montiel    1.100301   5.00
82                 Ryoya Ogawa    2.264688   1.50
83                 Caleb Wiley    2.357673   8.00
84                 Tom Pouilly    2.063847   0.80
85                   Ken Nkuba    0.995373   2.70
86            Miguel Gutierrez   10.327138  20.00
87                Lucas Fasson    0.969803   3.00
88                 Eray Comert    3.324026   2.00
89                 Aron Donnum    5.984686   4.00
90                        Tuta    5.936462  15.00
91             Nicola Zalewski    3.308721  12.00
92                 John Stones   28.278865  25.00
93               Andres Garcia    9.640722   7.00
94                      Derick    0.955878   0.30
95            Joao Mario Lopes    1.675665  10.00
96                 Alex Moreno    5.513443   7.00
97             Petar Golubovic    0.476176   0.35
98         Aleksandr Kutitskiy    1.780868   1.80
99           Samuel Amo-Ameyaw    5.031699   4.00
100     Christian Neiva Afonso    0.524118   0.50
101                Robert Skov    1.955446   4.00
102               Ilia Rozhkov    3.638390   2.50
103             Warren Kamanzi    3.551111   2.00
104                Zeno Debast    3.124222  30.00
105        Christopher Trimmel    1.074290   0.60
106             Syb Van Ottele    2.753006   1.00
107                         MT    2.709570   5.00
108              Jaydee Canvot    4.263230   4.00
109           Jailson Siqueira    1.631790   1.00
110        Stephan El Shaarawy    2.889655   3.50
111                 Hugo Novoa    2.143635   1.50
112                 Eric Veiga    0.625930   0.20
113              Ruben Aguilar    1.524148   3.50
114             Arnau Martinez   13.063648  10.00
115               Ryan Manning    9.373052   3.00
116            Frederic Ananou    0.491969   0.40
117                   Ali Abdi    3.291799   3.00
118                  Joao Tome    0.957813   0.60
119                  Tom Rothe   10.344561  10.00
120            Patrick Pflucke    1.961550   1.60
121               Yuri Ribeiro    0.447053   1.20
122            Ruslan Bezrukov    2.537836   1.00
123            Alfonso Pedraza    1.662187   2.50
124               Pedro Amaral    1.859189   1.00
125          Jerome Roussillon    0.602557   0.80
126             Pedro Carvalho    1.112317   0.40
127          Mikael Ellertsson   10.331518   3.40
128           Bjarki Bjarkason    1.304298   0.80
129                   Emre Can    3.510226   7.00
130                 Rico Lewis   36.304505  40.00
131                Tom Louchet    2.761752   2.50
132            Josip Juranovic    1.689166   4.00
133            Marious Vrousai    2.220571   2.00
134            Darko Todorovic    1.201911   1.00
135                 Mory Gbane    2.656918   4.00
136             Fabiano Parisi    4.462328   6.00
137            Gustavo Mantuan    2.394468   3.50
138          Yukinari Sugawara   21.103308  11.00
139           Pawel Dawidowicz    2.182446   2.50

In [112]:
comp_leftovers_test

                 Player  Value_pred  Value
0        Danil Stepanov    0.662416   0.60
1           Eric Garcia    8.728282  18.00
2        Leandro Bacuna    2.459301   0.30
3       Ridwane M'Barki    0.308934   0.25
4         Nicolas Cozza    4.206646   3.50
5     Nikolai Rasskazov    1.683859   1.50
6     Raphael Guerreiro    5.090845   8.00
7         Nilton Varela    2.203839   1.50
8   Filippo Terracciano    2.513474   3.20
9        Julius Dirksen    1.110591   0.40
10        Kobe Corbanie    2.080561   1.70
11                Moura   11.343525  15.00
12           Max Aarons    1.561704   6.00
13     Jeremie Frimpong   16.043658  50.00
14       Danila Prokhin    1.831969   1.50
15         Nadir Zortea   12.291100   5.00
16     Jeanuel Belocian    1.919709  15.00
17      Nathaniel Clyne    3.429008   1.00
18       Dmitri Kabutov    1.017479   0.80
19      Nathaniel Brown   12.477223  22.00
20       Mateo Stamatov    0.799026   0.50
21      Jonathan Clauss    4.301087   5.00
22      Lorenz Assignon    8.205187   9.00
23              Rivaldo    0.664195   0.20
24          Tomas Silva    0.856454   0.10
25   Maximiliano Araujo    2.906326  17.00
26        Adam Dzwigala    0.949300   0.60
27      Jhoanner Chavez    3.132421   3.50
28        Matheus Nunes   34.852636  35.00
29  Aurelien Tchouameni    6.156466  75.00
30          Daam Foulon    2.537660   2.50
31          Finn Porath    4.591018   1.70
32       Josip Mitrovic    1.573276   0.50
33           Ali Maamar    1.082001   2.00
34    Daniil Khlusevich    0.870221   3.50
35      Fernando Calero    2.536014   1.50