In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_rows', None)

In [75]:
X_train = pd.read_csv('../../../data/processed/for_linear_model/GK/predictors_train_filtered.csv')
X_test = pd.read_csv('../../../data/processed/for_linear_model/GK/predictors_test_filtered.csv')
y_train = pd.read_csv('../../../data/processed/for_linear_model/GK/target_train_filtered_logariphmed.csv')
y_test = pd.read_csv('../../../data/processed/for_linear_model/GK/target_test_filtered_logariphmed.csv')

In [6]:
train_players = pd.read_csv('../../../data/processed/for_linear_model/GK/train_players_names.csv')
test_players = pd.read_csv('../../../data/processed/for_linear_model/GK/test_players_names.csv')

In [8]:
all_cols = X_train.columns
all_cols

Index(['Age', 'MP', 'Starts', 'Min', '90s', 'GA', 'GA90', 'SoTA', 'Saves',
       'Save%', 'W', 'D', 'L', 'CS', 'CS%', 'PKatt', 'PKA', 'PKsv', 'PKm',
       'PKsv%', 'league_ES1', 'league_FR1', 'league_GB1', 'league_IT1',
       'league_L1', 'league_NL1', 'league_PO1', 'league_RU1'],
      dtype='object')

## Регрессор

In [79]:
LR_regressor = LinearRegression()
LR_regressor.fit(X_train, y_train)

LinearRegression()

## Предсказанные значения

In [80]:
y_pred_log = LR_regressor.predict(X_test)
y_pred = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

y_train_pred = np.exp(LR_regressor.predict(X_train))
y_train_original = np.exp(y_train)

## Метрики

In [81]:
mae_test = mean_absolute_error(y_test_original, y_pred)
rmse_test = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2_test = r2_score(y_test_original, y_pred)
mape_test = mean_absolute_percentage_error(y_test_original, y_pred)

mae_train = mean_absolute_error(y_train_original, y_train_pred)
rmse_train = np.sqrt(mean_squared_error(y_train_original, y_train_pred))
r2_train = r2_score(y_train_original, y_train_pred)
mape_train = mean_absolute_percentage_error(y_train_original, y_train_pred)

metrics = pd.DataFrame({
    'MAE':[mae_test, mae_train],
    'RMSE':[rmse_test, rmse_train],
    'MAPE':[mape_test, mape_train],
    'R2':[r2_test, r2_train]
}, index = ['test', 'train'])

## Остатки

In [82]:
y_pred = pd.Series(np.reshape(y_pred, len(y_pred)), name='Value_pred')
y_train_pred = pd.Series(np.reshape(y_train_pred, len(y_train_pred)), name='Value_pred')

comp_leftovers_test = pd.concat([test_players, y_pred, y_test_original], axis=1)
comp_leftovers_train = pd.concat([train_players, y_train_pred, y_train_original], axis=1)

## Коэффициенты

In [83]:
coeffs = LR_regressor.coef_[0]
coeffs_df = pd.DataFrame({
    'coeff':coeffs.astype('float')
}, index=X_train.columns)
coeffs_df = coeffs_df.sort_values(by='coeff', key=abs, ascending=False)

# Все переменные

In [14]:
coeffs_df

                coeff
Min        -15.324961
90s         13.872235
SoTA         5.991010
Saves       -4.576390
GA          -2.041567
W            1.036480
Starts       0.809669
Age         -0.687525
league_GB1   0.661890
league_IT1   0.478799
league_ES1   0.438392
league_FR1   0.421544
league_L1    0.415606
L            0.412060
MP           0.247648
PKsv         0.235833
D            0.212873
PKatt        0.158976
league_PO1   0.146232
GA90        -0.133501
PKsv%       -0.108847
Save%        0.106014
PKA          0.105485
league_NL1   0.086239
PKm         -0.068138
CS          -0.054289
CS%          0.012899
league_RU1   0.006180

In [15]:
metrics

            MAE      RMSE     MAPE        R2
test   2.526755  4.721005  0.67345  0.487875
train  2.627833  5.155999  0.54584  0.633245

# Потенциальные переменные для добавления и удаления

## Текущие переменные

In [74]:
base_cols = ['W', '90s', 'PKsv%', 'GA90', 'Age', 'CS%' ,'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']

## Для добавления:

In [76]:
cols_to_add = [col for col in all_cols if not(col in base_cols)]
new_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_add:
    X_train_new = X_train[base_cols + [col]]
    X_test_new = X_test[base_cols + [col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new<mae_test or mape_new<mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=new_cols.columns, index=[col])
        new_cols = pd.concat([new_cols, row])
new_cols

             mae      mape        r2
base    2.290762  0.660419  0.561213
MP      2.292114  0.804624  0.581363
Starts  2.281196  0.811967  0.580643
Min     2.310482  0.802534  0.589511
GA      2.289883  0.808664  0.582158
SoTA    2.287909  0.805450  0.578962
Saves   2.292280  0.806435  0.580961
Save%   2.297227  0.813479  0.581205
D       2.264819  0.808106  0.570762
L       2.258407  0.809874  0.569196
CS      2.265817  0.805946  0.584430
PKatt   2.261113  0.822935  0.572972
PKA     2.266310  0.818742  0.576223
PKsv    2.172202  0.830179  0.555432
PKm     2.228414  0.793947  0.586513

## Для удаления:

In [77]:
cols_to_delete = [col for col in base_cols if not(col.startswith('league'))]
del_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_delete:
    X_train_new = X_train[[c for c in base_cols if c != col]]
    X_test_new = X_test[[c for c in base_cols if c != col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new < mae_test or mape_new < mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=del_cols.columns, index=[col])
        del_cols = pd.concat([del_cols, row])
del_cols

            mae      mape        r2
base   2.290762  0.660419  0.561213
W      2.286652  0.919916  0.420584
90s    2.376186  0.802093  0.577281
PKsv%  2.186760  0.798569  0.564861
CS%    2.295316  0.804931  0.581886

# Модель 1

In [19]:
X_train = X_train[['W', 'CS', '90s', 'GA90', 'Age', 'D', 'CS%', 'Save%' ,'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['W', 'CS', '90s', 'GA90', 'Age', 'D', 'CS%', 'Save%' ,'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [25]:
coeffs_df

               coeff
Age        -0.673402
league_GB1  0.659165
W           0.625911
league_IT1  0.483233
league_ES1  0.442786
league_L1   0.427698
league_FR1  0.410369
GA90       -0.215938
90s         0.189621
league_PO1  0.134140
league_NL1  0.054682
D          -0.053494
CS         -0.044994
Save%       0.023616
league_RU1  0.008782
CS%         0.006899

In [26]:
metrics

            MAE      RMSE      MAPE        R2
test   2.167138  4.289290  0.631043  0.577255
train  2.832055  5.440427  0.571497  0.591665

In [29]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                      Player  Value_pred  Value
56           Bart Verbruggen   46.151589  30.00
126               David Raya   44.687675  40.00
81            Robert Sanchez   40.215760  20.00
82               Mile Svilar   36.605173  25.00
17         Marco Carnesecchi   30.909874  25.00
169          Lucas Chevalier   29.409858  30.00
51           Anatolii Trubin   25.663555  28.00
137     Gianluigi Donnarumma   19.239964  40.00
122         Djordje Petrovic   16.036381  20.00
199         Guillaume Restes   15.907115  20.00
15         Kepa Arrizabalaga   15.656313  10.00
92              Mark Flekken   15.374693  10.00
153              Diogo Costa   15.186761  40.00
4                Lucas Perri   14.802414  10.00
22       Michele Di Gregorio   12.992513  18.00
109              Andre Onana   12.864432  25.00
161               Bernd Leno   12.725540  10.00
69        Stanislav Agkatsev   12.385072   7.50
119             Noah Atubolu   12.350175  18.00
149                Jan Oblak   12.180490  20.00
60              Gregor Kobel   11.797855  40.00
74         Guglielmo Vicario   11.296701  32.00
194             Mike Maignan   11.289925  25.00
116          Jordan Pickford   11.038891  18.00
99      Giorgi Mamardashvili   11.037912  30.00
24              Elia Caprile   10.654666   9.00
175          Filip Jorgensen   10.199492  18.00
123       Julen Agirrezabala   10.151551  15.00
20               Zion Suzuki   10.059387  20.00
201             Yahia Fofana   10.000391   7.00
166         Thibaut Courtois    9.683754  20.00
91             Tiago Cardoso    9.513751   1.50
156           Geronimo Rulli    8.710496   8.00
190         Jakub Stolarczyk    8.532988   1.00
197           Antonin Kinsky    8.011427  15.00
129          Alexander Nubel    7.782029  12.00
87           Gabriel Batista    7.560519   4.00
172             Mark Travers    7.465471   4.00
26             Yehvann Diouf    7.434210  12.00
154            Dominik Greif    7.318050   6.00
171              Diego Conde    7.253731   7.50
118             Mike Penders    7.198941  12.00
48    Vanja Milinkovic-Savic    6.959680  16.00
5                Yann Sommer    6.742732   4.00
57               Alex Remiro    6.669970  18.00
184            Ivan Provedel    6.339059   3.00
133       Yevgeni Latyshonok    6.211437   4.00
152           Walter Benitez    6.179037   7.50
151              Razvan Sava    6.169219   2.50
89           Christos Mandas    6.151932  10.00
85               Robin Roefs    5.893385   4.00
159            Robin Zentner    5.831848   4.00
145  Rome-Jayden Owusu-Oduro    5.665102   6.00
176           Arijanet Muric    5.589679   5.00
21            Matvei Safonov    5.559457  20.00
28               Jonas Urbig    5.484761  12.00
185            Kamil Grabara    5.427474  14.00
6               Maduka Okoye    5.405022   7.50
120         Michael Zetterer    5.316478   4.50
130           Antonio Sivera    5.229501   6.00
136              Brice Samba    5.226533  12.00
203         Radoslaw Majecki    5.196631   6.00
35            Moritz Nicolas    5.108658   5.00
155          Augusto Batalla    5.108433   6.00
100           Aaron Ramsdale    4.847637  16.00
111              David Soria    4.611058   3.00
19              Andriy Lunin    4.595361  18.00
0             Stefano Turati    4.583649   6.50
33         Federico Ravaglia    4.542415   1.50
68           Filip Stankovic    4.334367   6.00
13             Devis Vasquez    4.330806   2.00
9              Nikola Vasilj    4.301277   3.50
106           Josep Martinez    4.289663  12.00
84          Patrick Sequeira    4.203533   4.00
11           Lorenzo Montipo    4.134951   2.00
36            Sergio Herrera    3.880851   3.00
46                Jean Butez    3.794143   3.50
61                 Rui Silva    3.782754   7.00
42      Aleksandr Maksimenko    3.709142   4.50
188        Wladimiro Falcone    3.695213   3.50
104              Matej Kovar    3.628193   5.00
34            Lukas Hradecky    3.602580   2.00
67             Stefan Ortega    3.495094   8.00
45             Anthony Moris    3.477640   1.80
138        Wojciech Szczesny    3.468626   1.00
191             Alex Padilla    3.451228   3.00
53             Franco Israel    3.341230   5.00
73              Donovan Leon    3.317259   1.00
78        Gautier Larsonneur    3.199520   3.00
117             Manuel Neuer    3.130622   4.00
38               Marco Bizot    3.086346   3.00
94           Paulo Gazzaniga    3.083120   2.50
41            Matthieu Epolo    3.067628   4.00
71                 Leo Roman    2.946577   5.00
23             Cezary Miszta    2.923402   3.00
16               Jesus Owono    2.923064   0.90
112              Tobe Leysen    2.864671   4.00
202          Martin Dubravka    2.820085   1.00
178             Mohamed Kone    2.816586   1.20
98               Alex Palmer    2.764112   1.00
10                Nico Mantl    2.703810   1.50
177       Semuel Pizzignacco    2.574626   0.80
93          Lukasz Skorupski    2.525073   2.50
179        Nediljko Labrovic    2.486430   2.50
12        Jasper Schendelaar    2.482376   2.50
2              Dani Cardenas    2.477007   1.80
134      Maarten Vandevoordt    2.405910   8.00
79                Leo Kokubo    2.374093   3.00
86           Colin Coosemans    2.334963   1.50
146               Ionut Radu    2.321172   2.50
165              Kevin Trapp    2.278593   2.50
148          Frederik Ronnow    2.264211   3.00
196           Evgenii Staver    2.247788   1.50
140            Lazar Carevic    2.196070   1.50
50              Timon Weiner    2.150753   1.00
29              Juan Soriano    2.125201   1.00
135        Fabian de Keijzer    2.106245   1.50
115              Kjetil Haug    2.089056   0.60
101           Vicente Guaita    2.056794   0.70
167                  Matheus    2.051555   2.50
14               Mathew Ryan    2.031364   2.50
44            Ortwin De Wolf    1.958219   1.50
144          Marko Dmitrovic    1.943299   0.80
18            Florian Muller    1.900493   1.20
127             Lucas Franca    1.856623   1.00
193           Daniel Bielica    1.850129   1.00
198             Ørjan Nyland    1.834429   0.90
43           Andreas Jungdal    1.785730   1.50
95            Simone Scuffet    1.746615   2.00
158           Jari De Busser    1.735254   2.00
25                     Kewin    1.712394   1.00
1      Marc-Andre ter Stegen    1.687152  12.00
31            Nikita Kokarev    1.674874   1.50
96              Mattia Perin    1.626314   2.50
7           Alvaro Fernandez    1.609896   2.00
3                  Nick Olij    1.572158   3.50
58            Simon Mignolet    1.541832   1.20
27           Maxime Delanghe    1.539820   1.20
103             Luca Philipp    1.532086   0.75
70            Rustam Yatimov    1.500894   1.50
54               Herve Koffi    1.500666   1.20
113         Vladan Kovacevic    1.451319   3.00
77             Ricardo Velho    1.382179   4.00
141            Arthur Desmas    1.335266   1.20
83           Timur Magomedov    1.299728   0.70
75              Kevin Muller    1.280097   0.70
108               David Volk    1.276608   1.20
164          Etienne Vaessen    1.274630   2.00
30               Emil Audero    1.257130   3.20
157          Michael Verrips    1.242586   0.80
37             Sam Johnstone    1.209403   6.00
173            Marius Muller    1.206364   1.50
132     Mattijs Branderhorst    1.139392   0.80
162              Joao Valido    1.129013   0.30
182                   Adrian    1.122908   0.50
8              Anthony Lopes    1.087033   1.20
114   Hendrik Van Crombrugge    1.079797   1.70
195              Ivan Zlobin    1.079524   1.50
147          Daniil Odoevski    1.055481   0.80
150          Lars Unnerstall    1.021883   2.00
192          Thomas Didillon    0.998767   0.90
107                Timo Horn    0.975318   0.80
32          Jasper Cillessen    0.965299   0.80
55            Oliver Baumann    0.939037   3.00
131           Nordin Jackers    0.937702   1.20
90         Patrik Gunnarsson    0.921209   1.00
72              Nick Shinton    0.917534   0.60
163            Nordin Bakker    0.891208   0.70
66         Pierluigi Gollini    0.878856   1.00
40   Joao Paulo Santos Costa    0.875146   0.80
62            Patrick Drewes    0.839346   0.50
49          Mathieu Gorgelin    0.824777   0.30
183             Thomas Dahne    0.817422   0.40
59             Jesse Joronen    0.781806   0.50
187         Benjamin Lecomte    0.762726   1.50
76            Fraser Forster    0.756671   1.00
47        Aleksandr Vasyutin    0.745119   0.90
189          Patrik Carlgren    0.729803   0.60
174              Joel Robles    0.727849   0.50
143          Nikita Medvedev    0.699714   0.80
39           Andries Noppert    0.685161   1.00
181            Igor Akinfeev    0.683914   1.00
142            Igor Leshchuk    0.627343   0.70
200        Anton Mitryushkin    0.618120   1.80
170          Nikolai Sysuyev    0.562586   0.80
139              Jeroen Zoet    0.562248   0.30
65        Alexander Schwolow    0.555849   0.50
160      Mickey van der Hart    0.515739   0.50
186           Steve Mandanda    0.503665   0.50
80            Andre Ferreira    0.471111   0.70
52                  Warleson    0.442478   2.50
105            Davor Matijas    0.440978   0.40
97            Simao Bertelli    0.395815   0.30
102             Lucas Pirard    0.381898   0.25
125            Bruno Brigido    0.379972   0.20
88            Vitali Gudiyev    0.375516   0.40
124               Pepe Reina    0.320976   0.50
180                 Jhonatan    0.285638   0.30
110               Caio Secco    0.244926   0.20
128         Tom Vandenberghe    0.237760   0.40
63               Sinan Bolat    0.162686   0.15
168     Koen Van Langendonck    0.152403   0.15
64           Guillermo Ochoa    0.141683   0.50
121        Aleksandr Belenov    0.107764   0.10

In [30]:
comp_leftovers_test.sort_values('Value_pred', ascending=False)

                    Player  Value_pred  Value
25              Alex Meret   25.448597  18.00
36            Marcin Bulka   20.991325  20.00
49               Matz Sels   20.802052   7.00
41                 Alisson   20.774830  20.00
10                 Ederson   19.568675  20.00
30          Dean Henderson   19.482980  20.00
15  Luiz Lucio Reis Junior   10.435337  10.00
40               Nick Pope    9.729860   8.00
4             David de Gea    8.341541   5.00
18            Philipp Kohn    7.475950   5.00
16                 Jose Sa    7.434669   7.00
2               Unai Simon    6.852512  28.00
5           Mads Hermansen    6.830093  15.00
7              Kaua Santos    6.108986   2.50
42          Lukas Hornicek    6.027923   6.00
51           Senne Lammens    5.653202   9.00
38              Inaki Pena    5.230473   8.00
0      Timon Wellenreuther    5.020198   6.00
32             Finn Dahmen    4.716569   9.00
47         Karl Jakob Hein    4.318787   3.00
50         Alphonse Areola    3.746407   9.00
12                  Andrew    3.414380   4.00
9        Martin Delavallee    3.164130   1.50
22            Nicola Leali    2.988503   1.50
26            Bruno Varela    2.885383   2.50
6                   Kaique    2.507585   0.60
45            Dinko Horkas    2.479709   1.20
31            Alban Lafont    2.305355   3.00
27         Vasilios Barkas    2.234555   3.50
23           Peter Gulacsi    2.176702   2.00
14             Alen Sherri    1.834523   1.00
3         Christian Walton    1.770176   1.00
1           Ilya Lantratov    1.575617   2.50
34           Luca Plogmann    1.482413   0.50
17       Bogdan Moskvichev    1.332706   0.80
28           Andrey Lunyov    1.220489   1.20
43        Lukasz Fabianski    1.168474   0.50
44               Davy Roef    0.877752   2.50
33           Alex McCarthy    0.722775   0.35
35            Gavin Bazunu    0.702839   9.00
11           Remko Pasveer    0.676931   0.15
8              Ivan Lomaev    0.646737   1.50
29             Jonas Omlin    0.633941   2.50
48           Jeroen Houwen    0.599151   0.40
39         Marco Silvestri    0.423361   0.50
24              Marko Ilic    0.349776   0.70
19           Sergei Volkov    0.302738   1.00
20                   Cesar    0.286056   0.30
46            Igor Obukhov    0.243016   0.40
37         Sergei Pesyakov    0.233278   0.30
13           Luuk Koopmans    0.194723   0.20
21           Giorgi Shelia    0.183111   0.30

# Модель 2

In [35]:
X_train = X_train[['W', 'PKsv%', '90s', 'GA90', 'Age', 'D', 'CS%', 'Save%' ,'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['W', 'PKsv%', '90s', 'GA90', 'Age', 'D', 'CS%', 'Save%' ,'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [41]:
coeffs_df

               coeff
Age        -0.674138
league_GB1  0.666870
W           0.622551
league_IT1  0.490457
league_ES1  0.452531
league_L1   0.426264
league_FR1  0.416267
GA90       -0.208743
league_PO1  0.144321
90s         0.142297
league_NL1  0.069221
D          -0.055752
PKsv%       0.052072
Save%       0.028177
CS%        -0.015398
league_RU1  0.009419

In [42]:
metrics

            MAE      RMSE      MAPE        R2
test   2.271014  4.372885  0.672511  0.560617
train  2.767798  5.374240  0.567095  0.601540

In [48]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                      Player  Value_pred  Value
56           Bart Verbruggen   43.076504  30.00
126               David Raya   42.617379  40.00
81            Robert Sanchez   40.542227  20.00
82               Mile Svilar   35.710253  25.00
17         Marco Carnesecchi   29.894185  25.00
169          Lucas Chevalier   28.058799  30.00
51           Anatolii Trubin   27.227531  28.00
137     Gianluigi Donnarumma   18.216115  40.00
199         Guillaume Restes   17.236077  20.00
153              Diogo Costa   16.201395  40.00
122         Djordje Petrovic   15.904538  20.00
119             Noah Atubolu   15.004514  18.00
15         Kepa Arrizabalaga   14.980439  10.00
92              Mark Flekken   14.497967  10.00
69        Stanislav Agkatsev   14.352692   7.50
4                Lucas Perri   14.148060  10.00
116          Jordan Pickford   13.436475  18.00
109              Andre Onana   13.006947  25.00
22       Michele Di Gregorio   12.612214  18.00
161               Bernd Leno   12.351066  10.00
194             Mike Maignan   12.226612  25.00
149                Jan Oblak   11.907130  20.00
123       Julen Agirrezabala   11.245714  15.00
99      Giorgi Mamardashvili   11.227167  30.00
24              Elia Caprile   10.996752   9.00
74         Guglielmo Vicario   10.865610  32.00
60              Gregor Kobel   10.835364  40.00
175          Filip Jorgensen   10.351272  18.00
201             Yahia Fofana    9.464563   7.00
166         Thibaut Courtois    9.400412  20.00
20               Zion Suzuki    9.321884  20.00
91             Tiago Cardoso    9.034815   1.50
156           Geronimo Rulli    9.030038   8.00
190         Jakub Stolarczyk    8.523993   1.00
197           Antonin Kinsky    8.170419  15.00
129          Alexander Nubel    7.684805  12.00
87           Gabriel Batista    7.665109   4.00
48    Vanja Milinkovic-Savic    7.547771  16.00
172             Mark Travers    7.542056   4.00
26             Yehvann Diouf    7.342810  12.00
118             Mike Penders    7.303435  12.00
171              Diego Conde    6.984298   7.50
154            Dominik Greif    6.965293   6.00
5                Yann Sommer    6.915203   4.00
133       Yevgeni Latyshonok    6.859770   4.00
57               Alex Remiro    6.748585  18.00
145  Rome-Jayden Owusu-Oduro    6.331120   6.00
151              Razvan Sava    6.082247   2.50
152           Walter Benitez    5.993053   7.50
89           Christos Mandas    5.982995  10.00
184            Ivan Provedel    5.925339   3.00
85               Robin Roefs    5.865719   4.00
136              Brice Samba    5.767366  12.00
159            Robin Zentner    5.693075   4.00
176           Arijanet Muric    5.491288   5.00
185            Kamil Grabara    5.441673  14.00
21            Matvei Safonov    5.412650  20.00
28               Jonas Urbig    5.280541  12.00
155          Augusto Batalla    5.183638   6.00
6               Maduka Okoye    5.174374   7.50
203         Radoslaw Majecki    5.089400   6.00
130           Antonio Sivera    5.046878   6.00
120         Michael Zetterer    4.951286   4.50
100           Aaron Ramsdale    4.942270  16.00
35            Moritz Nicolas    4.876230   5.00
9              Nikola Vasilj    4.845138   3.50
0             Stefano Turati    4.829984   6.50
13             Devis Vasquez    4.576656   2.00
68           Filip Stankovic    4.487313   6.00
111              David Soria    4.457133   3.00
19              Andriy Lunin    4.445886  18.00
33         Federico Ravaglia    4.363690   1.50
11           Lorenzo Montipo    4.213377   2.00
106           Josep Martinez    4.104373  12.00
84          Patrick Sequeira    4.022432   4.00
45             Anthony Moris    3.794388   1.80
46                Jean Butez    3.681020   3.50
36            Sergio Herrera    3.649207   3.00
61                 Rui Silva    3.634122   7.00
191             Alex Padilla    3.618734   3.00
42      Aleksandr Maksimenko    3.597077   4.50
188        Wladimiro Falcone    3.572653   3.50
67             Stefan Ortega    3.455310   8.00
104              Matej Kovar    3.390029   5.00
138        Wojciech Szczesny    3.374814   1.00
94           Paulo Gazzaniga    3.364717   2.50
41            Matthieu Epolo    3.316511   4.00
34            Lukas Hradecky    3.309617   2.00
73              Donovan Leon    3.304907   1.00
53             Franco Israel    3.239328   5.00
78        Gautier Larsonneur    3.102935   3.00
38               Marco Bizot    3.035916   3.00
16               Jesus Owono    2.984826   0.90
117             Manuel Neuer    2.979690   4.00
71                 Leo Roman    2.978152   5.00
178             Mohamed Kone    2.840806   1.20
23             Cezary Miszta    2.808527   3.00
98               Alex Palmer    2.779133   1.00
112              Tobe Leysen    2.768913   4.00
202          Martin Dubravka    2.759689   1.00
93          Lukasz Skorupski    2.722334   2.50
165              Kevin Trapp    2.707367   2.50
86           Colin Coosemans    2.647614   1.50
10                Nico Mantl    2.615972   1.50
177       Semuel Pizzignacco    2.592727   0.80
148          Frederik Ronnow    2.563992   3.00
2              Dani Cardenas    2.456007   1.80
12        Jasper Schendelaar    2.433005   2.50
134      Maarten Vandevoordt    2.412608   8.00
179        Nediljko Labrovic    2.392243   2.50
140            Lazar Carevic    2.312169   1.50
146               Ionut Radu    2.278845   2.50
79                Leo Kokubo    2.213177   3.00
196           Evgenii Staver    2.174467   1.50
14               Mathew Ryan    2.153443   2.50
29              Juan Soriano    2.152163   1.00
115              Kjetil Haug    2.066523   0.60
135        Fabian de Keijzer    2.044647   1.50
167                  Matheus    2.018179   2.50
50              Timon Weiner    2.009016   1.00
101           Vicente Guaita    1.944815   0.70
144          Marko Dmitrovic    1.886072   0.80
43           Andreas Jungdal    1.877150   1.50
44            Ortwin De Wolf    1.874848   1.50
198             Ørjan Nyland    1.871705   0.90
18            Florian Muller    1.849423   1.20
31            Nikita Kokarev    1.810056   1.50
193           Daniel Bielica    1.795508   1.00
127             Lucas Franca    1.788950   1.00
158           Jari De Busser    1.763988   2.00
95            Simone Scuffet    1.743011   2.00
1      Marc-Andre ter Stegen    1.693541  12.00
25                     Kewin    1.640569   1.00
7           Alvaro Fernandez    1.600915   2.00
3                  Nick Olij    1.588880   3.50
27           Maxime Delanghe    1.580692   1.20
96              Mattia Perin    1.556089   2.50
54               Herve Koffi    1.549269   1.20
103             Luca Philipp    1.543663   0.75
58            Simon Mignolet    1.524601   1.20
113         Vladan Kovacevic    1.439026   3.00
70            Rustam Yatimov    1.421657   1.50
141            Arthur Desmas    1.416445   1.20
77             Ricardo Velho    1.338029   4.00
164          Etienne Vaessen    1.296335   2.00
30               Emil Audero    1.278033   3.20
83           Timur Magomedov    1.271640   0.70
37             Sam Johnstone    1.251109   6.00
108               David Volk    1.215309   1.20
75              Kevin Muller    1.194306   0.70
173            Marius Muller    1.176875   1.50
157          Michael Verrips    1.161313   0.80
162              Joao Valido    1.146857   0.30
132     Mattijs Branderhorst    1.145225   0.80
182                   Adrian    1.090542   0.50
195              Ivan Zlobin    1.068643   1.50
8              Anthony Lopes    1.056818   1.20
147          Daniil Odoevski    1.036787   0.80
114   Hendrik Van Crombrugge    1.029609   1.70
32          Jasper Cillessen    1.024152   0.80
150          Lars Unnerstall    1.013436   2.00
55            Oliver Baumann    1.001934   3.00
192          Thomas Didillon    0.964788   0.90
66         Pierluigi Gollini    0.942100   1.00
107                Timo Horn    0.935665   0.80
40   Joao Paulo Santos Costa    0.924011   0.80
90         Patrik Gunnarsson    0.896504   1.00
183             Thomas Dahne    0.879934   0.40
72              Nick Shinton    0.878256   0.60
131           Nordin Jackers    0.878136   1.20
62            Patrick Drewes    0.872901   0.50
163            Nordin Bakker    0.871515   0.70
49          Mathieu Gorgelin    0.807916   0.30
47        Aleksandr Vasyutin    0.801963   0.90
59             Jesse Joronen    0.780546   0.50
76            Fraser Forster    0.772716   1.00
187         Benjamin Lecomte    0.735987   1.50
189          Patrik Carlgren    0.730707   0.60
174              Joel Robles    0.722602   0.50
143          Nikita Medvedev    0.707043   0.80
39           Andries Noppert    0.696438   1.00
181            Igor Akinfeev    0.650741   1.00
142            Igor Leshchuk    0.616531   0.70
200        Anton Mitryushkin    0.596156   1.80
139              Jeroen Zoet    0.560009   0.30
65        Alexander Schwolow    0.555693   0.50
170          Nikolai Sysuyev    0.549037   0.80
186           Steve Mandanda    0.530145   0.50
160      Mickey van der Hart    0.519767   0.50
80            Andre Ferreira    0.496587   0.70
105            Davor Matijas    0.447740   0.40
52                  Warleson    0.433688   2.50
97            Simao Bertelli    0.431247   0.30
125            Bruno Brigido    0.375183   0.20
102             Lucas Pirard    0.370735   0.25
88            Vitali Gudiyev    0.361475   0.40
124               Pepe Reina    0.316121   0.50
180                 Jhonatan    0.288132   0.30
110               Caio Secco    0.249742   0.20
128         Tom Vandenberghe    0.245661   0.40
63               Sinan Bolat    0.159331   0.15
168     Koen Van Langendonck    0.159172   0.15
64           Guillermo Ochoa    0.139240   0.50
121        Aleksandr Belenov    0.104005   0.10

In [44]:
comp_leftovers_test

                    Player  Value_pred  Value
0      Timon Wellenreuther    5.617790   6.00
1           Ilya Lantratov    1.492195   2.50
2               Unai Simon    7.605972  28.00
3         Christian Walton    1.810015   1.00
4             David de Gea    9.330813   5.00
5           Mads Hermansen    6.910078  15.00
6                   Kaique    3.234330   0.60
7              Kaua Santos    5.889263   2.50
8              Ivan Lomaev    0.710235   1.50
9        Martin Delavallee    3.030339   1.50
10                 Ederson   19.035955  20.00
11           Remko Pasveer    0.682348   0.15
12                  Andrew    3.249970   4.00
13           Luuk Koopmans    0.234410   0.20
14             Alen Sherri    1.844940   1.00
15  Luiz Lucio Reis Junior   10.297069  10.00
16                 Jose Sa    7.628957   7.00
17       Bogdan Moskvichev    1.426238   0.80
18            Philipp Kohn    7.264662   5.00
19           Sergei Volkov    0.292842   1.00
20                   Cesar    0.284669   0.30
21           Giorgi Shelia    0.171157   0.30
22            Nicola Leali    3.067900   1.50
23           Peter Gulacsi    2.274393   2.00
24              Marko Ilic    0.355054   0.70
25              Alex Meret   29.421746  18.00
26            Bruno Varela    2.809003   2.50
27         Vasilios Barkas    2.181499   3.50
28           Andrey Lunyov    1.139089   1.20
29             Jonas Omlin    0.678960   2.50
30          Dean Henderson   20.852059  20.00
31            Alban Lafont    2.279210   3.00
32             Finn Dahmen    4.520476   9.00
33           Alex McCarthy    0.760451   0.35
34           Luca Plogmann    1.496317   0.50
35            Gavin Bazunu    0.689430   9.00
36            Marcin Bulka   21.370559  20.00
37         Sergei Pesyakov    0.223932   0.30
38              Inaki Pena    5.137312   8.00
39         Marco Silvestri    0.437245   0.50
40               Nick Pope   10.584637   8.00
41                 Alisson   20.125166  20.00
42          Lukas Hornicek    5.957410   6.00
43        Lukasz Fabianski    1.161667   0.50
44               Davy Roef    0.843164   2.50
45            Dinko Horkas    2.803484   1.20
46            Igor Obukhov    0.272914   0.40
47         Karl Jakob Hein    4.133153   3.00
48           Jeroen Houwen    0.598660   0.40
49               Matz Sels   20.016246   7.00
50         Alphonse Areola    3.610974   9.00
51           Senne Lammens    5.858547   9.00

# Модель 3

In [51]:
X_train = X_train[['W', 'PKsv%', 'GA90', 'Age', 'CS', 'CS%', 'Save%' ,'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['W', 'PKsv%', 'GA90', 'Age', 'CS', 'CS%', 'Save%' ,'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [57]:
coeffs_df

               coeff
W           0.700690
Age        -0.675922
league_GB1  0.669110
league_IT1  0.496733
league_ES1  0.457510
league_L1   0.424145
league_FR1  0.423984
GA90       -0.171028
league_PO1  0.150236
league_NL1  0.080353
PKsv%       0.065488
Save%       0.037439
CS%        -0.026354
CS          0.018758
league_RU1  0.009519

In [58]:
metrics

            MAE      RMSE      MAPE        R2
test   2.375219  4.504631  0.701419  0.533743
train  2.768157  5.414380  0.565917  0.595565

In [61]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                      Player  Value_pred  Value
126               David Raya   44.779704  40.00
56           Bart Verbruggen   43.854366  30.00
81            Robert Sanchez   41.820546  20.00
82               Mile Svilar   35.869691  25.00
17         Marco Carnesecchi   30.003500  25.00
51           Anatolii Trubin   28.882270  28.00
169          Lucas Chevalier   28.451746  30.00
137     Gianluigi Donnarumma   19.688393  40.00
199         Guillaume Restes   16.813557  20.00
153              Diogo Costa   16.698517  40.00
122         Djordje Petrovic   16.425053  20.00
119             Noah Atubolu   15.880871  18.00
69        Stanislav Agkatsev   15.566118   7.50
15         Kepa Arrizabalaga   14.343082  10.00
4                Lucas Perri   14.142310  10.00
92              Mark Flekken   14.029531  10.00
116          Jordan Pickford   13.785156  18.00
22       Michele Di Gregorio   13.390222  18.00
194             Mike Maignan   12.341427  25.00
149                Jan Oblak   12.205074  20.00
109              Andre Onana   12.045620  25.00
123       Julen Agirrezabala   11.901183  15.00
161               Bernd Leno   11.634434  10.00
99      Giorgi Mamardashvili   11.059894  30.00
24              Elia Caprile   10.745920   9.00
175          Filip Jorgensen   10.714035  18.00
60              Gregor Kobel   10.444681  40.00
74         Guglielmo Vicario   10.190769  32.00
166         Thibaut Courtois    9.741575  20.00
156           Geronimo Rulli    9.252038   8.00
91             Tiago Cardoso    8.840523   1.50
20               Zion Suzuki    8.815734  20.00
201             Yahia Fofana    8.735009   7.00
190         Jakub Stolarczyk    8.504612   1.00
197           Antonin Kinsky    8.443356  15.00
172             Mark Travers    7.759964   4.00
48    Vanja Milinkovic-Savic    7.494592  16.00
129          Alexander Nubel    7.412396  12.00
87           Gabriel Batista    7.386100   4.00
171              Diego Conde    7.277047   7.50
5                Yann Sommer    7.275789   4.00
118             Mike Penders    7.240992  12.00
133       Yevgeni Latyshonok    7.216395   4.00
26             Yehvann Diouf    6.814072  12.00
145  Rome-Jayden Owusu-Oduro    6.623499   6.00
154            Dominik Greif    6.530589   6.00
151              Razvan Sava    6.360330   2.50
152           Walter Benitez    6.332516   7.50
57               Alex Remiro    6.185755  18.00
89           Christos Mandas    6.070194  10.00
184            Ivan Provedel    5.882250   3.00
136              Brice Samba    5.788577  12.00
85               Robin Roefs    5.727970   4.00
159            Robin Zentner    5.558636   4.00
21            Matvei Safonov    5.494003  20.00
28               Jonas Urbig    5.455233  12.00
176           Arijanet Muric    5.443779   5.00
185            Kamil Grabara    5.241759  14.00
203         Radoslaw Majecki    5.183315   6.00
155          Augusto Batalla    5.177638   6.00
35            Moritz Nicolas    4.924380   5.00
120         Michael Zetterer    4.851710   4.50
130           Antonio Sivera    4.813535   6.00
6               Maduka Okoye    4.764364   7.50
68           Filip Stankovic    4.630705   6.00
19              Andriy Lunin    4.435678  18.00
13             Devis Vasquez    4.420451   2.00
100           Aaron Ramsdale    4.352916  16.00
9              Nikola Vasilj    4.350777   3.50
0             Stefano Turati    4.320214   6.50
33         Federico Ravaglia    4.196427   1.50
106           Josep Martinez    4.077753  12.00
45             Anthony Moris    4.029826   1.80
84          Patrick Sequeira    3.934997   4.00
111              David Soria    3.914258   3.00
191             Alex Padilla    3.884889   3.00
11           Lorenzo Montipo    3.820405   2.00
61                 Rui Silva    3.739532   7.00
36            Sergio Herrera    3.686361   3.00
46                Jean Butez    3.622882   3.50
67             Stefan Ortega    3.569342   8.00
34            Lukas Hradecky    3.524061   2.00
42      Aleksandr Maksimenko    3.480246   4.50
138        Wojciech Szczesny    3.436719   1.00
104              Matej Kovar    3.317869   5.00
41            Matthieu Epolo    3.288990   4.00
53             Franco Israel    3.279699   5.00
73              Donovan Leon    3.246289   1.00
188        Wladimiro Falcone    3.198827   3.50
94           Paulo Gazzaniga    3.156125   2.50
71                 Leo Roman    3.077215   5.00
117             Manuel Neuer    3.032236   4.00
16               Jesus Owono    2.994846   0.90
93          Lukasz Skorupski    2.964948   2.50
38               Marco Bizot    2.963020   3.00
78        Gautier Larsonneur    2.908876   3.00
165              Kevin Trapp    2.903493   2.50
98               Alex Palmer    2.850069   1.00
23             Cezary Miszta    2.814963   3.00
112              Tobe Leysen    2.763911   4.00
202          Martin Dubravka    2.750843   1.00
178             Mohamed Kone    2.745755   1.20
177       Semuel Pizzignacco    2.737711   0.80
148          Frederik Ronnow    2.564780   3.00
86           Colin Coosemans    2.553647   1.50
134      Maarten Vandevoordt    2.528689   8.00
10                Nico Mantl    2.499778   1.50
2              Dani Cardenas    2.458326   1.80
179        Nediljko Labrovic    2.447661   2.50
12        Jasper Schendelaar    2.422981   2.50
140            Lazar Carevic    2.323316   1.50
146               Ionut Radu    2.290960   2.50
14               Mathew Ryan    2.214005   2.50
29              Juan Soriano    2.188946   1.00
79                Leo Kokubo    2.149865   3.00
115              Kjetil Haug    2.128499   0.60
196           Evgenii Staver    2.123220   1.50
167                  Matheus    2.065072   2.50
135        Fabian de Keijzer    2.051103   1.50
43           Andreas Jungdal    1.988008   1.50
18            Florian Muller    1.903025   1.20
158           Jari De Busser    1.900486   2.00
50              Timon Weiner    1.893820   1.00
31            Nikita Kokarev    1.885246   1.50
101           Vicente Guaita    1.827438   0.70
144          Marko Dmitrovic    1.825555   0.80
44            Ortwin De Wolf    1.815225   1.50
198             Ørjan Nyland    1.810475   0.90
95            Simone Scuffet    1.783492   2.00
1      Marc-Andre ter Stegen    1.760220  12.00
103             Luca Philipp    1.734128   0.75
193           Daniel Bielica    1.732469   1.00
7           Alvaro Fernandez    1.641485   2.00
54               Herve Koffi    1.641018   1.20
127             Lucas Franca    1.633985   1.00
27           Maxime Delanghe    1.596620   1.20
58            Simon Mignolet    1.576464   1.20
3                  Nick Olij    1.562916   3.50
96              Mattia Perin    1.550654   2.50
25                     Kewin    1.545453   1.00
70            Rustam Yatimov    1.441153   1.50
113         Vladan Kovacevic    1.420973   3.00
141            Arthur Desmas    1.400842   1.20
30               Emil Audero    1.390980   3.20
37             Sam Johnstone    1.338069   6.00
164          Etienne Vaessen    1.288235   2.00
83           Timur Magomedov    1.258491   0.70
77             Ricardo Velho    1.224686   4.00
162              Joao Valido    1.206065   0.30
173            Marius Muller    1.196848   1.50
108               David Volk    1.163804   1.20
132     Mattijs Branderhorst    1.143092   0.80
182                   Adrian    1.126934   0.50
157          Michael Verrips    1.114138   0.80
195              Ivan Zlobin    1.098125   1.50
8              Anthony Lopes    1.080372   1.20
114   Hendrik Van Crombrugge    1.049755   1.70
147          Daniil Odoevski    1.045859   0.80
150          Lars Unnerstall    1.037940   2.00
75              Kevin Muller    1.037252   0.70
66         Pierluigi Gollini    1.026641   1.00
32          Jasper Cillessen    1.012873   0.80
55            Oliver Baumann    0.971307   3.00
183             Thomas Dahne    0.945867   0.40
107                Timo Horn    0.914665   0.80
40   Joao Paulo Santos Costa    0.907470   0.80
90         Patrik Gunnarsson    0.890969   1.00
72              Nick Shinton    0.877407   0.60
192          Thomas Didillon    0.873369   0.90
131           Nordin Jackers    0.857369   1.20
47        Aleksandr Vasyutin    0.856888   0.90
49          Mathieu Gorgelin    0.849363   0.30
62            Patrick Drewes    0.836323   0.50
76            Fraser Forster    0.831601   1.00
59             Jesse Joronen    0.808496   0.50
163            Nordin Bakker    0.805681   0.70
189          Patrik Carlgren    0.782010   0.60
174              Joel Robles    0.725255   0.50
39           Andries Noppert    0.711953   1.00
143          Nikita Medvedev    0.659394   0.80
187         Benjamin Lecomte    0.649218   1.50
181            Igor Akinfeev    0.642970   1.00
142            Igor Leshchuk    0.625617   0.70
200        Anton Mitryushkin    0.599445   1.80
65        Alexander Schwolow    0.583240   0.50
80            Andre Ferreira    0.572711   0.70
139              Jeroen Zoet    0.557054   0.30
160      Mickey van der Hart    0.545203   0.50
170          Nikolai Sysuyev    0.536934   0.80
186           Steve Mandanda    0.521593   0.50
97            Simao Bertelli    0.457569   0.30
105            Davor Matijas    0.441842   0.40
52                  Warleson    0.441641   2.50
102             Lucas Pirard    0.381622   0.25
125            Bruno Brigido    0.370677   0.20
88            Vitali Gudiyev    0.350573   0.40
124               Pepe Reina    0.317043   0.50
180                 Jhonatan    0.299450   0.30
110               Caio Secco    0.270337   0.20
128         Tom Vandenberghe    0.237454   0.40
63               Sinan Bolat    0.167022   0.15
168     Koen Van Langendonck    0.158433   0.15
64           Guillermo Ochoa    0.134802   0.50
121        Aleksandr Belenov    0.100329   0.10

In [60]:
comp_leftovers_test

                    Player  Value_pred  Value
0      Timon Wellenreuther    6.225886   6.00
1           Ilya Lantratov    1.509380   2.50
2               Unai Simon    7.961154  28.00
3         Christian Walton    1.981683   1.00
4             David de Gea    9.314734   5.00
5           Mads Hermansen    6.489912  15.00
6                   Kaique    3.445405   0.60
7              Kaua Santos    6.029480   2.50
8              Ivan Lomaev    0.722780   1.50
9        Martin Delavallee    3.064768   1.50
10                 Ederson   18.837969  20.00
11           Remko Pasveer    0.722776   0.15
12                  Andrew    2.967807   4.00
13           Luuk Koopmans    0.274861   0.20
14             Alen Sherri    1.911059   1.00
15  Luiz Lucio Reis Junior   10.588854  10.00
16                 Jose Sa    7.306583   7.00
17       Bogdan Moskvichev    1.445597   0.80
18            Philipp Kohn    7.516993   5.00
19           Sergei Volkov    0.284453   1.00
20                   Cesar    0.278585   0.30
21           Giorgi Shelia    0.163749   0.30
22            Nicola Leali    2.986894   1.50
23           Peter Gulacsi    2.383777   2.00
24              Marko Ilic    0.375544   0.70
25              Alex Meret   32.154793  18.00
26            Bruno Varela    2.828969   2.50
27         Vasilios Barkas    2.335147   3.50
28           Andrey Lunyov    1.140523   1.20
29             Jonas Omlin    0.729906   2.50
30          Dean Henderson   21.122240  20.00
31            Alban Lafont    2.336389   3.00
32             Finn Dahmen    4.410862   9.00
33           Alex McCarthy    0.842535   0.35
34           Luca Plogmann    1.571339   0.50
35            Gavin Bazunu    0.699696   9.00
36            Marcin Bulka   22.265766  20.00
37         Sergei Pesyakov    0.223814   0.30
38              Inaki Pena    5.088193   8.00
39         Marco Silvestri    0.474088   0.50
40               Nick Pope   10.632901   8.00
41                 Alisson   21.044750  20.00
42          Lukas Hornicek    6.095448   6.00
43        Lukasz Fabianski    1.212281   0.50
44               Davy Roef    0.859325   2.50
45            Dinko Horkas    2.763565   1.20
46            Igor Obukhov    0.299580   0.40
47         Karl Jakob Hein    3.583682   3.00
48           Jeroen Houwen    0.573884   0.40
49               Matz Sels   19.477190   7.00
50         Alphonse Areola    3.391422   9.00
51           Senne Lammens    5.777041   9.00

# Модель 4

In [66]:
X_train = X_train[['W', '90s', 'PKsv%', 'GA90', 'Age', 'CS%' ,'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['W', '90s', 'PKsv%', 'GA90', 'Age', 'CS%' ,'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [72]:
coeffs_df

               coeff
Age        -0.674760
league_GB1  0.670090
W           0.637754
league_IT1  0.488408
league_ES1  0.452761
league_L1   0.425379
league_FR1  0.424756
GA90       -0.212306
league_PO1  0.146867
90s         0.088225
league_NL1  0.070699
PKsv%       0.050258
league_RU1  0.014313
CS%        -0.010446

In [73]:
metrics

            MAE      RMSE      MAPE        R2
test   2.290762  4.369917  0.660419  0.561213
train  2.767814  5.409834  0.566300  0.596244

# Модель 5

In [78]:
X_train = X_train[['90s', 'PKsv%', 'GA90', 'Age', 'CS%', 'Save%', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['90s', 'PKsv%', 'GA90', 'Age', 'CS%', 'Save%', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [84]:
coeffs_df

               coeff
league_GB1  0.685395
Age        -0.626589
90s         0.547705
GA90       -0.459792
league_FR1  0.457386
league_L1   0.455685
league_IT1  0.444537
league_ES1  0.442449
league_PO1  0.126352
Save%      -0.072955
CS%         0.071540
league_NL1  0.042188
PKsv%       0.002630
league_RU1 -0.000649

In [85]:
metrics

            MAE      RMSE      MAPE        R2
test   2.333813  4.004961  0.593402  0.631444
train  2.970635  5.916928  0.656951  0.517004

In [86]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                      Player  Value_pred  Value
56           Bart Verbruggen   40.620113  30.00
126               David Raya   36.397300  40.00
81            Robert Sanchez   28.686572  20.00
199         Guillaume Restes   24.408996  20.00
169          Lucas Chevalier   23.395670  30.00
82               Mile Svilar   21.204243  25.00
116          Jordan Pickford   21.001354  18.00
109              Andre Onana   19.998150  25.00
20               Zion Suzuki   17.195509  20.00
17         Marco Carnesecchi   16.339516  25.00
15         Kepa Arrizabalaga   14.579476  10.00
99      Giorgi Mamardashvili   12.730947  30.00
122         Djordje Petrovic   12.433807  20.00
26             Yehvann Diouf   11.893107  12.00
91             Tiago Cardoso   11.642296   1.50
161               Bernd Leno   11.572719  10.00
22       Michele Di Gregorio   11.224214  18.00
201             Yahia Fofana   11.046135   7.00
92              Mark Flekken   10.845012  10.00
74         Guglielmo Vicario   10.505561  32.00
119             Noah Atubolu   10.439662  18.00
48    Vanja Milinkovic-Savic   10.209394  16.00
4                Lucas Perri    9.703350  10.00
51           Anatolii Trubin    9.690282  28.00
24              Elia Caprile    9.484860   9.00
123       Julen Agirrezabala    9.414058  15.00
137     Gianluigi Donnarumma    8.882040  40.00
190         Jakub Stolarczyk    8.838253   1.00
194             Mike Maignan    8.621207  25.00
149                Jan Oblak    8.557220  20.00
175          Filip Jorgensen    8.355227  18.00
172             Mark Travers    8.311862   4.00
154            Dominik Greif    8.290491   6.00
89           Christos Mandas    8.260814  10.00
57               Alex Remiro    8.161627  18.00
153              Diogo Costa    8.108492  40.00
9              Nikola Vasilj    8.107158   3.50
100           Aaron Ramsdale    7.721193  16.00
0             Stefano Turati    7.573430   6.50
60              Gregor Kobel    7.477221  40.00
13             Devis Vasquez    7.471653   2.00
130           Antonio Sivera    7.419834   6.00
111              David Soria    7.261421   3.00
197           Antonin Kinsky    6.962139  15.00
129          Alexander Nubel    6.856273  12.00
176           Arijanet Muric    6.793277   5.00
155          Augusto Batalla    6.726018   6.00
69        Stanislav Agkatsev    6.565978   7.50
41            Matthieu Epolo    6.390968   4.00
145  Rome-Jayden Owusu-Oduro    6.249078   6.00
33         Federico Ravaglia    6.221862   1.50
159            Robin Zentner    5.854125   4.00
21            Matvei Safonov    5.736655  20.00
28               Jonas Urbig    5.639754  12.00
185            Kamil Grabara    5.581341  14.00
188        Wladimiro Falcone    5.564822   3.50
87           Gabriel Batista    5.464041   4.00
6               Maduka Okoye    5.438386   7.50
112              Tobe Leysen    5.306829   4.00
85               Robin Roefs    5.187220   4.00
151              Razvan Sava    5.040262   2.50
104              Matej Kovar    4.945395   5.00
11           Lorenzo Montipo    4.932708   2.00
136              Brice Samba    4.850509  12.00
106           Josep Martinez    4.834945  12.00
166         Thibaut Courtois    4.809546  20.00
19              Andriy Lunin    4.794286  18.00
118             Mike Penders    4.605838  12.00
120         Michael Zetterer    4.594255   4.50
203         Radoslaw Majecki    4.560476   6.00
36            Sergio Herrera    4.536583   3.00
171              Diego Conde    4.413767   7.50
156           Geronimo Rulli    4.313989   8.00
133       Yevgeni Latyshonok    4.165396   4.00
68           Filip Stankovic    4.067021   6.00
94           Paulo Gazzaniga    4.034975   2.50
73              Donovan Leon    3.884531   1.00
148          Frederik Ronnow    3.846720   3.00
184            Ivan Provedel    3.793538   3.00
67             Stefan Ortega    3.748949   8.00
35            Moritz Nicolas    3.727685   5.00
5                Yann Sommer    3.675834   4.00
84          Patrick Sequeira    3.630423   4.00
16               Jesus Owono    3.612717   0.90
46                Jean Butez    3.442623   3.50
53             Franco Israel    3.416505   5.00
42      Aleksandr Maksimenko    3.329884   4.50
78        Gautier Larsonneur    3.311451   3.00
146               Ionut Radu    3.222543   2.50
10                Nico Mantl    3.163865   1.50
178             Mohamed Kone    3.059065   1.20
115              Kjetil Haug    3.057159   0.60
198             Ørjan Nyland    3.003755   0.90
144          Marko Dmitrovic    2.977039   0.80
2              Dani Cardenas    2.918010   1.80
61                 Rui Silva    2.865386   7.00
12        Jasper Schendelaar    2.849825   2.50
23             Cezary Miszta    2.848876   3.00
202          Martin Dubravka    2.841732   1.00
93          Lukasz Skorupski    2.793638   2.50
38               Marco Bizot    2.785838   3.00
191             Alex Padilla    2.748472   3.00
77             Ricardo Velho    2.666296   4.00
98               Alex Palmer    2.613368   1.00
71                 Leo Roman    2.522730   5.00
44            Ortwin De Wolf    2.517110   1.50
138        Wojciech Szczesny    2.514723   1.00
29              Juan Soriano    2.483155   1.00
79                Leo Kokubo    2.425182   3.00
34            Lukas Hradecky    2.420724   2.00
108               David Volk    2.419785   1.20
96              Mattia Perin    2.413881   2.50
117             Manuel Neuer    2.398860   4.00
140            Lazar Carevic    2.302817   1.50
45             Anthony Moris    2.295000   1.80
127             Lucas Franca    2.260792   1.00
27           Maxime Delanghe    2.215214   1.20
179        Nediljko Labrovic    2.187036   2.50
50              Timon Weiner    2.182599   1.00
3                  Nick Olij    2.173610   3.50
86           Colin Coosemans    2.165724   1.50
134      Maarten Vandevoordt    2.139433   8.00
135        Fabian de Keijzer    2.094251   1.50
165              Kevin Trapp    2.070514   2.50
193           Daniel Bielica    2.056845   1.00
14               Mathew Ryan    2.046834   2.50
177       Semuel Pizzignacco    2.044087   0.80
25                     Kewin    1.962997   1.00
101           Vicente Guaita    1.950653   0.70
75              Kevin Muller    1.834604   0.70
152           Walter Benitez    1.817460   7.50
31            Nikita Kokarev    1.736135   1.50
18            Florian Muller    1.639092   1.20
113         Vladan Kovacevic    1.637930   3.00
196           Evgenii Staver    1.621126   1.50
163            Nordin Bakker    1.619982   0.70
7           Alvaro Fernandez    1.615682   2.00
167                  Matheus    1.536719   2.50
173            Marius Muller    1.532180   1.50
95            Simone Scuffet    1.531358   2.00
43           Andreas Jungdal    1.490964   1.50
195              Ivan Zlobin    1.446368   1.50
192          Thomas Didillon    1.439549   0.90
8              Anthony Lopes    1.439447   1.20
164          Etienne Vaessen    1.368932   2.00
54               Herve Koffi    1.356356   1.20
158           Jari De Busser    1.338164   2.00
55            Oliver Baumann    1.335558   3.00
141            Arthur Desmas    1.277229   1.20
107                Timo Horn    1.267760   0.80
131           Nordin Jackers    1.264553   1.20
83           Timur Magomedov    1.250400   0.70
1      Marc-Andre ter Stegen    1.241078  12.00
32          Jasper Cillessen    1.233299   0.80
162              Joao Valido    1.227488   0.30
157          Michael Verrips    1.206115   0.80
132     Mattijs Branderhorst    1.199878   0.80
187         Benjamin Lecomte    1.170011   1.50
40   Joao Paulo Santos Costa    1.165665   0.80
70            Rustam Yatimov    1.148886   1.50
62            Patrick Drewes    1.132922   0.50
72              Nick Shinton    1.088598   0.60
103             Luca Philipp    1.020922   0.75
147          Daniil Odoevski    1.011755   0.80
150          Lars Unnerstall    1.009240   2.00
37             Sam Johnstone    0.996818   6.00
90         Patrik Gunnarsson    0.945657   1.00
182                   Adrian    0.871845   0.50
200        Anton Mitryushkin    0.871309   1.80
189          Patrik Carlgren    0.840947   0.60
58            Simon Mignolet    0.834090   1.20
30               Emil Audero    0.827215   3.20
186           Steve Mandanda    0.806582   0.50
49          Mathieu Gorgelin    0.748963   0.30
143          Nikita Medvedev    0.733282   0.80
174              Joel Robles    0.726945   0.50
114   Hendrik Van Crombrugge    0.720766   1.70
66         Pierluigi Gollini    0.708965   1.00
139              Jeroen Zoet    0.700750   0.30
181            Igor Akinfeev    0.679385   1.00
76            Fraser Forster    0.672880   1.00
59             Jesse Joronen    0.667014   0.50
142            Igor Leshchuk    0.662100   0.70
88            Vitali Gudiyev    0.658213   0.40
183             Thomas Dahne    0.631476   0.40
170          Nikolai Sysuyev    0.608519   0.80
39           Andries Noppert    0.526521   1.00
97            Simao Bertelli    0.522049   0.30
47        Aleksandr Vasyutin    0.483355   0.90
160      Mickey van der Hart    0.476212   0.50
65        Alexander Schwolow    0.439875   0.50
105            Davor Matijas    0.427318   0.40
124               Pepe Reina    0.408592   0.50
125            Bruno Brigido    0.401412   0.20
102             Lucas Pirard    0.359247   0.25
52                  Warleson    0.336467   2.50
180                 Jhonatan    0.286902   0.30
110               Caio Secco    0.239642   0.20
168     Koen Van Langendonck    0.221802   0.15
80            Andre Ferreira    0.217543   0.70
128         Tom Vandenberghe    0.202143   0.40
64           Guillermo Ochoa    0.201263   0.50
121        Aleksandr Belenov    0.177206   0.10
63               Sinan Bolat    0.127264   0.15

In [87]:
comp_leftovers_test

                    Player  Value_pred  Value
0      Timon Wellenreuther    2.568340   6.00
1           Ilya Lantratov    0.809570   2.50
2               Unai Simon    8.599509  28.00
3         Christian Walton    1.285371   1.00
4             David de Gea    4.641305   5.00
5           Mads Hermansen    8.509222  15.00
6                   Kaique    2.482537   0.60
7              Kaua Santos    4.766536   2.50
8              Ivan Lomaev    0.695744   1.50
9        Martin Delavallee    2.531262   1.50
10                 Ederson   14.328825  20.00
11           Remko Pasveer    0.405878   0.15
12                  Andrew    4.936579   4.00
13           Luuk Koopmans    0.124071   0.20
14             Alen Sherri    1.746947   1.00
15  Luiz Lucio Reis Junior    7.788065  10.00
16                 Jose Sa    7.513548   7.00
17       Bogdan Moskvichev    1.223612   0.80
18            Philipp Kohn    7.483118   5.00
19           Sergei Volkov    0.324962   1.00
20                   Cesar    0.368427   0.30
21           Giorgi Shelia    0.364862   0.30
22            Nicola Leali    4.521378   1.50
23           Peter Gulacsi    2.702293   2.00
24              Marko Ilic    0.280531   0.70
25              Alex Meret   15.516010  18.00
26            Bruno Varela    3.426825   2.50
27         Vasilios Barkas    1.271699   3.50
28           Andrey Lunyov    0.744140   1.20
29             Jonas Omlin    0.423273   2.50
30          Dean Henderson   27.200409  20.00
31            Alban Lafont    3.057612   3.00
32             Finn Dahmen    6.413912   9.00
33           Alex McCarthy    0.459766   0.35
34           Luca Plogmann    1.126343   0.50
35            Gavin Bazunu    0.741862   9.00
36            Marcin Bulka   14.515332  20.00
37         Sergei Pesyakov    0.199211   0.30
38              Inaki Pena    5.040015   8.00
39         Marco Silvestri    0.316646   0.50
40               Nick Pope    8.790639   8.00
41                 Alisson   12.633049  20.00
42          Lukas Hornicek    5.418225   6.00
43        Lukasz Fabianski    1.021685   0.50
44               Davy Roef    1.130121   2.50
45            Dinko Horkas    2.604023   1.20
46            Igor Obukhov    0.196514   0.40
47         Karl Jakob Hein    5.735429   3.00
48           Jeroen Houwen    0.656090   0.40
49               Matz Sels   15.041161   7.00
50         Alphonse Areola    5.904879   9.00
51           Senne Lammens    5.659022   9.00