In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_rows', None)

In [80]:
X_train = pd.read_csv('csv/final_datasets/for_linear_model/MF/predictors_train_filtered.csv')
X_test = pd.read_csv('csv/final_datasets/for_linear_model/MF/predictors_test_filtered.csv')
y_train = pd.read_csv('csv/final_datasets/for_linear_model/MF/target_train_filtered_logariphmed.csv')
y_test = pd.read_csv('csv/final_datasets/for_linear_model/MF/target_test_filtered_logariphmed.csv')

In [4]:
train_players = pd.read_csv('csv/final_datasets/for_linear_model/MF/train_players_names.csv')
test_players = pd.read_csv('csv/final_datasets/for_linear_model/MF/test_players_names.csv')

In [5]:
all_cols = X_train.columns
all_cols

Index(['Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
       '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh', 'SoT',
       'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'],
      dtype='object')

## Регрессор

In [83]:
LR_regressor = LinearRegression()
LR_regressor.fit(X_train, y_train)

LinearRegression()

## Предсказанные значения

In [84]:
y_pred_log = LR_regressor.predict(X_test)
y_pred = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

y_train_pred = np.exp(LR_regressor.predict(X_train))
y_train_original = np.exp(y_train)

## Метрики

In [85]:
mae_test = mean_absolute_error(y_test_original, y_pred)
rmse_test = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2_test = r2_score(y_test_original, y_pred)
mape_test = mean_absolute_percentage_error(y_test_original, y_pred)

mae_train = mean_absolute_error(y_train_original, y_train_pred)
rmse_train = np.sqrt(mean_squared_error(y_train_original, y_train_pred))
r2_train = r2_score(y_train_original, y_train_pred)
mape_train = mean_absolute_percentage_error(y_train_original, y_train_pred)

metrics = pd.DataFrame({
    'MAE':[mae_test, mae_train],
    'RMSE':[rmse_test, rmse_train],
    'MAPE':[mape_test, mape_train],
    'R2':[r2_test, r2_train]
}, index = ['test', 'train'])

## Остатки

In [86]:
y_pred = pd.Series(np.reshape(y_pred, len(y_pred)), name='Value_pred')
y_train_pred = pd.Series(np.reshape(y_train_pred, len(y_train_pred)), name='Value_pred')

comp_leftovers_test = pd.concat([test_players, y_pred, y_test_original], axis=1)
comp_leftovers_train = pd.concat([train_players, y_train_pred, y_train_original], axis=1)

## Коэффициенты

In [87]:
coeffs = LR_regressor.coef_[0]
coeffs_df = pd.DataFrame({
    'coeff':coeffs.astype('float')
}, index=X_train.columns)
coeffs_df = coeffs_df.sort_values(by='coeff', key=abs, ascending=False)

<b>Все переменные</b>

In [12]:
coeffs_df

                coeff
90s         16.319206
Min        -16.089723
league_GB1   0.567529
Gls.1        0.465130
Age         -0.421172
G+A-PK      -0.377476
league_IT1   0.365412
league_ES1   0.299258
league_L1    0.278807
Ast          0.243098
league_FR1   0.238604
Ast.1        0.202051
Sh           0.190806
Starts       0.180821
PKatt       -0.171988
SoT         -0.159929
G+A.1        0.153020
Fld          0.134361
CrdY        -0.132631
G-PK.1      -0.128261
Off         -0.122311
G+A          0.121322
league_NL1  -0.111190
league_RU1  -0.106033
SoT%         0.101126
Crs         -0.089810
G/Sh         0.084226
Sh/90        0.077462
G/SoT       -0.075131
PK           0.065260
league_PO1  -0.064004
Int          0.050804
OG          -0.048451
MP           0.028818
Fls          0.027337
CrdR        -0.026244
G-PK        -0.026115
TklW        -0.019426
2CrdY        0.013754
SoT/90       0.007689
Gls         -0.006719

In [13]:
metrics

            MAE       RMSE      MAPE        R2
test   5.774406  15.347800  1.022365  0.478862
train  5.387281  11.309522  0.841682  0.440134

In [14]:
comp_leftovers_test

                       Player  Value_pred    Value
0                Sandi Lovric   14.820001    8.500
1              Danila Godiaev    0.937032    1.500
2     Inigo Ruiz de Galarreta    3.693768    3.000
3              Johnny Cardoso   13.330161   25.000
4                  Unai Lopez    4.158035    2.500
5          Florian Grillitsch    2.577003    2.000
6              Mahmoud Dahoud    2.684127    3.500
7               Teji Savanier    7.063929    2.500
8                Djaoui Cisse    6.261746    8.000
9               Dean Huiberts    0.863534    0.300
10            Khephren Thuram   26.097409   40.000
11                 Pape Gueye    8.807355   15.000
12      Thomas Van den Keybus    1.189198    0.800
13              Sandro Tonali   38.117542   60.000
14     Ibrahima Sory Bangoura    2.187292    8.000
15        Vladimir Moskvichev    0.454671    0.500
16               Lasse Schone    0.131918    0.075
17            Kalvin Phillips    4.820760   12.000
18         Morgan Gibbs-White   80.055294   50.000
19              Ilija Vukotic    1.547208    0.600
20               Issa Doumbia    6.106630    2.400
21        Eduardo Felicissimo    1.098858    3.000
22              Stefano Sensi    6.114275    1.000
23             Tommaso Pobega    6.319627    9.000
24          Fernando Costanza    2.174301    3.000
25               Ilaix Moriba   10.574987    6.000
26            Finn Ole Becker    3.430590    2.000
27                   Casemiro    4.561024   10.000
28                Kaishu Sano   12.477356   20.000
29         Matthias Braunoder    2.194744    1.400
30            Abdoulaye Toure    6.694836    3.000
31                David Simao    0.436519    0.100
32                Ondrej Duda    6.801167    3.500
33        Oussama Targhalline    2.723638    4.000
34               Daniil Utkin    1.560039    2.800
35              Edson Alvarez    6.840741   25.000
36             Magnus Knudsen    6.122490    2.500
37         Henrikh Mkhitaryan    3.569260    4.000
38                Anas Tahiri    0.789041    0.500
39           Maxence Caqueret   13.943580   16.000
40               Nadiem Amiri   15.350512   20.000
41            Yehor Yarmoliuk   10.185917   15.000
42             Atakan Karazor   15.002376   12.000
43              Jonatan Lucca    0.345904    0.200
44                  Thom Haye    1.003810    1.000
45              Karol Linetty    2.819402    1.800
46            Mathias Delorge    6.083821    9.000
47            Rodrigo Saravia    1.524813    1.500
48           Jordan Henderson    0.718183    2.500
49             Miralem Pjanic    0.439388    2.000
50               Bence Dardai    8.900794   12.000
51                Alan Varela    2.344746   32.000
52            Nick Fichtinger    1.014781    0.450
53          Vladislav Kamilov    0.802665    0.800
54                 Kevin Pina    1.830255    5.000
55                  Alex Kral    8.950953    6.000
56               Isaac Babadi    2.650819    3.000
57         Iaroslav Mikhailov    2.172083    0.800
58           Kirian Rodriguez    5.555949    1.000
59               Lewis Holtby    1.792894    0.500
60                 Tom Krauss    4.201568    4.000
61              Mario Pasalic    9.780342   10.000
62               Daniil Fomin    2.604676    8.000
63                 Arne Maier    2.624549    4.000
64            Benjami­n Garre    1.251301    6.000
65              Luka Gagnidze    3.351176    1.200
66              Lamine Camara   24.909153   22.000
67             Nabil Bentaleb    1.637388    6.000
68              Harrison Reed    3.859544    6.000
69          Alessandro Deiola    3.881026    1.600
70          James Ward-Prowse    6.613927    8.000
71              Ryan Christie   16.413492   10.000
72                Salih Ozcan    1.937192    4.000
73             Justin Devenny   15.763878    6.000
74              Kian Fitz-Jim    2.369265    5.000
75               Jonas Martin    0.995214    0.600
76              Roberto Lopez    2.699683    1.000
77         Dominik Szoboszlai   86.503251   80.000
78              Denis Zakaria   12.796593   30.000
79             Rassoul Ndiaye    4.038216    2.000
80           Lawrence Agyekum    4.133235    2.500
81               Ivan Komarov    2.822317    2.000
82                Andre Horta    1.690942    4.000
83            Jude Bellingham   47.372185  180.000
84                       Igor    1.127544    3.500
85        Kamiel Van De Perre    1.901580    3.000
86               Aleix Garcia    7.594217   20.000
87            Justin Kluivert   60.337231   35.000
88              Paulo Moreira    1.616789    0.400
89                 Mert Komur    9.495955    5.000
90            Florian Tardieu    3.763297    0.600
91               Louis Mouton    4.070662    0.700
92          William Smallbone    7.362895    6.000
93            Nikita Saltykov    0.977759    2.000
94             Esequiel Barco   15.072225   14.000
95              Ellyes Skhiri    4.621949    7.500
96            Morten Hjulmand    2.679908   50.000
97           Gustavo Mendonca    1.805112    0.400
98            Leandro Paredes    4.798790    5.000
99             Angelo Stiller   29.091323   45.000
100                      Alan    7.309484    4.000
101            Sherzod Esanov    0.768796    0.300
102             Gerard Gumbau    1.693606    1.500
103             Hugo Magnetti    4.874631    6.000
104            Vi­ctor Mendez    0.741157    1.800
105              Mario Martin    7.790360    1.500
106             Robert Wagner    2.534586    3.000
107              Can Bozdogan    1.057302    3.500
108               Vadim Rakov    2.325921    1.200
109              Remo Freuler    6.633810    5.000
110          Aljoscha Kemlein    4.925847    7.000
111                  Guus Til   18.420439   12.000
112            Yellu Santiago    2.042221    0.900
113           Kristijan Jakic    5.892480    6.500
114             Samuele Ricci   18.840866   30.000
115         Han-Noah Massengo    3.134316    5.000
116          Maksim Paliyenko    0.535274    0.350
117                      Neto    0.644196    0.200
118            Darko Brasanac    2.216163    0.500
119                   Douglas    9.245804    6.000
120            Viktor Okishor   11.252689    0.500
121            Liam Henderson    6.584640    2.000
122           Diego Rodrigues    2.022596    2.000
123             Jamal Musiala   49.368118  140.000
124            Santi Comesana    8.986985    8.000
125       Vladislav Masternoy    0.309846    0.600
126      Jean-Philippe Gbamin    1.031971    2.000
127            Tim van de Loo    2.599200    0.600
128     Branco van den Boomen    0.359028    3.500
129            Gjivai Zechiel    4.092412    4.000
130            Matteo Pessina    1.966653    6.000
131               Jakub Moder    3.266698   12.000
132           Daouda Weidmann    0.913518    0.300
133            Aimen Moueffek    2.936780    2.500
134               Ulvi Babaev    1.078086    0.250
135                   Keliano    1.280989    0.400
136              Roman Yezhov    0.751687    1.800
137               Angel Gomes    3.550184   20.000
138             Junior Mwanga    7.045597    6.000
139       Aleksandar Pavlovic    7.182482   55.000
140       Dmitrii Aleksandrov    0.891296    0.350
141           Boubacar Kamara   16.887013   40.000
142  Leandro Barreiro Martins    2.338121   15.000
143          Gustavo Assuncao    1.226794    1.000
144              Dario Essugo    9.068614   20.000
145               Lewis Miley   21.713701   22.000
146                Jean Gorby    1.623277    4.000
147             Yassin Oukili    4.255421    0.900
148           Arthur Piedfort    2.999770    2.000
149            Nampalys Mendy    0.995372    1.800
150              Matt O'Riley   15.386207   22.000
151           Marcel Sabitzer    2.952836    8.000
152           Tanner Tessmann    5.044132    6.000
153             Danil Prutsev    2.103973    4.000
154                Roman Kvet    2.706810    1.500
155          Marshall Munetsi   21.817069   15.000
156           Nicolai Remberg    4.850232    3.000
157             Joris Chotard    4.519934    6.000

In [15]:
comp_leftovers_train

                         Player  Value_pred   Value
0                  Mateo Flores    2.051606    1.00
1                  Lennard Hens    1.174727    0.40
2                   Orkun Kokcu   11.187435   30.00
3                Ylber Ramadani    4.929461    1.80
4           Aleksandr Kovalenko    1.257167    1.50
5               Hidemasa Morita    1.807709   13.00
6                  Felix Nmecha   12.075562   28.00
7                Philipp Sander    4.495042    4.00
8               Kacper Urbanski    5.158894    6.00
9               Jordan Veretout    2.622854    4.00
10             Giuliano Simeone   19.397818   35.00
11                Mohamed Bamba    2.235817    3.00
12             Demir Ege Tiknaz    7.298021    5.00
13                Stefan Loncar    5.075254    1.50
14                Niklas Dorsch    5.551525    3.50
15                Martin Payero    6.621415    5.50
16                   Yvan Neyou    4.731345    3.00
17                 Edu Exposito    3.132173    3.00
18             Kristjan Asllani   11.199933   13.00
19             Ibrahima Sissoko    6.912673    6.00
20             Arthur Vermeeren    8.307817   22.00
21                Urko Gonzalez    5.974780    5.00
22                 Rudy Matondo    2.614393    0.30
23           Mikhail Shchetinin    1.267618    0.40
24            Antoine Makoumbou    8.215789    3.50
25                 Adem Zorgane    3.847851    6.00
26                   Joao Gomes   30.547041   40.00
27             Damian Rodriguez    2.823227    3.00
28            Mathias Rasmussen    2.612429    2.00
29                 Anton Mukhin    0.749411    0.25
30           Michel Ndary Adopo    9.622742    4.00
31               Fredrik Hammer    1.358287    1.50
32                  Oleg Ivanov    0.330403    0.10
33               Moumi Ngamaleu    2.599118    4.00
34              Facundo Caseres    1.540275    1.00
35               Sem Scheperman    1.452796    0.90
36                 Kevin Danois    5.307662    8.00
37              Luca Mazzitelli    3.548662    1.50
38                 Bryan Heynen    3.582900   11.00
39              Andreas Pereira   12.974093   18.00
40                  Rob Schoofs    3.783852    2.20
41          Nikolas Sattlberger    3.013447    3.50
42            Aleksandr Erokhin    0.913644    0.25
43                Billy Gilmour    6.734550   20.00
44                 Fran Beltran    8.350435    8.00
45                      Adriano    2.241221    2.50
46                Youssef Maleh    5.063664    3.20
47               Renato Sanches    0.367507    3.00
48             Patrik Hrosovsky    2.284262    2.70
49                  Andy Irving    5.353759    4.00
50             Giovanni Fabbian   10.525718   12.00
51                   Atsuki Ito    2.466127    3.00
52                Tika de Jonge    1.579036    0.90
53                        Artur    2.268505    8.00
54                Yves Bissouma    7.765448   25.00
55                    Ze Carlos    1.083116    1.00
56               Ivan Oleinikov    4.048796    1.40
57                 Julian Weigl    8.212149    6.00
58                Daniel Parejo    2.842008    1.50
59           Bilal El Khannouss   59.626573   28.00
60            Tijjani Reijnders   43.463622   60.00
61          Benjamin Bouchouari    6.069444    5.00
62                   Ryan Yates   11.667951   12.00
63             Dogucan Haspolat    4.771006    5.00
64                      Vitinha   33.578471   80.00
65                  Glen Kamara    1.722063    5.00
66                    Sam Morsy    7.015817    0.50
67             Jordan Holsgrove    5.138046    3.50
68              Santiago Garcia    3.098758    0.80
69                Luiz Henrique    2.685619   25.00
70               Nahuel Estevez    1.611149    2.00
71                  Francis Abu    5.081533    1.80
72                 Senny Mayulu   14.853588   15.00
73              Nikita Krivtsov    3.346126    4.00
74                   Luis Milla    7.387007    3.50
75              Lazar Samardzic    6.845723   17.00
76             Nicolas Gonzalez   10.286231   40.00
77              Frenkie de Jong    6.274888   45.00
78              Conor Gallagher   11.829899   40.00
79               Joshua Kimmich   13.320568   45.00
80                Kobbie Mainoo   13.900099   50.00
81               Zaim Divanovic    0.488079    0.15
82          Marco Ilaimaharitra    0.581866    0.80
83             Benat Turrientes    3.768136   10.00
84                 Granit Xhaka   13.394425   12.00
85                 Toby Collyer    6.094852    5.00
86              Rabby Nzingoula    7.584204    2.50
87      Sotiris Alexandropoulos    1.330912    2.50
88          Dmitrii Rybchinskii    1.570325    0.80
89               Artem Karpukas    2.166007    5.00
90                Cheikh Niasse    2.828686    2.50
91           Christian Norgaard   29.986567   11.00
92                 Michel Costa    0.741505    0.55
93                   Max Balard    3.321354    1.50
94                 Jose Campana    3.003928    0.90
95                 Oscar Fraulo    4.725250    3.50
96                 Elisha Owusu    6.363899    3.00
97               Lucas Bergvall   20.734247   38.00
98              Youssouf Fofana   23.945613   30.00
99            Pierre Lees-Melou    3.510655    6.00
100           Jean-Eudes Aholou    3.578712    2.00
101               Kevin Castano    1.866032    8.00
102              Jackson Irvine   12.928639    2.00
103                Oihan Sancet   23.902430   60.00
104                   Victor Sa    1.870300    3.00
105               Mamadou Maiga    0.354680    0.90
106          Rolando Mandragora   11.186255   12.00
107             Zaydou Youssouf    1.559774    6.00
108               Nabil Aberdin    2.204773    0.70
109          Lorenzo Pellegrini    4.982889    9.00
110              Lewis Ferguson    5.518771   28.00
111                Pablo Ibanez    5.542337    2.00
112               Mateo Kovacic   21.117473   20.00
113                 Xavi Simons   51.088179   70.00
114                 Seko Fofana    2.422382   10.00
115             Elliot Anderson   75.236634   32.00
116                Frank Onyeka    9.656670    7.00
117                 Enzo Le Fee    2.545120   18.00
118                Hans Vanaken   16.661513    7.00
119                Jordy Clasie    0.695346    1.50
120               Andrey Santos   49.724050   35.00
121                 Ryan Sanusi    0.925786    0.30
122               Manu Morlanes    2.738622    2.50
123                Douglas Luiz    2.134721   30.00
124                 Mirko Topic    2.400238    5.00
125           Olakunle Olusegun    1.590557    2.50
126     Hans Nicolussi Caviglia   20.196236    8.50
127          Idrissa Gana Gueye   16.029315    1.50
128                Daniil Zorin    1.098903    0.70
129              Sofiane Boufal    1.251791    3.50
130              Ayyoub Bouaddi    7.865562   28.00
131            Eduard Spertsyan    9.324185   25.00
132                 Mason Mount    8.433335   28.00
133           Kirill Shchetinin    2.498761    2.80
134               Miguel Menino    2.885409    1.00
135      Thorir Johann Helgason    7.523359    3.00
136                 Vitor Gomes    0.252610    0.10
137              Alberto Grassi    4.321959    1.80
138                     Ederson   18.365140   50.00
139              Dmitri Barinov    2.300937    8.00
140             Guido Rodriguez    4.379134   10.00
141           Dmytro Ivanisenya    0.478750    0.40
142                Veldin Hodza    1.861198    3.00
143     Leonardo da Silva Lopes    0.995005    3.50
144              Jerdy Schouten    1.577569   22.00
145              Sidnei Tavares    1.660207    0.80
146          Cheick Oumar Conde    1.728177    1.80
147           Birger Verstraete    2.060216    1.80
148                Jordy Bruijn    0.384904    0.30
149             Niccolo Pisilli    8.548483   13.00
150           Charles Vanhoutte    2.734085    6.00
151            Ibrahim Sulemana    8.331206    7.00
152                Oier Zarraga    2.981020    2.00
153                Benat Prados    5.602892   18.00
154               Aster Vranckx    2.994029    7.00
155                  Ryan Fosso    3.035211    1.50
156         Kristijan Bistrovic    0.916948    2.00
157                Mohamed Kaba    2.585236    2.00
158                  Kike Perez    5.485020    2.80
159               Medon Berisha    6.911531    1.50
160              Antoni Milambo   10.580425   18.00
161                Orel Mangala    9.626736   18.00
162                 Andre Sousa    0.408523    0.05
163               Vitaly Janelt   11.864370   20.00
164            Corentin Tolisso   11.411392   12.00
165               Azor Matusiwa    8.615380    8.00
166             Johann Lepenant   12.088804    6.00
167             Youri Tielemans   61.789938   38.00
168         Aleksei Baranovskii    1.332149    0.25
169                  Iker Munoz    4.479919    3.00
170              Alex Corredera    0.927278    0.80
171               Ander Herrera    0.654891    0.80
172               Sergi Roberto    1.348879    1.50
173                    Lars Mol    0.947596    0.20
174     Luis Manuel Costa Silva    0.303316    0.10
175           Boubakary Soumare    9.562241   12.00
176                Pedro Santos    1.500086    1.20
177              Seydouba Cisse   11.038094    3.00
178                 Pablo Marin    9.338688    8.00
179             Jordhy Thompson    1.153917    0.35
180              Harvey Elliott   21.877694   30.00
181         Baptiste Santamaria    3.544202    7.00
182                Nicolas Haas    1.214359    0.70
183      Valentin Atangana Edoa   11.914334   10.00
184               Alvaro Aguado    1.818076    1.80
185                 Jesse Bosch    3.130046    0.90
186             Lennard Maloney    2.094682    3.50
187          Ragnar Oratmangoen    1.204107    0.60
188               Franco Orozco    2.346259    1.50
189                 Rocco Reitz   14.193354   15.00
190                Espen van Ee    4.056429    1.30
191               German Valera    2.969726    1.50
192             Andrei Mostovoy    6.829110    4.00
193                   Ivan Ilic    3.892194   16.00
194            Enzo Barrenechea   10.688427   10.00
195                Denis Suarez    2.483385    1.20
196                  Pol Lozano    4.350701    5.00
197            Daniil Shantalii    1.036103    0.80
198                   Tygo Land    0.997510    2.00
199              Etienne Camara    1.603078    1.80
200                 Iver Fossum    0.598262    0.50
201                Carel Eiting    1.700800    1.60
202             Ismael Bennacer    3.768635   15.00
203                 Ivan Martin    5.228253    6.00
204            Saminu Abdullahi    0.757664    0.30
205                 Vasco Sousa    1.259311    4.00
206                  Gustavo sa   16.983722   16.00
207              Ismael Saibari   35.027825   27.00
208                 Yacine Adli   19.446087   11.00
209       Jose Luis Garcia Vaya    4.546937    9.00
210               Romano Schmid   19.987484   17.00
211                 Welat Cagro    0.683187    0.50
212                 Joan Jordan    3.420876    2.50
213               Joao Moutinho    0.344648    0.60
214                Razvan Marin    5.356896    3.50
215             Scott McTominay  100.055599   50.00
216                 Oscar Trejo    0.973628    0.50
217         Hamed Junior Traore   15.441298   20.00
218                 Suat Serdar    5.654438    4.50
219       Konstantinos Karetsas    7.001771   20.00
220               Hwang In-beom    1.709985   10.00
221            Matteo Guendouzi   17.955532   32.00
222                Rafael Brito    1.297573    0.50
223                Lee Jae-sung   12.861452    2.50
224                       Andre   20.465733   28.00
225                  Jhon Solis    3.741354    2.50
226              Jesus Castillo    0.813752    0.70
227         Pierre Ekwah Elimby   12.341720    7.00
228                Lamine Fomba    1.031431    0.60
229                Oliver Skipp    6.072912   10.00
230               Uguchukwu Iwu    1.525773    2.50
231               Morgan Sanson    7.664961    5.00
232               Carlos Baleba   64.071182   40.00
233             Patrizio Masini    5.656582    6.00
234                 Oriol Romeu    1.529261    1.20
235              Antonio Blanco    8.293876   10.00
236           Vinicius Zanocelo    2.565954    2.50
237             Dominik Janosek    3.149551    0.75
238           Aleksa Djurasovic    2.262981    2.00
239          Irakli Kvekveskiri    0.582080    0.30
240                 Senne Lynen   10.376790    9.00
241                Luis Esteves    5.339794    1.00
242          Vyacheslav Yakimov    0.777077    0.70
243           Alessandro Bianco   11.517880    5.00
244            Giorgi Aburjania    0.589475    0.40
245              Gijs Besselink    0.669284    0.60
246                Tomas Soucek   21.185701   18.00
247         Andreas Verstraeten    1.379563    0.80
248                  Andy Diouf   13.838126   15.00
249              Massimo Luongo    1.787538    0.40
250             Antoine Bernede    3.488107    2.50
251              Lawrence Ofori    2.122946    2.00
252                 Noah Mbamba    1.222973    1.50
253                Alieu Fadera   10.093624    4.50
254               Lucas Tousart    2.690265    2.50
255                Youri Regeer    2.615704    6.00
256              Sergi Altimira    9.232829   15.00
257                Matteo Prati    3.404984    6.00
258             Kirill Kaplenko    0.442059    0.50
259            Faustino Anjorin   14.007164    6.00
260             Djibril Soumare    3.140837    1.50
261                 Joao Simoes    1.766750    6.00
262                 Ismael Kone    6.194195    9.00
263              Niklas Schmidt    2.346402    1.80
264              Kanya Fujimoto    6.524017    4.00
265               Ardon Jashari    8.491010   32.00
266                 Yasin Ayari   23.998838   22.00
267                 Ryotaro Ito    3.870619    2.50
268            Ryan Gravenberch   81.671223   75.00
269              Chuky san jose    5.477492    1.50
270                 Amadou Kone    8.324414    4.00
271                 Luis Chavez    2.296799    8.00
272         Jean Thierry Lazare    1.281506    3.00
273              Alex Carbonell    0.312872    0.40
274               Denis Genreau    1.840974    0.80
275             Bruno Fernandes  102.870333   50.00
276              Pablo Gozalbez    1.233274    0.50
277             Wi­lmar Barrios    1.228116    8.00
278                    Jorginho    2.151418    6.00
279               Daichi Kamada    6.797400   12.00
280              Assane Diousse    2.553261    0.70
281              Vincent Sierro    6.567017    4.00
282               Igor Dmitriev    2.635770    1.00
283                Hugo Larsson   15.891895   40.00
284            Mario Stroeykens    9.195754   12.00
285             Nikita Glushkov    1.608704    0.90
286      Hannes Van der Bruggen    1.509121    0.60
287                 Luka Modric    2.549515    4.00
288            Pedro Chirivella    5.114561    5.00
289            Mees Hoedemakers    1.663652    1.00
290                  Sasa Lukic   11.168946   14.00
291              Nicolo Rovella   13.097118   30.00
292                  Luka Sucic    8.432129   15.00
293           Exequiel Palacios   13.822017   40.00
294               Aziz Ouattara    1.102020    1.00
295                 Joel Fujita    5.912124    3.00
296                 Harry Winks    8.958427    9.00
297                  Paul Nebel   29.751770   24.00
298                 Bilal Nadir    5.483404    5.00
299                Amadou Onana   25.022205   50.00
300              Haris Belkebla    2.728714    2.00
301            Mauricio Benitez    1.402363    0.80
302              Jacopo Fazzini   11.260833   10.00
303            Yassine Titraoui    3.342672    5.00
304            Adrien Thomasson   12.368045    5.00
305           Lassana Coulibaly    7.174558    2.50
306         Konstantin Kuchayev    1.044502    1.50
307               Dennis Kaygin    0.935662    0.45
308              Yangel Herrera   10.897862   15.00
309            Martin Zubimendi   10.598563   60.00
310                      Camilo    0.773694    1.20
311               Wouter George    0.879361    0.70
312               Daler Kuzyaev    1.892854    3.50
313                       Pedri   44.170360  140.00
314           Balthazar Pierret    4.646901    1.70
315            Hakan Calhanoglu    9.738485   30.00
316                Simon Olsson    0.910797    2.00
317           Marco Brescianini    9.392752    8.00
318                 Martim Neto    1.686377    2.50
319                Rafael Bauza    2.609702    0.20
320               Massimo Bruno    0.689344    0.30
321                 Manuel Manu    1.851285   10.00
322                Sven Mijnans    3.704345    9.00
323            Artyom Timofeyev    0.731788    1.50
324             Rihito Yamamoto    1.856841    0.90
325            Francis Coquelin    1.751300    0.90
326              Nicolas Hofler    0.767736    0.50
327               Yannik Keitel    2.536745    3.50
328                 Julian Baas    1.302702    0.80
329             Samuele Vignato    3.248391    2.20
330              Quinten Timber    3.390653   30.00
331                 Hamza Rafia    3.280159    1.40
332             Marat Apshatsev    0.742209    0.30
333                 Tiago Silva    1.963187    3.00
334                Andrei Ivlev    2.617521    0.40
335             Daniel Braganca    4.625985   12.00
336                 Isaac Price    2.460257    3.00
337             Florian Neuhaus    2.512324    3.50
338             Tomoki Takamine    1.062064    0.65
339                      Bitelo   17.989256   12.00
340            Nikolay Kalinsky    0.757486    1.20
341     Sebastian Perez Cardona    1.007080    1.00
342           Mathias De Amorim    2.394219    1.50
343                  Boni Amian    0.556337    0.15
344        Maximilian Eggestein    8.635995   10.00
345               Skelly Alvero    2.002733    2.50
346             Pierre Hojbjerg   14.003881   20.00
347             Kristijan Belic    1.053511    3.50
348               Alfred Duncan    1.726357    1.40
349       Manuel Ugarte Ribeiro   13.658329   45.00
350              Pedro Ferreira    2.312746    2.00
351              Benjamin Andre    3.551749    5.00
352                Nail Umyarov    3.210594    4.00
353             Neil El Aynaoui   13.729755   15.00
354              Maximo Perrone   10.027682   12.00
355          Ivan Jaime Pajuelo    5.020792    5.00
356      Abdulpasha Dzhabrailov    0.945271    0.30
357                  Jens Stage   18.958175   14.00
358             Ibrahim Sangare    9.135815   24.00
359                   Miha Zajc    1.057959    1.50
360                Stanko Juric    2.548411    1.20
361           Maksim Glushenkov    2.885411   14.00
362                 Joao Novais    0.574259    0.40
363                Sander Berge    9.810792   25.00
364              Gianluca Busio   11.833719    6.00
365             Jandro Orellana    1.565608    1.00
366               Clint Leemans    1.589106    0.75
367                Rani Khedira    3.932447    2.50
368            Carlos Benavidez    3.016884    1.20
369                 Chris Nadje    0.944176    1.20
370       Fredrik Oldrup Jensen    0.414687    0.30
371       Magnus Kofod Andersen    3.651379    1.00
372                Daniel Penha    1.937196    0.75
373                  Johan Hove    1.753926    2.00
374              Amine Oudrhiri    0.460096    0.30
375                Hakim Sahabo    1.642020    1.00
376          Carney Chukwuemeka    5.627437   18.00
377            Raphael Onyedika    3.453278   20.00
378               Matias Vecino    2.853121    2.00
379               Andrian Kraev    1.100107    1.50
380               Joao Palhinha    1.681647   30.00
381             Majeed Ashimeru    1.285537    1.50
382            Mikel Jauregizar   14.276699   30.00

In [16]:
comp_leftovers_train[comp_leftovers_train['Player'].str.contains('Batxi')]

    Player  Value_pred  Value
536  Batxi    6.561134    5.0

<b>Потенциальные переменные для добавления</b>

In [79]:
base_cols = ['G+A', 'Gls.1', 'SoT/90', '90s', 'Fld', 'CrdY', 'SoT%', 'Age', 'Crs', 'Int', 'PK', 'Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']

In [46]:
cols_to_add = [col for col in all_cols if not(col in base_cols)]
new_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_add:
    X_train_new = X_train[base_cols + [col]]
    X_test_new = X_test[base_cols + [col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new<mae_test or mape_new<mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=new_cols.columns, index=[col])
        new_cols = pd.concat([new_cols, row])
new_cols

            mae      mape        r2
base   5.686543  0.951272  0.572145
Min    5.652037  1.007650 -0.030386
PK     5.530911  1.014825  0.047364
PKatt  5.550080  1.022319  0.009378
2CrdY  5.684844  1.008763  0.030107
Off    5.598393  1.004720 -0.068392
Int    5.653316  1.010213  0.051427
TklW   5.660771  1.010023  0.027543
Sh     5.679193  1.009237  0.036855
G/Sh   5.678686  1.008258  0.024269

<b>Потенциальные переменные для удаления</b>

In [81]:
cols_to_delete = [col for col in base_cols if not(col.startswith('league'))]
del_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_delete:
    X_train_new = X_train[[c for c in base_cols if c != col]]
    X_test_new = X_test[[c for c in base_cols if c != col]]
    LR_regressor_new = LinearRegression()
    LR_regressor_new.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor_new.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new < mae_test or mape_new < mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=del_cols.columns, index=[col])
        del_cols = pd.concat([del_cols, row])
del_cols

             mae      mape        r2
base    5.400191  0.931033  0.642989
SoT/90  5.367201  1.034970  0.237663
90s     5.254602  1.060704  0.521605
Sh      5.369418  1.036733  0.295511

<b>Модель 1</b>

In [17]:
X_train = X_train[['G+A', 'G+A.1', 'SoT', 'Ast.1', 'Gls.1', 'SoT/90', '90s', 'Fld', 'PK', 'CrdY', 'SoT%', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'G+A.1', 'SoT', 'Ast.1', 'Gls.1', 'SoT/90', '90s', 'Fld', 'PK', 'CrdY', 'SoT%', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [23]:
coeffs_df

               coeff
league_GB1  0.556580
90s         0.520633
Age        -0.433309
league_IT1  0.363924
league_ES1  0.283295
G+A         0.282728
Ast.1       0.282216
league_L1   0.274195
Gls.1       0.270752
league_FR1  0.238401
G+A.1      -0.236630
SoT        -0.142258
Fld         0.121646
SoT/90      0.119642
league_RU1 -0.115435
league_NL1 -0.115400
CrdY       -0.108704
league_PO1 -0.071390
SoT%        0.058538
PK         -0.033573

In [24]:
metrics

            MAE       RMSE      MAPE        R2
test   5.597816  14.268647  0.945403  0.549571
train  5.390391  11.065701  0.862653  0.464014

In [25]:
comp_leftovers_test

                       Player  Value_pred    Value
0                Sandi Lovric   10.773762    8.500
1              Danila Godiaev    0.919997    1.500
2     Inigo Ruiz de Galarreta    3.228167    3.000
3              Johnny Cardoso   11.559130   25.000
4                  Unai Lopez    3.952923    2.500
5          Florian Grillitsch    2.380475    2.000
6              Mahmoud Dahoud    2.963600    3.500
7               Teji Savanier    6.948817    2.500
8                Djaoui Cisse    5.490980    8.000
9               Dean Huiberts    0.905834    0.300
10            Khephren Thuram   21.435853   40.000
11                 Pape Gueye    9.493175   15.000
12      Thomas Van den Keybus    1.421913    0.800
13              Sandro Tonali   42.780678   60.000
14     Ibrahima Sory Bangoura    2.015968    8.000
15        Vladimir Moskvichev    0.482095    0.500
16               Lasse Schone    0.138186    0.075
17            Kalvin Phillips    5.076169   12.000
18         Morgan Gibbs-White   84.034481   50.000
19              Ilija Vukotic    2.330154    0.600
20               Issa Doumbia    5.776691    2.400
21        Eduardo Felicissimo    1.071306    3.000
22              Stefano Sensi    2.382623    1.000
23             Tommaso Pobega    5.773721    9.000
24          Fernando Costanza    1.887284    3.000
25               Ilaix Moriba   10.292375    6.000
26            Finn Ole Becker    3.753347    2.000
27                   Casemiro    4.660594   10.000
28                Kaishu Sano   13.368171   20.000
29         Matthias Braunoder    2.197273    1.400
30            Abdoulaye Toure    7.294237    3.000
31                David Simao    0.515727    0.100
32                Ondrej Duda    6.957110    3.500
33        Oussama Targhalline    4.113357    4.000
34               Daniil Utkin    1.864476    2.800
35              Edson Alvarez    8.385338   25.000
36             Magnus Knudsen    5.655579    2.500
37         Henrikh Mkhitaryan    4.358062    4.000
38                Anas Tahiri    0.837407    0.500
39           Maxence Caqueret   12.336152   16.000
40               Nadiem Amiri   16.815331   20.000
41            Yehor Yarmoliuk   12.727161   15.000
42             Atakan Karazor   13.666981   12.000
43              Jonatan Lucca    0.341934    0.200
44                  Thom Haye    0.916277    1.000
45              Karol Linetty    2.713804    1.800
46            Mathias Delorge    7.003919    9.000
47            Rodrigo Saravia    1.371188    1.500
48           Jordan Henderson    0.763125    2.500
49             Miralem Pjanic    0.459657    2.000
50               Bence Dardai   10.315230   12.000
51                Alan Varela    2.539733   32.000
52            Nick Fichtinger    1.020082    0.450
53          Vladislav Kamilov    1.049525    0.800
54                 Kevin Pina    1.991008    5.000
55                  Alex Kral    7.885986    6.000
56               Isaac Babadi    2.608268    3.000
57         Iaroslav Mikhailov    1.964191    0.800
58           Kirian Rodriguez    4.802167    1.000
59               Lewis Holtby    1.844651    0.500
60                 Tom Krauss    3.801002    4.000
61              Mario Pasalic    8.305996   10.000
62               Daniil Fomin    2.547130    8.000
63                 Arne Maier    3.157375    4.000
64            Benjami­n Garre    1.010926    6.000
65              Luka Gagnidze    2.694908    1.200
66              Lamine Camara   22.685485   22.000
67             Nabil Bentaleb    1.505642    6.000
68              Harrison Reed    4.681669    6.000
69          Alessandro Deiola    3.737685    1.600
70          James Ward-Prowse    8.099531    8.000
71              Ryan Christie   13.816526   10.000
72                Salih Ozcan    2.179758    4.000
73             Justin Devenny   19.205216    6.000
74              Kian Fitz-Jim    2.171145    5.000
75               Jonas Martin    0.917927    0.600
76              Roberto Lopez    2.883204    1.000
77         Dominik Szoboszlai   64.141644   80.000
78              Denis Zakaria   10.757780   30.000
79             Rassoul Ndiaye    4.172085    2.000
80           Lawrence Agyekum    3.586116    2.500
81               Ivan Komarov    2.564402    2.000
82                Andre Horta    1.965634    4.000
83            Jude Bellingham   71.243457  180.000
84                       Igor    1.108198    3.500
85        Kamiel Van De Perre    1.675825    3.000
86               Aleix Garcia    8.203126   20.000
87            Justin Kluivert   65.118411   35.000
88              Paulo Moreira    1.594668    0.400
89                 Mert Komur   11.518876    5.000
90            Florian Tardieu    3.801051    0.600
91               Louis Mouton    4.000508    0.700
92          William Smallbone    7.530456    6.000
93            Nikita Saltykov    1.097476    2.000
94             Esequiel Barco   12.685807   14.000
95              Ellyes Skhiri    5.018194    7.500
96            Morten Hjulmand    2.658401   50.000
97           Gustavo Mendonca    1.399310    0.400
98            Leandro Paredes    3.562124    5.000
99             Angelo Stiller   31.145283   45.000
100                      Alan    8.410469    4.000
101            Sherzod Esanov    0.841100    0.300
102             Gerard Gumbau    1.923921    1.500
103             Hugo Magnetti    5.271834    6.000
104            Vi­ctor Mendez    0.773827    1.800
105              Mario Martin    8.212748    1.500
106             Robert Wagner    2.708437    3.000
107              Can Bozdogan    1.127694    3.500
108               Vadim Rakov    2.485218    1.200
109              Remo Freuler    6.870361    5.000
110          Aljoscha Kemlein    5.575959    7.000
111                  Guus Til   15.280191   12.000
112            Yellu Santiago    2.251680    0.900
113           Kristijan Jakic    6.567443    6.500
114             Samuele Ricci   19.101191   30.000
115         Han-Noah Massengo    3.333171    5.000
116          Maksim Paliyenko    0.507611    0.350
117                      Neto    0.584335    0.200
118            Darko Brasanac    2.504158    0.500
119                   Douglas    8.068876    6.000
120            Viktor Okishor    6.393555    0.500
121            Liam Henderson    6.278928    2.000
122           Diego Rodrigues    2.445055    2.000
123             Jamal Musiala   48.286009  140.000
124            Santi Comesana    8.836615    8.000
125       Vladislav Masternoy    0.320864    0.600
126      Jean-Philippe Gbamin    0.995887    2.000
127            Tim van de Loo    2.481771    0.600
128     Branco van den Boomen    0.504108    3.500
129            Gjivai Zechiel    3.155669    4.000
130            Matteo Pessina    2.071357    6.000
131               Jakub Moder    2.684860   12.000
132           Daouda Weidmann    0.869094    0.300
133            Aimen Moueffek    3.596106    2.500
134               Ulvi Babaev    1.127377    0.250
135                   Keliano    1.262230    0.400
136              Roman Yezhov    1.363016    1.800
137               Angel Gomes    4.361858   20.000
138             Junior Mwanga    6.959734    6.000
139       Aleksandar Pavlovic    7.588651   55.000
140       Dmitrii Aleksandrov    0.816383    0.350
141           Boubacar Kamara   15.780926   40.000
142  Leandro Barreiro Martins    2.322728   15.000
143          Gustavo Assuncao    1.199703    1.000
144              Dario Essugo    7.917280   20.000
145               Lewis Miley   16.770278   22.000
146                Jean Gorby    1.560541    4.000
147             Yassin Oukili    4.972877    0.900
148           Arthur Piedfort    3.151517    2.000
149            Nampalys Mendy    1.081608    1.800
150              Matt O'Riley   17.479607   22.000
151           Marcel Sabitzer    2.717549    8.000
152           Tanner Tessmann    5.018895    6.000
153             Danil Prutsev    1.988008    4.000
154                Roman Kvet    2.978144    1.500
155          Marshall Munetsi   18.486360   15.000
156           Nicolai Remberg    7.492130    3.000
157             Joris Chotard    5.528897    6.000

In [26]:
comp_leftovers_train

                         Player  Value_pred   Value
0                  Mateo Flores    2.204801    1.00
1                  Lennard Hens    1.158568    0.40
2                   Orkun Kokcu   10.415220   30.00
3                Ylber Ramadani    4.376401    1.80
4           Aleksandr Kovalenko    1.374605    1.50
5               Hidemasa Morita    1.553983   13.00
6                  Felix Nmecha   10.264963   28.00
7                Philipp Sander    3.866962    4.00
8               Kacper Urbanski    5.542858    6.00
9               Jordan Veretout    2.371675    4.00
10             Giuliano Simeone   22.267169   35.00
11                Mohamed Bamba    2.023864    3.00
12             Demir Ege Tiknaz    5.709943    5.00
13                Stefan Loncar    3.538661    1.50
14                Niklas Dorsch    5.727616    3.50
15                Martin Payero    5.612996    5.50
16                   Yvan Neyou    4.788224    3.00
17                 Edu Exposito    3.421478    3.00
18             Kristjan Asllani    7.679958   13.00
19             Ibrahima Sissoko    7.432764    6.00
20             Arthur Vermeeren    7.794205   22.00
21                Urko Gonzalez    5.808457    5.00
22                 Rudy Matondo    3.132813    0.30
23           Mikhail Shchetinin    1.210575    0.40
24            Antoine Makoumbou    7.510180    3.50
25                 Adem Zorgane    5.013981    6.00
26                   Joao Gomes   35.613441   40.00
27             Damian Rodriguez    3.179727    3.00
28            Mathias Rasmussen    2.547848    2.00
29                 Anton Mukhin    0.887002    0.25
30           Michel Ndary Adopo    9.089629    4.00
31               Fredrik Hammer    1.235696    1.50
32                  Oleg Ivanov    0.346581    0.10
33               Moumi Ngamaleu    3.921541    4.00
34              Facundo Caseres    1.509492    1.00
35               Sem Scheperman    1.675067    0.90
36                 Kevin Danois    5.870142    8.00
37              Luca Mazzitelli    3.877123    1.50
38                 Bryan Heynen    2.768579   11.00
39              Andreas Pereira   16.469929   18.00
40                  Rob Schoofs    3.403072    2.20
41          Nikolas Sattlberger    2.832924    3.50
42            Aleksandr Erokhin    0.764165    0.25
43                Billy Gilmour    6.154471   20.00
44                 Fran Beltran    7.791830    8.00
45                      Adriano    2.802967    2.50
46                Youssef Maleh    4.803462    3.20
47               Renato Sanches    0.424523    3.00
48             Patrik Hrosovsky    2.282944    2.70
49                  Andy Irving    6.187640    4.00
50             Giovanni Fabbian    9.962790   12.00
51                   Atsuki Ito    2.187788    3.00
52                Tika de Jonge    1.650810    0.90
53                        Artur    4.140972    8.00
54                Yves Bissouma    8.096471   25.00
55                    Ze Carlos    1.144372    1.00
56               Ivan Oleinikov    4.563002    1.40
57                 Julian Weigl    7.072614    6.00
58                Daniel Parejo    3.551861    1.50
59           Bilal El Khannouss   54.593962   28.00
60            Tijjani Reijnders   35.383280   60.00
61          Benjamin Bouchouari    6.444007    5.00
62                   Ryan Yates   14.225807   12.00
63             Dogucan Haspolat    6.493233    5.00
64                      Vitinha   42.489108   80.00
65                  Glen Kamara    1.737891    5.00
66                    Sam Morsy    9.277607    0.50
67             Jordan Holsgrove    4.378884    3.50
68              Santiago Garcia    3.086510    0.80
69                Luiz Henrique    2.345205   25.00
70               Nahuel Estevez    1.691198    2.00
71                  Francis Abu    3.878936    1.80
72                 Senny Mayulu   12.423097   15.00
73              Nikita Krivtsov    2.842361    4.00
74                   Luis Milla    9.258902    3.50
75              Lazar Samardzic    7.723687   17.00
76             Nicolas Gonzalez    8.213837   40.00
77              Frenkie de Jong    4.969171   45.00
78              Conor Gallagher   11.312327   40.00
79               Joshua Kimmich   16.798458   45.00
80                Kobbie Mainoo   17.124146   50.00
81               Zaim Divanovic    0.517946    0.15
82          Marco Ilaimaharitra    0.655922    0.80
83             Benat Turrientes    3.509176   10.00
84                 Granit Xhaka   14.437816   12.00
85                 Toby Collyer    6.257110    5.00
86              Rabby Nzingoula    8.055976    2.50
87      Sotiris Alexandropoulos    1.123266    2.50
88          Dmitrii Rybchinskii    1.643824    0.80
89               Artem Karpukas    2.357646    5.00
90                Cheikh Niasse    2.853163    2.50
91           Christian Norgaard   25.715672   11.00
92                 Michel Costa    0.818961    0.55
93                   Max Balard    3.781677    1.50
94                 Jose Campana    2.749913    0.90
95                 Oscar Fraulo    4.691311    3.50
96                 Elisha Owusu    7.739563    3.00
97               Lucas Bergvall   18.361987   38.00
98              Youssouf Fofana   15.436765   30.00
99            Pierre Lees-Melou    3.085022    6.00
100           Jean-Eudes Aholou    2.912210    2.00
101               Kevin Castano    2.064097    8.00
102              Jackson Irvine    7.860964    2.00
103                Oihan Sancet   27.734260   60.00
104                   Victor Sa    2.115729    3.00
105               Mamadou Maiga    0.379859    0.90
106          Rolando Mandragora    9.674122   12.00
107             Zaydou Youssouf    1.571562    6.00
108               Nabil Aberdin    2.190937    0.70
109          Lorenzo Pellegrini    4.681089    9.00
110              Lewis Ferguson    5.329458   28.00
111                Pablo Ibanez    4.395886    2.00
112               Mateo Kovacic   18.742425   20.00
113                 Xavi Simons   65.867503   70.00
114                 Seko Fofana    2.206920   10.00
115             Elliot Anderson   71.210364   32.00
116                Frank Onyeka   10.030510    7.00
117                 Enzo Le Fee    2.762114   18.00
118                Hans Vanaken   10.938251    7.00
119                Jordy Clasie    0.640185    1.50
120               Andrey Santos   52.753908   35.00
121                 Ryan Sanusi    0.910948    0.30
122               Manu Morlanes    2.474484    2.50
123                Douglas Luiz    2.111765   30.00
124                 Mirko Topic    2.465861    5.00
125           Olakunle Olusegun    1.570565    2.50
126     Hans Nicolussi Caviglia   17.124231    8.50
127          Idrissa Gana Gueye   12.060882    1.50
128                Daniil Zorin    1.342570    0.70
129              Sofiane Boufal    1.093363    3.50
130              Ayyoub Bouaddi    8.418034   28.00
131            Eduard Spertsyan   12.040330   25.00
132                 Mason Mount    8.355770   28.00
133           Kirill Shchetinin    2.789032    2.80
134               Miguel Menino    3.081366    1.00
135      Thorir Johann Helgason    9.172026    3.00
136                 Vitor Gomes    0.504610    0.10
137              Alberto Grassi    4.472834    1.80
138                     Ederson   17.715499   50.00
139              Dmitri Barinov    1.654292    8.00
140             Guido Rodriguez    4.247457   10.00
141           Dmytro Ivanisenya    0.425325    0.40
142                Veldin Hodza    1.710981    3.00
143     Leonardo da Silva Lopes    0.943937    3.50
144              Jerdy Schouten    1.363896   22.00
145              Sidnei Tavares    1.764828    0.80
146          Cheick Oumar Conde    1.704800    1.80
147           Birger Verstraete    1.767660    1.80
148                Jordy Bruijn    0.315445    0.30
149             Niccolo Pisilli    8.879366   13.00
150           Charles Vanhoutte    3.728056    6.00
151            Ibrahim Sulemana    7.131807    7.00
152                Oier Zarraga    3.384725    2.00
153                Benat Prados    4.664811   18.00
154               Aster Vranckx    3.125088    7.00
155                  Ryan Fosso    3.179410    1.50
156         Kristijan Bistrovic    0.868518    2.00
157                Mohamed Kaba    2.762889    2.00
158                  Kike Perez    6.104707    2.80
159               Medon Berisha    5.539277    1.50
160              Antoni Milambo    7.548157   18.00
161                Orel Mangala    9.797357   18.00
162                 Andre Sousa    0.346169    0.05
163               Vitaly Janelt   20.513487   20.00
164            Corentin Tolisso   13.911796   12.00
165               Azor Matusiwa    7.775432    8.00
166             Johann Lepenant   11.738068    6.00
167             Youri Tielemans   65.249331   38.00
168         Aleksei Baranovskii    0.965803    0.25
169                  Iker Munoz    3.673003    3.00
170              Alex Corredera    0.896406    0.80
171               Ander Herrera    0.931432    0.80
172               Sergi Roberto    1.420530    1.50
173                    Lars Mol    1.095721    0.20
174     Luis Manuel Costa Silva    0.279190    0.10
175           Boubakary Soumare   10.981163   12.00
176                Pedro Santos    1.412202    1.20
177              Seydouba Cisse   12.009135    3.00
178                 Pablo Marin    7.553398    8.00
179             Jordhy Thompson    1.237830    0.35
180              Harvey Elliott   23.887621   30.00
181         Baptiste Santamaria    2.681274    7.00
182                Nicolas Haas    1.254691    0.70
183      Valentin Atangana Edoa   18.414671   10.00
184               Alvaro Aguado    1.677734    1.80
185                 Jesse Bosch    3.553311    0.90
186             Lennard Maloney    2.389075    3.50
187          Ragnar Oratmangoen    1.336418    0.60
188               Franco Orozco    2.677349    1.50
189                 Rocco Reitz   11.959771   15.00
190                Espen van Ee    3.266017    1.30
191               German Valera    3.550912    1.50
192             Andrei Mostovoy    6.976192    4.00
193                   Ivan Ilic    4.561629   16.00
194            Enzo Barrenechea   10.162637   10.00
195                Denis Suarez    2.159187    1.20
196                  Pol Lozano    3.984945    5.00
197            Daniil Shantalii    1.151930    0.80
198                   Tygo Land    0.757919    2.00
199              Etienne Camara    1.740274    1.80
200                 Iver Fossum    0.597664    0.50
201                Carel Eiting    1.977154    1.60
202             Ismael Bennacer    3.856660   15.00
203                 Ivan Martin    6.383258    6.00
204            Saminu Abdullahi    0.682926    0.30
205                 Vasco Sousa    1.122578    4.00
206                  Gustavo sa   16.891427   16.00
207              Ismael Saibari   24.398216   27.00
208                 Yacine Adli   19.845271   11.00
209       Jose Luis Garcia Vaya    5.181268    9.00
210               Romano Schmid   25.425588   17.00
211                 Welat Cagro    1.036989    0.50
212                 Joan Jordan    4.245343    2.50
213               Joao Moutinho    0.427940    0.60
214                Razvan Marin    5.077941    3.50
215             Scott McTominay   77.504186   50.00
216                 Oscar Trejo    0.863536    0.50
217         Hamed Junior Traore   20.508275   20.00
218                 Suat Serdar    4.655676    4.50
219       Konstantinos Karetsas    8.692505   20.00
220               Hwang In-beom    1.647443   10.00
221            Matteo Guendouzi   17.416342   32.00
222                Rafael Brito    1.244868    0.50
223                Lee Jae-sung   18.315645    2.50
224                       Andre   19.097894   28.00
225                  Jhon Solis    4.214117    2.50
226              Jesus Castillo    0.915846    0.70
227         Pierre Ekwah Elimby   11.056510    7.00
228                Lamine Fomba    1.146822    0.60
229                Oliver Skipp    7.015823   10.00
230               Uguchukwu Iwu    1.441228    2.50
231               Morgan Sanson    5.542740    5.00
232               Carlos Baleba   44.684684   40.00
233             Patrizio Masini    7.263212    6.00
234                 Oriol Romeu    1.394450    1.20
235              Antonio Blanco    6.855226   10.00
236           Vinicius Zanocelo    2.188987    2.50
237             Dominik Janosek    2.219257    0.75
238           Aleksa Djurasovic    3.204597    2.00
239          Irakli Kvekveskiri    0.498749    0.30
240                 Senne Lynen    7.461517    9.00
241                Luis Esteves    3.619149    1.00
242          Vyacheslav Yakimov    0.755677    0.70
243           Alessandro Bianco   14.093337    5.00
244            Giorgi Aburjania    0.526825    0.40
245              Gijs Besselink    0.697181    0.60
246                Tomas Soucek   25.740593   18.00
247         Andreas Verstraeten    1.420621    0.80
248                  Andy Diouf   11.398613   15.00
249              Massimo Luongo    1.952643    0.40
250             Antoine Bernede    3.129815    2.50
251              Lawrence Ofori    1.984992    2.00
252                 Noah Mbamba    1.248900    1.50
253                Alieu Fadera   19.482994    4.50
254               Lucas Tousart    2.928233    2.50
255                Youri Regeer    2.338812    6.00
256              Sergi Altimira    7.636529   15.00
257                Matteo Prati    3.558194    6.00
258             Kirill Kaplenko    0.410591    0.50
259            Faustino Anjorin   10.938563    6.00
260             Djibril Soumare    2.963918    1.50
261                 Joao Simoes    1.870245    6.00
262                 Ismael Kone    6.462273    9.00
263              Niklas Schmidt    2.951559    1.80
264              Kanya Fujimoto    5.968921    4.00
265               Ardon Jashari    6.167213   32.00
266                 Yasin Ayari   30.627080   22.00
267                 Ryotaro Ito    3.663657    2.50
268            Ryan Gravenberch   60.299126   75.00
269              Chuky san jose    6.621567    1.50
270                 Amadou Kone    7.440439    4.00
271                 Luis Chavez    1.913692    8.00
272         Jean Thierry Lazare    1.279120    3.00
273              Alex Carbonell    0.369403    0.40
274               Denis Genreau    1.416966    0.80
275             Bruno Fernandes   71.439559   50.00
276              Pablo Gozalbez    1.470991    0.50
277             Wi­lmar Barrios    1.287713    8.00
278                    Jorginho    2.237847    6.00
279               Daichi Kamada    7.425365   12.00
280              Assane Diousse    2.247426    0.70
281              Vincent Sierro    7.628151    4.00
282               Igor Dmitriev    3.849323    1.00
283                Hugo Larsson   16.877781   40.00
284            Mario Stroeykens    9.079802   12.00
285             Nikita Glushkov    1.563189    0.90
286      Hannes Van der Bruggen    1.198869    0.60
287                 Luka Modric    2.703369    4.00
288            Pedro Chirivella    5.188014    5.00
289            Mees Hoedemakers    1.310764    1.00
290                  Sasa Lukic   11.536232   14.00
291              Nicolo Rovella   12.409018   30.00
292                  Luka Sucic    7.369450   15.00
293           Exequiel Palacios   13.181005   40.00
294               Aziz Ouattara    1.572090    1.00
295                 Joel Fujita    4.287307    3.00
296                 Harry Winks    8.937071    9.00
297                  Paul Nebel   46.906091   24.00
298                 Bilal Nadir    4.627946    5.00
299                Amadou Onana   21.076397   50.00
300              Haris Belkebla    3.051813    2.00
301            Mauricio Benitez    1.281289    0.80
302              Jacopo Fazzini   14.746852   10.00
303            Yassine Titraoui    2.941030    5.00
304            Adrien Thomasson   12.229453    5.00
305           Lassana Coulibaly    8.536784    2.50
306         Konstantin Kuchayev    1.060287    1.50
307               Dennis Kaygin    1.243668    0.45
308              Yangel Herrera   11.888519   15.00
309            Martin Zubimendi   10.024547   60.00
310                      Camilo    0.775618    1.20
311               Wouter George    0.860440    0.70
312               Daler Kuzyaev    1.567466    3.50
313                       Pedri   42.060746  140.00
314           Balthazar Pierret    5.164129    1.70
315            Hakan Calhanoglu    9.067860   30.00
316                Simon Olsson    0.912635    2.00
317           Marco Brescianini   10.346377    8.00
318                 Martim Neto    2.216644    2.50
319                Rafael Bauza    2.472434    0.20
320               Massimo Bruno    0.594173    0.30
321                 Manuel Manu    1.633522   10.00
322                Sven Mijnans    5.441594    9.00
323            Artyom Timofeyev    0.629008    1.50
324             Rihito Yamamoto    1.809958    0.90
325            Francis Coquelin    1.816903    0.90
326              Nicolas Hofler    0.811633    0.50
327               Yannik Keitel    2.560655    3.50
328                 Julian Baas    1.569649    0.80
329             Samuele Vignato    3.874207    2.20
330              Quinten Timber    2.446092   30.00
331                 Hamza Rafia    3.224716    1.40
332             Marat Apshatsev    0.791608    0.30
333                 Tiago Silva    2.645849    3.00
334                Andrei Ivlev    2.599277    0.40
335             Daniel Braganca    3.246143   12.00
336                 Isaac Price    2.973054    3.00
337             Florian Neuhaus    2.844654    3.50
338             Tomoki Takamine    0.959843    0.65
339                      Bitelo   12.324965   12.00
340            Nikolay Kalinsky    0.983623    1.20
341     Sebastian Perez Cardona    1.053111    1.00
342           Mathias De Amorim    2.452018    1.50
343                  Boni Amian    0.580385    0.15
344        Maximilian Eggestein    8.195458   10.00
345               Skelly Alvero    2.189322    2.50
346             Pierre Hojbjerg   10.306333   20.00
347             Kristijan Belic    0.996311    3.50
348               Alfred Duncan    1.633926    1.40
349       Manuel Ugarte Ribeiro   16.027137   45.00
350              Pedro Ferreira    1.760431    2.00
351              Benjamin Andre    3.777004    5.00
352                Nail Umyarov    2.548610    4.00
353             Neil El Aynaoui   13.362306   15.00
354              Maximo Perrone   10.055694   12.00
355          Ivan Jaime Pajuelo    4.770895    5.00
356      Abdulpasha Dzhabrailov    0.876207    0.30
357                  Jens Stage   21.381522   14.00
358             Ibrahim Sangare    7.504994   24.00
359                   Miha Zajc    1.067100    1.50
360                Stanko Juric    2.582615    1.20
361           Maksim Glushenkov    5.511251   14.00
362                 Joao Novais    0.620769    0.40
363                Sander Berge   11.078387   25.00
364              Gianluca Busio   14.465633    6.00
365             Jandro Orellana    1.552354    1.00
366               Clint Leemans    1.785652    0.75
367                Rani Khedira    4.941401    2.50
368            Carlos Benavidez    2.921750    1.20
369                 Chris Nadje    0.816230    1.20
370       Fredrik Oldrup Jensen    0.511084    0.30
371       Magnus Kofod Andersen    3.940566    1.00
372                Daniel Penha    2.284313    0.75
373                  Johan Hove    1.558822    2.00
374              Amine Oudrhiri    0.518850    0.30
375                Hakim Sahabo    1.816450    1.00
376          Carney Chukwuemeka    5.382795   18.00
377            Raphael Onyedika    2.915405   20.00
378               Matias Vecino    2.907741    2.00
379               Andrian Kraev    1.111867    1.50
380               Joao Palhinha    1.653759   30.00
381             Majeed Ashimeru    1.468662    1.50
382            Mikel Jauregizar   15.075695   30.00

In [29]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                         Player  Value_pred   Value
428             Bruno Guimaraes  117.460520   80.00
500              Enzo Fernandez  100.308833   75.00
525            Mateus Fernandes   87.168301   15.00
386              James Maddison   85.545442   42.00
215             Scott McTominay   77.504186   50.00
275             Bruno Fernandes   71.439559   50.00
115             Elliot Anderson   71.210364   32.00
113                 Xavi Simons   65.867503   70.00
167             Youri Tielemans   65.249331   38.00
268            Ryan Gravenberch   60.299126   75.00
59           Bilal El Khannouss   54.593962   28.00
120               Andrey Santos   52.753908   35.00
523         Alexis Mac Allister   52.112780  100.00
629                 Declan Rice   51.546699  120.00
398             Martin Ødegaard   48.283200   85.00
297                  Paul Nebel   46.906091   24.00
232               Carlos Baleba   44.684684   40.00
64                      Vitinha   42.489108   80.00
313                       Pedri   42.060746  140.00
498                  Sem Steijn   37.929481   16.00
451            Emile Smith Rowe   37.448582   30.00
26                   Joao Gomes   35.613441   40.00
60            Tijjani Reijnders   35.383280   60.00
385             Pape Matar Sarr   32.445928   32.00
266                 Yasin Ayari   30.627080   22.00
399                  Aimar Oroz   29.811091   15.00
103                Oihan Sancet   27.734260   60.00
559               Julian Brandt   25.881050   25.00
246                Tomas Soucek   25.740593   18.00
91           Christian Norgaard   25.715672   11.00
210               Romano Schmid   25.425588   17.00
207              Ismael Saibari   24.398216   27.00
180              Harvey Elliott   23.887621   30.00
10             Giuliano Simeone   22.267169   35.00
357                  Jens Stage   21.381522   14.00
299                Amadou Onana   21.076397   50.00
163               Vitaly Janelt   20.513487   20.00
217         Hamed Junior Traore   20.508275   20.00
208                 Yacine Adli   19.845271   11.00
253                Alieu Fadera   19.482994    4.50
497  Andre-Frank Zambo Anguissa   19.460423   27.00
586                   Manu Kone   19.412133   40.00
224                       Andre   19.097894   28.00
112               Mateo Kovacic   18.742425   20.00
183      Valentin Atangana Edoa   18.414671   10.00
568               Wilfred Ndidi   18.375188   15.00
97               Lucas Bergvall   18.361987   38.00
223                Lee Jae-sung   18.315645    2.50
542               Javier Guerra   18.236066   25.00
540                Jens Cajuste   17.915063   12.00
496              Nicolo Barella   17.743990   75.00
138                     Ederson   17.715499   50.00
221            Matteo Guendouzi   17.416342   32.00
508                  Simon Sohm   17.155039    5.00
126     Hans Nicolussi Caviglia   17.124231    8.50
80                Kobbie Mainoo   17.124146   50.00
557              Lucas Da Cunha   16.935193   10.00
206                  Gustavo sa   16.891427   16.00
283                Hugo Larsson   16.877781   40.00
79               Joshua Kimmich   16.798458   45.00
39              Andreas Pereira   16.469929   18.00
555              İlkay Gundogan   16.108971    5.00
472               Adrien Rabiot   16.062092   25.00
349       Manuel Ugarte Ribeiro   16.027137   45.00
520             Morten Frendrup   15.961576   20.00
591               Pablo Barrios   15.841737   55.00
570                 Tyler Adams   15.709011   18.00
98              Youssouf Fofana   15.436765   30.00
382            Mikel Jauregizar   15.075695   30.00
468                        Isco   14.939473    6.00
302              Jacopo Fazzini   14.746852   10.00
421          Jurgen Ekkelenkamp   14.518918    7.00
364              Gianluca Busio   14.465633    6.00
84                 Granit Xhaka   14.437816   12.00
510               Armin Gigovic   14.351998    3.00
62                   Ryan Yates   14.225807   12.00
243           Alessandro Bianco   14.093337    5.00
164            Corentin Tolisso   13.911796   12.00
353             Neil El Aynaoui   13.362306   15.00
477               Jan Schoppner   13.235294    4.00
293           Exequiel Palacios   13.181005   40.00
432                  Alex Scott   12.871806   20.00
467          Abdoulaye Doucoure   12.808667    7.00
446                Flynn Downes   12.761087   13.00
72                 Senny Mayulu   12.423097   15.00
291              Nicolo Rovella   12.409018   30.00
339                      Bitelo   12.324965   12.00
304            Adrien Thomasson   12.229453    5.00
127          Idrissa Gana Gueye   12.060882    1.50
131            Eduard Spertsyan   12.040330   25.00
177              Seydouba Cisse   12.009135    3.00
189                 Rocco Reitz   11.959771   15.00
308              Yangel Herrera   11.888519   15.00
552                 Marc Casado   11.774644   30.00
166             Johann Lepenant   11.738068    6.00
290                  Sasa Lukic   11.536232   14.00
411             Davide Frattesi   11.510747   35.00
248                  Andy Diouf   11.398613   15.00
78              Conor Gallagher   11.312327   40.00
565                  Samu Costa   11.277533   15.00
452                 Mohamed Haj   11.251080    1.80
609             Gvidas Gineitis   11.244604    6.00
427             Hicham Boudaoui   11.187080   15.00
405       Cristian Casseres Jr.   11.087146    6.00
363                Sander Berge   11.078387   25.00
227         Pierre Ekwah Elimby   11.056510    7.00
175           Boubakary Soumare   10.981163   12.00
577                 Amine Harit   10.980903    8.00
259            Faustino Anjorin   10.938563    6.00
118                Hans Vanaken   10.938251    7.00
501                 Diego Gomez   10.835938   14.00
598           Maximilian Arnold   10.762194    5.00
541             Mauro Arambarri   10.578950   12.00
2                   Orkun Kokcu   10.415220   30.00
317           Marco Brescianini   10.346377    8.00
346             Pierre Hojbjerg   10.306333   20.00
6                  Felix Nmecha   10.264963   28.00
194            Enzo Barrenechea   10.162637   10.00
354              Maximo Perrone   10.055694   12.00
406                 Romeo Lavia   10.045509   40.00
116                Frank Onyeka   10.030510    7.00
309            Martin Zubimendi   10.024547   60.00
50             Giovanni Fabbian    9.962790   12.00
548              Reda Belahyane    9.947678   10.00
161                Orel Mangala    9.797357   18.00
437                 Will Hughes    9.768003    7.00
106          Rolando Mandragora    9.674122   12.00
448            Manuel Locatelli    9.514895   30.00
579                 Tommy Doyle    9.505963   10.00
430               Lucien Agoume    9.492710    8.00
417            Fabian Ruiz Pena    9.491825   40.00
589                  Matus Bero    9.295783    3.00
66                    Sam Morsy    9.277607    0.50
74                   Luis Milla    9.258902    3.50
135      Thorir Johann Helgason    9.172026    3.00
30           Michel Ndary Adopo    9.089629    4.00
284            Mario Stroeykens    9.079802   12.00
315            Hakan Calhanoglu    9.067860   30.00
453            Ezechiel Banzuzi    9.062478   13.00
296                 Harry Winks    8.937071    9.00
149             Niccolo Pisilli    8.879366   13.00
390              Tim Iroegbunam    8.693734    9.00
219       Konstantinos Karetsas    8.692505   20.00
512            Jesper Karlstrom    8.676164    4.00
621                Warren Bondo    8.546296   10.00
305           Lassana Coulibaly    8.536784    2.50
130              Ayyoub Bouaddi    8.418034   28.00
416                 Lovro Majer    8.416761   17.00
499             Rodrigo De Paul    8.383000   25.00
132                 Mason Mount    8.355770   28.00
425              Tajon Buchanan    8.287412    6.00
76             Nicolas Gonzalez    8.213837   40.00
616                Ross Barkley    8.208429    6.00
344        Maximilian Eggestein    8.195458   10.00
461                 Joshua King    8.170584    1.00
54                Yves Bissouma    8.096471   25.00
86              Rabby Nzingoula    8.055976    2.50
418              Adrian Bernabe    8.000226   15.00
102              Jackson Irvine    7.860964    2.00
530              Cesare Casadei    7.796344   15.00
20             Arthur Vermeeren    7.794205   22.00
44                 Fran Beltran    7.791830    8.00
165               Azor Matusiwa    7.775432    8.00
96                 Elisha Owusu    7.739563    3.00
75              Lazar Samardzic    7.723687   17.00
584              Nicolo Fagioli    7.688514   18.00
18             Kristjan Asllani    7.679958   13.00
457           Rodrigo Bentancur    7.656449   30.00
256              Sergi Altimira    7.636529   15.00
281              Vincent Sierro    7.628151    4.00
178                 Pablo Marin    7.553398    8.00
160              Antoni Milambo    7.548157   18.00
24            Antoine Makoumbou    7.510180    3.50
358             Ibrahim Sangare    7.504994   24.00
240                 Senne Lynen    7.461517    9.00
553                 Noah Sadiki    7.453310   12.00
270                 Amadou Kone    7.440439    4.00
482             Pedrinho Santos    7.433654   10.00
19             Ibrahima Sissoko    7.432764    6.00
279               Daichi Kamada    7.425365   12.00
292                  Luka Sucic    7.369450   15.00
233             Patrizio Masini    7.263212    6.00
151            Ibrahim Sulemana    7.131807    7.00
563       Christoph Baumgartner    7.079118   12.00
57                 Julian Weigl    7.072614    6.00
229                Oliver Skipp    7.015823   10.00
192             Andrei Mostovoy    6.976192    4.00
483                Brais Mendez    6.909000   22.00
235              Antonio Blanco    6.855226   10.00
443           Patrick Osterhage    6.838497   10.00
536                       Batxi    6.706352    5.00
269              Chuky san jose    6.621567    1.50
511              Mathias Jensen    6.523344   14.00
63             Dogucan Haspolat    6.493233    5.00
262                 Ismael Kone    6.462273    9.00
522             Yassin Belkhdim    6.450213    1.00
61          Benjamin Bouchouari    6.444007    5.00
203                 Ivan Martin    6.383258    6.00
567           Stanislav Lobotka    6.369993   25.00
85                 Toby Collyer    6.257110    5.00
459            Mattias Svanberg    6.200686   12.00
49                  Andy Irving    6.187640    4.00
265               Ardon Jashari    6.167213   32.00
507                   Gio Reyna    6.156967    7.00
43                Billy Gilmour    6.154471   20.00
487             Amir Richardson    6.112565    8.50
158                  Kike Perez    6.104707    2.80
628                 Djibril Sow    6.071463    7.50
264              Kanya Fujimoto    5.968921    4.00
438                Kevin Stoger    5.958687    3.50
36                 Kevin Danois    5.870142    8.00
481               Oscar Hojlund    5.831233    7.50
478              Enric Llansana    5.825232    4.00
597             Bryan Cristante    5.814680    7.00
21                Urko Gonzalez    5.808457    5.00
544             Ngal'Ayel Mukau    5.798019   15.00
14                Niklas Dorsch    5.727616    3.50
573             Carlo Boukhalfa    5.720467    2.00
12             Demir Ege Tiknaz    5.709943    5.00
554                Kevin Zeroli    5.693948    4.00
580                 Lucas Torro    5.630175    3.00
439              Andras Schafer    5.625125    5.00
15                Martin Payero    5.612996    5.50
8               Kacper Urbanski    5.542858    6.00
231               Morgan Sanson    5.542740    5.00
159               Medon Berisha    5.539277    1.50
361           Maksim Glushenkov    5.511251   14.00
322                Sven Mijnans    5.441594    9.00
376          Carney Chukwuemeka    5.382795   18.00
588                 Emi Buendia    5.377980   15.00
531       Brian De Keersmaecker    5.353318    3.00
110              Lewis Ferguson    5.329458   28.00
404        Albert Sambi Lokonga    5.293692    8.00
615                      Wendel    5.217490   18.00
460                Jordan James    5.209619    8.00
419          Soungoutou Magassa    5.191854   12.00
288            Pedro Chirivella    5.188014    5.00
471              Danilo Cataldi    5.184776    3.50
209       Jose Luis Garcia Vaya    5.181268    9.00
445             Elvis Rexhbecaj    5.179265    3.50
314           Balthazar Pierret    5.164129    1.70
214                Razvan Marin    5.077941    3.50
25                 Adem Zorgane    5.013981    6.00
547                 Saul Niguez    4.983202    3.00
434              Sean Longstaff    4.972249   20.00
77              Frenkie de Jong    4.969171   45.00
367                Rani Khedira    4.941401    2.50
400           Mahamadou Diawara    4.851834    2.00
46                Youssef Maleh    4.803462    3.20
607             Cheick Doucoure    4.789337   25.00
16                   Yvan Neyou    4.788224    3.00
355          Ivan Jaime Pajuelo    4.770895    5.00
95                 Oscar Fraulo    4.691311    3.50
109          Lorenzo Pellegrini    4.681089    9.00
153                Benat Prados    4.664811   18.00
218                 Suat Serdar    4.655676    4.50
298                 Bilal Nadir    4.627946    5.00
455                Stije Resink    4.582978    4.00
56               Ivan Oleinikov    4.563002    1.40
193                   Ivan Ilic    4.561629   16.00
456               Mats Pannewig    4.514623    1.00
465              Mathis Amougou    4.474827   10.00
137              Alberto Grassi    4.472834    1.80
516                Daan Heymans    4.440807    3.00
111                Pablo Ibanez    4.395886    2.00
420               Selim Amallah    4.385127    1.60
67             Jordan Holsgrove    4.378884    3.50
3                Ylber Ramadani    4.376401    1.80
538              Emircan Gurluk    4.374526    0.60
560           Christian Eriksen    4.363987    4.00
534                 Nikola Moro    4.298825    4.50
295                 Joel Fujita    4.287307    3.00
140             Guido Rodriguez    4.247457   10.00
212                 Joan Jordan    4.245343    2.50
225                  Jhon Solis    4.214117    2.50
606           Donny van de Beek    4.189973    5.00
503               Ander Guevara    4.181593    3.50
528               Hong Hyunseok    4.141657    3.50
53                        Artur    4.140972    8.00
622                Alfie Devine    4.137323    3.50
610             Tanguy Ndombele    4.130434    7.00
527                     Hernani    4.116225    1.60
600                  Olasagasti    4.056131    4.00
604                Nathan Rodes    4.052126    1.40
524             Evert Linthorst    4.037572    2.50
551                 Hugo Sotelo    4.009718    4.00
521                 Tom Cairney    3.985219    1.50
196                  Pol Lozano    3.984945    5.00
371       Magnus Kofod Andersen    3.940566    1.00
33               Moumi Ngamaleu    3.921541    4.00
556                Joey Veerman    3.883576   25.00
71                  Francis Abu    3.878936    1.80
37              Luca Mazzitelli    3.877123    1.50
329             Samuele Vignato    3.874207    2.20
7                Philipp Sander    3.866962    4.00
392                  Pedro Diaz    3.866130    3.00
202             Ismael Bennacer    3.856660   15.00
429           Mahamadou Doumbia    3.853790    9.00
282               Igor Dmitriev    3.849323    1.00
475                Taichi Fukui    3.795071    2.00
464                   Marc Roca    3.789004    6.00
480             Piotr Zielinski    3.785358   10.00
93                   Max Balard    3.781677    1.50
351              Benjamin Andre    3.777004    5.00
413             Leandre Kuavita    3.762654    1.50
562                Tomas Handel    3.752470   13.00
150           Charles Vanhoutte    3.728056    6.00
169                  Iker Munoz    3.673003    3.00
267                 Ryotaro Ito    3.663657    2.50
241                Luis Esteves    3.619149    1.00
257                Matteo Prati    3.558194    6.00
185                 Jesse Bosch    3.553311    0.90
58                Daniel Parejo    3.551861    1.50
191               German Valera    3.550912    1.50
13                Stefan Loncar    3.538661    1.50
83             Benat Turrientes    3.509176   10.00
433               Jon Moncayola    3.498836    7.00
17                 Edu Exposito    3.421478    3.00
40                  Rob Schoofs    3.403072    2.20
152                Oier Zarraga    3.384725    2.00
397                Danil Glebov    3.359839    8.00
190                Espen van Ee    3.266017    1.30
335             Daniel Braganca    3.246143   12.00
546           Dave Van Den Berg    3.245300    2.00
388              Matvei Kisliak    3.239361    8.00
331                 Hamza Rafia    3.224716    1.40
238           Aleksa Djurasovic    3.204597    2.00
27             Damian Rodriguez    3.179727    3.00
155                  Ryan Fosso    3.179410    1.50
22                 Rudy Matondo    3.132813    0.30
250             Antoine Bernede    3.129815    2.50
154               Aster Vranckx    3.125088    7.00
493        Leonardo Bittencourt    3.121656    1.50
68              Santiago Garcia    3.086510    0.80
99            Pierre Lees-Melou    3.085022    6.00
134               Miguel Menino    3.081366    1.00
300              Haris Belkebla    3.051813    2.00
336                 Isaac Price    2.973054    3.00
613          Anouar Ait El Hadj    2.972388    3.00
260             Djibril Soumare    2.963918    1.50
263              Niklas Schmidt    2.951559    1.80
303            Yassine Titraoui    2.941030    5.00
254               Lucas Tousart    2.928233    2.50
368            Carlos Benavidez    2.921750    1.20
377            Raphael Onyedika    2.915405   20.00
100           Jean-Eudes Aholou    2.912210    2.00
458               Enzo Loiodice    2.907889    1.20
378               Matias Vecino    2.907741    2.00
466              Philip Billing    2.869347   10.00
90                Cheikh Niasse    2.853163    2.50
337             Florian Neuhaus    2.844654    3.50
395               Sergey Babkin    2.842589    1.80
73              Nikita Krivtsov    2.842361    4.00
495              Amadou Haidara    2.842290   16.00
605              Oscar Valentin    2.837367    2.50
41          Nikolas Sattlberger    2.832924    3.50
45                      Adriano    2.802967    2.50
490               Davy Klaassen    2.794216    3.50
133           Kirill Shchetinin    2.789032    2.80
422               Marcus Linday    2.782267    4.00
572       Almoatasem Al Musrati    2.774841    8.00
38                 Bryan Heynen    2.768579   11.00
157                Mohamed Kaba    2.762889    2.00
117                 Enzo Le Fee    2.762114   18.00
94                 Jose Campana    2.749913    0.90
519                        Koke    2.743219    8.00
539         Lucas Gourna-Douath    2.741065    8.00
287                 Luka Modric    2.703369    4.00
431               Dani Ceballos    2.688938   10.00
181         Baptiste Santamaria    2.681274    7.00
188               Franco Orozco    2.677349    1.50
333                 Tiago Silva    2.645849    3.00
578              Julian Niehues    2.625678    1.50
529         Christopher Martins    2.613770    6.00
581            Siebe Schrijvers    2.611169    1.50
603             Daniel Bandeira    2.609199    2.50
334                Andrei Ivlev    2.599277    0.40
569            Michel Aebischer    2.586071    7.50
360                Stanko Juric    2.582615    1.20
327               Yannik Keitel    2.560655    3.50
352                Nail Umyarov    2.548610    4.00
28            Mathias Rasmussen    2.547848    2.00
436            Faisal Al Ghamdi    2.518958    1.50

<b>Модель 2</b>

In [6]:
X_train = X_train[['G+A', 'Ast.1', 'Gls.1', 'SoT/90', '90s', 'Fld', 'CrdY', 'SoT%', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Ast.1', 'Gls.1', 'SoT/90', '90s', 'Fld', 'CrdY', 'SoT%', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [13]:
coeffs_df

               coeff
league_GB1  0.578777
90s         0.498539
Age        -0.434598
league_IT1  0.383718
league_ES1  0.304167
league_L1   0.293895
league_FR1  0.253822
Ast.1       0.181157
G+A         0.160573
Gls.1       0.132066
Fld         0.124532
CrdY       -0.115147
league_NL1 -0.105165
league_RU1 -0.097126
SoT%        0.063561
SoT/90      0.055668
league_PO1 -0.051583

In [14]:
metrics

            MAE       RMSE      MAPE        R2
test   5.768209  14.555255  0.964026  0.531295
train  5.315549  10.920498  0.865460  0.477988

In [15]:
comp_leftovers_test

                       Player  Value_pred    Value
0                Sandi Lovric   11.146894    8.500
1              Danila Godiaev    0.937110    1.500
2     Inigo Ruiz de Galarreta    3.063885    3.000
3              Johnny Cardoso   11.521856   25.000
4                  Unai Lopez    4.110745    2.500
5          Florian Grillitsch    2.478522    2.000
6              Mahmoud Dahoud    3.045875    3.500
7               Teji Savanier    8.477398    2.500
8                Djaoui Cisse    5.716981    8.000
9               Dean Huiberts    0.869625    0.300
10            Khephren Thuram   20.267384   40.000
11                 Pape Gueye   10.923877   15.000
12      Thomas Van den Keybus    1.473938    0.800
13              Sandro Tonali   44.201467   60.000
14     Ibrahima Sory Bangoura    1.931745    8.000
15        Vladimir Moskvichev    0.493343    0.500
16               Lasse Schone    0.135035    0.075
17            Kalvin Phillips    5.219005   12.000
18         Morgan Gibbs-White   81.095008   50.000
19              Ilija Vukotic    2.413670    0.600
20               Issa Doumbia    6.027321    2.400
21        Eduardo Felicissimo    1.111074    3.000
22              Stefano Sensi    2.436753    1.000
23             Tommaso Pobega    5.867630    9.000
24          Fernando Costanza    1.861635    3.000
25               Ilaix Moriba   11.561491    6.000
26            Finn Ole Becker    3.920028    2.000
27                   Casemiro    5.147623   10.000
28                Kaishu Sano   13.404899   20.000
29         Matthias Braunoder    2.242250    1.400
30            Abdoulaye Toure   10.491778    3.000
31                David Simao    0.507742    0.100
32                Ondrej Duda    6.585945    3.500
33        Oussama Targhalline    4.112149    4.000
34               Daniil Utkin    1.979681    2.800
35              Edson Alvarez    8.243533   25.000
36             Magnus Knudsen    5.837721    2.500
37         Henrikh Mkhitaryan    3.879124    4.000
38                Anas Tahiri    0.806557    0.500
39           Maxence Caqueret    8.676161   16.000
40               Nadiem Amiri   21.038074   20.000
41            Yehor Yarmoliuk   13.116090   15.000
42             Atakan Karazor   13.033145   12.000
43              Jonatan Lucca    0.340611    0.200
44                  Thom Haye    0.971442    1.000
45              Karol Linetty    2.741726    1.800
46            Mathias Delorge    6.934933    9.000
47            Rodrigo Saravia    1.391804    1.500
48           Jordan Henderson    0.690042    2.500
49             Miralem Pjanic    0.468916    2.000
50               Bence Dardai   10.269493   12.000
51                Alan Varela    2.581490   32.000
52            Nick Fichtinger    1.014731    0.450
53          Vladislav Kamilov    1.005579    0.800
54                 Kevin Pina    1.950739    5.000
55                  Alex Kral    7.733522    6.000
56               Isaac Babadi    2.224804    3.000
57         Iaroslav Mikhailov    1.959725    0.800
58           Kirian Rodriguez    5.151973    1.000
59               Lewis Holtby    1.873063    0.500
60                 Tom Krauss    3.935844    4.000
61              Mario Pasalic    8.351328   10.000
62               Daniil Fomin    2.708503    8.000
63                 Arne Maier    3.345422    4.000
64            Benjami­n Garre    1.075321    6.000
65              Luka Gagnidze    2.408042    1.200
66              Lamine Camara   20.691665   22.000
67             Nabil Bentaleb    1.510184    6.000
68              Harrison Reed    3.749383    6.000
69          Alessandro Deiola    3.683620    1.600
70          James Ward-Prowse    8.253075    8.000
71              Ryan Christie   14.454385   10.000
72                Salih Ozcan    2.242891    4.000
73             Justin Devenny   19.180857    6.000
74              Kian Fitz-Jim    2.200940    5.000
75               Jonas Martin    0.920221    0.600
76              Roberto Lopez    3.033162    1.000
77         Dominik Szoboszlai   67.702569   80.000
78              Denis Zakaria   10.922018   30.000
79             Rassoul Ndiaye    4.258961    2.000
80           Lawrence Agyekum    4.073104    2.500
81               Ivan Komarov    2.557913    2.000
82                Andre Horta    2.150257    4.000
83            Jude Bellingham   70.251175  180.000
84                       Igor    1.132845    3.500
85        Kamiel Van De Perre    1.688972    3.000
86               Aleix Garcia    7.665503   20.000
87            Justin Kluivert   90.486973   35.000
88              Paulo Moreira    1.635026    0.400
89                 Mert Komur   11.468324    5.000
90            Florian Tardieu    3.592168    0.600
91               Louis Mouton    4.072616    0.700
92          William Smallbone    7.679081    6.000
93            Nikita Saltykov    1.042811    2.000
94             Esequiel Barco   18.000559   14.000
95              Ellyes Skhiri    4.742568    7.500
96            Morten Hjulmand    2.789748   50.000
97           Gustavo Mendonca    1.426296    0.400
98            Leandro Paredes    3.984068    5.000
99             Angelo Stiller   26.681726   45.000
100                      Alan   11.092648    4.000
101            Sherzod Esanov    0.830328    0.300
102             Gerard Gumbau    1.986682    1.500
103             Hugo Magnetti    5.470964    6.000
104            Vi­ctor Mendez    0.795801    1.800
105              Mario Martin    9.559854    1.500
106             Robert Wagner    2.805533    3.000
107              Can Bozdogan    1.162737    3.500
108               Vadim Rakov    2.498858    1.200
109              Remo Freuler    6.382646    5.000
110          Aljoscha Kemlein    5.689450    7.000
111                  Guus Til   15.509867   12.000
112            Yellu Santiago    2.298001    0.900
113           Kristijan Jakic    7.035377    6.500
114             Samuele Ricci   19.693514   30.000
115         Han-Noah Massengo    3.428295    5.000
116          Maksim Paliyenko    0.501458    0.350
117                      Neto    0.590389    0.200
118            Darko Brasanac    2.444184    0.500
119                   Douglas    8.419035    6.000
120            Viktor Okishor    6.149965    0.500
121            Liam Henderson    5.778171    2.000
122           Diego Rodrigues    2.695942    2.000
123             Jamal Musiala   53.941833  140.000
124            Santi Comesana    8.350034    8.000
125       Vladislav Masternoy    0.327563    0.600
126      Jean-Philippe Gbamin    1.017573    2.000
127            Tim van de Loo    2.347722    0.600
128     Branco van den Boomen    0.493918    3.500
129            Gjivai Zechiel    3.005063    4.000
130            Matteo Pessina    2.085661    6.000
131               Jakub Moder    1.930388   12.000
132           Daouda Weidmann    0.858105    0.300
133            Aimen Moueffek    3.644793    2.500
134               Ulvi Babaev    0.977392    0.250
135                   Keliano    1.271380    0.400
136              Roman Yezhov    1.359150    1.800
137               Angel Gomes    4.391286   20.000
138             Junior Mwanga    7.012388    6.000
139       Aleksandar Pavlovic    7.894632   55.000
140       Dmitrii Aleksandrov    0.839908    0.350
141           Boubacar Kamara   16.215449   40.000
142  Leandro Barreiro Martins    2.402383   15.000
143          Gustavo Assuncao    1.335468    1.000
144              Dario Essugo    7.559104   20.000
145               Lewis Miley   16.860823   22.000
146                Jean Gorby    1.589943    4.000
147             Yassin Oukili    4.717674    0.900
148           Arthur Piedfort    3.092629    2.000
149            Nampalys Mendy    1.106888    1.800
150              Matt O'Riley   18.885974   22.000
151           Marcel Sabitzer    2.948365    8.000
152           Tanner Tessmann    5.418775    6.000
153             Danil Prutsev    2.024497    4.000
154                Roman Kvet    3.121609    1.500
155          Marshall Munetsi   13.543279   15.000
156           Nicolai Remberg    7.469163    3.000
157             Joris Chotard    5.486326    6.000

In [17]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                         Player  Value_pred   Value
428             Bruno Guimaraes  111.387049   80.00
500              Enzo Fernandez  100.260927   75.00
275             Bruno Fernandes   86.106958   50.00
386              James Maddison   76.885056   42.00
525            Mateus Fernandes   75.470807   15.00
113                 Xavi Simons   63.760017   70.00
115             Elliot Anderson   63.654943   32.00
167             Youri Tielemans   62.482759   38.00
268            Ryan Gravenberch   58.025353   75.00
398             Martin Ødegaard   51.738319   85.00
523         Alexis Mac Allister   51.053728  100.00
215             Scott McTominay   49.482984   50.00
629                 Declan Rice   49.203831  120.00
232               Carlos Baleba   47.749762   40.00
120               Andrey Santos   47.000148   35.00
498                  Sem Steijn   45.604568   16.00
297                  Paul Nebel   43.919117   24.00
59           Bilal El Khannouss   42.622170   28.00
313                       Pedri   39.311435  140.00
60            Tijjani Reijnders   37.708221   60.00
451            Emile Smith Rowe   35.924808   30.00
385             Pape Matar Sarr   35.266901   32.00
26                   Joao Gomes   34.690582   40.00
64                      Vitinha   34.627332   80.00
266                 Yasin Ayari   32.170276   22.00
399                  Aimar Oroz   31.717584   15.00
103                Oihan Sancet   28.923812   60.00
210               Romano Schmid   26.993633   17.00
91           Christian Norgaard   26.083147   11.00
246                Tomas Soucek   25.552676   18.00
180              Harvey Elliott   24.783084   30.00
207              Ismael Saibari   24.351148   27.00
559               Julian Brandt   23.127892   25.00
217         Hamed Junior Traore   22.948189   20.00
299                Amadou Onana   21.411586   50.00
10             Giuliano Simeone   20.848152   35.00
586                   Manu Kone   20.308146   40.00
163               Vitaly Janelt   19.854107   20.00
126     Hans Nicolussi Caviglia   19.754012    8.50
224                       Andre   18.952037   28.00
183      Valentin Atangana Edoa   18.947979   10.00
97               Lucas Bergvall   18.846880   38.00
138                     Ederson   18.547196   50.00
568               Wilfred Ndidi   18.436230   15.00
508                  Simon Sohm   18.400669    5.00
557              Lucas Da Cunha   18.273658   10.00
357                  Jens Stage   18.267801   14.00
112               Mateo Kovacic   18.266026   20.00
542               Javier Guerra   18.197164   25.00
208                 Yacine Adli   18.065560   11.00
497  Andre-Frank Zambo Anguissa   18.035938   27.00
283                Hugo Larsson   17.756030   40.00
80                Kobbie Mainoo   17.615006   50.00
221            Matteo Guendouzi   17.503545   32.00
540                Jens Cajuste   17.181870   12.00
223                Lee Jae-sung   16.978627    2.50
468                        Isco   16.955656    6.00
520             Morten Frendrup   16.873382   20.00
472               Adrien Rabiot   16.551374   25.00
253                Alieu Fadera   16.529334    4.50
206                  Gustavo sa   16.386297   16.00
39              Andreas Pereira   16.369612   18.00
496              Nicolo Barella   15.964648   75.00
591               Pablo Barrios   15.790326   55.00
349       Manuel Ugarte Ribeiro   15.767809   45.00
382            Mikel Jauregizar   15.698854   30.00
555              İlkay Gundogan   15.437309    5.00
79               Joshua Kimmich   15.365124   45.00
570                 Tyler Adams   15.175898   18.00
62                   Ryan Yates   14.950586   12.00
364              Gianluca Busio   14.907270    6.00
302              Jacopo Fazzini   14.767292   10.00
243           Alessandro Bianco   14.533159    5.00
353             Neil El Aynaoui   14.468423   15.00
131            Eduard Spertsyan   14.421242   25.00
164            Corentin Tolisso   14.361375   12.00
510               Armin Gigovic   14.355778    3.00
293           Exequiel Palacios   13.656832   40.00
98              Youssouf Fofana   13.644597   30.00
432                  Alex Scott   13.419971   20.00
477               Jan Schoppner   13.337880    4.00
427             Hicham Boudaoui   13.053361   15.00
467          Abdoulaye Doucoure   13.024939    7.00
446                Flynn Downes   12.735152   13.00
72                 Senny Mayulu   12.596087   15.00
291              Nicolo Rovella   12.586557   30.00
541             Mauro Arambarri   12.559605   12.00
339                      Bitelo   12.499518   12.00
189                 Rocco Reitz   12.457381   15.00
308              Yangel Herrera   12.218786   15.00
565                  Samu Costa   11.921242   15.00
2                   Orkun Kokcu   11.918987   30.00
84                 Granit Xhaka   11.899418   12.00
127          Idrissa Gana Gueye   11.763407    1.50
452                 Mohamed Haj   11.655322    1.80
166             Johann Lepenant   11.559714    6.00
577                 Amine Harit   11.530474    8.00
177              Seydouba Cisse   11.513320    3.00
227         Pierre Ekwah Elimby   11.500504    7.00
304            Adrien Thomasson   11.490487    5.00
118                Hans Vanaken   11.358222    7.00
609             Gvidas Gineitis   11.257944    6.00
290                  Sasa Lukic   11.241717   14.00
421          Jurgen Ekkelenkamp   11.229200    7.00
248                  Andy Diouf   11.222786   15.00
363                Sander Berge   11.109059   25.00
411             Davide Frattesi   11.097524   35.00
552                 Marc Casado   10.956214   30.00
501                 Diego Gomez   10.911954   14.00
259            Faustino Anjorin   10.885402    6.00
598           Maximilian Arnold   10.801197    5.00
175           Boubakary Soumare   10.733273   12.00
106          Rolando Mandragora   10.624078   12.00
78              Conor Gallagher   10.485766   40.00
405       Cristian Casseres Jr.   10.419829    6.00
406                 Romeo Lavia   10.276462   40.00
315            Hakan Calhanoglu   10.245213   30.00
309            Martin Zubimendi   10.218828   60.00
116                Frank Onyeka   10.199235    7.00
448            Manuel Locatelli   10.184755   30.00
317           Marco Brescianini   10.078110    8.00
6                  Felix Nmecha   10.005057   28.00
579                 Tommy Doyle    9.882884   10.00
194            Enzo Barrenechea    9.774109   10.00
50             Giovanni Fabbian    9.753813   12.00
346             Pierre Hojbjerg    9.705474   20.00
548              Reda Belahyane    9.704272   10.00
161                Orel Mangala    9.645026   18.00
74                   Luis Milla    9.618845    3.50
354              Maximo Perrone    9.607573   12.00
219       Konstantinos Karetsas    9.357703   20.00
135      Thorir Johann Helgason    9.344286    3.00
589                  Matus Bero    9.319027    3.00
344        Maximilian Eggestein    9.271187   10.00
296                 Harry Winks    9.226123    9.00
417            Fabian Ruiz Pena    9.121272   40.00
437                 Will Hughes    9.120210    7.00
390              Tim Iroegbunam    9.092179    9.00
66                    Sam Morsy    9.029886    0.50
149             Niccolo Pisilli    8.997528   13.00
453            Ezechiel Banzuzi    8.973787   13.00
284            Mario Stroeykens    8.837108   12.00
30           Michel Ndary Adopo    8.828755    4.00
430               Lucien Agoume    8.795520    8.00
621                Warren Bondo    8.644374   10.00
416                 Lovro Majer    8.593918   17.00
461                 Joshua King    8.575794    1.00
130              Ayyoub Bouaddi    8.486830   28.00
18             Kristjan Asllani    8.484786   13.00
305           Lassana Coulibaly    8.483401    2.50
102              Jackson Irvine    8.397565    2.00
86              Rabby Nzingoula    8.304385    2.50
75              Lazar Samardzic    8.234232   17.00
132                 Mason Mount    8.209380   28.00
418              Adrian Bernabe    8.178444   15.00
292                  Luka Sucic    8.139022   15.00
54                Yves Bissouma    8.137609   25.00
616                Ross Barkley    8.121551    6.00
530              Cesare Casadei    8.097395   15.00
281              Vincent Sierro    8.071771    4.00
563       Christoph Baumgartner    8.061900   12.00
358             Ibrahim Sangare    8.003953   24.00
256              Sergi Altimira    7.873600   15.00
279               Daichi Kamada    7.846184   12.00
512            Jesper Karlstrom    7.824576    4.00
178                 Pablo Marin    7.819829    8.00
457           Rodrigo Bentancur    7.808893   30.00
270                 Amadou Kone    7.789848    4.00
584              Nicolo Fagioli    7.696301   18.00
20             Arthur Vermeeren    7.624029   22.00
19             Ibrahima Sissoko    7.576339    6.00
516                Daan Heymans    7.551795    3.00
553                 Noah Sadiki    7.549188   12.00
44                 Fran Beltran    7.512875    8.00
240                 Senne Lynen    7.372036    9.00
499             Rodrigo De Paul    7.315233   25.00
57                 Julian Weigl    7.213411    6.00
165               Azor Matusiwa    7.197682    8.00
192             Andrei Mostovoy    7.172856    4.00
233             Patrizio Masini    7.159559    6.00
229                Oliver Skipp    7.137277   10.00
96                 Elisha Owusu    7.104598    3.00
482             Pedrinho Santos    7.054107   10.00
151            Ibrahim Sulemana    7.037022    7.00
438                Kevin Stoger    7.023473    3.50
24            Antoine Makoumbou    7.006046    3.50
483                Brais Mendez    6.912781   22.00
160              Antoni Milambo    6.850357   18.00
443           Patrick Osterhage    6.840172   10.00
511              Mathias Jensen    6.725427   14.00
235              Antonio Blanco    6.699042   10.00
269              Chuky san jose    6.603343    1.50
522             Yassin Belkhdim    6.577502    1.00
85                 Toby Collyer    6.554256    5.00
265               Ardon Jashari    6.504537   32.00
63             Dogucan Haspolat    6.472647    5.00
262                 Ismael Kone    6.454185    9.00
61          Benjamin Bouchouari    6.430988    5.00
203                 Ivan Martin    6.397741    6.00
459            Mattias Svanberg    6.363427   12.00
507                   Gio Reyna    6.207239    7.00
487             Amir Richardson    6.202148    8.50
536                       Batxi    6.125639    5.00
264              Kanya Fujimoto    6.121656    4.00
628                 Djibril Sow    6.095677    7.50
322                Sven Mijnans    6.093407    9.00
36                 Kevin Danois    6.066089    8.00
531       Brian De Keersmaecker    6.047982    3.00
567           Stanislav Lobotka    5.978310   25.00
481               Oscar Hojlund    5.959507    7.50
554                Kevin Zeroli    5.950351    4.00
21                Urko Gonzalez    5.852586    5.00
544             Ngal'Ayel Mukau    5.843860   15.00
158                  Kike Perez    5.809639    2.80
573             Carlo Boukhalfa    5.776324    2.00
209       Jose Luis Garcia Vaya    5.768629    9.00
214                Razvan Marin    5.743397    3.50
43                Billy Gilmour    5.723399   20.00
110              Lewis Ferguson    5.675078   28.00
361           Maksim Glushenkov    5.637923   14.00
15                Martin Payero    5.629100    5.50
159               Medon Berisha    5.609204    1.50
14                Niklas Dorsch    5.566581    3.50
580                 Lucas Torro    5.554703    3.00
8               Kacper Urbanski    5.542735    6.00
49                  Andy Irving    5.538364    4.00
439              Andras Schafer    5.518428    5.00
109          Lorenzo Pellegrini    5.497771    9.00
404        Albert Sambi Lokonga    5.474673    8.00
12             Demir Ege Tiknaz    5.374465    5.00
597             Bryan Cristante    5.347283    7.00
425              Tajon Buchanan    5.335925    6.00
419          Soungoutou Magassa    5.301697   12.00
460                Jordan James    5.289256    8.00
478              Enric Llansana    5.275269    4.00
445             Elvis Rexhbecaj    5.272946    3.50
376          Carney Chukwuemeka    5.248195   18.00
471              Danilo Cataldi    5.130774    3.50
434              Sean Longstaff    5.125419   20.00
314           Balthazar Pierret    5.092926    1.70
76             Nicolas Gonzalez    5.073010   40.00
25                 Adem Zorgane    5.036763    6.00
231               Morgan Sanson    5.016555    5.00
400           Mahamadou Diawara    4.991064    2.00
607             Cheick Doucoure    4.966041   25.00
288            Pedro Chirivella    4.951033    5.00
588                 Emi Buendia    4.929915   15.00
547                 Saul Niguez    4.896885    3.00
46                Youssef Maleh    4.860173    3.20
77              Frenkie de Jong    4.849571   45.00
153                Benat Prados    4.806441   18.00
615                      Wendel    4.780555   18.00
212                 Joan Jordan    4.780078    2.50
455                Stije Resink    4.776256    4.00
218                 Suat Serdar    4.770468    4.50
527                     Hernani    4.672037    1.60
56               Ivan Oleinikov    4.664183    1.40
367                Rani Khedira    4.650537    2.50
622                Alfie Devine    4.624328    3.50
193                   Ivan Ilic    4.621035   16.00
420               Selim Amallah    4.619342    1.60
16                   Yvan Neyou    4.595764    3.00
560           Christian Eriksen    4.583589    4.00
538              Emircan Gurluk    4.542298    0.60
465              Mathis Amougou    4.531128   10.00
67             Jordan Holsgrove    4.512519    3.50
137              Alberto Grassi    4.500955    1.80
111                Pablo Ibanez    4.495634    2.00
3                Ylber Ramadani    4.487249    1.80
298                 Bilal Nadir    4.459070    5.00
95                 Oscar Fraulo    4.440471    3.50
534                 Nikola Moro    4.306741    4.50
480             Piotr Zielinski    4.287394   10.00
140             Guido Rodriguez    4.283959   10.00
225                  Jhon Solis    4.259711    2.50
40                  Rob Schoofs    4.254105    2.20
503               Ander Guevara    4.246337    3.50
429           Mahamadou Doumbia    4.234934    9.00
7                Philipp Sander    4.191006    4.00
456               Mats Pannewig    4.165486    1.00
610             Tanguy Ndombele    4.103509    7.00
241                Luis Esteves    4.091162    1.00
606           Donny van de Beek    4.063790    5.00
600                  Olasagasti    4.042387    4.00
551                 Hugo Sotelo    3.999434    4.00
371       Magnus Kofod Andersen    3.978977    1.00
521                 Tom Cairney    3.968716    1.50
295                 Joel Fujita    3.935703    3.00
329             Samuele Vignato    3.934003    2.20
392                  Pedro Diaz    3.925448    3.00
556                Joey Veerman    3.923854   25.00
13                Stefan Loncar    3.917773    1.50
196                  Pol Lozano    3.913035    5.00
433               Jon Moncayola    3.912283    7.00
604                Nathan Rodes    3.909524    1.40
53                        Artur    3.899457    8.00
37              Luca Mazzitelli    3.887085    1.50
524             Evert Linthorst    3.875514    2.50
528               Hong Hyunseok    3.864572    3.50
185                 Jesse Bosch    3.835378    0.90
169                  Iker Munoz    3.806523    3.00
267                 Ryotaro Ito    3.787168    2.50
282               Igor Dmitriev    3.766729    1.00
464                   Marc Roca    3.756114    6.00
475                Taichi Fukui    3.691368    2.00
33               Moumi Ngamaleu    3.637501    4.00
257                Matteo Prati    3.621819    6.00
83             Benat Turrientes    3.606771   10.00
351              Benjamin Andre    3.575079    5.00
17                 Edu Exposito    3.569302    3.00
562                Tomas Handel    3.558487   13.00
413             Leandre Kuavita    3.549334    1.50
150           Charles Vanhoutte    3.519480    6.00
71                  Francis Abu    3.519468    1.80
93                   Max Balard    3.488823    1.50
388              Matvei Kisliak    3.472889    8.00
152                Oier Zarraga    3.385878    2.00
58                Daniel Parejo    3.374360    1.50
336                 Isaac Price    3.369697    3.00
190                Espen van Ee    3.353960    1.30
331                 Hamza Rafia    3.285510    1.40
134               Miguel Menino    3.282046    1.00
397                Danil Glebov    3.234763    8.00
154               Aster Vranckx    3.227559    7.00
22                 Rudy Matondo    3.224423    0.30
613          Anouar Ait El Hadj    3.218199    3.00
335             Daniel Braganca    3.217564   12.00
493        Leonardo Bittencourt    3.216410    1.50
27             Damian Rodriguez    3.212659    3.00
238           Aleksa Djurasovic    3.211822    2.00
202             Ismael Bennacer    3.209883   15.00
303            Yassine Titraoui    3.199695    5.00
546           Dave Van Den Berg    3.185476    2.00
263              Niklas Schmidt    3.177476    1.80
250             Antoine Bernede    3.144573    2.50
99            Pierre Lees-Melou    3.101965    6.00
260             Djibril Soumare    3.101765    1.50
191               German Valera    3.095451    1.50
333                 Tiago Silva    3.075638    3.00
395               Sergey Babkin    3.048876    1.80
355          Ivan Jaime Pajuelo    3.045481    5.00
368            Carlos Benavidez    3.024332    1.20
155                  Ryan Fosso    3.021819    1.50
581            Siebe Schrijvers    3.020416    1.50
68              Santiago Garcia    3.011691    0.80
254               Lucas Tousart    2.985557    2.50
100           Jean-Eudes Aholou    2.971442    2.00
458               Enzo Loiodice    2.970228    1.20
300              Haris Belkebla    2.951768    2.00
377            Raphael Onyedika    2.938929   20.00
90                Cheikh Niasse    2.897875    2.50
337             Florian Neuhaus    2.890447    3.50
495              Amadou Haidara    2.863505   16.00
133           Kirill Shchetinin    2.847248    2.80
605              Oscar Valentin    2.844348    2.50
157                Mohamed Kaba    2.821400    2.00
378               Matias Vecino    2.818769    2.00
608                Adam Lallana    2.814229    0.75
539         Lucas Gourna-Douath    2.808677    8.00
41          Nikolas Sattlberger    2.807362    3.50
572       Almoatasem Al Musrati    2.804937    8.00
431               Dani Ceballos    2.803076   10.00
73              Nikita Krivtsov    2.798243    4.00
94                 Jose Campana    2.786704    0.90
45                      Adriano    2.769695    2.50
330              Quinten Timber    2.766106   30.00
181         Baptiste Santamaria    2.754056    7.00
38                 Bryan Heynen    2.720682   11.00
519                        Koke    2.720267    8.00
490               Davy Klaassen    2.719062    3.50
422               Marcus Linday    2.686158    4.00
117                 Enzo Le Fee    2.685995   18.00
603             Daniel Bandeira    2.648871    2.50
334                Andrei Ivlev    2.639368    0.40
569            Michel Aebischer    2.638702    7.50
360                Stanko Juric    2.614401    1.20
436            Faisal Al Ghamdi    2.612702    1.50
188               Franco Orozco    2.582111    1.50
529         Christopher Martins    2.577285    6.00
319                Rafael Bauza    2.557191    0.20
352                Nail Umyarov    2.548271    4.00
578              Julian Niehues    2.534205    1.50
408             Gabriel Vidovic    2.526518    3.00

In [18]:
comp_leftovers_train[comp_leftovers_train['Player'].str.contains('Spert')]

               Player  Value_pred  Value
131  Eduard Spertsyan   14.421242   25.0

<b>Модель 3</b>

In [28]:
X_train = X_train[['G+A', 'Ast.1', 'Gls.1', 'SoT/90', '90s', 'Fld', 'CrdY', 'SoT%', 'Age', 'Crs', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Ast.1', 'Gls.1', 'SoT/90', '90s', 'Fld', 'CrdY', 'SoT%', 'Age', 'Crs', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [34]:
coeffs_df

               coeff
league_GB1  0.573213
90s         0.508289
Age        -0.430135
league_IT1  0.374206
league_ES1  0.296953
league_L1   0.288395
league_FR1  0.242921
G+A         0.188811
Ast.1       0.185464
Fld         0.129201
Gls.1       0.116656
CrdY       -0.116473
league_NL1 -0.114825
league_RU1 -0.105600
SoT/90      0.066696
Crs        -0.066624
SoT%        0.062147
league_PO1 -0.058883

In [35]:
metrics

            MAE       RMSE      MAPE        R2
test   5.686543  13.906516  0.951272  0.572145
train  5.297151  10.922813  0.865137  0.477767

In [36]:
comp_leftovers_test

                       Player  Value_pred    Value
0                Sandi Lovric   10.152456    8.500
1              Danila Godiaev    0.933929    1.500
2     Inigo Ruiz de Galarreta    3.106548    3.000
3              Johnny Cardoso   12.092378   25.000
4                  Unai Lopez    4.083674    2.500
5          Florian Grillitsch    2.502674    2.000
6              Mahmoud Dahoud    3.088466    3.500
7               Teji Savanier    6.435096    2.500
8                Djaoui Cisse    5.743165    8.000
9               Dean Huiberts    0.890311    0.300
10            Khephren Thuram   21.759434   40.000
11                 Pape Gueye   11.325372   15.000
12      Thomas Van den Keybus    1.374094    0.800
13              Sandro Tonali   43.568523   60.000
14     Ibrahima Sory Bangoura    2.000533    8.000
15        Vladimir Moskvichev    0.492167    0.500
16               Lasse Schone    0.134445    0.075
17            Kalvin Phillips    5.176062   12.000
18         Morgan Gibbs-White   87.274409   50.000
19              Ilija Vukotic    2.466137    0.600
20               Issa Doumbia    6.031153    2.400
21        Eduardo Felicissimo    1.104485    3.000
22              Stefano Sensi    2.368756    1.000
23             Tommaso Pobega    6.066630    9.000
24          Fernando Costanza    1.920999    3.000
25               Ilaix Moriba   12.168153    6.000
26            Finn Ole Becker    3.978541    2.000
27                   Casemiro    5.219378   10.000
28                Kaishu Sano   13.764754   20.000
29         Matthias Braunoder    2.236152    1.400
30            Abdoulaye Toure   11.202866    3.000
31                David Simao    0.456520    0.100
32                Ondrej Duda    5.971583    3.500
33        Oussama Targhalline    3.968985    4.000
34               Daniil Utkin    1.889736    2.800
35              Edson Alvarez    8.458941   25.000
36             Magnus Knudsen    5.976046    2.500
37         Henrikh Mkhitaryan    4.011330    4.000
38                Anas Tahiri    0.823608    0.500
39           Maxence Caqueret    8.781148   16.000
40               Nadiem Amiri   17.612586   20.000
41            Yehor Yarmoliuk   12.980807   15.000
42             Atakan Karazor   14.250112   12.000
43              Jonatan Lucca    0.344825    0.200
44                  Thom Haye    0.752064    1.000
45              Karol Linetty    2.801993    1.800
46            Mathias Delorge    6.155769    9.000
47            Rodrigo Saravia    1.390227    1.500
48           Jordan Henderson    0.660475    2.500
49             Miralem Pjanic    0.445490    2.000
50               Bence Dardai   10.361629   12.000
51                Alan Varela    2.386137   32.000
52            Nick Fichtinger    1.004929    0.450
53          Vladislav Kamilov    1.005821    0.800
54                 Kevin Pina    2.046556    5.000
55                  Alex Kral    7.566090    6.000
56               Isaac Babadi    2.166976    3.000
57         Iaroslav Mikhailov    1.965612    0.800
58           Kirian Rodriguez    5.351470    1.000
59               Lewis Holtby    1.792372    0.500
60                 Tom Krauss    3.950782    4.000
61              Mario Pasalic    8.918761   10.000
62               Daniil Fomin    2.859889    8.000
63                 Arne Maier    3.033101    4.000
64            Benjami­n Garre    0.999851    6.000
65              Luka Gagnidze    2.344610    1.200
66              Lamine Camara   18.025204   22.000
67             Nabil Bentaleb    1.462117    6.000
68              Harrison Reed    3.944184    6.000
69          Alessandro Deiola    3.715592    1.600
70          James Ward-Prowse    7.652195    8.000
71              Ryan Christie   14.382463   10.000
72                Salih Ozcan    2.240197    4.000
73             Justin Devenny   19.243291    6.000
74              Kian Fitz-Jim    2.228013    5.000
75               Jonas Martin    0.909984    0.600
76              Roberto Lopez    2.986970    1.000
77         Dominik Szoboszlai   71.752658   80.000
78              Denis Zakaria   11.715398   30.000
79             Rassoul Ndiaye    4.034925    2.000
80           Lawrence Agyekum    4.099701    2.500
81               Ivan Komarov    2.243931    2.000
82                Andre Horta    2.211865    4.000
83            Jude Bellingham   80.428274  180.000
84                       Igor    1.141035    3.500
85        Kamiel Van De Perre    1.724241    3.000
86               Aleix Garcia    6.879287   20.000
87            Justin Kluivert   90.248783   35.000
88              Paulo Moreira    1.648421    0.400
89                 Mert Komur   11.263838    5.000
90            Florian Tardieu    3.636831    0.600
91               Louis Mouton    3.969803    0.700
92          William Smallbone    7.247867    6.000
93            Nikita Saltykov    1.041562    2.000
94             Esequiel Barco   17.286348   14.000
95              Ellyes Skhiri    5.009240    7.500
96            Morten Hjulmand    2.923170   50.000
97           Gustavo Mendonca    1.411369    0.400
98            Leandro Paredes    3.742767    5.000
99             Angelo Stiller   25.124961   45.000
100                      Alan   10.853110    4.000
101            Sherzod Esanov    0.832157    0.300
102             Gerard Gumbau    1.929465    1.500
103             Hugo Magnetti    5.429965    6.000
104            Vi­ctor Mendez    0.807552    1.800
105              Mario Martin    9.888613    1.500
106             Robert Wagner    2.811668    3.000
107              Can Bozdogan    1.154630    3.500
108               Vadim Rakov    2.436952    1.200
109              Remo Freuler    6.572404    5.000
110          Aljoscha Kemlein    5.700641    7.000
111                  Guus Til   17.283793   12.000
112            Yellu Santiago    2.286627    0.900
113           Kristijan Jakic    7.236192    6.500
114             Samuele Ricci   19.764352   30.000
115         Han-Noah Massengo    3.387458    5.000
116          Maksim Paliyenko    0.488757    0.350
117                      Neto    0.599997    0.200
118            Darko Brasanac    2.526842    0.500
119                   Douglas    8.833671    6.000
120            Viktor Okishor    5.380098    0.500
121            Liam Henderson    5.123184    2.000
122           Diego Rodrigues    2.796034    2.000
123             Jamal Musiala   60.313486  140.000
124            Santi Comesana    8.776931    8.000
125       Vladislav Masternoy    0.323162    0.600
126      Jean-Philippe Gbamin    1.011435    2.000
127            Tim van de Loo    2.386223    0.600
128     Branco van den Boomen    0.474911    3.500
129            Gjivai Zechiel    3.121323    4.000
130            Matteo Pessina    2.087235    6.000
131               Jakub Moder    1.972019   12.000
132           Daouda Weidmann    0.840023    0.300
133            Aimen Moueffek    3.663720    2.500
134               Ulvi Babaev    0.999617    0.250
135                   Keliano    1.286172    0.400
136              Roman Yezhov    1.289423    1.800
137               Angel Gomes    4.357147   20.000
138             Junior Mwanga    6.910694    6.000
139       Aleksandar Pavlovic    8.003510   55.000
140       Dmitrii Aleksandrov    0.832177    0.350
141           Boubacar Kamara   16.835476   40.000
142  Leandro Barreiro Martins    2.477267   15.000
143          Gustavo Assuncao    1.332980    1.000
144              Dario Essugo    7.773278   20.000
145               Lewis Miley   16.704051   22.000
146                Jean Gorby    1.597790    4.000
147             Yassin Oukili    4.984584    0.900
148           Arthur Piedfort    3.225844    2.000
149            Nampalys Mendy    1.121592    1.800
150              Matt O'Riley   18.075167   22.000
151           Marcel Sabitzer    2.943326    8.000
152           Tanner Tessmann    5.382057    6.000
153             Danil Prutsev    2.084856    4.000
154                Roman Kvet    3.076361    1.500
155          Marshall Munetsi   14.331603   15.000
156           Nicolai Remberg    7.746945    3.000
157             Joris Chotard    5.224910    6.000

In [37]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                         Player  Value_pred   Value
428             Bruno Guimaraes  123.357156   80.00
500              Enzo Fernandez   94.136497   75.00
386              James Maddison   74.287936   42.00
275             Bruno Fernandes   73.404035   50.00
525            Mateus Fernandes   66.934785   15.00
113                 Xavi Simons   63.403685   70.00
268            Ryan Gravenberch   62.601550   75.00
115             Elliot Anderson   60.210230   32.00
167             Youri Tielemans   57.210814   38.00
215             Scott McTominay   57.090623   50.00
498                  Sem Steijn   53.679738   16.00
120               Andrey Santos   52.400885   35.00
232               Carlos Baleba   50.444262   40.00
398             Martin Ødegaard   50.242442   85.00
523         Alexis Mac Allister   48.725764  100.00
629                 Declan Rice   40.950677  120.00
297                  Paul Nebel   40.053602   24.00
60            Tijjani Reijnders   39.729970   60.00
313                       Pedri   39.365243  140.00
59           Bilal El Khannouss   38.530901   28.00
451            Emile Smith Rowe   38.045373   30.00
385             Pape Matar Sarr   36.963920   32.00
26                   Joao Gomes   35.290724   40.00
64                      Vitinha   34.117653   80.00
399                  Aimar Oroz   33.551042   15.00
103                Oihan Sancet   30.569498   60.00
266                 Yasin Ayari   29.628702   22.00
207              Ismael Saibari   28.799246   27.00
91           Christian Norgaard   28.318355   11.00
246                Tomas Soucek   27.613518   18.00
180              Harvey Elliott   25.450557   30.00
559               Julian Brandt   23.746949   25.00
217         Hamed Junior Traore   23.444119   20.00
210               Romano Schmid   22.924607   17.00
299                Amadou Onana   22.202929   50.00
586                   Manu Kone   21.748780   40.00
10             Giuliano Simeone   20.869823   35.00
163               Vitaly Janelt   20.036798   20.00
112               Mateo Kovacic   20.018156   20.00
357                  Jens Stage   19.818867   14.00
224                       Andre   19.731758   28.00
497  Andre-Frank Zambo Anguissa   19.295849   27.00
138                     Ederson   19.205285   50.00
508                  Simon Sohm   19.029194    5.00
568               Wilfred Ndidi   19.012863   15.00
183      Valentin Atangana Edoa   18.992113   10.00
126     Hans Nicolussi Caviglia   18.868168    8.50
97               Lucas Bergvall   18.644172   38.00
283                Hugo Larsson   18.485263   40.00
223                Lee Jae-sung   18.479751    2.50
221            Matteo Guendouzi   18.205292   32.00
542               Javier Guerra   18.141684   25.00
80                Kobbie Mainoo   17.822471   50.00
520             Morten Frendrup   17.684238   20.00
540                Jens Cajuste   17.639103   12.00
208                 Yacine Adli   17.391998   11.00
472               Adrien Rabiot   17.244423   25.00
206                  Gustavo sa   16.573487   16.00
349       Manuel Ugarte Ribeiro   16.435001   45.00
468                        Isco   16.427930    6.00
591               Pablo Barrios   16.239026   55.00
253                Alieu Fadera   16.224848    4.50
557              Lucas Da Cunha   16.167055   10.00
570                 Tyler Adams   16.068733   18.00
382            Mikel Jauregizar   15.763865   30.00
62                   Ryan Yates   15.714163   12.00
496              Nicolo Barella   15.626556   75.00
555              İlkay Gundogan   15.312723    5.00
164            Corentin Tolisso   15.062958   12.00
293           Exequiel Palacios   15.002438   40.00
510               Armin Gigovic   14.883523    3.00
364              Gianluca Busio   14.764324    6.00
98              Youssouf Fofana   14.652420   30.00
243           Alessandro Bianco   14.539978    5.00
302              Jacopo Fazzini   14.525518   10.00
477               Jan Schoppner   14.288817    4.00
432                  Alex Scott   13.779542   20.00
427             Hicham Boudaoui   13.665536   15.00
541             Mauro Arambarri   13.550512   12.00
467          Abdoulaye Doucoure   13.471613    7.00
118                Hans Vanaken   13.424941    7.00
353             Neil El Aynaoui   13.348753   15.00
131            Eduard Spertsyan   13.276434   25.00
446                Flynn Downes   13.180550   13.00
72                 Senny Mayulu   12.808567   15.00
39              Andreas Pereira   12.780709   18.00
84                 Granit Xhaka   12.716644   12.00
127          Idrissa Gana Gueye   12.707029    1.50
189                 Rocco Reitz   12.594491   15.00
291              Nicolo Rovella   12.515026   30.00
79               Joshua Kimmich   12.392139   45.00
308              Yangel Herrera   12.378910   15.00
565                  Samu Costa   12.276909   15.00
577                 Amine Harit   12.007734    8.00
177              Seydouba Cisse   11.971282    3.00
452                 Mohamed Haj   11.833202    1.80
227         Pierre Ekwah Elimby   11.771805    7.00
421          Jurgen Ekkelenkamp   11.616258    7.00
166             Johann Lepenant   11.612490    6.00
304            Adrien Thomasson   11.542992    5.00
339                      Bitelo   11.513361   12.00
363                Sander Berge   11.402532   25.00
411             Davide Frattesi   11.401892   35.00
552                 Marc Casado   11.385906   30.00
259            Faustino Anjorin   11.142346    6.00
248                  Andy Diouf   11.067853   15.00
78              Conor Gallagher   10.957419   40.00
175           Boubakary Soumare   10.896259   12.00
501                 Diego Gomez   10.802473   14.00
106          Rolando Mandragora   10.680673   12.00
309            Martin Zubimendi   10.625660   60.00
609             Gvidas Gineitis   10.611807    6.00
290                  Sasa Lukic   10.540762   14.00
2                   Orkun Kokcu   10.515209   30.00
116                Frank Onyeka   10.506520    7.00
406                 Romeo Lavia   10.502635   40.00
448            Manuel Locatelli   10.385229   30.00
6                  Felix Nmecha   10.379410   28.00
194            Enzo Barrenechea   10.327313   10.00
346             Pierre Hojbjerg   10.134648   20.00
317           Marco Brescianini   10.128390    8.00
354              Maximo Perrone    9.979200   12.00
548              Reda Belahyane    9.973913   10.00
579                 Tommy Doyle    9.933488   10.00
161                Orel Mangala    9.876542   18.00
50             Giovanni Fabbian    9.867804   12.00
453            Ezechiel Banzuzi    9.738731   13.00
344        Maximilian Eggestein    9.710933   10.00
284            Mario Stroeykens    9.490132   12.00
405       Cristian Casseres Jr.    9.482894    6.00
417            Fabian Ruiz Pena    9.435152   40.00
66                    Sam Morsy    9.344874    0.50
390              Tim Iroegbunam    9.290989    9.00
296                 Harry Winks    9.124815    9.00
149             Niccolo Pisilli    9.104307   13.00
102              Jackson Irvine    9.081059    2.00
30           Michel Ndary Adopo    9.068491    4.00
315            Hakan Calhanoglu    9.056696   30.00
598           Maximilian Arnold    9.006602    5.00
430               Lucien Agoume    8.993081    8.00
621                Warren Bondo    8.719119   10.00
135      Thorir Johann Helgason    8.707032    3.00
305           Lassana Coulibaly    8.698039    2.50
461                 Joshua King    8.536491    1.00
437                 Will Hughes    8.512594    7.00
416                 Lovro Majer    8.505751   17.00
130              Ayyoub Bouaddi    8.461200   28.00
132                 Mason Mount    8.383485   28.00
563       Christoph Baumgartner    8.383183   12.00
54                Yves Bissouma    8.375048   25.00
616                Ross Barkley    8.344319    6.00
530              Cesare Casadei    8.331453   15.00
292                  Luka Sucic    8.257787   15.00
358             Ibrahim Sangare    8.174043   24.00
86              Rabby Nzingoula    8.170528    2.50
256              Sergi Altimira    8.151407   15.00
18             Kristjan Asllani    8.141237   13.00
512            Jesper Karlstrom    8.139456    4.00
418              Adrian Bernabe    8.059185   15.00
219       Konstantinos Karetsas    8.054982   20.00
516                Daan Heymans    8.050450    3.00
457           Rodrigo Bentancur    8.045076   30.00
178                 Pablo Marin    8.037715    8.00
589                  Matus Bero    8.021371    3.00
270                 Amadou Kone    7.874139    4.00
553                 Noah Sadiki    7.850213   12.00
44                 Fran Beltran    7.844026    8.00
20             Arthur Vermeeren    7.832204   22.00
19             Ibrahima Sissoko    7.741257    6.00
75              Lazar Samardzic    7.687626   17.00
240                 Senne Lynen    7.683339    9.00
279               Daichi Kamada    7.649819   12.00
165               Azor Matusiwa    7.570962    8.00
281              Vincent Sierro    7.565915    4.00
57                 Julian Weigl    7.559433    6.00
584              Nicolo Fagioli    7.446615   18.00
160              Antoni Milambo    7.348815   18.00
96                 Elisha Owusu    7.317166    3.00
24            Antoine Makoumbou    7.293787    3.50
192             Andrei Mostovoy    7.284940    4.00
499             Rodrigo De Paul    7.243672   25.00
229                Oliver Skipp    7.197722   10.00
74                   Luis Milla    7.179586    3.50
233             Patrizio Masini    6.997702    6.00
443           Patrick Osterhage    6.832431   10.00
151            Ibrahim Sulemana    6.735423    7.00
483                Brais Mendez    6.732582   22.00
235              Antonio Blanco    6.664537   10.00
511              Mathias Jensen    6.604995   14.00
482             Pedrinho Santos    6.601424   10.00
85                 Toby Collyer    6.579239    5.00
265               Ardon Jashari    6.558322   32.00
522             Yassin Belkhdim    6.504545    1.00
262                 Ismael Kone    6.463718    9.00
61          Benjamin Bouchouari    6.443791    5.00
269              Chuky san jose    6.431271    1.50
203                 Ivan Martin    6.421633    6.00
264              Kanya Fujimoto    6.361040    4.00
628                 Djibril Sow    6.353199    7.50
487             Amir Richardson    6.321548    8.50
459            Mattias Svanberg    6.247738   12.00
531       Brian De Keersmaecker    6.243390    3.00
567           Stanislav Lobotka    6.243060   25.00
438                Kevin Stoger    6.157490    3.50
536                       Batxi    6.127551    5.00
21                Urko Gonzalez    6.050839    5.00
554                Kevin Zeroli    6.032619    4.00
481               Oscar Hojlund    5.989351    7.50
36                 Kevin Danois    5.939166    8.00
580                 Lucas Torro    5.926434    3.00
573             Carlo Boukhalfa    5.866540    2.00
507                   Gio Reyna    5.862395    7.00
544             Ngal'Ayel Mukau    5.851170   15.00
322                Sven Mijnans    5.753861    9.00
49                  Andy Irving    5.733998    4.00
404        Albert Sambi Lokonga    5.733027    8.00
43                Billy Gilmour    5.669204   20.00
110              Lewis Ferguson    5.629809   28.00
12             Demir Ege Tiknaz    5.617362    5.00
439              Andras Schafer    5.572436    5.00
478              Enric Llansana    5.534215    4.00
597             Bryan Cristante    5.519978    7.00
159               Medon Berisha    5.500605    1.50
14                Niklas Dorsch    5.445246    3.50
15                Martin Payero    5.442304    5.50
76             Nicolas Gonzalez    5.422077   40.00
8               Kacper Urbanski    5.415911    6.00
425              Tajon Buchanan    5.351035    6.00
615                      Wendel    5.314862   18.00
109          Lorenzo Pellegrini    5.311815    9.00
419          Soungoutou Magassa    5.302099   12.00
361           Maksim Glushenkov    5.276308   14.00
158                  Kike Perez    5.268446    2.80
214                Razvan Marin    5.237399    3.50
547                 Saul Niguez    5.232835    3.00
376          Carney Chukwuemeka    5.192888   18.00
434              Sean Longstaff    5.176313   20.00
471              Danilo Cataldi    5.115133    3.50
314           Balthazar Pierret    5.112848    1.70
460                Jordan James    5.023307    8.00
607             Cheick Doucoure    5.014979   25.00
77              Frenkie de Jong    5.013685   45.00
400           Mahamadou Diawara    4.974989    2.00
288            Pedro Chirivella    4.961854    5.00
455                Stije Resink    4.930457    4.00
209       Jose Luis Garcia Vaya    4.923988    9.00
218                 Suat Serdar    4.902567    4.50
46                Youssef Maleh    4.882734    3.20
153                Benat Prados    4.865680   18.00
445             Elvis Rexhbecaj    4.854076    3.50
588                 Emi Buendia    4.849110   15.00
56               Ivan Oleinikov    4.764933    1.40
367                Rani Khedira    4.719900    2.50
16                   Yvan Neyou    4.714885    3.00
527                     Hernani    4.668368    1.60
231               Morgan Sanson    4.654002    5.00
3                Ylber Ramadani    4.623736    1.80
622                Alfie Devine    4.612131    3.50
137              Alberto Grassi    4.582262    1.80
111                Pablo Ibanez    4.580457    2.00
420               Selim Amallah    4.575840    1.60
95                 Oscar Fraulo    4.526287    3.50
465              Mathis Amougou    4.491599   10.00
538              Emircan Gurluk    4.481047    0.60
193                   Ivan Ilic    4.458557   16.00
429           Mahamadou Doumbia    4.440637    9.00
63             Dogucan Haspolat    4.424860    5.00
140             Guido Rodriguez    4.406190   10.00
503               Ander Guevara    4.399951    3.50
298                 Bilal Nadir    4.363500    5.00
480             Piotr Zielinski    4.279960   10.00
456               Mats Pannewig    4.278610    1.00
610             Tanguy Ndombele    4.225178    7.00
225                  Jhon Solis    4.210906    2.50
534                 Nikola Moro    4.200205    4.50
13                Stefan Loncar    4.192378    1.50
606           Donny van de Beek    4.181763    5.00
7                Philipp Sander    4.169013    4.00
295                 Joel Fujita    4.157466    3.00
212                 Joan Jordan    4.120172    2.50
53                        Artur    4.112061    8.00
560           Christian Eriksen    4.087897    4.00
241                Luis Esteves    4.069069    1.00
600                  Olasagasti    4.068285    4.00
604                Nathan Rodes    4.061048    1.40
40                  Rob Schoofs    4.038966    2.20
67             Jordan Holsgrove    4.034666    3.50
524             Evert Linthorst    3.986461    2.50
371       Magnus Kofod Andersen    3.927387    1.00
521                 Tom Cairney    3.911008    1.50
196                  Pol Lozano    3.898154    5.00
37              Luca Mazzitelli    3.886234    1.50
185                 Jesse Bosch    3.884725    0.90
33               Moumi Ngamaleu    3.863989    4.00
528               Hong Hyunseok    3.860502    3.50
329             Samuele Vignato    3.838018    2.20
169                  Iker Munoz    3.837563    3.00
464                   Marc Roca    3.835524    6.00
282               Igor Dmitriev    3.827665    1.00
71                  Francis Abu    3.758115    1.80
392                  Pedro Diaz    3.749058    3.00
475                Taichi Fukui    3.712710    2.00
351              Benjamin Andre    3.690511    5.00
551                 Hugo Sotelo    3.672063    4.00
25                 Adem Zorgane    3.635717    6.00
93                   Max Balard    3.623947    1.50
267                 Ryotaro Ito    3.618040    2.50
388              Matvei Kisliak    3.600814    8.00
257                Matteo Prati    3.586060    6.00
562                Tomas Handel    3.558982   13.00
83             Benat Turrientes    3.543957   10.00
413             Leandre Kuavita    3.466287    1.50
190                Espen van Ee    3.444695    1.30
58                Daniel Parejo    3.422993    1.50
335             Daniel Braganca    3.403225   12.00
17                 Edu Exposito    3.327042    3.00
152                Oier Zarraga    3.287854    2.00
397                Danil Glebov    3.282877    8.00
303            Yassine Titraoui    3.282598    5.00
433               Jon Moncayola    3.281634    7.00
134               Miguel Menino    3.278470    1.00
238           Aleksa Djurasovic    3.271146    2.00
493        Leonardo Bittencourt    3.253204    1.50
154               Aster Vranckx    3.239971    7.00
336                 Isaac Price    3.236455    3.00
260             Djibril Soumare    3.231739    1.50
191               German Valera    3.178080    1.50
263              Niklas Schmidt    3.163315    1.80
22                 Rudy Matondo    3.154930    0.30
355          Ivan Jaime Pajuelo    3.154027    5.00
68              Santiago Garcia    3.147897    0.80
556                Joey Veerman    3.135327   25.00
395               Sergey Babkin    3.127694    1.80
254               Lucas Tousart    3.127312    2.50
99            Pierre Lees-Melou    3.126578    6.00
377            Raphael Onyedika    3.123409   20.00
613          Anouar Ait El Hadj    3.117068    3.00
202             Ismael Bennacer    3.088629   15.00
368            Carlos Benavidez    3.079568    1.20
155                  Ryan Fosso    3.076678    1.50
331                 Hamza Rafia    3.074621    1.40
546           Dave Van Den Berg    3.067203    2.00
250             Antoine Bernede    3.062403    2.50
27             Damian Rodriguez    3.061607    3.00
100           Jean-Eudes Aholou    3.059152    2.00
300              Haris Belkebla    3.029554    2.00
337             Florian Neuhaus    2.993726    3.50
150           Charles Vanhoutte    2.982829    6.00
458               Enzo Loiodice    2.971982    1.20
378               Matias Vecino    2.958425    2.00
608                Adam Lallana    2.954202    0.75
605              Oscar Valentin    2.929875    2.50
41          Nikolas Sattlberger    2.926433    3.50
490               Davy Klaassen    2.914377    3.50
90                Cheikh Niasse    2.911868    2.50
495              Amadou Haidara    2.895075   16.00
330              Quinten Timber    2.860025   30.00
572       Almoatasem Al Musrati    2.845098    8.00
73              Nikita Krivtsov    2.840493    4.00
45                      Adriano    2.834064    2.50
581            Siebe Schrijvers    2.830999    1.50
38                 Bryan Heynen    2.822590   11.00
157                Mohamed Kaba    2.821075    2.00
431               Dani Ceballos    2.810751   10.00
181         Baptiste Santamaria    2.803814    7.00
539         Lucas Gourna-Douath    2.783908    8.00
94                 Jose Campana    2.771064    0.90
422               Marcus Linday    2.759736    4.00
529         Christopher Martins    2.746918    6.00
519                        Koke    2.735145    8.00
117                 Enzo Le Fee    2.692627   18.00
436            Faisal Al Ghamdi    2.689626    1.50
360                Stanko Juric    2.682618    1.20
352                Nail Umyarov    2.652330    4.00
569            Michel Aebischer    2.647473    7.50
133           Kirill Shchetinin    2.637851    2.80
603             Daniel Bandeira    2.620920    2.50
578              Julian Niehues    2.585250    1.50
319                Rafael Bauza    2.551195    0.20
513                Bogdan Jocic    2.544320    0.80
124                 Mirko Topic    2.536809    5.00
595          Ruben Loftus-Cheek    2.536031   10.00
334                Andrei Ivlev    2.534079    0.40

In [43]:
comp_leftovers_test[comp_leftovers_test['Player'].str.contains('Barco')]

            Player  Value_pred  Value
94  Esequiel Barco   17.286348   14.0

<b>Модель 4</b>

In [47]:
X_train = X_train[['G+A', 'Ast.1', 'Gls.1', 'SoT/90', '90s', 'Fld', 'CrdY', 'SoT%', 'Age', 'Crs', 'Int', 'PK', 'Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Ast.1', 'Gls.1', 'SoT/90', '90s', 'Fld', 'CrdY', 'SoT%', 'Age', 'Crs', 'Int', 'PK', 'Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [53]:
coeffs_df

               coeff
league_GB1  0.586112
90s         0.437282
Age        -0.427508
league_IT1  0.395787
league_ES1  0.316072
league_L1   0.296574
league_FR1  0.254164
G+A         0.206722
Ast.1       0.180166
Fld         0.127575
CrdY       -0.123407
Gls.1       0.122197
league_NL1 -0.101650
league_RU1 -0.095751
SoT%        0.068801
Int         0.060608
Crs        -0.055499
SoT/90      0.053840
league_PO1 -0.045782
PK         -0.033152
Sh          0.031898

In [54]:
metrics

            MAE       RMSE      MAPE        R2
test   5.463742  13.214845  0.934374  0.613647
train  5.297484  10.887309  0.862377  0.481157

In [55]:
comp_leftovers_test

                       Player  Value_pred    Value
0                Sandi Lovric   10.792036    8.500
1              Danila Godiaev    0.907757    1.500
2     Inigo Ruiz de Galarreta    3.088624    3.000
3              Johnny Cardoso   13.764298   25.000
4                  Unai Lopez    4.232315    2.500
5          Florian Grillitsch    2.509089    2.000
6              Mahmoud Dahoud    3.048655    3.500
7               Teji Savanier    5.963070    2.500
8                Djaoui Cisse    5.725256    8.000
9               Dean Huiberts    0.871485    0.300
10            Khephren Thuram   21.288354   40.000
11                 Pape Gueye   11.894555   15.000
12      Thomas Van den Keybus    1.394457    0.800
13              Sandro Tonali   45.141476   60.000
14     Ibrahima Sory Bangoura    2.032721    8.000
15        Vladimir Moskvichev    0.482710    0.500
16               Lasse Schone    0.139323    0.075
17            Kalvin Phillips    5.197880   12.000
18         Morgan Gibbs-White   90.460931   50.000
19              Ilija Vukotic    2.441341    0.600
20               Issa Doumbia    6.121616    2.400
21        Eduardo Felicissimo    1.116416    3.000
22              Stefano Sensi    2.337801    1.000
23             Tommaso Pobega    6.318122    9.000
24          Fernando Costanza    1.972653    3.000
25               Ilaix Moriba   11.478311    6.000
26            Finn Ole Becker    3.963624    2.000
27                   Casemiro    5.271060   10.000
28                Kaishu Sano   14.754976   20.000
29         Matthias Braunoder    2.254922    1.400
30            Abdoulaye Toure    8.026934    3.000
31                David Simao    0.462172    0.100
32                Ondrej Duda    6.086798    3.500
33        Oussama Targhalline    4.035742    4.000
34               Daniil Utkin    1.919805    2.800
35              Edson Alvarez    8.046773   25.000
36             Magnus Knudsen    5.406636    2.500
37         Henrikh Mkhitaryan    3.843427    4.000
38                Anas Tahiri    0.767633    0.500
39           Maxence Caqueret    8.759909   16.000
40               Nadiem Amiri   16.858629   20.000
41            Yehor Yarmoliuk   12.409438   15.000
42             Atakan Karazor   13.752241   12.000
43              Jonatan Lucca    0.345624    0.200
44                  Thom Haye    0.833001    1.000
45              Karol Linetty    2.713672    1.800
46            Mathias Delorge    6.307535    9.000
47            Rodrigo Saravia    1.356963    1.500
48           Jordan Henderson    0.667638    2.500
49             Miralem Pjanic    0.459374    2.000
50               Bence Dardai   10.063141   12.000
51                Alan Varela    2.294888   32.000
52            Nick Fichtinger    0.992508    0.450
53          Vladislav Kamilov    1.027627    0.800
54                 Kevin Pina    2.032981    5.000
55                  Alex Kral    7.344817    6.000
56               Isaac Babadi    2.181333    3.000
57         Iaroslav Mikhailov    2.040071    0.800
58           Kirian Rodriguez    5.196270    1.000
59               Lewis Holtby    1.817524    0.500
60                 Tom Krauss    3.848958    4.000
61              Mario Pasalic    9.203278   10.000
62               Daniil Fomin    2.906126    8.000
63                 Arne Maier    3.009589    4.000
64            Benjami­n Garre    0.971670    6.000
65              Luka Gagnidze    2.350314    1.200
66              Lamine Camara   19.190055   22.000
67             Nabil Bentaleb    1.504126    6.000
68              Harrison Reed    3.826980    6.000
69          Alessandro Deiola    3.752169    1.600
70          James Ward-Prowse    7.677237    8.000
71              Ryan Christie   15.060144   10.000
72                Salih Ozcan    2.304806    4.000
73             Justin Devenny   18.787800    6.000
74              Kian Fitz-Jim    2.214830    5.000
75               Jonas Martin    0.934058    0.600
76              Roberto Lopez    3.002326    1.000
77         Dominik Szoboszlai   72.153647   80.000
78              Denis Zakaria   11.560366   30.000
79             Rassoul Ndiaye    4.087853    2.000
80           Lawrence Agyekum    4.365375    2.500
81               Ivan Komarov    2.353802    2.000
82                Andre Horta    2.214067    4.000
83            Jude Bellingham   85.261771  180.000
84                       Igor    1.150391    3.500
85        Kamiel Van De Perre    1.805548    3.000
86               Aleix Garcia    7.032552   20.000
87            Justin Kluivert   69.737132   35.000
88              Paulo Moreira    1.619834    0.400
89                 Mert Komur   11.028148    5.000
90            Florian Tardieu    3.758432    0.600
91               Louis Mouton    3.999889    0.700
92          William Smallbone    7.194909    6.000
93            Nikita Saltykov    1.029323    2.000
94             Esequiel Barco   13.209948   14.000
95              Ellyes Skhiri    4.985664    7.500
96            Morten Hjulmand    2.694256   50.000
97           Gustavo Mendonca    1.423942    0.400
98            Leandro Paredes    3.642135    5.000
99             Angelo Stiller   24.422166   45.000
100                      Alan    8.034184    4.000
101            Sherzod Esanov    0.821081    0.300
102             Gerard Gumbau    1.930156    1.500
103             Hugo Magnetti    5.051679    6.000
104            Vi­ctor Mendez    0.788870    1.800
105              Mario Martin    9.890463    1.500
106             Robert Wagner    2.728217    3.000
107              Can Bozdogan    1.165047    3.500
108               Vadim Rakov    2.391880    1.200
109              Remo Freuler    6.542625    5.000
110          Aljoscha Kemlein    5.538907    7.000
111                  Guus Til   18.297047   12.000
112            Yellu Santiago    2.261157    0.900
113           Kristijan Jakic    7.080250    6.500
114             Samuele Ricci   18.859495   30.000
115         Han-Noah Massengo    3.406650    5.000
116          Maksim Paliyenko    0.494295    0.350
117                      Neto    0.592429    0.200
118            Darko Brasanac    2.532749    0.500
119                   Douglas    9.191643    6.000
120            Viktor Okishor    5.454322    0.500
121            Liam Henderson    4.936469    2.000
122           Diego Rodrigues    2.721626    2.000
123             Jamal Musiala   62.898353  140.000
124            Santi Comesana    8.764936    8.000
125       Vladislav Masternoy    0.319395    0.600
126      Jean-Philippe Gbamin    1.005949    2.000
127            Tim van de Loo    2.513231    0.600
128     Branco van den Boomen    0.472850    3.500
129            Gjivai Zechiel    3.263123    4.000
130            Matteo Pessina    2.108227    6.000
131               Jakub Moder    1.835959   12.000
132           Daouda Weidmann    0.834484    0.300
133            Aimen Moueffek    3.509542    2.500
134               Ulvi Babaev    0.966217    0.250
135                   Keliano    1.271450    0.400
136              Roman Yezhov    1.224340    1.800
137               Angel Gomes    4.212233   20.000
138             Junior Mwanga    6.832315    6.000
139       Aleksandar Pavlovic    7.431859   55.000
140       Dmitrii Aleksandrov    0.826984    0.350
141           Boubacar Kamara   16.190160   40.000
142  Leandro Barreiro Martins    2.447005   15.000
143          Gustavo Assuncao    1.127056    1.000
144              Dario Essugo    8.388848   20.000
145               Lewis Miley   16.919437   22.000
146                Jean Gorby    1.667194    4.000
147             Yassin Oukili    5.319174    0.900
148           Arthur Piedfort    3.040905    2.000
149            Nampalys Mendy    1.128302    1.800
150              Matt O'Riley   18.000504   22.000
151           Marcel Sabitzer    2.811209    8.000
152           Tanner Tessmann    5.497359    6.000
153             Danil Prutsev    2.029209    4.000
154                Roman Kvet    3.210667    1.500
155          Marshall Munetsi   14.570439   15.000
156           Nicolai Remberg    7.363764    3.000
157             Joris Chotard    5.096216    6.000

In [56]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                         Player  Value_pred   Value
428             Bruno Guimaraes  121.280403   80.00
500              Enzo Fernandez   92.873187   75.00
386              James Maddison   78.434430   42.00
275             Bruno Fernandes   74.219080   50.00
525            Mateus Fernandes   66.532506   15.00
113                 Xavi Simons   66.168543   70.00
268            Ryan Gravenberch   65.459555   75.00
215             Scott McTominay   62.765315   50.00
115             Elliot Anderson   61.395997   32.00
167             Youri Tielemans   57.263853   38.00
232               Carlos Baleba   55.521887   40.00
120               Andrey Santos   54.420909   35.00
523         Alexis Mac Allister   49.694956  100.00
398             Martin Ødegaard   46.832179   85.00
60            Tijjani Reijnders   46.436025   60.00
498                  Sem Steijn   44.546102   16.00
629                 Declan Rice   43.820216  120.00
297                  Paul Nebel   41.373032   24.00
313                       Pedri   39.884845  140.00
385             Pape Matar Sarr   38.565652   32.00
451            Emile Smith Rowe   37.950476   30.00
59           Bilal El Khannouss   36.321697   28.00
26                   Joao Gomes   33.307782   40.00
207              Ismael Saibari   32.771266   27.00
399                  Aimar Oroz   31.486260   15.00
64                      Vitinha   31.316701   80.00
91           Christian Norgaard   31.053321   11.00
266                 Yasin Ayari   30.073358   22.00
246                Tomas Soucek   28.390005   18.00
103                Oihan Sancet   28.303982   60.00
180              Harvey Elliott   25.144784   30.00
559               Julian Brandt   24.444004   25.00
217         Hamed Junior Traore   24.200019   20.00
299                Amadou Onana   23.029759   50.00
586                   Manu Kone   21.527733   40.00
210               Romano Schmid   21.191100   17.00
10             Giuliano Simeone   20.942580   35.00
112               Mateo Kovacic   20.859562   20.00
497  Andre-Frank Zambo Anguissa   20.759350   27.00
357                  Jens Stage   20.466058   14.00
223                Lee Jae-sung   20.064098    2.50
163               Vitaly Janelt   19.944595   20.00
126     Hans Nicolussi Caviglia   19.837825    8.50
138                     Ederson   19.831221   50.00
224                       Andre   19.227995   28.00
97               Lucas Bergvall   19.111876   38.00
568               Wilfred Ndidi   18.827107   15.00
183      Valentin Atangana Edoa   18.773573   10.00
283                Hugo Larsson   18.674317   40.00
542               Javier Guerra   18.545250   25.00
508                  Simon Sohm   18.542206    5.00
520             Morten Frendrup   18.402427   20.00
472               Adrien Rabiot   17.986431   25.00
208                 Yacine Adli   17.809856   11.00
540                Jens Cajuste   17.809821   12.00
221            Matteo Guendouzi   17.589410   32.00
80                Kobbie Mainoo   17.361180   50.00
591               Pablo Barrios   17.088335   55.00
349       Manuel Ugarte Ribeiro   16.461357   45.00
253                Alieu Fadera   16.394947    4.50
557              Lucas Da Cunha   16.084149   10.00
382            Mikel Jauregizar   16.043390   30.00
570                 Tyler Adams   16.014576   18.00
62                   Ryan Yates   15.942112   12.00
164            Corentin Tolisso   15.823403   12.00
206                  Gustavo sa   15.815171   16.00
496              Nicolo Barella   15.648651   75.00
477               Jan Schoppner   15.260457    4.00
555              İlkay Gundogan   15.058724    5.00
510               Armin Gigovic   15.041231    3.00
293           Exequiel Palacios   14.849915   40.00
302              Jacopo Fazzini   14.800023   10.00
189                 Rocco Reitz   14.740068   15.00
364              Gianluca Busio   14.389580    6.00
98              Youssouf Fofana   14.363018   30.00
468                        Isco   13.957396    6.00
243           Alessandro Bianco   13.892364    5.00
432                  Alex Scott   13.668052   20.00
118                Hans Vanaken   13.514909    7.00
427             Hicham Boudaoui   13.402835   15.00
308              Yangel Herrera   13.117152   15.00
291              Nicolo Rovella   13.046629   30.00
39              Andreas Pereira   12.963572   18.00
127          Idrissa Gana Gueye   12.882870    1.50
446                Flynn Downes   12.838572   13.00
72                 Senny Mayulu   12.808986   15.00
353             Neil El Aynaoui   12.759055   15.00
79               Joshua Kimmich   12.566981   45.00
467          Abdoulaye Doucoure   12.525157    7.00
227         Pierre Ekwah Elimby   12.441317    7.00
339                      Bitelo   12.344662   12.00
565                  Samu Costa   12.171002   15.00
577                 Amine Harit   11.914449    8.00
452                 Mohamed Haj   11.861283    1.80
131            Eduard Spertsyan   11.845871   25.00
552                 Marc Casado   11.723506   30.00
411             Davide Frattesi   11.672080   35.00
259            Faustino Anjorin   11.641386    6.00
541             Mauro Arambarri   11.631632   12.00
421          Jurgen Ekkelenkamp   11.518101    7.00
304            Adrien Thomasson   11.489449    5.00
78              Conor Gallagher   11.465792   40.00
177              Seydouba Cisse   11.334757    3.00
84                 Granit Xhaka   11.320118   12.00
609             Gvidas Gineitis   11.306285    6.00
166             Johann Lepenant   11.050362    6.00
501                 Diego Gomez   11.037878   14.00
309            Martin Zubimendi   10.900647   60.00
6                  Felix Nmecha   10.778600   28.00
346             Pierre Hojbjerg   10.763452   20.00
248                  Andy Diouf   10.758312   15.00
406                 Romeo Lavia   10.573723   40.00
363                Sander Berge   10.548560   25.00
175           Boubakary Soumare   10.338777   12.00
106          Rolando Mandragora   10.336273   12.00
116                Frank Onyeka   10.319561    7.00
317           Marco Brescianini   10.303597    8.00
194            Enzo Barrenechea   10.254093   10.00
161                Orel Mangala   10.194758   18.00
290                  Sasa Lukic   10.192704   14.00
579                 Tommy Doyle    9.932864   10.00
50             Giovanni Fabbian    9.891213   12.00
2                   Orkun Kokcu    9.858485   30.00
344        Maximilian Eggestein    9.839839   10.00
417            Fabian Ruiz Pena    9.822106   40.00
354              Maximo Perrone    9.767994   12.00
405       Cristian Casseres Jr.    9.702216    6.00
430               Lucien Agoume    9.584830    8.00
390              Tim Iroegbunam    9.485182    9.00
102              Jackson Irvine    9.440221    2.00
453            Ezechiel Banzuzi    9.350872   13.00
284            Mario Stroeykens    9.300721   12.00
548              Reda Belahyane    9.296193   10.00
448            Manuel Locatelli    9.277550   30.00
149             Niccolo Pisilli    9.255465   13.00
598           Maximilian Arnold    9.250864    5.00
30           Michel Ndary Adopo    8.933580    4.00
135      Thorir Johann Helgason    8.769465    3.00
457           Rodrigo Bentancur    8.758131   30.00
616                Ross Barkley    8.718735    6.00
66                    Sam Morsy    8.709435    0.50
296                 Harry Winks    8.659467    9.00
461                 Joshua King    8.573467    1.00
315            Hakan Calhanoglu    8.567472   30.00
240                 Senne Lynen    8.464080    9.00
292                  Luka Sucic    8.413778   15.00
437                 Will Hughes    8.319782    7.00
358             Ibrahim Sangare    8.318510   24.00
54                Yves Bissouma    8.283967   25.00
132                 Mason Mount    8.283091   28.00
86              Rabby Nzingoula    8.281142    2.50
530              Cesare Casadei    8.261097   15.00
563       Christoph Baumgartner    8.222634   12.00
130              Ayyoub Bouaddi    8.214401   28.00
256              Sergi Altimira    8.085579   15.00
418              Adrian Bernabe    8.042166   15.00
219       Konstantinos Karetsas    8.033775   20.00
305           Lassana Coulibaly    8.008507    2.50
621                Warren Bondo    8.002462   10.00
416                 Lovro Majer    7.936518   17.00
165               Azor Matusiwa    7.876626    8.00
178                 Pablo Marin    7.874299    8.00
270                 Amadou Kone    7.857912    4.00
553                 Noah Sadiki    7.846733   12.00
589                  Matus Bero    7.813228    3.00
75              Lazar Samardzic    7.769102   17.00
57                 Julian Weigl    7.756284    6.00
512            Jesper Karlstrom    7.706266    4.00
44                 Fran Beltran    7.669343    8.00
279               Daichi Kamada    7.647033   12.00
20             Arthur Vermeeren    7.605175   22.00
19             Ibrahima Sissoko    7.551468    6.00
18             Kristjan Asllani    7.483271   13.00
96                 Elisha Owusu    7.443227    3.00
584              Nicolo Fagioli    7.323367   18.00
160              Antoni Milambo    7.183072   18.00
516                Daan Heymans    7.074959    3.00
151            Ibrahim Sulemana    6.975273    7.00
233             Patrizio Masini    6.949094    6.00
229                Oliver Skipp    6.943246   10.00
74                   Luis Milla    6.898558    3.50
24            Antoine Makoumbou    6.887902    3.50
499             Rodrigo De Paul    6.860952   25.00
482             Pedrinho Santos    6.859021   10.00
235              Antonio Blanco    6.793608   10.00
483                Brais Mendez    6.756019   22.00
265               Ardon Jashari    6.726583   32.00
192             Andrei Mostovoy    6.667603    4.00
281              Vincent Sierro    6.663037    4.00
85                 Toby Collyer    6.620473    5.00
511              Mathias Jensen    6.537455   14.00
522             Yassin Belkhdim    6.534478    1.00
628                 Djibril Sow    6.515257    7.50
262                 Ismael Kone    6.497162    9.00
443           Patrick Osterhage    6.470711   10.00
269              Chuky san jose    6.415751    1.50
459            Mattias Svanberg    6.382713   12.00
12             Demir Ege Tiknaz    6.254533    5.00
322                Sven Mijnans    6.229601    9.00
580                 Lucas Torro    6.178091    3.00
487             Amir Richardson    6.156399    8.50
61          Benjamin Bouchouari    6.144794    5.00
203                 Ivan Martin    6.085663    6.00
554                Kevin Zeroli    6.056147    4.00
478              Enric Llansana    5.992968    4.00
36                 Kevin Danois    5.983888    8.00
264              Kanya Fujimoto    5.981103    4.00
536                       Batxi    5.934321    5.00
507                   Gio Reyna    5.879850    7.00
481               Oscar Hojlund    5.866040    7.50
544             Ngal'Ayel Mukau    5.826353   15.00
21                Urko Gonzalez    5.799616    5.00
567           Stanislav Lobotka    5.720871   25.00
159               Medon Berisha    5.718409    1.50
438                Kevin Stoger    5.684352    3.50
15                Martin Payero    5.627205    5.50
573             Carlo Boukhalfa    5.620937    2.00
439              Andras Schafer    5.620130    5.00
49                  Andy Irving    5.618671    4.00
597             Bryan Cristante    5.604052    7.00
361           Maksim Glushenkov    5.597165   14.00
43                Billy Gilmour    5.596249   20.00
531       Brian De Keersmaecker    5.595663    3.00
547                 Saul Niguez    5.537259    3.00
404        Albert Sambi Lokonga    5.521496    8.00
419          Soungoutou Magassa    5.454898   12.00
8               Kacper Urbanski    5.426366    6.00
14                Niklas Dorsch    5.418184    3.50
425              Tajon Buchanan    5.404954    6.00
76             Nicolas Gonzalez    5.361620   40.00
471              Danilo Cataldi    5.356542    3.50
63             Dogucan Haspolat    5.331811    5.00
110              Lewis Ferguson    5.290781   28.00
158                  Kike Perez    5.284345    2.80
615                      Wendel    5.197967   18.00
607             Cheick Doucoure    5.186150   25.00
77              Frenkie de Jong    5.160908   45.00
376          Carney Chukwuemeka    5.144785   18.00
314           Balthazar Pierret    5.101077    1.70
400           Mahamadou Diawara    5.098665    2.00
434              Sean Longstaff    5.098239   20.00
109          Lorenzo Pellegrini    5.058014    9.00
455                Stije Resink    5.049582    4.00
153                Benat Prados    5.036058   18.00
460                Jordan James    5.028566    8.00
218                 Suat Serdar    4.916308    4.50
231               Morgan Sanson    4.868633    5.00
588                 Emi Buendia    4.845776   15.00
46                Youssef Maleh    4.839650    3.20
367                Rani Khedira    4.801641    2.50
56               Ivan Oleinikov    4.794103    1.40
445             Elvis Rexhbecaj    4.776598    3.50
622                Alfie Devine    4.774549    3.50
111                Pablo Ibanez    4.747764    2.00
95                 Oscar Fraulo    4.722242    3.50
3                Ylber Ramadani    4.699859    1.80
214                Razvan Marin    4.684722    3.50
137              Alberto Grassi    4.633414    1.80
288            Pedro Chirivella    4.598389    5.00
209       Jose Luis Garcia Vaya    4.570654    9.00
16                   Yvan Neyou    4.555863    3.00
538              Emircan Gurluk    4.495445    0.60
465              Mathis Amougou    4.466532   10.00
420               Selim Amallah    4.464887    1.60
193                   Ivan Ilic    4.450946   16.00
13                Stefan Loncar    4.437851    1.50
295                 Joel Fujita    4.411757    3.00
298                 Bilal Nadir    4.369825    5.00
140             Guido Rodriguez    4.319868   10.00
534                 Nikola Moro    4.286572    4.50
600                  Olasagasti    4.282812    4.00
67             Jordan Holsgrove    4.275820    3.50
40                  Rob Schoofs    4.275355    2.20
225                  Jhon Solis    4.272000    2.50
429           Mahamadou Doumbia    4.269658    9.00
7                Philipp Sander    4.268509    4.00
610             Tanguy Ndombele    4.218770    7.00
527                     Hernani    4.217386    1.60
503               Ander Guevara    4.180100    3.50
606           Donny van de Beek    4.180095    5.00
33               Moumi Ngamaleu    4.170258    4.00
456               Mats Pannewig    4.144151    1.00
604                Nathan Rodes    4.103832    1.40
371       Magnus Kofod Andersen    4.022160    1.00
464                   Marc Roca    4.019188    6.00
37              Luca Mazzitelli    3.979131    1.50
521                 Tom Cairney    3.957542    1.50
241                Luis Esteves    3.955041    1.00
480             Piotr Zielinski    3.941649   10.00
560           Christian Eriksen    3.915740    4.00
25                 Adem Zorgane    3.893136    6.00
392                  Pedro Diaz    3.888081    3.00
53                        Artur    3.885279    8.00
169                  Iker Munoz    3.871945    3.00
185                 Jesse Bosch    3.864166    0.90
329             Samuele Vignato    3.834134    2.20
528               Hong Hyunseok    3.812879    3.50
351              Benjamin Andre    3.809125    5.00
524             Evert Linthorst    3.788708    2.50
282               Igor Dmitriev    3.765737    1.00
196                  Pol Lozano    3.752796    5.00
475                Taichi Fukui    3.714060    2.00
212                 Joan Jordan    3.660735    2.50
257                Matteo Prati    3.643849    6.00
388              Matvei Kisliak    3.623093    8.00
71                  Francis Abu    3.618049    1.80
267                 Ryotaro Ito    3.614530    2.50
93                   Max Balard    3.601763    1.50
562                Tomas Handel    3.600999   13.00
303            Yassine Titraoui    3.584979    5.00
190                Espen van Ee    3.546612    1.30
17                 Edu Exposito    3.513793    3.00
83             Benat Turrientes    3.495657   10.00
551                 Hugo Sotelo    3.488403    4.00
335             Daniel Braganca    3.430523   12.00
397                Danil Glebov    3.403172    8.00
493        Leonardo Bittencourt    3.377875    1.50
395               Sergey Babkin    3.352201    1.80
413             Leandre Kuavita    3.277452    1.50
134               Miguel Menino    3.267420    1.00
58                Daniel Parejo    3.255023    1.50
152                Oier Zarraga    3.253054    2.00
150           Charles Vanhoutte    3.248799    6.00
100           Jean-Eudes Aholou    3.213046    2.00
154               Aster Vranckx    3.209600    7.00
191               German Valera    3.207792    1.50
336                 Isaac Price    3.191606    3.00
556                Joey Veerman    3.187160   25.00
613          Anouar Ait El Hadj    3.178787    3.00
368            Carlos Benavidez    3.168645    1.20
155                  Ryan Fosso    3.166350    1.50
238           Aleksa Djurasovic    3.161915    2.00
355          Ivan Jaime Pajuelo    3.159555    5.00
546           Dave Van Den Berg    3.159000    2.00
250             Antoine Bernede    3.144990    2.50
68              Santiago Garcia    3.141745    0.80
433               Jon Moncayola    3.141310    7.00
22                 Rudy Matondo    3.128163    0.30
263              Niklas Schmidt    3.114451    1.80
300              Haris Belkebla    3.109285    2.00
202             Ismael Bennacer    3.104646   15.00
38                 Bryan Heynen    3.102838   11.00
352                Nail Umyarov    3.097284    4.00
260             Djibril Soumare    3.096854    1.50
377            Raphael Onyedika    3.070912   20.00
254               Lucas Tousart    3.061563    2.50
99            Pierre Lees-Melou    3.053386    6.00
458               Enzo Loiodice    3.040645    1.20
90                Cheikh Niasse    3.037746    2.50
331                 Hamza Rafia    3.010952    1.40
27             Damian Rodriguez    3.001639    3.00
378               Matias Vecino    2.994486    2.00
73              Nikita Krivtsov    2.972395    4.00
181         Baptiste Santamaria    2.963928    7.00
337             Florian Neuhaus    2.962954    3.50
41          Nikolas Sattlberger    2.958349    3.50
608                Adam Lallana    2.931759    0.75
581            Siebe Schrijvers    2.919399    1.50
94                 Jose Campana    2.902638    0.90
572       Almoatasem Al Musrati    2.877886    8.00
495              Amadou Haidara    2.871421   16.00
605              Oscar Valentin    2.859475    2.50
157                Mohamed Kaba    2.852982    2.00
431               Dani Ceballos    2.842731   10.00
494              Omar Mascarell    2.813789    0.90
539         Lucas Gourna-Douath    2.802117    8.00
490               Davy Klaassen    2.799564    3.50
117                 Enzo Le Fee    2.769774   18.00
529         Christopher Martins    2.751084    6.00
422               Marcus Linday    2.747798    4.00
436            Faisal Al Ghamdi    2.739664    1.50
519                        Koke    2.729676    8.00
603             Daniel Bandeira    2.702833    2.50
569            Michel Aebischer    2.683620    7.50
360                Stanko Juric    2.658270    1.20
133           Kirill Shchetinin    2.605384    2.80
513                Bogdan Jocic    2.603556    0.80
124                 Mirko Topic    2.592248    5.00
330              Quinten Timber    2.592246   30.00
319                Rafael Bauza    2.572471    0.20
122               Manu Morlanes    2.556885    2.50
342           Mathias De Amorim    2.548408    1.50
578              Julian Niehues    2.532449    1.50

In [64]:
comp_leftovers_train[comp_leftovers_train['Player'].str.contains('Sperts')]

               Player  Value_pred  Value
131  Eduard Spertsyan   11.845871   25.0

<b>Модель 5</b>

In [68]:
X_train = X_train[['G+A', 'Gls.1', 'SoT/90', '90s', 'Fld', 'CrdY', 'SoT%', 'Age', 'Crs', 'Int', 'PK', 'Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Gls.1', 'SoT/90', '90s', 'Fld', 'CrdY', 'SoT%', 'Age', 'Crs', 'Int', 'PK', 'Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [74]:
coeffs_df

               coeff
league_GB1  0.578256
Age        -0.410501
G+A         0.408076
90s         0.393690
league_IT1  0.389110
league_ES1  0.306499
league_L1   0.279485
league_FR1  0.252628
Fld         0.129643
CrdY       -0.118318
SoT/90      0.113009
league_NL1 -0.106945
league_RU1 -0.101956
Int         0.071515
Gls.1       0.064324
PK         -0.060020
Sh         -0.053359
league_PO1 -0.051512
SoT%        0.046372
Crs        -0.035576

In [75]:
metrics

            MAE       RMSE      MAPE        R2
test   5.400191  12.703128  0.931033  0.642989
train  5.503649  11.288079  0.877465  0.442255

In [78]:
comp_leftovers_test.sort_values('Value_pred', ascending=False)

                       Player  Value_pred    Value
18         Morgan Gibbs-White  100.370672   50.000
83            Jude Bellingham   91.385108  180.000
123             Jamal Musiala   77.077862  140.000
87            Justin Kluivert   71.856399   35.000
77         Dominik Szoboszlai   70.933475   80.000
13              Sandro Tonali   47.551740   60.000
99             Angelo Stiller   24.043982   45.000
10            Khephren Thuram   21.247696   40.000
111                  Guus Til   20.320732   12.000
66              Lamine Camara   18.861745   22.000
114             Samuele Ricci   18.190458   30.000
40               Nadiem Amiri   17.826051   20.000
145               Lewis Miley   17.144304   22.000
73             Justin Devenny   17.047225    6.000
141           Boubacar Kamara   16.550741   40.000
150              Matt O'Riley   15.749977   22.000
155          Marshall Munetsi   15.700421   15.000
71              Ryan Christie   15.048634   10.000
3              Johnny Cardoso   14.503204   25.000
42             Atakan Karazor   13.690544   12.000
28                Kaishu Sano   13.135485   20.000
41            Yehor Yarmoliuk   12.493858   15.000
94             Esequiel Barco   12.241042   14.000
78              Denis Zakaria   11.974646   30.000
11                 Pape Gueye   11.845401   15.000
25               Ilaix Moriba   10.628963    6.000
0                Sandi Lovric   10.124420    8.500
89                 Mert Komur   10.066766    5.000
119                   Douglas    9.894870    6.000
105              Mario Martin    9.355960    1.500
50               Bence Dardai    9.309123   12.000
124            Santi Comesana    8.822161    8.000
39           Maxence Caqueret    8.503181   16.000
61              Mario Pasalic    8.481313   10.000
144              Dario Essugo    8.195707   20.000
35              Edson Alvarez    7.925064   25.000
92          William Smallbone    7.797793    6.000
100                      Alan    7.630610    4.000
70          James Ward-Prowse    7.621153    8.000
30            Abdoulaye Toure    7.331241    3.000
139       Aleksandar Pavlovic    7.244009   55.000
55                  Alex Kral    6.833948    6.000
109              Remo Freuler    6.581737    5.000
86               Aleix Garcia    6.573652   20.000
156           Nicolai Remberg    6.538494    3.000
113           Kristijan Jakic    6.482247    6.500
138             Junior Mwanga    6.397710    6.000
20               Issa Doumbia    6.360973    2.400
32                Ondrej Duda    6.263097    3.500
46            Mathias Delorge    6.174450    9.000
8                Djaoui Cisse    6.131621    8.000
23             Tommaso Pobega    6.042710    9.000
152           Tanner Tessmann    5.999746    6.000
7               Teji Savanier    5.769300    2.500
147             Yassin Oukili    5.664507    0.900
110          Aljoscha Kemlein    5.547286    7.000
17            Kalvin Phillips    5.512843   12.000
27                   Casemiro    5.464176   10.000
68              Harrison Reed    5.409227    6.000
157             Joris Chotard    5.167748    6.000
103             Hugo Magnetti    5.052015    6.000
36             Magnus Knudsen    4.964272    2.500
95              Ellyes Skhiri    4.881043    7.500
121            Liam Henderson    4.835942    2.000
58           Kirian Rodriguez    4.746769    1.000
4                  Unai Lopez    4.583880    2.500
79             Rassoul Ndiaye    4.403202    2.000
33        Oussama Targhalline    4.320153    4.000
120            Viktor Okishor    4.139924    0.500
137               Angel Gomes    4.016514   20.000
80           Lawrence Agyekum    4.003750    2.500
69          Alessandro Deiola    3.890710    1.600
60                 Tom Krauss    3.831735    4.000
91               Louis Mouton    3.781585    0.700
37         Henrikh Mkhitaryan    3.775785    4.000
115         Han-Noah Massengo    3.633977    5.000
98            Leandro Paredes    3.617874    5.000
26            Finn Ole Becker    3.518699    2.000
133            Aimen Moueffek    3.369777    2.500
154                Roman Kvet    3.327334    1.500
90            Florian Tardieu    3.325193    0.600
63                 Arne Maier    3.173642    4.000
62               Daniil Fomin    3.088660    8.000
148           Arthur Piedfort    2.944493    2.000
129            Gjivai Zechiel    2.890585    4.000
106             Robert Wagner    2.864307    3.000
45              Karol Linetty    2.818885    1.800
151           Marcel Sabitzer    2.817681    8.000
2     Inigo Ruiz de Galarreta    2.757627    3.000
19              Ilija Vukotic    2.668654    0.600
96            Morten Hjulmand    2.661977   50.000
5          Florian Grillitsch    2.618374    2.000
142  Leandro Barreiro Martins    2.607490   15.000
127            Tim van de Loo    2.556982    0.600
118            Darko Brasanac    2.518722    0.500
29         Matthias Braunoder    2.501267    1.400
65              Luka Gagnidze    2.479777    1.200
112            Yellu Santiago    2.477506    0.900
22              Stefano Sensi    2.466115    1.000
76              Roberto Lopez    2.448225    1.000
72                Salih Ozcan    2.415822    4.000
56               Isaac Babadi    2.406007    3.000
130            Matteo Pessina    2.326979    6.000
81               Ivan Komarov    2.308636    2.000
6              Mahmoud Dahoud    2.297048    3.500
51                Alan Varela    2.246141   32.000
74              Kian Fitz-Jim    2.227050    5.000
14     Ibrahima Sory Bangoura    2.127278    8.000
54                 Kevin Pina    2.125660    5.000
108               Vadim Rakov    1.999782    1.200
57         Iaroslav Mikhailov    1.991536    0.800
85        Kamiel Van De Perre    1.978160    3.000
102             Gerard Gumbau    1.905199    1.500
24          Fernando Costanza    1.860989    3.000
34               Daniil Utkin    1.844890    2.800
59               Lewis Holtby    1.833168    0.500
146                Jean Gorby    1.768970    4.000
88              Paulo Moreira    1.711223    0.400
67             Nabil Bentaleb    1.640514    6.000
131               Jakub Moder    1.640247   12.000
153             Danil Prutsev    1.522986    4.000
97           Gustavo Mendonca    1.486775    0.400
122           Diego Rodrigues    1.394357    2.000
47            Rodrigo Saravia    1.305964    1.500
12      Thomas Van den Keybus    1.298438    0.800
134               Ulvi Babaev    1.231877    0.250
135                   Keliano    1.222738    0.400
21        Eduardo Felicissimo    1.222662    3.000
84                       Igor    1.222240    3.500
93            Nikita Saltykov    1.183121    2.000
136              Roman Yezhov    1.173365    1.800
126      Jean-Philippe Gbamin    1.157752    2.000
143          Gustavo Assuncao    1.120033    1.000
149            Nampalys Mendy    1.088052    1.800
53          Vladislav Kamilov    1.081569    0.800
75               Jonas Martin    1.053637    0.600
52            Nick Fichtinger    1.042261    0.450
82                Andre Horta    1.036014    4.000
64            Benjami­n Garre    1.016195    6.000
1              Danila Godiaev    0.992744    1.500
9               Dean Huiberts    0.968178    0.300
107              Can Bozdogan    0.925020    3.500
101            Sherzod Esanov    0.909559    0.300
140       Dmitrii Aleksandrov    0.907235    0.350
132           Daouda Weidmann    0.884786    0.300
44                  Thom Haye    0.815614    1.000
38                Anas Tahiri    0.766723    0.500
104            Vi­ctor Mendez    0.730275    1.800
48           Jordan Henderson    0.677164    2.500
117                      Neto    0.634520    0.200
128     Branco van den Boomen    0.558826    3.500
116          Maksim Paliyenko    0.549366    0.350
15        Vladimir Moskvichev    0.538773    0.500
31                David Simao    0.524180    0.100
49             Miralem Pjanic    0.429432    2.000
43              Jonatan Lucca    0.402024    0.200
125       Vladislav Masternoy    0.367987    0.600
16               Lasse Schone    0.164086    0.075

In [77]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                         Player  Value_pred   Value
428             Bruno Guimaraes  131.394598   80.00
500              Enzo Fernandez  105.726864   75.00
386              James Maddison   89.343911   42.00
215             Scott McTominay   80.451181   50.00
113                 Xavi Simons   78.386215   70.00
275             Bruno Fernandes   73.449971   50.00
120               Andrey Santos   69.345831   35.00
498                  Sem Steijn   66.753475   16.00
525            Mateus Fernandes   64.496955   15.00
268            Ryan Gravenberch   62.020089   75.00
167             Youri Tielemans   60.632721   38.00
115             Elliot Anderson   58.860950   32.00
523         Alexis Mac Allister   55.342639  100.00
60            Tijjani Reijnders   54.563187   60.00
232               Carlos Baleba   53.099514   40.00
297                  Paul Nebel   52.137956   24.00
629                 Declan Rice   47.882353  120.00
313                       Pedri   43.041757  140.00
398             Martin Ødegaard   42.009340   85.00
451            Emile Smith Rowe   40.227155   30.00
385             Pape Matar Sarr   38.605480   32.00
103                Oihan Sancet   34.883553   60.00
91           Christian Norgaard   34.573442   11.00
59           Bilal El Khannouss   34.435194   28.00
246                Tomas Soucek   33.381731   18.00
26                   Joao Gomes   32.599728   40.00
64                      Vitinha   32.016530   80.00
207              Ismael Saibari   31.273766   27.00
399                  Aimar Oroz   31.136808   15.00
266                 Yasin Ayari   29.846096   22.00
217         Hamed Junior Traore   29.560689   20.00
299                Amadou Onana   24.781578   50.00
357                  Jens Stage   24.538133   14.00
559               Julian Brandt   23.724356   25.00
223                Lee Jae-sung   23.473999    2.50
472               Adrien Rabiot   23.234604   25.00
497  Andre-Frank Zambo Anguissa   23.008501   27.00
112               Mateo Kovacic   22.399399   20.00
210               Romano Schmid   21.181230   17.00
586                   Manu Kone   20.631704   40.00
138                     Ederson   20.351229   50.00
126     Hans Nicolussi Caviglia   20.095130    8.50
163               Vitaly Janelt   19.699490   20.00
10             Giuliano Simeone   19.239522   35.00
508                  Simon Sohm   18.803421    5.00
224                       Andre   18.794335   28.00
283                Hugo Larsson   18.322389   40.00
164            Corentin Tolisso   18.304446   12.00
97               Lucas Bergvall   18.303413   38.00
540                Jens Cajuste   17.771291   12.00
568               Wilfred Ndidi   17.597974   15.00
520             Morten Frendrup   17.388922   20.00
542               Javier Guerra   17.356346   25.00
183      Valentin Atangana Edoa   17.008279   10.00
80                Kobbie Mainoo   16.827815   50.00
221            Matteo Guendouzi   16.764464   32.00
557              Lucas Da Cunha   16.502029   10.00
118                Hans Vanaken   16.485482    7.00
206                  Gustavo sa   16.380706   16.00
382            Mikel Jauregizar   15.990705   30.00
510               Armin Gigovic   15.954439    3.00
349       Manuel Ugarte Ribeiro   15.893927   45.00
591               Pablo Barrios   15.771084   55.00
62                   Ryan Yates   15.736492   12.00
302              Jacopo Fazzini   15.455465   10.00
570                 Tyler Adams   15.192938   18.00
477               Jan Schoppner   15.152531    4.00
253                Alieu Fadera   15.083828    4.50
496              Nicolo Barella   15.080552   75.00
432                  Alex Scott   15.037966   20.00
189                 Rocco Reitz   14.562342   15.00
180              Harvey Elliott   14.475497   30.00
353             Neil El Aynaoui   14.460179   15.00
555              İlkay Gundogan   14.355518    5.00
208                 Yacine Adli   14.322830   11.00
308              Yangel Herrera   13.805501   15.00
79               Joshua Kimmich   13.660381   45.00
364              Gianluca Busio   13.511574    6.00
446                Flynn Downes   13.308535   13.00
427             Hicham Boudaoui   13.237727   15.00
243           Alessandro Bianco   13.145701    5.00
131            Eduard Spertsyan   12.936850   25.00
39              Andreas Pereira   12.860435   18.00
467          Abdoulaye Doucoure   12.712777    7.00
98              Youssouf Fofana   12.602888   30.00
541             Mauro Arambarri   12.464939   12.00
411             Davide Frattesi   12.282450   35.00
127          Idrissa Gana Gueye   12.215613    1.50
291              Nicolo Rovella   12.126435   30.00
227         Pierre Ekwah Elimby   12.015260    7.00
304            Adrien Thomasson   11.948166    5.00
501                 Diego Gomez   11.939124   14.00
609             Gvidas Gineitis   11.667092    6.00
421          Jurgen Ekkelenkamp   11.530454    7.00
84                 Granit Xhaka   11.328619   12.00
177              Seydouba Cisse   11.272548    3.00
166             Johann Lepenant   11.208210    6.00
6                  Felix Nmecha   11.142651   28.00
339                      Bitelo   11.086461   12.00
72                 Senny Mayulu   11.033581   15.00
468                        Isco   10.979921    6.00
565                  Samu Costa   10.931209   15.00
78              Conor Gallagher   10.891140   40.00
309            Martin Zubimendi   10.717989   60.00
161                Orel Mangala   10.712676   18.00
346             Pierre Hojbjerg   10.693284   20.00
552                 Marc Casado   10.671729   30.00
175           Boubakary Soumare   10.560358   12.00
363                Sander Berge   10.476626   25.00
2                   Orkun Kokcu   10.362542   30.00
106          Rolando Mandragora   10.292062   12.00
405       Cristian Casseres Jr.   10.255204    6.00
293           Exequiel Palacios   10.209213   40.00
406                 Romeo Lavia   10.129515   40.00
259            Faustino Anjorin   10.081824    6.00
598           Maximilian Arnold   10.060069    5.00
290                  Sasa Lukic   10.004343   14.00
194            Enzo Barrenechea    9.973487   10.00
132                 Mason Mount    9.860188   28.00
317           Marco Brescianini    9.816104    8.00
50             Giovanni Fabbian    9.631534   12.00
417            Fabian Ruiz Pena    9.498145   40.00
248                  Andy Diouf    9.456705   15.00
430               Lucien Agoume    9.443846    8.00
457           Rodrigo Bentancur    9.355650   30.00
116                Frank Onyeka    9.353068    7.00
461                 Joshua King    9.221828    1.00
149             Niccolo Pisilli    9.104807   13.00
344        Maximilian Eggestein    9.013006   10.00
54                Yves Bissouma    8.995256   25.00
354              Maximo Perrone    8.986559   12.00
66                    Sam Morsy    8.979597    0.50
448            Manuel Locatelli    8.927154   30.00
589                  Matus Bero    8.879070    3.00
579                 Tommy Doyle    8.693906   10.00
548              Reda Belahyane    8.686118   10.00
30           Michel Ndary Adopo    8.594175    4.00
86              Rabby Nzingoula    8.579880    2.50
390              Tim Iroegbunam    8.399007    9.00
284            Mario Stroeykens    8.303963   12.00
616                Ross Barkley    8.272573    6.00
453            Ezechiel Banzuzi    8.261526   13.00
296                 Harry Winks    8.227755    9.00
305           Lassana Coulibaly    8.064272    2.50
102              Jackson Irvine    8.036062    2.00
270                 Amadou Kone    8.031586    4.00
530              Cesare Casadei    8.030936   15.00
75              Lazar Samardzic    7.984084   17.00
165               Azor Matusiwa    7.976793    8.00
437                 Will Hughes    7.963068    7.00
130              Ayyoub Bouaddi    7.810277   28.00
315            Hakan Calhanoglu    7.799166   30.00
563       Christoph Baumgartner    7.791339   12.00
621                Warren Bondo    7.755406   10.00
240                 Senne Lynen    7.693307    9.00
512            Jesper Karlstrom    7.688581    4.00
452                 Mohamed Haj    7.688355    1.80
279               Daichi Kamada    7.678443   12.00
418              Adrian Bernabe    7.669441   15.00
96                 Elisha Owusu    7.601493    3.00
292                  Luka Sucic    7.517314   15.00
553                 Noah Sadiki    7.480077   12.00
44                 Fran Beltran    7.471554    8.00
19             Ibrahima Sissoko    7.410690    6.00
233             Patrizio Masini    7.408014    6.00
256              Sergi Altimira    7.397223   15.00
229                Oliver Skipp    7.297731   10.00
85                 Toby Collyer    7.273870    5.00
57                 Julian Weigl    7.192629    6.00
499             Rodrigo De Paul    7.127339   25.00
219       Konstantinos Karetsas    7.105326   20.00
178                 Pablo Marin    7.077314    8.00
135      Thorir Johann Helgason    7.076005    3.00
49                  Andy Irving    7.065229    4.00
269              Chuky san jose    7.059431    1.50
358             Ibrahim Sangare    6.973688   24.00
361           Maksim Glushenkov    6.965060   14.00
20             Arthur Vermeeren    6.958135   22.00
281              Vincent Sierro    6.911248    4.00
584              Nicolo Fagioli    6.868702   18.00
74                   Luis Milla    6.831995    3.50
12             Demir Ege Tiknaz    6.809165    5.00
483                Brais Mendez    6.801130   22.00
482             Pedrinho Santos    6.796082   10.00
151            Ibrahim Sulemana    6.783851    7.00
192             Andrei Mostovoy    6.752186    4.00
628                 Djibril Sow    6.639135    7.50
24            Antoine Makoumbou    6.627942    3.50
522             Yassin Belkhdim    6.613705    1.00
459            Mattias Svanberg    6.548372   12.00
322                Sven Mijnans    6.480256    9.00
160              Antoni Milambo    6.402417   18.00
516                Daan Heymans    6.371352    3.00
18             Kristjan Asllani    6.333605   13.00
63             Dogucan Haspolat    6.328453    5.00
262                 Ismael Kone    6.314198    9.00
235              Antonio Blanco    6.300690   10.00
61          Benjamin Bouchouari    6.299474    5.00
580                 Lucas Torro    6.265643    3.00
536                       Batxi    6.254555    5.00
265               Ardon Jashari    6.185236   32.00
443           Patrick Osterhage    6.090627   10.00
487             Amir Richardson    6.079224    8.50
203                 Ivan Martin    6.078310    6.00
478              Enric Llansana    6.015933    4.00
471              Danilo Cataldi    6.005914    3.50
36                 Kevin Danois    5.967996    8.00
481               Oscar Hojlund    5.900488    7.50
597             Bryan Cristante    5.893204    7.00
264              Kanya Fujimoto    5.884164    4.00
76             Nicolas Gonzalez    5.786454   40.00
567           Stanislav Lobotka    5.776851   25.00
511              Mathias Jensen    5.727312   14.00
8               Kacper Urbanski    5.726053    6.00
577                 Amine Harit    5.722986    8.00
158                  Kike Perez    5.655504    2.80
544             Ngal'Ayel Mukau    5.593504   15.00
607             Cheick Doucoure    5.582660   25.00
507                   Gio Reyna    5.580793    7.00
573             Carlo Boukhalfa    5.542743    2.00
531       Brian De Keersmaecker    5.499122    3.00
439              Andras Schafer    5.481646    5.00
434              Sean Longstaff    5.454787   20.00
416                 Lovro Majer    5.454218   17.00
43                Billy Gilmour    5.424240   20.00
159               Medon Berisha    5.367018    1.50
438                Kevin Stoger    5.363306    3.50
15                Martin Payero    5.344339    5.50
419          Soungoutou Magassa    5.320917   12.00
455                Stije Resink    5.318364    4.00
314           Balthazar Pierret    5.296832    1.70
14                Niklas Dorsch    5.266667    3.50
21                Urko Gonzalez    5.233593    5.00
376          Carney Chukwuemeka    5.214055   18.00
153                Benat Prados    5.141508   18.00
404        Albert Sambi Lokonga    5.083015    8.00
588                 Emi Buendia    5.029983   15.00
56               Ivan Oleinikov    4.962071    1.40
110              Lewis Ferguson    4.953382   28.00
554                Kevin Zeroli    4.892719    4.00
622                Alfie Devine    4.891908    3.50
298                 Bilal Nadir    4.864128    5.00
137              Alberto Grassi    4.847402    1.80
460                Jordan James    4.836523    8.00
218                 Suat Serdar    4.835282    4.50
231               Morgan Sanson    4.835072    5.00
367                Rani Khedira    4.829901    2.50
193                   Ivan Ilic    4.827742   16.00
456               Mats Pannewig    4.814270    1.00
109          Lorenzo Pellegrini    4.809065    9.00
77              Frenkie de Jong    4.806616   45.00
13                Stefan Loncar    4.757149    1.50
3                Ylber Ramadani    4.728131    1.80
465              Mathis Amougou    4.697215   10.00
46                Youssef Maleh    4.677809    3.20
95                 Oscar Fraulo    4.662010    3.50
111                Pablo Ibanez    4.655773    2.00
16                   Yvan Neyou    4.613628    3.00
400           Mahamadou Diawara    4.594536    2.00
288            Pedro Chirivella    4.572685    5.00
445             Elvis Rexhbecaj    4.548374    3.50
521                 Tom Cairney    4.499526    1.50
209       Jose Luis Garcia Vaya    4.484304    9.00
420               Selim Amallah    4.481623    1.60
214                Razvan Marin    4.476664    3.50
225                  Jhon Solis    4.445979    2.50
7                Philipp Sander    4.370588    4.00
140             Guido Rodriguez    4.307399   10.00
547                 Saul Niguez    4.284784    3.00
185                 Jesse Bosch    4.256983    0.90
604                Nathan Rodes    4.242374    1.40
40                  Rob Schoofs    4.236244    2.20
67             Jordan Holsgrove    4.235078    3.50
295                 Joel Fujita    4.210451    3.00
392                  Pedro Diaz    4.153034    3.00
329             Samuele Vignato    4.139981    2.20
615                      Wendel    4.134990   18.00
25                 Adem Zorgane    4.114237    6.00
33               Moumi Ngamaleu    4.081652    4.00
191               German Valera    4.031772    1.50
606           Donny van de Beek    4.030829    5.00
503               Ander Guevara    3.997351    3.50
600                  Olasagasti    3.990156    4.00
610             Tanguy Ndombele    3.978505    7.00
538              Emircan Gurluk    3.930755    0.60
534                 Nikola Moro    3.929691    4.50
257                Matteo Prati    3.918695    6.00
351              Benjamin Andre    3.918457    5.00
524             Evert Linthorst    3.913274    2.50
429           Mahamadou Doumbia    3.897632    9.00
425              Tajon Buchanan    3.786079    6.00
371       Magnus Kofod Andersen    3.764366    1.00
196                  Pol Lozano    3.703703    5.00
551                 Hugo Sotelo    3.701136    4.00
562                Tomas Handel    3.680395   13.00
83             Benat Turrientes    3.667816   10.00
527                     Hernani    3.644396    1.60
93                   Max Balard    3.636829    1.50
212                 Joan Jordan    3.623981    2.50
464                   Marc Roca    3.603466    6.00
560           Christian Eriksen    3.585469    4.00
152                Oier Zarraga    3.502964    2.00
475                Taichi Fukui    3.495879    2.00
388              Matvei Kisliak    3.495362    8.00
22                 Rudy Matondo    3.486593    0.30
528               Hong Hyunseok    3.473539    3.50
58                Daniel Parejo    3.465671    1.50
150           Charles Vanhoutte    3.431005    6.00
267                 Ryotaro Ito    3.428518    2.50
480             Piotr Zielinski    3.409727   10.00
154               Aster Vranckx    3.407091    7.00
100           Jean-Eudes Aholou    3.403320    2.00
73              Nikita Krivtsov    3.402083    4.00
490               Davy Klaassen    3.396485    3.50
250             Antoine Bernede    3.389985    2.50
134               Miguel Menino    3.378708    1.00
493        Leonardo Bittencourt    3.371319    1.50
282               Igor Dmitriev    3.353008    1.00
352                Nail Umyarov    3.344687    4.00
300              Haris Belkebla    3.337601    2.00
169                  Iker Munoz    3.329572    3.00
458               Enzo Loiodice    3.308005    1.20
17                 Edu Exposito    3.288182    3.00
90                Cheikh Niasse    3.275445    2.50
397                Danil Glebov    3.267439    8.00
68              Santiago Garcia    3.265039    0.80
413             Leandre Kuavita    3.259552    1.50
303            Yassine Titraoui    3.259013    5.00
395               Sergey Babkin    3.239029    1.80
190                Espen van Ee    3.232791    1.30
331                 Hamza Rafia    3.222035    1.40
27             Damian Rodriguez    3.206269    3.00
117                 Enzo Le Fee    3.186015   18.00
433               Jon Moncayola    3.164229    7.00
546           Dave Van Den Berg    3.145700    2.00
37              Luca Mazzitelli    3.140618    1.50
613          Anouar Ait El Hadj    3.132679    3.00
99            Pierre Lees-Melou    3.130699    6.00
241                Luis Esteves    3.109101    1.00
157                Mohamed Kaba    3.099169    2.00
71                  Francis Abu    3.093782    1.80
336                 Isaac Price    3.089313    3.00
539         Lucas Gourna-Douath    3.066026    8.00
155                  Ryan Fosso    3.026233    1.50
494              Omar Mascarell    3.024035    0.90
569            Michel Aebischer    3.014493    7.50
238           Aleksa Djurasovic    2.987242    2.00
431               Dani Ceballos    2.979585   10.00
260             Djibril Soumare    2.968656    1.50
605              Oscar Valentin    2.956171    2.50
181         Baptiste Santamaria    2.951292    7.00
603             Daniel Bandeira    2.936179    2.50
377            Raphael Onyedika    2.918860   20.00
556                Joey Veerman    2.908360   25.00
41          Nikolas Sattlberger    2.899908    3.50
188               Franco Orozco    2.887807    1.50
38                 Bryan Heynen    2.867227   11.00
202             Ismael Bennacer    2.839265   15.00
466              Philip Billing    2.838620   10.00
327               Yannik Keitel    2.828027    3.50
578              Julian Niehues    2.818186    1.50
519                        Koke    2.805525    8.00
254               Lucas Tousart    2.797926    2.50
330              Quinten Timber    2.786959   30.00
319                Rafael Bauza    2.772489    0.20
335             Daniel Braganca    2.753862   12.00
355          Ivan Jaime Pajuelo    2.752454    5.00
368            Carlos Benavidez    2.732491    1.20
360                Stanko Juric    2.703123    1.20
408             Gabriel Vidovic    2.665634    3.00
495              Amadou Haidara    2.652936   16.00
469             Florentino Luis    2.643565   22.00
122               Manu Morlanes    2.643102    2.50
48             Patrik Hrosovsky    2.612512    2.70
574        Zinedine Ould Khaled    2.609136    0.40
595          Ruben Loftus-Cheek    2.607238   10.00
372                Daniel Penha    2.607067    0.75
422               Marcus Linday    2.606436    4.00
9               Jordan Veretout    2.587667    4.00
278                    Jorginho    2.587315    6.00
436            Faisal Al Ghamdi    2.581894    1.50
620                Jose Gragera    2.570207    2.00
104                   Victor Sa    2.566943    3.00

<b>Модель 6</b>

In [82]:
X_train = X_train[['G+A', 'Gls.1', 'SoT/90', 'Fld', 'CrdY', 'SoT%', 'Age', 'Crs', 'Int', 'PK', 'Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Gls.1', 'SoT/90', 'Fld', 'CrdY', 'SoT%', 'Age', 'Crs', 'Int', 'PK', 'Sh', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [88]:
coeffs_df

               coeff
league_GB1  0.626875
league_IT1  0.459380
G+A         0.452417
Age        -0.399405
league_ES1  0.363291
league_L1   0.324627
league_FR1  0.293720
Int         0.224991
Fld         0.187842
Sh          0.125448
SoT%        0.102662
PK         -0.083223
CrdY       -0.076664
league_RU1 -0.061731
Gls.1       0.054214
league_NL1 -0.053452
Crs        -0.013332
league_PO1 -0.013070
SoT/90      0.002743

In [89]:
metrics

            MAE       RMSE      MAPE        R2
test   5.254602  11.755020  0.926606  0.694292
train  5.806443  12.176112  0.903290  0.351048

In [90]:
comp_leftovers_test.sort_values('Value_pred', ascending=False)

                       Player  Value_pred    Value
83            Jude Bellingham  123.442940  180.000
18         Morgan Gibbs-White  117.019452   50.000
123             Jamal Musiala   87.428753  140.000
77         Dominik Szoboszlai   70.036507   80.000
87            Justin Kluivert   66.602577   35.000
13              Sandro Tonali   47.853692   60.000
66              Lamine Camara   24.302528   22.000
40               Nadiem Amiri   21.855721   20.000
99             Angelo Stiller   20.553283   45.000
111                  Guus Til   20.345750   12.000
145               Lewis Miley   18.054787   22.000
10            Khephren Thuram   17.994078   40.000
71              Ryan Christie   17.803755   10.000
3              Johnny Cardoso   17.259208   25.000
150              Matt O'Riley   16.901295   22.000
114             Samuele Ricci   15.863760   30.000
73             Justin Devenny   15.077443    6.000
155          Marshall Munetsi   15.034030   15.000
11                 Pape Gueye   14.935761   15.000
94             Esequiel Barco   14.586954   14.000
141           Boubacar Kamara   14.152315   40.000
42             Atakan Karazor   13.509253   12.000
78              Denis Zakaria   12.662437   30.000
0                Sandi Lovric   11.758912    8.500
28                Kaishu Sano   11.569228   20.000
41            Yehor Yarmoliuk   11.118542   15.000
119                   Douglas   10.837044    6.000
144              Dario Essugo   10.630608   20.000
25               Ilaix Moriba   10.442051    6.000
105              Mario Martin   10.417735    1.500
89                 Mert Komur    9.409534    5.000
50               Bence Dardai    8.166430   12.000
61              Mario Pasalic    8.135771   10.000
39           Maxence Caqueret    8.077760   16.000
124            Santi Comesana    7.921704    8.000
92          William Smallbone    7.603897    6.000
32                Ondrej Duda    7.468041    3.500
70          James Ward-Prowse    7.333136    8.000
23             Tommaso Pobega    7.118048    9.000
35              Edson Alvarez    7.079434   25.000
30            Abdoulaye Toure    6.761249    3.000
86               Aleix Garcia    6.644237   20.000
20               Issa Doumbia    6.420090    2.400
156           Nicolai Remberg    6.339940    3.000
147             Yassin Oukili    6.227326    0.900
8                Djaoui Cisse    6.147462    8.000
152           Tanner Tessmann    6.096451    6.000
17            Kalvin Phillips    6.091739   12.000
7               Teji Savanier    6.031492    2.500
27                   Casemiro    5.827683   10.000
138             Junior Mwanga    5.756366    6.000
139       Aleksandar Pavlovic    5.669784   55.000
100                      Alan    5.604235    4.000
46            Mathias Delorge    5.407101    9.000
113           Kristijan Jakic    5.307382    6.500
110          Aljoscha Kemlein    5.300860    7.000
4                  Unai Lopez    5.129391    2.500
68              Harrison Reed    4.631794    6.000
109              Remo Freuler    4.473158    5.000
79             Rassoul Ndiaye    4.436087    2.000
55                  Alex Kral    4.431685    6.000
80           Lawrence Agyekum    4.401202    2.500
95              Ellyes Skhiri    4.302371    7.500
157             Joris Chotard    4.280837    6.000
121            Liam Henderson    4.211047    2.000
115         Han-Noah Massengo    4.159276    5.000
98            Leandro Paredes    4.026047    5.000
33        Oussama Targhalline    4.019895    4.000
69          Alessandro Deiola    3.993441    1.600
58           Kirian Rodriguez    3.963376    1.000
26            Finn Ole Becker    3.938647    2.000
91               Louis Mouton    3.895629    0.700
154                Roman Kvet    3.836407    1.500
60                 Tom Krauss    3.772192    4.000
137               Angel Gomes    3.765271   20.000
36             Magnus Knudsen    3.752938    2.500
103             Hugo Magnetti    3.567897    6.000
90            Florian Tardieu    3.431719    0.600
129            Gjivai Zechiel    3.428474    4.000
62               Daniil Fomin    3.061561    8.000
63                 Arne Maier    3.056127    4.000
133            Aimen Moueffek    2.998586    2.500
106             Robert Wagner    2.936553    3.000
29         Matthias Braunoder    2.930700    1.400
81               Ivan Komarov    2.908240    2.000
37         Henrikh Mkhitaryan    2.879237    4.000
120            Viktor Okishor    2.785161    0.500
72                Salih Ozcan    2.744288    4.000
112            Yellu Santiago    2.741968    0.900
2     Inigo Ruiz de Galarreta    2.692483    3.000
142  Leandro Barreiro Martins    2.636647   15.000
5          Florian Grillitsch    2.621283    2.000
76              Roberto Lopez    2.602228    1.000
45              Karol Linetty    2.593155    1.800
85        Kamiel Van De Perre    2.580444    3.000
96            Morten Hjulmand    2.579337   50.000
22              Stefano Sensi    2.540259    1.000
19              Ilija Vukotic    2.517541    0.600
6              Mahmoud Dahoud    2.437664    3.500
148           Arthur Piedfort    2.431513    2.000
130            Matteo Pessina    2.406510    6.000
127            Tim van de Loo    2.361848    0.600
151           Marcel Sabitzer    2.360990    8.000
118            Darko Brasanac    2.321846    0.500
74              Kian Fitz-Jim    2.190532    5.000
24          Fernando Costanza    2.122025    3.000
14     Ibrahima Sory Bangoura    2.063689    8.000
56               Isaac Babadi    2.055299    3.000
102             Gerard Gumbau    2.022128    1.500
65              Luka Gagnidze    1.981825    1.200
54                 Kevin Pina    1.954804    5.000
59               Lewis Holtby    1.934169    0.500
34               Daniil Utkin    1.923959    2.800
108               Vadim Rakov    1.923827    1.200
57         Iaroslav Mikhailov    1.906184    0.800
146                Jean Gorby    1.884039    4.000
51                Alan Varela    1.862310   32.000
67             Nabil Bentaleb    1.761035    6.000
97           Gustavo Mendonca    1.675274    0.400
88              Paulo Moreira    1.673700    0.400
131               Jakub Moder    1.598177   12.000
12      Thomas Van den Keybus    1.540630    0.800
153             Danil Prutsev    1.467608    4.000
122           Diego Rodrigues    1.374485    2.000
21        Eduardo Felicissimo    1.338750    3.000
84                       Igor    1.326071    3.500
135                   Keliano    1.319508    0.400
126      Jean-Philippe Gbamin    1.286215    2.000
93            Nikita Saltykov    1.254959    2.000
75               Jonas Martin    1.240784    0.600
149            Nampalys Mendy    1.216232    1.800
53          Vladislav Kamilov    1.204803    0.800
47            Rodrigo Saravia    1.170273    1.500
82                Andre Horta    1.112022    4.000
64            Benjami­n Garre    1.102419    6.000
52            Nick Fichtinger    1.083075    0.450
107              Can Bozdogan    1.057454    3.500
136              Roman Yezhov    1.039458    1.800
44                  Thom Haye    1.038845    1.000
143          Gustavo Assuncao    1.032583    1.000
134               Ulvi Babaev    1.031907    0.250
101            Sherzod Esanov    1.017538    0.300
140       Dmitrii Aleksandrov    1.008793    0.350
9               Dean Huiberts    1.004367    0.300
1              Danila Godiaev    0.968253    1.500
132           Daouda Weidmann    0.946220    0.300
104            Vi­ctor Mendez    0.705155    1.800
117                      Neto    0.646196    0.200
48           Jordan Henderson    0.640761    2.500
116          Maksim Paliyenko    0.576084    0.350
15        Vladimir Moskvichev    0.566430    0.500
128     Branco van den Boomen    0.539501    3.500
49             Miralem Pjanic    0.524937    2.000
31                David Simao    0.524270    0.100
38                Anas Tahiri    0.523018    0.500
43              Jonatan Lucca    0.427643    0.200
125       Vladislav Masternoy    0.385578    0.600
16               Lasse Schone    0.211668    0.075

In [91]:
comp_leftovers_train.sort_values('Value_pred', ascending=False)

                         Player  Value_pred   Value
428             Bruno Guimaraes  139.582200   80.00
386              James Maddison  115.575742   42.00
275             Bruno Fernandes  105.349084   50.00
500              Enzo Fernandez  100.791502   75.00
215             Scott McTominay   96.241846   50.00
113                 Xavi Simons   91.857385   70.00
120               Andrey Santos   75.552536   35.00
232               Carlos Baleba   68.561828   40.00
115             Elliot Anderson   67.098066   32.00
60            Tijjani Reijnders   63.581583   60.00
525            Mateus Fernandes   61.717553   15.00
498                  Sem Steijn   60.465189   16.00
268            Ryan Gravenberch   56.787178   75.00
167             Youri Tielemans   53.583654   38.00
523         Alexis Mac Allister   53.517392  100.00
297                  Paul Nebel   52.948130   24.00
629                 Declan Rice   48.065500  120.00
385             Pape Matar Sarr   44.103156   32.00
207              Ismael Saibari   40.555528   27.00
91           Christian Norgaard   38.647283   11.00
398             Martin Ødegaard   36.027274   85.00
313                       Pedri   35.471566  140.00
451            Emile Smith Rowe   34.926185   30.00
246                Tomas Soucek   33.818212   18.00
103                Oihan Sancet   31.883184   60.00
217         Hamed Junior Traore   31.480899   20.00
399                  Aimar Oroz   28.989516   15.00
357                  Jens Stage   28.495893   14.00
266                 Yasin Ayari   28.245337   22.00
26                   Joao Gomes   27.187960   40.00
299                Amadou Onana   26.718441   50.00
223                Lee Jae-sung   26.286979    2.50
59           Bilal El Khannouss   25.213966   28.00
64                      Vitinha   24.325080   80.00
112               Mateo Kovacic   23.830153   20.00
497  Andre-Frank Zambo Anguissa   23.827339   27.00
586                   Manu Kone   22.410780   40.00
472               Adrien Rabiot   22.173461   25.00
559               Julian Brandt   21.586654   25.00
189                 Rocco Reitz   21.072180   15.00
126     Hans Nicolussi Caviglia   20.875568    8.50
164            Corentin Tolisso   20.442007   12.00
138                     Ederson   19.808931   50.00
97               Lucas Bergvall   19.774806   38.00
62                   Ryan Yates   19.679744   12.00
10             Giuliano Simeone   19.104646   35.00
308              Yangel Herrera   18.839111   15.00
349       Manuel Ugarte Ribeiro   18.425317   45.00
210               Romano Schmid   17.236789   17.00
253                Alieu Fadera   16.789055    4.50
477               Jan Schoppner   16.531519    4.00
542               Javier Guerra   16.489891   25.00
353             Neil El Aynaoui   16.280123   15.00
432                  Alex Scott   16.136615   20.00
568               Wilfred Ndidi   15.978828   15.00
510               Armin Gigovic   15.977587    3.00
206                  Gustavo sa   15.945257   16.00
163               Vitaly Janelt   15.655936   20.00
591               Pablo Barrios   15.555842   55.00
302              Jacopo Fazzini   15.532638   10.00
80                Kobbie Mainoo   15.391710   50.00
208                 Yacine Adli   15.329213   11.00
540                Jens Cajuste   15.248169   12.00
183      Valentin Atangana Edoa   15.122822   10.00
224                       Andre   15.021480   28.00
382            Mikel Jauregizar   15.007399   30.00
118                Hans Vanaken   14.606371    7.00
520             Morten Frendrup   14.525133   20.00
283                Hugo Larsson   14.326002   40.00
570                 Tyler Adams   14.309754   18.00
609             Gvidas Gineitis   14.046856    6.00
496              Nicolo Barella   13.992438   75.00
508                  Simon Sohm   13.985437    5.00
339                      Bitelo   13.875693   12.00
180              Harvey Elliott   13.857209   30.00
39              Andreas Pereira   13.635917   18.00
557              Lucas Da Cunha   13.523112   10.00
291              Nicolo Rovella   13.452102   30.00
427             Hicham Boudaoui   13.395242   15.00
446                Flynn Downes   13.332307   13.00
131            Eduard Spertsyan   13.180024   25.00
468                        Isco   12.886267    6.00
411             Davide Frattesi   12.842088   35.00
501                 Diego Gomez   12.283509   14.00
6                  Felix Nmecha   12.213988   28.00
78              Conor Gallagher   12.033484   40.00
457           Rodrigo Bentancur   11.939171   30.00
555              İlkay Gundogan   11.921005    5.00
221            Matteo Guendouzi   11.896764   32.00
541             Mauro Arambarri   11.889619   12.00
304            Adrien Thomasson   11.822322    5.00
243           Alessandro Bianco   11.712055    5.00
259            Faustino Anjorin   11.662209    6.00
364              Gianluca Busio   11.605998    6.00
79               Joshua Kimmich   11.576360   45.00
227         Pierre Ekwah Elimby   11.508368    7.00
552                 Marc Casado   11.479356   30.00
127          Idrissa Gana Gueye   11.445907    1.50
565                  Samu Costa   11.375105   15.00
161                Orel Mangala   11.251568   18.00
598           Maximilian Arnold   11.247959    5.00
346             Pierre Hojbjerg   11.125132   20.00
106          Rolando Mandragora   11.059726   12.00
72                 Senny Mayulu   10.931495   15.00
293           Exequiel Palacios   10.828766   40.00
406                 Romeo Lavia   10.806563   40.00
86              Rabby Nzingoula   10.582001    2.50
2                   Orkun Kokcu   10.565436   30.00
98              Youssouf Fofana   10.526655   30.00
405       Cristian Casseres Jr.   10.402487    6.00
461                 Joshua King   10.385812    1.00
390              Tim Iroegbunam   10.294369    9.00
149             Niccolo Pisilli   10.132974   13.00
116                Frank Onyeka    9.954167    7.00
50             Giovanni Fabbian    9.862767   12.00
358             Ibrahim Sangare    9.680211   24.00
421          Jurgen Ekkelenkamp    9.619435    7.00
194            Enzo Barrenechea    9.405286   10.00
317           Marco Brescianini    9.358660    8.00
579                 Tommy Doyle    9.341126   10.00
417            Fabian Ruiz Pena    9.189075   40.00
54                Yves Bissouma    9.177697   25.00
290                  Sasa Lukic    9.161339   14.00
132                 Mason Mount    9.108380   28.00
270                 Amadou Kone    9.069464    4.00
166             Johann Lepenant    9.038576    6.00
63             Dogucan Haspolat    9.018165    5.00
240                 Senne Lynen    8.867571    9.00
430               Lucien Agoume    8.789587    8.00
452                 Mohamed Haj    8.787954    1.80
616                Ross Barkley    8.786257    6.00
315            Hakan Calhanoglu    8.621408   30.00
309            Martin Zubimendi    8.411849   60.00
219       Konstantinos Karetsas    8.341231   20.00
589                  Matus Bero    8.315454    3.00
467          Abdoulaye Doucoure    8.310627    7.00
453            Ezechiel Banzuzi    8.253382   13.00
437                 Will Hughes    8.130589    7.00
85                 Toby Collyer    8.111607    5.00
12             Demir Ege Tiknaz    8.082329    5.00
175           Boubakary Soumare    8.080019   12.00
563       Christoph Baumgartner    8.006183   12.00
248                  Andy Diouf    7.877414   15.00
418              Adrian Bernabe    7.875120   15.00
354              Maximo Perrone    7.785701   12.00
177              Seydouba Cisse    7.756061    3.00
75              Lazar Samardzic    7.730485   17.00
165               Azor Matusiwa    7.712075    8.00
322                Sven Mijnans    7.688709    9.00
279               Daichi Kamada    7.666268   12.00
344        Maximilian Eggestein    7.653080   10.00
292                  Luka Sucic    7.588459   15.00
102              Jackson Irvine    7.532563    2.00
530              Cesare Casadei    7.529168   15.00
284            Mario Stroeykens    7.463415   12.00
482             Pedrinho Santos    7.431012   10.00
233             Patrizio Masini    7.427411    6.00
229                Oliver Skipp    7.418207   10.00
459            Mattias Svanberg    7.301492   12.00
483                Brais Mendez    7.294042   22.00
363                Sander Berge    7.056536   25.00
130              Ayyoub Bouaddi    7.033116   28.00
296                 Harry Winks    7.010054    9.00
361           Maksim Glushenkov    6.971268   14.00
516                Daan Heymans    6.922705    3.00
96                 Elisha Owusu    6.903978    3.00
135      Thorir Johann Helgason    6.903802    3.00
151            Ibrahim Sulemana    6.856058    7.00
15                Martin Payero    6.829017    5.50
19             Ibrahima Sissoko    6.826504    6.00
256              Sergi Altimira    6.804164   15.00
628                 Djibril Sow    6.770909    7.50
49                  Andy Irving    6.760569    4.00
265               Ardon Jashari    6.750454   32.00
30           Michel Ndary Adopo    6.714224    4.00
607             Cheick Doucoure    6.704078   25.00
84                 Granit Xhaka    6.685609   12.00
18             Kristjan Asllani    6.632402   13.00
178                 Pablo Marin    6.624357    8.00
478              Enric Llansana    6.623688    4.00
159               Medon Berisha    6.610706    1.50
548              Reda Belahyane    6.564276   10.00
584              Nicolo Fagioli    6.542738   18.00
262                 Ismael Kone    6.511354    9.00
57                 Julian Weigl    6.488919    6.00
553                 Noah Sadiki    6.488442   12.00
522             Yassin Belkhdim    6.480471    1.00
621                Warren Bondo    6.438770   10.00
66                    Sam Morsy    6.423839    0.50
419          Soungoutou Magassa    6.396763   12.00
269              Chuky san jose    6.389472    1.50
499             Rodrigo De Paul    6.318217   25.00
20             Arthur Vermeeren    6.298015   22.00
487             Amir Richardson    6.278648    8.50
448            Manuel Locatelli    6.223671   30.00
507                   Gio Reyna    6.167612    7.00
580                 Lucas Torro    6.134714    3.00
192             Andrei Mostovoy    6.119475    4.00
577                 Amine Harit    5.975357    8.00
8               Kacper Urbanski    5.944506    6.00
235              Antonio Blanco    5.915805   10.00
511              Mathias Jensen    5.897707   14.00
74                   Luis Milla    5.872051    3.50
471              Danilo Cataldi    5.851937    3.50
61          Benjamin Bouchouari    5.838156    5.00
439              Andras Schafer    5.771542    5.00
160              Antoni Milambo    5.755742   18.00
597             Bryan Cristante    5.744501    7.00
158                  Kike Perez    5.717353    2.80
544             Ngal'Ayel Mukau    5.690402   15.00
33               Moumi Ngamaleu    5.677184    4.00
438                Kevin Stoger    5.660755    3.50
36                 Kevin Danois    5.652437    8.00
481               Oscar Hojlund    5.648821    7.50
547                 Saul Niguez    5.584830    3.00
14                Niklas Dorsch    5.564262    3.50
455                Stije Resink    5.451434    4.00
434              Sean Longstaff    5.419374   20.00
111                Pablo Ibanez    5.376925    2.00
77              Frenkie de Jong    5.374930   45.00
153                Benat Prados    5.368836   18.00
76             Nicolas Gonzalez    5.341116   40.00
44                 Fran Beltran    5.336335    8.00
281              Vincent Sierro    5.273834    4.00
193                   Ivan Ilic    5.229801   16.00
554                Kevin Zeroli    5.225849    4.00
445             Elvis Rexhbecaj    5.224035    3.50
305           Lassana Coulibaly    5.208868    2.50
536                       Batxi    5.150959    5.00
376          Carney Chukwuemeka    5.091644   18.00
400           Mahamadou Diawara    5.073933    2.00
460                Jordan James    5.063041    8.00
218                 Suat Serdar    4.989376    4.50
298                 Bilal Nadir    4.985541    5.00
95                 Oscar Fraulo    4.981043    3.50
521                 Tom Cairney    4.962400    1.50
512            Jesper Karlstrom    4.932533    4.00
622                Alfie Devine    4.920751    3.50
56               Ivan Oleinikov    4.918279    1.40
43                Billy Gilmour    4.906948   20.00
420               Selim Amallah    4.875287    1.60
40                  Rob Schoofs    4.866178    2.20
225                  Jhon Solis    4.846936    2.50
443           Patrick Osterhage    4.844926   10.00
46                Youssef Maleh    4.825298    3.20
137              Alberto Grassi    4.788180    1.80
109          Lorenzo Pellegrini    4.783636    9.00
16                   Yvan Neyou    4.694694    3.00
110              Lewis Ferguson    4.694382   28.00
465              Mathis Amougou    4.673414   10.00
67             Jordan Holsgrove    4.649480    3.50
24            Antoine Makoumbou    4.626143    3.50
264              Kanya Fujimoto    4.611303    4.00
13                Stefan Loncar    4.601224    1.50
573             Carlo Boukhalfa    4.596497    2.00
416                 Lovro Majer    4.594417   17.00
531       Brian De Keersmaecker    4.591213    3.00
404        Albert Sambi Lokonga    4.590776    8.00
303            Yassine Titraoui    4.579590    5.00
600                  Olasagasti    4.546047    4.00
21                Urko Gonzalez    4.504319    5.00
429           Mahamadou Doumbia    4.493135    9.00
314           Balthazar Pierret    4.436337    1.70
425              Tajon Buchanan    4.433628    6.00
209       Jose Luis Garcia Vaya    4.429091    9.00
456               Mats Pannewig    4.424508    1.00
3                Ylber Ramadani    4.415879    1.80
140             Guido Rodriguez    4.405474   10.00
7                Philipp Sander    4.384890    4.00
352                Nail Umyarov    4.353987    4.00
351              Benjamin Andre    4.292383    5.00
329             Samuele Vignato    4.278573    2.20
588                 Emi Buendia    4.249396   15.00
527                     Hernani    4.216849    1.60
257                Matteo Prati    4.214403    6.00
392                  Pedro Diaz    4.194728    3.00
610             Tanguy Ndombele    4.187517    7.00
581            Siebe Schrijvers    4.151553    1.50
90                Cheikh Niasse    4.132627    2.50
203                 Ivan Martin    4.106690    6.00
464                   Marc Roca    4.087952    6.00
371       Magnus Kofod Andersen    4.042064    1.00
367                Rani Khedira    4.016684    2.50
295                 Joel Fujita    3.980926    3.00
493        Leonardo Bittencourt    3.978731    1.50
17                 Edu Exposito    3.978596    3.00
615                      Wendel    3.967312   18.00
534                 Nikola Moro    3.965166    4.50
191               German Valera    3.931691    1.50
214                Razvan Marin    3.928381    3.50
83             Benat Turrientes    3.860576   10.00
388              Matvei Kisliak    3.860132    8.00
606           Donny van de Beek    3.855472    5.00
22                 Rudy Matondo    3.850895    0.30
250             Antoine Bernede    3.844388    2.50
100           Jean-Eudes Aholou    3.833389    2.00
169                  Iker Munoz    3.825432    3.00
231               Morgan Sanson    3.803034    5.00
117                 Enzo Le Fee    3.693481   18.00
458               Enzo Loiodice    3.688080    1.20
185                 Jesse Bosch    3.686373    0.90
528               Hong Hyunseok    3.666905    3.50
560           Christian Eriksen    3.647522    4.00
150           Charles Vanhoutte    3.621172    6.00
538              Emircan Gurluk    3.610852    0.60
68              Santiago Garcia    3.589731    0.80
154               Aster Vranckx    3.579661    7.00
603             Daniel Bandeira    3.579360    2.50
539         Lucas Gourna-Douath    3.555676    8.00
25                 Adem Zorgane    3.470406    6.00
181         Baptiste Santamaria    3.467885    7.00
157                Mohamed Kaba    3.458998    2.00
494              Omar Mascarell    3.420718    0.90
574        Zinedine Ould Khaled    3.416856    0.40
395               Sergey Babkin    3.414672    1.80
190                Espen van Ee    3.368153    1.30
73              Nikita Krivtsov    3.367070    4.00
567           Stanislav Lobotka    3.338726   25.00
196                  Pol Lozano    3.328014    5.00
569            Michel Aebischer    3.327936    7.50
37              Luca Mazzitelli    3.327858    1.50
331                 Hamza Rafia    3.327858    1.40
431               Dani Ceballos    3.310292   10.00
546           Dave Van Den Berg    3.285351    2.00
480             Piotr Zielinski    3.284246   10.00
212                 Joan Jordan    3.267820    2.50
604                Nathan Rodes    3.255639    1.40
38                 Bryan Heynen    3.230789   11.00
94                 Jose Campana    3.229076    0.90
99            Pierre Lees-Melou    3.222932    6.00
152                Oier Zarraga    3.202416    2.00
202             Ismael Bennacer    3.191469   15.00
368            Carlos Benavidez    3.185618    1.20
58                Daniel Parejo    3.161209    1.50
613          Anouar Ait El Hadj    3.158817    3.00
397                Danil Glebov    3.154522    8.00
469             Florentino Luis    3.150171   22.00
241                Luis Esteves    3.118566    1.00
408             Gabriel Vidovic    3.097451    3.00
466              Philip Billing    3.093896   10.00
282               Igor Dmitriev    3.075320    1.00
319                Rafael Bauza    3.075014    0.20
288            Pedro Chirivella    3.070618    5.00
578              Julian Niehues    3.056113    1.50
475                Taichi Fukui    3.038916    2.00
562                Tomas Handel    3.019033   13.00
551                 Hugo Sotelo    3.015239    4.00
327               Yannik Keitel    3.013193    3.50
287                 Luka Modric    3.011216    4.00
300              Haris Belkebla    3.009827    2.00
260             Djibril Soumare    3.009110    1.50
267                 Ryotaro Ito    2.999862    2.50
134               Miguel Menino    2.999396    1.00
280              Assane Diousse    2.987361    0.70
503               Ander Guevara    2.966875    3.50
27             Damian Rodriguez    2.962974    3.00
254               Lucas Tousart    2.907013    2.50
335             Daniel Braganca    2.897757   12.00
495              Amadou Haidara    2.887339   16.00
122               Manu Morlanes    2.880552    2.50
342           Mathias De Amorim    2.872920    1.50
155                  Ryan Fosso    2.858619    1.50
529         Christopher Martins    2.858020    6.00
0                  Mateo Flores    2.855783    1.00
41          Nikolas Sattlberger    2.834942    3.50
441              Hugo Guillamon    2.832900    2.50
278                    Jorginho    2.792897    6.00
449                Justin Smith    2.792025    0.30
378               Matias Vecino    2.776324    2.00
104                   Victor Sa    2.763801    3.00
556                Joey Veerman    2.729689   25.00
93                   Max Balard    2.728568    1.50
108               Nabil Aberdin    2.716107    0.70
336                 Isaac Price    2.698986    3.00
249              Massimo Luongo    2.694866    0.40
147           Birger Verstraete    2.685208    1.80
123                Douglas Luiz    2.668571   30.00
355          Ivan Jaime Pajuelo    2.659573    5.00
436            Faisal Al Ghamdi    2.657788    1.50
490               Davy Klaassen    2.654958    3.50
330              Quinten Timber    2.654867   30.00
345               Skelly Alvero    2.645446    2.50
337             Florian Neuhaus    2.635989    3.50

In [97]:
comp_leftovers_test[comp_leftovers_test['Player'].str.contains('Okish')]

             Player  Value_pred  Value
120  Viktor Okishor    2.785161    0.5