In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_rows', None)

In [109]:
X_train = pd.read_csv('../../../data/processed/for_linear_model/FW,MF/predictors_train_filtered.csv')
X_test = pd.read_csv('../../../data/processed/for_linear_model/FW,MF/predictors_test_filtered.csv')
y_train = pd.read_csv('../../../data/processed/for_linear_model/FW,MF/target_train_filtered_logariphmed.csv')
y_test = pd.read_csv('../../../data/processed/for_linear_model/FW,MF/target_test_filtered_logariphmed.csv')

In [4]:
train_players = pd.read_csv('../../../data/processed/for_linear_model/FW,MF/train_players_names.csv')
test_players = pd.read_csv('../../../data/processed/for_linear_model/FW,MF/test_players_names.csv')

In [5]:
all_cols = X_train.columns
all_cols

Index(['Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK',
       '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh', 'SoT',
       'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'],
      dtype='object')

<b>Регрессор</b>

In [97]:
LR_regressor = LinearRegression()
LR_regressor.fit(X_train, y_train)

LinearRegression()

<b>Предсказанные значения</b>

In [98]:
y_pred_log = LR_regressor.predict(X_test)
y_pred = np.exp(y_pred_log)
y_test_original = np.exp(y_test)

y_train_pred = np.exp(LR_regressor.predict(X_train))
y_train_original = np.exp(y_train)

<b>Метрики</b>

In [99]:
mae_test = mean_absolute_error(y_test_original, y_pred)
rmse_test = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2_test = r2_score(y_test_original, y_pred)
mape_test = mean_absolute_percentage_error(y_test_original, y_pred)

mae_train = mean_absolute_error(y_train_original, y_train_pred)
rmse_train = np.sqrt(mean_squared_error(y_train_original, y_train_pred))
r2_train = r2_score(y_train_original, y_train_pred)
mape_train = mean_absolute_percentage_error(y_train_original, y_train_pred)

metrics = pd.DataFrame({
    'MAE':[mae_test, mae_train],
    'RMSE':[rmse_test, rmse_train],
    'MAPE':[mape_test, mape_train],
    'R2':[r2_test, r2_train]
}, index = ['test', 'train'])

<b>Сравнение остатков</b>

In [100]:
y_pred = pd.Series(np.reshape(y_pred, len(y_pred)), name='Value_pred')
y_train_pred = pd.Series(np.reshape(y_train_pred, len(y_train_pred)), name='Value_pred')

comp_leftovers_test = pd.concat([test_players, y_pred, y_test_original], axis=1)
comp_leftovers_train = pd.concat([train_players, y_train_pred, y_train_original], axis=1)

<b>Коэффициенты</b>

In [101]:
coeffs = LR_regressor.coef_[0]
coeffs_df = pd.DataFrame({
    'coeff':coeffs.astype('float')
}, index=X_train.columns)
coeffs_df = coeffs_df.sort_values(by='coeff', key=abs, ascending=False)

<b>Все переменные</b>

In [10]:
coeffs_df

               coeff
Min        -1.459256
90s         1.043555
league_GB1  0.755900
G-PK.1     -0.611205
G+A-PK      0.535746
Starts      0.504469
Gls.1       0.480824
league_IT1  0.435443
G/Sh       -0.329266
Fls        -0.320049
league_ES1  0.305535
Age        -0.305468
Sh          0.301979
league_L1   0.301958
league_FR1  0.295248
G/SoT       0.272782
Ast.1      -0.216246
TklW        0.184193
SoT         0.182788
league_NL1 -0.164510
Ast         0.151901
Sh/90      -0.146820
SoT/90      0.141563
PK         -0.100960
Fld         0.088721
MP          0.081116
G+A         0.076785
Int        -0.069917
G+A.1      -0.067491
CrdR       -0.057133
Off         0.049552
CrdY        0.048332
league_PO1  0.044491
league_RU1  0.042725
PKatt      -0.035967
SoT%       -0.035448
G-PK        0.035279
Crs        -0.033356
OG         -0.027568
2CrdY       0.024788
Gls         0.008897

In [28]:
metrics

            MAE       RMSE      MAPE        R2
test   4.382325   8.073346  0.833730  0.617946
train  5.075260  15.356006  0.672494  0.138782

In [29]:
comp_leftovers_test

                     Player  Value_pred  Value
0              Antonio Nusa    8.143371  28.00
1              Luis Vazquez    2.025725   2.50
2           Tristan Degreef    0.919353   2.00
3        Maximilian Breunig    3.030932   1.50
4                Kike Barja    1.250319   1.50
5           Pontus Almqvist    3.380170   2.50
6              Jacob Ramsey   20.577263  32.00
7            Luciano Gondou    6.069575  12.00
8            Issiaka Kamate    0.765947   0.75
9             Lucas Beltran    5.981920  18.00
10           Tomas Conechny    1.695364   1.80
11          Sheraldo Becker    2.027057   2.50
12         Anthony Descotte    0.878990   0.65
13            Marc Domenech    2.089315   1.00
14              John Yeboah    4.281191   2.80
15              Noah Okafor    2.741986  13.00
16             Nigel Thomas    0.733931   0.30
17  Gabriel Airton de Souza    1.077925   0.80
18            Conrad Harder    4.860552  24.00
19             Franco Cervi    0.922884   0.80
20         Soltmurad Bakaev    1.838621   0.70
21            Stanis Idumbo    3.391278   2.50
22              Sekou Koita    2.033224   3.50
23            Felix Correia    3.625804   4.00
24            Irvin Cardona    5.529417   2.50
25          Mason Greenwood   46.264265  40.00
26           Marin Ljubicic    1.610902   4.00
27         Marvin Pieringer    5.060402   5.50
28   Christopher Bonsu-Baah    3.847941   7.50
29         Jeremy Antonisse    1.138768   0.70
30             Sorba Thomas    6.242357   3.50
31             Breel Embolo    8.337640  12.00
32            Ibrahim Osman    1.609728  10.00
33                Bryan Gil    6.202676  15.00
34      Dardan Shabanhaxhaj    1.886583   1.20
35           Thorgan Hazard    0.656597   2.50
36                Juan Cruz    7.467461   5.00
37           Yaser Asprilla    6.258786  15.00
38             Rayan Cherki   25.003913  45.00
39           Anthony Gordon   62.690659  65.00
40    Gabriel Osei Misehouy    3.262967   1.00
41             Wahbi Khazri    1.564867   1.00
42            Luka Ivanusec    0.497777   3.50
43             Dario Poveda    1.586539   0.50
44      Andreas Schjelderup    1.887307  15.00
45             Lukas Nmecha    3.103450   3.00
46           El Bilal Toure    3.609422  15.00
47           Alfonso Trezza    1.652008   1.00
48         Gil Bastiao Dias    2.471487   1.50
49             Cisse Sandra    0.853279   1.00
50             Pedro Santos    0.822934   0.80
51               Robin Hack   16.646099  12.00
52              Jordan Ayew    9.385992   2.50
53           Erik Ahlstrand    1.777773   0.50
54         Mathis Lambourde    5.449356   0.80
55            Josue Casimir    7.890399   4.00
56             Angel Correa    1.901119  10.00
57              Vasco Lopes    1.668193   0.50
58            Juho Talvitie    1.330519   0.90
59             Dave Kwakman    1.449965   2.00
60               Sekou Mara    2.453443   5.00
61        Julien Duranville    2.019777   8.50
62             Max Svensson    1.174537   0.50
63            Anass Zaroury    5.264814   8.00
64         Bernardo Martins    1.516416   1.00
65              Luka Romero    1.912507   4.00
66              Kai Havertz   27.758426  65.00
67               Ayman Aiki    1.762609   0.40
68               Elias Saad    4.695144   4.00
69                     Caue    1.126837   0.80
70            Denis Makarov    1.648530   1.20
71         Oscar Pettersson    0.314298   0.50
72             Andre Inacio    3.739037   2.50
73         Vladislav Shitov    1.341731   0.80
74            Jamie Gittens   18.053477  50.00
75           Yusuf Kabadayi    8.278809   1.50
76    Allahyar Sayyadmanesh    6.500773   4.00
77         Nicolas Gonzalez    7.091077  24.00
78        Giacomo Raspadori    9.472485  25.00
79      Benedict Hollerbach   13.479576  12.00
80             Caio Santana    0.911400   0.10
81  Marcos Vinicios Sorriso    3.779064   5.00
82              Luka Tunjic    0.750283   0.45
83           Felipe Augusto    2.122988   2.20
84           Yankuba Minteh   53.138171  30.00
85           Andrea Colpani    4.048717   9.50
86              Frank Magri    4.136268   3.00
87          Vincent Janssen    6.638940   7.00
88         Miguel Rodriguez    3.472955   4.50
89           Abdoulay Diaby    0.481779   0.20
90                Keke Topp    4.657785   4.00
91        Francesco Camarda    2.316022  10.00
92       Callum Hudson-Odoi   30.696951  25.00
93             Jordi Mboula    0.667879   0.50

In [30]:
comp_leftovers_train

                           Player  Value_pred    Value
0                  Vincenzo Grifo   20.035632    6.000
1             Rifat Zhemaletdinov    1.259427    2.500
2                 Roger Fernandes    4.364004   22.000
3                     Gyrano Kerk    2.358704    3.000
4                 Musa Al-Taamari    5.404008    6.000
5                   Emilio Kehrer    1.062651    0.500
6              Albert Gudmundsson    4.620049   18.000
7                     Moses Simon    8.303744   12.000
8                   Michal Skoras    0.758983    2.500
9                  Sirlord Conteh    1.599808    1.500
10                  Ferran Torres   20.365179   40.000
11                  Ilias Sebaoui    1.115559    1.500
12                Josimar Alcocer    2.610096    2.200
13                  Ivan Sergeyev    2.354987    3.000
14                        Antoniu    2.540111    1.800
15   Lucas Vennegoor of Hesselink    0.433010    0.300
16                Jorge de Frutos    4.056179    4.000
17                  Paris Brunner    1.298961    1.500
18                   Adri Embarba    2.026820    1.200
19                    Lois Openda   25.787418   50.000
20                Lorenzo Colombo    8.166868    5.000
21          Crysencio Summerville   12.849536   22.000
22                Mohamed Ali Cho   12.223245   15.000
23                         Juanmi    1.180113    2.000
24                           Pepe    1.533398   22.000
25                 Nicolo Zaniolo    2.892378   12.000
26                    Bruno Messi    0.469981    0.700
27                    Igor Paixao   24.331181   35.000
28           Nuno Goncalo Moreira    3.471170    3.000
29                     Joao Felix    8.780942   20.000
30                          Portu    1.256123    1.800
31                Florian Thauvin    9.502663    5.000
32                   Danel Sinani    2.782087    1.500
33                  Ronaldo Cesar    4.647831    4.000
34                  Mamadou Sylla    1.826238    1.200
35                   Charly Keita    0.746550    0.550
36              Saeid Saharkhizan    3.381645    1.000
37                   Ruben Macedo    0.765869    0.450
38                Bazoumana Toure    3.758228    9.000
39                 Egas Cacintura    1.975727    1.000
40              Youssoufa Moukoko    8.989681   10.000
41                Chemsdine Talbi    4.855975    8.000
42                           Raul    4.386192    3.000
43             Moritz Broschinski    4.041969    2.000
44                 Brian Mansilla    0.773159    1.000
45                  Mickael Biron    0.504518    1.200
46               Nokkvi Thorisson    1.073136    0.600
47                 Johan Manzambi    6.287414    8.000
48             William Balikwisha    1.026798    1.200
49           Abbosbek Fayzullayev    3.979232    8.000
50                          Jason    1.861037    2.500
51                 Sandro Ramirez    7.108137    2.500
52                     Elif Elmas    5.823299   14.000
53                 Gabri Martinez    4.870246    4.000
54               Viktor Tsyhankov    4.789505   18.000
55                           Suso    1.370362    1.500
56                  Edon Zhegrova    3.367172   25.000
57                  Ibrahim Mbaye    4.616300    3.000
58            Sebastiano Esposito    9.987761    8.500
59               Denilho Cleonise    0.801934    0.400
60             Baptiste Guillaume    0.332593    0.450
61               Erencan Yardimci    1.598032    2.500
62                 Fabio Carvalho   15.862083   14.000
63                  Junior Kadile    2.002811    0.650
64                 Carlos Eduardo    0.775334    0.700
65                 Evann Guessand   21.566250   25.000
66                 Jacob Trenskow    2.598655    4.000
67                 Jonathan Ikone    4.111737    7.000
68                    Leon Bailey   11.858114   28.000
69                   Mario Engels    0.743225    0.500
70         Alessandro Gabrielloni    2.798967    0.850
71                  Mexx Meerdink    2.777198    8.000
72                       Raphinha   94.588485   90.000
73                  Thijs Oosting    0.448512    0.500
74                           Jota    1.497916    8.000
75                Mario Balotelli    0.677918    0.500
76                 Othmane Maamma    3.658941    0.600
77                 Yanis Begraoui    5.407597    3.500
78                     Joao Pedro   28.063800   50.000
79                    Pablo Duran    3.788326    3.500
80                    Bukayo Saka  118.271617  150.000
81                 Osame Sahraoui    4.103821   12.000
82                        Willian    2.024707    0.750
83                 Florinel Coman    3.682467    5.000
84                 Alex Berenguer    6.862593    9.000
85                  Jovane Cabral    1.022654    1.000
86                 Wilson Odobert   13.473286   20.000
87                 Kacper Kostorz    0.540884    0.450
88               Christantus Uche    7.983596   15.000
89                  Alvaro Morata    3.120961   11.000
90                  Filip Krastev    2.556258    4.000
91               Marcus Tavernier   25.975553   18.000
92                     Tim Skarke    2.777012    2.000
93                   Adama Traore   19.231865    9.000
94                   Steve Mounie    1.372996    2.000
95             Gabriel Martinelli   60.368603   55.000
96                  Sontje Hansen    2.418132    4.000
97                   Joao Marques    1.006348    3.000
98               Mohammed Fuseini    2.433975    4.500
99                Ignatius Ganago    0.963539    2.000
100                    Amar Ahmed    0.575044    0.450
101                 Morgan Rogers   75.470557   55.000
102            Kingstone Mutandwa    1.366160    0.600
103                    Alieu Njie    2.896665    2.500
104                  Thibo Somers    2.436402    2.500
105                  Abde Rebbach    1.257054    0.700
106              Valentin Mihaila    5.134577    3.000
107                   Alex Millan    0.548915    0.500
108                Kirill Danilin    1.351780    0.700
109                    Jonas Wind    7.945572   12.000
110                Yussuf Poulsen    1.973861    5.000
111                Keito Nakamura   17.378391    8.000
112           Remy Labeau Lascary    3.114397    2.000
113                 Simon Adingra   19.827486   28.000
114            Facundo Buonanotte   31.795727   20.000
115            Vyacheslav Grulyov    1.757640    1.200
116              Anis Hadj Moussa    4.055085   14.000
117               Francisco Perez    2.234658    3.000
118                   Brahim Diaz    6.433583   40.000
119            Muhammed Gumuskaya    0.361783    0.350
120        Alexander Bernhardsson    4.778067    3.000
121                 Abdallah Sima    9.361104    9.000
122                   Matheusinho    0.462676    1.500
123                     Rui Costa    1.052229    0.600
124                    Alex Iwobi   71.588476   28.000
125              Eldor Shomurodov    4.998063    5.000
126                Joshua Zirkzee   18.361769   30.000
127              Oliver Edvardsen    3.487329    5.000
128                 Jack Grealish    8.751548   28.000
129                  Ruben Garcia    3.561467    2.000
130             Arnaud Kalimuendo   16.333426   22.000
131                 Jonathan Rowe    7.921485   12.000
132                  Marco Matias    0.552701    0.100
133                   Lee Kang-in   11.131177   25.000
134               Bernard Berisha    0.388895    0.600
135              Munir El Haddadi    2.875524    1.500
136                   Dylan Mbayo    2.853155    2.000
137                    Iago Aspas    3.587274    2.000
138                Sergiu Perciun    2.721270    1.500
139               Jeremy Agbonifo    2.023177    5.000
140                Thomas Buitink    0.315645    0.400
141         Arkaitz Mariezkurrena    3.171530    0.700
142                  Ilyes Housni    1.917053    1.500
143                Sana Fernandes    0.774187    0.700
144                   Deniz Undav   14.052232   20.000
145                 Ismael Konate    4.192960    1.000
146                 Carlos Martin    4.039968    2.800
147              Victor Edvardsen    2.112141    1.300
148                  Takuma Asano    2.980828    2.500
149                  Noah Adedeji    3.947340    4.500
150               Hyllarion Goore    0.883335    0.600
151                     Junya Ito    4.844609    6.000
152                Bryan Zaragoza    8.552785   12.000
153                  David Brooks    9.869495   10.000
154                 Omar Marmoush  256.225352   75.000
155                  Jarrod Bowen  158.486464   40.000
156                   Jose Arnaiz    1.242283    1.500
157            Michael Folorunsho    2.026514    6.000
158                          Dudu    1.709033    0.600
159                  Younes Namli    0.755580    1.300
160               Riccardo Sottil    3.827474    5.000
161                  Armindo Sieb    4.514566    3.000
162                 Loum Tchaouna    3.876902   10.000
163                   Nuno Santos    2.296214    2.500
164                         Bruma    4.502750    7.000
165             Maghnes Akliouche   17.614303   45.000
166                Jann-Fiete Arp    2.185203    0.800
167                     Enes Unal   10.875094   10.000
168                Mats Seuntjens    0.389010    0.550
169               Sammie Szmodics   13.226653   10.000
170              Augustine Boakye    2.693674    2.500
171                  Mathis Suray    1.102776    1.500
172                 Paulinho Boia    1.295939    0.700
173              Henrique Pereira    0.679070    0.800
174                    Ante Erceg    0.168048    0.100
175                         Pedro    3.590195    1.000
176                   Tiago Tomas    9.125885   12.000
177             Christian Pulisic   27.565579   50.000
178                 Jizz Hornkamp    0.878352    1.300
179                 Ismael Gharbi    3.853376    7.500
180                       Rodrygo   14.885054   90.000
181                Adam Armstrong   11.894490   12.000
182                 Karim Adeyemi   11.980233   45.000
183               Florent Muslija    1.349647    1.800
184                  Kaj de Rooij    0.279359    0.350
185                    Ricardinho    1.078155    1.000
186                  Chris Lokesa    1.386224    0.400
187                    Iker Bravo    5.864899    3.000
188                  Samuel Bamba    1.870707    0.500
189                Emmanuel Sabbi    1.483785    1.500
190                   Desire Doue   17.788884   90.000
191                    Danny Ings    6.975205    6.000
192                  Zito Luvumbo    4.824095    5.000
193             Adrian Benedyczak    1.845525    4.500
194              Williot Swedberg   10.299210    5.000
195                  Ruben Vargas    3.009994    7.000
196                Goncalo Borges    1.530706    5.000
197                   Timo Werner    7.356041    7.000
198                   Che Nunnely    0.396673    0.500
199                  Koji Miyoshi    1.416284    1.500
200                 Marco Asensio   32.414434   20.000
201                  Kenan Yildiz   29.629056   50.000
202                Romano Postema    0.747635    0.450
203                     Dani Raba    4.999805    2.500
204                   Fuki Yamada    1.240354    0.700
205                   Marco Grull    4.048900    4.000
206              Tanguy Coulibaly    1.893330    1.500
207                Bobby Adekanye    0.580159    0.650
208                 Elton Kabangu    0.442122    0.600
209                 Samuel Lobato    0.723804    0.200
210                         Alfon    5.107465    5.000
211                 Nicolas Viola    3.099282    1.000
212               Abde Ezzalzouli   10.546463   12.000
213                  Paulo Dybala    9.073726    8.000
214                   Jack Clarke   13.843669   15.000
215                 Ernest Nuamah    4.992472   15.000
216         Aleksandr Lomovitskiy    0.561228    0.500
217                  Alexis Flips    0.419434    1.000
218            Adriano Bertaccini   16.345372    4.500
219                Florian Sotoca    2.201482    2.000
220             Bahereba Guirassy    4.105325    1.000
221                  Faiz Mattoir    0.327511    0.200
222                 Michael Olise  124.778563  100.000
223                        Thiago    5.655846   18.000
224                     Fer Lopez    3.390892    5.000
225                    Alan Minda    2.187877    3.000
226           Francisco Conceicao    7.760124   28.000
227                    Raul Paula    0.705641    0.600
228                  Matt Garbett    0.680941    0.400
229                Carlos Alcaraz   18.019278   14.000
230               Franjo Ivanovic   15.098779   13.000
231           Alireza Jahanbakhsh    0.578574    1.500
232                 Eddie Nketiah   12.835560   18.000
233             Lorenzo Venturino    4.695444    1.500
234              Christian Kouame    3.085212    4.000
235                    Milan Smit    1.632704    1.500
236               Mateo Cassierra    3.446537   10.000
237             Gianluca Lapadula    0.609355    0.750
238          Tiago Fonseca Morais    2.577302    3.000
239               Alberto Moleiro   10.935091   25.000
240                  Harry Wilson   25.405169   15.000
241              Kerem Akturkoglu   15.899498   24.000
242                    Jota Silva   12.903746   15.000
243                  Issa Soumare    9.137605    2.000
244                    Jaime Mata    0.737889    0.400
245                   Scott Banks    1.270746    0.500
246                    Ramon Sosa    8.630752   12.000
247               Christos Tzolis   25.541417   25.000
248                  Koen Kostons    0.599254    0.600
249              Antoine Colassin    1.935258    0.750
250                Tijjani Noslin    3.456080    7.500
251                   Leo Scienza    6.635284    3.000
252                Mohammed Kudus   49.748733   45.000
253                   Vando Felix    0.647670    1.000
254               Joselpho Barnes    0.565286    0.200
255             Miliano Jonathans    0.387511    0.900
256                  Lameck Banda    2.628482    4.500
257                    Dennis Man   11.831773   10.000
258              Oladapo Afolayan    3.814051    4.000
259          Mathias Pereira Lage    4.600218    2.500
260              Odysseus Velanas    0.491559    0.550
261               Zinedine Ferhat    1.160504    1.000
262                  Helio Varela    0.819947    1.200
263               Mamadou Diakhon    4.778350    3.000
264                 Said Benrahma    2.538749   10.000
265                  Yusupha Njie    0.435349    0.800
266                   Levi Garcia    0.795864   12.000
267               Stefan Schimmer    0.731598    0.500
268                 Yassir Zabiri    0.568878    0.600
269      D'Margio Wright-Phillips    0.522535    0.250
270                    Ritsu Doan   29.362910   25.000
271              Razhab Magomedov    1.007715    0.600
272                  Lucas Michal    1.691830    0.500
273              Andrew Hjulsager    0.506308    0.600
274                  Danny Loader    1.438254    4.000
275                    Basar Onal    1.052193    0.700
276               Raheem Sterling    4.784656   10.000
277             Gabriel Strefezza   12.811306    6.000
278                  Kiko Bondoso    1.601567    0.800
279                 Gboly Ariyibi    0.422594    0.200
280                 Nelson Weiper    5.109623   10.000
281              Samuel Chukwueze    8.023408   10.000
282                 Ethan Nwaneri   34.537761   55.000
283                         Savio   68.262727   50.000
284              Jan-Niklas Beste    0.804986    7.000
285                 Otso Liimatta    0.644758    0.800
286           Samuel Iling-Junior    7.593502   10.000
287                  Gerson Sousa    0.656508    1.300
288               Jeremy Livolant    1.592311    1.500
289                  Serge Gnabry    6.896238   22.000
290                 Nick Doodeman    0.503471    0.400
291             Gaetano Oristanio    7.693408    6.000
292                   Solly March    3.618886    6.000
293                  Nicolas Pays    1.831583    0.700
294                 Ferran Jutglà    8.625904    8.000
295            Kamaldeen Sulemana   14.643523   13.000
296                Anthony Elanga  143.120361   42.000
297                   Lucas Holer    4.642725    3.000
298                Daniel Maldini   12.563971   10.000
299                   Abdon Prats    1.853302    1.200
300                   Konan N'dri    2.087209    1.400
301              Ruben Providence    0.426238    0.350
302              Gilson Benchimol    2.709153    0.700
303                  Helder Costa    0.715799    0.400
304                          Sala    0.611371    0.200
305              Mathieu Maertens    0.828721    1.800
306                Arnaut Danjuma    3.979787    4.000
307                  Kaoru Mitoma   28.723160   40.000
308              Mathias Fixelles    0.477175    0.300
309                  Tete Morente    4.939898    2.000
310            Alexander Jakobsen    0.188073    0.075
311             Antoine Griezmann    9.604235   18.000
312                Nick Woltemade   10.983196   30.000
313                  John Mercado    2.720779    2.500
314               Stefan Mitrovic    1.740966    1.500
315                  Adrian Blake    1.612497    0.750
316                     Dany Mota    5.550366    4.000
317                Joaquin Correa    3.005908    3.000
318              Mauro Luna Diale    1.244393    1.000
319              Giorgos Masouras    2.724287    2.000
320                 Alvaro Garcia    7.326732    2.000
321                Suf Podgoreanu    0.850000    0.850
322               Matteo Politano    8.956658   10.000
323                  Jeremy Sebas    1.549112    0.700
324                Benjamin Sesko   21.466908   70.000
325                 Morlaye Sylla    2.265234    2.500
326           Zuriko Davitashvili   19.775545   10.000
327             Morgan Guilavogui    3.657372    4.000
328           Miguel Puche Garcia    0.956958    0.400
329                Justin Njinmah    5.926756    7.000
330                  Jeff Ekhator    4.422809    5.000
331                   Adam Nhaili    0.984658    0.250
332        Younes Taha El Idrissi    0.376685    1.000
333               Jovan Mijatovic    1.522445    3.000
334                Ibrahima Wadji    0.701557    0.700
335                   Jeremy Doku   47.728853   50.000
336                      Vinicius    3.076580    2.500
337                   Patson Daka    7.918565    9.000
338              Lassine Sinayoko    9.845885    4.000
339                 Islam Slimani    0.614254    0.500
340                  Grejohn Kyei    0.478329    0.700
341               Steven Berghuis    0.601033    3.500
342            Matteo Cancellieri    4.354005    4.500
343                    Luka Jovic    3.108180    4.500
344              Valeri Tsarukyan    1.713240    0.350
345                 Shuto Machino    9.024161    5.000
346                       Ben Old    1.806205    0.700
347                    Ante Rebic    1.254375    1.000
348              Yunus Emre Konak    6.875554    4.500
349           Kristoffer Peterson    0.854630    0.800
350              Maximilian Beier   16.764825   25.000
351               Tidjany Chabrol    2.638640    0.500
352                 Oliver Antman    9.838138    6.000
353             Dailon Livramento    2.516501    0.800
354                   Adam Hlozek   18.977629   18.000
355                   Joshua King    3.563320    1.800
356                  Remy Cabella    1.684142    2.500
357                 Milos Lukovic    1.055351    5.000
358              Kornelius Hansen    1.572628    0.500
359                      Rafa Mir    1.977978    0.800
360                  Roy Kuijpers    0.282522    0.275
361                 Manuel Fuster    2.660838    1.500

<b>Модель 1.<br>
Переменные: 'G+A', 'Ast', 'SoT', 'G+A-PK', '90s', 'Ast.1', 'Fld', 'Crs', 'SoT/90', 'Off', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'</b>

In [31]:
X_train = X_train[['G+A', 'Ast', 'SoT', 'G+A-PK', '90s', 'Ast.1', 'Fld', 'Crs', 'SoT/90', 'Off', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Ast', 'SoT', 'G+A-PK', '90s', 'Ast.1', 'Fld', 'Crs', 'SoT/90', 'Off', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [37]:
coeffs_df

               coeff
league_GB1  0.735027
SoT         0.439562
league_IT1  0.373715
league_L1   0.276272
league_FR1  0.273967
league_ES1  0.228564
G+A-PK      0.204463
league_NL1 -0.181836
Ast         0.171821
Fld         0.109514
G+A         0.101938
90s         0.095058
Off        -0.048759
Crs        -0.032049
Ast.1      -0.023451
league_RU1 -0.006097
SoT/90     -0.001846
league_PO1  0.001016

In [38]:
metrics

            MAE       RMSE      MAPE        R2
test   5.010587  10.142198  0.790099  0.397050
train  5.396066  13.178744  0.824118  0.365686

In [39]:
comp_leftovers_test

                     Player  Value_pred  Value
0              Antonio Nusa    3.712396  28.00
1              Luis Vazquez    1.880706   2.50
2           Tristan Degreef    0.604785   2.00
3        Maximilian Breunig    1.893953   1.50
4                Kike Barja    1.423746   1.50
5           Pontus Almqvist    3.632810   2.50
6              Jacob Ramsey   12.489325  32.00
7            Luciano Gondou    4.012628  12.00
8            Issiaka Kamate    0.527373   0.75
9             Lucas Beltran    7.422511  18.00
10           Tomas Conechny    1.977516   1.80
11          Sheraldo Becker    2.743215   2.50
12         Anthony Descotte    0.457180   0.65
13            Marc Domenech    1.163930   1.00
14              John Yeboah    3.684340   2.80
15              Noah Okafor    2.520487  13.00
16             Nigel Thomas    0.720893   0.30
17  Gabriel Airton de Souza    1.321335   0.80
18            Conrad Harder    4.690803  24.00
19             Franco Cervi    1.056626   0.80
20         Soltmurad Bakaev    1.578608   0.70
21            Stanis Idumbo    2.070518   2.50
22              Sekou Koita    1.329467   3.50
23            Felix Correia    3.361298   4.00
24            Irvin Cardona    4.695823   2.50
25          Mason Greenwood   97.586760  40.00
26           Marin Ljubicic    2.375992   4.00
27         Marvin Pieringer    9.351769   5.50
28   Christopher Bonsu-Baah    2.888754   7.50
29         Jeremy Antonisse    0.728290   0.70
30             Sorba Thomas    2.313655   3.50
31             Breel Embolo    9.522653  12.00
32            Ibrahim Osman    1.015013  10.00
33                Bryan Gil    5.044662  15.00
34      Dardan Shabanhaxhaj    2.330986   1.20
35           Thorgan Hazard    1.146227   2.50
36                Juan Cruz    5.166088   5.00
37           Yaser Asprilla    3.023476  15.00
38             Rayan Cherki   21.932506  45.00
39           Anthony Gordon   47.823906  65.00
40    Gabriel Osei Misehouy    1.544073   1.00
41             Wahbi Khazri    2.430093   1.00
42            Luka Ivanusec    0.471057   3.50
43             Dario Poveda    1.280190   0.50
44      Andreas Schjelderup    1.617048  15.00
45             Lukas Nmecha    3.548333   3.00
46           El Bilal Toure    3.006236  15.00
47           Alfonso Trezza    2.504968   1.00
48         Gil Bastiao Dias    2.746038   1.50
49             Cisse Sandra    1.078210   1.00
50             Pedro Santos    0.571692   0.80
51               Robin Hack   12.937296  12.00
52              Jordan Ayew   16.359104   2.50
53           Erik Ahlstrand    1.216424   0.50
54         Mathis Lambourde    3.506821   0.80
55            Josue Casimir    5.558729   4.00
56             Angel Correa    3.841367  10.00
57              Vasco Lopes    1.776509   0.50
58            Juho Talvitie    0.770426   0.90
59             Dave Kwakman    0.618875   2.00
60               Sekou Mara    2.431603   5.00
61        Julien Duranville    1.406677   8.50
62             Max Svensson    1.849133   0.50
63            Anass Zaroury    3.839107   8.00
64         Bernardo Martins    2.219441   1.00
65              Luka Romero    1.046585   4.00
66              Kai Havertz   38.044148  65.00
67               Ayman Aiki    1.284345   0.40
68               Elias Saad    3.789438   4.00
69                     Caue    1.029435   0.80
70            Denis Makarov    1.341079   1.20
71         Oscar Pettersson    0.332173   0.50
72             Andre Inacio    2.239396   2.50
73         Vladislav Shitov    1.137121   0.80
74            Jamie Gittens   13.072645  50.00
75           Yusuf Kabadayi    3.433874   1.50
76    Allahyar Sayyadmanesh    4.172235   4.00
77         Nicolas Gonzalez    8.982263  24.00
78        Giacomo Raspadori    6.576990  25.00
79      Benedict Hollerbach    9.013080  12.00
80             Caio Santana    0.540441   0.10
81  Marcos Vinicios Sorriso    4.909157   5.00
82              Luka Tunjic    0.539032   0.45
83           Felipe Augusto    2.323219   2.20
84           Yankuba Minteh   27.231232  30.00
85           Andrea Colpani    4.592322   9.50
86              Frank Magri    6.273251   3.00
87          Vincent Janssen   13.800541   7.00
88         Miguel Rodriguez    2.524187   4.50
89           Abdoulay Diaby    1.209297   0.20
90                Keke Topp    5.026038   4.00
91        Francesco Camarda    1.583864  10.00
92       Callum Hudson-Odoi   23.316763  25.00
93             Jordi Mboula    1.065391   0.50

In [40]:
comp_leftovers_train

                           Player  Value_pred    Value
0                  Vincenzo Grifo   28.678508    6.000
1             Rifat Zhemaletdinov    1.532433    2.500
2                 Roger Fernandes    3.698332   22.000
3                     Gyrano Kerk    3.592852    3.000
4                 Musa Al-Taamari    4.440971    6.000
5                   Emilio Kehrer    0.865675    0.500
6              Albert Gudmundsson    5.931311   18.000
7                     Moses Simon   14.716896   12.000
8                   Michal Skoras    0.810240    2.500
9                  Sirlord Conteh    2.217511    1.500
10                  Ferran Torres   16.790272   40.000
11                  Ilias Sebaoui    0.932863    1.500
12                Josimar Alcocer    1.296408    2.200
13                  Ivan Sergeyev    5.098279    3.000
14                        Antoniu    1.759487    1.800
15   Lucas Vennegoor of Hesselink    0.335812    0.300
16                Jorge de Frutos    6.520379    4.000
17                  Paris Brunner    0.870332    1.500
18                   Adri Embarba    2.340228    1.200
19                    Lois Openda   24.299366   50.000
20                Lorenzo Colombo    9.923446    5.000
21          Crysencio Summerville    9.799606   22.000
22                Mohamed Ali Cho    6.552325   15.000
23                         Juanmi    1.712194    2.000
24                           Pepe    2.013943   22.000
25                 Nicolo Zaniolo    4.927981   12.000
26                    Bruno Messi    0.556592    0.700
27                    Igor Paixao   20.859832   35.000
28           Nuno Goncalo Moreira    3.701600    3.000
29                     Joao Felix    5.184624   20.000
30                          Portu    1.995614    1.800
31                Florian Thauvin   14.301260    5.000
32                   Danel Sinani    3.728630    1.500
33                  Ronaldo Cesar    3.408291    4.000
34                  Mamadou Sylla    2.350430    1.200
35                   Charly Keita    1.091859    0.550
36              Saeid Saharkhizan    2.159300    1.000
37                   Ruben Macedo    1.110524    0.450
38                Bazoumana Toure    2.595811    9.000
39                 Egas Cacintura    2.849751    1.000
40              Youssoufa Moukoko    3.782511   10.000
41                Chemsdine Talbi    2.448305    8.000
42                           Raul    3.047012    3.000
43             Moritz Broschinski    4.124600    2.000
44                 Brian Mansilla    0.631083    1.000
45                  Mickael Biron    0.545348    1.200
46               Nokkvi Thorisson    0.979333    0.600
47                 Johan Manzambi    3.068224    8.000
48             William Balikwisha    0.972093    1.200
49           Abbosbek Fayzullayev    3.493541    8.000
50                          Jason    2.712473    2.500
51                 Sandro Ramirez    8.726433    2.500
52                     Elif Elmas    3.272867   14.000
53                 Gabri Martinez    2.633068    4.000
54               Viktor Tsyhankov    4.274705   18.000
55                           Suso    1.961076    1.500
56                  Edon Zhegrova    3.296846   25.000
57                  Ibrahim Mbaye    2.770128    3.000
58            Sebastiano Esposito    9.444397    8.500
59               Denilho Cleonise    0.609413    0.400
60             Baptiste Guillaume    0.444133    0.450
61               Erencan Yardimci    1.299553    2.500
62                 Fabio Carvalho   12.433221   14.000
63                  Junior Kadile    1.766023    0.650
64                 Carlos Eduardo    0.538792    0.700
65                 Evann Guessand   31.507545   25.000
66                 Jacob Trenskow    1.604729    4.000
67                 Jonathan Ikone    3.464713    7.000
68                    Leon Bailey   11.326526   28.000
69                   Mario Engels    1.392187    0.500
70         Alessandro Gabrielloni    4.484148    0.850
71                  Mexx Meerdink    2.000592    8.000
72                       Raphinha   55.235216   90.000
73                  Thijs Oosting    0.488220    0.500
74                           Jota    1.663528    8.000
75                Mario Balotelli    1.530138    0.500
76                 Othmane Maamma    2.304833    0.600
77                 Yanis Begraoui    4.151847    3.500
78                     Joao Pedro   59.145896   50.000
79                    Pablo Duran    4.329080    3.500
80                    Bukayo Saka   86.871720  150.000
81                 Osame Sahraoui    4.150847   12.000
82                        Willian    5.045655    0.750
83                 Florinel Coman    2.272063    5.000
84                 Alex Berenguer    9.550707    9.000
85                  Jovane Cabral    1.196834    1.000
86                 Wilson Odobert    7.237353   20.000
87                 Kacper Kostorz    0.831411    0.450
88               Christantus Uche    7.654786   15.000
89                  Alvaro Morata    4.045223   11.000
90                  Filip Krastev    2.448835    4.000
91               Marcus Tavernier   30.592943   18.000
92                     Tim Skarke    2.692634    2.000
93                   Adama Traore   31.124114    9.000
94                   Steve Mounie    2.330715    2.000
95             Gabriel Martinelli   47.055818   55.000
96                  Sontje Hansen    1.884778    4.000
97                   Joao Marques    0.721167    3.000
98               Mohammed Fuseini    1.952992    4.500
99                Ignatius Ganago    1.233837    2.000
100                    Amar Ahmed    0.491543    0.450
101                 Morgan Rogers   96.965406   55.000
102            Kingstone Mutandwa    1.533829    0.600
103                    Alieu Njie    2.537345    2.500
104                  Thibo Somers    2.482153    2.500
105                  Abde Rebbach    1.125139    0.700
106              Valentin Mihaila    4.748925    3.000
107                   Alex Millan    0.539639    0.500
108                Kirill Danilin    1.146920    0.700
109                    Jonas Wind    7.777430   12.000
110                Yussuf Poulsen    2.864783    5.000
111                Keito Nakamura   14.084266    8.000
112           Remy Labeau Lascary    2.336628    2.000
113                 Simon Adingra   12.057552   28.000
114            Facundo Buonanotte   21.562185   20.000
115            Vyacheslav Grulyov    1.534936    1.200
116              Anis Hadj Moussa    2.205018   14.000
117               Francisco Perez    1.216134    3.000
118                   Brahim Diaz    5.549157   40.000
119            Muhammed Gumuskaya    0.508893    0.350
120        Alexander Bernhardsson    6.214866    3.000
121                 Abdallah Sima    7.474542    9.000
122                   Matheusinho    0.544290    1.500
123                     Rui Costa    1.241483    0.600
124                    Alex Iwobi   72.369047   28.000
125              Eldor Shomurodov    7.915803    5.000
126                Joshua Zirkzee   14.333366   30.000
127              Oliver Edvardsen    3.448148    5.000
128                 Jack Grealish   10.460203   28.000
129                  Ruben Garcia    4.719076    2.000
130             Arnaud Kalimuendo   25.948917   22.000
131                 Jonathan Rowe    6.279212   12.000
132                  Marco Matias    1.632594    0.100
133                   Lee Kang-in    9.217776   25.000
134               Bernard Berisha    0.693837    0.600
135              Munir El Haddadi    3.036224    1.500
136                   Dylan Mbayo    2.202606    2.000
137                    Iago Aspas   11.975102    2.000
138                Sergiu Perciun    1.636481    1.500
139               Jeremy Agbonifo    1.927653    5.000
140                Thomas Buitink    0.367637    0.400
141         Arkaitz Mariezkurrena    2.428863    0.700
142                  Ilyes Housni    1.261541    1.500
143                Sana Fernandes    0.442700    0.700
144                   Deniz Undav   15.464313   20.000
145                 Ismael Konate    2.938141    1.000
146                 Carlos Martin    3.440332    2.800
147              Victor Edvardsen    3.840721    1.300
148                  Takuma Asano    2.327334    2.500
149                  Noah Adedeji    2.754150    4.500
150               Hyllarion Goore    0.671205    0.600
151                     Junya Ito    4.304489    6.000
152                Bryan Zaragoza    5.377646   12.000
153                  David Brooks   12.632999   10.000
154                 Omar Marmoush   82.401899   75.000
155                  Jarrod Bowen  180.443671   40.000
156                   Jose Arnaiz    1.154792    1.500
157            Michael Folorunsho    2.167159    6.000
158                          Dudu    1.576440    0.600
159                  Younes Namli    1.339818    1.300
160               Riccardo Sottil    3.427596    5.000
161                  Armindo Sieb    3.061484    3.000
162                 Loum Tchaouna    2.727998   10.000
163                   Nuno Santos    2.862481    2.500
164                         Bruma    5.262260    7.000
165             Maghnes Akliouche   15.456600   45.000
166                Jann-Fiete Arp    2.753575    0.800
167                     Enes Unal   14.468274   10.000
168                Mats Seuntjens    0.716849    0.550
169               Sammie Szmodics   13.155302   10.000
170              Augustine Boakye    2.820387    2.500
171                  Mathis Suray    0.631425    1.500
172                 Paulinho Boia    1.246147    0.700
173              Henrique Pereira    0.895312    0.800
174                    Ante Erceg    0.342701    0.100
175                         Pedro    9.982838    1.000
176                   Tiago Tomas    7.812668   12.000
177             Christian Pulisic   28.670869   50.000
178                 Jizz Hornkamp    1.587391    1.300
179                 Ismael Gharbi    2.159767    7.500
180                       Rodrygo    9.579865   90.000
181                Adam Armstrong   12.169194   12.000
182                 Karim Adeyemi   11.964175   45.000
183               Florent Muslija    1.369512    1.800
184                  Kaj de Rooij    0.751981    0.350
185                    Ricardinho    1.919861    1.000
186                  Chris Lokesa    0.800850    0.400
187                    Iker Bravo    3.068818    3.000
188                  Samuel Bamba    1.258608    0.500
189                Emmanuel Sabbi    1.767381    1.500
190                   Desire Doue   13.545441   90.000
191                    Danny Ings   14.700508    6.000
192                  Zito Luvumbo    3.740066    5.000
193             Adrian Benedyczak    1.575270    4.500
194              Williot Swedberg    6.786672    5.000
195                  Ruben Vargas    1.756176    7.000
196                Goncalo Borges    1.533392    5.000
197                   Timo Werner   10.272546    7.000
198                   Che Nunnely    0.591670    0.500
199                  Koji Miyoshi    1.913788    1.500
200                 Marco Asensio   33.066417   20.000
201                  Kenan Yildiz   15.298844   50.000
202                Romano Postema    0.611411    0.450
203                     Dani Raba    9.379810    2.500
204                   Fuki Yamada    1.068473    0.700
205                   Marco Grull    4.593168    4.000
206              Tanguy Coulibaly    3.504957    1.500
207                Bobby Adekanye    0.488152    0.650
208                 Elton Kabangu    0.508106    0.600
209                 Samuel Lobato    0.540368    0.200
210                         Alfon    6.481196    5.000
211                 Nicolas Viola    4.063715    1.000
212               Abde Ezzalzouli    7.213784   12.000
213                  Paulo Dybala   10.823417    8.000
214                   Jack Clarke   11.858132   15.000
215                 Ernest Nuamah    3.579244   15.000
216         Aleksandr Lomovitskiy    0.601245    0.500
217                  Alexis Flips    0.592058    1.000
218            Adriano Bertaccini   15.972148    4.500
219                Florian Sotoca    4.148875    2.000
220             Bahereba Guirassy    2.345258    1.000
221                  Faiz Mattoir    0.333894    0.200
222                 Michael Olise  106.772646  100.000
223                        Thiago    5.088848   18.000
224                     Fer Lopez    1.906162    5.000
225                    Alan Minda    1.447506    3.000
226           Francisco Conceicao    6.770016   28.000
227                    Raul Paula    0.550419    0.600
228                  Matt Garbett    0.423824    0.400
229                Carlos Alcaraz   19.908375   14.000
230               Franjo Ivanovic   21.697005   13.000
231           Alireza Jahanbakhsh    0.985037    1.500
232                 Eddie Nketiah   20.001390   18.000
233             Lorenzo Venturino    4.140142    1.500
234              Christian Kouame    3.255060    4.000
235                    Milan Smit    1.196978    1.500
236               Mateo Cassierra    3.570746   10.000
237             Gianluca Lapadula    1.773907    0.750
238          Tiago Fonseca Morais    2.212865    3.000
239               Alberto Moleiro    7.839524   25.000
240                  Harry Wilson   25.323379   15.000
241              Kerem Akturkoglu   12.619276   24.000
242                    Jota Silva   12.439511   15.000
243                  Issa Soumare   10.700156    2.000
244                    Jaime Mata    1.388822    0.400
245                   Scott Banks    1.269311    0.500
246                    Ramon Sosa    8.423726   12.000
247               Christos Tzolis   20.559484   25.000
248                  Koen Kostons    0.768610    0.600
249              Antoine Colassin    2.375041    0.750
250                Tijjani Noslin    3.915327    7.500
251                   Leo Scienza    7.258581    3.000
252                Mohammed Kudus   38.687050   45.000
253                   Vando Felix    0.689808    1.000
254               Joselpho Barnes    0.529375    0.200
255             Miliano Jonathans    0.317306    0.900
256                  Lameck Banda    2.552851    4.500
257                    Dennis Man    9.874908   10.000
258              Oladapo Afolayan    4.267659    4.000
259          Mathias Pereira Lage    8.507189    2.500
260              Odysseus Velanas    0.681354    0.550
261               Zinedine Ferhat    2.104929    1.000
262                  Helio Varela    0.868735    1.200
263               Mamadou Diakhon    3.084026    3.000
264                 Said Benrahma    2.699638   10.000
265                  Yusupha Njie    0.717709    0.800
266                   Levi Garcia    0.987328   12.000
267               Stefan Schimmer    1.355584    0.500
268                 Yassir Zabiri    1.771194    0.600
269      D'Margio Wright-Phillips    0.521604    0.250
270                    Ritsu Doan   20.277336   25.000
271              Razhab Magomedov    0.775296    0.600
272                  Lucas Michal    1.307899    0.500
273              Andrew Hjulsager    0.847431    0.600
274                  Danny Loader    1.589898    4.000
275                    Basar Onal    0.821814    0.700
276               Raheem Sterling    7.738706   10.000
277             Gabriel Strefezza   16.558737    6.000
278                  Kiko Bondoso    1.231880    0.800
279                 Gboly Ariyibi    0.580165    0.200
280                 Nelson Weiper    4.387901   10.000
281              Samuel Chukwueze    4.300065   10.000
282                 Ethan Nwaneri   15.216068   55.000
283                         Savio   48.264512   50.000
284              Jan-Niklas Beste    0.900434    7.000
285                 Otso Liimatta    0.527821    0.800
286           Samuel Iling-Junior    2.893322   10.000
287                  Gerson Sousa    0.531647    1.300
288               Jeremy Livolant    2.241800    1.500
289                  Serge Gnabry    9.880084   22.000
290                 Nick Doodeman    0.553124    0.400
291             Gaetano Oristanio    7.618500    6.000
292                   Solly March    4.875388    6.000
293                  Nicolas Pays    1.368130    0.700
294                 Ferran Jutglà    8.124035    8.000
295            Kamaldeen Sulemana   10.549948   13.000
296                Anthony Elanga   86.532765   42.000
297                   Lucas Holer    9.084247    3.000
298                Daniel Maldini    8.120469   10.000
299                   Abdon Prats    1.908796    1.200
300                   Konan N'dri    1.950287    1.400
301              Ruben Providence    0.527921    0.350
302              Gilson Benchimol    1.799138    0.700
303                  Helder Costa    0.696437    0.400
304                          Sala    0.554631    0.200
305              Mathieu Maertens    1.262061    1.800
306                Arnaut Danjuma    3.059236    4.000
307                  Kaoru Mitoma   60.285377   40.000
308              Mathias Fixelles    0.516022    0.300
309                  Tete Morente    5.807647    2.000
310            Alexander Jakobsen    0.300148    0.075
311             Antoine Griezmann    8.778177   18.000
312                Nick Woltemade   14.306057   30.000
313                  John Mercado    1.146124    2.500
314               Stefan Mitrovic    1.272537    1.500
315                  Adrian Blake    1.103832    0.750
316                     Dany Mota    5.991335    4.000
317                Joaquin Correa    3.983895    3.000
318              Mauro Luna Diale    0.859287    1.000
319              Giorgos Masouras    3.352143    2.000
320                 Alvaro Garcia    8.404111    2.000
321                Suf Podgoreanu    1.251233    0.850
322               Matteo Politano    6.807038   10.000
323                  Jeremy Sebas    1.332374    0.700
324                Benjamin Sesko   19.475679   70.000
325                 Morlaye Sylla    2.175679    2.500
326           Zuriko Davitashvili   22.689458   10.000
327             Morgan Guilavogui    5.992739    4.000
328           Miguel Puche Garcia    0.875907    0.400
329                Justin Njinmah    3.202598    7.000
330                  Jeff Ekhator    2.575168    5.000
331                   Adam Nhaili    0.813989    0.250
332        Younes Taha El Idrissi    0.329478    1.000
333               Jovan Mijatovic    1.107836    3.000
334                Ibrahima Wadji    1.297563    0.700
335                   Jeremy Doku   25.653893   50.000
336                      Vinicius    2.851150    2.500
337                   Patson Daka    7.967934    9.000
338              Lassine Sinayoko   11.624161    4.000
339                 Islam Slimani    0.771903    0.500
340                  Grejohn Kyei    0.757992    0.700
341               Steven Berghuis    1.087902    3.500
342            Matteo Cancellieri    3.829779    4.500
343                    Luka Jovic    2.678924    4.500
344              Valeri Tsarukyan    1.590527    0.350
345                 Shuto Machino   10.010376    5.000
346                       Ben Old    1.484155    0.700
347                    Ante Rebic    2.287797    1.000
348              Yunus Emre Konak    5.007920    4.500
349           Kristoffer Peterson    1.109541    0.800
350              Maximilian Beier    8.117835   25.000
351               Tidjany Chabrol    1.481986    0.500
352                 Oliver Antman    5.685730    6.000
353             Dailon Livramento    2.401571    0.800
354                   Adam Hlozek   13.708869   18.000
355                   Joshua King    8.778763    1.800
356                  Remy Cabella    2.890215    2.500
357                 Milos Lukovic    0.535204    5.000
358              Kornelius Hansen    1.211705    0.500
359                      Rafa Mir    2.446608    0.800
360                  Roy Kuijpers    0.324603    0.275
361                 Manuel Fuster    2.637659    1.500

<b>Модель 2.<br>Переменные: 'G+A', 'Ast', 'SoT', 'G+A-PK', '90s', 'Ast.1', 'Fld', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'</b>

In [41]:
X_train = X_train[['G+A', 'Ast', 'SoT', 'G+A-PK', '90s', 'Ast.1', 'Fld', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['G+A', 'Ast', 'SoT', 'G+A-PK', '90s', 'Ast.1', 'Fld', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [47]:
coeffs_df

               coeff
league_GB1  0.741435
SoT         0.427203
league_IT1  0.381107
league_FR1  0.277803
league_L1   0.276529
league_ES1  0.226258
G+A-PK      0.204598
league_NL1 -0.173222
Ast         0.160384
G+A         0.112886
Fld         0.105473
90s         0.058358
Ast.1      -0.023680
league_PO1  0.005553
league_RU1 -0.002526

In [48]:
metrics

            MAE       RMSE      MAPE        R2
test   4.904375   9.684149  0.786559  0.450282
train  5.342185  13.165542  0.824999  0.366956

In [49]:
comp_leftovers_test

                     Player  Value_pred  Value
0              Antonio Nusa    3.747776  28.00
1              Luis Vazquez    1.910895   2.50
2           Tristan Degreef    0.587454   2.00
3        Maximilian Breunig    1.852731   1.50
4                Kike Barja    1.413495   1.50
5           Pontus Almqvist    3.509293   2.50
6              Jacob Ramsey   12.134180  32.00
7            Luciano Gondou    3.993957  12.00
8            Issiaka Kamate    0.523586   0.75
9             Lucas Beltran    6.970824  18.00
10           Tomas Conechny    1.983334   1.80
11          Sheraldo Becker    2.917140   2.50
12         Anthony Descotte    0.468188   0.65
13            Marc Domenech    1.118928   1.00
14              John Yeboah    3.656377   2.80
15              Noah Okafor    2.522536  13.00
16             Nigel Thomas    0.704878   0.30
17  Gabriel Airton de Souza    1.269701   0.80
18            Conrad Harder    4.682125  24.00
19             Franco Cervi    1.019284   0.80
20         Soltmurad Bakaev    1.699521   0.70
21            Stanis Idumbo    1.982234   2.50
22              Sekou Koita    1.301730   3.50
23            Felix Correia    3.899390   4.00
24            Irvin Cardona    4.780332   2.50
25          Mason Greenwood   89.962558  40.00
26           Marin Ljubicic    2.321113   4.00
27         Marvin Pieringer    9.581013   5.50
28   Christopher Bonsu-Baah    2.889939   7.50
29         Jeremy Antonisse    0.745823   0.70
30             Sorba Thomas    2.407042   3.50
31             Breel Embolo    9.560892  12.00
32            Ibrahim Osman    1.020828  10.00
33                Bryan Gil    4.883076  15.00
34      Dardan Shabanhaxhaj    2.364137   1.20
35           Thorgan Hazard    1.234894   2.50
36                Juan Cruz    5.124776   5.00
37           Yaser Asprilla    2.945507  15.00
38             Rayan Cherki   21.425266  45.00
39           Anthony Gordon   49.430281  65.00
40    Gabriel Osei Misehouy    1.526284   1.00
41             Wahbi Khazri    2.529751   1.00
42            Luka Ivanusec    0.465578   3.50
43             Dario Poveda    1.254977   0.50
44      Andreas Schjelderup    1.631655  15.00
45             Lukas Nmecha    3.411335   3.00
46           El Bilal Toure    2.930083  15.00
47           Alfonso Trezza    2.605598   1.00
48         Gil Bastiao Dias    2.659233   1.50
49             Cisse Sandra    1.018353   1.00
50             Pedro Santos    0.563792   0.80
51               Robin Hack   12.727576  12.00
52              Jordan Ayew   16.841866   2.50
53           Erik Ahlstrand    1.203764   0.50
54         Mathis Lambourde    3.515974   0.80
55            Josue Casimir    5.716721   4.00
56             Angel Correa    3.799046  10.00
57              Vasco Lopes    1.749602   0.50
58            Juho Talvitie    0.733014   0.90
59             Dave Kwakman    0.593888   2.00
60               Sekou Mara    2.388969   5.00
61        Julien Duranville    1.403585   8.50
62             Max Svensson    1.764193   0.50
63            Anass Zaroury    3.929503   8.00
64         Bernardo Martins    2.059142   1.00
65              Luka Romero    1.027093   4.00
66              Kai Havertz   40.376141  65.00
67               Ayman Aiki    1.268767   0.40
68               Elias Saad    3.848361   4.00
69                     Caue    0.990441   0.80
70            Denis Makarov    1.371120   1.20
71         Oscar Pettersson    0.336717   0.50
72             Andre Inacio    2.155513   2.50
73         Vladislav Shitov    1.116308   0.80
74            Jamie Gittens   12.298679  50.00
75           Yusuf Kabadayi    3.417432   1.50
76    Allahyar Sayyadmanesh    4.415009   4.00
77         Nicolas Gonzalez    8.688676  24.00
78        Giacomo Raspadori    6.588146  25.00
79      Benedict Hollerbach    9.808189  12.00
80             Caio Santana    0.544425   0.10
81  Marcos Vinicios Sorriso    4.853873   5.00
82              Luka Tunjic    0.538810   0.45
83           Felipe Augusto    2.479199   2.20
84           Yankuba Minteh   28.061592  30.00
85           Andrea Colpani    4.376706   9.50
86              Frank Magri    5.962635   3.00
87          Vincent Janssen   14.790215   7.00
88         Miguel Rodriguez    2.413780   4.50
89           Abdoulay Diaby    1.210969   0.20
90                Keke Topp    4.992356   4.00
91        Francesco Camarda    1.607636  10.00
92       Callum Hudson-Odoi   23.934635  25.00
93             Jordi Mboula    1.061411   0.50

In [52]:
comp_leftovers_train

                           Player  Value_pred    Value
0                  Vincenzo Grifo   27.510818    6.000
1             Rifat Zhemaletdinov    1.489575    2.500
2                 Roger Fernandes    3.704442   22.000
3                     Gyrano Kerk    3.994239    3.000
4                 Musa Al-Taamari    4.374957    6.000
5                   Emilio Kehrer    0.849651    0.500
6              Albert Gudmundsson    5.832401   18.000
7                     Moses Simon   16.211570   12.000
8                   Michal Skoras    0.812585    2.500
9                  Sirlord Conteh    2.199063    1.500
10                  Ferran Torres   16.465749   40.000
11                  Ilias Sebaoui    0.956267    1.500
12                Josimar Alcocer    1.206484    2.200
13                  Ivan Sergeyev    4.937790    3.000
14                        Antoniu    1.712715    1.800
15   Lucas Vennegoor of Hesselink    0.338159    0.300
16                Jorge de Frutos    6.406377    4.000
17                  Paris Brunner    0.885548    1.500
18                   Adri Embarba    2.643121    1.200
19                    Lois Openda   27.904832   50.000
20                Lorenzo Colombo    9.397347    5.000
21          Crysencio Summerville    9.928578   22.000
22                Mohamed Ali Cho    6.717874   15.000
23                         Juanmi    1.707802    2.000
24                           Pepe    2.018863   22.000
25                 Nicolo Zaniolo    4.891544   12.000
26                    Bruno Messi    0.559650    0.700
27                    Igor Paixao   21.090487   35.000
28           Nuno Goncalo Moreira    3.501082    3.000
29                     Joao Felix    5.000255   20.000
30                          Portu    2.046594    1.800
31                Florian Thauvin   14.864672    5.000
32                   Danel Sinani    3.738143    1.500
33                  Ronaldo Cesar    3.284537    4.000
34                  Mamadou Sylla    2.455402    1.200
35                   Charly Keita    1.055080    0.550
36              Saeid Saharkhizan    2.139419    1.000
37                   Ruben Macedo    1.113065    0.450
38                Bazoumana Toure    2.694134    9.000
39                 Egas Cacintura    2.837844    1.000
40              Youssoufa Moukoko    3.939327   10.000
41                Chemsdine Talbi    2.460061    8.000
42                           Raul    3.062326    3.000
43             Moritz Broschinski    4.002966    2.000
44                 Brian Mansilla    0.635366    1.000
45                  Mickael Biron    0.533226    1.200
46               Nokkvi Thorisson    1.007866    0.600
47                 Johan Manzambi    2.970330    8.000
48             William Balikwisha    1.033782    1.200
49           Abbosbek Fayzullayev    3.341874    8.000
50                          Jason    2.905949    2.500
51                 Sandro Ramirez    8.737022    2.500
52                     Elif Elmas    3.260712   14.000
53                 Gabri Martinez    2.797498    4.000
54               Viktor Tsyhankov    4.245325   18.000
55                           Suso    1.957325    1.500
56                  Edon Zhegrova    3.431704   25.000
57                  Ibrahim Mbaye    2.735838    3.000
58            Sebastiano Esposito    9.673078    8.500
59               Denilho Cleonise    0.599887    0.400
60             Baptiste Guillaume    0.441587    0.450
61               Erencan Yardimci    1.327661    2.500
62                 Fabio Carvalho   12.341736   14.000
63                  Junior Kadile    1.704416    0.650
64                 Carlos Eduardo    0.529614    0.700
65                 Evann Guessand   30.535587   25.000
66                 Jacob Trenskow    1.588989    4.000
67                 Jonathan Ikone    3.382049    7.000
68                    Leon Bailey   11.231836   28.000
69                   Mario Engels    1.477541    0.500
70         Alessandro Gabrielloni    4.515701    0.850
71                  Mexx Meerdink    2.038119    8.000
72                       Raphinha   59.130019   90.000
73                  Thijs Oosting    0.499838    0.500
74                           Jota    1.702465    8.000
75                Mario Balotelli    1.529937    0.500
76                 Othmane Maamma    2.311394    0.600
77                 Yanis Begraoui    4.346064    3.500
78                     Joao Pedro   54.521034   50.000
79                    Pablo Duran    4.252945    3.500
80                    Bukayo Saka   90.001660  150.000
81                 Osame Sahraoui    3.898737   12.000
82                        Willian    5.041506    0.750
83                 Florinel Coman    2.250171    5.000
84                 Alex Berenguer    9.721206    9.000
85                  Jovane Cabral    1.145008    1.000
86                 Wilson Odobert    7.147646   20.000
87                 Kacper Kostorz    0.820334    0.450
88               Christantus Uche    8.014450   15.000
89                  Alvaro Morata    4.376766   11.000
90                  Filip Krastev    2.250120    4.000
91               Marcus Tavernier   30.658639   18.000
92                     Tim Skarke    2.807980    2.000
93                   Adama Traore   30.129929    9.000
94                   Steve Mounie    2.275731    2.000
95             Gabriel Martinelli   48.107684   55.000
96                  Sontje Hansen    1.807418    4.000
97                   Joao Marques    0.705995    3.000
98               Mohammed Fuseini    2.096257    4.500
99                Ignatius Ganago    1.239236    2.000
100                    Amar Ahmed    0.485383    0.450
101                 Morgan Rogers   83.565823   55.000
102            Kingstone Mutandwa    1.527185    0.600
103                    Alieu Njie    2.554477    2.500
104                  Thibo Somers    2.541762    2.500
105                  Abde Rebbach    1.111426    0.700
106              Valentin Mihaila    4.529527    3.000
107                   Alex Millan    0.543076    0.500
108                Kirill Danilin    1.193571    0.700
109                    Jonas Wind    7.214061   12.000
110                Yussuf Poulsen    2.790436    5.000
111                Keito Nakamura   14.049367    8.000
112           Remy Labeau Lascary    2.542607    2.000
113                 Simon Adingra   12.236213   28.000
114            Facundo Buonanotte   21.086634   20.000
115            Vyacheslav Grulyov    1.483005    1.200
116              Anis Hadj Moussa    2.254851   14.000
117               Francisco Perez    1.171286    3.000
118                   Brahim Diaz    5.028182   40.000
119            Muhammed Gumuskaya    0.499324    0.350
120        Alexander Bernhardsson    5.974038    3.000
121                 Abdallah Sima    7.299184    9.000
122                   Matheusinho    0.538358    1.500
123                     Rui Costa    1.305404    0.600
124                    Alex Iwobi   70.621221   28.000
125              Eldor Shomurodov    7.684577    5.000
126                Joshua Zirkzee   13.749831   30.000
127              Oliver Edvardsen    3.393245    5.000
128                 Jack Grealish   10.148993   28.000
129                  Ruben Garcia    4.969214    2.000
130             Arnaud Kalimuendo   25.696966   22.000
131                 Jonathan Rowe    6.414995   12.000
132                  Marco Matias    1.719790    0.100
133                   Lee Kang-in    8.945901   25.000
134               Bernard Berisha    0.710841    0.600
135              Munir El Haddadi    3.070550    1.500
136                   Dylan Mbayo    2.243776    2.000
137                    Iago Aspas   11.183239    2.000
138                Sergiu Perciun    1.632714    1.500
139               Jeremy Agbonifo    1.939379    5.000
140                Thomas Buitink    0.374977    0.400
141         Arkaitz Mariezkurrena    2.356802    0.700
142                  Ilyes Housni    1.254617    1.500
143                Sana Fernandes    0.441877    0.700
144                   Deniz Undav   15.685067   20.000
145                 Ismael Konate    2.926717    1.000
146                 Carlos Martin    3.356078    2.800
147              Victor Edvardsen    3.652808    1.300
148                  Takuma Asano    2.317641    2.500
149                  Noah Adedeji    2.759747    4.500
150               Hyllarion Goore    0.672800    0.600
151                     Junya Ito    4.913402    6.000
152                Bryan Zaragoza    5.529244   12.000
153                  David Brooks   12.394386   10.000
154                 Omar Marmoush   88.374176   75.000
155                  Jarrod Bowen  180.810045   40.000
156                   Jose Arnaiz    1.186384    1.500
157            Michael Folorunsho    2.118137    6.000
158                          Dudu    1.560593    0.600
159                  Younes Namli    1.329411    1.300
160               Riccardo Sottil    3.389493    5.000
161                  Armindo Sieb    3.224009    3.000
162                 Loum Tchaouna    2.696715   10.000
163                   Nuno Santos    2.723710    2.500
164                         Bruma    5.574382    7.000
165             Maghnes Akliouche   14.891299   45.000
166                Jann-Fiete Arp    2.694581    0.800
167                     Enes Unal   14.561205   10.000
168                Mats Seuntjens    0.720595    0.550
169               Sammie Szmodics   13.812044   10.000
170              Augustine Boakye    2.798587    2.500
171                  Mathis Suray    0.625702    1.500
172                 Paulinho Boia    1.237589    0.700
173              Henrique Pereira    0.879941    0.800
174                    Ante Erceg    0.355014    0.100
175                         Pedro   10.021448    1.000
176                   Tiago Tomas    7.435094   12.000
177             Christian Pulisic   27.815476   50.000
178                 Jizz Hornkamp    1.544171    1.300
179                 Ismael Gharbi    2.152775    7.500
180                       Rodrygo    8.847321   90.000
181                Adam Armstrong   12.683598   12.000
182                 Karim Adeyemi   11.427103   45.000
183               Florent Muslija    1.347768    1.800
184                  Kaj de Rooij    0.751812    0.350
185                    Ricardinho    1.947566    1.000
186                  Chris Lokesa    0.782821    0.400
187                    Iker Bravo    3.048899    3.000
188                  Samuel Bamba    1.266053    0.500
189                Emmanuel Sabbi    1.744388    1.500
190                   Desire Doue   12.812477   90.000
191                    Danny Ings   14.466621    6.000
192                  Zito Luvumbo    4.054879    5.000
193             Adrian Benedyczak    1.578001    4.500
194              Williot Swedberg    6.613615    5.000
195                  Ruben Vargas    1.740996    7.000
196                Goncalo Borges    1.554209    5.000
197                   Timo Werner   10.702075    7.000
198                   Che Nunnely    0.587557    0.500
199                  Koji Miyoshi    1.887512    1.500
200                 Marco Asensio   32.964233   20.000
201                  Kenan Yildiz   15.051820   50.000
202                Romano Postema    0.604735    0.450
203                     Dani Raba    9.560558    2.500
204                   Fuki Yamada    1.070672    0.700
205                   Marco Grull    4.595526    4.000
206              Tanguy Coulibaly    3.362980    1.500
207                Bobby Adekanye    0.487451    0.650
208                 Elton Kabangu    0.506310    0.600
209                 Samuel Lobato    0.536552    0.200
210                         Alfon    6.357182    5.000
211                 Nicolas Viola    4.392450    1.000
212               Abde Ezzalzouli    6.670024   12.000
213                  Paulo Dybala   11.026250    8.000
214                   Jack Clarke   11.512633   15.000
215                 Ernest Nuamah    3.695960   15.000
216         Aleksandr Lomovitskiy    0.605478    0.500
217                  Alexis Flips    0.590488    1.000
218            Adriano Bertaccini   16.637725    4.500
219                Florian Sotoca    4.174614    2.000
220             Bahereba Guirassy    2.306037    1.000
221                  Faiz Mattoir    0.332515    0.200
222                 Michael Olise  102.214877  100.000
223                        Thiago    5.106407   18.000
224                     Fer Lopez    1.836212    5.000
225                    Alan Minda    1.394829    3.000
226           Francisco Conceicao    6.809225   28.000
227                    Raul Paula    0.535555    0.600
228                  Matt Garbett    0.421169    0.400
229                Carlos Alcaraz   19.254141   14.000
230               Franjo Ivanovic   21.910190   13.000
231           Alireza Jahanbakhsh    0.990645    1.500
232                 Eddie Nketiah   19.842700   18.000
233             Lorenzo Venturino    4.171024    1.500
234              Christian Kouame    3.209030    4.000
235                    Milan Smit    1.196247    1.500
236               Mateo Cassierra    3.509677   10.000
237             Gianluca Lapadula    1.773116    0.750
238          Tiago Fonseca Morais    2.080194    3.000
239               Alberto Moleiro    6.835283   25.000
240                  Harry Wilson   24.680227   15.000
241              Kerem Akturkoglu   13.199494   24.000
242                    Jota Silva   13.170083   15.000
243                  Issa Soumare   10.112680    2.000
244                    Jaime Mata    1.498231    0.400
245                   Scott Banks    1.242148    0.500
246                    Ramon Sosa    8.638023   12.000
247               Christos Tzolis   21.475508   25.000
248                  Koen Kostons    0.752382    0.600
249              Antoine Colassin    2.179746    0.750
250                Tijjani Noslin    3.810733    7.500
251                   Leo Scienza    7.341258    3.000
252                Mohammed Kudus   42.871926   45.000
253                   Vando Felix    0.666743    1.000
254               Joselpho Barnes    0.522572    0.200
255             Miliano Jonathans    0.319649    0.900
256                  Lameck Banda    2.557141    4.500
257                    Dennis Man    9.378154   10.000
258              Oladapo Afolayan    4.360739    4.000
259          Mathias Pereira Lage    8.319312    2.500
260              Odysseus Velanas    0.696073    0.550
261               Zinedine Ferhat    2.150800    1.000
262                  Helio Varela    0.866047    1.200
263               Mamadou Diakhon    2.980927    3.000
264                 Said Benrahma    2.828178   10.000
265                  Yusupha Njie    0.739177    0.800
266                   Levi Garcia    0.984081   12.000
267               Stefan Schimmer    1.346248    0.500
268                 Yassir Zabiri    1.773193    0.600
269      D'Margio Wright-Phillips    0.507673    0.250
270                    Ritsu Doan   19.440420   25.000
271              Razhab Magomedov    0.865142    0.600
272                  Lucas Michal    1.292894    0.500
273              Andrew Hjulsager    0.834826    0.600
274                  Danny Loader    1.558083    4.000
275                    Basar Onal    0.850946    0.700
276               Raheem Sterling    7.942707   10.000
277             Gabriel Strefezza   15.788779    6.000
278                  Kiko Bondoso    1.185761    0.800
279                 Gboly Ariyibi    0.588077    0.200
280                 Nelson Weiper    4.483569   10.000
281              Samuel Chukwueze    4.384222   10.000
282                 Ethan Nwaneri   16.150129   55.000
283                         Savio   46.604430   50.000
284              Jan-Niklas Beste    0.907362    7.000
285                 Otso Liimatta    0.521254    0.800
286           Samuel Iling-Junior    2.911364   10.000
287                  Gerson Sousa    0.529263    1.300
288               Jeremy Livolant    2.349080    1.500
289                  Serge Gnabry    9.985297   22.000
290                 Nick Doodeman    0.562298    0.400
291             Gaetano Oristanio    7.817102    6.000
292                   Solly March    5.073305    6.000
293                  Nicolas Pays    1.342792    0.700
294                 Ferran Jutglà    8.277463    8.000
295            Kamaldeen Sulemana   10.291759   13.000
296                Anthony Elanga  102.366271   42.000
297                   Lucas Holer    8.790798    3.000
298                Daniel Maldini    7.912030   10.000
299                   Abdon Prats    1.851917    1.200
300                   Konan N'dri    1.887716    1.400
301              Ruben Providence    0.524596    0.350
302              Gilson Benchimol    1.825326    0.700
303                  Helder Costa    0.686486    0.400
304                          Sala    0.547609    0.200
305              Mathieu Maertens    1.309863    1.800
306                Arnaut Danjuma    3.502658    4.000
307                  Kaoru Mitoma   57.946425   40.000
308              Mathias Fixelles    0.505521    0.300
309                  Tete Morente    5.406238    2.000
310            Alexander Jakobsen    0.304882    0.075
311             Antoine Griezmann    9.614531   18.000
312                Nick Woltemade   13.730783   30.000
313                  John Mercado    1.209055    2.500
314               Stefan Mitrovic    1.265797    1.500
315                  Adrian Blake    1.090918    0.750
316                     Dany Mota    5.951949    4.000
317                Joaquin Correa    3.928375    3.000
318              Mauro Luna Diale    0.844923    1.000
319              Giorgos Masouras    3.723731    2.000
320                 Alvaro Garcia    9.054647    2.000
321                Suf Podgoreanu    1.248794    0.850
322               Matteo Politano    7.378389   10.000
323                  Jeremy Sebas    1.342513    0.700
324                Benjamin Sesko   20.479452   70.000
325                 Morlaye Sylla    1.944444    2.500
326           Zuriko Davitashvili   21.316839   10.000
327             Morgan Guilavogui    6.048314    4.000
328           Miguel Puche Garcia    0.871106    0.400
329                Justin Njinmah    3.454167    7.000
330                  Jeff Ekhator    2.575774    5.000
331                   Adam Nhaili    0.790735    0.250
332        Younes Taha El Idrissi    0.330955    1.000
333               Jovan Mijatovic    1.083072    3.000
334                Ibrahima Wadji    1.324263    0.700
335                   Jeremy Doku   25.708107   50.000
336                      Vinicius    2.800249    2.500
337                   Patson Daka    7.928019    9.000
338              Lassine Sinayoko   11.746206    4.000
339                 Islam Slimani    0.784627    0.500
340                  Grejohn Kyei    0.764374    0.700
341               Steven Berghuis    1.135696    3.500
342            Matteo Cancellieri    3.686749    4.500
343                    Luka Jovic    2.615893    4.500
344              Valeri Tsarukyan    1.544926    0.350
345                 Shuto Machino   10.013436    5.000
346                       Ben Old    1.450782    0.700
347                    Ante Rebic    2.432397    1.000
348              Yunus Emre Konak    4.993228    4.500
349           Kristoffer Peterson    1.160712    0.800
350              Maximilian Beier    8.169170   25.000
351               Tidjany Chabrol    1.434689    0.500
352                 Oliver Antman    5.547239    6.000
353             Dailon Livramento    2.538000    0.800
354                   Adam Hlozek   12.988217   18.000
355                   Joshua King    8.551917    1.800
356                  Remy Cabella    2.882827    2.500
357                 Milos Lukovic    0.549009    5.000
358              Kornelius Hansen    1.174473    0.500
359                      Rafa Mir    2.415344    0.800
360                  Roy Kuijpers    0.324997    0.275
361                 Manuel Fuster    2.564928    1.500

<b>Модель 3.<br>Переменные: 'Gls', 'Ast', 'SoT', 'G+A-PK', '90s', 'Fld', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'</b>

In [78]:
X_train = X_train[['Gls', 'Ast', 'SoT', 'G+A-PK', '90s', 'Fld', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Gls', 'Ast', 'SoT', 'G+A-PK', '90s', 'Fld', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [73]:
coeffs_df

               coeff
league_GB1  0.759883
league_IT1  0.425914
SoT         0.398776
Age        -0.308773
league_L1   0.302773
league_ES1  0.294168
league_FR1  0.274001
Ast         0.213958
league_NL1 -0.170033
G+A-PK      0.143286
Gls         0.127006
90s         0.112403
Fld         0.053246
league_PO1  0.020333
league_RU1  0.016961

In [82]:
metrics

            MAE       RMSE      MAPE        R2
test   4.931770  10.741656  0.804759  0.323668
train  5.066766  12.299104  0.741155  0.447537

In [63]:
comp_leftovers_test

                     Player  Value_pred  Value
0              Antonio Nusa    6.280616  28.00
1              Luis Vazquez    1.938061   2.50
2           Tristan Degreef    0.829723   2.00
3        Maximilian Breunig    2.096281   1.50
4                Kike Barja    1.362094   1.50
5           Pontus Almqvist    3.651289   2.50
6              Jacob Ramsey   13.810790  32.00
7            Luciano Gondou    4.442946  12.00
8            Issiaka Kamate    0.807218   0.75
9             Lucas Beltran    8.347471  18.00
10           Tomas Conechny    2.054001   1.80
11          Sheraldo Becker    2.367354   2.50
12         Anthony Descotte    0.626488   0.65
13            Marc Domenech    2.178913   1.00
14              John Yeboah    4.056408   2.80
15              Noah Okafor    2.753769  13.00
16             Nigel Thomas    0.793717   0.30
17  Gabriel Airton de Souza    0.902970   0.80
18            Conrad Harder    6.072813  24.00
19             Franco Cervi    0.806635   0.80
20         Soltmurad Bakaev    1.853271   0.70
21            Stanis Idumbo    3.246932   2.50
22              Sekou Koita    1.351947   3.50
23            Felix Correia    4.495591   4.00
24            Irvin Cardona    4.587649   2.50
25          Mason Greenwood  115.353678  40.00
26           Marin Ljubicic    2.668951   4.00
27         Marvin Pieringer   10.385749   5.50
28   Christopher Bonsu-Baah    3.536040   7.50
29         Jeremy Antonisse    0.893221   0.70
30             Sorba Thomas    2.412110   3.50
31             Breel Embolo    7.089291  12.00
32            Ibrahim Osman    1.388415  10.00
33                Bryan Gil    6.111767  15.00
34      Dardan Shabanhaxhaj    2.809054   1.20
35           Thorgan Hazard    0.667516   2.50
36                Juan Cruz    6.671450   5.00
37           Yaser Asprilla    4.809099  15.00
38             Rayan Cherki   28.072929  45.00
39           Anthony Gordon   51.775123  65.00
40    Gabriel Osei Misehouy    2.542859   1.00
41             Wahbi Khazri    1.212541   1.00
42            Luka Ivanusec    0.419303   3.50
43             Dario Poveda    1.028058   0.50
44      Andreas Schjelderup    2.125968  15.00
45             Lukas Nmecha    3.003949   3.00
46           El Bilal Toure    3.333448  15.00
47           Alfonso Trezza    2.636783   1.00
48         Gil Bastiao Dias    2.126471   1.50
49             Cisse Sandra    1.475193   1.00
50             Pedro Santos    0.736746   0.80
51               Robin Hack   12.950311  12.00
52              Jordan Ayew    8.991147   2.50
53           Erik Ahlstrand    1.517474   0.50
54         Mathis Lambourde    5.043627   0.80
55            Josue Casimir    6.327131   4.00
56             Angel Correa    2.973303  10.00
57              Vasco Lopes    1.656878   0.50
58            Juho Talvitie    1.091001   0.90
59             Dave Kwakman    0.833876   2.00
60               Sekou Mara    2.635023   5.00
61        Julien Duranville    2.362117   8.50
62             Max Svensson    2.013874   0.50
63            Anass Zaroury    4.063061   8.00
64         Bernardo Martins    1.787473   1.00
65              Luka Romero    1.840387   4.00
66              Kai Havertz   40.239151  65.00
67               Ayman Aiki    1.820221   0.40
68               Elias Saad    3.860049   4.00
69                     Caue    1.201321   0.80
70            Denis Makarov    1.013481   1.20
71         Oscar Pettersson    0.339009   0.50
72             Andre Inacio    2.398270   2.50
73         Vladislav Shitov    1.519152   0.80
74            Jamie Gittens   18.032136  50.00
75           Yusuf Kabadayi    3.787810   1.50
76    Allahyar Sayyadmanesh    4.667609   4.00
77         Nicolas Gonzalez    7.905640  24.00
78        Giacomo Raspadori    7.059853  25.00
79      Benedict Hollerbach   11.696664  12.00
80             Caio Santana    0.764509   0.10
81  Marcos Vinicios Sorriso    5.256816   5.00
82              Luka Tunjic    0.816438   0.45
83           Felipe Augusto    3.141139   2.20
84           Yankuba Minteh   42.241130  30.00
85           Andrea Colpani    4.523304   9.50
86              Frank Magri    5.633295   3.00
87          Vincent Janssen    8.734989   7.00
88         Miguel Rodriguez    2.752110   4.50
89           Abdoulay Diaby    0.625520   0.20
90                Keke Topp    5.997343   4.00
91        Francesco Camarda    3.353084  10.00
92       Callum Hudson-Odoi   28.378749  25.00
93             Jordi Mboula    1.012837   0.50

In [64]:
comp_leftovers_train

                           Player  Value_pred    Value
0                  Vincenzo Grifo   18.894152    6.000
1             Rifat Zhemaletdinov    1.241305    2.500
2                 Roger Fernandes    5.605908   22.000
3                     Gyrano Kerk    2.939458    3.000
4                 Musa Al-Taamari    3.297011    6.000
5                   Emilio Kehrer    0.985541    0.500
6              Albert Gudmundsson    5.311651   18.000
7                     Moses Simon   11.354530   12.000
8                   Michal Skoras    0.775369    2.500
9                  Sirlord Conteh    1.753462    1.500
10                  Ferran Torres   18.158203   40.000
11                  Ilias Sebaoui    1.139226    1.500
12                Josimar Alcocer    1.567213    2.200
13                  Ivan Sergeyev    3.959849    3.000
14                        Antoniu    2.574395    1.800
15   Lucas Vennegoor of Hesselink    0.527294    0.300
16                Jorge de Frutos    6.554182    4.000
17                  Paris Brunner    1.288546    1.500
18                   Adri Embarba    1.785280    1.200
19                    Lois Openda   26.599725   50.000
20                Lorenzo Colombo   12.415216    5.000
21          Crysencio Summerville   11.505894   22.000
22                Mohamed Ali Cho    8.297932   15.000
23                         Juanmi    1.216895    2.000
24                           Pepe    1.669418   22.000
25                 Nicolo Zaniolo    4.546349   12.000
26                    Bruno Messi    0.463388    0.700
27                    Igor Paixao   21.391472   35.000
28           Nuno Goncalo Moreira    3.243504    3.000
29                     Joao Felix    5.279828   20.000
30                          Portu    1.348214    1.800
31                Florian Thauvin   10.010600    5.000
32                   Danel Sinani    3.199829    1.500
33                  Ronaldo Cesar    3.910975    4.000
34                  Mamadou Sylla    2.005064    1.200
35                   Charly Keita    0.943649    0.550
36              Saeid Saharkhizan    2.980657    1.000
37                   Ruben Macedo    0.834971    0.450
38                Bazoumana Toure    4.523850    9.000
39                 Egas Cacintura    2.432694    1.000
40              Youssoufa Moukoko    4.593364   10.000
41                Chemsdine Talbi    3.388651    8.000
42                           Raul    3.764072    3.000
43             Moritz Broschinski    4.614381    2.000
44                 Brian Mansilla    0.766612    1.000
45                  Mickael Biron    0.454018    1.200
46               Nokkvi Thorisson    0.766104    0.600
47                 Johan Manzambi    4.477290    8.000
48             William Balikwisha    0.957391    1.200
49           Abbosbek Fayzullayev    4.650418    8.000
50                          Jason    1.814714    2.500
51                 Sandro Ramirez    7.243400    2.500
52                     Elif Elmas    3.880907   14.000
53                 Gabri Martinez    3.468874    4.000
54               Viktor Tsyhankov    4.505118   18.000
55                           Suso    1.462868    1.500
56                  Edon Zhegrova    3.051688   25.000
57                  Ibrahim Mbaye    4.571883    3.000
58            Sebastiano Esposito   12.464283    8.500
59               Denilho Cleonise    0.708582    0.400
60             Baptiste Guillaume    0.295703    0.450
61               Erencan Yardimci    1.672910    2.500
62                 Fabio Carvalho   14.874876   14.000
63                  Junior Kadile    2.242375    0.650
64                 Carlos Eduardo    0.690385    0.700
65                 Evann Guessand   31.100720   25.000
66                 Jacob Trenskow    1.810707    4.000
67                 Jonathan Ikone    3.189929    7.000
68                    Leon Bailey   10.063238   28.000
69                   Mario Engels    0.951608    0.500
70         Alessandro Gabrielloni    2.711025    0.850
71                  Mexx Meerdink    2.277642    8.000
72                       Raphinha   63.323673   90.000
73                  Thijs Oosting    0.506535    0.500
74                           Jota    1.495841    8.000
75                Mario Balotelli    0.877695    0.500
76                 Othmane Maamma    3.330521    0.600
77                 Yanis Begraoui    5.201047    3.500
78                     Joao Pedro   67.562005   50.000
79                    Pablo Duran    5.562330    3.500
80                    Bukayo Saka  102.136628  150.000
81                 Osame Sahraoui    4.162803   12.000
82                        Willian    2.358864    0.750
83                 Florinel Coman    2.030710    5.000
84                 Alex Berenguer    8.425760    9.000
85                  Jovane Cabral    0.989058    1.000
86                 Wilson Odobert   11.262508   20.000
87                 Kacper Kostorz    0.764249    0.450
88               Christantus Uche   11.433499   15.000
89                  Alvaro Morata    2.840900   11.000
90                  Filip Krastev    2.575459    4.000
91               Marcus Tavernier   29.692478   18.000
92                     Tim Skarke    2.409733    2.000
93                   Adama Traore   22.738337    9.000
94                   Steve Mounie    1.589492    2.000
95             Gabriel Martinelli   57.803466   55.000
96                  Sontje Hansen    2.131398    4.000
97                   Joao Marques    0.846162    3.000
98               Mohammed Fuseini    2.367558    4.500
99                Ignatius Ganago    1.136646    2.000
100                    Amar Ahmed    0.645269    0.450
101                 Morgan Rogers  106.865454   55.000
102            Kingstone Mutandwa    2.179941    0.600
103                    Alieu Njie    3.956309    2.500
104                  Thibo Somers    2.399114    2.500
105                  Abde Rebbach    1.267810    0.700
106              Valentin Mihaila    5.017980    3.000
107                   Alex Millan    0.567429    0.500
108                Kirill Danilin    1.612658    0.700
109                    Jonas Wind    7.339364   12.000
110                Yussuf Poulsen    1.703896    5.000
111                Keito Nakamura   15.831420    8.000
112           Remy Labeau Lascary    2.999664    2.000
113                 Simon Adingra   15.280323   28.000
114            Facundo Buonanotte   31.045605   20.000
115            Vyacheslav Grulyov    1.419048    1.200
116              Anis Hadj Moussa    2.675887   14.000
117               Francisco Perez    1.793553    3.000
118                   Brahim Diaz    5.733692   40.000
119            Muhammed Gumuskaya    0.534351    0.350
120        Alexander Bernhardsson    5.874491    3.000
121                 Abdallah Sima    7.260210    9.000
122                   Matheusinho    0.480536    1.500
123                     Rui Costa    0.943615    0.600
124                    Alex Iwobi   62.398153   28.000
125              Eldor Shomurodov    5.828338    5.000
126                Joshua Zirkzee   15.894656   30.000
127              Oliver Edvardsen    2.798594    5.000
128                 Jack Grealish    7.382130   28.000
129                  Ruben Garcia    3.816750    2.000
130             Arnaud Kalimuendo   32.401783   22.000
131                 Jonathan Rowe    6.959839   12.000
132                  Marco Matias    0.724487    0.100
133                   Lee Kang-in    9.277967   25.000
134               Bernard Berisha    0.411668    0.600
135              Munir El Haddadi    2.448376    1.500
136                   Dylan Mbayo    2.544455    2.000
137                    Iago Aspas    5.638326    2.000
138                Sergiu Perciun    2.890131    1.500
139               Jeremy Agbonifo    2.815851    5.000
140                Thomas Buitink    0.374246    0.400
141         Arkaitz Mariezkurrena    3.648244    0.700
142                  Ilyes Housni    1.795606    1.500
143                Sana Fernandes    0.678299    0.700
144                   Deniz Undav   12.243075   20.000
145                 Ismael Konate    4.918136    1.000
146                 Carlos Martin    4.580305    2.800
147              Victor Edvardsen    2.998757    1.300
148                  Takuma Asano    1.920927    2.500
149                  Noah Adedeji    3.389946    4.500
150               Hyllarion Goore    1.036728    0.600
151                     Junya Ito    3.051268    6.000
152                Bryan Zaragoza    7.473913   12.000
153                  David Brooks    9.994210   10.000
154                 Omar Marmoush  103.450631   75.000
155                  Jarrod Bowen  156.487860   40.000
156                   Jose Arnaiz    0.981180    1.500
157            Michael Folorunsho    1.984213    6.000
158                          Dudu    1.602052    0.600
159                  Younes Namli    0.819274    1.300
160               Riccardo Sottil    3.283605    5.000
161                  Armindo Sieb    4.164910    3.000
162                 Loum Tchaouna    4.054575   10.000
163                   Nuno Santos    2.691949    2.500
164                         Bruma    4.057794    7.000
165             Maghnes Akliouche   17.166786   45.000
166                Jann-Fiete Arp    2.795606    0.800
167                     Enes Unal   10.711957   10.000
168                Mats Seuntjens    0.392803    0.550
169               Sammie Szmodics   10.599889   10.000
170              Augustine Boakye    2.853008    2.500
171                  Mathis Suray    0.700040    1.500
172                 Paulinho Boia    1.089814    0.700
173              Henrique Pereira    1.057218    0.800
174                    Ante Erceg    0.165659    0.100
175                         Pedro    4.020786    1.000
176                   Tiago Tomas    8.743731   12.000
177             Christian Pulisic   31.091276   50.000
178                 Jizz Hornkamp    1.408026    1.300
179                 Ismael Gharbi    2.754712    7.500
180                       Rodrygo   11.308825   90.000
181                Adam Armstrong   10.980269   12.000
182                 Karim Adeyemi   13.927509   45.000
183               Florent Muslija    1.252273    1.800
184                  Kaj de Rooij    0.705922    0.350
185                    Ricardinho    1.821134    1.000
186                  Chris Lokesa    1.109656    0.400
187                    Iker Bravo    4.851244    3.000
188                  Samuel Bamba    1.841688    0.500
189                Emmanuel Sabbi    1.442459    1.500
190                   Desire Doue   16.914910   90.000
191                    Danny Ings    7.526715    6.000
192                  Zito Luvumbo    4.993185    5.000
193             Adrian Benedyczak    1.924582    4.500
194              Williot Swedberg   10.142489    5.000
195                  Ruben Vargas    2.075244    7.000
196                Goncalo Borges    1.628418    5.000
197                   Timo Werner    8.133130    7.000
198                   Che Nunnely    0.515686    0.500
199                  Koji Miyoshi    1.589452    1.500
200                 Marco Asensio   28.033826   20.000
201                  Kenan Yildiz   24.378232   50.000
202                Romano Postema    0.718965    0.450
203                     Dani Raba    8.319948    2.500
204                   Fuki Yamada    1.151023    0.700
205                   Marco Grull    4.005868    4.000
206              Tanguy Coulibaly    3.563172    1.500
207                Bobby Adekanye    0.446439    0.650
208                 Elton Kabangu    0.433797    0.600
209                 Samuel Lobato    0.645327    0.200
210                         Alfon    6.694230    5.000
211                 Nicolas Viola    2.215780    1.000
212               Abde Ezzalzouli    8.949342   12.000
213                  Paulo Dybala    7.073907    8.000
214                   Jack Clarke   12.833279   15.000
215                 Ernest Nuamah    4.814146   15.000
216         Aleksandr Lomovitskiy    0.577827    0.500
217                  Alexis Flips    0.587194    1.000
218            Adriano Bertaccini   18.054088    4.500
219                Florian Sotoca    2.093403    2.000
220             Bahereba Guirassy    3.533162    1.000
221                  Faiz Mattoir    0.333560    0.200
222                 Michael Olise  114.389261  100.000
223                        Thiago    5.807012   18.000
224                     Fer Lopez    2.964103    5.000
225                    Alan Minda    1.756786    3.000
226           Francisco Conceicao    8.969438   28.000
227                    Raul Paula    0.719383    0.600
228                  Matt Garbett    0.483104    0.400
229                Carlos Alcaraz   23.774848   14.000
230               Franjo Ivanovic   25.921573   13.000
231           Alireza Jahanbakhsh    0.635514    1.500
232                 Eddie Nketiah   17.712289   18.000
233             Lorenzo Venturino    5.976728    1.500
234              Christian Kouame    2.997852    4.000
235                    Milan Smit    1.369539    1.500
236               Mateo Cassierra    3.232967   10.000
237             Gianluca Lapadula    0.953805    0.750
238          Tiago Fonseca Morais    2.725712    3.000
239               Alberto Moleiro   11.673203   25.000
240                  Harry Wilson   19.510654   15.000
241              Kerem Akturkoglu   12.526727   24.000
242                    Jota Silva   12.947560   15.000
243                  Issa Soumare    9.569391    2.000
244                    Jaime Mata    0.786984    0.400
245                   Scott Banks    1.553535    0.500
246                    Ramon Sosa    8.426819   12.000
247               Christos Tzolis   21.835342   25.000
248                  Koen Kostons    0.732539    0.600
249              Antoine Colassin    2.194093    0.750
250                Tijjani Noslin    3.854224    7.500
251                   Leo Scienza    6.073450    3.000
252                Mohammed Kudus   45.652362   45.000
253                   Vando Felix    0.849118    1.000
254               Joselpho Barnes    0.606873    0.200
255             Miliano Jonathans    0.433053    0.900
256                  Lameck Banda    2.987778    4.500
257                    Dennis Man   10.172600   10.000
258              Oladapo Afolayan    3.829174    4.000
259          Mathias Pereira Lage    6.208953    2.500
260              Odysseus Velanas    0.610340    0.550
261               Zinedine Ferhat    1.219052    1.000
262                  Helio Varela    0.944635    1.200
263               Mamadou Diakhon    4.333178    3.000
264                 Said Benrahma    2.020423   10.000
265                  Yusupha Njie    0.476134    0.800
266                   Levi Garcia    0.888684   12.000
267               Stefan Schimmer    0.933051    0.500
268                 Yassir Zabiri    1.908557    0.600
269      D'Margio Wright-Phillips    0.589385    0.250
270                    Ritsu Doan   18.400123   25.000
271              Razhab Magomedov    1.042796    0.600
272                  Lucas Michal    1.835860    0.500
273              Andrew Hjulsager    0.554175    0.600
274                  Danny Loader    1.692865    4.000
275                    Basar Onal    1.147676    0.700
276               Raheem Sterling    5.647309   10.000
277             Gabriel Strefezza   13.220742    6.000
278                  Kiko Bondoso    0.927866    0.800
279                 Gboly Ariyibi    0.410500    0.200
280                 Nelson Weiper    6.727832   10.000
281              Samuel Chukwueze    4.481302   10.000
282                 Ethan Nwaneri   28.094129   55.000
283                         Savio   62.866440   50.000
284              Jan-Niklas Beste    0.871925    7.000
285                 Otso Liimatta    0.728640    0.800
286           Samuel Iling-Junior    3.810592   10.000
287                  Gerson Sousa    0.640274    1.300
288               Jeremy Livolant    1.995600    1.500
289                  Serge Gnabry    7.259403   22.000
290                 Nick Doodeman    0.474443    0.400
291             Gaetano Oristanio   10.128999    6.000
292                   Solly March    3.415973    6.000
293                  Nicolas Pays    1.797922    0.700
294                 Ferran Jutglà    6.410753    8.000
295            Kamaldeen Sulemana   13.015845   13.000
296                Anthony Elanga  121.475846   42.000
297                   Lucas Holer    5.980163    3.000
298                Daniel Maldini    9.588626   10.000
299                   Abdon Prats    1.257176    1.200
300                   Konan N'dri    2.061517    1.400
301              Ruben Providence    0.557040    0.350
302              Gilson Benchimol    2.210005    0.700
303                  Helder Costa    0.444015    0.400
304                          Sala    0.710444    0.200
305              Mathieu Maertens    0.845347    1.800
306                Arnaut Danjuma    3.443032    4.000
307                  Kaoru Mitoma   53.147009   40.000
308              Mathias Fixelles    0.397422    0.300
309                  Tete Morente    5.054324    2.000
310            Alexander Jakobsen    0.194934    0.075
311             Antoine Griezmann    6.490341   18.000
312                Nick Woltemade   16.745716   30.000
313                  John Mercado    1.637472    2.500
314               Stefan Mitrovic    1.566307    1.500
315                  Adrian Blake    1.391469    0.750
316                     Dany Mota    5.912693    4.000
317                Joaquin Correa    2.893726    3.000
318              Mauro Luna Diale    0.818028    1.000
319              Giorgos Masouras    2.514111    2.000
320                 Alvaro Garcia    6.919121    2.000
321                Suf Podgoreanu    1.490609    0.850
322               Matteo Politano    5.702305   10.000
323                  Jeremy Sebas    1.653534    0.700
324                Benjamin Sesko   30.617545   70.000
325                 Morlaye Sylla    1.816808    2.500
326           Zuriko Davitashvili   23.780362   10.000
327             Morgan Guilavogui    5.554020    4.000
328           Miguel Puche Garcia    0.942495    0.400
329                Justin Njinmah    3.867042    7.000
330                  Jeff Ekhator    4.865396    5.000
331                   Adam Nhaili    1.200967    0.250
332        Younes Taha El Idrissi    0.414370    1.000
333               Jovan Mijatovic    1.325351    3.000
334                Ibrahima Wadji    0.896846    0.700
335                   Jeremy Doku   30.087860   50.000
336                      Vinicius    2.813118    2.500
337                   Patson Daka    7.477006    9.000
338              Lassine Sinayoko   11.762139    4.000
339                 Islam Slimani    0.291932    0.500
340                  Grejohn Kyei    0.557916    0.700
341               Steven Berghuis    0.643531    3.500
342            Matteo Cancellieri    4.606846    4.500
343                    Luka Jovic    2.451800    4.500
344              Valeri Tsarukyan    1.717276    0.350
345                 Shuto Machino   11.405235    5.000
346                       Ben Old    1.783108    0.700
347                    Ante Rebic    1.726446    1.000
348              Yunus Emre Konak    8.256819    4.500
349           Kristoffer Peterson    0.877178    0.800
350              Maximilian Beier   11.285994   25.000
351               Tidjany Chabrol    1.614496    0.500
352                 Oliver Antman    6.928645    6.000
353             Dailon Livramento    3.166649    0.800
354                   Adam Hlozek   15.987072   18.000
355                   Joshua King    4.480060    1.800
356                  Remy Cabella    1.293999    2.500
357                 Milos Lukovic    0.897421    5.000
358              Kornelius Hansen    1.281677    0.500
359                      Rafa Mir    2.307488    0.800
360                  Roy Kuijpers    0.328161    0.275
361                 Manuel Fuster    2.475224    1.500

<b>Модель 4.<br>
Переменные: 'Gls', 'Ast', 'G+A-PK', '90s', 'Fld', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1'</b>

In [96]:
X_train = X_train[['Gls', 'Ast', 'G+A-PK', '90s', 'Fld', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]
X_test = X_test[['Gls', 'Ast', 'G+A-PK', '90s', 'Fld', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']]

In [103]:
coeffs_df

               coeff
league_GB1  0.712847
Gls         0.367860
league_IT1  0.361012
Age        -0.315112
league_L1   0.260582
90s         0.240181
league_ES1  0.239881
league_NL1 -0.239678
Ast         0.229201
league_FR1  0.219051
G+A-PK      0.140762
Fld         0.067194
league_PO1 -0.039614
league_RU1 -0.008636

In [104]:
metrics

            MAE       RMSE      MAPE        R2
test   4.438201   8.014056  0.817920  0.623537
train  5.165309  12.884933  0.763453  0.393654

In [105]:
comp_leftovers_test

                     Player  Value_pred  Value
0              Antonio Nusa    7.780520  28.00
1              Luis Vazquez    1.920413   2.50
2           Tristan Degreef    1.039289   2.00
3        Maximilian Breunig    2.366052   1.50
4                Kike Barja    1.402858   1.50
5           Pontus Almqvist    3.111401   2.50
6              Jacob Ramsey   17.643419  32.00
7            Luciano Gondou    4.775285  12.00
8            Issiaka Kamate    0.866643   0.75
9             Lucas Beltran   11.763245  18.00
10           Tomas Conechny    1.694486   1.80
11          Sheraldo Becker    1.895341   2.50
12         Anthony Descotte    0.641592   0.65
13            Marc Domenech    2.165432   1.00
14              John Yeboah    3.542192   2.80
15              Noah Okafor    2.461140  13.00
16             Nigel Thomas    0.836564   0.30
17  Gabriel Airton de Souza    1.069145   0.80
18            Conrad Harder    5.193301  24.00
19             Franco Cervi    0.851312   0.80
20         Soltmurad Bakaev    2.035433   0.70
21            Stanis Idumbo    3.458418   2.50
22              Sekou Koita    1.455053   3.50
23            Felix Correia    7.033234   4.00
24            Irvin Cardona    5.051252   2.50
25          Mason Greenwood   74.155670  40.00
26           Marin Ljubicic    3.045120   4.00
27         Marvin Pieringer   11.538609   5.50
28   Christopher Bonsu-Baah    4.450585   7.50
29         Jeremy Antonisse    0.846682   0.70
30             Sorba Thomas    3.203266   3.50
31             Breel Embolo    6.896468  12.00
32            Ibrahim Osman    1.535663  10.00
33                Bryan Gil    5.651715  15.00
34      Dardan Shabanhaxhaj    2.929795   1.20
35           Thorgan Hazard    0.772476   2.50
36                Juan Cruz    7.977346   5.00
37           Yaser Asprilla    4.895602  15.00
38             Rayan Cherki   33.736275  45.00
39           Anthony Gordon   59.170196  65.00
40    Gabriel Osei Misehouy    2.682849   1.00
41             Wahbi Khazri    1.240751   1.00
42            Luka Ivanusec    0.406012   3.50
43             Dario Poveda    1.247132   0.50
44      Andreas Schjelderup    1.821321  15.00
45             Lukas Nmecha    2.879147   3.00
46           El Bilal Toure    3.616087  15.00
47           Alfonso Trezza    2.675792   1.00
48         Gil Bastiao Dias    1.809168   1.50
49             Cisse Sandra    1.604523   1.00
50             Pedro Santos    0.822018   0.80
51               Robin Hack    9.771780  12.00
52              Jordan Ayew   11.721535   2.50
53           Erik Ahlstrand    1.612051   0.50
54         Mathis Lambourde    5.236624   0.80
55            Josue Casimir    8.143422   4.00
56             Angel Correa    2.518317  10.00
57              Vasco Lopes    1.478124   0.50
58            Juho Talvitie    1.132999   0.90
59             Dave Kwakman    0.956922   2.00
60               Sekou Mara    2.561381   5.00
61        Julien Duranville    2.425214   8.50
62             Max Svensson    1.543049   0.50
63            Anass Zaroury    3.683981   8.00
64         Bernardo Martins    2.107638   1.00
65              Luka Romero    1.955888   4.00
66              Kai Havertz   44.694983  65.00
67               Ayman Aiki    1.816454   0.40
68               Elias Saad    4.234239   4.00
69                     Caue    1.428508   0.80
70            Denis Makarov    0.976227   1.20
71         Oscar Pettersson    0.316899   0.50
72             Andre Inacio    2.179956   2.50
73         Vladislav Shitov    1.533583   0.80
74            Jamie Gittens   16.845456  50.00
75           Yusuf Kabadayi    4.116233   1.50
76    Allahyar Sayyadmanesh    4.746966   4.00
77         Nicolas Gonzalez    5.515860  24.00
78        Giacomo Raspadori    7.160527  25.00
79      Benedict Hollerbach   13.058727  12.00
80             Caio Santana    0.764599   0.10
81  Marcos Vinicios Sorriso    5.541739   5.00
82              Luka Tunjic    0.835252   0.45
83           Felipe Augusto    2.324722   2.20
84           Yankuba Minteh   47.112252  30.00
85           Andrea Colpani    4.035474   9.50
86              Frank Magri    4.725907   3.00
87          Vincent Janssen    6.738010   7.00
88         Miguel Rodriguez    2.510954   4.50
89           Abdoulay Diaby    0.488631   0.20
90                Keke Topp    6.426486   4.00
91        Francesco Camarda    3.355505  10.00
92       Callum Hudson-Odoi   29.965784  25.00
93             Jordi Mboula    0.977183   0.50

In [107]:
comp_leftovers_train

                           Player  Value_pred    Value
0                  Vincenzo Grifo   15.918552    6.000
1             Rifat Zhemaletdinov    1.329983    2.500
2                 Roger Fernandes    3.528582   22.000
3                     Gyrano Kerk    3.011677    3.000
4                 Musa Al-Taamari    3.077539    6.000
5                   Emilio Kehrer    0.854593    0.500
6              Albert Gudmundsson    5.280265   18.000
7                     Moses Simon   16.245926   12.000
8                   Michal Skoras    0.784917    2.500
9                  Sirlord Conteh    1.862312    1.500
10                  Ferran Torres   18.016330   40.000
11                  Ilias Sebaoui    1.025628    1.500
12                Josimar Alcocer    1.549053    2.200
13                  Ivan Sergeyev    3.263899    3.000
14                        Antoniu    2.696605    1.800
15   Lucas Vennegoor of Hesselink    0.488915    0.300
16                Jorge de Frutos    7.047071    4.000
17                  Paris Brunner    1.383745    1.500
18                   Adri Embarba    1.541865    1.200
19                    Lois Openda   21.027541   50.000
20                Lorenzo Colombo   12.100023    5.000
21          Crysencio Summerville   12.107246   22.000
22                Mohamed Ali Cho    7.577260   15.000
23                         Juanmi    1.033623    2.000
24                           Pepe    1.630980   22.000
25                 Nicolo Zaniolo    4.293448   12.000
26                    Bruno Messi    0.434225    0.700
27                    Igor Paixao   18.076745   35.000
28           Nuno Goncalo Moreira    3.116221    3.000
29                     Joao Felix    4.496842   20.000
30                          Portu    1.418166    1.800
31                Florian Thauvin    7.782235    5.000
32                   Danel Sinani    2.898145    1.500
33                  Ronaldo Cesar    3.320335    4.000
34                  Mamadou Sylla    2.837231    1.200
35                   Charly Keita    1.089009    0.550
36              Saeid Saharkhizan    3.555973    1.000
37                   Ruben Macedo    0.797606    0.450
38                Bazoumana Toure    4.365709    9.000
39                 Egas Cacintura    2.849768    1.000
40              Youssoufa Moukoko    5.087459   10.000
41                Chemsdine Talbi    3.975216    8.000
42                           Raul    3.455703    3.000
43             Moritz Broschinski    4.053525    2.000
44                 Brian Mansilla    0.691950    1.000
45                  Mickael Biron    0.534322    1.200
46               Nokkvi Thorisson    0.771481    0.600
47                 Johan Manzambi    5.090736    8.000
48             William Balikwisha    1.062591    1.200
49           Abbosbek Fayzullayev    3.723101    8.000
50                          Jason    1.739967    2.500
51                 Sandro Ramirez    8.187252    2.500
52                     Elif Elmas    3.844001   14.000
53                 Gabri Martinez    2.631182    4.000
54               Viktor Tsyhankov    4.948254   18.000
55                           Suso    1.407382    1.500
56                  Edon Zhegrova    3.288319   25.000
57                  Ibrahim Mbaye    3.956785    3.000
58            Sebastiano Esposito   13.587246    8.500
59               Denilho Cleonise    0.772607    0.400
60             Baptiste Guillaume    0.293862    0.450
61               Erencan Yardimci    1.788152    2.500
62                 Fabio Carvalho   15.042939   14.000
63                  Junior Kadile    1.896963    0.650
64                 Carlos Eduardo    0.727866    0.700
65                 Evann Guessand   38.350106   25.000
66                 Jacob Trenskow    1.786159    4.000
67                 Jonathan Ikone    2.773009    7.000
68                    Leon Bailey   10.717038   28.000
69                   Mario Engels    1.105911    0.500
70         Alessandro Gabrielloni    2.688589    0.850
71                  Mexx Meerdink    2.186985    8.000
72                       Raphinha   61.542146   90.000
73                  Thijs Oosting    0.453029    0.500
74                           Jota    1.567950    8.000
75                Mario Balotelli    0.872472    0.500
76                 Othmane Maamma    3.428688    0.600
77                 Yanis Begraoui    6.183610    3.500
78                     Joao Pedro   88.492717   50.000
79                    Pablo Duran    6.364354    3.500
80                    Bukayo Saka   87.898693  150.000
81                 Osame Sahraoui    4.482416   12.000
82                        Willian    2.516580    0.750
83                 Florinel Coman    2.169948    5.000
84                 Alex Berenguer    8.984256    9.000
85                  Jovane Cabral    1.093002    1.000
86                 Wilson Odobert   12.274883   20.000
87                 Kacper Kostorz    0.637350    0.450
88               Christantus Uche   13.997922   15.000
89                  Alvaro Morata    3.127757   11.000
90                  Filip Krastev    2.715150    4.000
91               Marcus Tavernier   26.637298   18.000
92                     Tim Skarke    2.133330    2.000
93                   Adama Traore   23.145584    9.000
94                   Steve Mounie    1.343469    2.000
95             Gabriel Martinelli   54.625511   55.000
96                  Sontje Hansen    2.389611    4.000
97                   Joao Marques    0.918056    3.000
98               Mohammed Fuseini    2.884563    4.500
99                Ignatius Ganago    1.197043    2.000
100                    Amar Ahmed    0.627800    0.450
101                 Morgan Rogers  152.125706   55.000
102            Kingstone Mutandwa    2.228491    0.600
103                    Alieu Njie    3.702567    2.500
104                  Thibo Somers    2.517159    2.500
105                  Abde Rebbach    1.323233    0.700
106              Valentin Mihaila    4.004999    3.000
107                   Alex Millan    0.612498    0.500
108                Kirill Danilin    1.673221    0.700
109                    Jonas Wind   11.911721   12.000
110                Yussuf Poulsen    1.622754    5.000
111                Keito Nakamura   13.186739    8.000
112           Remy Labeau Lascary    3.171250    2.000
113                 Simon Adingra   15.791165   28.000
114            Facundo Buonanotte   36.766240   20.000
115            Vyacheslav Grulyov    1.513857    1.200
116              Anis Hadj Moussa    2.815648   14.000
117               Francisco Perez    1.949856    3.000
118                   Brahim Diaz    4.875365   40.000
119            Muhammed Gumuskaya    0.647377    0.350
120        Alexander Bernhardsson    6.902801    3.000
121                 Abdallah Sima    7.290314    9.000
122                   Matheusinho    0.470870    1.500
123                     Rui Costa    0.838830    0.600
124                    Alex Iwobi   59.836113   28.000
125              Eldor Shomurodov    5.137634    5.000
126                Joshua Zirkzee   16.304600   30.000
127              Oliver Edvardsen    3.842066    5.000
128                 Jack Grealish    7.629042   28.000
129                  Ruben Garcia    5.552573    2.000
130             Arnaud Kalimuendo   36.745330   22.000
131                 Jonathan Rowe    5.440129   12.000
132                  Marco Matias    0.878437    0.100
133                   Lee Kang-in   10.868123   25.000
134               Bernard Berisha    0.453047    0.600
135              Munir El Haddadi    2.643123    1.500
136                   Dylan Mbayo    2.903340    2.000
137                    Iago Aspas    5.696734    2.000
138                Sergiu Perciun    2.865331    1.500
139               Jeremy Agbonifo    2.731983    5.000
140                Thomas Buitink    0.324882    0.400
141         Arkaitz Mariezkurrena    3.594514    0.700
142                  Ilyes Housni    1.909121    1.500
143                Sana Fernandes    0.693703    0.700
144                   Deniz Undav    8.746396   20.000
145                 Ismael Konate    4.632523    1.000
146                 Carlos Martin    4.154199    2.800
147              Victor Edvardsen    2.778431    1.300
148                  Takuma Asano    1.916964    2.500
149                  Noah Adedeji    3.390845    4.500
150               Hyllarion Goore    1.013242    0.600
151                     Junya Ito    4.095530    6.000
152                Bryan Zaragoza    6.808545   12.000
153                  David Brooks    8.476648   10.000
154                 Omar Marmoush   90.248447   75.000
155                  Jarrod Bowen  146.351948   40.000
156                   Jose Arnaiz    0.896725    1.500
157            Michael Folorunsho    1.981151    6.000
158                          Dudu    1.662894    0.600
159                  Younes Namli    0.654176    1.300
160               Riccardo Sottil    3.289758    5.000
161                  Armindo Sieb    4.333335    3.000
162                 Loum Tchaouna    3.470825   10.000
163                   Nuno Santos    2.192485    2.500
164                         Bruma    4.011887    7.000
165             Maghnes Akliouche   18.533127   45.000
166                Jann-Fiete Arp    2.412325    0.800
167                     Enes Unal   10.067040   10.000
168                Mats Seuntjens    0.367943    0.550
169               Sammie Szmodics   10.236126   10.000
170              Augustine Boakye    2.739563    2.500
171                  Mathis Suray    0.810130    1.500
172                 Paulinho Boia    1.017576    0.700
173              Henrique Pereira    1.101412    0.800
174                    Ante Erceg    0.155902    0.100
175                         Pedro    4.441535    1.000
176                   Tiago Tomas    8.504407   12.000
177             Christian Pulisic   38.682495   50.000
178                 Jizz Hornkamp    1.538935    1.300
179                 Ismael Gharbi    3.101182    7.500
180                       Rodrygo   10.837290   90.000
181                Adam Armstrong   11.080883   12.000
182                 Karim Adeyemi   14.637538   45.000
183               Florent Muslija    1.242340    1.800
184                  Kaj de Rooij    0.783466    0.350
185                    Ricardinho    2.114159    1.000
186                  Chris Lokesa    1.157879    0.400
187                    Iker Bravo    5.331054    3.000
188                  Samuel Bamba    1.877377    0.500
189                Emmanuel Sabbi    1.328489    1.500
190                   Desire Doue   15.851256   90.000
191                    Danny Ings    7.058277    6.000
192                  Zito Luvumbo    6.624504    5.000
193             Adrian Benedyczak    1.997297    4.500
194              Williot Swedberg    9.523520    5.000
195                  Ruben Vargas    2.240067    7.000
196                Goncalo Borges    1.697157    5.000
197                   Timo Werner    8.193119    7.000
198                   Che Nunnely    0.536545    0.500
199                  Koji Miyoshi    1.559053    1.500
200                 Marco Asensio   17.689985   20.000
201                  Kenan Yildiz   23.549549   50.000
202                Romano Postema    0.687531    0.450
203                     Dani Raba   10.459904    2.500
204                   Fuki Yamada    1.197440    0.700
205                   Marco Grull    5.173883    4.000
206              Tanguy Coulibaly    3.314717    1.500
207                Bobby Adekanye    0.436527    0.650
208                 Elton Kabangu    0.532113    0.600
209                 Samuel Lobato    0.631607    0.200
210                         Alfon    5.107935    5.000
211                 Nicolas Viola    2.319340    1.000
212               Abde Ezzalzouli    5.040069   12.000
213                  Paulo Dybala    6.347999    8.000
214                   Jack Clarke   15.515342   15.000
215                 Ernest Nuamah    4.175394   15.000
216         Aleksandr Lomovitskiy    0.598476    0.500
217                  Alexis Flips    0.653123    1.000
218            Adriano Bertaccini   11.635932    4.500
219                Florian Sotoca    1.431153    2.000
220             Bahereba Guirassy    3.692232    1.000
221                  Faiz Mattoir    0.331229    0.200
222                 Michael Olise  100.638058  100.000
223                        Thiago    6.235211   18.000
224                     Fer Lopez    3.028921    5.000
225                    Alan Minda    1.511835    3.000
226           Francisco Conceicao    8.288578   28.000
227                    Raul Paula    0.722679    0.600
228                  Matt Garbett    0.519604    0.400
229                Carlos Alcaraz   19.916072   14.000
230               Franjo Ivanovic   10.844354   13.000
231           Alireza Jahanbakhsh    0.597902    1.500
232                 Eddie Nketiah   13.982949   18.000
233             Lorenzo Venturino    6.184235    1.500
234              Christian Kouame    3.061683    4.000
235                    Milan Smit    1.347360    1.500
236               Mateo Cassierra    3.690364   10.000
237             Gianluca Lapadula    0.866943    0.750
238          Tiago Fonseca Morais    2.359740    3.000
239               Alberto Moleiro   10.600107   25.000
240                  Harry Wilson   18.313047   15.000
241              Kerem Akturkoglu   11.682078   24.000
242                    Jota Silva   14.458598   15.000
243                  Issa Soumare    8.966540    2.000
244                    Jaime Mata    0.688944    0.400
245                   Scott Banks    1.675652    0.500
246                    Ramon Sosa    8.005772   12.000
247               Christos Tzolis    7.557813   25.000
248                  Koen Kostons    0.849863    0.600
249              Antoine Colassin    2.321736    0.750
250                Tijjani Noslin    4.011629    7.500
251                   Leo Scienza    5.365504    3.000
252                Mohammed Kudus   43.313426   45.000
253                   Vando Felix    0.836907    1.000
254               Joselpho Barnes    0.715739    0.200
255             Miliano Jonathans    0.451105    0.900
256                  Lameck Banda    2.842654    4.500
257                    Dennis Man    8.203978   10.000
258              Oladapo Afolayan    3.870685    4.000
259          Mathias Pereira Lage    5.228043    2.500
260              Odysseus Velanas    0.611277    0.550
261               Zinedine Ferhat    1.314158    1.000
262                  Helio Varela    1.125977    1.200
263               Mamadou Diakhon    4.251437    3.000
264                 Said Benrahma    2.110239   10.000
265                  Yusupha Njie    0.431317    0.800
266                   Levi Garcia    0.739311   12.000
267               Stefan Schimmer    0.930032    0.500
268                 Yassir Zabiri    1.973210    0.600
269      D'Margio Wright-Phillips    0.731743    0.250
270                    Ritsu Doan   25.166181   25.000
271              Razhab Magomedov    0.986340    0.600
272                  Lucas Michal    1.834094    0.500
273              Andrew Hjulsager    0.582526    0.600
274                  Danny Loader    1.469631    4.000
275                    Basar Onal    0.986016    0.700
276               Raheem Sterling    6.416967   10.000
277             Gabriel Strefezza   12.991632    6.000
278                  Kiko Bondoso    1.172233    0.800
279                 Gboly Ariyibi    0.419330    0.200
280                 Nelson Weiper    5.701883   10.000
281              Samuel Chukwueze    4.614840   10.000
282                 Ethan Nwaneri   31.046494   55.000
283                         Savio   41.396080   50.000
284              Jan-Niklas Beste    0.818381    7.000
285                 Otso Liimatta    0.753054    0.800
286           Samuel Iling-Junior    3.970966   10.000
287                  Gerson Sousa    0.624666    1.300
288               Jeremy Livolant    2.561793    1.500
289                  Serge Gnabry    7.195808   22.000
290                 Nick Doodeman    0.555101    0.400
291             Gaetano Oristanio   11.814445    6.000
292                   Solly March    3.625252    6.000
293                  Nicolas Pays    1.897004    0.700
294                 Ferran Jutglà    3.766910    8.000
295            Kamaldeen Sulemana   13.228987   13.000
296                Anthony Elanga  115.390706   42.000
297                   Lucas Holer    5.972005    3.000
298                Daniel Maldini    8.671008   10.000
299                   Abdon Prats    1.232644    1.200
300                   Konan N'dri    2.209541    1.400
301              Ruben Providence    0.558926    0.350
302              Gilson Benchimol    2.313923    0.700
303                  Helder Costa    0.505424    0.400
304                          Sala    0.708997    0.200
305              Mathieu Maertens    0.752410    1.800
306                Arnaut Danjuma    2.909129    4.000
307                  Kaoru Mitoma   55.526140   40.000
308              Mathias Fixelles    0.478635    0.300
309                  Tete Morente    5.099747    2.000
310            Alexander Jakobsen    0.192745    0.075
311             Antoine Griezmann    8.370826   18.000
312                Nick Woltemade   18.088628   30.000
313                  John Mercado    2.151514    2.500
314               Stefan Mitrovic    1.782869    1.500
315                  Adrian Blake    1.440875    0.750
316                     Dany Mota    7.629800    4.000
317                Joaquin Correa    2.923556    3.000
318              Mauro Luna Diale    0.951244    1.000
319              Giorgos Masouras    1.915321    2.000
320                 Alvaro Garcia    4.844513    2.000
321                Suf Podgoreanu    1.602126    0.850
322               Matteo Politano    6.353059   10.000
323                  Jeremy Sebas    1.594613    0.700
324                Benjamin Sesko   32.678011   70.000
325                 Morlaye Sylla    1.472317    2.500
326           Zuriko Davitashvili   24.273223   10.000
327             Morgan Guilavogui    6.499951    4.000
328           Miguel Puche Garcia    0.999136    0.400
329                Justin Njinmah    4.445651    7.000
330                  Jeff Ekhator    5.315892    5.000
331                   Adam Nhaili    1.391434    0.250
332        Younes Taha El Idrissi    0.409152    1.000
333               Jovan Mijatovic    1.486547    3.000
334                Ibrahima Wadji    0.917422    0.700
335                   Jeremy Doku   35.804077   50.000
336                      Vinicius    3.392946    2.500
337                   Patson Daka    8.041717    9.000
338              Lassine Sinayoko   12.241952    4.000
339                 Islam Slimani    0.351609    0.500
340                  Grejohn Kyei    0.637696    0.700
341               Steven Berghuis    0.616023    3.500
342            Matteo Cancellieri    5.485996    4.500
343                    Luka Jovic    2.590565    4.500
344              Valeri Tsarukyan    1.835780    0.350
345                 Shuto Machino   13.650003    5.000
346                       Ben Old    1.830993    0.700
347                    Ante Rebic    1.699527    1.000
348              Yunus Emre Konak    8.737300    4.500
349           Kristoffer Peterson    1.100882    0.800
350              Maximilian Beier   16.026979   25.000
351               Tidjany Chabrol    1.464143    0.500
352                 Oliver Antman    8.598412    6.000
353             Dailon Livramento    3.360128    0.800
354                   Adam Hlozek   14.393187   18.000
355                   Joshua King    3.789153    1.800
356                  Remy Cabella    1.241717    2.500
357                 Milos Lukovic    0.849860    5.000
358              Kornelius Hansen    1.036198    0.500
359                      Rafa Mir    2.050897    0.800
360                  Roy Kuijpers    0.322645    0.275
361                 Manuel Fuster    2.614786    1.500

In [ ]:
base_cols = ['Gls', 'Ast', 'G+A-PK', '90s', 'Fld', 'Age', 'league_ES1', 'league_FR1',
       'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1',
       'league_RU1']

In [110]:
cols_to_add = [col for col in all_cols if not(col in base_cols)]
new_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_add:
    X_train_new = X_train[base_cols + [col]]
    X_test_new = X_test[base_cols + [col]]
    LR_regressor.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new<mae_test or mape_new<mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=new_cols.columns, index=[col])
        new_cols = pd.concat([new_cols, row])
new_cols

           mae     mape        r2
base  4.438201  0.81792  0.623537

In [111]:
cols_to_delete = [col for col in base_cols if not(col.startswith('league'))]
del_cols = pd.DataFrame({
    'mae':[mae_test],
    'mape':[mape_test],
    'r2':[r2_test]
}, index=['base'])
for col in cols_to_delete:
    X_train_new = X_train[[c for c in base_cols if c != col]]
    X_test_new = X_test[[c for c in base_cols if c != col]]
    LR_regressor.fit(X_train_new, y_train)
    y_pred_new = np.exp(LR_regressor.predict(X_test_new))
    mae_new = mean_absolute_error(y_pred_new, y_test_original)
    mape_new = mean_absolute_percentage_error(y_pred_new, y_test_original)
    r2_new = r2_score(y_pred_new, y_test_original)
    if mae_new < mae_test or mape_new < mape_test or r2_new > r2_test:
        row = pd.DataFrame([[mae_new, mape_new, r2_new]], columns=del_cols.columns, index=[col])
        del_cols = pd.concat([del_cols, row])
del_cols

           mae     mape        r2
base  4.438201  0.81792  0.623537