In [1]:
import pandas as pd

pd.options.display.max_columns = 37
pd.set_option('display.width', None)
pd.set_option('display.max_rows', None)

In [77]:
df = pd.read_csv('csv/stats/PO1_gk_24-25.csv')
df

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,Save%.1
0,Andrew,BRA,GK,Gil Vicente FC,23,33,33,2970,33.0,46,1.39,122,81,67.2,8,9,16,7,21.2,7,6,0,1,0.0
1,Brian AraГєjo,FRA,GK,Gil Vicente FC,24,1,1,90,1.0,1,1.00,3,2,66.7,0,1,0,0,0.0,0,0,0,0,NaN
2,Daniel Azevedo,POR,GK,Casa Pia,26,1,1,90,1.0,2,2.00,4,2,50.0,0,0,1,0,0.0,0,0,0,0,NaN
3,Gabriel Batista,BRA,GK,Santa Clara,26,34,34,3060,34.0,32,0.94,108,81,74.1,17,6,11,11,32.4,6,4,1,1,20.0
4,Ricardo Batista,POR,GK,Casa Pia,37,1,1,90,1.0,1,1.00,1,1,100.0,0,0,1,0,0.0,1,1,0,0,0.0
5,SimГЈo Bertelli,BRA,GK,AVS Futebol,31,11,11,990,11.0,15,1.36,54,42,75.9,1,6,4,2,18.2,3,2,1,0,33.3
6,Bruno Brigido,BRA,GK,Estrela,33,18,18,1575,17.5,30,1.71,84,56,66.7,4,4,10,2,11.1,2,2,0,0,0.0
7,Lazar CareviД‡,MNE,GK,FamalicГЈo,25,18,18,1620,18.0,21,1.17,70,53,74.3,7,4,7,7,38.9,4,3,1,0,25.0
8,CГ©sar,BRA,GK,Boavista,32,16,16,1440,16.0,30,1.87,78,51,65.4,1,4,11,2,12.5,3,3,0,0,0.0
9,Kevin Chamorro,CRC,GK,Estoril,24,4,4,360,4.0,3,0.75,11,9,81.8,2,1,1,2,50.0,1,1,0,0,0.0
10,Diogo Costa,POR,GK,Porto,24,32,32,2880,32.0,27,0.84,78,58,71.8,21,5,6,16,50.0,7,5,2,0,28.6
11,JoГЈo Paulo Santos Costa,POR,GK,Estrela,28,14,14,1260,14.0,17,1.21,51,38,72.5,3,3,8,4,28.6,4,3,1,0,25.0
12,Rui EncarnaГ§ГЈo,POR,GK,Nacional,26,2,1,135,1.5,4,2.67,5,3,60.0,0,0,1,0,0.0,2,2,0,0,0.0
13,Daniel Figueira,POR,GK,Estoril,26,1,1,90,1.0,4,4.00,6,3,50.0,0,0,1,0,0.0,1,1,0,0,0.0
14,Lucas FranГ§a,BRA,GK,Nacional,28,33,33,2925,32.5,46,1.42,143,104,72.7,9,7,17,8,24.2,9,7,0,2,0.0
15,JoГЈo GonГ§alves,POR,GK,Boavista,23,4,4,360,4.0,2,0.50,8,6,75.0,1,1,2,2,50.0,0,0,0,0,NaN
16,Marko GudЕѕuliД‡,SRB,GK,Estrela,22,2,2,180,2.0,3,1.50,8,6,62.5,0,1,1,1,50.0,1,0,1,0,100.0
17,LukГЎЕЎ HornГ­ДЌek,CZE,GK,Braga,22,17,17,1530,17.0,11,0.65,58,47,82.8,10,5,2,8,47.1,1,1,0,0,0.0
18,Franco Israel,URU,GK,Sporting CP,24,11,11,990,11.0,9,0.82,25,15,64.0,9,2,0,7,63.6,0,0,0,0,NaN
19,Jhonatan,BRA,GK,Rio Ave,33,8,8,720,8.0,13,1.62,43,30,69.8,2,2,4,2,25.0,0,0,0,0,NaN
20,Luiz LГєcio Reis JГєnior,BRA,GK,FamalicГЈo,23,1,1,90,1.0,0,0.00,2,2,100.0,1,0,0,1,100.0,0,0,0,0,NaN
21,Kaique,BRA,GK,Farense,21,6,6,540,6.0,6,1.00,20,15,70.0,3,0,3,1,16.7,1,0,1,0,100.0
22,Kewin,BRA,GK,Moreirense,28,29,29,2610,29.0,42,1.45,112,72,65.2,9,7,13,6,20.7,3,3,0,0,0.0
23,Vladan KovaДЌeviД‡,BIH,GK,Sporting CP,26,6,6,540,6.0,5,0.83,16,11,68.8,4,0,2,2,33.3,0,0,0,0,NaN
24,Nico Mantl,GER,GK,Arouca,24,29,29,2610,29.0,43,1.48,117,82,70.1,8,8,13,7,24.1,8,8,0,0,0.0
25,Matheus,BRA,GK,Braga,32,17,17,1530,17.0,19,1.12,64,47,73.4,9,4,4,7,41.2,2,2,0,0,0.0
26,Francisco Meixedo,POR,GK,Estrela,23,1,0,45,0.5,0,0.00,3,3,100.0,0,0,0,1,NaN,0,0,0,0,NaN
27,Mika,POR,GK,Moreirense,33,1,0,3,0.0,0,0.00,0,0,NaN,0,0,0,1,NaN,0,0,0,0,NaN
28,Cezary Miszta,POL,GK,Rio Ave,22,26,26,2325,25.8,42,1.63,129,90,69.8,7,9,10,3,11.5,3,3,0,0,0.0
29,Guillermo Ochoa,MEX,GK,AVS Futebol,39,23,23,2070,23.0,45,1.96,118,74,62.7,4,6,13,6,26.1,1,1,0,0,0.0
30,ClГЎudio Ramos,POR,GK,Porto,32,2,2,180,2.0,3,1.50,7,5,71.4,1,0,1,0,0.0,1,1,0,0,0.0
31,Joel Robles,ESP,GK,Estoril,34,29,29,2610,29.0,46,1.59,122,82,66.4,10,9,10,5,17.2,6,5,1,0,16.7
32,Caio Secco,BRA,GK,Moreirense,33,5,5,447,5.0,8,1.61,21,15,71.4,1,3,1,1,20.0,2,2,0,0,0.0
33,Patrick Sequeira,CRC,GK,Casa Pia,25,32,32,2880,32.0,41,1.28,152,117,77.0,12,9,11,7,21.9,7,6,0,1,0.0
34,Rui Silva,POR,GK,Sporting CP,30,17,17,1530,17.0,13,0.76,30,21,70.0,12,5,0,6,35.3,4,4,0,0,0.0
35,Samuel Soares,POR,GK,Benfica,22,2,2,180,2.0,0,0.00,3,4,100.0,2,0,0,2,100.0,1,0,1,0,100.0
36,Matheus Teixeira,BRA,GK,Rio Ave,25,1,0,15,0.2,0,0.00,0,0,NaN,0,0,0,0,NaN,0,0,0,0,NaN
37,TomГ©,POR,GK,Boavista,17,2,2,180,2.0,5,2.50,11,6,54.5,0,1,1,0,0.0,0,0,0,0,NaN
38,Anatolii Trubin,UKR,GK,Benfica,22,32,32,2880,32.0,28,0.87,97,72,73.2,23,5,4,13,40.6,3,2,1,0,33.3
39,TomГЎЕЎ VaclГ­k,CZE,GK,Boavista,35,12,12,1080,12.0,22,1.83,75,56,74.7,4,0,8,3,25.0,3,3,0,0,0.0
40,JoГЈo Valido,POR,GK,Arouca,24,5,5,450,5.0,6,1.20,19,14,73.7,1,3,1,1,20.0,1,1,0,0,0.0
41,Bruno Varela,CPV,GK,VitГіria GuimarГЈes,29,34,34,3060,34.0,37,1.09,98,63,67.3,14,12,8,13,38.2,7,5,0,2,0.0
42,Ricardo Velho,POR,GK,Farense,25,28,28,2520,28.0,40,1.43,123,89,72.4,3,9,16,6,21.4,7,6,0,1,0.0
43,Ivan Zlobin,RUS,GK,FamalicГЈo,27,15,15,1350,15.0,18,1.20,62,45,72.6,4,7,4,5,33.3,1,1,0,0,0.0

In [78]:
false_names = df[~(df['Player'].str.match(r'^[A-Za-z\s-]+$'))]
false_club_names = df[~(df['Squad'].str.match(r'^[A-Za-z\s-]+$'))]
len(false_names)

16

In [79]:
false_club_names['Squad'].unique()
false_names

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,Save%.1
1,Brian AraГєjo,FRA,GK,Gil Vicente FC,24,1,1,90,1.0,1,1.00,3,2,66.7,0,1,0,0,0.0,0,0,0,0,NaN
5,SimГЈo Bertelli,BRA,GK,AVS Futebol,31,11,11,990,11.0,15,1.36,54,42,75.9,1,6,4,2,18.2,3,2,1,0,33.3
7,Lazar CareviД‡,MNE,GK,FamalicГЈo,25,18,18,1620,18.0,21,1.17,70,53,74.3,7,4,7,7,38.9,4,3,1,0,25.0
8,CГ©sar,BRA,GK,Boavista,32,16,16,1440,16.0,30,1.87,78,51,65.4,1,4,11,2,12.5,3,3,0,0,0.0
11,JoГЈo Paulo Santos Costa,POR,GK,Estrela,28,14,14,1260,14.0,17,1.21,51,38,72.5,3,3,8,4,28.6,4,3,1,0,25.0
12,Rui EncarnaГ§ГЈo,POR,GK,Nacional,26,2,1,135,1.5,4,2.67,5,3,60.0,0,0,1,0,0.0,2,2,0,0,0.0
14,Lucas FranГ§a,BRA,GK,Nacional,28,33,33,2925,32.5,46,1.42,143,104,72.7,9,7,17,8,24.2,9,7,0,2,0.0
15,JoГЈo GonГ§alves,POR,GK,Boavista,23,4,4,360,4.0,2,0.50,8,6,75.0,1,1,2,2,50.0,0,0,0,0,NaN
16,Marko GudЕѕuliД‡,SRB,GK,Estrela,22,2,2,180,2.0,3,1.50,8,6,62.5,0,1,1,1,50.0,1,0,1,0,100.0
17,LukГЎЕЎ HornГ­ДЌek,CZE,GK,Braga,22,17,17,1530,17.0,11,0.65,58,47,82.8,10,5,2,8,47.1,1,1,0,0,0.0
20,Luiz LГєcio Reis JГєnior,BRA,GK,FamalicГЈo,23,1,1,90,1.0,0,0.00,2,2,100.0,1,0,0,1,100.0,0,0,0,0,NaN
23,Vladan KovaДЌeviД‡,BIH,GK,Sporting CP,26,6,6,540,6.0,5,0.83,16,11,68.8,4,0,2,2,33.3,0,0,0,0,NaN
30,ClГЎudio Ramos,POR,GK,Porto,32,2,2,180,2.0,3,1.50,7,5,71.4,1,0,1,0,0.0,1,1,0,0,0.0
37,TomГ©,POR,GK,Boavista,17,2,2,180,2.0,5,2.50,11,6,54.5,0,1,1,0,0.0,0,0,0,0,NaN
39,TomГЎЕЎ VaclГ­k,CZE,GK,Boavista,35,12,12,1080,12.0,22,1.83,75,56,74.7,4,0,8,3,25.0,3,3,0,0,0.0
40,JoГЈo Valido,POR,GK,Arouca,24,5,5,450,5.0,6,1.20,19,14,73.7,1,3,1,1,20.0,1,1,0,0,0.0

In [80]:
changes = {
    'Г©':'é',
    'Г§':'ç',
    'ГЇ':'i',
    'Д‡':'ć',
    'Гі':'o',
    'Д›':'ě',
    'ГЎ':'á',
    'Г¤':'ä',
    'Г±':'ñ',
    'Гґ':'ô',
    'ЕЅ':'Ž',
    'Г«':'ë',
    'ГЈ':'ã',
    'Е‚':'ł',
    'Е›':'ś',
    'Г“':'Ó',
    'ЕЎ':'š',
    'Дђ':'Đ',
    'ГЃ':'Á',
    'Гє':'ú',
    'Гў':'â',
    'Г‰':'É',
    'ГЄ':'ê',
    'Гј':'ü',
    'Г¶':'ö',
    'ДЌ':'č',
    'Г‘':'Ñ',
    'Г–':'Ö',
    'Гё':'ø',
    'Гњ':'Ü',
    'Д™':'ę',
    'Дџ':'ğ',
    'Д±':'ı',
    'Гћ':'Þ',
    'ГЁ':'è',
    'Г°':'ð',
    'ГЅ':'ý',
    'Е ':'Š',
    'Д†':'Ć',
    'Еѕ':'ž',
    'Еџ':'ş',
    'Д‘':'đ',
    'ГІ':'ò',
    'Дѓ':'ă',
    'И™':'ș',
    'Г‡':'Ç',
    'ДЊ':'Č',
    'Г¦':'æ',
    'Е„':'ń',
    'Дѓ':'ă',
    'И›':'ț',
    'ЕЃ':'Ł',
    'Г¬':'ì',
    'Е»':'Ż',
    'Еє':'ź',
    'ЕЌ':'ō',
    'Гџ':'ß',
    'Е™':'ř',
    'ГҐ':'å',
    'Гљ':'Ú',
    'ГЂ':'À',
    'ЕЇ':'ů',
    'вЂ™':'’',
    'Гµ':'õ',
    'Е«':'ū',
    'Г‚':'Â',
    

    #'Г':'í'
}
for symbol in changes:
    df['Player']=df['Player'].str.replace(symbol, changes[symbol])
    df['Squad']=df['Squad'].str.replace(symbol, changes[symbol])
df

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,Save%.1
0,Andrew,BRA,GK,Gil Vicente FC,23,33,33,2970,33.0,46,1.39,122,81,67.2,8,9,16,7,21.2,7,6,0,1,0.0
1,Brian Araújo,FRA,GK,Gil Vicente FC,24,1,1,90,1.0,1,1.00,3,2,66.7,0,1,0,0,0.0,0,0,0,0,NaN
2,Daniel Azevedo,POR,GK,Casa Pia,26,1,1,90,1.0,2,2.00,4,2,50.0,0,0,1,0,0.0,0,0,0,0,NaN
3,Gabriel Batista,BRA,GK,Santa Clara,26,34,34,3060,34.0,32,0.94,108,81,74.1,17,6,11,11,32.4,6,4,1,1,20.0
4,Ricardo Batista,POR,GK,Casa Pia,37,1,1,90,1.0,1,1.00,1,1,100.0,0,0,1,0,0.0,1,1,0,0,0.0
5,Simão Bertelli,BRA,GK,AVS Futebol,31,11,11,990,11.0,15,1.36,54,42,75.9,1,6,4,2,18.2,3,2,1,0,33.3
6,Bruno Brigido,BRA,GK,Estrela,33,18,18,1575,17.5,30,1.71,84,56,66.7,4,4,10,2,11.1,2,2,0,0,0.0
7,Lazar Carević,MNE,GK,Famalicão,25,18,18,1620,18.0,21,1.17,70,53,74.3,7,4,7,7,38.9,4,3,1,0,25.0
8,César,BRA,GK,Boavista,32,16,16,1440,16.0,30,1.87,78,51,65.4,1,4,11,2,12.5,3,3,0,0,0.0
9,Kevin Chamorro,CRC,GK,Estoril,24,4,4,360,4.0,3,0.75,11,9,81.8,2,1,1,2,50.0,1,1,0,0,0.0
10,Diogo Costa,POR,GK,Porto,24,32,32,2880,32.0,27,0.84,78,58,71.8,21,5,6,16,50.0,7,5,2,0,28.6
11,João Paulo Santos Costa,POR,GK,Estrela,28,14,14,1260,14.0,17,1.21,51,38,72.5,3,3,8,4,28.6,4,3,1,0,25.0
12,Rui Encarnação,POR,GK,Nacional,26,2,1,135,1.5,4,2.67,5,3,60.0,0,0,1,0,0.0,2,2,0,0,0.0
13,Daniel Figueira,POR,GK,Estoril,26,1,1,90,1.0,4,4.00,6,3,50.0,0,0,1,0,0.0,1,1,0,0,0.0
14,Lucas França,BRA,GK,Nacional,28,33,33,2925,32.5,46,1.42,143,104,72.7,9,7,17,8,24.2,9,7,0,2,0.0
15,João Gonçalves,POR,GK,Boavista,23,4,4,360,4.0,2,0.50,8,6,75.0,1,1,2,2,50.0,0,0,0,0,NaN
16,Marko Gudžulić,SRB,GK,Estrela,22,2,2,180,2.0,3,1.50,8,6,62.5,0,1,1,1,50.0,1,0,1,0,100.0
17,Lukáš HornГ­ček,CZE,GK,Braga,22,17,17,1530,17.0,11,0.65,58,47,82.8,10,5,2,8,47.1,1,1,0,0,0.0
18,Franco Israel,URU,GK,Sporting CP,24,11,11,990,11.0,9,0.82,25,15,64.0,9,2,0,7,63.6,0,0,0,0,NaN
19,Jhonatan,BRA,GK,Rio Ave,33,8,8,720,8.0,13,1.62,43,30,69.8,2,2,4,2,25.0,0,0,0,0,NaN
20,Luiz Lúcio Reis Júnior,BRA,GK,Famalicão,23,1,1,90,1.0,0,0.00,2,2,100.0,1,0,0,1,100.0,0,0,0,0,NaN
21,Kaique,BRA,GK,Farense,21,6,6,540,6.0,6,1.00,20,15,70.0,3,0,3,1,16.7,1,0,1,0,100.0
22,Kewin,BRA,GK,Moreirense,28,29,29,2610,29.0,42,1.45,112,72,65.2,9,7,13,6,20.7,3,3,0,0,0.0
23,Vladan Kovačević,BIH,GK,Sporting CP,26,6,6,540,6.0,5,0.83,16,11,68.8,4,0,2,2,33.3,0,0,0,0,NaN
24,Nico Mantl,GER,GK,Arouca,24,29,29,2610,29.0,43,1.48,117,82,70.1,8,8,13,7,24.1,8,8,0,0,0.0
25,Matheus,BRA,GK,Braga,32,17,17,1530,17.0,19,1.12,64,47,73.4,9,4,4,7,41.2,2,2,0,0,0.0
26,Francisco Meixedo,POR,GK,Estrela,23,1,0,45,0.5,0,0.00,3,3,100.0,0,0,0,1,NaN,0,0,0,0,NaN
27,Mika,POR,GK,Moreirense,33,1,0,3,0.0,0,0.00,0,0,NaN,0,0,0,1,NaN,0,0,0,0,NaN
28,Cezary Miszta,POL,GK,Rio Ave,22,26,26,2325,25.8,42,1.63,129,90,69.8,7,9,10,3,11.5,3,3,0,0,0.0
29,Guillermo Ochoa,MEX,GK,AVS Futebol,39,23,23,2070,23.0,45,1.96,118,74,62.7,4,6,13,6,26.1,1,1,0,0,0.0
30,Cláudio Ramos,POR,GK,Porto,32,2,2,180,2.0,3,1.50,7,5,71.4,1,0,1,0,0.0,1,1,0,0,0.0
31,Joel Robles,ESP,GK,Estoril,34,29,29,2610,29.0,46,1.59,122,82,66.4,10,9,10,5,17.2,6,5,1,0,16.7
32,Caio Secco,BRA,GK,Moreirense,33,5,5,447,5.0,8,1.61,21,15,71.4,1,3,1,1,20.0,2,2,0,0,0.0
33,Patrick Sequeira,CRC,GK,Casa Pia,25,32,32,2880,32.0,41,1.28,152,117,77.0,12,9,11,7,21.9,7,6,0,1,0.0
34,Rui Silva,POR,GK,Sporting CP,30,17,17,1530,17.0,13,0.76,30,21,70.0,12,5,0,6,35.3,4,4,0,0,0.0
35,Samuel Soares,POR,GK,Benfica,22,2,2,180,2.0,0,0.00,3,4,100.0,2,0,0,2,100.0,1,0,1,0,100.0
36,Matheus Teixeira,BRA,GK,Rio Ave,25,1,0,15,0.2,0,0.00,0,0,NaN,0,0,0,0,NaN,0,0,0,0,NaN
37,Tomé,POR,GK,Boavista,17,2,2,180,2.0,5,2.50,11,6,54.5,0,1,1,0,0.0,0,0,0,0,NaN
38,Anatolii Trubin,UKR,GK,Benfica,22,32,32,2880,32.0,28,0.87,97,72,73.2,23,5,4,13,40.6,3,2,1,0,33.3
39,Tomáš VaclГ­k,CZE,GK,Boavista,35,12,12,1080,12.0,22,1.83,75,56,74.7,4,0,8,3,25.0,3,3,0,0,0.0
40,João Valido,POR,GK,Arouca,24,5,5,450,5.0,6,1.20,19,14,73.7,1,3,1,1,20.0,1,1,0,0,0.0
41,Bruno Varela,CPV,GK,Vitoria Guimarães,29,34,34,3060,34.0,37,1.09,98,63,67.3,14,12,8,13,38.2,7,5,0,2,0.0
42,Ricardo Velho,POR,GK,Farense,25,28,28,2520,28.0,40,1.43,123,89,72.4,3,9,16,6,21.4,7,6,0,1,0.0
43,Ivan Zlobin,RUS,GK,Famalicão,27,15,15,1350,15.0,18,1.20,62,45,72.6,4,7,4,5,33.3,1,1,0,0,0.0

In [81]:
df.at[17,'Player'] = 'Lukas Hornicek'
df.at[17,'Player']

'Lukas Hornicek'

In [153]:
df[df['Player'].str.contains('Еѕ')]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
180,Stefan DЕѕodić,SRB,"DF,MF",Montpellier,19.0,7,2,242,2.7,0,0,0,0,0,0,2,1,0.1,0.1,0.0,0.1,2,10,0,0.0,0.0,0.0,0.0,0.0,0.03,0.0,0.03,0.03,0.03

In [82]:
df.to_csv('csv/stats/PO1_gk_24-25.csv', index=False)