In [1]:
import pandas as pd
import xgboost as xgb
import optuna
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import mean_absolute_error as mae, mean_absolute_percentage_error as mape, root_mean_squared_error as rmse, r2_score

C:\Users\denis\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
pd.set_option('display.max_rows', None)

In [9]:
df = pd.read_csv('csv/stats/combine_gk_24-25.csv')
X = df[(df['Value']>0) & (df['MP']>4)]
y = X[['Value']]
X = X.drop('Value', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_binned = pd.qcut(y_train['Value'], q=5, labels=False)
X_train, X_val, y_train, y_val, _, _ = train_test_split(
    X_train, y_train, y_binned, test_size=0.2, random_state=42, stratify=y_binned
)

In [10]:
X_train[['Player', 'Nation', 'Pos', 'Squad', 'league']].to_csv('csv/final_datasets/for_xgb/train_test_val/train_gk_names.csv', index=False)
X_test[['Player', 'Nation', 'Pos', 'Squad', 'league']].to_csv('csv/final_datasets/for_xgb/train_test_val/test_gk_names.csv', index=False)
X_val[['Player', 'Nation', 'Pos', 'Squad', 'league']].to_csv('csv/final_datasets/for_xgb/train_test_val/val_gk_names.csv', index=False)

X_train.drop('Player', axis=1).to_csv('csv/final_datasets/for_xgb/train_test_val/gk_predictors_train.csv', index=False)
X_test.drop('Player', axis=1).to_csv('csv/final_datasets/for_xgb/train_test_val/gk_predictors_test.csv', index=False)
X_val.drop('Player', axis=1).to_csv('csv/final_datasets/for_xgb/train_test_val/gk_predictors_val.csv', index=False)

y_train.to_csv('csv/final_datasets/for_xgb/train_test_val/gk_target_train.csv', index=False)
y_test.to_csv('csv/final_datasets/for_xgb/train_test_val/gk_target_test.csv', index=False)
y_val.to_csv('csv/final_datasets/for_xgb/train_test_val/gk_target_val.csv', index=False)

In [11]:
X_train = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/gk_predictors_train.csv')
X_test = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/gk_predictors_test.csv')
X_val = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/gk_predictors_val.csv')
for col in ('Nation', 'Pos', 'Squad', 'league'):
    X_train[col] = X_train[col].astype('category')
    X_test[col] = X_test[col].astype('category')
    X_val[col] = X_val[col].astype('category')

players_train = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/train_gk_names.csv')
players_test = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/test_gk_names.csv')
players_val = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/val_gk_names.csv')

y_train = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/gk_target_train.csv')
y_test = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/gk_target_test.csv')
y_val = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/gk_target_val.csv')

In [12]:
def objective_gamma(trial):
    params = {
        'max_depth' : trial.suggest_int('max_depth', 3, 10),
        'learning_rate' : trial.suggest_float('learning_rate', 0.01, 10, log=True),
        'subsample' : trial.suggest_float('subsample', 0.5, 1),
        'colsample_bytree' : trial.suggest_float('colsample_bytree', 0.5, 1),
        'reg_lambda' : trial.suggest_float('reg_lambda', 0.01, 10, log=True),
        'reg_alpha' : trial.suggest_float('reg_alpha', 0.01, 10, log=True)
    }

    params['n_estimators'] = 2000
    params['objective'] = 'reg:gamma'
    params['random_state'] = 42
    #params['device'] = 'cuda'
    params['early_stopping_rounds'] = 15
    params['eval_metric'] = 'mape'
    params['enable_categorical'] = True

    model = xgb.XGBRegressor(**params)
    model.fit(
        X_train, y_train,
        eval_set = [(X_val, y_val)],
        verbose = False
    )

    y_val_pred = model.predict(X_val)
    y_train_pred = model.predict(X_train)

    r2_val = r2_score(y_val, y_val_pred)
    r2_train = r2_score(y_train, y_train_pred)

    mape_val = mape(y_val, y_val_pred)
    
    trial.set_user_attr('r2_train', r2_train)
    trial.set_user_attr('r2_val', r2_val)
    trial.set_user_attr('r2_delta', abs(r2_train - r2_val))
    trial.set_user_attr('mape_val', mape_val)
    
    return r2_val

In [13]:
study = optuna.create_study(direction='maximize', study_name='xgb_tuning_gamma')

[I 2026-04-05 15:31:52,480] A new study created in memory with name: xgb_tuning_gamma

In [14]:
study.optimize(objective_gamma, n_trials=100, show_progress_bar=True, n_jobs=-1)

Best trial: 6. Best value: 0.126267:   5%|██▎                                          | 5/100 [00:00<00:09, 10.54it/s]

[I 2026-04-05 15:32:14,450] Trial 2 finished with value: -76.37210083007812 and parameters: {'max_depth': 5, 'learning_rate': 4.830652710983124, 'subsample': 0.7649186754706936, 'colsample_bytree': 0.7068289090056487, 'reg_lambda': 0.7725826039793499, 'reg_alpha': 2.1411834574438036}. Best is trial 2 with value: -76.37210083007812.
[I 2026-04-05 15:32:14,467] Trial 1 finished with value: -7.026104927062988 and parameters: {'max_depth': 8, 'learning_rate': 2.98539903688901, 'subsample': 0.8934818921922802, 'colsample_bytree': 0.8981826523540128, 'reg_lambda': 1.270637275304875, 'reg_alpha': 0.015498440370893223}. Best is trial 1 with value: -7.026104927062988.
[I 2026-04-05 15:32:14,497] Trial 6 finished with value: 0.12626659870147705 and parameters: {'max_depth': 4, 'learning_rate': 0.5007968887071863, 'subsample': 0.7036487314844136, 'colsample_bytree': 0.5798117553881201, 'reg_lambda': 0.021566445970805266, 'reg_alpha': 1.7931037257787208}. Best is trial 6 with value: 0.12626659870147705.
[I 2026-04-05 15:32:14,548] Trial 4 finished with value: -0.61577308177948 and parameters: {'max_depth': 7, 'learning_rate': 1.356133290272465, 'subsample': 0.7312106367186268, 'colsample_bytree': 0.911966825038199, 'reg_lambda': 0.020423391258397313, 'reg_alpha': 0.010470031667417551}. Best is trial 6 with value: 0.12626659870147705.
[I 2026-04-05 15:32:14,634] Trial 5 finished with value: -0.010080099105834961 and parameters: {'max_depth': 4, 'learning_rate': 0.14222696277643224, 'subsample': 0.5541293962409821, 'colsample_bytree': 0.8022944828313785, 'reg_lambda': 2.7710101403744276, 'reg_alpha': 0.028234740145401466}. Best is trial 6 with value: 0.12626659870147705.

Best trial: 6. Best value: 0.126267:   8%|███▌                                         | 8/100 [00:00<00:09, 10.13it/s]

[I 2026-04-05 15:32:14,760] Trial 12 finished with value: -1.522695779800415 and parameters: {'max_depth': 4, 'learning_rate': 2.203267375984796, 'subsample': 0.6837980211686431, 'colsample_bytree': 0.7379002804441612, 'reg_lambda': 1.7745733107466681, 'reg_alpha': 0.467562210825681}. Best is trial 6 with value: 0.12626659870147705.
[I 2026-04-05 15:32:14,841] Trial 0 finished with value: 0.02878338098526001 and parameters: {'max_depth': 9, 'learning_rate': 0.060921370568431714, 'subsample': 0.8994598626421896, 'colsample_bytree': 0.5462119135524026, 'reg_lambda': 1.2016844384633467, 'reg_alpha': 0.048781161371075}. Best is trial 6 with value: 0.12626659870147705.
[I 2026-04-05 15:32:14,874] Trial 3 finished with value: 0.10561317205429077 and parameters: {'max_depth': 9, 'learning_rate': 0.05652466179711447, 'subsample': 0.7547879894302172, 'colsample_bytree': 0.7716113097555641, 'reg_lambda': 1.6992337255015595, 'reg_alpha': 0.42333655235980544}. Best is trial 6 with value: 0.12626659870147705.
[I 2026-04-05 15:32:14,929] Trial 11 finished with value: -0.004744529724121094 and parameters: {'max_depth': 9, 'learning_rate': 0.12827341355894484, 'subsample': 0.601227958678328, 'colsample_bytree': 0.7101785425621554, 'reg_lambda': 6.007131654587556, 'reg_alpha': 0.05590545891838446}. Best is trial 6 with value: 0.12626659870147705.

Best trial: 7. Best value: 0.3517:  13%|█████▉                                        | 13/100 [00:01<00:06, 13.71it/s]

[I 2026-04-05 15:32:15,060] Trial 7 finished with value: 0.35169994831085205 and parameters: {'max_depth': 6, 'learning_rate': 0.14704482688744616, 'subsample': 0.5528682169432497, 'colsample_bytree': 0.8270660524623485, 'reg_lambda': 0.6474844715422483, 'reg_alpha': 9.10042334569283}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:15,072] Trial 13 finished with value: -0.04616975784301758 and parameters: {'max_depth': 6, 'learning_rate': 0.09788025213817328, 'subsample': 0.8420210399676946, 'colsample_bytree': 0.8366282045757272, 'reg_lambda': 1.7717154098274017, 'reg_alpha': 0.017689017466972073}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:15,101] Trial 14 finished with value: -0.6846520900726318 and parameters: {'max_depth': 7, 'learning_rate': 2.046254902754334, 'subsample': 0.692016774184036, 'colsample_bytree': 0.808426662464877, 'reg_lambda': 8.828951983648775, 'reg_alpha': 1.9358644108520364}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:15,211] Trial 8 finished with value: 0.05592459440231323 and parameters: {'max_depth': 4, 'learning_rate': 0.02535008798383009, 'subsample': 0.7578506035994342, 'colsample_bytree': 0.7048075951432697, 'reg_lambda': 0.5802972117453633, 'reg_alpha': 0.10921252099212292}. Best is trial 7 with value: 0.35169994831085205.

Best trial: 7. Best value: 0.3517:  15%|██████▉                                       | 15/100 [00:01<00:07, 11.54it/s]

[I 2026-04-05 15:32:15,328] Trial 9 finished with value: 0.03581362962722778 and parameters: {'max_depth': 8, 'learning_rate': 0.028447433527424834, 'subsample': 0.6076830269613697, 'colsample_bytree': 0.5875974642318118, 'reg_lambda': 0.05773248384304015, 'reg_alpha': 0.07602741853957289}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:15,459] Trial 20 finished with value: 0.2674322724342346 and parameters: {'max_depth': 3, 'learning_rate': 0.5271829711365413, 'subsample': 0.5079272234733103, 'colsample_bytree': 0.5682088024957108, 'reg_lambda': 0.1244550975243824, 'reg_alpha': 9.230737711077895}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:15,480] Trial 15 finished with value: -0.017742395401000977 and parameters: {'max_depth': 8, 'learning_rate': 0.03679162746131933, 'subsample': 0.9813202903414278, 'colsample_bytree': 0.5156316737305227, 'reg_lambda': 0.13552945240298755, 'reg_alpha': 0.01764421210230418}. Best is trial 7 with value: 0.35169994831085205.

Best trial: 7. Best value: 0.3517:  19%|████████▋                                     | 19/100 [00:01<00:06, 11.74it/s]

[I 2026-04-05 15:32:15,609] Trial 21 finished with value: 0.2256491780281067 and parameters: {'max_depth': 3, 'learning_rate': 0.47639789579800995, 'subsample': 0.5398231705738956, 'colsample_bytree': 0.9871606697209295, 'reg_lambda': 0.15558936205237173, 'reg_alpha': 9.064775321649542}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:15,614] Trial 10 finished with value: 0.026833951473236084 and parameters: {'max_depth': 9, 'learning_rate': 0.01315211859300142, 'subsample': 0.5984969463814569, 'colsample_bytree': 0.7118991235296626, 'reg_lambda': 0.027733288288251806, 'reg_alpha': 0.012650515278846326}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:15,787] Trial 23 finished with value: 0.2713721990585327 and parameters: {'max_depth': 3, 'learning_rate': 0.43479109349503403, 'subsample': 0.5057584539356987, 'colsample_bytree': 0.9770190852778181, 'reg_lambda': 0.20505469555350897, 'reg_alpha': 9.600674170806368}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:15,801] Trial 22 finished with value: 0.2825842499732971 and parameters: {'max_depth': 3, 'learning_rate': 0.5156772209207838, 'subsample': 0.5107638842359232, 'colsample_bytree': 0.6291395661421875, 'reg_lambda': 0.25953003343435516, 'reg_alpha': 9.640267417630152}. Best is trial 7 with value: 0.35169994831085205.

Best trial: 7. Best value: 0.3517:  22%|██████████                                    | 22/100 [00:02<00:07, 10.47it/s]

[I 2026-04-05 15:32:16,026] Trial 24 finished with value: 0.3362186551094055 and parameters: {'max_depth': 6, 'learning_rate': 0.29459337193597007, 'subsample': 0.5180737290760414, 'colsample_bytree': 0.6463769389235989, 'reg_lambda': 0.26606516443828754, 'reg_alpha': 9.43266798253741}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:16,069] Trial 27 finished with value: 0.3170706033706665 and parameters: {'max_depth': 6, 'learning_rate': 0.23718462907644844, 'subsample': 0.6273499805882069, 'colsample_bytree': 0.6396202967361946, 'reg_lambda': 0.40016213892846836, 'reg_alpha': 3.977935795831437}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:16,089] Trial 26 finished with value: 0.2757246494293213 and parameters: {'max_depth': 6, 'learning_rate': 0.24311072105180007, 'subsample': 0.630196857566513, 'colsample_bytree': 0.6489170724833272, 'reg_lambda': 0.45369456854519674, 'reg_alpha': 3.362127778251113}. Best is trial 7 with value: 0.35169994831085205.

Best trial: 29. Best value: 0.370828:  26%|███████████▏                               | 26/100 [00:02<00:06, 11.89it/s]

[I 2026-04-05 15:32:16,314] Trial 25 finished with value: 0.33895063400268555 and parameters: {'max_depth': 6, 'learning_rate': 0.3121492595243818, 'subsample': 0.5060362936259045, 'colsample_bytree': 0.6316044157674726, 'reg_lambda': 0.22051430176134135, 'reg_alpha': 7.79024712803972}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:16,335] Trial 28 finished with value: 0.2838526964187622 and parameters: {'max_depth': 6, 'learning_rate': 0.26002291044431486, 'subsample': 0.6362798972126955, 'colsample_bytree': 0.6391888117310824, 'reg_lambda': 0.3980445906745273, 'reg_alpha': 3.499253191068511}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:16,409] Trial 30 finished with value: 0.333576500415802 and parameters: {'max_depth': 5, 'learning_rate': 0.20066488106765484, 'subsample': 0.6378842987252404, 'colsample_bytree': 0.6438043292650075, 'reg_lambda': 0.06342754928241912, 'reg_alpha': 3.52878966206282}. Best is trial 7 with value: 0.35169994831085205.
[I 2026-04-05 15:32:16,447] Trial 29 finished with value: 0.3708280324935913 and parameters: {'max_depth': 5, 'learning_rate': 0.22546970707972405, 'subsample': 0.6525516200399805, 'colsample_bytree': 0.6751519330092054, 'reg_lambda': 0.06370235897783369, 'reg_alpha': 3.9738536850838835}. Best is trial 29 with value: 0.3708280324935913.

Best trial: 29. Best value: 0.370828:  31%|█████████████▎                             | 31/100 [00:02<00:04, 14.14it/s]

[I 2026-04-05 15:32:16,614] Trial 31 finished with value: -0.21183156967163086 and parameters: {'max_depth': 5, 'learning_rate': 1.1033369352551725, 'subsample': 0.5546012960495069, 'colsample_bytree': 0.8673240557338987, 'reg_lambda': 0.0673676668765604, 'reg_alpha': 1.0103047722398544}. Best is trial 29 with value: 0.3708280324935913.
[I 2026-04-05 15:32:16,625] Trial 32 finished with value: 0.13423454761505127 and parameters: {'max_depth': 5, 'learning_rate': 0.9962072841057893, 'subsample': 0.571499809648796, 'colsample_bytree': 0.86568418498761, 'reg_lambda': 0.08041015081911561, 'reg_alpha': 5.50476243922837}. Best is trial 29 with value: 0.3708280324935913.
[I 2026-04-05 15:32:16,699] Trial 33 finished with value: -0.12483024597167969 and parameters: {'max_depth': 5, 'learning_rate': 0.8870644376632201, 'subsample': 0.5602984645149304, 'colsample_bytree': 0.8679949648928923, 'reg_lambda': 0.010622358247867043, 'reg_alpha': 1.3899437224746385}. Best is trial 29 with value: 0.3708280324935913.
[I 2026-04-05 15:32:16,724] Trial 34 finished with value: 0.07700502872467041 and parameters: {'max_depth': 5, 'learning_rate': 0.9577296412004618, 'subsample': 0.5694797566734662, 'colsample_bytree': 0.8958396191644437, 'reg_lambda': 0.07318557659145661, 'reg_alpha': 0.8746886523399144}. Best is trial 29 with value: 0.3708280324935913.

Best trial: 29. Best value: 0.370828:  33%|██████████████▏                            | 33/100 [00:02<00:05, 12.27it/s]

[I 2026-04-05 15:32:16,905] Trial 35 finished with value: -32956.6171875 and parameters: {'max_depth': 10, 'learning_rate': 8.76879030371099, 'subsample': 0.671373223724175, 'colsample_bytree': 0.7594041814576417, 'reg_lambda': 0.01036737255939727, 'reg_alpha': 1.0832812801747285}. Best is trial 29 with value: 0.3708280324935913.
[I 2026-04-05 15:32:16,967] Trial 17 finished with value: 0.2250797152519226 and parameters: {'max_depth': 3, 'learning_rate': 0.013578225917556738, 'subsample': 0.514351306091484, 'colsample_bytree': 0.5586493586602561, 'reg_lambda': 0.08875479185809274, 'reg_alpha': 9.348760415189282}. Best is trial 29 with value: 0.3708280324935913.

Best trial: 29. Best value: 0.370828:  35%|███████████████                            | 35/100 [00:03<00:06,  9.87it/s]

[I 2026-04-05 15:32:17,128] Trial 36 finished with value: 0.27980494499206543 and parameters: {'max_depth': 7, 'learning_rate': 0.06988057123991175, 'subsample': 0.5757207117122228, 'colsample_bytree': 0.7569910944981482, 'reg_lambda': 0.03963031418062807, 'reg_alpha': 1.0962103316397125}. Best is trial 29 with value: 0.3708280324935913.
[I 2026-04-05 15:32:17,282] Trial 39 finished with value: 0.2629576325416565 and parameters: {'max_depth': 7, 'learning_rate': 0.0938552054884341, 'subsample': 0.5305811867181011, 'colsample_bytree': 0.6840029744082429, 'reg_lambda': 0.7223092702721055, 'reg_alpha': 5.433835334436714}. Best is trial 29 with value: 0.3708280324935913.

Best trial: 41. Best value: 0.381033:  37%|███████████████▉                           | 37/100 [00:03<00:06, 10.16it/s]

[I 2026-04-05 15:32:17,443] Trial 40 finished with value: 0.2710733413696289 and parameters: {'max_depth': 7, 'learning_rate': 0.08200968157758748, 'subsample': 0.5352389666642133, 'colsample_bytree': 0.6749175431030308, 'reg_lambda': 0.7510550822456998, 'reg_alpha': 5.590227651548657}. Best is trial 29 with value: 0.3708280324935913.
[I 2026-04-05 15:32:17,460] Trial 37 finished with value: 0.2974473834037781 and parameters: {'max_depth': 7, 'learning_rate': 0.07263944696410551, 'subsample': 0.530867527954831, 'colsample_bytree': 0.6787247265352909, 'reg_lambda': 0.7595405416399814, 'reg_alpha': 6.221012985882446}. Best is trial 29 with value: 0.3708280324935913.
[I 2026-04-05 15:32:17,588] Trial 41 finished with value: 0.3810330629348755 and parameters: {'max_depth': 6, 'learning_rate': 0.15585670170840063, 'subsample': 0.5356698755521361, 'colsample_bytree': 0.6826130325614589, 'reg_lambda': 0.7697565159938479, 'reg_alpha': 5.553630976731083}. Best is trial 41 with value: 0.3810330629348755.

Best trial: 41. Best value: 0.381033:  41%|█████████████████▋                         | 41/100 [00:03<00:05, 11.00it/s]

[I 2026-04-05 15:32:17,689] Trial 38 finished with value: 0.36173731088638306 and parameters: {'max_depth': 7, 'learning_rate': 0.07051311915688431, 'subsample': 0.5276117986814112, 'colsample_bytree': 0.6821084561320433, 'reg_lambda': 0.23935903592563396, 'reg_alpha': 5.787827193172688}. Best is trial 41 with value: 0.3810330629348755.
[I 2026-04-05 15:32:17,778] Trial 44 finished with value: 0.30935752391815186 and parameters: {'max_depth': 6, 'learning_rate': 0.1698490414844511, 'subsample': 0.7992821735874576, 'colsample_bytree': 0.6042540355883297, 'reg_lambda': 0.2273814667845162, 'reg_alpha': 2.6094773614579636}. Best is trial 41 with value: 0.3810330629348755.
[I 2026-04-05 15:32:17,809] Trial 43 finished with value: 0.30753564834594727 and parameters: {'max_depth': 6, 'learning_rate': 0.16964522009719055, 'subsample': 0.7897248605882898, 'colsample_bytree': 0.6091430215022857, 'reg_lambda': 0.23437895370891065, 'reg_alpha': 2.565246042980558}. Best is trial 41 with value: 0.3810330629348755.

Best trial: 42. Best value: 0.444918:  43%|██████████████████▍                        | 43/100 [00:04<00:05, 10.96it/s]

[I 2026-04-05 15:32:17,924] Trial 45 finished with value: 0.06967639923095703 and parameters: {'max_depth': 6, 'learning_rate': 0.131482478096995, 'subsample': 0.8181672401492105, 'colsample_bytree': 0.7913552786936559, 'reg_lambda': 3.0334264791859327, 'reg_alpha': 0.19000426529694234}. Best is trial 41 with value: 0.3810330629348755.
[I 2026-04-05 15:32:17,993] Trial 42 finished with value: 0.44491827487945557 and parameters: {'max_depth': 6, 'learning_rate': 0.1493276579810055, 'subsample': 0.7895087322187747, 'colsample_bytree': 0.6132686235926229, 'reg_lambda': 1.013447482597362, 'reg_alpha': 5.329506578113712}. Best is trial 42 with value: 0.44491827487945557.
[I 2026-04-05 15:32:18,089] Trial 19 finished with value: 0.2773963212966919 and parameters: {'max_depth': 3, 'learning_rate': 0.010875793010908826, 'subsample': 0.5072248647306152, 'colsample_bytree': 0.5064424880481191, 'reg_lambda': 0.0958272832450589, 'reg_alpha': 9.749704509365793}. Best is trial 42 with value: 0.44491827487945557.

Best trial: 42. Best value: 0.444918:  48%|████████████████████▋                      | 48/100 [00:04<00:04, 12.86it/s]

[I 2026-04-05 15:32:18,223] Trial 48 finished with value: 0.03627079725265503 and parameters: {'max_depth': 8, 'learning_rate': 0.044898491268128816, 'subsample': 0.5929248753023993, 'colsample_bytree': 0.7904806754815703, 'reg_lambda': 1.0640106991240132, 'reg_alpha': 0.14258590545012506}. Best is trial 42 with value: 0.44491827487945557.
[I 2026-04-05 15:32:18,247] Trial 18 finished with value: 0.27905547618865967 and parameters: {'max_depth': 5, 'learning_rate': 0.011299291965639167, 'subsample': 0.5257995536884397, 'colsample_bytree': 0.583654707964443, 'reg_lambda': 0.09658603989294416, 'reg_alpha': 9.652568886502621}. Best is trial 42 with value: 0.44491827487945557.
[I 2026-04-05 15:32:18,288] Trial 16 finished with value: 0.3999948501586914 and parameters: {'max_depth': 3, 'learning_rate': 0.011571255879133715, 'subsample': 0.8267619446090472, 'colsample_bytree': 0.9126395398575624, 'reg_lambda': 1.042874213213454, 'reg_alpha': 1.311639641367555}. Best is trial 42 with value: 0.44491827487945557.
[I 2026-04-05 15:32:18,354] Trial 47 finished with value: 0.032052695751190186 and parameters: {'max_depth': 8, 'learning_rate': 0.04518047507176546, 'subsample': 0.6585555886695206, 'colsample_bytree': 0.7896100884168316, 'reg_lambda': 1.0242890343721573, 'reg_alpha': 0.18102400003179728}. Best is trial 42 with value: 0.44491827487945557.

Best trial: 42. Best value: 0.444918:  50%|█████████████████████▌                     | 50/100 [00:04<00:04, 10.55it/s]

[I 2026-04-05 15:32:18,551] Trial 51 finished with value: 0.1731768250465393 and parameters: {'max_depth': 8, 'learning_rate': 0.05278688924596151, 'subsample': 0.7257547335017818, 'colsample_bytree': 0.7190189873769541, 'reg_lambda': 1.3722454440924166, 'reg_alpha': 0.5649035859090171}. Best is trial 42 with value: 0.44491827487945557.
[I 2026-04-05 15:32:18,646] Trial 49 finished with value: 0.2783036231994629 and parameters: {'max_depth': 8, 'learning_rate': 0.037922575683330496, 'subsample': 0.6634313665686462, 'colsample_bytree': 0.7333550639460663, 'reg_lambda': 1.1986767466603905, 'reg_alpha': 6.15431548066846}. Best is trial 42 with value: 0.44491827487945557.
[I 2026-04-05 15:32:18,683] Trial 54 finished with value: 0.09264498949050903 and parameters: {'max_depth': 4, 'learning_rate': 0.04675082230357167, 'subsample': 0.8697824422799647, 'colsample_bytree': 0.727480924646544, 'reg_lambda': 1.25673723728859, 'reg_alpha': 0.38392594295036475}. Best is trial 42 with value: 0.44491827487945557.

Best trial: 42. Best value: 0.444918:  52%|██████████████████████▎                    | 52/100 [00:04<00:04, 11.84it/s]

[I 2026-04-05 15:32:18,754] Trial 53 finished with value: 0.19393199682235718 and parameters: {'max_depth': 7, 'learning_rate': 0.05318723022091812, 'subsample': 0.7376101315420196, 'colsample_bytree': 0.7324116257767475, 'reg_lambda': 1.1491915146398706, 'reg_alpha': 0.6178397620576823}. Best is trial 42 with value: 0.44491827487945557.
[I 2026-04-05 15:32:18,928] Trial 52 finished with value: 0.33615297079086304 and parameters: {'max_depth': 8, 'learning_rate': 0.05421533739255145, 'subsample': 0.7227155726226049, 'colsample_bytree': 0.7299559929608243, 'reg_lambda': 1.1772851703660934, 'reg_alpha': 4.4880850325293755}. Best is trial 42 with value: 0.44491827487945557.

Best trial: 42. Best value: 0.444918:  54%|███████████████████████▏                   | 54/100 [00:04<00:04, 10.97it/s]

[I 2026-04-05 15:32:18,965] Trial 55 finished with value: 0.13773584365844727 and parameters: {'max_depth': 4, 'learning_rate': 0.020622916489889058, 'subsample': 0.7225341480575568, 'colsample_bytree': 0.7375544982479135, 'reg_lambda': 2.5855532430147754, 'reg_alpha': 0.6574103748112724}. Best is trial 42 with value: 0.44491827487945557.
[I 2026-04-05 15:32:18,999] Trial 46 finished with value: 0.3813667893409729 and parameters: {'max_depth': 8, 'learning_rate': 0.04715244891501644, 'subsample': 0.7936615375899746, 'colsample_bytree': 0.7954540227605481, 'reg_lambda': 1.0344492332505584, 'reg_alpha': 2.454207338394729}. Best is trial 42 with value: 0.44491827487945557.

Best trial: 42. Best value: 0.444918:  56%|████████████████████████                   | 56/100 [00:05<00:04,  8.91it/s]

[I 2026-04-05 15:32:19,308] Trial 50 finished with value: 0.38206613063812256 and parameters: {'max_depth': 8, 'learning_rate': 0.044385143008081315, 'subsample': 0.8744448441669571, 'colsample_bytree': 0.5204345994588693, 'reg_lambda': 1.1307191170409532, 'reg_alpha': 4.320458201802355}. Best is trial 42 with value: 0.44491827487945557.
[I 2026-04-05 15:32:19,494] Trial 61 finished with value: 0.3495248556137085 and parameters: {'max_depth': 7, 'learning_rate': 0.11110026633114528, 'subsample': 0.7695655512730601, 'colsample_bytree': 0.6886094882135444, 'reg_lambda': 0.5001180662978734, 'reg_alpha': 1.8365322001251747}. Best is trial 42 with value: 0.44491827487945557.

Best trial: 59. Best value: 0.512601:  59%|█████████████████████████▎                 | 59/100 [00:05<00:06,  6.41it/s]

[I 2026-04-05 15:32:19,845] Trial 58 finished with value: 0.4747546315193176 and parameters: {'max_depth': 4, 'learning_rate': 0.02034238557720223, 'subsample': 0.736529247767778, 'colsample_bytree': 0.949380969949811, 'reg_lambda': 0.5467227098282904, 'reg_alpha': 4.228007278738217}. Best is trial 58 with value: 0.4747546315193176.
[I 2026-04-05 15:32:19,994] Trial 59 finished with value: 0.512601375579834 and parameters: {'max_depth': 4, 'learning_rate': 0.019028941878226076, 'subsample': 0.7668738289980052, 'colsample_bytree': 0.9332263829735903, 'reg_lambda': 2.2041662734626644, 'reg_alpha': 4.6774890079247635}. Best is trial 59 with value: 0.512601375579834.

Best trial: 59. Best value: 0.512601:  60%|█████████████████████████▊                 | 60/100 [00:06<00:06,  6.19it/s]

[I 2026-04-05 15:32:20,175] Trial 56 finished with value: 0.4490435719490051 and parameters: {'max_depth': 4, 'learning_rate': 0.017601829054919114, 'subsample': 0.8931067174942031, 'colsample_bytree': 0.733379670080171, 'reg_lambda': 2.547145088584948, 'reg_alpha': 1.51573173030339}. Best is trial 59 with value: 0.512601375579834.
[I 2026-04-05 15:32:20,256] Trial 60 finished with value: 0.42106014490127563 and parameters: {'max_depth': 4, 'learning_rate': 0.018783694529274236, 'subsample': 0.8912155424690235, 'colsample_bytree': 0.6932727539331225, 'reg_lambda': 2.2347677092268112, 'reg_alpha': 1.6761339616946853}. Best is trial 59 with value: 0.512601375579834.

Best trial: 59. Best value: 0.512601:  62%|██████████████████████████▋                | 62/100 [00:06<00:05,  6.99it/s]

[I 2026-04-05 15:32:20,397] Trial 57 finished with value: 0.4442617893218994 and parameters: {'max_depth': 4, 'learning_rate': 0.01536991642327101, 'subsample': 0.8899984504331574, 'colsample_bytree': 0.9535078242284785, 'reg_lambda': 2.6355955582562944, 'reg_alpha': 1.590849800554474}. Best is trial 59 with value: 0.512601375579834.
[I 2026-04-05 15:32:20,597] Trial 62 finished with value: 0.41708552837371826 and parameters: {'max_depth': 9, 'learning_rate': 0.018126233821811027, 'subsample': 0.9155690548915001, 'colsample_bytree': 0.9286170543286828, 'reg_lambda': 0.5357328370494778, 'reg_alpha': 2.2939266868109125}. Best is trial 59 with value: 0.512601375579834.

Best trial: 59. Best value: 0.512601:  63%|███████████████████████████                | 63/100 [00:06<00:05,  6.41it/s]

[I 2026-04-05 15:32:20,621] Trial 64 finished with value: 0.3671444058418274 and parameters: {'max_depth': 10, 'learning_rate': 0.029929737623307705, 'subsample': 0.9403675458849392, 'colsample_bytree': 0.5233414067922674, 'reg_lambda': 2.105683508796094, 'reg_alpha': 2.568531622778935}. Best is trial 59 with value: 0.512601375579834.

Best trial: 59. Best value: 0.512601:  65%|███████████████████████████▉               | 65/100 [00:06<00:05,  6.05it/s]

[I 2026-04-05 15:32:20,967] Trial 66 finished with value: 0.44980812072753906 and parameters: {'max_depth': 4, 'learning_rate': 0.018942072138836762, 'subsample': 0.924544214285353, 'colsample_bytree': 0.9336558705198923, 'reg_lambda': 2.375009362552811, 'reg_alpha': 2.530779725722316}. Best is trial 59 with value: 0.512601375579834.

Best trial: 59. Best value: 0.512601:  67%|████████████████████████████▊              | 67/100 [00:07<00:05,  5.64it/s]

[I 2026-04-05 15:32:21,257] Trial 67 finished with value: 0.35761553049087524 and parameters: {'max_depth': 4, 'learning_rate': 0.01926591008344465, 'subsample': 0.8974244419741894, 'colsample_bytree': 0.9536762401736103, 'reg_lambda': 3.9912484200844296, 'reg_alpha': 1.3662757500921636}. Best is trial 59 with value: 0.512601375579834.
[I 2026-04-05 15:32:21,387] Trial 65 finished with value: 0.44371336698532104 and parameters: {'max_depth': 9, 'learning_rate': 0.0198300514535134, 'subsample': 0.8936855499022403, 'colsample_bytree': 0.9544222685748108, 'reg_lambda': 2.248130375327556, 'reg_alpha': 2.4781447249012962}. Best is trial 59 with value: 0.512601375579834.

Best trial: 59. Best value: 0.512601:  68%|█████████████████████████████▏             | 68/100 [00:07<00:05,  6.14it/s]

[I 2026-04-05 15:32:21,497] Trial 69 finished with value: 0.40565335750579834 and parameters: {'max_depth': 4, 'learning_rate': 0.018960273725893567, 'subsample': 0.9497988312430066, 'colsample_bytree': 0.9574074074850505, 'reg_lambda': 3.42611544137089, 'reg_alpha': 1.4624001258188772}. Best is trial 59 with value: 0.512601375579834.
[I 2026-04-05 15:32:21,520] Trial 63 finished with value: 0.4173159599304199 and parameters: {'max_depth': 9, 'learning_rate': 0.015947326532395882, 'subsample': 0.9194938338890845, 'colsample_bytree': 0.9467993143892003, 'reg_lambda': 1.9325635604470537, 'reg_alpha': 1.6275020790878005}. Best is trial 59 with value: 0.512601375579834.

Best trial: 59. Best value: 0.512601:  70%|██████████████████████████████             | 70/100 [00:07<00:04,  7.29it/s]

[I 2026-04-05 15:32:21,706] Trial 68 finished with value: 0.4290214776992798 and parameters: {'max_depth': 4, 'learning_rate': 0.018173732728852903, 'subsample': 0.9184324173467618, 'colsample_bytree': 0.9539634087039988, 'reg_lambda': 4.078780597981435, 'reg_alpha': 1.4292149045550617}. Best is trial 59 with value: 0.512601375579834.
[I 2026-04-05 15:32:21,769] Trial 70 finished with value: 0.3955399990081787 and parameters: {'max_depth': 4, 'learning_rate': 0.017450475159854928, 'subsample': 0.9172972503812994, 'colsample_bytree': 0.9573856165422693, 'reg_lambda': 3.910687912215968, 'reg_alpha': 1.5601918408862754}. Best is trial 59 with value: 0.512601375579834.

Best trial: 59. Best value: 0.512601:  72%|██████████████████████████████▉            | 72/100 [00:07<00:03,  7.17it/s]

[I 2026-04-05 15:32:21,994] Trial 71 finished with value: 0.42451828718185425 and parameters: {'max_depth': 4, 'learning_rate': 0.01778219671306848, 'subsample': 0.9240334220354447, 'colsample_bytree': 0.956427654483872, 'reg_lambda': 3.9961461494133768, 'reg_alpha': 1.409150260097085}. Best is trial 59 with value: 0.512601375579834.

Best trial: 59. Best value: 0.512601:  73%|███████████████████████████████▍           | 73/100 [00:08<00:05,  5.31it/s]

[I 2026-04-05 15:32:22,366] Trial 72 finished with value: 0.4218320846557617 and parameters: {'max_depth': 4, 'learning_rate': 0.016867836648785484, 'subsample': 0.9548202665608451, 'colsample_bytree': 0.9551449109811725, 'reg_lambda': 4.124700220689786, 'reg_alpha': 1.490486741586962}. Best is trial 59 with value: 0.512601375579834.

Best trial: 77. Best value: 0.530674:  76%|████████████████████████████████▋          | 76/100 [00:08<00:05,  4.61it/s]

[I 2026-04-05 15:32:22,670] Trial 75 finished with value: 0.5226763486862183 and parameters: {'max_depth': 4, 'learning_rate': 0.025360749124775754, 'subsample': 0.8550911098767218, 'colsample_bytree': 0.9956658972444052, 'reg_lambda': 5.169219411872784, 'reg_alpha': 3.231229658366013}. Best is trial 75 with value: 0.5226763486862183.
[I 2026-04-05 15:32:22,708] Trial 76 finished with value: 0.5076308250427246 and parameters: {'max_depth': 4, 'learning_rate': 0.025073826150338624, 'subsample': 0.852036605881512, 'colsample_bytree': 0.9733820949236632, 'reg_lambda': 4.757024249453321, 'reg_alpha': 3.0853470648212045}. Best is trial 75 with value: 0.5226763486862183.
[I 2026-04-05 15:32:22,726] Trial 77 finished with value: 0.5306735634803772 and parameters: {'max_depth': 3, 'learning_rate': 0.024903939928030024, 'subsample': 0.8544587498340275, 'colsample_bytree': 0.9950705474817999, 'reg_lambda': 6.04308226235523, 'reg_alpha': 3.074755892270261}. Best is trial 77 with value: 0.5306735634803772.
[I 2026-04-05 15:32:22,740] Trial 78 finished with value: 0.5036634206771851 and parameters: {'max_depth': 4, 'learning_rate': 0.025123792801209556, 'subsample': 0.9946396297597826, 'colsample_bytree': 0.9952121699465931, 'reg_lambda': 4.845635686879304, 'reg_alpha': 3.074551118316088}. Best is trial 77 with value: 0.5306735634803772.

Best trial: 79. Best value: 0.546095:  79%|█████████████████████████████████▉         | 79/100 [00:09<00:02,  7.19it/s]

[I 2026-04-05 15:32:23,008] Trial 79 finished with value: 0.5460952520370483 and parameters: {'max_depth': 3, 'learning_rate': 0.025750377881087444, 'subsample': 0.9925241521874311, 'colsample_bytree': 0.9973360357095847, 'reg_lambda': 6.165562822920539, 'reg_alpha': 3.1324780710351594}. Best is trial 79 with value: 0.5460952520370483.
[I 2026-04-05 15:32:23,135] Trial 73 finished with value: 0.49280667304992676 and parameters: {'max_depth': 4, 'learning_rate': 0.014338226144057364, 'subsample': 0.9627146881155074, 'colsample_bytree': 0.9611688204332742, 'reg_lambda': 5.071019427289445, 'reg_alpha': 3.337475009947838}. Best is trial 79 with value: 0.5460952520370483.
[I 2026-04-05 15:32:23,144] Trial 74 finished with value: 0.5116934776306152 and parameters: {'max_depth': 4, 'learning_rate': 0.013981190401677059, 'subsample': 0.9590126195173699, 'colsample_bytree': 0.9480785806668501, 'reg_lambda': 5.0602964506067645, 'reg_alpha': 2.8564504606239898}. Best is trial 79 with value: 0.5460952520370483.

Best trial: 79. Best value: 0.546095:  81%|██████████████████████████████████▊        | 81/100 [00:09<00:02,  7.13it/s]

[I 2026-04-05 15:32:23,425] Trial 80 finished with value: 0.5219374895095825 and parameters: {'max_depth': 3, 'learning_rate': 0.02469228359118285, 'subsample': 0.9800107985952771, 'colsample_bytree': 0.9964176695880378, 'reg_lambda': 5.550234314538598, 'reg_alpha': 2.968862272954118}. Best is trial 79 with value: 0.5460952520370483.

Best trial: 79. Best value: 0.546095:  82%|███████████████████████████████████▎       | 82/100 [00:09<00:03,  5.95it/s]

[I 2026-04-05 15:32:23,713] Trial 81 finished with value: 0.4931918978691101 and parameters: {'max_depth': 3, 'learning_rate': 0.02633774215387558, 'subsample': 0.858762989073588, 'colsample_bytree': 0.9947595354460804, 'reg_lambda': 5.261029105836265, 'reg_alpha': 3.0398675122350043}. Best is trial 79 with value: 0.5460952520370483.
[I 2026-04-05 15:32:23,794] Trial 84 finished with value: 0.5001693964004517 and parameters: {'max_depth': 3, 'learning_rate': 0.025700192957876795, 'subsample': 0.9895318170151903, 'colsample_bytree': 0.9938969896825135, 'reg_lambda': 8.872244917188793, 'reg_alpha': 3.274356220987652}. Best is trial 79 with value: 0.5460952520370483.

Best trial: 82. Best value: 0.547906:  86%|████████████████████████████████████▉      | 86/100 [00:10<00:02,  6.66it/s]

[I 2026-04-05 15:32:24,017] Trial 83 finished with value: 0.5215868353843689 and parameters: {'max_depth': 3, 'learning_rate': 0.025451480283225345, 'subsample': 0.8588445805818125, 'colsample_bytree': 0.9991000631428529, 'reg_lambda': 9.841274330677809, 'reg_alpha': 3.098529222527368}. Best is trial 79 with value: 0.5460952520370483.
[I 2026-04-05 15:32:24,116] Trial 86 finished with value: 0.5198549032211304 and parameters: {'max_depth': 3, 'learning_rate': 0.025424268889579292, 'subsample': 0.9833837129717664, 'colsample_bytree': 0.9953010029435476, 'reg_lambda': 9.852023892600693, 'reg_alpha': 3.243547727580386}. Best is trial 79 with value: 0.5460952520370483.
[I 2026-04-05 15:32:24,120] Trial 82 finished with value: 0.5479058027267456 and parameters: {'max_depth': 3, 'learning_rate': 0.026675152037373005, 'subsample': 0.8436789977167802, 'colsample_bytree': 0.9996129777967127, 'reg_lambda': 8.325076726689748, 'reg_alpha': 3.0858664124139406}. Best is trial 82 with value: 0.5479058027267456.
[I 2026-04-05 15:32:24,178] Trial 85 finished with value: 0.5006240606307983 and parameters: {'max_depth': 3, 'learning_rate': 0.02527677442866901, 'subsample': 0.9993045476265937, 'colsample_bytree': 0.9960988184377472, 'reg_lambda': 9.714885353449356, 'reg_alpha': 3.179662266747836}. Best is trial 82 with value: 0.5479058027267456.

Best trial: 82. Best value: 0.547906:  89%|██████████████████████████████████████▎    | 89/100 [00:10<00:01,  7.97it/s]

[I 2026-04-05 15:32:24,395] Trial 87 finished with value: 0.5046505928039551 and parameters: {'max_depth': 3, 'learning_rate': 0.025343705755248084, 'subsample': 0.9993005449702294, 'colsample_bytree': 0.9953192586719828, 'reg_lambda': 8.963093596924265, 'reg_alpha': 3.4688868055621707}. Best is trial 82 with value: 0.5479058027267456.
[I 2026-04-05 15:32:24,530] Trial 88 finished with value: 0.5121431350708008 and parameters: {'max_depth': 3, 'learning_rate': 0.02527525580926896, 'subsample': 0.9809093813069084, 'colsample_bytree': 0.999951301648138, 'reg_lambda': 9.941459639059548, 'reg_alpha': 3.1022051843427856}. Best is trial 82 with value: 0.5479058027267456.

Best trial: 82. Best value: 0.547906:  90%|██████████████████████████████████████▋    | 90/100 [00:10<00:01,  6.25it/s]

[I 2026-04-05 15:32:24,818] Trial 90 finished with value: 0.43515193462371826 and parameters: {'max_depth': 3, 'learning_rate': 0.0312897622449003, 'subsample': 0.9909909444817663, 'colsample_bytree': 0.9779881267069384, 'reg_lambda': 9.727399187393265, 'reg_alpha': 7.675324440672839}. Best is trial 82 with value: 0.5479058027267456.
[I 2026-04-05 15:32:24,850] Trial 89 finished with value: 0.5289868116378784 and parameters: {'max_depth': 3, 'learning_rate': 0.026969150695081778, 'subsample': 0.9819121596692821, 'colsample_bytree': 0.9969947655522388, 'reg_lambda': 8.638527326804155, 'reg_alpha': 3.18268980743336}. Best is trial 82 with value: 0.5479058027267456.

Best trial: 82. Best value: 0.547906:  92%|███████████████████████████████████████▌   | 92/100 [00:10<00:01,  7.13it/s]

[I 2026-04-05 15:32:25,036] Trial 94 finished with value: 0.4134383201599121 and parameters: {'max_depth': 3, 'learning_rate': 0.03320538948284947, 'subsample': 0.9773015040259383, 'colsample_bytree': 0.9814493302958698, 'reg_lambda': 6.893059475387808, 'reg_alpha': 7.71062447368058}. Best is trial 82 with value: 0.5479058027267456.

Best trial: 82. Best value: 0.547906:  93%|███████████████████████████████████████▉   | 93/100 [00:11<00:01,  5.85it/s]

[I 2026-04-05 15:32:25,324] Trial 92 finished with value: 0.5278145670890808 and parameters: {'max_depth': 3, 'learning_rate': 0.03145701157327496, 'subsample': 0.9765757501501688, 'colsample_bytree': 0.977787378192523, 'reg_lambda': 7.427211941425288, 'reg_alpha': 2.0724146451180836}. Best is trial 82 with value: 0.5479058027267456.
[I 2026-04-05 15:32:25,386] Trial 96 finished with value: 0.47882670164108276 and parameters: {'max_depth': 3, 'learning_rate': 0.0336393708076762, 'subsample': 0.9400138084768216, 'colsample_bytree': 0.9773697177922274, 'reg_lambda': 6.94750891071871, 'reg_alpha': 6.708809849108654}. Best is trial 82 with value: 0.5479058027267456.

Best trial: 82. Best value: 0.547906:  95%|████████████████████████████████████████▊  | 95/100 [00:11<00:00,  6.50it/s]

[I 2026-04-05 15:32:25,575] Trial 98 finished with value: 0.49226653575897217 and parameters: {'max_depth': 3, 'learning_rate': 0.03505491816600592, 'subsample': 0.9748239737439314, 'colsample_bytree': 0.9773317076853837, 'reg_lambda': 6.7992406566373695, 'reg_alpha': 2.00277593483615}. Best is trial 82 with value: 0.5479058027267456.
[I 2026-04-05 15:32:25,630] Trial 97 finished with value: 0.4985840320587158 and parameters: {'max_depth': 3, 'learning_rate': 0.035377779743061735, 'subsample': 0.8311356427358032, 'colsample_bytree': 0.9757847174881805, 'reg_lambda': 5.928509682293866, 'reg_alpha': 2.0799324444313934}. Best is trial 82 with value: 0.5479058027267456.

Best trial: 82. Best value: 0.547906: 100%|██████████████████████████████████████████| 100/100 [00:11<00:00,  8.37it/s]

[I 2026-04-05 15:32:25,890] Trial 95 finished with value: 0.515710175037384 and parameters: {'max_depth': 3, 'learning_rate': 0.012478075408854827, 'subsample': 0.9715027472455198, 'colsample_bytree': 0.9784476332515112, 'reg_lambda': 7.061095965593016, 'reg_alpha': 1.9450237700996809}. Best is trial 82 with value: 0.5479058027267456.
[I 2026-04-05 15:32:25,945] Trial 93 finished with value: 0.4324914813041687 and parameters: {'max_depth': 3, 'learning_rate': 0.0102638711625892, 'subsample': 0.9734386736107682, 'colsample_bytree': 0.9773728815640771, 'reg_lambda': 7.089336936576464, 'reg_alpha': 7.438654914108618}. Best is trial 82 with value: 0.5479058027267456.
[I 2026-04-05 15:32:26,014] Trial 99 finished with value: 0.4915968179702759 and parameters: {'max_depth': 3, 'learning_rate': 0.011987598361689304, 'subsample': 0.9729465426709692, 'colsample_bytree': 0.9697769979486693, 'reg_lambda': 7.430776109446629, 'reg_alpha': 2.0722229995116095}. Best is trial 82 with value: 0.5479058027267456.
[I 2026-04-05 15:32:26,021] Trial 91 finished with value: 0.5127105712890625 and parameters: {'max_depth': 3, 'learning_rate': 0.010095336016302464, 'subsample': 0.9821098801649727, 'colsample_bytree': 0.9761269421667106, 'reg_lambda': 7.169923487116933, 'reg_alpha': 1.988205464620817}. Best is trial 82 with value: 0.5479058027267456.

In [20]:
valid_trials = []
for trial in study.trials:
    if trial.state != optuna.trial.TrialState.COMPLETE:
        continue
    r2_val = trial.user_attrs['r2_val']
    if r2_val > 0.5:
        valid_trials.append(trial)

In [21]:
if len(valid_trials) > 0:
    valid_trials.sort(key=lambda t:t.user_attrs['r2_delta'])

In [22]:
best_trials = valid_trials[:15]

In [23]:
best_trials_df = pd.DataFrame({
    'r2_val':[trial.user_attrs['r2_val'] for trial in best_trials],
    'r2_train':[trial.user_attrs['r2_train'] for trial in best_trials],
    'r2_delta':[trial.user_attrs['r2_delta'] for trial in best_trials],
    'mape_val':[trial.user_attrs['mape_val'] for trial in best_trials]
})

In [24]:
best_trials_df

      r2_val  r2_train  r2_delta  mape_val
0   0.519855  0.724727  0.204872  1.069056
1   0.512601  0.720019  0.207418  0.941005
2   0.528987  0.742944  0.213957  1.061981
3   0.512143  0.727861  0.215718  1.062255
4   0.521937  0.744028  0.222090  1.093129
5   0.500169  0.728887  0.228717  1.074196
6   0.546095  0.776080  0.229984  1.092074
7   0.530674  0.762458  0.231785  1.000961
8   0.547906  0.782956  0.235050  0.979542
9   0.521587  0.764314  0.242727  0.995608
10  0.504651  0.752454  0.247803  1.074163
11  0.500624  0.751572  0.250948  1.095974
12  0.511693  0.801139  0.289446  0.990248
13  0.522676  0.815695  0.293019  0.922446
14  0.503663  0.809028  0.305364  1.005689

In [137]:
params = best_trials[9].params
params['n_estimators'] = 2000
params['objective'] = 'reg:gamma'
params['random_state'] = 42
#params['device'] = 'cuda'
params['early_stopping_rounds'] = 15
params['eval_metric'] = 'mape'
params['enable_categorical'] = True

In [138]:
xgb_regressor = xgb.XGBRegressor(**params)
xgb_regressor.fit(
    X_train, y_train,
    eval_set = [(X_val, y_val)],
    verbose = True
)

[0]	validation_0-mape:3.05749
[1]	validation_0-mape:2.97986
[2]	validation_0-mape:2.90074
[3]	validation_0-mape:2.86854
[4]	validation_0-mape:2.80705
[5]	validation_0-mape:2.76910
[6]	validation_0-mape:2.72971
[7]	validation_0-mape:2.70741
[8]	validation_0-mape:2.67377
[9]	validation_0-mape:2.61581
[10]	validation_0-mape:2.57014
[11]	validation_0-mape:2.54305
[12]	validation_0-mape:2.50467
[13]	validation_0-mape:2.46773
[14]	validation_0-mape:2.39964
[15]	validation_0-mape:2.36442
[16]	validation_0-mape:2.31763
[17]	validation_0-mape:2.29820
[18]	validation_0-mape:2.27423
[19]	validation_0-mape:2.25347
[20]	validation_0-mape:2.22653
[21]	validation_0-mape:2.20927
[22]	validation_0-mape:2.18148
[23]	validation_0-mape:2.16280
[24]	validation_0-mape:2.12223
[25]	validation_0-mape:2.10558
[26]	validation_0-mape:2.09097
[27]	validation_0-mape:2.07232
[28]	validation_0-mape:2.04386
[29]	validation_0-mape:2.02445
[30]	validation_0-mape:2.01109
[31]	validation_0-mape:1.98758
[32]	validation_0-mape:1.97673
[33]	validation_0-mape:1.95790
[34]	validation_0-mape:1.93933
[35]	validation_0-mape:1.91846
[36]	validation_0-mape:1.90595
[37]	validation_0-mape:1.89901
[38]	validation_0-mape:1.87920
[39]	validation_0-mape:1.86358
[40]	validation_0-mape:1.84468
[41]	validation_0-mape:1.83883
[42]	validation_0-mape:1.81567
[43]	validation_0-mape:1.79033
[44]	validation_0-mape:1.78448
[45]	validation_0-mape:1.76785
[46]	validation_0-mape:1.75795
[47]	validation_0-mape:1.73966
[48]	validation_0-mape:1.72567
[49]	validation_0-mape:1.71942
[50]	validation_0-mape:1.69792
[51]	validation_0-mape:1.67756
[52]	validation_0-mape:1.65359
[53]	validation_0-mape:1.63880
[54]	validation_0-mape:1.62829
[55]	validation_0-mape:1.62399
[56]	validation_0-mape:1.61722
[57]	validation_0-mape:1.61067
[58]	validation_0-mape:1.58905
[59]	validation_0-mape:1.57682
[60]	validation_0-mape:1.57384
[61]	validation_0-mape:1.56838
[62]	validation_0-mape:1.55752
[63]	validation_0-mape:1.55022
[64]	validation_0-mape:1.54432
[65]	validation_0-mape:1.54203
[66]	validation_0-mape:1.53282
[67]	validation_0-mape:1.52259
[68]	validation_0-mape:1.51674
[69]	validation_0-mape:1.50531
[70]	validation_0-mape:1.49733
[71]	validation_0-mape:1.49163
[72]	validation_0-mape:1.48434
[73]	validation_0-mape:1.47540
[74]	validation_0-mape:1.45828
[75]	validation_0-mape:1.44782
[76]	validation_0-mape:1.43863
[77]	validation_0-mape:1.43315
[78]	validation_0-mape:1.42757
[79]	validation_0-mape:1.42363
[80]	validation_0-mape:1.41575
[81]	validation_0-mape:1.40903
[82]	validation_0-mape:1.40010
[83]	validation_0-mape:1.39425
[84]	validation_0-mape:1.38525
[85]	validation_0-mape:1.38031
[86]	validation_0-mape:1.37167
[87]	validation_0-mape:1.36439
[88]	validation_0-mape:1.35560
[89]	validation_0-mape:1.34600
[90]	validation_0-mape:1.33553
[91]	validation_0-mape:1.33297
[92]	validation_0-mape:1.32584
[93]	validation_0-mape:1.31952
[94]	validation_0-mape:1.31076
[95]	validation_0-mape:1.30415
[96]	validation_0-mape:1.30039
[97]	validation_0-mape:1.29156
[98]	validation_0-mape:1.28090
[99]	validation_0-mape:1.27600
[100]	validation_0-mape:1.27169
[101]	validation_0-mape:1.26686
[102]	validation_0-mape:1.25969
[103]	validation_0-mape:1.25225
[104]	validation_0-mape:1.24255
[105]	validation_0-mape:1.23825
[106]	validation_0-mape:1.23134
[107]	validation_0-mape:1.22294
[108]	validation_0-mape:1.21799
[109]	validation_0-mape:1.21109
[110]	validation_0-mape:1.20423
[111]	validation_0-mape:1.20097
[112]	validation_0-mape:1.19929
[113]	validation_0-mape:1.19693
[114]	validation_0-mape:1.18863
[115]	validation_0-mape:1.18758
[116]	validation_0-mape:1.18335
[117]	validation_0-mape:1.18258
[118]	validation_0-mape:1.17667
[119]	validation_0-mape:1.17412
[120]	validation_0-mape:1.17275
[121]	validation_0-mape:1.17081
[122]	validation_0-mape:1.17037
[123]	validation_0-mape:1.16929
[124]	validation_0-mape:1.16488
[125]	validation_0-mape:1.16144
[126]	validation_0-mape:1.15967
[127]	validation_0-mape:1.15607
[128]	validation_0-mape:1.15312
[129]	validation_0-mape:1.15272
[130]	validation_0-mape:1.15149
[131]	validation_0-mape:1.14805
[132]	validation_0-mape:1.15010
[133]	validation_0-mape:1.15086
[134]	validation_0-mape:1.14331
[135]	validation_0-mape:1.13981
[136]	validation_0-mape:1.13468
[137]	validation_0-mape:1.13504
[138]	validation_0-mape:1.13259
[139]	validation_0-mape:1.13281
[140]	validation_0-mape:1.12617
[141]	validation_0-mape:1.12880
[142]	validation_0-mape:1.12677
[143]	validation_0-mape:1.12070
[144]	validation_0-mape:1.11815
[145]	validation_0-mape:1.11341
[146]	validation_0-mape:1.11168
[147]	validation_0-mape:1.10689
[148]	validation_0-mape:1.10325
[149]	validation_0-mape:1.10144
[150]	validation_0-mape:1.10295
[151]	validation_0-mape:1.10102
[152]	validation_0-mape:1.09879
[153]	validation_0-mape:1.09319
[154]	validation_0-mape:1.09372
[155]	validation_0-mape:1.09112
[156]	validation_0-mape:1.08545
[157]	validation_0-mape:1.08192
[158]	validation_0-mape:1.08058
[159]	validation_0-mape:1.07926
[160]	validation_0-mape:1.07636
[161]	validation_0-mape:1.07180
[162]	validation_0-mape:1.07010
[163]	validation_0-mape:1.06509
[164]	validation_0-mape:1.06337
[165]	validation_0-mape:1.06059
[166]	validation_0-mape:1.05799
[167]	validation_0-mape:1.05524
[168]	validation_0-mape:1.05609
[169]	validation_0-mape:1.05323
[170]	validation_0-mape:1.04973
[171]	validation_0-mape:1.04834
[172]	validation_0-mape:1.04571
[173]	validation_0-mape:1.04424
[174]	validation_0-mape:1.04386
[175]	validation_0-mape:1.04279
[176]	validation_0-mape:1.04332
[177]	validation_0-mape:1.04174
[178]	validation_0-mape:1.04333
[179]	validation_0-mape:1.04228
[180]	validation_0-mape:1.04063
[181]	validation_0-mape:1.03959
[182]	validation_0-mape:1.03749
[183]	validation_0-mape:1.03264
[184]	validation_0-mape:1.03320
[185]	validation_0-mape:1.03222
[186]	validation_0-mape:1.03183
[187]	validation_0-mape:1.03001
[188]	validation_0-mape:1.02855
[189]	validation_0-mape:1.02732
[190]	validation_0-mape:1.02417
[191]	validation_0-mape:1.02505
[192]	validation_0-mape:1.02529
[193]	validation_0-mape:1.02539
[194]	validation_0-mape:1.02681
[195]	validation_0-mape:1.02314
[196]	validation_0-mape:1.02257
[197]	validation_0-mape:1.02235
[198]	validation_0-mape:1.01751
[199]	validation_0-mape:1.01805
[200]	validation_0-mape:1.02012
[201]	validation_0-mape:1.02073
[202]	validation_0-mape:1.02186
[203]	validation_0-mape:1.02254
[204]	validation_0-mape:1.02188
[205]	validation_0-mape:1.01881
[206]	validation_0-mape:1.02001
[207]	validation_0-mape:1.02065
[208]	validation_0-mape:1.01843
[209]	validation_0-mape:1.01855
[210]	validation_0-mape:1.01905
[211]	validation_0-mape:1.01605
[212]	validation_0-mape:1.01707
[213]	validation_0-mape:1.01790
[214]	validation_0-mape:1.01855
[215]	validation_0-mape:1.01872
[216]	validation_0-mape:1.01827
[217]	validation_0-mape:1.01534
[218]	validation_0-mape:1.01633
[219]	validation_0-mape:1.01534
[220]	validation_0-mape:1.01544
[221]	validation_0-mape:1.01487
[222]	validation_0-mape:1.01354
[223]	validation_0-mape:1.01297
[224]	validation_0-mape:1.01155
[225]	validation_0-mape:1.01118
[226]	validation_0-mape:1.01079
[227]	validation_0-mape:1.01026
[228]	validation_0-mape:1.00985
[229]	validation_0-mape:1.01133
[230]	validation_0-mape:1.01043
[231]	validation_0-mape:1.01160
[232]	validation_0-mape:1.00837
[233]	validation_0-mape:1.00809
[234]	validation_0-mape:1.00501
[235]	validation_0-mape:1.00575
[236]	validation_0-mape:1.00479
[237]	validation_0-mape:1.00402
[238]	validation_0-mape:1.00509
[239]	validation_0-mape:1.00385
[240]	validation_0-mape:1.00459
[241]	validation_0-mape:1.00428
[242]	validation_0-mape:1.00385
[243]	validation_0-mape:1.00288
[244]	validation_0-mape:1.00239
[245]	validation_0-mape:1.00316
[246]	validation_0-mape:1.00223
[247]	validation_0-mape:0.99982
[248]	validation_0-mape:0.99921
[249]	validation_0-mape:0.99956
[250]	validation_0-mape:1.00056
[251]	validation_0-mape:1.00125
[252]	validation_0-mape:0.99959
[253]	validation_0-mape:0.99893
[254]	validation_0-mape:0.99680
[255]	validation_0-mape:0.99673
[256]	validation_0-mape:0.99570
[257]	validation_0-mape:0.99649
[258]	validation_0-mape:0.99690
[259]	validation_0-mape:0.99719
[260]	validation_0-mape:0.99610
[261]	validation_0-mape:0.99561
[262]	validation_0-mape:0.99641
[263]	validation_0-mape:0.99726
[264]	validation_0-mape:0.99744
[265]	validation_0-mape:0.99636
[266]	validation_0-mape:0.99596
[267]	validation_0-mape:0.99684
[268]	validation_0-mape:0.99740
[269]	validation_0-mape:0.99778
[270]	validation_0-mape:0.99942
[271]	validation_0-mape:1.00042
[272]	validation_0-mape:0.99918
[273]	validation_0-mape:0.99897
[274]	validation_0-mape:0.99965
[275]	validation_0-mape:1.00000
[276]	validation_0-mape:1.00119

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9991000631428529, device=None,
             early_stopping_rounds=15, enable_categorical=True,
             eval_metric='mape', feature_types=None, feature_weights=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.025451480283225345,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=2000, n_jobs=None,
             num_parallel_tree=None, ...)

In [139]:
y_train_pred = xgb_regressor.predict(X_train)
y_test_pred = xgb_regressor.predict(X_test)
y_val_pred = xgb_regressor.predict(X_val)

In [140]:
response_train = pd.concat([players_train, pd.Series(y_train_pred, name='Value_pred'), y_train], axis=1)
response_test = pd.concat([players_test, pd.Series(y_test_pred, name='Value_pred'), y_test], axis=1)
response_val = pd.concat([players_val, pd.Series(y_val_pred, name='Value_pred'), y_val], axis=1)

In [141]:
response_train_val = pd.concat([response_train, response_val])
response = pd.concat([response_train_val, response_test])

In [142]:
metrics = pd.DataFrame({
    'MAE':[mae(y_test_pred, y_test), mae(y_train_pred, y_train), mae(y_val_pred, y_val)],
    'RMSE':[rmse(y_test_pred, y_test), rmse(y_train_pred, y_train), rmse(y_val_pred, y_val)],
    'MAPE':[mape(y_test_pred, y_test), mape(y_train_pred, y_train), mape(y_val_pred, y_val)],
    'R2': [r2_score(y_test_pred, y_test), r2_score(y_train_pred, y_train), r2_score(y_val_pred, y_val)]
}, index = ['test', 'train', 'val'])

In [143]:
metrics

            MAE      RMSE      MAPE        R2
test   2.590815  4.189306  0.607201  0.203410
train  2.150496  4.232806  0.388970  0.412158
val    3.213408  5.287226  0.530461 -1.404599

In [106]:
response.sort_values('Value_pred', ascending=False)

,Player,Nation,Pos,Squad,league,Value_pred,Value
84,Gianluigi Donnarumma,ITA,GK,Paris Saint-Germain,FR1,24.282331,40.00
97,Robert Sanchez,ESP,GK,Chelsea,GB1,23.928696,20.00
95,David Raya,ESP,GK,Arsenal,GB1,23.896221,40.00
101,Mile Svilar,SRB,GK,Roma,IT1,22.049604,25.00
158,Lucas Chevalier,FRA,GK,Lille,FR1,21.958185,30.00
30,Marco Carnesecchi,ITA,GK,Atalanta,IT1,21.269358,25.00
25,Alex Meret,ITA,GK,Napoli,IT1,19.649870,18.00
15,Michele Di Gregorio,ITA,GK,Juventus,IT1,19.183144,18.00
150,Anatolii Trubin,UKR,GK,Benfica,PO1,18.487362,28.00
50,Diogo Costa,POR,GK,Porto,PO1,18.429121,40.00
13,Gregor Kobel,SUI,GK,Dortmund,L1,18.412090,40.00
36,Marcin Bulka,POL,GK,Nice,FR1,18.130016,20.00
30,Dean Henderson,ENG,GK,Crystal Palace,GB1,17.642050,20.00
71,Guglielmo Vicario,ITA,GK,Tottenham Hotspur,GB1,17.513462,32.00
105,Djordje Petrovic,SRB,GK,Strasbourg,FR1,17.070055,20.00
33,Giorgi Mamardashvili,GEO,GK,Valencia,ES1,16.414516,30.00
18,Philipp Kohn,SUI,GK,Monaco,FR1,13.838318,5.00
76,Noah Atubolu,GER,GK,Freiburg,L1,13.726696,18.00
9,Bart Verbruggen,NED,GK,Brighton,GB1,13.588380,30.00
108,Matvei Safonov,RUS,GK,Paris Saint-Germain,FR1,12.702682,20.00
10,Ederson,BRA,GK,Manchester City,GB1,12.698682,20.00
28,Zion Suzuki,JPN,GK,Parma,IT1,12.029236,20.00
49,Matz Sels,BEL,GK,Nottingham Forest,GB1,11.882497,7.00
109,Vanja Milinkovic-Savic,SRB,GK,Torino,IT1,11.861890,16.00
148,Andriy Lunin,UKR,GK,Real Madrid,ES1,11.846820,18.00
26,Lucas Perri,BRA,GK,Lyon,FR1,11.820720,10.00
41,Alisson,BRA,GK,Liverpool,GB1,11.814913,20.00
7,Mike Maignan,FRA,GK,Milan,IT1,11.540271,25.00
24,Alex Remiro,ESP,GK,Real Sociedad,ES1,11.442069,18.00
39,Kepa Arrizabalaga,ESP,GK,Bournemouth,GB1,11.338062,10.00
42,Alexander Nubel,GER,GK,Stuttgart,L1,11.284149,12.00
3,Diego Conde,ESP,GK,Villarreal,ES1,10.533263,7.50
12,Jordan Pickford,ENG,GK,Everton,GB1,10.515207,18.00
161,Dominik Greif,SVK,GK,Mallorca,ES1,10.456592,6.00
156,Filip Jorgensen,DEN,GK,Chelsea,GB1,10.386928,18.00
88,Kamil Grabara,POL,GK,Wolfsburg,L1,10.301308,14.00
40,Jan Oblak,SVN,GK,Atlético Madrid,ES1,9.948874,20.00
94,Thibaut Courtois,BEL,GK,Real Madrid,ES1,9.920011,20.00
40,Nick Pope,ENG,GK,Newcastle United,GB1,9.711006,8.00
5,Andre Onana,CMR,GK,Manchester Utd,GB1,9.628385,25.00
21,Guillaume Restes,FRA,GK,Toulouse,FR1,9.589148,20.00
14,Elia Caprile,ITA,GK,Cagliari,IT1,9.520547,9.00
38,Inaki Pena,ESP,GK,Barcelona,ES1,9.518720,8.00
16,Julen Agirrezabala,ESP,GK,Athletic Club,ES1,9.516294,15.00
138,Aaron Ramsdale,ENG,GK,Southampton,GB1,9.186894,16.00
162,Bernd Leno,GER,GK,Fulham,GB1,8.783504,10.00
15,Luiz Lucio Reis Junior,BRA,GK,Villarreal,ES1,8.772828,10.00
18,Antonin Kinsky,CZE,GK,Tottenham Hotspur,GB1,8.736316,15.00
69,Mark Flekken,NED,GK,Brentford,GB1,8.669468,10.00
0,Timon Wellenreuther,GER,GK,Feyenoord,NL1,8.336277,6.00
8,Devis Vasquez,COL,GK,Empoli,IT1,8.334365,2.00
92,Stanislav Agkatsev,RUS,GK,Krasnodar,RU1,8.271859,7.50
145,Gabriel Batista,BRA,GK,Santa Clara,PO1,8.212778,4.00
57,Maduka Okoye,NGA,GK,Udinese,IT1,8.098039,7.50
2,Unai Simon,ESP,GK,Athletic Club,ES1,7.890267,28.00
13,Yahia Fofana,CIV,GK,Angers,FR1,7.855995,7.00
38,Antonio Sivera,ESP,GK,Alavés,ES1,7.368255,6.00
8,Christos Mandas,GRE,GK,Lazio,IT1,7.365190,10.00
37,Yehvann Diouf,SEN,GK,Reims,FR1,7.265798,12.00
42,Lukas Hornicek,CZE,GK,Braga,PO1,7.247459,6.00
5,Mads Hermansen,DEN,GK,Leicester City,GB1,7.206662,15.00
17,Mike Penders,BEL,GK,Genk,BE1,7.032622,12.00
16,Geronimo Rulli,ARG,GK,Marseille,FR1,6.975695,8.00
140,Rome-Jayden Owusu-Oduro,NED,GK,AZ Alkmaar,NL1,6.882261,6.00
117,Razvan Sava,ROU,GK,Udinese,IT1,6.839415,2.50
32,Finn Dahmen,GER,GK,Augsburg,L1,6.794353,9.00
80,Rui Silva,POR,GK,Sporting CP,PO1,6.691882,7.00
27,Jonas Urbig,GER,GK,Bayern Munich,L1,6.687367,12.00
27,Stefano Turati,ITA,GK,Monza,IT1,6.647327,6.50
77,Walter Benitez,ARG,GK,PSV,NL1,6.620862,7.50
7,Kaua Santos,BRA,GK,Eintracht Frankfurt,L1,6.590079,2.50
144,Josep Martinez,ESP,GK,Inter,IT1,6.527311,12.00
25,David Soria,ESP,GK,Getafe,ES1,6.494081,3.00
1,Franco Israel,URU,GK,Sporting CP,PO1,6.279431,5.00
99,Augusto Batalla,ARG,GK,Rayo Vallecano,ES1,6.227569,6.00
29,Federico Ravaglia,ITA,GK,Bologna,IT1,5.956493,1.50
10,Moritz Nicolas,GER,GK,Gladbach,L1,5.833495,5.00
6,Radoslaw Majecki,POL,GK,Monaco,FR1,5.693293,6.00
129,Yevgeni Latyshonok,RUS,GK,Zenit,RU1,5.627761,4.00
11,Filip Stankovic,SRB,GK,Venezia,IT1,5.403800,6.00
4,David de Gea,ESP,GK,Fiorentina,IT1,5.180489,5.00
26,Bruno Varela,CPV,GK,Vitoria Guimarães,PO1,5.139329,2.50
160,Matej Kovar,CZE,GK,Leverkusen,L1,5.131905,5.00
51,Senne Lammens,BEL,GK,Antwerp,BE1,5.122442,9.00
32,Mark Travers,IRL,GK,Bournemouth,GB1,5.080545,4.00
159,Patrick Sequeira,CRC,GK,Casa Pia,PO1,5.064768,4.00
126,Robin Zentner,GER,GK,Mainz 05,L1,5.058188,4.00
91,Nikola Vasilj,BIH,GK,St Pauli,L1,5.005689,3.50
151,Aleksandr Maksimenko,RUS,GK,Spartak Moscow,RU1,4.968637,4.50
149,Robin Roefs,NED,GK,NEC Nijmegen,NL1,4.917217,4.00
22,Nicola Leali,ITA,GK,Genoa,IT1,4.866181,1.50
154,Marc-Andre ter Stegen,GER,GK,Barcelona,ES1,4.826558,12.00
46,Maarten Vandevoordt,BEL,GK,RB Leipzig,L1,4.669674,8.00
1,Michael Zetterer,GER,GK,Werder Bremen,L1,4.569110,4.50
87,Ivan Provedel,ITA,GK,Lazio,IT1,4.562238,3.00
143,Tiago Cardoso,LUX,GK,Gladbach,L1,4.545148,1.50
6,Kaique,BRA,GK,Farense,PO1,4.484214,0.60
40,Gautier Larsonneur,FRA,GK,Saint-Étienne,FR1,4.456981,3.00
16,Jose Sa,POR,GK,Wolves,GB1,4.443011,7.00
12,Andrew,BRA,GK,Gil Vicente FC,PO1,4.381081,4.00
15,Wladimiro Falcone,ITA,GK,Lecce,IT1,4.322251,3.50
20,Brice Samba,FRA,GK,Lens,FR1,4.319763,12.00
47,Karl Jakob Hein,EST,GK,Valladolid,ES1,4.311035,3.00
4,Semuel Pizzignacco,ITA,GK,Monza,IT1,4.306536,0.80
112,Matthieu Epolo,BEL,GK,Standard Liège,BE1,4.305985,4.00
50,Alphonse Areola,FRA,GK,West Ham United,GB1,4.243277,9.00
39,Paulo Gazzaniga,ARG,GK,Girona,ES1,4.052254,2.50
132,Lorenzo Montipo,ITA,GK,Hellas Verona,IT1,4.051449,2.00
72,Sergio Herrera,ESP,GK,Osasuna,ES1,4.047474,3.00
45,Dinko Horkas,CRO,GK,Las Palmas,ES1,3.898417,1.20
38,Arijanet Muric,KVX,GK,Ipswich Town,GB1,3.853829,5.00
26,Nico Mantl,GER,GK,Arouca,PO1,3.795051,1.50
24,Dani Cardenas,ESP,GK,Rayo Vallecano,ES1,3.738195,1.80
4,Stefan Ortega,GER,GK,Manchester City,GB1,3.689901,8.00
23,Timon Weiner,GER,GK,Holstein Kiel,L1,3.662485,1.00
29,Jakub Stolarczyk,POL,GK,Leicester City,GB1,3.646528,1.00
27,Vasilios Barkas,GRE,GK,Utrecht,NL1,3.629866,3.50
7,Sam Johnstone,ENG,GK,Wolves,GB1,3.611458,6.00
10,Yann Sommer,SUI,GK,Inter,IT1,3.610246,4.00
31,Alban Lafont,CIV,GK,Nantes,FR1,3.478871,3.00
14,Alen Sherri,ALB,GK,Cagliari,IT1,3.468442,1.00
3,Christian Walton,ENG,GK,Ipswich Town,GB1,3.468376,1.00
35,Jean Butez,FRA,GK,Como,IT1,3.436694,3.50
23,Manuel Neuer,GER,GK,Bayern Munich,L1,3.340423,4.00
12,Kjetil Haug,NOR,GK,Toulouse,FR1,3.338388,0.60
152,Matheus,BRA,GK,Braga,PO1,3.282260,2.50
47,Evgenii Staver,RUS,GK,Rubin Kazan,RU1,3.238549,1.50
2,Leo Roman,ESP,GK,Mallorca,ES1,3.230000,5.00
20,Ionut Radu,ROU,GK,Venezia,IT1,3.220530,2.50
18,Fabian de Keijzer,NED,GK,Heracles Almelo,NL1,3.164044,1.50
63,Colin Coosemans,BEL,GK,Anderlecht,BE1,3.143396,1.50
9,Martin Delavallee,BEL,GK,Charleroi,BE1,3.027827,1.50
111,Tobe Leysen,BEL,GK,OH Leuven,BE1,3.008698,4.00
19,Florian Muller,GER,GK,Freiburg,L1,2.953744,1.20
33,Vicente Guaita,ESP,GK,Celta Vigo,ES1,2.943818,0.70
131,Leo Kokubo,JPN,GK,Sint-Truiden,BE1,2.918818,3.00
31,Donovan Leon,GUF,GK,Auxerre,FR1,2.908502,1.00
75,Alex Padilla,ESP,GK,Athletic Club,ES1,2.866985,3.00
34,Frederik Ronnow,DEN,GK,Union Berlin,L1,2.826813,3.00
52,Jasper Schendelaar,NED,GK,Zwolle,NL1,2.741574,2.50
127,Nick Olij,NED,GK,Sparta Rotterdam,NL1,2.721755,3.50
17,Bogdan Moskvichev,RUS,GK,Orenburg,RU1,2.698956,0.80
130,Alex Palmer,ENG,GK,Ipswich Town,GB1,2.678109,1.00
37,Nediljko Labrovic,CRO,GK,Augsburg,L1,2.649225,2.50
66,Mattia Perin,ITA,GK,Juventus,IT1,2.638777,2.50
83,Jesus Owono,EQG,GK,Alavés,ES1,2.599717,0.90
2,Vladan Kovacevic,BIH,GK,Sporting CP,PO1,2.577032,3.00
34,Luca Plogmann,GER,GK,Go Ahead Eagles,NL1,2.564879,0.50
32,Cezary Miszta,POL,GK,Rio Ave,PO1,2.544122,3.00
28,Andrey Lunyov,RUS,GK,Dynamo Moscow,RU1,2.539045,1.20
147,Ortwin De Wolf,BEL,GK,Mechelen,BE1,2.462788,1.50
120,Lazar Carevic,MNE,GK,Famalicão,PO1,2.431795,1.50
134,Alvaro Fernandez,ESP,GK,Sevilla,ES1,2.413808,2.00
141,Juan Soriano,ESP,GK,Leganés,ES1,2.320483,1.00
90,Anthony Moris,LUX,GK,Union SG,BE1,2.267892,1.80
121,Emil Audero,IDN,GK,Como,IT1,2.242820,3.20
136,Ricardo Velho,POR,GK,Farense,PO1,2.182849,4.00
1,Ilya Lantratov,RUS,GK,Loko Moscow,RU1,2.180120,2.50
142,Marko Dmitrovic,SRB,GK,Leganés,ES1,2.176057,0.80
115,Mathew Ryan,AUS,GK,Lens,FR1,2.127902,2.50
79,Mohamed Kone,CIV,GK,Charleroi,BE1,2.088247,1.20
11,Remko Pasveer,NED,GK,Ajax,NL1,2.082841,0.15
139,Kevin Trapp,GER,GK,Eintracht Frankfurt,L1,2.082083,2.50
135,Marco Bizot,NED,GK,Brest,FR1,2.072672,3.00
48,Lukasz Skorupski,POL,GK,Bologna,IT1,2.070355,2.50
116,Andreas Jungdal,DEN,GK,Westerlo,BE1,2.067044,1.50
44,Davy Roef,BEL,GK,Gent,BE1,2.038137,2.50
137,Lukas Hradecky,FIN,GK,Leverkusen,L1,2.036513,2.00
33,Alex McCarthy,ENG,GK,Southampton,GB1,2.014287,0.35
34,Lucas Franca,BRA,GK,Nacional,PO1,2.011254,1.00
96,Luca Philipp,GER,GK,Hoffenheim,L1,1.915872,0.75
60,Martin Dubravka,SVK,GK,Newcastle United,GB1,1.915396,1.00
78,Wojciech Szczesny,POL,GK,Barcelona,ES1,1.913648,1.00
31,Andre Ferreira,POR,GK,Valladolid,ES1,1.880560,0.70
22,Rustam Yatimov,TJK,GK,Rostov,RU1,1.845897,1.50
36,Lars Unnerstall,GER,GK,Twente,NL1,1.839355,2.00
157,Simone Scuffet,ITA,GK,Napoli,IT1,1.826908,2.00
23,Peter Gulacsi,HUN,GK,RB Leipzig,L1,1.812288,2.00
53,Jari De Busser,BEL,GK,Go Ahead Eagles,NL1,1.810904,2.00
0,Kewin,BRA,GK,Moreirense,PO1,1.807907,1.00
107,Daniel Bielica,POL,GK,NAC Breda,NL1,1.761520,1.00
3,Simon Mignolet,BEL,GK,Club Brugge,BE1,1.758483,1.20
128,Marius Muller,GER,GK,Wolfsburg,L1,1.698120,1.50
98,Hendrik Van Crombrugge,BEL,GK,Genk,BE1,1.694512,1.70
35,Gavin Bazunu,IRL,GK,Standard Liège,BE1,1.640092,9.00
14,Fraser Forster,ENG,GK,Tottenham Hotspur,GB1,1.607754,1.00
82,Oliver Baumann,GER,GK,Hoffenheim,L1,1.596927,3.00
43,Lukasz Fabianski,POL,GK,West Ham United,GB1,1.573078,0.50
153,Nordin Jackers,BEL,GK,Club Brugge,BE1,1.567830,1.20
56,Maxime Delanghe,BEL,GK,Cercle Brugge,BE1,1.536703,1.20
146,Nikita Kokarev,RUS,GK,FC Khimki,RU1,1.526072,1.50
68,Herve Koffi,BFA,GK,Lens,FR1,1.501590,1.20
24,Marko Ilic,SRB,GK,Kortrijk,BE1,1.485149,0.70
5,Michael Verrips,NED,GK,Dender,BE1,1.418672,0.80
51,Timur Magomedov,RUS,GK,D'mo Makhachkala,RU1,1.414867,0.70
25,Etienne Vaessen,SUR,GK,Groningen,NL1,1.379820,2.00
44,Igor Akinfeev,RUS,GK,CSKA Moscow,RU1,1.364895,1.00
17,Alexander Schwolow,GER,GK,Union Berlin,L1,1.351187,0.50
19,Jesse Joronen,FIN,GK,Venezia,IT1,1.347632,0.50
0,Timo Horn,GER,GK,Bochum,L1,1.345577,0.80
93,Joao Valido,POR,GK,Arouca,PO1,1.333046,0.30
54,Pierluigi Gollini,ITA,GK,Genoa,IT1,1.291020,1.00
59,Ivan Zlobin,RUS,GK,Famalicão,PO1,1.288422,1.50
29,Jonas Omlin,SUI,GK,Gladbach,L1,1.284508,2.50
133,Mattijs Branderhorst,NED,GK,Fortuna Sittard,NL1,1.272828,0.80
28,David Volk,RUS,GK,D'mo Makhachkala,RU1,1.254442,1.20
48,Jeroen Houwen,NED,GK,RKC Waalwijk,NL1,1.252640,0.40
8,Ivan Lomaev,RUS,GK,Samara,RU1,1.252263,1.50
64,Thomas Didillon,FRA,GK,Willem II,NL1,1.248714,0.90
73,Daniil Odoevski,RUS,GK,Rostov,RU1,1.230903,0.80
43,Nordin Bakker,NED,GK,Almere City,NL1,1.212690,0.70
100,Kevin Muller,GER,GK,Heidenheim,L1,1.183138,0.70
39,Marco Silvestri,ITA,GK,Empoli,IT1,1.131649,0.50
61,Ørjan Nyland,NOR,GK,Sevilla,ES1,1.131188,0.90
89,Arthur Desmas,FRA,GK,Le Havre,FR1,1.105626,1.20
35,Adrian,ESP,GK,Real Betis,ES1,1.069919,0.50
114,Patrick Drewes,GER,GK,Bochum,L1,1.046241,0.50
22,Pepe Reina,ESP,GK,Como,IT1,1.040641,0.50
110,Benjamin Lecomte,FRA,GK,Montpellier,FR1,1.037656,1.50
46,Igor Obukhov,RUS,GK,FC Khimki,RU1,1.035842,0.40
65,Warleson,BRA,GK,Cercle Brugge,BE1,1.034295,2.50
62,Jeroen Zoet,NED,GK,AZ Alkmaar,NL1,1.013391,0.30
123,Anton Mitryushkin,RUS,GK,Loko Moscow,RU1,1.011777,1.80
13,Luuk Koopmans,NED,GK,Fortuna Sittard,NL1,0.998330,0.20
122,Patrik Gunnarsson,ISL,GK,Kortrijk,BE1,0.985466,1.00
119,Jasper Cillessen,NED,GK,Las Palmas,ES1,0.982562,0.80
36,Joao Paulo Santos Costa,POR,GK,Estrela,PO1,0.980109,0.80
30,Nikita Medvedev,RUS,GK,Nizhny Novgorod,RU1,0.976904,0.80
6,Patrik Carlgren,SWE,GK,Nantes,FR1,0.968100,0.60
102,Nick Shinton,BEL,GK,Beerschot Wilrijk,BE1,0.928124,0.60
67,Thomas Dahne,GER,GK,Holstein Kiel,L1,0.915626,0.40
106,Igor Leshchuk,RUS,GK,Dynamo Moscow,RU1,0.909744,0.70
11,Davor Matijas,CRO,GK,Beerschot Wilrijk,BE1,0.834571,0.40
86,Steve Mandanda,FRA,GK,Rennes,FR1,0.826091,0.50
41,Nikolai Sysuyev,RUS,GK,Orenburg,RU1,0.795746,0.80
104,Anthony Lopes,POR,GK,Nantes,FR1,0.781516,1.20
21,Andries Noppert,NED,GK,Heerenveen,NL1,0.768310,1.00
20,Cesar,BRA,GK,Boavista,PO1,0.745544,0.30
55,Aleksandr Vasyutin,RUS,GK,FK Akron Tolyatti,RU1,0.743327,0.90
125,Joel Robles,ESP,GK,Estoril,PO1,0.713858,0.50
19,Sergei Volkov,RUS,GK,FK Akron Tolyatti,RU1,0.666037,1.00
103,Mathieu Gorgelin,FRA,GK,Le Havre,FR1,0.614887,0.30
45,Mickey van der Hart,NED,GK,Heerenveen,NL1,0.592125,0.50
155,Tom Vandenberghe,BEL,GK,Gent,BE1,0.552393,0.40
37,Sergei Pesyakov,RUS,GK,Samara,RU1,0.519927,0.30
85,Lucas Pirard,BEL,GK,Kortrijk,BE1,0.515800,0.25
21,Giorgi Shelia,RUS,GK,Akhmat Grozny,RU1,0.503806,0.30
113,Simao Bertelli,BRA,GK,AVS Futebol,PO1,0.497044,0.30
70,Vitali Gudiyev,RUS,GK,Fakel Voronezh,RU1,0.437759,0.40
124,Guillermo Ochoa,MEX,GK,AVS Futebol,PO1,0.410961,0.50
74,Caio Secco,BRA,GK,Moreirense,PO1,0.407579,0.20
9,Sinan Bolat,TUR,GK,Westerlo,BE1,0.366771,0.15
49,Bruno Brigido,BRA,GK,Estrela,PO1,0.365848,0.20
81,Koen Van Langendonck,BEL,GK,Westerlo,BE1,0.357745,0.15
58,Jhonatan,BRA,GK,Rio Ave,PO1,0.345188,0.30
118,Aleksandr Belenov,RUS,GK,Fakel Voronezh,RU1,0.301695,0.10

In [92]:
params = best_trials[8].params
params['n_estimators'] = 2000
params['objective'] = 'reg:gamma'
params['random_state'] = 42
#params['device'] = 'cuda'
params['early_stopping_rounds'] = 15
params['eval_metric'] = 'mape'
params['enable_categorical'] = True

In [93]:
xgb_regressor = xgb.XGBRegressor(**params)
xgb_regressor.fit(
    X_train, y_train,
    eval_set = [(X_val, y_val)],
    verbose = True
)

[0]	validation_0-mape:3.05882
[1]	validation_0-mape:2.98085
[2]	validation_0-mape:2.89314
[3]	validation_0-mape:2.86183
[4]	validation_0-mape:2.79311
[5]	validation_0-mape:2.75633
[6]	validation_0-mape:2.71390
[7]	validation_0-mape:2.67799
[8]	validation_0-mape:2.64064
[9]	validation_0-mape:2.59289
[10]	validation_0-mape:2.54246
[11]	validation_0-mape:2.52138
[12]	validation_0-mape:2.47466
[13]	validation_0-mape:2.43324
[14]	validation_0-mape:2.35934
[15]	validation_0-mape:2.32172
[16]	validation_0-mape:2.29133
[17]	validation_0-mape:2.25983
[18]	validation_0-mape:2.23614
[19]	validation_0-mape:2.21240
[20]	validation_0-mape:2.18930
[21]	validation_0-mape:2.16685
[22]	validation_0-mape:2.13881
[23]	validation_0-mape:2.12363
[24]	validation_0-mape:2.08754
[25]	validation_0-mape:2.06530
[26]	validation_0-mape:2.03631
[27]	validation_0-mape:2.00653
[28]	validation_0-mape:1.97784
[29]	validation_0-mape:1.95832
[30]	validation_0-mape:1.94551
[31]	validation_0-mape:1.91961
[32]	validation_0-mape:1.91283
[33]	validation_0-mape:1.90030
[34]	validation_0-mape:1.88285
[35]	validation_0-mape:1.86149
[36]	validation_0-mape:1.84439
[37]	validation_0-mape:1.84235
[38]	validation_0-mape:1.82555
[39]	validation_0-mape:1.81047
[40]	validation_0-mape:1.79089
[41]	validation_0-mape:1.78088
[42]	validation_0-mape:1.76255
[43]	validation_0-mape:1.73884
[44]	validation_0-mape:1.73663
[45]	validation_0-mape:1.71306
[46]	validation_0-mape:1.69425
[47]	validation_0-mape:1.67787
[48]	validation_0-mape:1.66054
[49]	validation_0-mape:1.65563
[50]	validation_0-mape:1.64067
[51]	validation_0-mape:1.62155
[52]	validation_0-mape:1.60271
[53]	validation_0-mape:1.58720
[54]	validation_0-mape:1.56963
[55]	validation_0-mape:1.55866
[56]	validation_0-mape:1.55234
[57]	validation_0-mape:1.53852
[58]	validation_0-mape:1.52147
[59]	validation_0-mape:1.51055
[60]	validation_0-mape:1.50493
[61]	validation_0-mape:1.48807
[62]	validation_0-mape:1.47729
[63]	validation_0-mape:1.46616
[64]	validation_0-mape:1.46081
[65]	validation_0-mape:1.46124
[66]	validation_0-mape:1.45236
[67]	validation_0-mape:1.43683
[68]	validation_0-mape:1.43128
[69]	validation_0-mape:1.42122
[70]	validation_0-mape:1.41469
[71]	validation_0-mape:1.40952
[72]	validation_0-mape:1.40075
[73]	validation_0-mape:1.39229
[74]	validation_0-mape:1.37636
[75]	validation_0-mape:1.36706
[76]	validation_0-mape:1.35778
[77]	validation_0-mape:1.35329
[78]	validation_0-mape:1.34387
[79]	validation_0-mape:1.34001
[80]	validation_0-mape:1.33111
[81]	validation_0-mape:1.32356
[82]	validation_0-mape:1.31746
[83]	validation_0-mape:1.31125
[84]	validation_0-mape:1.30315
[85]	validation_0-mape:1.29858
[86]	validation_0-mape:1.29023
[87]	validation_0-mape:1.28814
[88]	validation_0-mape:1.27988
[89]	validation_0-mape:1.27361
[90]	validation_0-mape:1.26585
[91]	validation_0-mape:1.26291
[92]	validation_0-mape:1.25554
[93]	validation_0-mape:1.25006
[94]	validation_0-mape:1.24266
[95]	validation_0-mape:1.23692
[96]	validation_0-mape:1.23464
[97]	validation_0-mape:1.23208
[98]	validation_0-mape:1.22504
[99]	validation_0-mape:1.22149
[100]	validation_0-mape:1.21387
[101]	validation_0-mape:1.21036
[102]	validation_0-mape:1.20384
[103]	validation_0-mape:1.19548
[104]	validation_0-mape:1.18742
[105]	validation_0-mape:1.18397
[106]	validation_0-mape:1.17703
[107]	validation_0-mape:1.17706
[108]	validation_0-mape:1.17478
[109]	validation_0-mape:1.16941
[110]	validation_0-mape:1.16336
[111]	validation_0-mape:1.16083
[112]	validation_0-mape:1.15993
[113]	validation_0-mape:1.15566
[114]	validation_0-mape:1.14844
[115]	validation_0-mape:1.14671
[116]	validation_0-mape:1.14228
[117]	validation_0-mape:1.14429
[118]	validation_0-mape:1.13811
[119]	validation_0-mape:1.13601
[120]	validation_0-mape:1.13463
[121]	validation_0-mape:1.13300
[122]	validation_0-mape:1.13234
[123]	validation_0-mape:1.13135
[124]	validation_0-mape:1.12885
[125]	validation_0-mape:1.12657
[126]	validation_0-mape:1.12432
[127]	validation_0-mape:1.12013
[128]	validation_0-mape:1.11836
[129]	validation_0-mape:1.11708
[130]	validation_0-mape:1.11463
[131]	validation_0-mape:1.10934
[132]	validation_0-mape:1.11210
[133]	validation_0-mape:1.11026
[134]	validation_0-mape:1.10973
[135]	validation_0-mape:1.10678
[136]	validation_0-mape:1.10229
[137]	validation_0-mape:1.10277
[138]	validation_0-mape:1.09989
[139]	validation_0-mape:1.09683
[140]	validation_0-mape:1.09036
[141]	validation_0-mape:1.09348
[142]	validation_0-mape:1.09172
[143]	validation_0-mape:1.08469
[144]	validation_0-mape:1.08265
[145]	validation_0-mape:1.08313
[146]	validation_0-mape:1.08194
[147]	validation_0-mape:1.07736
[148]	validation_0-mape:1.07444
[149]	validation_0-mape:1.07317
[150]	validation_0-mape:1.07491
[151]	validation_0-mape:1.07463
[152]	validation_0-mape:1.07247
[153]	validation_0-mape:1.07043
[154]	validation_0-mape:1.07156
[155]	validation_0-mape:1.07313
[156]	validation_0-mape:1.06891
[157]	validation_0-mape:1.06300
[158]	validation_0-mape:1.06095
[159]	validation_0-mape:1.05946
[160]	validation_0-mape:1.06026
[161]	validation_0-mape:1.05808
[162]	validation_0-mape:1.05189
[163]	validation_0-mape:1.04750
[164]	validation_0-mape:1.04607
[165]	validation_0-mape:1.04740
[166]	validation_0-mape:1.04519
[167]	validation_0-mape:1.04252
[168]	validation_0-mape:1.03837
[169]	validation_0-mape:1.03382
[170]	validation_0-mape:1.03035
[171]	validation_0-mape:1.02934
[172]	validation_0-mape:1.02656
[173]	validation_0-mape:1.02494
[174]	validation_0-mape:1.02609
[175]	validation_0-mape:1.02523
[176]	validation_0-mape:1.02773
[177]	validation_0-mape:1.02639
[178]	validation_0-mape:1.02640
[179]	validation_0-mape:1.02458
[180]	validation_0-mape:1.02329
[181]	validation_0-mape:1.02234
[182]	validation_0-mape:1.02184
[183]	validation_0-mape:1.01797
[184]	validation_0-mape:1.01637
[185]	validation_0-mape:1.01622
[186]	validation_0-mape:1.01586
[187]	validation_0-mape:1.01516
[188]	validation_0-mape:1.01356
[189]	validation_0-mape:1.01231
[190]	validation_0-mape:1.01007
[191]	validation_0-mape:1.01075
[192]	validation_0-mape:1.01143
[193]	validation_0-mape:1.01148
[194]	validation_0-mape:1.01102
[195]	validation_0-mape:1.01100
[196]	validation_0-mape:1.01020
[197]	validation_0-mape:1.00998
[198]	validation_0-mape:1.00511
[199]	validation_0-mape:1.00563
[200]	validation_0-mape:1.00747
[201]	validation_0-mape:1.00834
[202]	validation_0-mape:1.00838
[203]	validation_0-mape:1.00789
[204]	validation_0-mape:1.00677
[205]	validation_0-mape:1.00666
[206]	validation_0-mape:1.00767
[207]	validation_0-mape:1.00827
[208]	validation_0-mape:1.00565
[209]	validation_0-mape:1.00585
[210]	validation_0-mape:1.00641
[211]	validation_0-mape:1.00359
[212]	validation_0-mape:1.00429
[213]	validation_0-mape:1.00550
[214]	validation_0-mape:1.00486
[215]	validation_0-mape:1.00366
[216]	validation_0-mape:1.00395
[217]	validation_0-mape:1.00294
[218]	validation_0-mape:1.00251
[219]	validation_0-mape:1.00206
[220]	validation_0-mape:1.00229
[221]	validation_0-mape:1.00076
[222]	validation_0-mape:1.00116
[223]	validation_0-mape:1.00115
[224]	validation_0-mape:1.00018
[225]	validation_0-mape:0.99855
[226]	validation_0-mape:1.00016
[227]	validation_0-mape:1.00000
[228]	validation_0-mape:0.99953
[229]	validation_0-mape:1.00086
[230]	validation_0-mape:1.00025
[231]	validation_0-mape:1.00144
[232]	validation_0-mape:0.99900
[233]	validation_0-mape:0.99906
[234]	validation_0-mape:0.99614
[235]	validation_0-mape:0.99665
[236]	validation_0-mape:0.99678
[237]	validation_0-mape:0.99640
[238]	validation_0-mape:0.99744
[239]	validation_0-mape:0.99669
[240]	validation_0-mape:0.99703
[241]	validation_0-mape:0.99673
[242]	validation_0-mape:0.99528
[243]	validation_0-mape:0.99412
[244]	validation_0-mape:0.99421
[245]	validation_0-mape:0.99292
[246]	validation_0-mape:0.99203
[247]	validation_0-mape:0.98960
[248]	validation_0-mape:0.98905
[249]	validation_0-mape:0.98952
[250]	validation_0-mape:0.99069
[251]	validation_0-mape:0.99077
[252]	validation_0-mape:0.99116
[253]	validation_0-mape:0.98975
[254]	validation_0-mape:0.98783
[255]	validation_0-mape:0.98737
[256]	validation_0-mape:0.98625
[257]	validation_0-mape:0.98638
[258]	validation_0-mape:0.98738
[259]	validation_0-mape:0.98809
[260]	validation_0-mape:0.98739
[261]	validation_0-mape:0.98726
[262]	validation_0-mape:0.98838
[263]	validation_0-mape:0.98804
[264]	validation_0-mape:0.98504
[265]	validation_0-mape:0.98434
[266]	validation_0-mape:0.98368
[267]	validation_0-mape:0.98327
[268]	validation_0-mape:0.98427
[269]	validation_0-mape:0.98461
[270]	validation_0-mape:0.98650
[271]	validation_0-mape:0.98632
[272]	validation_0-mape:0.98517
[273]	validation_0-mape:0.98273
[274]	validation_0-mape:0.98018
[275]	validation_0-mape:0.98224
[276]	validation_0-mape:0.98129
[277]	validation_0-mape:0.97954
[278]	validation_0-mape:0.98031
[279]	validation_0-mape:0.98096
[280]	validation_0-mape:0.97983
[281]	validation_0-mape:0.98083
[282]	validation_0-mape:0.98012
[283]	validation_0-mape:0.97985
[284]	validation_0-mape:0.97967
[285]	validation_0-mape:0.98003
[286]	validation_0-mape:0.97967
[287]	validation_0-mape:0.97972
[288]	validation_0-mape:0.97986
[289]	validation_0-mape:0.98093
[290]	validation_0-mape:0.98053
[291]	validation_0-mape:0.98119
[292]	validation_0-mape:0.98030

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9996129777967127, device=None,
             early_stopping_rounds=15, enable_categorical=True,
             eval_metric='mape', feature_types=None, feature_weights=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.026675152037373005,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=2000, n_jobs=None,
             num_parallel_tree=None, ...)

In [94]:
y_train_pred = xgb_regressor.predict(X_train)
y_test_pred = xgb_regressor.predict(X_test)
y_val_pred = xgb_regressor.predict(X_val)

In [95]:
response_train = pd.concat([players_train, pd.Series(y_train_pred, name='Value_pred'), y_train], axis=1)
response_test = pd.concat([players_test, pd.Series(y_test_pred, name='Value_pred'), y_test], axis=1)
response_val = pd.concat([players_val, pd.Series(y_val_pred, name='Value_pred'), y_val], axis=1)

In [96]:
response_train_val = pd.concat([response_train, response_val])
response = pd.concat([response_train_val, response_test])

In [97]:
metrics = pd.DataFrame({
    'MAE':[mae(y_test_pred, y_test), mae(y_train_pred, y_train), mae(y_val_pred, y_val)],
    'RMSE':[rmse(y_test_pred, y_test), rmse(y_train_pred, y_train), rmse(y_val_pred, y_val)],
    'MAPE':[mape(y_test_pred, y_test), mape(y_train_pred, y_train), mape(y_val_pred, y_val)],
    'R2': [r2_score(y_test_pred, y_test), r2_score(y_train_pred, y_train), r2_score(y_val_pred, y_val)]
}, index = ['test', 'train', 'val'])

In [98]:
metrics

            MAE      RMSE      MAPE        R2
test   2.507381  4.052343  0.601795  0.287945
train  2.066061  4.061953  0.369476  0.491414
val    3.137590  5.139736  0.509731 -1.059596

In [83]:
params = best_trials[7].params
params['n_estimators'] = 2000
params['objective'] = 'reg:gamma'
params['random_state'] = 42
#params['device'] = 'cuda'
params['early_stopping_rounds'] = 15
params['eval_metric'] = 'mape'
params['enable_categorical'] = True

In [84]:
xgb_regressor = xgb.XGBRegressor(**params)
xgb_regressor.fit(
    X_train, y_train,
    eval_set = [(X_val, y_val)],
    verbose = True
)

[0]	validation_0-mape:3.04204
[1]	validation_0-mape:2.95223
[2]	validation_0-mape:2.86233
[3]	validation_0-mape:2.82966
[4]	validation_0-mape:2.76129
[5]	validation_0-mape:2.72205
[6]	validation_0-mape:2.67613
[7]	validation_0-mape:2.65213
[8]	validation_0-mape:2.61583
[9]	validation_0-mape:2.55351
[10]	validation_0-mape:2.50193
[11]	validation_0-mape:2.47575
[12]	validation_0-mape:2.43461
[13]	validation_0-mape:2.39489
[14]	validation_0-mape:2.31783
[15]	validation_0-mape:2.28124
[16]	validation_0-mape:2.24896
[17]	validation_0-mape:2.21941
[18]	validation_0-mape:2.19720
[19]	validation_0-mape:2.17320
[20]	validation_0-mape:2.14579
[21]	validation_0-mape:2.11319
[22]	validation_0-mape:2.08591
[23]	validation_0-mape:2.07089
[24]	validation_0-mape:2.03127
[25]	validation_0-mape:2.01355
[26]	validation_0-mape:1.98550
[27]	validation_0-mape:1.96840
[28]	validation_0-mape:1.93720
[29]	validation_0-mape:1.91359
[30]	validation_0-mape:1.88472
[31]	validation_0-mape:1.86070
[32]	validation_0-mape:1.85233
[33]	validation_0-mape:1.83411
[34]	validation_0-mape:1.81554
[35]	validation_0-mape:1.79704
[36]	validation_0-mape:1.78552
[37]	validation_0-mape:1.78391
[38]	validation_0-mape:1.76233
[39]	validation_0-mape:1.74843
[40]	validation_0-mape:1.72986
[41]	validation_0-mape:1.72062
[42]	validation_0-mape:1.70044
[43]	validation_0-mape:1.67783
[44]	validation_0-mape:1.67231
[45]	validation_0-mape:1.65737
[46]	validation_0-mape:1.65053
[47]	validation_0-mape:1.63554
[48]	validation_0-mape:1.63104
[49]	validation_0-mape:1.62716
[50]	validation_0-mape:1.61069
[51]	validation_0-mape:1.60045
[52]	validation_0-mape:1.58119
[53]	validation_0-mape:1.56729
[54]	validation_0-mape:1.55357
[55]	validation_0-mape:1.53713
[56]	validation_0-mape:1.52479
[57]	validation_0-mape:1.51974
[58]	validation_0-mape:1.50254
[59]	validation_0-mape:1.49124
[60]	validation_0-mape:1.48682
[61]	validation_0-mape:1.48196
[62]	validation_0-mape:1.47213
[63]	validation_0-mape:1.46486
[64]	validation_0-mape:1.45926
[65]	validation_0-mape:1.45973
[66]	validation_0-mape:1.45082
[67]	validation_0-mape:1.43674
[68]	validation_0-mape:1.43054
[69]	validation_0-mape:1.42109
[70]	validation_0-mape:1.41454
[71]	validation_0-mape:1.41313
[72]	validation_0-mape:1.40613
[73]	validation_0-mape:1.39635
[74]	validation_0-mape:1.38105
[75]	validation_0-mape:1.37433
[76]	validation_0-mape:1.36534
[77]	validation_0-mape:1.36106
[78]	validation_0-mape:1.35603
[79]	validation_0-mape:1.35252
[80]	validation_0-mape:1.34384
[81]	validation_0-mape:1.33760
[82]	validation_0-mape:1.33159
[83]	validation_0-mape:1.32506
[84]	validation_0-mape:1.31825
[85]	validation_0-mape:1.31371
[86]	validation_0-mape:1.30571
[87]	validation_0-mape:1.29959
[88]	validation_0-mape:1.29322
[89]	validation_0-mape:1.28575
[90]	validation_0-mape:1.27619
[91]	validation_0-mape:1.27112
[92]	validation_0-mape:1.26427
[93]	validation_0-mape:1.25937
[94]	validation_0-mape:1.25197
[95]	validation_0-mape:1.24678
[96]	validation_0-mape:1.24561
[97]	validation_0-mape:1.24345
[98]	validation_0-mape:1.23600
[99]	validation_0-mape:1.23132
[100]	validation_0-mape:1.22797
[101]	validation_0-mape:1.22370
[102]	validation_0-mape:1.21733
[103]	validation_0-mape:1.21728
[104]	validation_0-mape:1.21255
[105]	validation_0-mape:1.20932
[106]	validation_0-mape:1.20289
[107]	validation_0-mape:1.19403
[108]	validation_0-mape:1.19202
[109]	validation_0-mape:1.18418
[110]	validation_0-mape:1.17954
[111]	validation_0-mape:1.17522
[112]	validation_0-mape:1.17438
[113]	validation_0-mape:1.17027
[114]	validation_0-mape:1.16699
[115]	validation_0-mape:1.16530
[116]	validation_0-mape:1.16216
[117]	validation_0-mape:1.16046
[118]	validation_0-mape:1.15373
[119]	validation_0-mape:1.15129
[120]	validation_0-mape:1.15057
[121]	validation_0-mape:1.14715
[122]	validation_0-mape:1.14739
[123]	validation_0-mape:1.14625
[124]	validation_0-mape:1.14368
[125]	validation_0-mape:1.14126
[126]	validation_0-mape:1.13959
[127]	validation_0-mape:1.13424
[128]	validation_0-mape:1.13232
[129]	validation_0-mape:1.13107
[130]	validation_0-mape:1.12848
[131]	validation_0-mape:1.12578
[132]	validation_0-mape:1.12378
[133]	validation_0-mape:1.12496
[134]	validation_0-mape:1.12431
[135]	validation_0-mape:1.12096
[136]	validation_0-mape:1.11684
[137]	validation_0-mape:1.11768
[138]	validation_0-mape:1.11598
[139]	validation_0-mape:1.11305
[140]	validation_0-mape:1.10680
[141]	validation_0-mape:1.10941
[142]	validation_0-mape:1.10672
[143]	validation_0-mape:1.10001
[144]	validation_0-mape:1.10034
[145]	validation_0-mape:1.09620
[146]	validation_0-mape:1.09527
[147]	validation_0-mape:1.09071
[148]	validation_0-mape:1.08808
[149]	validation_0-mape:1.08673
[150]	validation_0-mape:1.08850
[151]	validation_0-mape:1.08806
[152]	validation_0-mape:1.08830
[153]	validation_0-mape:1.08331
[154]	validation_0-mape:1.08402
[155]	validation_0-mape:1.08178
[156]	validation_0-mape:1.07662
[157]	validation_0-mape:1.07125
[158]	validation_0-mape:1.06917
[159]	validation_0-mape:1.06768
[160]	validation_0-mape:1.06545
[161]	validation_0-mape:1.06556
[162]	validation_0-mape:1.05987
[163]	validation_0-mape:1.05647
[164]	validation_0-mape:1.05467
[165]	validation_0-mape:1.05229
[166]	validation_0-mape:1.05018
[167]	validation_0-mape:1.05045
[168]	validation_0-mape:1.04680
[169]	validation_0-mape:1.04331
[170]	validation_0-mape:1.03991
[171]	validation_0-mape:1.03905
[172]	validation_0-mape:1.03637
[173]	validation_0-mape:1.03520
[174]	validation_0-mape:1.03473
[175]	validation_0-mape:1.03355
[176]	validation_0-mape:1.03585
[177]	validation_0-mape:1.03646
[178]	validation_0-mape:1.03738
[179]	validation_0-mape:1.03663
[180]	validation_0-mape:1.03518
[181]	validation_0-mape:1.03405
[182]	validation_0-mape:1.03287
[183]	validation_0-mape:1.02947
[184]	validation_0-mape:1.03020
[185]	validation_0-mape:1.02934
[186]	validation_0-mape:1.02883
[187]	validation_0-mape:1.02727
[188]	validation_0-mape:1.02579
[189]	validation_0-mape:1.02479
[190]	validation_0-mape:1.02352
[191]	validation_0-mape:1.02439
[192]	validation_0-mape:1.02353
[193]	validation_0-mape:1.02390
[194]	validation_0-mape:1.02471
[195]	validation_0-mape:1.02372
[196]	validation_0-mape:1.02351
[197]	validation_0-mape:1.02381
[198]	validation_0-mape:1.01927
[199]	validation_0-mape:1.01953
[200]	validation_0-mape:1.02199
[201]	validation_0-mape:1.02272
[202]	validation_0-mape:1.02195
[203]	validation_0-mape:1.02233
[204]	validation_0-mape:1.02066
[205]	validation_0-mape:1.01766
[206]	validation_0-mape:1.01890
[207]	validation_0-mape:1.01973
[208]	validation_0-mape:1.01599
[209]	validation_0-mape:1.01479
[210]	validation_0-mape:1.01534
[211]	validation_0-mape:1.01326
[212]	validation_0-mape:1.01395
[213]	validation_0-mape:1.01470
[214]	validation_0-mape:1.01340
[215]	validation_0-mape:1.01270
[216]	validation_0-mape:1.01335
[217]	validation_0-mape:1.01072
[218]	validation_0-mape:1.01079
[219]	validation_0-mape:1.01032
[220]	validation_0-mape:1.01050
[221]	validation_0-mape:1.00986
[222]	validation_0-mape:1.00893
[223]	validation_0-mape:1.01114
[224]	validation_0-mape:1.00987
[225]	validation_0-mape:1.00997
[226]	validation_0-mape:1.01232
[227]	validation_0-mape:1.01302
[228]	validation_0-mape:1.01285
[229]	validation_0-mape:1.01286
[230]	validation_0-mape:1.01264
[231]	validation_0-mape:1.01348
[232]	validation_0-mape:1.01106
[233]	validation_0-mape:1.01081
[234]	validation_0-mape:1.00815
[235]	validation_0-mape:1.00591
[236]	validation_0-mape:1.00500
[237]	validation_0-mape:1.00592
[238]	validation_0-mape:1.00661
[239]	validation_0-mape:1.00583
[240]	validation_0-mape:1.00657
[241]	validation_0-mape:1.00621
[242]	validation_0-mape:1.00608
[243]	validation_0-mape:1.00542
[244]	validation_0-mape:1.00530
[245]	validation_0-mape:1.00431
[246]	validation_0-mape:1.00363
[247]	validation_0-mape:1.00123
[248]	validation_0-mape:1.00096
[249]	validation_0-mape:1.00170
[250]	validation_0-mape:1.00288
[251]	validation_0-mape:1.00280
[252]	validation_0-mape:1.00251
[253]	validation_0-mape:1.00180
[254]	validation_0-mape:1.00312
[255]	validation_0-mape:1.00337
[256]	validation_0-mape:1.00224
[257]	validation_0-mape:1.00257
[258]	validation_0-mape:1.00379
[259]	validation_0-mape:1.00509
[260]	validation_0-mape:1.00423
[261]	validation_0-mape:1.00593
[262]	validation_0-mape:1.00692
[263]	validation_0-mape:1.00513

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9950705474817999, device=None,
             early_stopping_rounds=15, enable_categorical=True,
             eval_metric='mape', feature_types=None, feature_weights=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.024903939928030024,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=2000, n_jobs=None,
             num_parallel_tree=None, ...)

In [85]:
y_train_pred = xgb_regressor.predict(X_train)
y_test_pred = xgb_regressor.predict(X_test)
y_val_pred = xgb_regressor.predict(X_val)

In [86]:
response_train = pd.concat([players_train, pd.Series(y_train_pred, name='Value_pred'), y_train], axis=1)
response_test = pd.concat([players_test, pd.Series(y_test_pred, name='Value_pred'), y_test], axis=1)
response_val = pd.concat([players_val, pd.Series(y_val_pred, name='Value_pred'), y_val], axis=1)

In [87]:
response_train_val = pd.concat([response_train, response_val])
response = pd.concat([response_train_val, response_test])

In [88]:
metrics = pd.DataFrame({
    'MAE':[mae(y_test_pred, y_test), mae(y_train_pred, y_train), mae(y_val_pred, y_val)],
    'RMSE':[rmse(y_test_pred, y_test), rmse(y_train_pred, y_train), rmse(y_val_pred, y_val)],
    'MAPE':[mape(y_test_pred, y_test), mape(y_train_pred, y_train), mape(y_val_pred, y_val)],
    'R2': [r2_score(y_test_pred, y_test), r2_score(y_train_pred, y_train), r2_score(y_val_pred, y_val)]
}, index = ['test', 'train', 'val'])

In [89]:
metrics

            MAE      RMSE      MAPE        R2
test   2.524376  4.110988  0.600594  0.208191
train  2.135694  4.249435  0.382751  0.393346
val    3.202610  5.236773  0.517033 -1.280099

In [91]:
response.sort_values('Value_pred', ascending=False)

,Player,Nation,Pos,Squad,league,Value_pred,Value
84,Gianluigi Donnarumma,ITA,GK,Paris Saint-Germain,FR1,24.914911,40.00
95,David Raya,ESP,GK,Arsenal,GB1,23.349607,40.00
97,Robert Sanchez,ESP,GK,Chelsea,GB1,22.712318,20.00
101,Mile Svilar,SRB,GK,Roma,IT1,21.492401,25.00
30,Marco Carnesecchi,ITA,GK,Atalanta,IT1,21.032005,25.00
158,Lucas Chevalier,FRA,GK,Lille,FR1,20.985502,30.00
150,Anatolii Trubin,UKR,GK,Benfica,PO1,18.694334,28.00
15,Michele Di Gregorio,ITA,GK,Juventus,IT1,18.624432,18.00
25,Alex Meret,ITA,GK,Napoli,IT1,18.524477,18.00
71,Guglielmo Vicario,ITA,GK,Tottenham Hotspur,GB1,18.371302,32.00
13,Gregor Kobel,SUI,GK,Dortmund,L1,18.234850,40.00
50,Diogo Costa,POR,GK,Porto,PO1,18.104662,40.00
30,Dean Henderson,ENG,GK,Crystal Palace,GB1,18.010561,20.00
36,Marcin Bulka,POL,GK,Nice,FR1,17.847702,20.00
105,Djordje Petrovic,SRB,GK,Strasbourg,FR1,16.662989,20.00
33,Giorgi Mamardashvili,GEO,GK,Valencia,ES1,15.976427,30.00
9,Bart Verbruggen,NED,GK,Brighton,GB1,13.784118,30.00
76,Noah Atubolu,GER,GK,Freiburg,L1,13.577298,18.00
18,Philipp Kohn,SUI,GK,Monaco,FR1,13.562403,5.00
10,Ederson,BRA,GK,Manchester City,GB1,13.231292,20.00
108,Matvei Safonov,RUS,GK,Paris Saint-Germain,FR1,12.535390,20.00
28,Zion Suzuki,JPN,GK,Parma,IT1,12.183947,20.00
42,Alexander Nubel,GER,GK,Stuttgart,L1,12.103389,12.00
49,Matz Sels,BEL,GK,Nottingham Forest,GB1,11.781781,7.00
7,Mike Maignan,FRA,GK,Milan,IT1,11.604314,25.00
109,Vanja Milinkovic-Savic,SRB,GK,Torino,IT1,11.483200,16.00
26,Lucas Perri,BRA,GK,Lyon,FR1,11.444438,10.00
148,Andriy Lunin,UKR,GK,Real Madrid,ES1,11.290901,18.00
41,Alisson,BRA,GK,Liverpool,GB1,11.269447,20.00
24,Alex Remiro,ESP,GK,Real Sociedad,ES1,11.238042,18.00
39,Kepa Arrizabalaga,ESP,GK,Bournemouth,GB1,11.188585,10.00
3,Diego Conde,ESP,GK,Villarreal,ES1,11.114616,7.50
88,Kamil Grabara,POL,GK,Wolfsburg,L1,10.580633,14.00
21,Guillaume Restes,FRA,GK,Toulouse,FR1,10.538654,20.00
40,Jan Oblak,SVN,GK,Atlético Madrid,ES1,10.450284,20.00
12,Jordan Pickford,ENG,GK,Everton,GB1,10.252698,18.00
156,Filip Jorgensen,DEN,GK,Chelsea,GB1,10.238630,18.00
161,Dominik Greif,SVK,GK,Mallorca,ES1,10.125911,6.00
94,Thibaut Courtois,BEL,GK,Real Madrid,ES1,9.960508,20.00
14,Elia Caprile,ITA,GK,Cagliari,IT1,9.678090,9.00
5,Andre Onana,CMR,GK,Manchester Utd,GB1,9.491302,25.00
38,Inaki Pena,ESP,GK,Barcelona,ES1,9.464703,8.00
40,Nick Pope,ENG,GK,Newcastle United,GB1,9.217061,8.00
162,Bernd Leno,GER,GK,Fulham,GB1,9.172494,10.00
138,Aaron Ramsdale,ENG,GK,Southampton,GB1,9.077814,16.00
69,Mark Flekken,NED,GK,Brentford,GB1,8.954467,10.00
18,Antonin Kinsky,CZE,GK,Tottenham Hotspur,GB1,8.940006,15.00
16,Julen Agirrezabala,ESP,GK,Athletic Club,ES1,8.870872,15.00
0,Timon Wellenreuther,GER,GK,Feyenoord,NL1,8.564124,6.00
8,Devis Vasquez,COL,GK,Empoli,IT1,8.539422,2.00
92,Stanislav Agkatsev,RUS,GK,Krasnodar,RU1,8.534338,7.50
15,Luiz Lucio Reis Junior,BRA,GK,Villarreal,ES1,8.434030,10.00
2,Unai Simon,ESP,GK,Athletic Club,ES1,8.349472,28.00
57,Maduka Okoye,NGA,GK,Udinese,IT1,8.232037,7.50
13,Yahia Fofana,CIV,GK,Angers,FR1,8.182378,7.00
145,Gabriel Batista,BRA,GK,Santa Clara,PO1,7.976350,4.00
5,Mads Hermansen,DEN,GK,Leicester City,GB1,7.690761,15.00
32,Finn Dahmen,GER,GK,Augsburg,L1,7.285824,9.00
37,Yehvann Diouf,SEN,GK,Reims,FR1,7.280389,12.00
140,Rome-Jayden Owusu-Oduro,NED,GK,AZ Alkmaar,NL1,7.171357,6.00
8,Christos Mandas,GRE,GK,Lazio,IT1,7.161789,10.00
17,Mike Penders,BEL,GK,Genk,BE1,7.128798,12.00
16,Geronimo Rulli,ARG,GK,Marseille,FR1,7.079668,8.00
42,Lukas Hornicek,CZE,GK,Braga,PO1,7.041323,6.00
27,Stefano Turati,ITA,GK,Monza,IT1,6.739197,6.50
38,Antonio Sivera,ESP,GK,Alavés,ES1,6.728873,6.00
27,Jonas Urbig,GER,GK,Bayern Munich,L1,6.695282,12.00
77,Walter Benitez,ARG,GK,PSV,NL1,6.672635,7.50
7,Kaua Santos,BRA,GK,Eintracht Frankfurt,L1,6.521744,2.50
144,Josep Martinez,ESP,GK,Inter,IT1,6.480732,12.00
80,Rui Silva,POR,GK,Sporting CP,PO1,6.473199,7.00
25,David Soria,ESP,GK,Getafe,ES1,6.265567,3.00
117,Razvan Sava,ROU,GK,Udinese,IT1,6.183910,2.50
29,Federico Ravaglia,ITA,GK,Bologna,IT1,6.167813,1.50
99,Augusto Batalla,ARG,GK,Rayo Vallecano,ES1,6.160989,6.00
1,Franco Israel,URU,GK,Sporting CP,PO1,6.114450,5.00
129,Yevgeni Latyshonok,RUS,GK,Zenit,RU1,5.895055,4.00
10,Moritz Nicolas,GER,GK,Gladbach,L1,5.858806,5.00
6,Radoslaw Majecki,POL,GK,Monaco,FR1,5.826414,6.00
51,Senne Lammens,BEL,GK,Antwerp,BE1,5.486142,9.00
26,Bruno Varela,CPV,GK,Vitoria Guimarães,PO1,5.294697,2.50
126,Robin Zentner,GER,GK,Mainz 05,L1,5.252165,4.00
91,Nikola Vasilj,BIH,GK,St Pauli,L1,5.204541,3.50
4,David de Gea,ESP,GK,Fiorentina,IT1,5.098908,5.00
151,Aleksandr Maksimenko,RUS,GK,Spartak Moscow,RU1,5.065381,4.50
160,Matej Kovar,CZE,GK,Leverkusen,L1,5.049731,5.00
87,Ivan Provedel,ITA,GK,Lazio,IT1,4.960971,3.00
22,Nicola Leali,ITA,GK,Genoa,IT1,4.894143,1.50
32,Mark Travers,IRL,GK,Bournemouth,GB1,4.891071,4.00
159,Patrick Sequeira,CRC,GK,Casa Pia,PO1,4.806661,4.00
46,Maarten Vandevoordt,BEL,GK,RB Leipzig,L1,4.786676,8.00
1,Michael Zetterer,GER,GK,Werder Bremen,L1,4.781059,4.50
40,Gautier Larsonneur,FRA,GK,Saint-Étienne,FR1,4.717104,3.00
20,Brice Samba,FRA,GK,Lens,FR1,4.712197,12.00
11,Filip Stankovic,SRB,GK,Venezia,IT1,4.701571,6.00
149,Robin Roefs,NED,GK,NEC Nijmegen,NL1,4.696755,4.00
154,Marc-Andre ter Stegen,GER,GK,Barcelona,ES1,4.662566,12.00
6,Kaique,BRA,GK,Farense,PO1,4.597949,0.60
12,Andrew,BRA,GK,Gil Vicente FC,PO1,4.555238,4.00
112,Matthieu Epolo,BEL,GK,Standard Liège,BE1,4.458429,4.00
16,Jose Sa,POR,GK,Wolves,GB1,4.433014,7.00
143,Tiago Cardoso,LUX,GK,Gladbach,L1,4.373585,1.50
39,Paulo Gazzaniga,ARG,GK,Girona,ES1,4.269880,2.50
47,Karl Jakob Hein,EST,GK,Valladolid,ES1,4.254170,3.00
50,Alphonse Areola,FRA,GK,West Ham United,GB1,4.206527,9.00
4,Semuel Pizzignacco,ITA,GK,Monza,IT1,4.140432,0.80
72,Sergio Herrera,ESP,GK,Osasuna,ES1,4.080315,3.00
15,Wladimiro Falcone,ITA,GK,Lecce,IT1,4.055464,3.50
24,Dani Cardenas,ESP,GK,Rayo Vallecano,ES1,3.999217,1.80
26,Nico Mantl,GER,GK,Arouca,PO1,3.918433,1.50
4,Stefan Ortega,GER,GK,Manchester City,GB1,3.884048,8.00
23,Timon Weiner,GER,GK,Holstein Kiel,L1,3.816026,1.00
14,Alen Sherri,ALB,GK,Cagliari,IT1,3.807224,1.00
38,Arijanet Muric,KVX,GK,Ipswich Town,GB1,3.754607,5.00
132,Lorenzo Montipo,ITA,GK,Hellas Verona,IT1,3.698639,2.00
7,Sam Johnstone,ENG,GK,Wolves,GB1,3.610502,6.00
3,Christian Walton,ENG,GK,Ipswich Town,GB1,3.587688,1.00
10,Yann Sommer,SUI,GK,Inter,IT1,3.557491,4.00
35,Jean Butez,FRA,GK,Como,IT1,3.547050,3.50
27,Vasilios Barkas,GRE,GK,Utrecht,NL1,3.537971,3.50
29,Jakub Stolarczyk,POL,GK,Leicester City,GB1,3.495368,1.00
12,Kjetil Haug,NOR,GK,Toulouse,FR1,3.485457,0.60
45,Dinko Horkas,CRO,GK,Las Palmas,ES1,3.470818,1.20
23,Manuel Neuer,GER,GK,Bayern Munich,L1,3.406074,4.00
33,Vicente Guaita,ESP,GK,Celta Vigo,ES1,3.257954,0.70
2,Leo Roman,ESP,GK,Mallorca,ES1,3.251472,5.00
31,Alban Lafont,CIV,GK,Nantes,FR1,3.242313,3.00
111,Tobe Leysen,BEL,GK,OH Leuven,BE1,3.196465,4.00
152,Matheus,BRA,GK,Braga,PO1,3.177606,2.50
20,Ionut Radu,ROU,GK,Venezia,IT1,3.157693,2.50
9,Martin Delavallee,BEL,GK,Charleroi,BE1,3.083867,1.50
18,Fabian de Keijzer,NED,GK,Heracles Almelo,NL1,3.063069,1.50
47,Evgenii Staver,RUS,GK,Rubin Kazan,RU1,3.035013,1.50
63,Colin Coosemans,BEL,GK,Anderlecht,BE1,2.978895,1.50
131,Leo Kokubo,JPN,GK,Sint-Truiden,BE1,2.975675,3.00
19,Florian Muller,GER,GK,Freiburg,L1,2.930884,1.20
32,Cezary Miszta,POL,GK,Rio Ave,PO1,2.890653,3.00
75,Alex Padilla,ESP,GK,Athletic Club,ES1,2.884054,3.00
34,Frederik Ronnow,DEN,GK,Union Berlin,L1,2.818715,3.00
31,Donovan Leon,GUF,GK,Auxerre,FR1,2.815527,1.00
1,Ilya Lantratov,RUS,GK,Loko Moscow,RU1,2.769343,2.50
17,Bogdan Moskvichev,RUS,GK,Orenburg,RU1,2.759944,0.80
127,Nick Olij,NED,GK,Sparta Rotterdam,NL1,2.736320,3.50
28,Andrey Lunyov,RUS,GK,Dynamo Moscow,RU1,2.673394,1.20
130,Alex Palmer,ENG,GK,Ipswich Town,GB1,2.651824,1.00
37,Nediljko Labrovic,CRO,GK,Augsburg,L1,2.637427,2.50
83,Jesus Owono,EQG,GK,Alavés,ES1,2.635081,0.90
52,Jasper Schendelaar,NED,GK,Zwolle,NL1,2.606302,2.50
90,Anthony Moris,LUX,GK,Union SG,BE1,2.584544,1.80
2,Vladan Kovacevic,BIH,GK,Sporting CP,PO1,2.540433,3.00
147,Ortwin De Wolf,BEL,GK,Mechelen,BE1,2.516860,1.50
34,Luca Plogmann,GER,GK,Go Ahead Eagles,NL1,2.516335,0.50
120,Lazar Carevic,MNE,GK,Famalicão,PO1,2.481152,1.50
66,Mattia Perin,ITA,GK,Juventus,IT1,2.398819,2.50
121,Emil Audero,IDN,GK,Como,IT1,2.341427,3.20
134,Alvaro Fernandez,ESP,GK,Sevilla,ES1,2.325647,2.00
141,Juan Soriano,ESP,GK,Leganés,ES1,2.304487,1.00
136,Ricardo Velho,POR,GK,Farense,PO1,2.233377,4.00
115,Mathew Ryan,AUS,GK,Lens,FR1,2.197137,2.50
142,Marko Dmitrovic,SRB,GK,Leganés,ES1,2.144713,0.80
44,Davy Roef,BEL,GK,Gent,BE1,2.136309,2.50
36,Lars Unnerstall,GER,GK,Twente,NL1,2.077936,2.00
79,Mohamed Kone,CIV,GK,Charleroi,BE1,2.073614,1.20
48,Lukasz Skorupski,POL,GK,Bologna,IT1,2.069085,2.50
11,Remko Pasveer,NED,GK,Ajax,NL1,2.067025,0.15
116,Andreas Jungdal,DEN,GK,Westerlo,BE1,2.066690,1.50
33,Alex McCarthy,ENG,GK,Southampton,GB1,2.025911,0.35
135,Marco Bizot,NED,GK,Brest,FR1,1.994042,3.00
78,Wojciech Szczesny,POL,GK,Barcelona,ES1,1.986680,1.00
137,Lukas Hradecky,FIN,GK,Leverkusen,L1,1.982489,2.00
139,Kevin Trapp,GER,GK,Eintracht Frankfurt,L1,1.915562,2.50
3,Simon Mignolet,BEL,GK,Club Brugge,BE1,1.904304,1.20
157,Simone Scuffet,ITA,GK,Napoli,IT1,1.903367,2.00
96,Luca Philipp,GER,GK,Hoffenheim,L1,1.894046,0.75
23,Peter Gulacsi,HUN,GK,RB Leipzig,L1,1.867675,2.00
31,Andre Ferreira,POR,GK,Valladolid,ES1,1.859954,0.70
60,Martin Dubravka,SVK,GK,Newcastle United,GB1,1.831631,1.00
34,Lucas Franca,BRA,GK,Nacional,PO1,1.795433,1.00
128,Marius Muller,GER,GK,Wolfsburg,L1,1.791417,1.50
53,Jari De Busser,BEL,GK,Go Ahead Eagles,NL1,1.773814,2.00
98,Hendrik Van Crombrugge,BEL,GK,Genk,BE1,1.757697,1.70
0,Kewin,BRA,GK,Moreirense,PO1,1.745620,1.00
107,Daniel Bielica,POL,GK,NAC Breda,NL1,1.686812,1.00
22,Rustam Yatimov,TJK,GK,Rostov,RU1,1.662956,1.50
68,Herve Koffi,BFA,GK,Lens,FR1,1.621029,1.20
82,Oliver Baumann,GER,GK,Hoffenheim,L1,1.592558,3.00
35,Gavin Bazunu,IRL,GK,Standard Liège,BE1,1.572832,9.00
56,Maxime Delanghe,BEL,GK,Cercle Brugge,BE1,1.566817,1.20
24,Marko Ilic,SRB,GK,Kortrijk,BE1,1.542709,0.70
14,Fraser Forster,ENG,GK,Tottenham Hotspur,GB1,1.536953,1.00
43,Lukasz Fabianski,POL,GK,West Ham United,GB1,1.476505,0.50
153,Nordin Jackers,BEL,GK,Club Brugge,BE1,1.449900,1.20
146,Nikita Kokarev,RUS,GK,FC Khimki,RU1,1.436443,1.50
59,Ivan Zlobin,RUS,GK,Famalicão,PO1,1.365346,1.50
5,Michael Verrips,NED,GK,Dender,BE1,1.361245,0.80
44,Igor Akinfeev,RUS,GK,CSKA Moscow,RU1,1.359674,1.00
48,Jeroen Houwen,NED,GK,RKC Waalwijk,NL1,1.323236,0.40
0,Timo Horn,GER,GK,Bochum,L1,1.306189,0.80
25,Etienne Vaessen,SUR,GK,Groningen,NL1,1.303797,2.00
93,Joao Valido,POR,GK,Arouca,PO1,1.294803,0.30
19,Jesse Joronen,FIN,GK,Venezia,IT1,1.283041,0.50
51,Timur Magomedov,RUS,GK,D'mo Makhachkala,RU1,1.280805,0.70
43,Nordin Bakker,NED,GK,Almere City,NL1,1.251302,0.70
54,Pierluigi Gollini,ITA,GK,Genoa,IT1,1.232894,1.00
8,Ivan Lomaev,RUS,GK,Samara,RU1,1.226952,1.50
29,Jonas Omlin,SUI,GK,Gladbach,L1,1.222698,2.50
17,Alexander Schwolow,GER,GK,Union Berlin,L1,1.218238,0.50
133,Mattijs Branderhorst,NED,GK,Fortuna Sittard,NL1,1.187300,0.80
64,Thomas Didillon,FRA,GK,Willem II,NL1,1.182947,0.90
28,David Volk,RUS,GK,D'mo Makhachkala,RU1,1.165348,1.20
100,Kevin Muller,GER,GK,Heidenheim,L1,1.159542,0.70
39,Marco Silvestri,ITA,GK,Empoli,IT1,1.154565,0.50
61,Ørjan Nyland,NOR,GK,Sevilla,ES1,1.149983,0.90
73,Daniil Odoevski,RUS,GK,Rostov,RU1,1.138433,0.80
89,Arthur Desmas,FRA,GK,Le Havre,FR1,1.105131,1.20
35,Adrian,ESP,GK,Real Betis,ES1,1.075775,0.50
22,Pepe Reina,ESP,GK,Como,IT1,1.061038,0.50
123,Anton Mitryushkin,RUS,GK,Loko Moscow,RU1,1.053324,1.80
65,Warleson,BRA,GK,Cercle Brugge,BE1,1.053203,2.50
110,Benjamin Lecomte,FRA,GK,Montpellier,FR1,1.031035,1.50
36,Joao Paulo Santos Costa,POR,GK,Estrela,PO1,1.026965,0.80
114,Patrick Drewes,GER,GK,Bochum,L1,1.013027,0.50
6,Patrik Carlgren,SWE,GK,Nantes,FR1,0.995465,0.60
46,Igor Obukhov,RUS,GK,FC Khimki,RU1,0.979062,0.40
122,Patrik Gunnarsson,ISL,GK,Kortrijk,BE1,0.960089,1.00
13,Luuk Koopmans,NED,GK,Fortuna Sittard,NL1,0.954412,0.20
102,Nick Shinton,BEL,GK,Beerschot Wilrijk,BE1,0.934348,0.60
106,Igor Leshchuk,RUS,GK,Dynamo Moscow,RU1,0.934074,0.70
119,Jasper Cillessen,NED,GK,Las Palmas,ES1,0.929298,0.80
30,Nikita Medvedev,RUS,GK,Nizhny Novgorod,RU1,0.921931,0.80
62,Jeroen Zoet,NED,GK,AZ Alkmaar,NL1,0.910916,0.30
67,Thomas Dahne,GER,GK,Holstein Kiel,L1,0.878747,0.40
86,Steve Mandanda,FRA,GK,Rennes,FR1,0.830397,0.50
41,Nikolai Sysuyev,RUS,GK,Orenburg,RU1,0.785394,0.80
21,Andries Noppert,NED,GK,Heerenveen,NL1,0.766944,1.00
11,Davor Matijas,CRO,GK,Beerschot Wilrijk,BE1,0.763573,0.40
104,Anthony Lopes,POR,GK,Nantes,FR1,0.760775,1.20
55,Aleksandr Vasyutin,RUS,GK,FK Akron Tolyatti,RU1,0.742609,0.90
20,Cesar,BRA,GK,Boavista,PO1,0.702839,0.30
19,Sergei Volkov,RUS,GK,FK Akron Tolyatti,RU1,0.636245,1.00
125,Joel Robles,ESP,GK,Estoril,PO1,0.625796,0.50
103,Mathieu Gorgelin,FRA,GK,Le Havre,FR1,0.586036,0.30
45,Mickey van der Hart,NED,GK,Heerenveen,NL1,0.577295,0.50
37,Sergei Pesyakov,RUS,GK,Samara,RU1,0.530163,0.30
155,Tom Vandenberghe,BEL,GK,Gent,BE1,0.528821,0.40
85,Lucas Pirard,BEL,GK,Kortrijk,BE1,0.515725,0.25
21,Giorgi Shelia,RUS,GK,Akhmat Grozny,RU1,0.496976,0.30
113,Simao Bertelli,BRA,GK,AVS Futebol,PO1,0.442026,0.30
124,Guillermo Ochoa,MEX,GK,AVS Futebol,PO1,0.432256,0.50
70,Vitali Gudiyev,RUS,GK,Fakel Voronezh,RU1,0.390954,0.40
74,Caio Secco,BRA,GK,Moreirense,PO1,0.375311,0.20
49,Bruno Brigido,BRA,GK,Estrela,PO1,0.348789,0.20
9,Sinan Bolat,TUR,GK,Westerlo,BE1,0.345085,0.15
81,Koen Van Langendonck,BEL,GK,Westerlo,BE1,0.338519,0.15
58,Jhonatan,BRA,GK,Rio Ave,PO1,0.329155,0.30
118,Aleksandr Belenov,RUS,GK,Fakel Voronezh,RU1,0.277744,0.10